### ISSUE TITLE
Drug index: Scope out and define role of small molecules in Open Targets

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#10]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/76)

The plan is to expand Drug to an entity in the Open Targets platform.
- [x] Meet with ChEMBL to discuss our issues & questions
- [x] What do we gain by making Drug an entity?
- [x] Definition of drug entity fields and connections
- [x] Define user perspective, ie., what additional information will they get
- [x] Definition of terms with ChEMBL (drugs with and without targets, chemical probes etc.)
- [x] Identify data that needs to be pulled in
- [x] Compare PubChem and DrugBank with ChEMBL. Has ChEMBL analysed differential coverage of the databases?
- [x] Look at licensing for data sources
- [x] Define steps for implementation

Also see [here](https://github.com/opentargets/data_pipeline/issues/233).

---

@MichaelaEBI commented on [Thu Apr 05 2018](https://github.com/opentargets/data_release/issues/76#issuecomment-378889250)

**Update posted on Slack on March 29, 2018:**
I thought it would be good to update everyone on where we are at with the Drug entity. So here we go: @mkarmona, @ckong and I sat together and looked at it from the back end. @ckong and I also met with @dunham to discuss requirements for the drug entity. We all agreed that there is not need to reinvent the wheel, so we will work with ChEMBL to find out more about their data structure related to drugs and to see what other data we can get from them. For example, we can probably increase our coverage by including drug-target and drug-disease pairs from ChEMBL on the target and disease pages in addition to the drug-disease-target triplets we currently get as evidence. They are also looking into annotating more targets because their initial efforts focused on 4 main target classes. We have assembled a list of questions for ChEMBL and they are happy to answer them and to meet with us to help define specs for the drug entity in our platform. We shared this document with them - if you have any further questions or comments, feel free to add them or comment in the document or send @ckong or myself a message and we'll include it in the document. https://docs.google.com/document/d/1OybXEkESjKp46bprAJBy2xXGONKnXGxM5F1NsvlYVC8/edit#heading=h.jn9v843k5njf

---

@MichaelaEBI commented on [Thu Apr 19 2018](https://github.com/opentargets/data_release/issues/76#issuecomment-382675242)

**Update on Drug Entity April 19, 2018:**

- Anna presented at the OT lab meeting yesterday, she will be in touch shortly to arrange a meeting so that we can work through our [drug entity-related document](https://docs.google.com/document/d/1OybXEkESjKp46bprAJBy2xXGONKnXGxM5F1NsvlYVC8/edit#).

**Comment by MichaelaEBI** [comment]
DrugBank data is not straight forward. Below are a few findings when looking at a set of diseases that was listed in an email May 7, 2019:

- **Autism**:  29 drug - 59 target pairs in Phase IV (449 entries), Phase III (48), Phase II (99), Phase I (6) and Phase 0 (2) projects, https://www.targetvalidation.org/disease/EFO_0003758 (see drugs tab)
a) _A search in DrugBank provides information on[ 14 drugs for autism](https://www.drugbank.ca/unearth/q?utf8=✓&searcher=drugs&query=autism&approved=1&investigational=1&us=0&ca=0&eu=0&commit=Apply+Filter)_
b) _The Autistic disorder profile in DrugBank lists only [one approved drug](https://www.drugbank.ca/indications/DBCOND0006161#drugs) & [~58 drugs in clinical trials](https://www.drugbank.ca/indications/DBCOND0006161#drug-trials) - 28 of the drugs come from this one [clinical trial](https://clinicaltrials.gov/ct2/show/NCT01431326)_

- **Alzheimer's Disease**: 128 drug - 146 target pairs in Phase IV (260), Phase III (225), Phase II (223), Phase I (255), Phase 0 (5), https://www.targetvalidation.org/disease/EFO_0000249
a) _A search in DrugBank provides a list of [1167(!) approved and investigational drugs](https://www.drugbank.ca/unearth/q?utf8=✓&searcher=drugs&query=Alzheimer%27s+Disease&approved=1&investigational=1&us=0&ca=0&eu=0&commit=Apply+Filter)_
b) _The Alzheimer's Disease profile in DrugBank lists [7 approved drugs](https://www.drugbank.ca/indications/DBCOND0049114#drugs) and [465 entries for clinical trials](https://www.drugbank.ca/indications/DBCOND0049114#drug-trials)_

- **Amyotropic lateral sclerosis**: 47 drug - 97 target pairs in Phase IV (20), Phase III (59), Phase II (223), Phase I (47), Phase 0 (5), https://www.targetvalidation.org/disease/EFO_0000253
_A search in DrugBank lists [92 investigational and approved drugs](https://www.drugbank.ca/unearth/q?utf8=✓&searcher=drugs&query=amyotrphic+lateral+sclerosis&approved=1&investigational=1&us=0&ca=0&eu=0&commit=Apply+Filter)_

- **Down syndrome**: 5 drug - 12 target pairs in Phase IV (7), Phase III (4), Phase II (3), Phase I (3); https://www.targetvalidation.org/disease/EFO_0001064 
_ A search in DrugBank lists [682(!) approved and investigational drugs](https://www.drugbank.ca/unearth/q?utf8=✓&searcher=drugs&query=down+syndrome&approved=1&investigational=1&us=0&ca=0&eu=0&commit=Apply+Filter)_

- **Fragile X Syndrome**: 15 drug - 95 target pairs in Phase IV (11), Phase III (29), Phase II (136), Phase I (5), https://www.targetvalidation.org/disease/Orphanet_908 
_A seach for Fragile X Syndrome in DrugBank yields [769 approved and investigational drugs](https://www.drugbank.ca/unearth/q?utf8=✓&searcher=drugs&query=Fragile+X+Syndrome&approved=1&investigational=1&us=0&ca=0&eu=0&commit=Apply+Filter)_

- **Huntington Disease**: 15 drug - 37 target pairs in Phase IV (10), Phase III (19), Phase II (20), Phase I (8), https://www.targetvalidation.org/disease/Orphanet_399
_A search in DrugBank yields [1166 approved and investigational drugs](https://www.drugbank.ca/unearth/q?utf8=✓&searcher=drugs&query=huntington%27s+disease&approved=1&investigational=1&us=0&ca=0&eu=0&commit=Apply+Filter)_

**Comment by MichaelaEBI** [comment]
For ChEMBL-DrugBank comparison, drug indication pairs need to be compared if possible. This will be incomplete/hard because not all compound IDs have been mapped and DrugBank diseases are not mapped to EFO IDs, they are comments.

**Comment by MichaelaEBI** [comment]
This ticket has been superseded by other tickets on drug index work.
