### ISSUE TITLE
Integrate tractability from new API into widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1003]
In the MVP branch, we display the tractability heat map for both small molecule and antibody modalities. 

However, in the 20.04 release, we introduced a new heat map with clinical precedence data for other modalities along - see #882 for further details and see the [MC2R target profile page](https://www.targetvalidation.org/target/ENSG00000185231?view=sec:tractability) for an example in production (Angular app).

Note: this ticket is awaiting confirmation that the data is now exposed by the new API as data has already been processed in ETL pipeline (see #989)

**Comment by fedde-s** [comment]
I've started looking into this.

**Comment by fedde-s** [comment]
Presented opentargets/platform-app#138 for review.

**Comment by andrewhercules** [comment]
Thanks @fedde-s - I have assigned the PR to @mirandaio to review and merge into `alpha`

**Comment by fedde-s** [comment]
The implementation has been merged to `alpha`.
