### ISSUE TITLE
Integrate Gene Ontology from new API into widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1004]
The Gene Ontology data shown on the target profile page is available from the [new GraphQL API](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser).

For more information on the Gene Ontology data structure, please see the [schema](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/schema) (note: search for `GeneOntology`) or use the following query in the [browser](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser):

```
query targetq {
  target(ensemblId: "ENSG00000091831") {
    id
    approvedSymbol
    geneOntology {
      id
      term
      evidence {
        id
      }
    }
  }
}
```

**Comment by fedde-s** [comment]
We (@forus and I) are looking into this now.

**Comment by fedde-s** [comment]
The schema for the new API does not expose the **category** field of Gene Ontology terms, i.e. whether it's a Biological Process, a Cellular Component or a Molecular Function. This is one of the three columns in the table.

Additionally, targets do not expose fields like **summaries → geneOntology → molecularFunctionTermsCount**, to display the counts of these three categories in the summary view. See this screenshot of the ‘old’ version of the rewrite:
![Screenshot of the Gene Ontology summary component](https://user-images.githubusercontent.com/4929431/80983907-6eb13080-8e2d-11ea-93cc-1b7ba1c557fd.png)

**Comment by fedde-s** [comment]
@andrewhercules, should we look into adjusting the Scala backend, or contact someone else?

**Comment by fedde-s** [comment]
The fields were calculated in [the old GraphQL backend](https://github.com/opentargets/platform-api/blob/8d773f3dae00ea89fb9524d179894c4031dda618/src/public/apis/dataloaders.js#L293) based on a prefix of the **term** field, which comes verbatim from Elasticsearch.

Theoretically we could calculate the counts in the frontend, but that would involve loading all rows there without any paging.

**Comment by andrewhercules** [comment]
@fedde-s thanks for the note - I will investigate and speak with the team tomorrow about the different approach

**Comment by fedde-s** [comment]
The opposite approach would involve the least amount of data transfer: calculating the counts in Elasticsearch. But from the top of my head I can't recall whether Elasticsearch aggregations support matching on prefixes like that.

**Comment by fedde-s** [comment]
Even a part of the data pipeline [is aware of these prefixes](https://github.com/opentargets/data_pipeline/blob/20.04.3/mrtarget/common/EvidenceString.py#L410), but the data pipeline does not introduce them: [it reads them from **mrtarget.data.*.yml → uniprot-uri:**](https://github.com/opentargets/data_pipeline/blob/20.04.3/mrtarget/plugins/gene/uniprot.py#L74)

**Comment by andrewhercules** [comment]
To build in flexibility to the summary widgets, it can either display pre-aggregated counts from the GraphQL API or counts based on front-end calculations.

Because all of the Gene Ontology data is loaded at once with no server-side pagination or batch loading, the front-end can calculate and display counts. 

For the Gene Ontology widget, @fedde-s, could you please:

1. Display the length of the array of terms (e.g. `83 terms in total`)?
2. Drop the second row with `21 MF • 49 BP • 13 CC` as the API will not return these counts?

And in terms of the category, I will include this in my list of the target endpoint data that needs to be added or updated by @mkarmona and will ask if we can parse the GO term for `C:`, `P:`, or `F:` and assign the correct category based on the table below:

Letter in GO term | GO category|
|:--|:--|
| C | Cellular component |
| P  | Biological process |
| F | Molecular function |

**Comment by fedde-s** [comment]
For reference, I found [a UniprotKB XML schema](https://www.uniprot.org/docs/uniprot.xsd) that seems to say that the type of the `dbReference` element is in some contexts “Equivalent to the flat file DR-line”, and [a UniprotKB flat file manual](https://web.expasy.org/docs/userman.html#DR_line) that refers to the same “1-letter abbreviation for one of the 3 ontology aspects” on that line.

**Comment by andrewhercules** [comment]
@fedde-s and @forus could you please create a mapping function, similar to what is done in the [Angular app](https://github.com/opentargets/webapp/blob/51cca4c6083dc362010787e22a01152cb8639351/app/src/components/multiple-targets/multiple-targets-go-summary-directive.js#L3) and use it to generate the categories?

I looked into the relevant sections of the pipeline and our target index does not include the category label - not sure why - but I don't want to delay any further work for the alpha MVP project. Miguel will investigate after he pushes the remaining target data from the ETL pipeline to the GraphQL API (e.g. pathways, protein info, mouse phenotypes, etc.).

**Comment by fedde-s** [comment]
Will do, thanks!

> our target index does not include the category label

I don't think it ever has—the mapping was inferred by the old GraphQL backend as I explained in [this comment](https://github.com/opentargets/platform/issues/1004#issuecomment-623566462) on Monday, but also known to a part of the data pipeline, as I found in [this one](https://github.com/opentargets/platform/issues/1004#issuecomment-623593894).

**Comment by fedde-s** [comment]
ah, or do you mean it does not include the prefix?

**Comment by andrewhercules** [comment]
Sorry, my apologies but I posted the wrong link to the mapping file used in the batch search - which actually has different prefixes.

Ideally, could we create a mapping file like the one used in the [GO plugin ](https://github.com/opentargets/webapp/blob/51cca4c6083dc362010787e22a01152cb8639351/app/plugins/gene-ontology/gene-ontology-directive.js). So it could take the label returned by the API (e.g. `"P:cellular response to drug"`) and use the `F:`, `C:`, or `P:` prefix to assign the category?

**Comment by fedde-s** [comment]
Presented pull request opentargets/platform-app#137 for review.

**Comment by fedde-s** [comment]
opentargets/platform-app#137 has been merged into `alpha`.
