### ISSUE TITLE
Review yarn version and lockfile PRs on platform-app

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1005]
@fedde-s has created two PRs in the [platform-app](https://github.com/opentargets/platform-app) repo:

- Update lockfile to pinned version of prettier: opentargets/platform-app#133
- Pin and document what version of yarn to use: opentargets/platform-app#132

@javfg I have assigned both PRs to you for review and merging as you made updates to the libraries and can confirm that these changes won't cause any upstream issues.

**Comment by javfg** [comment]
Working on it!

**Comment by andrewhercules** [comment]
Ticket closed as both PRs merged in `alpha`
