### ISSUE TITLE
phenotype must come as a list of ids

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1007]
Currently looks like this
```
          "phenotypes" : {
            "rows" : [
              {
                "url" : "http://purl.obolibrary.org/obo/HP_0000035",
                "name" : "Abnormality of the testis",
                "disease" : "HP_0000035"
              },
              {
                "url" : "http://purl.obolibrary.org/obo/HP_0000037",
                "name" : "Male pseudohermaphroditism",
                "disease" : "HP_0000037"
              },
              {
                "url" : "http://purl.obolibrary.org/obo/HP_0000147",
                "name" : "Polycystic ovaries",
                "disease" : "HP_0000147"
              }
            ]
          },
```
and it must be a list of disease ids or empty array

**Comment by andrewhercules** [comment]
Moved to next sprint - Roland Garros

**Comment by d0choa** [comment]
The problem with phenotypes is a much more profound than just what the exposed fields are. The data currently comes from a very old list of mapping files that need to be updated

I'm working on this with the SPOT team. Unclear what the timeline is at the moment

**Comment by d0choa** [comment]
The preparations for this work are happening in EFO and will soon cascade to the platform team.
Some preliminary Disease - Phenotype mappings are expected during the summer.
User stories will be created describing the necessary work at the appropriate time. 
This ticket and the related #91 are now closed
