### ISSUE TITLE
GO and Reactome results with the API

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#101]
@gkos-bio commented on [Thu Jan 05 2017](https://github.com/opentargets/rest_api/issues/30)

When getting the data with the API, I've noticed we've got GO IDs and descriptions, whereas for Reactome we've got IDs only e.g. R-HSA-5685942.

In the web app, we've got a description rather than the R-HSA-50951 (see attached image). Could we have the description in the results from the API query in addition to the R-HSA-5685942?

Would an API user like that? Or would they be happy with the ID only? It would be good to be consistent in my opinion. So GO IDs and description and the same for the other resources.
![image](https://cloud.githubusercontent.com/assets/1447134/21683696/62f42174-d352-11e6-9d8b-7b61ab37f80d.png)

---

@ElaineMcA commented on [Tue Aug 28 2018](https://github.com/opentargets/rest_api/issues/30#issuecomment-416511555)

@gkos-bio this is minor issue, need to confirm requirement.

**Comment by andrewhercules** [comment]
This issue has been addressed in the React rewrite version of the target profile page - it displays the ID, description, and top-level parent pathway.
