### ISSUE TITLE
Add how baseline expression data is processed to documentation

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1011]
Currently the only information about baseline expression in the documentation is the list of the baseline sources [in the target profile documentation](https://docs.targetvalidation.org/getting-started/getting-started/target-profile) and how the tissue specificity is calculated [in the FAQs](https://docs.targetvalidation.org/faq/tissue-specificity). We should find a new page with the information available [in this Google doc](https://docs.google.com/document/d/1_40Knrsf69bHPVEzTYZVMyHhhabhSEYzO5u7wf1X84M/edit#).

**Comment by andrewhercules** [comment]
@AsierGonzalez is this ready or shall we push to the 20.09 release?

**Comment by AsierGonzalez** [comment]
I wrote the documentation and I am awaiting the feedback from @deniseOme and instructions as to where we should put it. From my end, I hope to have it ready for this release even if it's after the platform is out.

**Comment by AsierGonzalez** [comment]
The documentation is now available at https://docs.targetvalidation.org/getting-started/baseline-expression. I leave the ticket open for now as I would still appreciate if @deniseOme or @iandunham or someone else would like to share some feedback.

**Comment by iandunham** [comment]
This sentence is ambiguous "The tissue- and cell-based samples are processed together separately". Do you mean "The tissue- and cell-based samples are processed separately"?

**Comment by iandunham** [comment]
"assumed no to be" => "assumed not to be"

Otherwise this looks good. The language could be tightened up a bit - is there a version to edit for the future?

**Comment by AsierGonzalez** [comment]
Thank you for the feedback. I have corrected both mistakes in the [Google doc](https://docs.google.com/document/d/1_40Knrsf69bHPVEzTYZVMyHhhabhSEYzO5u7wf1X84M/edit#heading=h.am7ca1dfnaqp), where you can add comments or make edits.

**Comment by deniseOme** [comment]
Following adjustments TODO:

- include screenshots or a short animation if available to illustrate what we mean by Expression Atlas (EA) widget
- make clear the normalisation and other steps are done by EA not by us
- minor changes such as Gene Expression Atlas --> Expression Atlas (plus hyperlinking these resources)
- mention RNA baseline data comes from both microarray and RNA sequencing experiments

We'd need to include the following as well:

- details on how the Summary view is obtained (where mRNA and protein can be compared side by side)
- GTEx variability plot: which file we have used? How did we compute/display the expression variance?

As it stands we are mainly talking about the Expression Atlas widget (in the tab in the target profile page). Is that the aim @AsierGonzalez? If so, no need to address the above 2 points (summary and GTEx plot).

@iandunham, we have the current text in [this google doc page](https://docs.google.com/document/d/15N2ZBNEWm8jwn2wR1DZAlGwNbhDNtGSYcgGvvps4bR8/edit) with links to Asier's original doc. Feel free to make changes to the text in there.

**Comment by deniseOme** [comment]
Clarification/confirmation from @AsierGonzalez : baseline expression data is available from RNA sequencing experiments only. No microarray data for baseline, only differential expression (not the subject of this help page).

**Comment by deniseOme** [comment]
Clarification 2 from @AsierGonzalez : this piece of documentation pertains **only** to the Summary tab; not to Expression Atlas or GTEx tabs under "RNA and protein baseline expression" section. We will make this clearer in the docs.

<img width="1126" alt="Screen Shot 2020-06-24 at 00 21 34" src="https://user-images.githubusercontent.com/6472381/85476659-b42de680-b5b0-11ea-8ef4-cd90b44a5a14.png">
(current Platform)

<img width="990" alt="Screen Shot 2020-06-24 at 00 22 21" src="https://user-images.githubusercontent.com/6472381/85476763-e3445800-b5b0-11ea-88c9-bd0b5123f3c3.png">
(alpha release)

**Comment by AsierGonzalez** [comment]
@deniseOme is there anything left to do here?
