### ISSUE TITLE
review "disease" terms such as “latitude” and “collection latitude”

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#1012]
We currently have want terms such as “[latitude](https://www.targetvalidation.org/disease/OBI_0001620)” and “[collection latitude](https://www.targetvalidation.org/disease/EFO_0005020)” in the Open Targets Platform, under the larger "TA" [measurement](https://www.targetvalidation.org/disease/EFO_0001444).

There is no data associated to this (e.g. phenotypes, drugs) and no targets associated with them.

Worth investigating how they get there and whether blacklist them.

**Comment by d0choa** [comment]
@cmalangone it would be good to comment here whether the new disease index is dealing with this cases in any way or we are including them all. We can discuss

**Comment by d0choa** [comment]
After revising the new index logic, the idea is to maintain them the terms in the index for different reasons.
It will be up to the FE to display nicely, when no targets are associated
