### ISSUE TITLE
EVA: Duplicate association fields — Usage of RCV and RS identifiers

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1014]
**Update 2020-06-03:** the scope of the ticket has been refined following more investigation. See [here](https://github.com/opentargets/platform/issues/1014#issuecomment-628802114) for the latest summary.

Original description (partially not relevant anymore):

----

This ticket is part of the effort to get rid of duplicates in **unique_association_fields** in the evidence strings submitted by EVA, along with #1013.

ClinVar records (RCV*) pair together phenotypes and variations. In most cases, a variation (VCV*) is a single variant. However, sometimes it is a haplotype consisting of several variants. For example, 
record [RCV000504796.1](https://www.ncbi.nlm.nih.gov/clinvar/RCV000504796.1/) includes the variation [VCV000438264.1](https://www.ncbi.nlm.nih.gov/clinvar/variation/VCV000438264.1/) which is a haplotype consisting of four variants: three SNPs and one short deletion.

When generating the evidence strings, we issue one for _each_ combination of (RCV record, VCV variation, source trait name, gene, functional consequence). However, the variants in the haplotype can in general have different functional consequences. When this happens, a separate evidence string is issued for each of those consequences. And because the functional consequence is not a part of the **unique_association_fields,** we get duplicates.

I'm not sure what would be the most sensible solution here. If we do want to issue separate evidence strings for all functional consequence of the haplotype variants, we could just add the functional consequence to **unique_association_fields**. But I'm not sure how much clinical/biological meaning this would have. By the way, could you remind me what _exactly_ a single evidence string is supposed to represent?

An additional question about the haplotypes in which variant type we should assign them. Currently we [have](https://github.com/opentargets/json_schema/blob/a0c6394e9a08f8313fe5c3b0848e77d3340f90f9/opentargets.json#L692):
```
                "snp single",
                "snp snp interaction",
                "structural variant",
                "SNP",
                "deletion",
                "insertion"
```
None of which seems to fit. Except maybe for "snp snp interaction"?

**Comment by tskir** [comment]
And actually, a bigger problem is that functional consequences of individual variants of a haplotype might not make any sense until you consider the entire haplotype all together. I'm not sure we have the capacity to do that: I don't think VEP supports that, and I also don't think that the ClinVar haplotypes include the phasing information. It looks like it's just a collection of variants.

**Comment by AsierGonzalez** [comment]
This is an interesting case and my feeling is that the best solution would be to include haplotypes as variant types, which is something that @iandunham brought up in #809. If we considered an haplotype a single variation unit then the question would be if we would like to list all the theoretical functional consequences.
In the interim, we could add the functional consequence to the unique association fields so that all the variants in the haplotype are represented. However, if we do that in the table the rows would still look as repeats because we do not show what the allele is. Do you have any numbers about how many haplotypes there are at the moment so that we can factor in how widespread this is?

**Comment by tskir** [comment]
@AsierGonzalez

I did further investigation and have a correction to make to the original scope of this ticket. Actually, the main problem is not related to functional consequences and is only indirectly related to haplotypes. The reason for duplication is how we name the variants.

Currently, when our pipeline needs to specify a variant ID for the evidence string, it uses an RS ID as the first priority, and if is it not available in ClinVar data for this variant, simply substitutes the RCV ID of the ClinVar record itself. As a result, we can have something like this:
```json
"unique_association_fields": {
    "alleleOrigin": "germline",
    "clinvarAccession": "RCV000504796",
    "gene": "ENSG00000072210",
    "phenotype": "http://www.orpha.net/ORDO/Orphanet_816",
    "variant_id": "RCV000504796"
}
```

Notice how `clinvarAccession` and `variant_id` are the same.

I assume that it was implemented this way because the Open Targets JSON schema only allowed RS IDs or RCV IDs in place of a variant identifier. Anyway, the current approach is very bad because **RCV ID does not identify a variant at all,** it identifies a record which in general associates _multiple variations_ (which can in turn be not simple variants, but haplotypes) with _multiple phenotypes._

This has been kind of working all this time because, in a majority of cases, RCV _will_ include only a single variation and that variation _will_ be a single variant. However, this is not the general design, just a very common case. You might remember me raising this issue many months ago, but back then we had more pressing issues to resolve so it was eventually put aside.

Anyway, now when an RCV contains either haplotype with variants without RS IDs, _or_ just two separate variants without RS IDs, we will not only record identical `unique_association_fields` for them, we will issue **two completely identical evidence strings for actually different variants.**

Although less likely, RS IDs can also be prone to this issue (I did not investigate this case in depth).

I see that now the Open Targets JSON schema actually supports a sensible and unambiguous `CHROM_POS_REF_ALT` notation. I propose that I modify the EVA pipeline so that it drops using RS and RCV IDs for identifying variants, and always identifies variants using this new notation. What do you think about this idea?

**Comment by tskir** [comment]
And then, _separately,_ we have the issue that haplotypes are being processed simply as individual variants and recorded as such.

**Comment by AsierGonzalez** [comment]
From what you say, it feels wrong to use the RCV id as a variant identifier and the chromosomal notation would be a better option. There is one caveat though, which is that we show the variant id in the Genetics Associations table in the "Mutation" table and we generate a link based on it so any changes we do to this may break things in the front-end. Before we saction your suggestion, which makes sense from the data's standpoint, let us check that it would not break anything.

**Comment by AsierGonzalez** [comment]
As I suspected, the FE uses the variant id to generate the url in the `Mutation` column. When the variant id is an RCV id, the url looks like `https://www.ncbi.nlm.nih.gov/clinvar/[variant.id]` and it seems to be (I haven't checked it systematically) the same as the link in the `Evidence source` column. If we change to using the chromosomal notation for the mutation, should we link somewhere?
@d0choa, @andrewhercules what do you think about the suggested changes? In the example above the change would be `"variant_id": "RCV000504796"` -> `"variant_id": "CHROM_POS_G_C"`

**Comment by tskir** [comment]
@AsierGonzalez @d0choa @andrewhercules Do you have any updates on this issue? I think it would be nice to address it for the next release.

Some additional considerations to add to what has been said above:
* In terms of where to point the variant link: I think a sensible solution would be to continue pointing to Ensembl if there is an RS ID, and just not point _anywhere_ (simply plain text) if there isn't one, since I don't think Ensembl supports browsing variation using arbitrary chrom/pos/ref/alt notation. There are external commercial sites like 
* If we migrate our pipeline to always output only chromosomal coordinates, then presumably there will be some functionality required on _your_ end to try to map those into RS IDs, because people will still want to be able to browse by RS ID. Do you perhaps have something like this already?
* We should remember that in very rare cases chrom/pos/ref/alt notation be very long, up to a couple of thousand characters (because of the ref/alt sequences). I suspect this will break page layouts badly if we just naively migrate to it.

**Comment by andrewhercules** [comment]
@tskir, agreed - I'll flag this as something to review/close for our next release. In the meantime, I will explore the FE implications, particularly in our new rewrite UI.

**Comment by AsierGonzalez** [comment]
Summary of discussion in EVA-OT meeting held on 9-06-20
---
Two solutions have been suggested to avoid using suboptimal RCV and rs ids as variant identifiers:
1. Use "CHROM_POS_REF_ALT" notation: It would work for small variants but would require alternatives for SVs. In addition, the notation for STRs could be extremely long (longest repeat is 4kb at the moment but there is no theoretical upper limit).
2. Use alternative variant ids: ClinVar assign a Variation ClinVar accession number (VCV) to the aggregation of all submitted records interpreting the same variant or set of variants.

In the next release the evidence will be generated twice, one using the usual id system and another one using "CHROM_POS_REF_ALT" notation so that OT can check whether there are any issues. In the meantime VCV ids will also be explored.

**Comment by AsierGonzalez** [comment]
[This commit](https://github.com/opentargets/json_schema/commit/997ed66f93d67eb29a3a3007cac533f603716fd9#diff-8733dc6847a1a17a6cfa055eb8a14605) to [ag_eva_changes](https://github.com/opentargets/json_schema/blob/ag_eva_changes/opentargets.json) replaces support of RCV ids with VCV ids

**Comment by AsierGonzalez** [comment]
RS ids will be accepted as secondary ids, which is intended to be used with variants identified with the "CHROM_POS_REF_ALT" notation if they have one. Change implemented in [this commit](https://github.com/opentargets/json_schema/commit/7066d68265a1b05038c356de30ea4e69cd648d41).

**Comment by andrewhercules** [comment]
Re-assigning to the next sprint so that PR can be opened and approved

**Comment by AsierGonzalez** [comment]
I leave the ticket open until the next time we receive an EVA evidence file

**Comment by AsierGonzalez** [comment]
This has not been implemted yet and it is not scheduled to be done for 20.11 - moving it to 21.02

**Comment by ireneisdoomed** [comment]
This has not been implemented yet and it is not scheduled to be done for 21.02 - moving it to 21.04.

**Comment by ireneisdoomed** [comment]
In the new pipeline this is no longer a problem as we have added the `variantRsId` field to capture variations and thus eliminate duplicate evidence.

It should be noted that there is not always a SNP described for all the evidence, however this does not lead to duplications at the moment.

```
eva.filter(col("variantRsId").isNull()).groupBy("datasourceId", "diseaseFromSourceMappedId", "studyId", "targetFromSourceId").count().orderBy(desc("count")).show()
+------------+-------------------------+------------+------------------+-----+
|datasourceId|diseaseFromSourceMappedId|     studyId|targetFromSourceId|count|
+------------+-------------------------+------------+------------------+-----+
|         eva|             Orphanet_722|RCV001030447|   ENSG00000122194|    1|
|         eva|              EFO_0009139|RCV001039591|   ENSG00000117394|    1|
|         eva|              EFO_0010953|RCV001042368|   ENSG00000116786|    1|
...

```

Closing issue.
