### ISSUE TITLE
React rewrite alpha: Related Targets section (target profile page) crashes for (some?) pseudogenes

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#1016]
The `data` prop to both the Summary and Section component seems to be null for these genes. This results in a TypeError as `src/public/target/sections/RelatedTargets/Summary.js` tries to access its `.data` property, and this line of  `src/public/target/sections/RelatedTargets/Section.js` tries to access several of its properties:
```js
  const { rows, count, maxCountAOrB } = data;
```

Contrived example: [ADGRE4P](https://alpha--platform-app.netlify.app/target/ENSG00000268758)

**Comment by mirandaio** [comment]
Thanks for reporting @fedde-s! This has been fixed by this PR https://github.com/opentargets/platform-app/pull/139
