### ISSUE TITLE
API: allow target_class parameter in evidence filter endpoint

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#102]
@gkos-bio commented on [Thu Jan 05 2017](https://github.com/opentargets/rest_api/issues/32)

there is a `target_class` parameter in the association endpoint. 

It would be nice if there was a similar parameter in the `public/evidence/filter` endpoint too.

---

@gkos-bio commented on [Thu Jan 05 2017](https://github.com/opentargets/rest_api/issues/32#issuecomment-270690874)

Hi @PriyankaW are you working on it?

---

@PriyankaW commented on [Thu Jan 05 2017](https://github.com/opentargets/rest_api/issues/32#issuecomment-270703170)

Hello, @gkos-bio , yes i am working on the evidence endpoint - will incorporate target_class param too.

---

@ElaineMcA commented on [Tue Aug 28 2018](https://github.com/opentargets/rest_api/issues/32#issuecomment-416509646)

@gkos-bio : Need to confirm if requirement still and priority/value.

**Comment by andrewhercules** [comment]
This issue has been closed as it has been captured on [the Master Feature Prioritisation worksheet](https://docs.google.com/spreadsheets/d/1jZMKv6fDum6aEOqernfuwSv__f8CBFK6PZoRo9m0mWE/edit#gid=0) available on the team's Google Drive.

CC: @d0choa
