### ISSUE TITLE
Integrate Pathways summary widget and detail view using with GraphQL API

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1021]
Pathway data is now available in the new GraphQL API ([sample query for IL2RA](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20test_protein_annotations%20%7B%0A%20%20reactome%3Atarget(ensemblId%3A%20%22ENSG00000134460%22)%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20reactome%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20label%0A%20%20%20%20%20%20children%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20parents%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20isRoot%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20ancestors%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20isRoot%0A%20%20%20%20%20%20%20%20ancestors%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20isRoot%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20isRoot%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)).

![Screenshot 2020-05-19 at 13 09 07](https://user-images.githubusercontent.com/7490258/82324713-fd977e80-99d1-11ea-9a1a-0963a4bdf1ea.png)

Please implement the summary widget and detail views with the following changes noted below.

**Summary widget**
- Display total number of pathways

**Detail view**
- Remove the "Top-level parent pathways" section as it appears to act as a filter with clickable elements but is not interactive
- Change the "View diagram" column heading to "View target (ESR1) and pathway". Within the column, remove the PNG and SVG links and instead construct a link to the Reactome pathway browser page `https://reactome.org/PathwayBrowser/#/PATHWAY_ID&FLG=UNIPROT_ID` ([example](https://reactome.org/PathwayBrowser/#/R-HSA-1251985&FLG=P03372))
- In the "Top-level parent pathway" column in the data table, please display the top-level parent pathway(s) which are noted with `isRoot: True` (e.g. in the case below, both `Signal Transduction` and `Immune System` would be visible in the column) 

![Screenshot 2020-05-19 at 13 07 50](https://user-images.githubusercontent.com/7490258/82324637-dd67bf80-99d1-11ea-9f63-4b911d981935.png)

**Comment by fedde-s** [comment]
I've talked @andrewhercules about this task and started looking into the implementation.

**Comment by fedde-s** [comment]
I've talked to @andrewhercules about this task and started looking into the implementation.

**Comment by fedde-s** [comment]
Most of the work is ready in #158—I'll push a patch to replace the PNG links soon.

**Comment by andrewhercules** [comment]
Closing this ticket as PNG link and Reactome link label will be captured in target profile page polish work - see epic #1073
