### ISSUE TITLE
Integrate Mouse Phenotypes summary widget and detail view using with GraphQL API 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1022]
Mouse phenotype data is now available from the new GraphQL API - see below for a [sample query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?operationName=target_search&query=query%20target_search%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000091831%22)%7B%0A%20%20%09id%0A%20%20%20%20approvedName%0A%20%20%20%20mousePhenotypes%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20phenotypes%7B%0A%20%20%20%20%20%20%20%20categoryLabel%0A%20%20%20%20%20%20%20%20categoryIdentifier%0A%20%20%20%20%20%20%20%20genotypePhenotype%7B%0A%20%20%20%20%20%20%20%20%20%20subjectBackground%0A%20%20%20%20%20%20%20%20%20%20subjectAllelicComposition%0A%20%20%20%20%20%20%20%20%20%20pubmedId%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20identifier%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A) and response.

**Query:**
![Screenshot 2020-05-22 at 14 29 33](https://user-images.githubusercontent.com/7490258/82672795-be1e9b80-9c38-11ea-9d44-f96181ea481f.png)

**Response:**
![Screenshot 2020-05-22 at 14 29 58](https://user-images.githubusercontent.com/7490258/82672805-c080f580-9c38-11ea-9c15-03a7c6459967.png)

Can we please port the existing summary widget and detail view into `alpha`, with the following changes?

**Summary widget**
- Display total number of unique phenotypes. Unique phenotypes can be found by iterating through the response and looking at the `mousePhenotypes.phenotypes.genotypePhenotype.label` values  

**Detail view**
- Remove the section that displays the phenotype categories in blue (active) or grey/white (inactive) boxes as it appears to act as a filter with clickable elements but is not interactive

**Comment by andrewhercules** [comment]
@forus could you take a look at this?

**Comment by forus** [comment]
@andrewhercules 
I think @mkarmona mentioned similar issue on the last call.

The following `GenotypePhenotype `(`query.target.mousePhenotypes.phenotypes.genotypePhenotype`) fields have a string value that has to be split by a comma:
```
pubmedId: String!
subjectAllelicComposition: String!
```
Should backend return an array instead?

**Comment by andrewhercules** [comment]
Hi @forus! Good spot - thank you! I'll follow up with @mkarmona and ask if that can be formatted differently. I would prefer an array just because I can't be certain commas don't exist in a value in the `subjectAllelicComposition` field.

@mkarmona is this something we can adjust in the back-end? Or for the MVP, should the front-end handle this data processing?

**Comment by forus** [comment]
Here is PR https://github.com/opentargets/platform-app/pull/154
We'd have to remove splitting when the back-end will be ready.

**Comment by andrewhercules** [comment]
Ticket closed as PR approved and merged into `alpha`
