### ISSUE TITLE
export Drugs data in from disease and target profile pages

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#1030]
User has brought to our attention that the export of drug data into a .csv file from a disease profile page has an issue with the field “mechanism of action”. User has noticed some extra info gets appended to the MoA information e.g. "1 publicationEuropePMC". 

<img width="636" alt="Screen Shot 2020-05-12 at 15 29 21" src="https://user-images.githubusercontent.com/6472381/81743097-0a2f4a80-9499-11ea-8242-81b06a58cd00.png">

<img width="433" alt="Screen Shot 2020-05-12 at 15 30 39" src="https://user-images.githubusercontent.com/6472381/81743131-1f0bde00-9499-11ea-8b2a-2ad571327a13.png">

This is because in the UI we have "1 publication" hyperlinked and pointing to Europe PMC (hence "1 publicationEuropePMC" appended to the mechanism of action (e.g. Glutathione reductase inhibitor) e.g. https://www.targetvalidation.org/disease/EFO_0000519

<img width="180" alt="Screen Shot 2020-05-12 at 21 47 26" src="https://user-images.githubusercontent.com/6472381/81743823-34cdd300-949a-11ea-82e3-13b3b5afcbe6.png">

Is this a feature or a bug? 
Note same behaviour in the drug data downloaded from the Target profile page and whether we download in .tsv or .csv.

**Comment by d0choa** [comment]
I doubt this behaviour was intentional in the first place, so I would go for a bug. No fix is expected in the angular app with the imminent inclusion of new tables and export functions derived from #1000. We'll keep an eye, so this behaviour is not reproduced there.
