### ISSUE TITLE
support email from the footer has "Target Validation Platform"

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#1031]
We've been getting a few support emails lately with the subject line "Target Validation Platform - help request).

This is due to how users are getting in touch with us by clicking in the email address in the footer of the Open Targets Platform 

<img width="282" alt="Screen Shot 2020-05-12 at 21 51 07" src="https://user-images.githubusercontent.com/6472381/81744178-c8070880-949a-11ea-87c9-25e6f15b2af5.png">

<img width="358" alt="Screen Shot 2020-05-12 at 21 51 18" src="https://user-images.githubusercontent.com/6472381/81744185-ca696280-949a-11ea-9817-709ad2c1e3c3.png">

Can we change this automatic subject line from "Target Validation Platform - help request" to "Open Targets Platform - help request".

As it stands different, inconsistent names get our users confused and it's not ideal for branding consolidation.

Besides, when one clicks on the "Feedback" button, the subject line is automatically set to "Open Targets Platform", which is the right thing to have:

<img width="184" alt="Screen Shot 2020-05-12 at 21 54 46" src="https://user-images.githubusercontent.com/6472381/81744532-3fd53300-949b-11ea-840d-9fa1228938a5.png">

Note that in the current version of the re-write, no subject line at all is automatically inserted. Ideally this should be fixed.

<img width="330" alt="Screen Shot 2020-05-12 at 22 03 20" src="https://user-images.githubusercontent.com/6472381/81745266-6d6eac00-949c-11ea-95dd-9eb4d90f0c14.png">

**Comment by d0choa** [comment]
Tagged for 20.06 (Zenhub)

**Comment by andrewhercules** [comment]
Ticket closed as PR merged and pushed to production
