### ISSUE TITLE
Extract OT information to prioritise COVID-19 targets

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1032]
In OT we have identified a number of aspects in COVID-19 research that we could support with our data. With that objective, we have decided to collate the following information in a few tables:

- Human and virus protein information
- Baseline gene and protein expression
- Human - virus protein interactions
- Target tractability 
- Target safety

**Comment by d0choa** [comment]
Version 0.1 of this tools has been generated. More actions will be specified when the future directions are agreed
