### ISSUE TITLE
Refactor Gene Ontology data feed

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1037]
It came again as a discussion the potential improvement on the data source feed for Gene Ontology. Discussed before @PruMM in #794. There are 3 main reasons to improve the annotation data:

- Cover RNA targets in the platform - lncRNAs, etc.
- Avoid some nuances with the uniprot parsing
- Get more complete information about the annotations

 I'm documenting here the course of action in order to have a healthy Gene Ontology data source. BE team can decide the priority based on capacity.

1. Download files from EBI services
- Annotation files for human proteins - EBI ftp - ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gaf.gz
- Annotation files for human RNAs - EBI ftp - ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_rna.gaf.gz
- RNAcentral to Ensembl mapping files - EBI ftp - ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv

2. Mappings
RNAs will require a mapping to Ensembl. It needs to be Ensembl (and not uniprot) because these RNAs do not encode proteins therefore they have no Uniprot ID.

3. Extract relevant fields:
Documentation on the header of the gaf file can be found [here](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/)

The fields we are interested in are:
- GO ID - col 5
- DB:Reference - col 6
- Evidence Code - col 7
- Aspect - col 9
- Assigned By col 15

4. Enrich with ECO codes:
Using the `Evidence Code` field we should be able to include the ECO code, similar to the way QuickGO does [here](https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=A0A0V0SHY9). This step is not critical, as we no longer use ECO codes in our evidence.

**Comment by JarrodBaker** [comment]
It looks like the ECO annotations are available in this location: ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gpa.gz

**Comment by d0choa** [comment]
if they come easy take them. If they don't it's not worth going the extra mile for them. Happy to drop them. We no longer use eco codes in evidence (for example)
