### ISSUE TITLE
Update targets and minor changes

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1042]
get the branch in this PR https://github.com/opentargets/platform-etl-backend/pull/38 and work from there? Actions

- [x] run the whole steps (now all default steps are configured in the configuration file if no steps are provided)
- [x] include mouse phenotypes in targets like it is
- [x] another step expression just get the expression index at it is for now (add to the steps in the configuration)
- [x] replace all indices in the ES machine you prepared and include the new ones

**Comment by cmalangone** [comment]
Done. Merged in master (approved PR)
