### ISSUE TITLE
GraphQL error: Internal server error on TP53 profile page

### ISSUE THREAD

**Issue by forus** [opentargets/platform#1045]
TP53 profile page throws "GraphQL error: Internal server error."

https://alpha--platform-app.netlify.app/target/ENSG00000141510

![prod_mode.png](https://images.zenhubusercontent.com/5eaad3777ada80775aa7039e/3fb2711a-934f-411b-8f62-0f8b5121ed46)

![dev_mode.png](https://images.zenhubusercontent.com/5eaad3777ada80775aa7039e/38efc7d8-45c2-46d4-a9bf-43467074174b)

**Comment by forus** [comment]
Surprisingly enough, I haven't found failing (not 200) graphql request on the network tab of the browser.

**Comment by d0choa** [comment]
Thanks @forus. @mkarmona will look at it tomorrow. For future reference, the offending query is related with `Cancer Biomarkers`

**Comment by mirandaio** [comment]
Here is a minimal query that causes this error https://tinyurl.com/yb2w37va

**Comment by mkarmona** [comment]
We are currently touching some parts of the pipeline so I will review this as soon as I get refreshed the data.

**Comment by forus** [comment]
@mirandaio Do you think we should show a user-oriented error message when such types of errors happen?
