### ISSUE TITLE
Update target tractability detail view to show/hide heat maps depending on data availability

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1046]
In the current Angular version of the Platform, we show or hide the tractability heat maps depending on whether the API returns data:

**Data for all three modalities available (e.g. [PTGS2]**(https://www.targetvalidation.org/target/ENSG00000073756?view=sec:tractability))

![Screen Shot 2020-05-15 at 3 03 41 PM](https://user-images.githubusercontent.com/7490258/82058982-5b1f8880-96bd-11ea-88c2-2c279418de7f.png)

Only data for antibody modality available (e.g. [RPGRIP1L](https://www.targetvalidation.org/target/ENSG00000103494?view=sec:tractability)) 

![Screen Shot 2020-05-15 at 3 02 48 PM](https://user-images.githubusercontent.com/7490258/82058876-3a573300-96bd-11ea-861d-0ba5cf0e2408.png)

Only data for small molecule modality available (e.g. [PALB2](https://www.targetvalidation.org/target/ENSG00000083093?view=sec:tractability))

![Screen Shot 2020-05-15 at 3 06 40 PM](https://user-images.githubusercontent.com/7490258/82059276-b5b8e480-96bd-11ea-9a3d-ae94d2bb9601.png)

Can we please implement similar logic for the React rewrite?

If a specific modality is not available, can we please hide the heat map and instead display a note:

`No small molecule tractability data for GENE-SYMBOL available`
or 
`No antibody tractability data for GENE-SYMBOL available`
or
`No other modalities tractability data for GENE-SYMBOL available`

Can we please replace GENE-SYMBOL with the HGNC symbol?

**Comment by forus** [comment]
@andrewhercules I assume the case when all three tables (small molecule, antibody, and the other modalities) have no data is not an exception: we show the section with those three messages instead.
AFAIK hence this section becomes different from the rest of the sections that in such cases just not shown altogether

**Comment by andrewhercules** [comment]
@forus, in cases where all three tables have no data (e.g. [GATA3](https://alpha--platform-app.netlify.app/target/ENSG00000107485)), we already hide the entire detail view and that can remain as-is - we won't change how this section behaves with no data.

The show/hide functionality noted above is only for targets where there is data for at least modality.

**Comment by forus** [comment]
Here is PR: https://github.com/opentargets/platform-app/pull/147

**Comment by andrewhercules** [comment]
Ticket closed as work merged into `alpha`
