### ISSUE TITLE
Related diseases / targets header is not appropiate as symbols

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1049]
related diseases table, at the top header that formulation is wrong. that is the shared diseases count which is the cardinality of the intersection. having a plus sign is not appropriate. more like this |A⋂B|

you have 2 main options here

1. utf using the font
2. mathjax rendering (top quality)

Shared diseases $\vert D_{A}\cap D_{B} \vert$ https://www.mathjax.org/#demo

**Comment by javfg** [comment]
Going with the first option for now. Mathjax library is pretty big and it's not justified to increase the bundle size so much for just a table header caption.

We might reevaluate this if we end up displaying more math.
