### ISSUE TITLE
Update filters for L2G evidence

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1050]
Update the script for evidence preparation to accept a lower threshold for l2g score for filtering

Further details TBC

**Comment by DSuveges** [comment]
The filtered data is now available: [here](https://console.cloud.google.com/storage/browser/_details/otar000-evidence_input/Genetics_portal/json/genetics_portal_evidences-20-05-2020.json.gz?project=open-targets)

**Comment by andrewhercules** [comment]
@DSuveges and @d0choa, just to confirm, we will now set the filter to 0.05 as that will ensure coverage that is comparable to the previous GWAS Catalog evidence?

**Comment by andrewhercules** [comment]
Pipeline has been re-run with filter set to 0.05

**Comment by andrewhercules** [comment]
Ticket closed as work has been completed

**Comment by andrewhercules** [comment]
Post note: for rationale about filtering, please see #876
