### ISSUE TITLE
Rerun LINK for 20.06

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1052]
Details TBC

**Comment by cmalangone** [comment]
Arwa provided the new vocabulary :
https://console.cloud.google.com/storage/browser/opentargets-vocabularies_2020_06

Run library-beam:
   Issue with publicationType field. Fixed.

Releasing today after loading the data into a new ES
http://es-200617-101804.es-200617-101804.il4.europe-west1.lb.open-targets-library.internal:9200

**Comment by andrewhercules** [comment]
Ticket closed as LINK has been updated thanks to @cmalangone! 👍  🎉
