### ISSUE TITLE
Draft contribution guidelines for platform-app repo

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1054]
As discussed in today's sprint catch-up meeting, it would be a good idea to have a set of [contribution guidelines](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) for the platform-app repo.

**Comment by andrewhercules** [comment]
@javfg as you did such a great job with the documentation for the table component, could you start drafting contribution guidelines for the `platform-app` repo? 

Topics could include: 

- Do PRs need to be connected to an issue? 
- Opening up a PR and tagging me or David O.
- When merging a PR, do we squash commits or keep the history?

**Comment by javfg** [comment]
Indeed, this is in my to-do list. I'll open a discussion about it everyone involved to get you input!

**Comment by javfg** [comment]
New docs are up: https://github.com/opentargets/platform-app/tree/jf-docs

@andrewhercules @d0choa can you take a look and see if I missed something? Thanks!

PS: We now have a working badge! :D

**Comment by d0choa** [comment]
Looks good in my opinion. We need @mkarmona view on this as well

**Comment by d0choa** [comment]
@andrewhercules up to you to close this ticket

**Comment by andrewhercules** [comment]
Guidelines reviewed and will be included in our release comms plan
