### ISSUE TITLE
Resolve Bibliography detail view error on drug profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1058]
With some drugs - e.g. [CHEMBL2109124](https://alpha--platform-app.netlify.app/drug/CHEMBL2109124) - LINK returns 8 publications but the detail view displays an error message. 

![Screenshot 2020-05-21 at 12 43 22](https://user-images.githubusercontent.com/7490258/82555937-ad025b80-9b60-11ea-9775-38b429015717.png)

In reviewing the API calls made to LINK - https://link.opentargets.io/search?query=Dorlimomab%20aritox and https://link.opentargets.io/search?query=Dorlimomab%20aritox&aggs=true&size=0 - it returns the count (8) and the first call returns 8 publication records.

Can you please investigate and fix this issue so that the publications are displayed correctly?

**Comment by d0choa** [comment]
After digging on the error, the issue is related with some publications having a `null` in the `._source.authors` object.

```
      {
        "_id": "2620256", 
        "_index": "pubmed-19", 
        "_score": null, 
        "_source": {
          "abstract": null, 
          "authors": null, 
          "chemicals": [
            {
              "name": "Antibodies, Monoclonal", 
              "name_id": "D000911", 
              "registryNumber": "0"
            }, 
            {
              "name": "Immunotoxins", 
              "name_id": "D000922", 
              "registryNumber": "0"
            }, 
            {
              "name": "zolimomab aritox", 
              "name_id": "C068230", 
              "registryNumber": "2C1ZT922TD"
            }, 
            {
              "name": "Ricin", 
              "name_id": "D012276", 
              "registryNumber": "9009-86-3"
            }
          ], 
```

**Comment by andrewhercules** [comment]
Good spot - thanks @d0choa. I also think the `null` abstract also causes a problem:

![Screenshot 2020-05-21 at 16 35 44](https://user-images.githubusercontent.com/7490258/82576054-36298a80-9b81-11ea-9d6d-a25fd6dd3195.png)

https://www.targetvalidation.org/summary?drug=CHEMBL2109124

**Comment by fedde-s** [comment]
Probably the same code: I encountered the same failing assumption on [the target profile page for SLC10A2](https://alpha--platform-app.netlify.app/target/ENSG00000125255).

**Comment by andrewhercules** [comment]
Ticket closed as work merged into `alpha`
