### ISSUE TITLE
AND,OR,NOT logic in the API

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#106]
@elipapa commented on [Fri Sep 15 2017](https://github.com/opentargets/rest_api/issues/105)

## Description
* [x] **WHY - What is the problem this feature would answer?**  

filtering targets expressed in one tissue but NOT in another one and other similar queries. Basically it will enable an expressive query language for search.

* [ ] **HOW are we going to solve the problem?**  
> *Describe technical design of the solution.*
> *Paste here google doc link or link to markdown file, if already written somewhere else*

* [ ] **WHAT would this look like?**
> *Screenshots and mock-ups are great*
 

### Get to a prototype at branch.targetvalidation.org:
> Write code + **tests** + docs. Isolate the work in feature branches.  
> Use as many PRs as you need.  
> Write tests in the same or different PRs, as is convenient for you.  
> As each PR is merged, add a comment to this issue referencing the PRs.  

- [ ] Feature tag *Code should have a feature tag to be disabled by default.*
- [ ] Minimal functional testing
- [ ] Minimal docs
- [ ] if on webapp, test a deployment on netlify
       
### Push to staging
- [ ] merged code and pushed to staging.targetvalidation.org
  **PULL request should be reviewed by 1-2 people at least**
- [ ] at least 1 week internal testing?
- [ ] received some feedback/input from users (eg. pharma scientist)

### Released
- [ ] in the release notes?
- [ ] documentation updated?		
- [ ] blog post?
- [ ] users that requested it originally informed?

## Make sure you can measure impact
> As dev team we want to know if a new feature are succesful.
> To do that we need to define metrics to assess the impact of each new feature we introduce to the platform
- [ ] metric identified 
- [ ] identify the one metric that matters (OMTM)

---

@elipapa commented on [Fri May 04 2018](https://github.com/opentargets/rest_api/issues/105#issuecomment-386617615)

slack does this well:

![image](https://user-images.githubusercontent.com/112610/39633185-2b13c874-4faf-11e8-88e9-70a84128ad26.png)

**Comment by ElaineMcA** [comment]
@Need to confirm priority and value of this advanced search/ filtering over other requirements.

**Comment by d0choa** [comment]
This level of advanced search query is under consideration for the new search API #823
