### ISSUE TITLE
Refactoring the critical value computations as a published standalone library 

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1063]
Making the critical value computation into a published library as a common bucket to put generic stuff produced by Open Targets backend sounds like a good idea. This helps to reduce code duplication. Doing the scala way (see [this example](https://github.com/scalanlp/breeze/blob/master/project/Build.scala#L52)) might be the right way to go. Having a look at the most recent way (from the Scala community) of doing this task and whether a specific SBT plugin exists that does most of the job.

**Comment by ktsirigos** [comment]
related to adverse events / pharmacovigilance.

@mbdebian is this within scope?
