### ISSUE TITLE
Update rewrite homepage to prepare for alpha release

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1065]
To prepare for the release of `alpha` in June 2020, we should update the [homepage](https://alpha--platform-app.netlify.app/) to communicate to users that this is a preview and that not all functionality is available.

Can we please make the following changes to the homepage layout?

- [x] Remove the "Platform Stats" section

And can we please update the search box with the following changes?

- [x] Remove the "Evidence page" quick search link
- [x] Update the quick search links to the following: ESR1, ENSG00000123374, Crohn's disease, Orphanet_839, EFO_0003060, Mifamurtide, Humira
- [x] Remove the blue Open Targets helix and text word mark and replace with [the Open Targets helix logo and word mark](https://d33wubrfki0l68.cloudfront.net/eb0a90a96fbc4ad67ff3002870c5e32ad8cf61d0/c63e2/assets/img/ot-logo-colour.png)
- [x] Add the following notice underneath the Open Targets helix logo and word mark image:

**Important Note:
This is an ALPHA release of a new version of the existing [Open Targets Platform](https://www.targetvalidation.org/). 
You can search for and view target, disease, and drug profile pages.**

**Comment by andrewhercules** [comment]
@mirandaio, can you please make a few small changes to the homepage to prepare it for the `alpha` release?

**Comment by andrewhercules** [comment]
@mirandaio looks good! 👍 

Can we please make a slight change to the layout in the search box and add some line breaks and padding to the alpha release notice to to increase the prominence of the notice?

![Screenshot 2020-06-09 at 09 14 53](https://user-images.githubusercontent.com/7490258/84123407-b7ae6300-aa31-11ea-9799-b74df31a441c.png)

And here is a 8KB SVG of the helix logo and Platform-branded word mark: [**Open_Targets_Platform_Logo.svg.zip**](https://github.com/opentargets/platform/files/4750774/Open_Targets_Platform_Logo.svg.zip)

**Comment by andrewhercules** [comment]
![Rewrite homepage search box](https://user-images.githubusercontent.com/7490258/84146470-aaa26b80-aa53-11ea-9a27-3ac783431e60.png)

A few notes:

- I have created a special [SVG logo and word mark](https://github.com/opentargets/platform/files/4752104/Open_Targets_Platform_Logo_alpha.svg.zip)
- Please link the `Browse our GraphQL API` link to the GraphQL browser
- For the background of the notice, please use `#FFFFCC`

For the quick-search links, please create [chips](https://material-ui.com/components/chips/) that have a blue outline and blue text in Open Targets Blue `#3489ca` and please show two targets, two diseases, and two drugs. 

In the current Angular app, we have a [config file](https://github.com/opentargets/webapp/blob/be019b6a095f1115c647a2a6657c510ac6d6c40e/app/config/general/default.json#L587) where we list a set of targets and diseases and we use a [sample function](https://github.com/opentargets/webapp/blob/5b9bae6179a1ba36a18505a5f07b3e64de2c2ec7/app/src/js/page-controller.js#L54) to randomly select two targets and two diseases to show as quick links.

Could we implement something similar using the following list so that we return two random targets, diseases, and drugs for the quick-search chips?

```
    "searchExamples" : {
        "targets":[
            {"label":"IL13", "id":"ENSG00000169194"},
            {"label":"TSLP", "id":"ENSG00000145777"},
            {"label":"ADAM33", "id":"ENSG00000149451"},
            {"label":"CFTR", "id":"ENSG00000001626"},
            {"label":"KIT", "id":"ENSG00000157404"},
            {"label":"NOD2", "id":"ENSG00000167207"},
            {"label":"TYK2", "id":"ENSG00000105397"},
            {"label":"TNF", "id":"ENSG00000232810"},
            {"label":"PTGS2", "id":"ENSG00000073756"},
            {"label":"ADORA3", "id":"ENSG00000282608"},
            {"label":"APP", "id":"ENSG00000142192"},
            {"label":"GRIN3A", "id":"ENSG00000198785"},
            {"label":"IL2RA", "id":"ENSG00000134460"},
            {"label":"ACHE", "id":"ENSG00000087085"},
            {"label":"SNCA", "id":"ENSG00000145335"},
            {"label":"BRAF", "id":"ENSG00000157764"},
            {"label":"BRCA2", "id":"ENSG00000139618"},
            {"label":"KRAS", "id":"ENSG00000133703"},
            {"label":"PTEN", "id":"ENSG00000171862"},
            {"label":"TP53", "id":"ENSG00000141510"}
        ],
        "diseases":[
            {"label":"asthma", "id":"EFO_0000270"},
            {"label":"lung disease", "id":"EFO_0003818"},
            {"label":"childhood onset asthma", "id":"EFO_0004591"},
            {"label":"pneumonia", "id":"EFO_0003106"},
            {"label":"Cystic fibrosis", "id":"Orphanet_586"},
            {"label":"inflammatory bowel disease", "id":"EFO_0003767"},
            {"label":"Crohn's disease", "id":"EFO_0000384"},
            {"label":"ulcerative colitis", "id":"EFO_0000729"},
            {"label":"liver disease", "id":"EFO_0001421"},
            {"label":"rheumatoid arthritis", "id":"EFO_0000685"},
            {"label":"brain disease", "id":"EFO_0005774"},
            {"label":"multiple sclerosis", "id":"EFO_0003885"},
            {"label":"schizophrenia", "id":"EFO_0000692"},
            {"label":"Alzheimers disease", "id":"EFO_0000249"},
            {"label":"dementia", "id":"HP_0000726"},
            {"label":"Noonan syndrome", "id":"Orphanet_648"},
            {"label":"melanoma", "id":"EFO_0000756"},
            {"label":"leukemia", "id":"EFO_0000565"},
            {"label":"liver disease", "id":"EFO_0001421"},
            {"label":"Cowden syndrome", "id":"Orphanet_201"}
        ]
        "drugs":[
            {"label":"Rofecoxib", "id":"CHEMBL122"},
            {"label":"Regrelor", "id":"CHEMBL1162175"},
            {"label":"Metformin", "id":"CHEMBL1431"},
            {"label":"Acetaminophen", "id":"CHEMBL112"},
            {"label":"Thalidomide", "id":"CHEMBL468"},
            {"label":"Humira", "id":"CHEMBL1201580"},
            {"label":"Viagra", "id":"CHEMBL192"},
            {"label":"Tagrisso", "id":"CHEMBL3353410"},
            {"label":"Ivacaftor", "id":"CHEMBL2010601"},
            {"label":"Lyrica", "id":"CHEMBL1059"},
        ]
    },
```

**Comment by andrewhercules** [comment]
@mirandaio can we add two small tweaks to the CSS of this section to improve the responsiveness?

For the logo, can we update the `.jss19` class to `width: 100%` so that the SVG logo resizes properly on all devices?

![Screenshot 2020-06-10 at 09 59 54](https://user-images.githubusercontent.com/7490258/84259807-ebac8580-ab10-11ea-9f4f-35a49ad6e7c7.png)

And for the search input box, we set the `.jss24` class to `min-width:400px`, but this causes issues on screens with the input box overflow?

**Comment by mirandaio** [comment]
@andrewhercules responsiveness issues have been fixed. Closing this now.
