### ISSUE TITLE
describe how pathway and GO enrichment are calculated in batch search

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#107]
@elipapa commented on [Fri Jul 06 2018](https://github.com/opentargets/docs.targetvalidation.org/issues/4)

We need to give more detail on the Batch Search results page about how pathway and GO enrichment are calculated

---

@deniseOme commented on [Fri Jul 06 2018](https://github.com/opentargets/docs.targetvalidation.org/issues/4#issuecomment-402958812)

That's in my TODO list in addition to add info on chemical probes (although a blog is coming by by @MichaelaEBI), and include links to youtube video when appropriate. We might be able to try to link out to our blog posts from docs as well.

---

@elipapa commented on [Fri Jul 06 2018](https://github.com/opentargets/docs.targetvalidation.org/issues/4#issuecomment-402963723)

was mapping some of https://docs.google.com/spreadsheets/d/1gvS14oUAWEvnz61ELbe73L9PseeXdIBRrWxsoVpBlew/edit#gid=1901934433 in github

**Comment by deniseOme** [comment]
Sadly this has not been addressed, only upon request through support email when users ask for this information.

If a help page describing these steps is put in place in the future, please go to the 'Sent' folder in the Office365 space for support email. There you will find the stept-by-step instructions sent to the user and can use that to start drafting the help doc. Please note some changes may have to be included as OmniPath calls seem no longer work in production and may have been replaced in the new-generation UI of the Platform.

**Comment by AsierGonzalez** [comment]
@deniseOme is the length of the explanation suitable to be posted in this ticket? Alternatively could you paste it into a Google doc? I am concerned that we may not be able to extract the information from Office365 for different reasons.

**Comment by d0choa** [comment]
This work will soon be deprecated by the React application. No action is expected
