### ISSUE TITLE
Integrate Font-Awesome library and update icons used in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1072]
Currently, each profile page has an SVG icon that we use to represent each entity. 

As there will be other icons that we will want to use (e.g. on the homepage), it was suggested that we instead make use of [Font Awesome's official React component](https://fontawesome.com/how-to-use/on-the-web/using-with/react) and the [1500+ free icons](https://fontawesome.com/icons?d=gallery&m=free).

Can we please integrate Font Awesome into the React rewrite version using their component? If, however, there is a better, more maintained component library, please feel free to use it.

Once integrated, can we replace the following SVG icons with the free solid icons from Font Awesome?

| Entity  | Icon | Icon link |
| ----- | ----- | -----|
| target | dna | https://fontawesome.com/icons/dna?style=solid |
| disease | stethoscope | https://fontawesome.com/icons/stethoscope?style=solid |
| drug | prescription-bottle-alt | https://fontawesome.com/icons/prescription-bottle-alt?style=solid |

**Comment by andrewhercules** [comment]
Ticket moved to next sprint to account for work on updating data tables

**Comment by andrewhercules** [comment]
Ticket closed as work merged into `alpha`

**Comment by d0choa** [comment]
Search filters still using old icons:
 
<img width="227" alt="Screenshot 2020-07-17 at 18 36 08" src="https://user-images.githubusercontent.com/5097586/87814889-7e50ea80-c85c-11ea-861b-5e751d99d235.png">

**Comment by LucaFumis** [comment]
Doh! Well spotted @d0choa - the icons have now been updated in the code (not yet merged).

**Comment by andrewhercules** [comment]
Ticket closed as work completed and pushed to `alpha` branch
