### ISSUE TITLE
Create summary widget and detail view for Open Targets project Intranet links

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1087]
Once details of Open Targets projects and their relevant diseases and EFO IDs are available - see #1053 - we should create a summary widget and detail view on the disease profile pages for a partner-specific customisation.

Please see below for the [design spec](https://docs.google.com/presentation/d/1i101n-VdNaYJuaMVwSGulrEig7IgKEEpSKTP_iAJcKQ) for the summary widget and detail view.

**Summary widget**

In the summary widget, please display the number of active and closed projects.

![Screenshot 2020-06-02 at 12 57 06](https://user-images.githubusercontent.com/7490258/83517311-95b45e00-a4d0-11ea-9257-2abd40f98533.png)

**Detail view**

In the detail view, please display a data table with the project code, project name, disease, status, and link to the Open Targets Intranet.

![Screenshot 2020-06-02 at 12 57 50](https://user-images.githubusercontent.com/7490258/83517368-af55a580-a4d0-11ea-9f60-e44551cd9846.png)

*Note: if the data about Open Targets projects is **not** propagated through the ontology tree in #1053, we can drop the disease column. The column is only useful if a user is on the disease profile page for a parent diseases and there is/was an Open Targets project about a child disease and the data about the child disease project is available.

**Comment by mirandaio** [comment]
The projects widget can be found here https://custom--platform-app.netlify.app/disease/EFO_0003767

**Comment by andrewhercules** [comment]
@mirandaio looks great! 👍 

Unfortunately I made a mistake in the design spec. I thought the GraphQL API would return the mapped disease name, which would appear in the `Disease` column. This would be useful when showing projects where the mapped disease is a child term - for example, if a user is on the `intestinal disease` profile page, they could see projects for the child term `inflammatory bowel disease`. However, this data is not available.

And so, can you please remove the `Disease` column?

**Comment by mirandaio** [comment]
Yeah, no worries. Disease column has been removed now.

**Comment by iandunham** [comment]
Can we get the mapped disease names supplied? This would be useful

**Comment by andrewhercules** [comment]
@iandunham I have added the request for the mapped disease name and ID to epic #1114 as it will form part of a larger piece of work on deploying this feature in both public and private instances of the Platform
