### ISSUE TITLE
private instance: fewer associations than expected (18.06)

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#109]
Summary from support email conversation. Entire thread has been forwarded to core and is available in mail365. Talk to @deniseOme if you want to access the original mail365 messages.

* partner ran into memory issues when loading the data (18.06 JSON) 
* we recommended them to disable the global stats and provided the settings
* memory issue solved
* however results did not match the snapshot: they got fewer associations
* files provided with the numbers (DEV: data loaded via JSON files; PROD: from a server where they loaded the snapshot)

[index_comparison_DEV_PROD (2).xlsx](https://github.com/opentargets/platform/files/2339329/index_comparison_DEV_PROD.2.xlsx)

We believe that the discrepancy of DEV x PROD could be due to a bug we had in our 18.06 release, which affected the number of associations (fewer than expected).

Latest reply from us on the 31st Aug:

* we requested the following details:
- the pipeline commit used to produce the data
- the command line used to run the evidence step
- and the association step used to run the pipeline

@ElaineMcA @mkarmona, more details to follow.

**Comment by deniseOme** [comment]
@mkarmona @ElaineMcA, here are the details from the user:

* user executed the pipeline using the docker image built based on this commit:
https://github.com/opentargets/data_pipeline/commit/526d94ae6258c98b7d2b3c69305d0ce2c8853070

* these were their steps:
- checkout commit above
- made the changes to GLOBAL_STATS_* as discussed in previous emails
- build image: docker build -t mrtarget-image .
- evidence up to ddr steps are executed using the script below:

#!/bin/bash

DATA_RELEASE_VERSION=18.06
mkdir -p /ot_files/logs/$DATA_RELEASE_VERSION
echo "Running post processing steps" | tee /ot_files/logs/$DATA_RELEASE_VERSION/log_post.txt
steps=(evs \
as \
qc \
sea \
ddr)

for step in ${steps[*]}
do
echo "*************************************************************************"
echo "*************************************************************************"
echo "Running step --$step for data release version $DATA_RELEASE_VERSION"

echo "*************************************************************************"
echo "*************************************************************************"
docker run --rm --net=opentargetsautomation_ot-net \
-e ELASTICSEARCH_NODES=opentargetsautomation_es-ot_1:9200 -e ELASTICSEARCH_NODES_PUB=35.189.243.117:39200 \

mrtarget-image mrtarget --$step --log-level INFO $DATA_RELEASE_VERSION | tee -a /ot_files/logs/$DATA_RELEASE_VERSION/log_post_$step.txt

PS: user thanked the invitation to come over and work on the pipeline together. They think this is a good idea, and would be happy to come over for a few days. User will propose this to PIs.

**Comment by deniseOme** [comment]
Latest:

-----
Hi ????,

I have included in a previous email (please check the thread below) that "We believe that the discrepancy of DEV x PROD could be due to a bug we had in our 18.06 release, which affected the number of associations (fewer than expected)".

Hence our latest suggestion that the bug should no longer be in the 18.08 files.

Thanks and kind regards,
Denise

From: >
Sent: 11 September 2018 12:58
To: Open Targets Support
Cc: 
Subject: Re: Question regarding loading all .json files
 
Hi Denise,

I think it would be useful to have some explanation on why you think the issue would no longer be there. E.g. are there specific problems you identified and fixed between June and August that could explain the observed behavior? 

I just want to avoid getting into a trial and error cycle without a reasonable expectation for success, since running this pipeline takes quite some time. 

Thanks,
????

2018-09-11 12:20 GMT+02:00 Open Targets Support <support@targetvalidation.org>:

Dear ??,
Thanks for the reminder.
We have had a new release (18.08) and we were hoping that if Pieter updates his code to the latest version, the issue would no longer be there.

??, could you try that please? 

Thanks,
Denise

From: 
Sent: 10 September 2018 21:48
To: Open Targets Support; Pieter Lukasse
Cc: 
Subject: 
 
Hi Denise and OT Support,

 Any update on the issues ???? reported?  At ????, we are eager to start the effort of incorporating internal data into ??? hosted instance.  But first of all, I want to make sure that we can replicate the processing of JSON files from public data sources using the same pipeline.  So I greatly appreciate your assistance in resolving the discrepancies ???? reported.


From: Open Targets Support [mailto:support@targetvalidation.org] 
Sent: Friday, August 31, 2018 3:23 AM
To: ???
Cc: ????
Subject: Re: Question regarding loading all .json files

Thanks ??? for providing this so promptly.
I have shared the details with my colleagues and will get back to you as soon as we can.

Glad to hear you may be able to pay us a visit for an intensive pipeline running and bug troubleshooting here on the Genome campus.

Cheers,
Denise

**Comment by mkarmona** [comment]
sounds ok to me.

**Comment by deniseOme** [comment]
@mkarmona @ElaineMcA 

Latest reply from user:

----
yes, I saw that email. In this same email you also mentioned your colleagues would investigate further if I send the details regarding the exact version I used (which I did in my reply). So, in my last email I was referring to the results of this further investigation by your colleagues, since I have not received any updates on that yet. I was hoping to receive links to the issue and to the git commit that fixes the issue (these details help me understand the pipeline better and could even help me troubleshoot faster in case of a similar issue in the future). Thanks for your help!
----

I understand that having a new release would seem a waste of time trying to troubleshoot something going wrong with the new release; but it'd be useful to try to investigate the user's issue based on the specs they had provided.

If you think it's not worth it, I can get back to the user and thank them (again) for the specs and apologise for not having had a chance to investigate the issue and say we won't be able to investigate it.

**Comment by mkarmona** [comment]
Adam, would you mind please have a look at this issue and the issue
reported on GitHub pipeline about Pieter having less data than expected
with associations. I think it could be related to the bug I created when I
added the modification about removing routing and number of shards. he
provides all needed information to reproduce his cause

thank you.

**Comment by afaulconbridge** [comment]
Sure, I'll dig into this a bit - though I'll need a bit of time as I'm not familiar with the global stats yet.

Some of the steps use an API, or the "latest" release, of a resource, so as that resource updates the steps will produce different results. We're working on using JSON files that we can redistribute to ensure better reproducability. This includes:
18.06_efo-data
18.06_mp-data
18.06_reactome-data
18.06_uniprot-data

This might have then had downstream effects on other steps - for example, 18.06_evidence-data-generic depends on 18.06_efo-data. 

However, I agree that this doesn't explain the difference in associations. I'll try to reproduce the steps and see how it goes.

**Comment by afaulconbridge** [comment]
Okay, after looking into this further, it seems that there was a bug between 526d94ae6258c98b7d2b3c69305d0ce2c8853070 and f4ed7dca45c6671e46fec3030e408af1fd10536d related to how the Elasticsearch configuration was managed (routing of documents and number of shards). Unfortunately, the version your using is in the middle of that window, and so it suffers from this bug.

If you update to the more recent version (526d94ae6258c98b7d2b3c69305d0ce2c8853070) then it should be then you should get all the associations into Elasticsearch correctly. You'll still need to disable global stats to operate with lower memory requirements however.

If this problem persists for you with the alternative version, please open a new issue.
