### ISSUE TITLE
Update Comparative Genomics detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1096]
Prior to the `alpha` release, can we please do the following with the Comparative Genomics detail view (formerly known as Homology see #1095)?

1. Remove the descriptions on both the `Orthology table` and `Gene tree` tabs

2. Update the `Orthology table` tab label to `Homology table`

3. In the data table, please update the `Orthologue and ID` column heading to read `Homologue and ID`

**Comment by iandunham** [comment]
Will we also solve this problem where paralogues are given N/A in the table as their homology type?
![image](https://user-images.githubusercontent.com/1729980/84018203-ae60c000-a977-11ea-8fb6-26a19423d7f0.png)

**Comment by d0choa** [comment]
@cmalangone is currently pulling this info in #1047 to not depend on the Ensembl API anymore. 

Regarding, @iandunham comment paralogues are currently being listed as such in the new alpha version, but we'll have a proper review once the data goes through the GraphQL API (this week).
