### ISSUE TITLE
Update columns and links in Gene Ontology data table

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1097]
In the Gene Ontology data table, we display links to view the GO term using EBI Quick GO and AMIGO. However, this does not allow the user to scrutinise the underlying data.

Can we please update the Gene Ontology data table with the following changes?

1. Please drop the `View GO term in graph` column

2. Please add a column called `Annotation references` and for each row, please construct a link to EBI Quick GO using the following link structure:

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=<UNIPROT_ID>&goId=<GO ID FOR TERM>

So for example, for BRCA1 and plasma membrane, the link would be https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P38398&goId=GO:0005886

**Comment by javfg** [comment]
Paging @mkarmona!

For this one, I need the GraphQL API to provide "uniprot reference accession" field from `ProteinAnnotation` object in the `GeneOntology` object.

This is the part in the schema:
```
"Various protein coding annotation derived from Uniprot"
type ProteinAnnotations {
  "Uniprot reference accession"
  id: String!
```

**Comment by javfg** [comment]
There is no need to change the API in the end, the uniprotId is provided by the target profile page to the component.

But don't close the issue yet! (still working on it)
