### ISSUE TITLE
Work with SGC, Chemical Probes Portal, SGC Frankfurt 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#1127]
To address the user need below:

"As a chemist exploring chemical probes (both curated or predicted by computational methods) available in chemical tools/resources such as Chemical Probes Portal, I want to be able to find more about the target (s) that are modulated/inhibited by probes so that I can assess the function of the target/protein in preclinical stages of my drug discovery pipeline and guide downstream experiments"

Since we already collaborate with SGC, it's a good idea to work with them (as discussed in an email with @iandunham et all on the 18th Jun 2020) for them to include our target pages in their xref sections. Some examples of chemical probe pages below:

- [eleutherobin](https://www.chemicalprobes.org/eleutherobin/)
Under "Probe information" section and "Target and Probe Information" subsection

- [NMS-P118](https://probeminer.icr.ac.uk/#/P09874/1483285)
In the "Cross References" section

- [ABT-724](https://www.sgc-ffm.uni-frankfurt.de/#!specificprobeoverview/ABT-724)
In "Target information" they link to GeneCards. They may or may not want to link to Open Targets Platform as well. If not, we will be referenced in GeneCards this summer (see [541](https://github.com/opentargets/platform/issues/541#issuecomment-646659197))

- [PFI-5](https://www.thesgc.org/chemical-probes/PFI-5)
There is no obvious place to link from in this page as there is for the above tools. Would SGC create a new tab for target information? Or can they find a workaround to point to the target profile page in the Open Targets Platform from the existing overview section?

<img width="669" alt="Screen Shot 2020-06-19 at 16 01 11" src="https://user-images.githubusercontent.com/6472381/85147012-25366c80-b246-11ea-9484-8bb1dbbd2908.png">

Target file has been available for download in the [download page](https://www.targetvalidation.org/downloads/data) since Sep 2019 following discussion on [#657](https://github.com/opentargets/platform/issues/657)

**Comment by d0choa** [comment]
Thanks @deniseOme. Does this ticket require any action on our side?

**Comment by deniseOme** [comment]
Yes @d0choa, indeed. From our side, we need to decide who is going to liaise with all the suggested chemical resources above to check A) if they are willing to point to the protein target pages in Open Targets Platform and B) how going about doing so? Would point them to the downloads page suffice? Would we filter out to include only the protein targets their chemical probes are devised for? I suspect this will be on an ongoing basis of collaboration. Perhaps it can be done at the time we get the list of new chemical probes for the mapping @AsierGonzalez (or others) carry out for every release?

**Comment by AsierGonzalez** [comment]
Did this request get to us? It sounds like something that the chemical probes sites should be doing, which we can help them with as you suggest.

Just for your reference, SGC already link to us from TEPs in the "useful links" section:

- [MTHFR](https://www.thesgc.org/tep/mthfr)
- [TASK1](https://www.thesgc.org/tep/task1)
- [MLLT1](https://www.thesgc.org/tep/mllt1)

Probably it is easier to do it for TEPs, which focus on specific targets. Chemical Probes don't always have define dprotein targets, sometimes they target protein domains and families and we do the mapping to targets ourselves. If they did this themselves the data would be more reliable.

**Comment by AsierGonzalez** [comment]
Closing as no action is planned in the short term
