### ISSUE TITLE
Update CI / CD process for rewrite

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1129]
To ensure we set a solid foundation for the next phase of work on the Rewrite project, can we please update the CI / CD process so that we can identify problems prior to the Netlify deploy process?

**Comment by andrewhercules** [comment]
As Browserstack is part of the CI / CD process, can we please do the following?

- Update smoke tests to ensure broader coverage (e.g. check for name/description section, summary widget section and detail view section)
- Update browsers used to reflect average use case
- Temporarily remove IE11 from Browserstack tests as we know the app is not building in IE11 and showing <noscript> tag (see #976)
- Ensure Browserstack tests **pass** before deploy and not just complete (see #976)

**Comment by andrewhercules** [comment]
Ticket moved to BBC Proms sprint as dependent on #1152

**Comment by ktsirigos** [comment]
The entire deployment process is being changed with the rewrite.
