### ISSUE TITLE
Update table component to allow users to show more rows

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1130]
The current [data table component](https://github.com/opentargets/platform-app/blob/alpha/src/public/common/Table/README.md) defaults to showing 10 rows. However, in the current Angular production version of the Platform, we allow users to see 10, 25, 50, or 100 rows.

Can we please update the table component to allow users to view more than 10 rows at once?

**Comment by andrewhercules** [comment]
Also, if we plan to use the same data table component on the association page heat map, we may want to allow users to see up to 500 rows as we currently allow that in the Angular production version.

**Comment by d0choa** [comment]
As discussed, we want the default behaviour to allow the table to expand to show all requested rows. This will allow the user to observe a longer list of entries without extra interaction. Also the scrolling solution has some unintended consequences, such as when users scroll the page and fall into a nested scrolling.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and pushed to `alpha` branch
