### ISSUE TITLE
Remove react-selection and replace with material-ui-select

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1133]
As we have migrated to `material-ui-select` can we please ensure all components are using `material-ui-select` rather than `react-select`?

**Comment by d0choa** [comment]
@javfg where do we stand on this?

**Comment by javfg** [comment]
`react-select` was removed in the bundle size optimizations PR (https://github.com/opentargets/platform-app/pull/265), we can mark this one done.
