### ISSUE TITLE
Improve rare disease associations

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1134]

**Comment by DSuveges** [comment]
### Progression plan for the 20.09 release

**EVA**
* - [ ] JSON schema update merged into master.
* - [ ] New data generated by the provider following the updated schema.
* - [ ] Test if data passes validation.

**Uniprot**
* - [ ] Send request to provider.
* - [ ] New data generated by provider.
* - [ ] Test if data passes validation.

**ClinGen**
* - [ ] Update JSON schema.
* - [ ] Write evidence parser.
* - [ ] Test if evidence passes validation

**Gene2Phenotype**
* - [ ] Update parser to include all panels.

**Genomics England.**
* - [ ] 

### Test run pipeline

**Comment by ireneisdoomed** [comment]
As of Genomics England, the parser has been revamped and new 21252 evidences have been generated for the 20-11 release.

CNVs and STRs variations have yet to be implemented into the parser (reference issues #1273, #1274)
