### ISSUE TITLE
Look at overlap between Uniprot and Uniprot Literature

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1135]
Measure overlap between Uniprot genetic and literature associations to see if all genetic association is also a literature association as well.

**Comment by DSuveges** [comment]
Overlap in the association level (unique disease/trait pairs):

|source |  counts |  perc |  
|----|--- |  ----|
| both |  2834 |  40.67 |  
| literature |  2056 |  29.50 |  
| uniprot |  2079 |  29.83 |  
| **sum**  |  **6969** |  **100.00** |  


Overlap in the evidence level (same disease/trait association supported by the same pubmed ID):

| source  | counts  | perc  | 
|----|--- |  ----|
| both  | 2915  | 7.81  | 
  | literature  | 2177  | 5.83  | 
  | uniprot  | 32227  | 86.36  | 
  | **sum**  | **37319**  | **100.00**  |

**Comment by andrewhercules** [comment]
Re-assigning to 20.11 as UniProt evidence assessment is ongoing as noted in [our release intentions document](https://docs.google.com/document/d/1DcQ1CVg0jgQpJlKSvVCQkcYznwaAKiUcY0khToA0Ubg/edit#)

**Comment by d0choa** [comment]
The task is done and it won't lead to any follow up analysis. Uniprot (now gone since 20.09 because of overlap with EVA) and Uniprot literature are based on independent data sources
