### ISSUE TITLE
Improve annotation for EVA rare disease evidences

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1137]
Check the following and fix if required:

- [ ]  Variant ID changes
- [ ] Original trait/disease (source name)
- [x] Review status(stars)

**Comment by AsierGonzalez** [comment]
Related to #1013 (source names) and #1014 (variant ids)

**Comment by AsierGonzalez** [comment]
Kirill is working to include the star rating in ticket [eva-opentargets/issues#124](https://github.com/EBIvariation/eva-opentargets/issues/124)

**Comment by tskir** [comment]
@DSuveges @AsierGonzalez (copying @tcezard)

Here's distribution of all review status (star rating) values:
![star-rating](https://user-images.githubusercontent.com/10669118/88088520-735ec880-cb82-11ea-9a25-cdbf0c266746.png)

As you can see, sometimes the same star rating corresponds to several different review status values.

Please let me know how would you like me to proceed here, e.g., how to specify this in the evidence strings

**Comment by DSuveges** [comment]
It would be great if both the star rating and the review status could be added to the evidence string. 

Something like this:

```json
"clinvar_rating": {
    "star_rating": 1,
    "review_status": "criteria provided, single submitter"
}
```

Ideally the data could be added to the `.evidence.variant2disease` object, however as I have noticed `.variant2disease` is not present for all evidence.

**Comment by tskir** [comment]
@DSuveges (also copying @tcezard)

## Note on the `variant2disease` block

> Ideally the data could be added to the `.evidence.variant2disease` object, however as I have noticed `.variant2disease` is not present for all evidence (like in this one: [link](https://jsoneditoronline.org/#right=local.hubupa&left=cloud.39896993e98f462bbd08fdb65a179519)).

There are two types of evidence strings we submit:
* `genetic association` ones always include the `variant2disease` block. [Here is the JSON template we use.](https://github.com/EBIvariation/eva-opentargets/blob/master/eva_cttv_pipeline/evidence_string_generation/resources/CTTVGeneticsEvidenceString.json)
* `somatic_mutation` never contain this block. [See template here.](https://github.com/EBIvariation/eva-opentargets/blob/master/eva_cttv_pipeline/evidence_string_generation/resources/CTTVSomaticEvidenceString.json)

I don't think this distinction was a conscious decision. Somatic mutations are less abundant in ClinVar data, so when the `variant2disease` block was being added to the evidence strings a few years ago, the somatic mutation case was probably simply overlooked.

I could add the `variant2disease` block to somatic variants as well, in the same way it's done for germline variants. Please let me know if you'd like me to do this. Also, maybe you could take a look at the evidence string templates which I've linked above and tell me if there are some other things which don't make sense?

## JSON schema changes and the development approach

I'm happy to include the star rating + review status in the way which you described, into the `variant2disease` block. However, this would require schema changes on your side. Previously, @AsierGonzalez already created a branch in the schema repository to accommodate some changes required for modifying the EVA pipeline: https://github.com/opentargets/json_schema/tree/ag_eva_changes

So it would be great if you could:
* Rebase that branch compared to the main one (it's not a bit behind)
* Add changes required for this issue and others we are currently discussing (#1137, #1140)

At the same time, I can start making changes on my side, also in a separate branch. Then we can integrate the changes, test them, and do new schema & EVA pipeline releases at the same time.

**Comment by DSuveges** [comment]
Thanks for picking up the issue! On the long run, we would like to make the two types (`genetic_assocation` vs `somatic_mutation`) more similar, but making them completely aligned requires quite a bit of a work on both our pipelines, backend and frontend, so we'll do it later. 

> I could add the variant2disease block to somatic variants as well, in the same way it's done for germline variants. 

How would that look like for the other values of the somatic_mutations that are now stored in the evidence directly? Currently our pipelines relay on those.

> Previously, @AsierGonzalez already created a branch in the schema repository to accommodate some changes required for modifying the EVA pipeline:

Thanks for pointing to the branch, and create a new branch with those modifications already in. Keep you updated.

**Comment by DSuveges** [comment]
The new json_schema branch [ds_eva_changes_2](https://github.com/opentargets/json_schema/tree/ds_eva_changes_2) contains @AsierGonzalez's modifications + a numerous changes accommodating the requirements of #1137, #1139 and #1140.

The ClinVar rating object in the schema looks like this:


```json
"clinvar_rating": {
  "type": "object",
  "properties": {
    "star_rating": {
      "type": "number",
      "description": "ClinVar star rating of the variant. Int. 1-5",
    },
    "review_status": {
      "type": "string",
      "description": "ClinVar review_status of the variant.",
    }
  },
  "required": [
    "star_rating",
    "review_status"
  ]
},
```

Please let me know if there's any issue.

**Comment by tskir** [comment]
Thanks @DSuveges, I'll proceed with implementation on our side and will let you know how it stacks together with the schema changes

**Comment by tskir** [comment]
@AsierGonzalez @DSuveges This is now also implemented and undergoing our internal review (https://github.com/EBIvariation/eva-opentargets/pull/148).

The ClinVar star rating (from 0 to 4) and the review status (one of a few possible values) are now extracted from ClinVar and added to the evidence strings.

I also submitted a PR to JSON schema repository to verify the range of review status values with an enum: opentargets/json_schema#96. Since we're going to use that for scoring, enum seems appropriate.

**Comment by tskir** [comment]
Also, note that given that the `clinvar_rating` field is inside `variant2disease` block, it will **not** be present for somatic variants, even though we have that information in source ClinVar data. I remember that on several occasions we discussed the possibility to bring `genetic_assocation` vs `somatic_mutation` closer together in terms of representation. Do we have an issue for tracking that?

**Comment by tskir** [comment]
Also also, I noticed that in #1140 (mode of inheritance) the decision was made to output it for _both_ evidence string types: it goes into `.evidence.variant2disease` for genetic_association and into `.evidence` for somatic_mutation. Do we maybe want to do something similar here?

**Comment by AsierGonzalez** [comment]
> I remember that on several occasions we discussed the possibility to bring genetic_assocation vs somatic_mutation closer together in terms of representation. Do we have an issue for tracking that?

I just created one, see #1185 

> Also also, I noticed that in #1140 (mode of inheritance) the decision was made to output it for both evidence string types: it goes into .evidence.variant2disease for genetic_association and into .evidence for somatic_mutation. Do we maybe want to do something similar here?

That would be ideal if you can do it.

**Comment by tskir** [comment]
Following our discussions, I have updated our code to support this section for `somatic_mutation` evidence strings as well (directly in the `evidence` section). This has been reviewed and merged on our side.

I have also updated the PR https://github.com/opentargets/json_schema/pull/96 to reflect the necessary changes in the schema.

**Comment by AsierGonzalez** [comment]
PR has been merged

**Comment by AsierGonzalez** [comment]
The changes in this ticket have been implemented so I'm closing it. Further changes can be tracked in thier respective tickets, namely #1013, #1014 and #1185
