### ISSUE TITLE
Discrepancies between Production and Alpha Platform sites for COVID-19 drug data

### ISSUE THREAD

**Issue by emcdonagh-OT** [opentargets/platform#1142]
At here: https://www.targetvalidation.org/disease/MONDO_0100096 
there are 758 entries for drugs, and in the tsv download

On alpha there are 396:
https://alpha.targetvalidation.org/disease/MONDO_0100096

I'm sure there is a reason for this, but wanted to check if alpha was missing anything?

**Comment by d0choa** [comment]
If you notice the number of targets and drugs is the same. The difference is that the current production lists every trial as an individual entry, whereas Alpha tries to remove some of the redundancy by aggregating rows and having a list of trials with overlapping information in the last column.

The information in both cases should be the same. Please reopen if this is not the case.
