### ISSUE TITLE
Do not hide "Activity" column in Known Drugs table for small screens

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1143]
As raised by @emcdonagh-OT, users might want to use this information to filter or interrogate the data. Although this information is partially represented in the MoA column, hiding the information on small screens ofuscates valuable information.

Could we please, remove the hiding of the `Activity` column on small screens for all Known Drugs / Clinical precedence widgets?

**Comment by andrewhercules** [comment]
@LucaFumis can we please include this for the next sprint - BBC Proms - ending on 5 August 2020?

**Comment by mirandaio** [comment]
Fixed in this PR https://github.com/opentargets/platform-app/pull/268 in the `beta` branch.
