### ISSUE TITLE
URL to platform URL from documentation does not work

### ISSUE THREAD

**Issue by emcdonagh-OT** [opentargets/platform#1144]
https://docs.targetvalidation.org/programmatic-access/rest-api
URL/link to rest-api from the documentation page is broken: https://platform-api.opentargets.io/v3/platform

**Comment by d0choa** [comment]
We have some significant issues with the documentation of the python API and we will approach them as we continue with the API refactoring.

However, I believe this issue in particular is not a problem. The URL is the actual API as you can see when completing the query:

https://platform-api.opentargets.io/v3/platform/public/association/filter

We could discuss if there is a better way to minimise confusion or removing links from documentation that might lead you to visit the URL in the browser.

**Comment by JarrodBaker** [comment]
It's a little confusing that the endpoint is displayed quite prominently on the page, and we don't say that it has to be parameterised until further down. Maybe in the first reference we can change `https://platform-api.opentargets.io/v3/platform` to `https://platform-api.opentargets.io/v3/platform/<method>/<query>` and disable it as a hyperlink?

**Comment by d0choa** [comment]
Sounds good, would this solve your issue @emcdonagh-OT ?

**Comment by emcdonagh-OT** [comment]
Yes...I think if it was disabled as a hyperlink that would solve it...thanks!
