### ISSUE TITLE
Integrate drop-down filters on OT data table component

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1145]
Based on the feedback from the `alpha` release, we should re-implement the drop-down filter feature for data tables and update the table component to allow customised settings for which columns should have drop-down filters.

@fedde-s and @forus submitted a PR - https://github.com/opentargets/platform-app/pull/160 - to move the filters in the Pathways data table to their own component.

Can we please investigate if it is possible to reuse this code to implement drop-down filters on the OT data table component created by @javfg?

Note: @javfg has started this on a separate branch and he will push to GitHub so work can continue

**Comment by fedde-s** [comment]
Other than applying only to client-side filtering, I think the wrapper component relied on just two assumptions about the column specification objects passed to the underlying table:
1. it accepts a render prop (a component/a function that returns JSX) named `renderFilter` that will be rendered below the column heading, and
2. it does not need a prop named `filterable` to be passed to it for any reason

As long as these things hold, the wrapper should just work as-is, and pass all remaining props down unchanged. As for server-side filtering, I don't see how it could benefit from reusing any part of the component other than the API conventions/prop names.

**Comment by ktsirigos** [comment]
The table component has been deprecated.

**Comment by fedde-s** [comment]
Oops, I just noticed that the pull original message here said

> investigate if it is possible to reuse this code to implement drop-down filters on the OT data table component created by `@javfg`

But that is exactly what my code already did.

**Comment by fedde-s** [comment]
Either way, if Javier's component has been deprecated too now, this should indeed be closed :+1:

**Comment by andrewhercules** [comment]
@fedde-s, currently we are making further improvements to the data table component based on front-end and API changes and so the original version of the table component built by Javier (and referenced by Kostas) has been "deprecated" pending further iterations and data changes.

**Comment by fedde-s** [comment]
Thanks for the clarification! I believe you previously said that you were aiming to factor out the practice of fetching all data to the frontend and then paging over it from there in those further iterations; the code I proposed only applied to that scenario, so would indeed be useless if that scenario no longer occurs.
