### ISSUE TITLE
Create persistent links to the latest associations and evidence files

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1146]
The EBI Search team is now using the Platform associations data in their search index to display gene-disease associations and we are in discussions about them using the evidence data to index the Locus2Gene data for links to the Genetics Portal. To ensure that their index remains up-to-date, they would like to periodically download the most recent associations and evidence files.

As such, can we please create the following persistent links that point users to the most recent associations and evidence file?

| Persistent link | Example of most recent file |
| ----- | ----- |
| https://www.targetvalidation.org/downloads/data/associations/latest | https://storage.googleapis.com/open-targets-data-releases/20.06/output/20.06_association_data.json.gz | 
| https://www.targetvalidation.org/downloads/data/evidence/latest | https://storage.googleapis.com/open-targets-data-releases/20.06/output/20.06_evidence_data.json.gz |

As the association and evidence file links for Google Cloud Platform have a consistent naming convention (thank you @cmalangone!), the front-end will only require the most recent release number (e.g. 20.06). This can be obtained from the `/platform/public/utils/stats` endpoint in the `data_version` as noted by @LucaFumis.

**Comment by andrewhercules** [comment]
Moving to 20.11 release and will be implemented in React rewrite version of Platform

**Comment by d0choa** [comment]
I'm rescoping this for the rewrite

**Comment by andrewhercules** [comment]
Ticket closed as JSON file produced in https://github.com/opentargets/platform/issues/1411 can be utilised by EBI search team to build a cron job that periodically checks and downloads and the most recent associations files for the EBI Search index
