### ISSUE TITLE
Include references in Indications data table on drug profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1149]
As noted in #929, `indication_refs` will be available in the ElasticSearch index after the pipeline has run for 20.09.

Once the data is available, we should update the GraphQL API and front-end UI to expose this data.

**Comment by JarrodBaker** [comment]
The field has the following format: 
`          "indication_refs" : [
            {
              "ref_type" : "DailyMed",
              "ref_url" :  "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?06c485cd-ee30-44f2-be63-bb98f8d1a907",
              "ref_id" : "06c485cd-ee30-44f2-be63-bb98f8d1a907"
            }, 
... ,
            {
              "ref_type" : "ClinicalTrials",
              "ref_url" :  "https://clinicaltrials.gov/search?id=%22NCT01908452%22",
              "ref_id" : "NCT01908452"
            }]`
There is a VM `cm-jb-es` in the _open-targets-eu-dev_ project. It has an Elasticsearch instance which has the updated drug index (jb_drug-data) in case you needed to test against it.

**Comment by d0choa** [comment]
@andrewhercules to provide more details on indications refs

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/285
