### ISSUE TITLE
Decide fate of data_pipeline/mrtarget/resources/evidences_sources.txt

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#115]
When running the data_pipeline --val step, one can either list all data files or provide no files at all and then all files listed in data_pipeline/mrtarget/resources/evidences_sources.txt will be processed. We should look at whether we want to keep this file and if so, it should get updated for each release.

**Comment by afaulconbridge** [comment]
After discussion, we think the best idea would be to remove this file from the git repository. We want users to explicitly point to different sources, so they know exactly what they are using (and they can tell us that if they need to). 

Instead, we will create a combined evidence & annotation sources file per release in a google bucket. This per release combined sources file can then be referenced from e.g. blog posts, and should help be more reproducible. In future, other files or urls can be added to the same sources file in future releases (e.g. specific ontology versions, api call outputs, etc).

**Comment by afaulconbridge** [comment]
As part of opentargets/platform#146 `evidences_sources.txt` will get folded into the wider configuration file and therefore remove that way. I'll keep this ticket open for now, but when opentargets/platform#146 is done this should also be completed.

**Comment by afaulconbridge** [comment]
Done as part of opentargets/data_pipeline#444
