### ISSUE TITLE
Include link to Open Targets COVID-19 target prioritisation tool in React rewrite application 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1151]
Given the work done on the Open Targets COVID-19 Target Prioritisation Tool, we should construct a link to it from the Alpha version of the React Platform so that users can conduct a more in-depth exploration about potential COVID-19 drug targets.

Further details on implementation in React app TBC

**Comment by andrewhercules** [comment]
As noted by @d0choa, EFO is pulling a more granular characterisation of COVID-19 - see https://github.com/EBISPOT/efo/issues/803.

> MONDO:0100139 asymptomatic COVID-19 infection
> MONDO:0100140 mild COVID-19 infection
> MONDO:0100141 moderate COVID-19 infection
> MONDO:0100142 severe COVID-19 infection
> MONDO:0100143 critical COVID-19 infection

As such, the link to should appear on all relevant COVID-19 profile pages.

**Comment by ktsirigos** [comment]
Link no longer needed.
