### ISSUE TITLE
Fix external links in Sources column in Cancer Biomarkers data table

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1153]
Upon review of the Cancer Biomarkers data table, there are two issues that the front-end should resolve prior to the next beta release.

### Display publication links

In the Sources column of the Cancer Biomarkers data table in the alpha version of the React Platform, there are instances where the relevant publication is not shown (e.g. [KIT](https://alpha.targetvalidation.org/target/ENSG00000157404)):

![Screenshot 2020-07-17 at 11 07 22](https://user-images.githubusercontent.com/7490258/87775263-bab12600-c81d-11ea-9432-9b0d61bb9b39.png)

This is because the publications are found in `target.CancerBiomarkers.rows.pubmedIds` while the other sources (e.g. FDA or conference links) are found in `target.CancerBiomarkers.rows.sources`.

Can we please update the data table to display the publication links also?

Please note that in some cases, there may be both a source and a publication - see below for an example involving [BRCA2](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0Aquery%20targetq%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000139618%22)%7B%0A%20%09%09cancerBiomarkers%7B%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20drugName%0A%20%20%20%20%20%20%20%20sources%7B%0A%20%20%20%20%20%20%20%20%20%20link%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20pubmedIds%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%20%0A%20%20%7D%0A%7D%0A):

![Screenshot 2020-07-17 at 11 13 31](https://user-images.githubusercontent.com/7490258/87775823-a3266d00-c81e-11ea-916b-2b58d624df34.png)

### Separate multiple links

With some targets, there are multiple entries in `target.CancerBiomarkers.rows.sources`; however, the links are not separated in the UI, leading to confusion that there are multiple links available (e.g. [BRCA2](https://alpha.targetvalidation.org/target/ENSG00000139618))

![Screenshot 2020-07-17 at 11 08 21](https://user-images.githubusercontent.com/7490258/87775459-0d8add80-c81e-11ea-9b5d-5256fc5b9019.png)

Can we please separate multiple entries so that it is clear that there are 2 or more links? And to distinguish between the links and keep consistent with other sections, we could use the "drawer" element of the data table, similar to how we show underlying data about clinical trial records in the Known Drugs column? (see https://github.com/opentargets/platform-app/pull/163)

**Comment by mirandaio** [comment]
Fixed in https://github.com/opentargets/platform-app/pull/277
