### ISSUE TITLE
Fix data issues in Cancer Biomarkers detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1156]
Upon review, it looks like the React logic used for the Cancer Biomarkers detail view needs to be updated to resolve a bug.

In the `alpha` version, there are rows where data is duplicated. For example, [BRCA2](https://alpha.targetvalidation.org/target/ENSG00000139618) has a table where 10 of 11 rows are the same. 

![Screenshot 2020-07-22 at 15 54 44](https://user-images.githubusercontent.com/7490258/88191778-b88f0300-cc33-11ea-99e7-a71180766893.png)

However, in the current production Angular version of the Platform, the [profile page for BRCA2](https://www.targetvalidation.org/target/ENSG00000139618) displays the correct data with 11 rows that each have unique data.

![Screenshot 2020-07-22 at 15 54 24](https://user-images.githubusercontent.com/7490258/88191861-c9d80f80-cc33-11ea-90b7-ddc3a6b59005.png)

When looking at the [GraphQL for BRCA2](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0Aquery%20targetq%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000139618%22)%7B%0A%20%09%09cancerBiomarkers%7B%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20drugName%0A%20%20%20%20%20%20%20%20sources%7B%0A%20%20%20%20%20%20%20%20%20%20link%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20pubmedIds%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%20%0A%20%20%7D%0A%7D%0A), the correct data is returned and so the issue is likely with the React logic selecting and displaying the incorrect data.

Can you please investigate this issue and apply a fix that ensures the correct data is displayed in the data table? 

This same issue is also seen with other targets, including [KIT](https://alpha.targetvalidation.org/target/ENSG00000157404), [KRAS](https://alpha.targetvalidation.org/target/ENSG00000133703), and [EGFR](https://alpha.targetvalidation.org/target/ENSG00000146648).

**Comment by mirandaio** [comment]
Fixed in https://github.com/opentargets/platform-app/pull/277
