### ISSUE TITLE
Ontology review: Brain disease under 'Other diseases'

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#116]
@deniseOme commented on [Mon Oct 16 2017](https://github.com/opentargets/data_pipeline/issues/195)

One user pointed out we list glioma and astrocytoma under both 'neoplasm' and 'other':

https://www.targetvalidation.org/disease/EFO_0005543
https://www.targetvalidation.org/disease/EFO_0000272

https://www.targetvalidation.org/disease/other

This doesn't seem to be correct. Or is it?

---

@iandunham commented on [Mon Oct 16 2017](https://github.com/opentargets/data_pipeline/issues/195#issuecomment-336879436)

Seems to comfrom "Brain disease" being under "Other Disease". This doesn't seem right since Brain disease has it's own better parent "Nervous system disease". Check with Gautier and Sira but this seems odd. As an aside we should review a bunch of these "other" diseases - parathyroid, thyroid, lymphatics disease all seem wrong. 

---

@gkos-bio commented on [Wed Aug 15 2018](https://github.com/opentargets/data_pipeline/issues/195#issuecomment-413218784)

Need to be fixed for release 18.10.
Adam and I should sit down to modify the EFO import to classify brain disease under nervous system disease.

**Comment by afaulconbridge** [comment]
This needs to be coordinated with #122 to make sure we fix it permanently.

**Comment by afaulconbridge** [comment]
Solved in EFO3 prototype at https://efo3.targetvalidation.org/disease/EFO_0005774 Closing this ticket
