### ISSUE TITLE
Automate deployment of new dataset revisions

### ISSUE THREAD

**Issue by javfg** [opentargets/platform#1160]
On a new release in the [opentargets/ot_covid19](https://github.com/opentargets/ot_covid19) repo, a GitHub action should be triggered that performs the following:

* Fetch the release asset containing the dataset: `https://github.com/opentargets/ot_covid19/releases/download/{VERSION_TAG}/targets_integrated_data.json.gz`

* Find out the revision number for the frontend: [https://storage.googleapis.com/open-targets-covid-prioritisation/current_revision.json]()

* Upload both the dataset and a new `current_revision.json` file to the `open-targets-covid-prioritisation` Google Storage bucket.

**Comment by ktsirigos** [comment]
not a priority
