### ISSUE TITLE
Implement interactions GraphQL endpoints

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1162]
After a series of iterations including Data, BE and FE, this is the current draft (documented) of the GraphQL schema for interactions.

The general functionality that we want to resolve has 3 layers:
- Data retrieved about interaction resources
- Data retrieved when Target (interactor A) + resource are fixed
- Data retrieved when Target(interactor A) + resource + interactor B are fixed 

Minor things might require adjustments. Please consult with me if you have any doubts.

Important considerations:
- We want the queried target to become interactor A in all cases. That might require a solution in the BE (e.g. duplicating the data to fill the full matrix) and making sure the appropriate fields referring to A and B are not confused.
- The `InteractionEvidence` endpoint does work for all 4 resources but it has quite a lot of optional fields.
- Ideally we want to make the `Species` endpoint compatible with other resources (e.g. Homology)
- We are working under the assumption that interactor A will always be a human protein. Once this is fixed, interactor B can be human or from other species. That might make some interactor Bs not resolvable into target objects. Hopefully, this schema resolves the issue.
- Some of the syntax might be incorrect - that will be my mistake. Feel free to edit

```scheme
type Target {
  "Open Targets target id"
  id: String!
	
  "NOTE: All the other fields go here"
  
  "Interacting targets by resource"
  "NOTE: the Target entity will always become interactor A - that might require to duplicate BE data or do some smart queries. Also to adjust accordingly all fields related to A and B"
  interactingTargetsBySource(resource: [interactionResourceInput!]!): InteractionSet
}

"Input for interaction resources"
input interactionResourceInput {
  id: String!
  version: String!
}

"Interaction resources"
type interactionResources{
  "Resource name"
  source_database: String!
  "Resource version"
  database_version: String!
}

"Set of interacting targets"
type InteractionSet{
  "Number of interacting proteins"
  uniqueInteractors: Long!
  "Number of interactions"
  count: Long!  
  "Interaction entries"
  rows: [Interaction!]!
}

"Target molecular interaction entry"
type Interaction{
  "Interactor A reported identifier"
  "Warning: Some might not be resolvable human targets"
  intA_sourceID: String!
  "Interactor A identifier resource"
  intA_source: String!
  "Interactor A biological role in interaction"
  intA_biological_role: String
  "Interactor B object (when human)"
  "Warning: Some might not be resolvable (human) targets"
  intB: Target
  "Interactor B reported identifier"
  intB_sourceID: String!
  "Interactor B identifier resource"
  intB_source: String!
  "Interactor B organism"
  intB_species: Species!
  "Interactor B biological role in interaction"
  intB_biological_role: String
  "Causal interaction"
  causal_interaction: Boolean
  "Interaction score"
  interaction_score: Float
  "Number of evidence supporting interaction"
  evidenceCount(partner: ensembl_id!): Long
  "Interaction evidence"
  evidence(interactorB: intB_sourceID!): [InteractionEvidence!]!
}

"Species entry"
type Species{
  "Species scientific name"
  scientific_name: String
  "NCBI taxonomy id"
  taxid: String
  "Species common name"
  mnemonic: String
}

"Interaction evidence"
type InteractionEvidence{
  "Datasource interaction ID"
  interaction_identifier: String
  "Pubmed id on publication"
  pubmed_id: String
  "Taxonomy id of organism in which experiment was performed"
  host_organism_tax_id: String
  "Scientific name of organism in which experiment was performed"
  host_organism_scientific_name: String
  "Type of molecular interaction"
  interaction_type_short_name: String
  "Type of molecular interaction MI identifier"
  interaction_type_mi_identifier: String
  "Interaction detection method MI identifier"
  interaction_detection_method_mi_identifier: String
  "Interaction detection method short name"
  interaction_detection_method_short_name: String
  "Detection method short name for interactor A"
  participant_detection_method_short_name_A: String
  "Detection method MI identifier for interactor A"
  participant_detection_method_mi_identifier_A: String
  "Detection method short name for interactor B"
  participant_detection_method_short_name_B: String
  "Detection method MI identifier for interactor B"
  participant_detection_method_mi_identifier_B: String
  "Expansion method short name"
  expansion_method_short_name: String
  "Expansion method short name"
  expansion_method_mi_identifier: String
  "Evidence score"
  evidenceScore: Long
}
```

**Comment by cmalangone** [comment]
The repositories involved are
*) platform-input-support: It will retrive and generate the input files.
*) platform-etl-backend: ETL step to get the input files and generate two indices.
The indices should be 
   otnetworks ("intATarget", "intBTarget","intABiologicalRole", "intBBiologicalRole", "interactionResources")
   otnetworksEvidences("intATarget", "intBTarget","intABiologicalRole", "intBBiologicalRole", "interactionResources", "evidences", "intA_sourceID", "intA_source", "intB_source", .....)
*) platform-api-beta: add the endpoint for retrieving the info

**Comment by d0choa** [comment]
Parts of the "Interaction evidence" (InteractionEvidence) object will change when the new fixes from Intact team are implemented.

In particular, the next fields could be affected:

```
"Detection method MI identifier for interactor A"
participant_detection_method_mi_identifier_A: String
"Detection method short name for interactor B"
participant_detection_method_short_name_B: String
"Detection method MI identifier for interactor B"
participant_detection_method_mi_identifier_B: String
```

**Comment by cmalangone** [comment]
Pull request to platform-etl-backend.
