### ISSUE TITLE
Missing target descriptions (e.g. ABO)

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1163]
As reported by David H. some targets (e.g. ABO) have missing descriptions in [production](https://www.targetvalidation.org/target/ENSG00000175164) and [alpha](https://alpha.targetvalidation.org/target/ENSG00000175164).

The FE uses the (GraphQL) `proteinAnnotations.functions` endpoint which at the moment is an empty list for ABO.
However, the information is available on the [Uniprot page](https://www.uniprot.org/uniprot/P16442) under the Function section.

All these evidence points to a problem on our pipeline when parsing the Uniprot information. This problem will affect both production and alpha.

**Comment by cmalangone** [comment]
@d0choa : can you please a target with this type of data?

**Comment by d0choa** [comment]
ESR1 [example query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20targetq%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000091831%22)%7B%0A%20%20%20%20approvedName%0A%20%20%20%20approvedSymbol%0A%20%20%20%20proteinAnnotations%7B%0A%20%20%20%20%20%20functions%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=targetq)

**Comment by cmalangone** [comment]
@JarrodBaker Can you please verify if this issue is still present and eventually talk with @d0choa about the new solution?

**Comment by d0choa** [comment]
I can confirm the problem is still there. Very likely a problem parsing the information from Uniprot in the old pipeline. Something to watch when the new ETL is implemented
