### ISSUE TITLE
Benchmarking ClinGen scores

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1166]

**Comment by DSuveges** [comment]
The table below shows the evidence distribution in the ClinGen data set stratified by the `confidence` field (which is the basis of the scoring):

| confidence class     |   score |   evidence count | count % |cumulative % |
|:---------------------|--------:|-----------------:|--------------:|------------------:|
| Definitive           |    1    |              528 |          53.9 |              53.9 |
| Strong               |    0.75 |               19 |           1.9 |              55.8 |
| Moderate             |    0.5  |              100 |          10.2 |              66   |
| Limited              |    0.25 |              162 |          16.5 |              82.6 |
| Disputed             |    0.1  |               69 |           7   |              89.6 |
| Refuted              |    0.05 |               10 |           1   |              90.6 |
| No Reported Evidence |    0.01 |               92 |           9.4 |             100   |

The table below shows the unmber of unique targets in each confidence category and now many of them can be found in the Pharmaproject dataset:

| confidence           |   target_cnt |   poscon_targets |   approved_targets |
|:---------------------|-------------:|-----------------:|-------------------:|
| Definitive           |          498 |              126 |                 36 |
| Strong               |           19 |                6 |                  2 |
| Moderate             |           99 |               17 |                  6 |
| Limited              |          152 |               35 |                 10 |
| Disputed             |           63 |               17 |                 10 |
| Refuted              |           10 |                2 |                  0 |
| No Reported Evidence |           48 |               16 |                  8 |

The table below shows the unmber of unique diseases in each confidence category and now many of them can be found in the Pharmaproject dataset:

| confidence           |   disease_cnt |   poscon_diseases |   approved_diseases |
|:---------------------|--------------:|------------------:|--------------------:|
| Definitive           |           333 |                 7 |                   3 |
| Strong               |            14 |                 1 |                   0 |
| Moderate             |            52 |                 1 |                   0 |
| Limited              |            55 |                 2 |                   1 |
| Disputed             |            23 |                 2 |                   2 |
| Refuted              |             9 |                 1 |                   1 |
| No Reported Evidence |            11 |                 1 |                   0 |

The last table shows the number of associations in each category and how many of them were found in the pharmaproject dataset:

| confidence           |   evidence_count |   poscon_associations |   approved_associations |
|:---------------------|-----------------:|----------------------:|------------------------:|
| Definitive           |              528 |                     3 |                       1 |
| Strong               |               19 |                     0 |                       0 |
| Moderate             |              100 |                     0 |                       0 |
| Limited              |              162 |                     1 |                       0 |
| Disputed             |               69 |                     0 |                       0 |
| Refuted              |               10 |                     0 |                       0 |
| No Reported Evidence |               92 |                     0 |                       0 |

**Comment by DSuveges** [comment]
As the overlap between the ClinGen data and the pharmaproject was not large enough to properly benchmark scores. We rater compare the scoring performance against literature data.

The 20.09 processed evidence file was used as a source, `.type == "literature"` as filter (evidence source is epmc). Number of evidence in the set: 7,640,374, representing 1,092,067 unique target/disease pairs. 

### Round 1

Without pooling evidences together, a 0.5 score threshold was applied to filter high confidence target/disease pairs. This resulted in 47,300 evidence strings representing 27,402 unique target/disease pairs. When I checked how many of these evidences are recapitulated by the clingen data and with what average scores I got the following table:


| confidence           |   evidence_count |   ClinGen score |   Evidence in literature |   Mean literature score |
|:---------------------|-----------------:|--------:|------------------:|-------------------------:|
| Definitive           |              528 |    1    |                32 |                 0.659018 |
| Strong               |               19 |    0.75 |                 1 |                 0.504    |
| Moderate             |              100 |    0.5  |                 1 |                 0.69     |
| Limited              |              162 |    0.25 |                 0 |               nan        |
| Disputed             |               69 |    0.1  |                 1 |                 0.612    |
| Refuted              |               10 |    0.05 |                 1 |                 0.614    |
| No Reported Evidence |               92 |    0.01 |                 0 |               nan        |

**Comment by d0choa** [comment]
just to clarify, only 36 clingen target-disease pairs have evidence in OT literature, isn't it?
