### ISSUE TITLE
Gather raw data for drug dataset creation

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1169]
Update [platform input support](https://github.com/opentargets/platform-input-support) such that the drug step calls the ElasticSearch provided by ChEMBL and saves the results into Google Cloud Storage.

## ChEMBL dataset

The primary data source for the drug index is the ChEMBL database. Currently this data is collected through HTTP API calls. ChEMBL now maintain an ElasticSearch (version 7.5.2) instance with the data loaded as documents.

ChEMBL's Elasticsearch includes the following indices:

```
chembl_27_target_relation
chembl_27_mechanism_by_parent_target
chembl_27_mechanism
chembl_27_compound_structural_alert
chembl_27_target_component
chembl_27_biotherapeutic
chembl_27_binding_site
chembl_27_protein_class
chembl_27_molecule_form
chembl_27_document_similarity
chembl_27_assay
chembl_27_compound_record
chembl_27_target
chembl_27_assay_class
chembl_glados_tiny_url
chembl_27_tissue
chembl_27_drug_indication_by_parent
chembl_27_drug
chembl_27_activity
chembl_27_cell_line
chembl_27_source
chembl_27_go_slim
chembl_27_molecule
chembl_27_document
chembl_27_atc_class
chembl_27_drug_indication
chembl_27_metabolism
chembl_27_chembl_id_lookup
chembl_27_organism
chembl_27_activity_supplementary_data_by_activity
```
A simplified representation of each can be found on [Google Drive](https://drive.google.com/drive/u/0/folders/1HaMbkPuVbppnlOZHsG10Wy--EZ9nKSGm). The outline of the indices include the field names and the types. This data can be regenerated with [this code](https://gist.github.com/JarrodBaker/4034cd046e4f169e3b458b4acb81c164) 

## Implementation notes

- There is an Elasticsearch library for Python which provides an interface to Elasticsearch instances [docs](https://elasticsearch-py.readthedocs.io/en/master/index.html)
- See the [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-fields.html#search-fields) and [python library docs](https://elasticsearch-py.readthedocs.io/en/master/api.html) for accessing only a subset of fields on the search objects.
- The `data-pipeline` currently uses the following sources for the drug step:
  - component (ChEMBL)
  - indication (ChEMBL)
  - mechanism (ChEMBL)
  - molecule (ChEMBL)
  - target (ChEMBL)
  - adverse events (FAERS)
  - drugbank (Drugbank)

### Drugbank 

The drugbank source is a list of drugbank ids cross-referenced with ChEMBL ids in the `cross_references` field. [Code](https://github.com/opentargets/data_pipeline/blob/795c99c06873156dd10eacbb0bf4ea1dafcda16d/mrtarget/modules/Drug.py#L727)

The drugbank data ([here](gs://open-targets-data-releases/20.06/input/annotation-files/drugbank-2020-06-01.csv.gz)) has the following shape:

```
From src:'1'    To src:'2'
CHEMBL614       DB00339
CHEMBL1269257   DB12309
CHEMBL295698    DB05667
CHEMBL1427      DB04076
CHEMBL1289601   DB09078
CHEMBL1201766   DB06716
CHEMBL113       DB00201
CHEMBL336908    DB02662
CHEMBL169046    DB04705

```
There are 7618 CHEMBL IDs present in the Drugbank lookup table.

### Indication

> `indications` in `data_pipeline`

See `Drug.py` line 760

- `molecule_chembl_id`
- `efo_id`
- `efo_label`: currently the pipeline defers to the Elasticsearch EFO index.
- `efo_uri`: similarly we currently defer to the ES index. 
- `max_phase_for_ind`
- `indication_refs`
  - `ref_type`
  - `ref_id`

### Mechanism

> `mechanisms` in `data_pipeline`

See `Drug.py` line 776. Uses ChEMBL id as key

- `molecule_chembl_id`
- `target_chembl_id`
- `target_components` -- _part of Target?_
  - `accession`: Looks like this should be an ensembl id? see lines 421-437. It checks uniprot too to see if it can be found
    there.  
- `action_type`
- `mechanism_of_action`: `description` in output
- `mechanism_refs`
  - `ref_type`
  - `ref_id`
- `record_id` _used in another `data_pipeline` step_

### Molecule

> `mols` in `data_pipeline`

- `molecule_chembl_id`
- `molecule_hierarchy` - This seems to be used so children can be properly linked to their parent. 
  - `parent_chembl_id`
- `internal_compound`
- `molecule_type`
- `pref_name`
- `first_approval`
- `max_phase`
- `withdrawn_flag`
- `withdrawn_reason`
- `withdrawn_year`
- `withdrawn_country`
- `withdrawn_class`
- `black_box_warning`
- `molecule_synonyms`: used for `synonyms` and `trade_names`
- `cross_references`: uses `xref_src`, `xref_id`
- `chebi_par_id`: used for `cross_references`
- `molecule_structure`
- `canonical_smiles` 

### Target

> `targets` in `data_pipeline`

- `target_chembl_id`
- `target_component`
  - `accession`
- `target_type`
- `pref_name`

## Gene ES index

See lines 440. Lookup is by `ensembl` id.

- `approved_name`
- `approved_symbol`

# Acceptance criteria

- There is a new step in PIS called `drug` which gathers all necessary raw data for later ETL processing.
- Executing the drug step queries the ChEMBL Elasticsearch for the indexes/fields specified in the `config.yaml`
- After Platform-Input-Support successfully completes the ChEMBL step, files exist on Google Cloud Storage containing the ChEMBL raw data for further processing.

**Outstanding problems:** 
- ChEMBL's ElasticSearch is within the EBI VPN: Google Cloud cannot reach it at present.

**Comment by CodeCruncher63** [comment]
@JarrodBaker I am reviewing and testing your PR.
