### ISSUE TITLE
Ontology review: reduce time for ontology tests

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#117]
@elipapa commented on [Wed May 16 2018](https://github.com/opentargets/data_pipeline/issues/280)

Currently it takes over > 10min to run `test_ontology`. 

![image](https://user-images.githubusercontent.com/112610/40112462-edac9328-58fd-11e8-83d8-eb83702575ec.png)

Could we please reduce it ?

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_pipeline/issues/280#issuecomment-403762154)

would this be something @afaulconbridge  can look at as well?

**Comment by afaulconbridge** [comment]
As part of #122 the ontology tests can also be separated, which will mitigate this issue
