### ISSUE TITLE
Write blog post on updated drug dataset

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1172]
Write an entry for the [blog](http://blog.opentargets.org/) highlighting changes to the pipeline and benefits of enhanced drug inclusions.

**Comment by JarrodBaker** [comment]
http://blog.opentargets.org/ghost/#/editor/5ffc4891edefb54e37ca2f4a

**Comment by HelenaCornu** [comment]
Published: http://blog.opentargets.org/2021/03/02/drug-index-rewrite/
