### ISSUE TITLE
Add allelic requirement, mutation consequence and disease confidence to JSON schema

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1179]
Although these values are now included in in the G2P and ClinGen evidence files, they are not formally defined in the JSON schema yet. This does not break anything but it is better to include them in the schema. A [review of the values in the different data sources](https://docs.google.com/spreadsheets/d/1mRqnXBayXHv27hfcYboigMYUN10ITiXpHlxjfhSSuHo/edit#gid=0) is ongoing to see if a common nomenclature can be used accross all of them.

**Comment by andrewhercules** [comment]
Re-assigned to 20.11 release

**Comment by AsierGonzalez** [comment]
Given the ongoing work to write a new JSON schema (see [#1249](https://github.com/opentargets/platform/issues/1249)) these fields will be captured there and they will not be added to the current JSON schema. Therefore, I unassign myself and I pass this onto @DSuveges. Please note that as agreed this week, from 21.02 `mutation_consequence` will be renamed as `functional_consequence` and it will be an SO code to be aligned with what is used by genetic associations.

**Comment by AsierGonzalez** [comment]
Have the fields been added to the new schema?

**Comment by ireneisdoomed** [comment]
Yes. You can easily see all the current fields in the schema with their descriptions [in this spreadsheet](https://drive.google.com/file/d/1vHoyIsQDBNmUfq2IUdZDoz3G457V5cqW/view?usp=sharing).

Also on the JSON Schema [repo](https://github.com/opentargets/json_schema/blob/ds_1249_new_json_schema/opentargets.json).

**Comment by AsierGonzalez** [comment]
Thanks @ireneisdoomed!
