### ISSUE TITLE
Make Google Analytics tracking disabled by default in the platform-app

### ISSUE THREAD

**Issue by forus** [opentargets/platform#1182]
The `platform-app` keeps sending Google Analytics reports to the EBI account independently where it's installed.

Please make the GA tracking turned off by default.

**Comment by forus** [comment]
Making the tracking host-aware as it's done for the angular version would work for us as well.

**Comment by andrewhercules** [comment]
Ticket closed as Google Analytics approach to be completely changed with use of Google Tag Manager - see https://github.com/opentargets/platform/issues/1379 for more information
