### ISSUE TITLE
Align evidence schemas of genetic associations and somatic mutation

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1185]
Currently the JSON schema of the two data types are very different, which limits the information that some of the data providers can provide for the somatic mutations compared to rare diseases, e.g. EVA. We need to work out what the best approach is to capture all the information that the different somatic mutation data sources have.

**Comment by AsierGonzalez** [comment]
After a thorough review of the problem (see [summary in this slide deck](https://docs.google.com/presentation/d/1Rx9yGGWazu8d6GoyosQ7iOanlrLiUdhkY54mxV5GcFs/edit?usp=sharing)) it has been observed that any restructuring of the schema would require changes to the data pipeline and the front-end. Given that there is a parallel effort to flatten the evidence strings, the whole JSON schema may be reorganised in the near future so it has been decided that the somatic evidence schema will not be modified for now.

**Comment by AsierGonzalez** [comment]
This will be addressed in the new JSON schema that @DSuveges is writing (see [#1249](https://github.com/opentargets/platform/issues/1249) where each data source will be defined separately.

Assigning the issue to you @DSuveges.

**Comment by d0choa** [comment]
The new schema can accommodate all fields so in a way different data types could make use of the same schema.
Closing as this is a problem of the old pipeline.
In the new pipeline there is still some work to do to harmonise some datasources/datatypes but goes beyond this ticket
