### ISSUE TITLE
Update documentation to include ClinGen references

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1186]
With the inclusion of ClinGen in the 20.09 release, we need to update the documentation to reflect the new data source:

- [ ] Update association score visual on [scoring page](https://docs.targetvalidation.org/getting-started/scoring)
- [ ] Add entry for ClinGen and description on [Genetic associations page](https://docs.targetvalidation.org/data-sources/genetic-associations)

**Comment by andrewhercules** [comment]
@DSuveges, @AsierGonzalez, @d0choa:

I have drafted a potential ClinGen description for the [Genetic association page in our documentation](https://docs.targetvalidation.org/data-sources/genetic-associations). Can you please review what I have written below and comment with any edits or alternative links?

The [ClinGen Gene-Disease Clinical Validity Curation](https://clinicalgenome.org/curation-activities/gene-disease-validity/) is a manual curation process that evaluates the strength of data and evidence used to support or refute a claim that variation of a particular gene causes a particular disease. Gene-disease relationships are evaluated using a set of criteria to establish clinical validity and curators make a qualitative classification using a set of agreed terms: "Definitive," "Strong," "Moderate," "Limited," "No Reported Evidence," or "Conflicting Evidence." For more information on ClinGen's curation approach, see [Strande et al., 2017](https://pubmed.ncbi.nlm.nih.gov/28552198/).

**Comment by AsierGonzalez** [comment]
It sounds very similar to some of the lines in their website but I find those clearer:

> The ClinGen Gene-Disease Clinical Validity curation process involves evaluating the strength of evidence supporting or refuting a claim that variation in a particular gene causes a particular disease.

If you want to keep your text I would say variation _in_ rathern than _of_ a particular gene, I have seen it like that more often.

Also, not sure if you want to list the terms used for the confidence levels or just say that "the evidence supporting a gene-disease association is described in a semi-quantitative manner" as they do in their website.

Finally, I would mention that we integrate the gene-disease pairs that have been evaluated by ClinGen available at https://search.clinicalgenome.org/kb/gene-validity.

**Comment by AsierGonzalez** [comment]
I would also check what @emcdonagh-OT thinks, as she suggested we use this data and she is more familiar with it.

**Comment by emcdonagh-OT** [comment]
Hello...my suggestion is below:

**ClinGen**

The [ClinGen Gene-Disease Clinical Validity curation process](https://clinicalgenome.org/curation-activities/gene-disease-validity/) involves evaluating the strength of evidence supporting or refuting a claim that variation in a particular gene causes a particular disease. Gene-disease relationships are evaluated using a framework to provide a semiquantitative measurement for the strength of evidence. This results in a qualitative classification for each curated gene-disease relationship: "Definitive," "Strong," "Moderate," "Limited," "No Reported Evidence," or "Conflicting Evidence." For more details on ClinGen's curation approach, see [Strande et al., 2017](https://pubmed.ncbi.nlm.nih.gov/28552198/). 

We integrate the gene-disease pairs that have been evaluated by ClinGen (available at https://search.clinicalgenome.org/kb/gene-validity) into our target-disease associations and evidence scoring. _(Add details on how each assessment "Definitive," "Strong," "Moderate," "Limited," "No Reported Evidence," or "Conflicting Evidence." is scored)._

**Comment by AsierGonzalez** [comment]
I really like Ellie's suggestion. The only thing I don't see very clear is including the details of the scoring, I think that the [association score page](https://docs.targetvalidation.org/getting-started/scoring) is the correct place for this information.

**Comment by d0choa** [comment]
For consistency, the information from each paragraph could go in different pages

**Comment by andrewhercules** [comment]
Confirmed and reviewed documentation available on the [team Google Drive](https://docs.google.com/document/d/1ed2-7-9p9fqitkQYAugzUSQVT5qj9NMhqBxahUx3NBI/edit#)

**Comment by andrewhercules** [comment]
Ticket closed - released as part of 20.09
