### ISSUE TITLE
Duplicate evidence in G2P

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1191]
There are 48 duplicate evidence strings in the 20.09 gene2phenotype evidence file. Currently the parameters used in the unique association fields are  `target_id`, `original_disease_label`, `disease_id` and `gene_panel`. It seems that sometime there might be multiple rows with the same values in the unique fields but differences in the allelic requirement (e.g. [CRYBB3-"CATARACT 22, MULTIPLE TYPES"](https://www.ebi.ac.uk/gene2phenotype/search?panel=ALL&search_term=CATARACT+22%2C+MULTIPLE+TYPES)), mutation consequence (e.g. [CNGB3-"Achromatopsia 3"](https://www.ebi.ac.uk/gene2phenotype/search?panel=ALL&search_term=Achromatopsia+3)) or both ([COL11A1-"MARSHALL SYNDROME"](https://www.ebi.ac.uk/gene2phenotype/search?panel=ALL&search_term=MARSHALL+SYNDROME)). Adding mutation consequence and allelic requirement to the unique association fields should fix the issue and it makes sense for them to be needed to identify a G2P record uniquely.

**Comment by d0choa** [comment]
it makes sense. go ahead with the changes

**Comment by AsierGonzalez** [comment]
I added `allelic_requirement` and `mutation_consequence` to the unique association fields and now there is a single duplicated evidence. However, that is a genuine duplicate in the downloaded G2P eye file:
```
"gene symbol","gene mim","disease name","disease mim","DDD category","allelic requirement","mutation consequence",phenotypes,"organ specificity list",pmids,panel,"prev symbols","hgnc id","gene disease pair entry date"
HGSNAT,610453,"Mucopolysaccharidosis type IIIC",252930,confirmed,biallelic,"loss of function",,,,Eye,TMEM76,26527,"2017-08-27 23:56:38"
HGSNAT,610453,"Mucopolysaccharidosis type IIIC",252930,confirmed,biallelic,"loss of function",,,,Eye,TMEM76,26527,"2017-08-27 23:56:38"
```

**Comment by d0choa** [comment]
I might have ignored this in my recommendations for the new ETL. This might be a source of duplicates for @mkarmona at the moment

**Comment by mkarmona** [comment]
@AsierGonzalez where did you get `mutation_consequence` from?

**Comment by d0choa** [comment]
It was in `evidence.mutation_consequence`, but it has not yet been included in the new evidence because it's not yet mapped to Sequence Ontology. The idea would be to include it in `functionalConsequenceId` in the new schema.

**Comment by mkarmona** [comment]
@AsierGonzalez @d0choa I am bringing back to life `mutation_consequence` from original schema into `mutationConsequence` as it is to keep duplications right

**Comment by mkarmona** [comment]
this should remain opened until we get the field into the right shape otherwise we'll forget

**Comment by d0choa** [comment]
It would be easier to keep the field out for the moment and have some duplicates, rather than including fields in the schema that we will have to remove in the future.

I believe it would be easier to freeze the schema at some point and get the data right. If we keep adding fields that we will have to remove later we are never going to finish

**Comment by AsierGonzalez** [comment]
`variantFunctionalConsequenceId` was added to the Gene2Phenotype schema in opentargets/json_schema#109 and to the new parser in opentargets/evidence_datasource_parsers#64. Because this field is new to Gene2Phenotype, it's missing from `unique-fields` in the [reference.conf](https://github.com/opentargets/platform-etl-backend/blob/master/src/main/resources/reference.conf#L365-L370), which shoul be reviewed.
