### ISSUE TITLE
Link G2P evidence to G2P gene-disease page

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1192]
Currently G2P evidence strings link to the G2P search page using the gene symbol, which is not very relevant. The issue is that the G2P gene-disease pages use some sort of internal number in the url ([example](https://www.ebi.ac.uk/gene2phenotype/gfd?search_type=gfd&dbID=2697)), so some mapping would be needed.

**Comment by AsierGonzalez** [comment]
Email sent to Sarah Hunt asking about it (she is away until 19th October)

**Comment by AsierGonzalez** [comment]
This is not supported at the moment but it will be in the updated gene2phenotype system that is expected to be ready later this year according to Sarah.

**Comment by d0choa** [comment]
In the rewrite, we are linking to the gene-panel, which is the best we can do for the moment.
Once gene2phenotype updates their system we can trigger an action on our side.
Closing this ticket until then
