### ISSUE TITLE
Re-run LINK after 20.09 release

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1193]
Further details TBC

**Comment by andrewhercules** [comment]
@cmalangone I am provisionally scheduling a LINK run for 30 September or 1 October, pending @arwaraies updating the dictionaries, but will confirm later this week as some other tickets (e.g. #996) could be impacted by this work

**Comment by cmalangone** [comment]
The link was deployed today after QA and QC reviews.

**The only main issue was the gene dictionary empty. It required a second run.
