### ISSUE TITLE
Fix openfda output header 

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#1195]
Fix the openfda output header to:

CSV/JSON
chembl_id,event,count,llr,critval

Add in the README file the way that the output are used in the OT project.

CSV: adverse_event in the current pipeline
JSON:  openfda index in the ETL pipeline

Thanks

**Comment by mkarmona** [comment]
@cmalangone @JarrodBaker whether it better fits you, people. Although, the changes should, at least, reduce the number of name transformations they have from start to end. If we need to change names let's do it all at once. I would suggest following camel case when in doubt or situations like this. We would start applying this way strictly (myself included! mea culpa as I started this mess time ago when I coded OpenFDA pipeline).
