### ISSUE TITLE
Add score for short_tandem_repeat_expansion (SO_0002162)

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1197]
In the first 20.09 pipeline run there are 5 EVA evidence strings with an score of 0 because their functional consequence is `short_tandem_repeat_expansion` ([SO_0002162](http://purl.obolibrary.org/obo/SO_0002162)) which is not currently supported by the pipeline. An score has to be decided for it and added to the [file where the pipeline reads the values from](https://github.com/opentargets/data_pipeline/blob/master/mrtarget/resources/eco_scores.tsv).

**Comment by d0choa** [comment]
Please don't forget to include it into the [variant scores table](https://www.targetvalidation.org/variants), together with a definition.

I found a bit of background online on the term creation in which CK participated: 
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/399

**Comment by AsierGonzalez** [comment]
Apparently, they just created `trinucleotide_repeat_expansion` as a child of `short_tandem_repeat_expansion`, which already existed in SO. However, I don't know if that is helpful to decide the score. Trinucleotide repeat expansions are scored with `1`, should it also be 1 for any other repeat expansions including this term?

**Comment by AsierGonzalez** [comment]
After discussing it with @emcdonagh-OT short tandem repeat expansions will be scored with `1` as trinucleotide repeat expansions.

**Comment by AsierGonzalez** [comment]
Reopening this as the second run still contains the scores of `0` because the new scores files was not loaded. It should be fixed in the next run, but that may be for 20.11.

**Comment by andrewhercules** [comment]
Tagging ticket for 20.11 release - will update and manually load the ECO file for 20.11 as per Slack

![Screenshot 2020-09-23 at 20 38 25](https://user-images.githubusercontent.com/7490258/94061053-c4867500-fddc-11ea-95ad-ce488ea7831b.png)

File location: https://storage.googleapis.com/open-targets-data-releases/20.09/input/annotation-files/eco_scores-2020-09-02.tsv

**Comment by AsierGonzalez** [comment]
Clarification: The f[ile has been updated](https://github.com/opentargets/data_pipeline/pull/567) and `platform-input-support` will pick it automatically the next time the it's run. There is nothing else left to be done, I leave the ticket open to remember it in the next release.

**Comment by AsierGonzalez** [comment]
This is fixed in 20.11. There are 13 eviendence string with this functional consequence and four of them have an association score of 0, but that is because their clinical significance is `not provided` or `bening`
