### ISSUE TITLE
The React app lacks the ‘internal data icon’ setting for custom profile sections

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#1199]
In the current, Angular-based webapp, sections can be configured to show a custom icon (often an institute logo) on the right-hand side of their title bars. This functionality was introduced in pull request https://github.com/opentargets/webapp/pull/304. I believe it has yet to be ported to the React app, unless I've overlooked the setting.

**Comment by fedde-s** [comment]
For clarity, this is not an avatar to identify the individual section, but a badge or tag that marks some sections as internal, similar to the ‘new’ badge mentioned in this resolved issue: <https://github.com/opentargets/platform/issues/511>

**Comment by d0choa** [comment]
In order to handle expectations, we are not planning to implement this feature anytime soon, but we are happy to consider PRs if implemented on your side.
