### ISSUE TITLE
API documentation - wrong links - which one to use?

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#120]
There are different documention reference for the API.

None of the links for the API worked on:
http://api.opentargets.io/v3/platform/docs
which is the link by default on the website and rather confusing for end-users who want to try the API.

It points to targetvalidation.com or targetvalidation.org but I understand that we are now pointing to api.opentargets.io so none of the examples works on this page.

However, this Swagger documentation looks more reliable:
https://api.opentargets.io/v3/platform/docs/swagger-ui

Should we use this one in the next version and remove the other one?

**Comment by LucaFumis** [comment]
As per issue #119 this is fixed in commit https://github.com/opentargets/webapp/commit/261d465a924eac68b20b8aa41c77121f1472b865
