### ISSUE TITLE
Invalid evidence strings: Multiple genes with uniprot P19440

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1200]
In the second 20.09 pipeline run there are 121 invalid evidence strings with the explanation `Multiple genes with uniprot P19440` that were valid in the first run. After doing some research it seems that `ENSG00000100031` (see [API response](https://platform-api-qc.opentargets.io/v3/platform/private/target/ENSG00000100031) and [target profile page](https://qa.targetvalidation.org/target/ENSG00000100031)) and `ENSG00000286070` (see [API response](https://platform-api-qc.opentargets.io/v3/platform/private/target/ENSG00000286070) and [target profile page](https://qa.targetvalidation.org/target/ENSG00000286070)) both point to UniProt accession [P19440](https://www.uniprot.org/uniprot/P19440). Apparently this was not the case when we did the first pipeline run so we need to investigate what changed.

**Comment by andrewhercules** [comment]
Reassigned to 20.11 release

**Comment by AsierGonzalez** [comment]
This does not seem to be the case in 20.11. [`ENSG00000100031` still points to `P19440`](https://qa.targetvalidation.org/target/ENSG00000100031) whereas `ENSG00000286070` has an incomplete link to UniProt (http://www.uniprot.org/uniprot/) because [it doesn't have any associated UniProt ids](https://qa.targetvalidation.org/target/ENSG00000286070).
