### ISSUE TITLE
Tractability and ChEMBL evidence out of sync

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1201]
It seems that the tractability pipeline does not use the same ChEMBL version as the ChEMBL evidence given that according to tractability there are small molecules in phase 4 trials for [ACE2](https://www.targetvalidation.org/target/ENSG00000130234) but there are no known drugs.

<img width="1363" alt="Screenshot 2020-09-11 at 17 08 03" src="https://user-images.githubusercontent.com/11410715/92948819-e6354300-f451-11ea-8b9c-3b49b9fb78cf.png">

Based on previous discussions (see #890) and the tractability file, the drug targeting ACE2 is `CILAZAPRIL` (CHEMBL515606) but since the last ChEMBL update in May 2020, the only target for that drug is ACE (see [drug page](https://www.targetvalidation.org/summary?drug=CHEMBL515606) and [ChEMBL](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL515606/)).

This seems to be an issue with the tractability pipeline but I open the ticket to track the issue.

**Comment by andrewhercules** [comment]
The [tractability file for 20.11](https://storage.googleapis.com/otar001-core/Tractability/20.11/tractability_buckets-23-10-2020.tsv) has been reviewed and ACE2 does not contain a clinical phase 4 assessment
