### ISSUE TITLE
Text mining evidence missing from sentences with multiple targets

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1203]
Raised by @saha-shyamasree:

If a sentence contains two targets and a disease there should be two evidence strings in the JSON file but there are none, i.e. the sentence is ignored entirely. This seems to be caused by the txt to JSON conversion step.

**Comment by d0choa** [comment]
are they evidence with multiple diseases (title) or evidence with multiple targets (body) or both?

**Comment by AsierGonzalez** [comment]
Good point, I corrected the title to reflect what was reported by Shyama.  @saha-shyamasree can you please clarify if it also affects sentences with multiple diseases and give some examples for our reference?

**Comment by AsierGonzalez** [comment]
According to @saha-shyamasree, the EPMC pipeline does not seem to include exceptions for sentences with multiple diseases so this should only affect sentences with multiple targets. This needs to be confirmed.

**Comment by AsierGonzalez** [comment]
According to @saha-shyamasree, this is at least partially related to gene/protein names that map to multiple UniProt ids:

```
<SENT sid="2237" pm="."><plain>The aim of this study was to evaluate the expression of <z:uniprot fb="4" ids="Q07065,Q9H3D4,Q9P2Y5">p63</z:uniprot> in the esophagus and related metaplastic and neoplastic disorders to gain insight into the pathogenesis of these processes. </plain></SENT>
```
The EPMC pipeline skips those sentences.

@d0choa suggests that if most of the problematic protein names are those that include the molecula weight it would be preferable to continue ignoring them as it is done now. Shyama will provide a file with examples so that we can have a look into them and make an informed decision.
