### ISSUE TITLE
Use latest available ClinVar data for EVA evidence

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1204]
Currently, the ClinVar version used by EVA to generate the evidence file is the same as the one used by the Ensembl release available at the time ([specified in Ensembl data sources documentation](http://www.ensembl.org/info/genome/variation/species/sources_documentation.html)). As reported by @tskir, this may lag 6-8 months behind the latest ClinVar release. For example, for 20.09 he used the ClinVar version used in Ensembl 100, because that was the one that was available when he generated the evidence file, which is ClinVar 2019-09, so it’s one year old, when the latest one is 2020-09.

After internal discussion, we have decided that from now own we want to use the latest available ClinVar, since there don't seem to be any reasons to keep the ClinVar-Ensembl synchronisation. The only concern is that it may produce some broken links in the FE, which we will QC when we get the new data.

**Comment by tskir** [comment]
Hi Asier, wanted to clarify this part here:

> After internal discussion, we have decided that from now own we want to use the latest available ClinVar

Does this apply immediately? Can I use the latest ClinVar version for the 2020.11 release already?

**Comment by AsierGonzalez** [comment]
Yes, you can. If you have time to make the changes to your code to process the new ClinVar files you can start using them.

**Comment by tskir** [comment]
After discussions, we decided that this will not be in scope yet for 2020.11 submission. This one will use pipeline v1.3 and ClinVar 2020/07 (the latest where the repeat expansion pipeline from v1.3 will still work)

**Comment by ireneisdoomed** [comment]
Status update from an email from @tskir:

> This is mostly implemented and will take full effect staring from v2.0 of our pipeline. The only restriction now is that the pipeline v1.3 cannot work with ClinVar data releases newer than 2020/08, because after that ClinVar data model changed, most notably regarding the repeat expansion variants representation.

We can expect this to change from 21.02 on. As for the next release, we are using the same ClinVar version (2020/08) with a more comprehensive manual curation dataset for text-to-ontology mappings.

**Comment by ireneisdoomed** [comment]
The migration to the v2.0 version of the EVA pipeline involves using the latest version of ClinVar.
This is taking full effect on our side as of 21.04 where the **2021–03 ClinVar release** is used.

Closing issue.
