### ISSUE TITLE
Mapping to MedDRA identifiers 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1205]
Copying ticket from opentargets/platform-etl-openfda-faers#17 

![Screenshot 2020-09-21 at 11 34 50](https://user-images.githubusercontent.com/7490258/93791299-f6a4a500-fc2b-11ea-9680-b6e36f693ce1.png)

**Comment by elipapa** [comment]
thanks for considering it everyone. 
[bioportal](https://bioportal.bioontology.org/ontologies/MEDDRA) license information allows non-commercial uses:
> The MedDRA ontology is maintained and distributed by the MedDRA MSSO. This ontology is freely accessible on this site for academic and other non-commercial uses. Users anticipating any commercial use of MedDRA must contact the MSSO to obtain a license.

I imagine most pharma users would have a license in-house to leverage the ontology in annotating clinical trials.

**Comment by JarrodBaker** [comment]
Thanks @elipapa . We have been in touch with the MedDRA MSSO and it looks like we're going to be able to add the MedDRA identifiers. Because the project isn't strictly non-commercial we need to be cautious about how we expose the MedDRA data so  that we continue to fall under the non-commercial licence.

**Comment by mkarmona** [comment]
@JarrodBaker , we still need to iterate this initial MedDRA mapping as we have covered a minority of the reported adverse event names.

**Comment by elipapa** [comment]
one more comment. is the data available for download?

**Comment by JarrodBaker** [comment]
@mkarmona with the latest PR the meddra codes cover all but five distinct events: 

```
  [hallucination, auditory],
  [delusional disorder, unspecified type],
  [hallucination, visual],
  [aeromona infection],
  [streptococcal identification test positive]
```
These affect 21 records across 16 ChEMBL ids.

Meddra codes are also included in both the `agg_by_chembl` and `agg_critval_drug` outputs.

**Comment by JarrodBaker** [comment]
@elipapa I have generated the output and it can be downloaded from the Google Cloud Bucket; `gs://open-targets-data-releases/20.09/openfda-faers-meddra`

**Comment by elipapa** [comment]
Fantastic!! thanks a lot for the quick turn around 😊 this has increased
the value of the data 💯 for us
