### ISSUE TITLE
Categorize safety records

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#1206]
The safety information curated and presented in OT is incredibly valuable.
Would it be possible to categorize the information by (anatomical) system using UBERON?
This way, we could:
- relate it to the mouse phenotypes information and check if there are any correlation. 
- classify the records when working on a list of targets.

**Comment by d0choa** [comment]
While this is within scope, we need to plan together with the OTAR safety project. Iceboxing it temporarily

**Comment by ireneisdoomed** [comment]
Safety data has been remodelled in such a way that now they can be analysed by anatomical system by using the `biosample` field. Here is the new schema:
```
 |-- safetyLiabilities: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- event: string (nullable = true)
 |    |    |-- eventId: string (nullable = true)
 |    |    |-- effects: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- direction: string (nullable = true)
 |    |    |    |    |-- dosing: string (nullable = true)
 |    |    |-- biosample: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- tissueLabel: string (nullable = true)
 |    |    |    |    |-- tissueId: string (nullable = true)
 |    |    |    |    |-- cellLabel: string (nullable = true)
 |    |    |    |    |-- cellFormat: string (nullable = true)
 |    |    |    |    |-- cellId: string (nullable = true)
 |    |    |-- datasource: string (nullable = true)
 |    |    |-- literature: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |    |    |-- study: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- name: string (nullable = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
```

This dataset is built into the **target** annotation, which is available in our [Data Downloads page](https://platform.opentargets.org/downloads). 
We are currently working on improving this annotation by bringing more sources of data and by expanding the coverage between the reported systems and their UBERON IDs.
