### ISSUE TITLE
Update interactions data to the new release

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1207]
From Intact team

> We have released data today, which is available at following path ftp://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current This has interactor_pair_interactions.json (ftp://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/data/interactor_pair_interactions.json) duplication issues resolved both which were reported and found by us.

- [x] Update ETL pipeline to match with new changes in the fields and evidences
- [x] Update API to accommodate the new changes produced by the ETL pipeline

**Comment by d0choa** [comment]
Notes on fixes for unmatched IDs Oct 9th 10am (ordered by priority):

- [ ] It was mentioned that some of the unmapped were uniprot isoforms (e.g. A6NFR6-4) were the -X numbering  can be ignored.  A6NFR6-4 is now fixed but others such as Q9Y2D5-5 don't match yet. Something to investigate.
- [ ] Some are in other species (non-human). These we want to keep but not mapped to any entitiy. You can use the organism field to mark interactors that are not required to be mapped (Check specification) https://www.uniprot.org/uniprot/A0A0F7RLZ4
- [ ] The RNAs from RNAcentral that do not map (e.g. MALAT1 URS0000A77400_9606(https://rnacentral.org/rna/URS0000A77400/9606) -> (https://alpha.targetvalidation.org/target/ENSG00000251562). They might require a 2-step mapping. From RNAcentral -> HGNC -> Ensembl.
- [ ] Some are HGNC ids (HGNC:10354) I think we have this on our gene index, so I suspect it wouldn’t be hard to get them. They are not very frequent.
- [ ] Most of the unmapped accession, correspond to Uniprot unreviewed (not very reliable) proteins. https://www.uniprot.org/uniprot/A0A024QZT2. 

Other notes:
- Some are reactome identifiers (R-HSA-9624909) you can probably ignore them for now
- Some are intact identifiers (EBI-10828686) you can probably ignore them as well

@DSuveges it would be good to gather your thoughts on this. In particular on how to map uniprot unreviewed proteins

**Comment by DSuveges** [comment]
Mapping unreviewed proteins is tricky. Let's take a look at [A0A024R4Q5](https://www.uniprot.org/uniprot/A0A024R4Q5). It's unreviewed, but has a 100% similarity with TFPT, which can be mapped to ENSG00000105619. 

I'm not 100% sure how similar/identical proteins can be found, but it's certainly doable. However we need to make a call how to go about proteins, where there's no perfect match or there are multiple perfect matches.

**Comment by DSuveges** [comment]
I agree having over 3k unmapped entities is just unacceptable. We need to do something about it.

**Comment by d0choa** [comment]
For the 2 cases listed above (A0A024R4Q5 & A0A024QZT2), a 2-step mapping using the Uniprot `GeneID` field would work.

```
❯ grep 29844 HUMAN_9606_idmapping.dat | grep GeneID
P0C1Z6	GeneID	29844
A0A024R4Q5	GeneID	29844

❯ grep 55770 HUMAN_9606_idmapping.dat | grep GeneID
Q96KP1	GeneID	55770
A0A024QZT2	GeneID	55770
```

**Comment by DSuveges** [comment]
So, let's assume we have an unmapped label, we look up the gene ID, but there might be multiple entries:

```
gzcat  HUMAN_9606_gene_ids.tsv.gz | awk '$3 == 3111'
P06340	GeneID	3111
X5CF87	GeneID	3111
A0A1V0E3S6	GeneID	3111
A0A1V0E3Q8	GeneID	3111
A0A1V0E3R8	GeneID	3111
A0A1V0E3Q1	GeneID	3111
A0A1V0E3Q3	GeneID	3111
A0A1V0E3P3	GeneID	3111
A0A1V0E3N6	GeneID	3111
A0A1V0E3R4	GeneID	3111
A0A1V0E3N7	GeneID	3111
A0A1V0E3Q4	GeneID	3111
A0A1V0E3S4	GeneID	3111
A0A1V0E3P8	GeneID	3111
A0A1V0E3R3	GeneID	3111
A0A1V0E3R0	GeneID	3111
A0A1V0E3P0	GeneID	3111
A0A1V0E3N3	GeneID	3111
A0A1V0E3Q7	GeneID	3111
A0A1V0E3N1	GeneID	3111
A0A1V0E3P9	GeneID	3111
A0A1V0E3R6	GeneID	3111
A0A1V0E3Q5	GeneID	3111
A0A1V0E3P1	GeneID	3111
A0A1V0E3M7	GeneID	3111
A0A1V0E3P6	GeneID	3111
A0A1V0E3Q2	GeneID	3111
A0A1V0E3T1	GeneID	3111
A0A1V0E3S7	GeneID	3111
A0A1V0E3S0	GeneID	3111
A0A1V0E3Q6	GeneID	3111
```
So we practically need a table with the uniprot gene ids and the uniprot id or ensembl gene id, then do the lookup. So all above listed `A0...` labels got resolved to the same label.

**Comment by cmalangone** [comment]
Q9Y2D5: Ok not to map. The reason being, the gene is defined in Ensembl as PALM2AKAP2 a fusion protein, whereas the uniprot proteins are defined as each of the constituents PALM2 and AKAP2.

**Comment by cmalangone** [comment]
About 
"some are HGNC ids (HGNC:10354) I think we have this on our gene index, so I suspect it wouldn’t be hard to get them. They are not very frequent."

Fixed using the info stored in the target index (hgncId)

**Comment by cmalangone** [comment]
@d0choa  
Released 0.46.4 for the dev appEngine server.

**Comment by cmalangone** [comment]
The new ETL 20.11 will contains the dataset of String without any threshold

**Comment by cmalangone** [comment]
The new structure for interactions:
*) Download the input file from PIS
*) ETL will transform the data 
*) output for the ES

**Comment by cmalangone** [comment]
21.04 release contains the proper data
