### ISSUE TITLE
Improve the caracteristics of the ES machine

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1208]
The current ES 7.9 machine needs improvements

- [x] Slim to 250GB (permanent SSD)
- [x] Down to 4CPUs HM
- [ ] update startup script to accommodate new mem changes and ES and kibana versions
- [ ] Update OS to latest stable cos-stable (it takes the latest if specify just cos-stable)
--

**Comment by cmalangone** [comment]
Done
