### ISSUE TITLE
 Streamline running internal datasource parsers

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1209]
Currently the internal evidence data source parsers are a set of independent python scripts in the [evidence_datasource_parsers](https://github.com/opentargets/evidence_datasource_parsers) repo that need to be run manually and whose input files need to be downloaded and placed in specific directories. This makes it rather time consuming to update the data sources when multiple parsers have to be run. This tickets will cover a number of improvements:

- [ ] Improve configuration of parsers: At the moment most of the parsers read input and output files from another Python module.
- [ ] Build a workflow to run the desired parsers. A makefile will be created to control what parsers are run

**Comment by d0choa** [comment]
Adding a comment in #1275 and closing this, as this is part of a bigger task

**Comment by AsierGonzalez** [comment]
Is this not a subtask of that epic?
