### ISSUE TITLE
Integrate new phenotypes data from EFO

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1214]

**Comment by cmalangone** [comment]
Platform-input-support:

- Download the data from https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
- Download the file phenotype.hpoa : 
 http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa
- HP.owl converted in JSON. Load all valid id and the relative info
- Phenotopy.hpoa is a tab file. Load all the info and convert into JSON lines
- Save JSON lines output

ETL:
Create a new step "hpo". 
Prerequisite run the disease step and generate hpo index and disease_hpo index.

GraphQL: (todo)
Render the info through specific endpoints.

**Comment by cmalangone** [comment]
Phenotypes are integrated with Disease (efo-ontology)
The resources involved are
  hpo_phenotypes info:
    uri: http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa
  hp ontology:
      uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
  mondo ontology:
      uri: https://github.com/monarch-initiative/mondo/releases/download/v2020-12-18/mondo.owl

PIS, ETL and GraphQL were updated accordingly with the new format/data
