### ISSUE TITLE
Missing synonyms of CRK in alpha

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1216]
There are three synonyms for CRK in the [production target profile page](https://www.targetvalidation.org/target/ENSG00000167193) but none in the [alpha version of the rewrite](https://alpha.targetvalidation.org/target/ENSG00000167193).

- Production
![Screenshot 2020-10-16 at 14 04 33](https://user-images.githubusercontent.com/11410715/96261602-913c9d80-0fb8-11eb-87d5-87f6560d4c9f.png)

- Alpha
![Screenshot 2020-10-16 at 14 04 25](https://user-images.githubusercontent.com/11410715/96261630-98fc4200-0fb8-11eb-97db-692fc554a50f.png)

**Comment by mkarmona** [comment]
the [API does properly](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20target(ensemblId%3A%20%22ENSG00000167193%22)%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20approvedName%0A%20%20%20%20nameSynonyms%0A%20%20%20%20symbolSynonyms%0A%20%20%7D%0A%7D%0A&operationName=assocs) and returns its name synonyms

**Comment by d0choa** [comment]
Based on @mkarmona response:
```
{
  "data": {
    "target": {
      "approvedSymbol": "CRK",
      "approvedName": "CRK proto-oncogene, adaptor protein",
      "nameSynonyms": [
        "Proto-oncogene c-Crk",
        "p38",
        "Adapter molecule crk"
      ],
      "symbolSynonyms": []
    }
  }
}
```
it's likely the rewrite app is only using `symbolSynonyms`, when it should be concatenating `symbolSynonyms` + `nameSynonyms`

**Comment by LucaFumis** [comment]
Done and merged in beta https://github.com/opentargets/platform-app/pull/278 
It also fixes the synonyms on evidence page.
