### ISSUE TITLE
Add confidence_interval, cases and odds_ration to JSON schema

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1219]
Similar issue to #1179,  `evidence.variant2disease.confidence_interval` is used by `ot_genetics_portal` and `evidence.variant2disease.odds_ratio` by `phewas_catalog` but none is in the JSON schema.

There is also `evidence.variant2disease.cases`, which is used by `phewas_catalog` and not in the schema. In this case, the question is whether one common field can be used to represent this value and the `evidence.variant2disease.gwas_sample_size` used by `ot_genetics_portal`. `sample_size` has been suggested as a possible name for this. Any thoughts @DSuveges, @d0choa?

**Comment by d0choa** [comment]
I'm incline to approach this in a systematic way for all evidence (types and classes). We will meet (next week) and decide what's the approach
