### ISSUE TITLE
Build a functional Panel App parser

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1224]
The structure of the parser to be the evidence is built, but the script is still inconsistent:

- [x] Clearer structure of the evidence field
- [x] Line 274: `self.evidence_builder.OpenTargets`or `self.evidence_builder.OpenTargets4`
- [x] Line 242: What should `evidence_codes` contain?
- [x] Line 226: Is `resource_score` and `confidence` supposed to have the same value? TO-DO: Give scores depending on green, ambar and red.
- [x] Line 231: `Linkout` is pointing to the publications field: that field still needs cleaning
- [x] Line 262: is `unique_associations_field `correct?
- [x] Argparse to implement
- [x] Add logging messages

**Comment by DSuveges** [comment]
> Line 274: self.evidence_builder.OpenTargetsor self.evidence_builder.OpenTargets4

That's a tricky question. If you take a look at the [schema](https://jsoneditoronline.org/#left=cloud.a52833ca7dc44b0abed2e975db450a5a) you can see 5 different definition under the key `oneOf`. When you say `OpenTargets4` that specifies the 5th schema. However it is not mandatory, the builder can find it, but occasionally there might be a clash.

> Line 242: What should evidence_codes contain?

That is a term from the evidence and conclusion ontology describing how the evidence is inferred eg. from curator, from author of a paper or computationally derived. We no longer use that filed, but it is still required. I think we can keep using the existing ECO code: `http://purl.obolibrary.org/obo/ECO_0000205` reflecting that the PanelApp data is manually curated.

> Line 262: is unique_associations_field correct?

I think the unique association field can be simplified. I would drop the `panel_name` and `panel_version` as those fields are already defined by the `panel_id` (There cannot be panels with the same id, with different version... at least there shouldn't)

**Comment by ireneisdoomed** [comment]
Things to correct after the code review with Daniel:
- [ ]  Look up table with green and amber scores.
- [ ]  Logger configuration in a separate function
- [ ]  @staticmethod decorator for those functions where no self variable is used.
- [ ]  Reduce logic in the main function.
- [ ]  .unique() instead of .value_counts().index.to_list()
- [ ] Initialise evidence_strings.append() to append the evidence. Include it in the return or save it somewhere
- [X ] Import the GeneParser.

**Comment by ireneisdoomed** [comment]
More than 47 000 evidence strings were generated.

These include 32 000 where the disease mapping got an exact match and 15 000 where the disease mapping result was cross-referenced with the mapping of the corresponding OMIM code.

Closing issue.
