### ISSUE TITLE
Create new ClinGen evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1227]
On the evidence page in the rewrite, can we please create a new data table that displays the ClinGen evidence data?

**Example GraphQL API query**
[ACAD9 and Exercise intolerance with lactic acidosis](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_254843%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000177646%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22clingen%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20recordId%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20allelicRequirement%0A%20%20%20%20%20%20%20%20confidence%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Reported disease/phenotype | Allelic requirement | Confidence
| --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].diseaseFromSource` | `evidences.rows[x].allelicRequirement` | `evidences.rows[x].confidence` | 
| **Sample data** | Exercise intolerance with lactic acidosis | acyl-CoA dehydrogenase 9 deficiency | Autosomal Recessive | Definitive |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Confidence" column to the relevant page in ClinGen using the following construct - `https://search.clinicalgenome.org/kb/gene-validity/` + `evidences.rows[x].recordId` (e.g. [Definitive](https://search.clinicalgenome.org/kb/gene-validity/5fad1866-75ce-470f-984c-e64bb7e11168--2018-03-27T16:00:00))

**QC checks**

- SLC19A3 (ENSG00000135917) and Leigh syndrome (Orphanet_506)
- HRAS (ENSG00000174775) and Noonan syndrome (Orphanet_648)
- CASQ2 (ENSG00000118729) and hypertrophic cardiomyopathy (EFO_0000538) - should have two rows in the data table with one row having an allelic requirement value of "Autosomal Recessive" and the other having a value of "Autosomal Dominant" and both rows should link to different pages on the ClinGen website

**Comment by andrewhercules** [comment]
Please see below for further amendments to the table specification.

### Summary widget

**Widget text:**
`evidences.count` records

### Detail view

**Detail view title:** 
ClinGen

**Detail view description:** 
Manual gene-validity curations for `target.approvedSymbol` and `disease.name`. Source: [ClinGen](https://search.clinicalgenome.org/kb/gene-validity/)

**Comment by andrewhercules** [comment]
Can we please make a small adjustment to the data table?

**Show more rows**
- [ ] Implement "Rows per page" feature to allow users to set number of rows visible in table

![Screenshot 2020-11-13 at 09 02 04](https://user-images.githubusercontent.com/7490258/99049635-fc18ce80-258e-11eb-86cf-f3fc776021fb.png)

**Comment by mirandaio** [comment]
@andrewhercules adjustments have been merged. Feel free to check again and close if done.

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please make a small adjustment to the ClinGen evidence data table?

- [ ] Update "Allelic requirement" column as previously, the field was a string `evidences.rows[x].allelicRequirement`; however, it is now an array called `evidences.rows[x].allelicRequirements` with an "s". Within the column, if there is only one entry in `evidences.rows[x].allelicRequirements`, please display the string. If there are two or more entries in `evidences.rows[x].allelicRequirements`, please list the entries in an unordered list

**Comment by andrewhercules** [comment]
One of the fields in the GraphQL API has deprecated - `recordId` - and this breaks the external links to the ClinGen website.

In the "Confidence" column, can we please construct the link to ClinGen using the `studyId` value instead?

The link construct will remain the same:

`https://search.clinicalgenome.org/kb/gene-validity/` + `evidences.rows[x].studyId` 

For example: [Definitive](https://search.clinicalgenome.org/kb/gene-validity/5fad1866-75ce-470f-984c-e64bb7e11168--2018-03-27T16:00:00)

**Comment by d0choa** [comment]
As discussed:
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
