### ISSUE TITLE
Create new Gene2Phenotype evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1228]
On the evidence page in the rewrite, can we please create a new data table that displays the Gene2Phenotype evidence data?

**Example GraphQL API query**
[BRAF and Cardiofaciocutaneous syndrome](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_1340%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22gene2phenotype%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20confidence%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20allelicRequirement%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Reported disease/phenotype | Allelic requirement | Confidence | Literature |
| --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].diseaseFromSource` | `evidences.rows[x].allelicRequirement` | `evidences.rows[x].confidence` | `evidences.rows[x].literature`
| **Sample data** | Cardiofaciocutaneous syndrome | Cardiofaciocutaneous syndrome | monoallelic | confirmed | 1 publication

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Transform the string value in the "Reported disease/phenotype" category from ALL CAPS to Sentence case
3. Link the value in the "Confidence" column to the gene search results page on the Gene2Phenoytpe portal using the following construct - `https://www.ebi.ac.uk/gene2phenotype/search?panel=ALL&search_term=` + `evidences.rows[x].target.approvedSymbol` (e.g. [confirmed](http://www.ebi.ac.uk/gene2phenotype/search?panel=ALL&search_term=BRAF))
4. In the "Literature" column, please show the number of publications and link the value to the EuropePMC search results page using the following construct, assuming `evidences.rows[x].literature` returns an array of PubMed IDs - `https://europepmc.org/search?query=` + `EXT_ID:` + `evidences.rows[x].literature[y]` + `EXT_ID:` + `evidences.rows[x].literature[y]` ... and so on (e.g. [7 publications](https://europepmc.org/search?query=EXT_ID%3A16364920%20OR%20EXT_ID%3A25435214%20OR%20EXT_ID%3A15035987%20OR%20EXT_ID%3A20130576%20OR%20EXT_ID%3A20179705%20OR%20EXT_ID%3A25907612%20OR%20EXT_ID%3A20141835))

**QC checks**

- GNAS (ENSG00000087460) and cataract (EFO_0001059)
- SMPD1 (ENSG00000166311) and Niemann-Pick disease type B (Orphanet_77293)
- ERCC2 (ENSG00000104884) and skin disease (EFO_0000701)

**Comment by javfg** [comment]
The graphql example shows `clinGen` as data source. Should that be `gene2phenotype`?

**Comment by andrewhercules** [comment]
Yes @javfg, my apologies! I've updated the query [here](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_1340%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22gene2phenotype%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20confidence%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20allelicRequirement%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by d0choa** [comment]
The work on #1226 will provide a `literature` field as well for this datasource (null at the moment).
Feel free to include it, even if the API returns nulls at the moment.

**Comment by andrewhercules** [comment]
Will do - thanks @d0choa!

@javfg I have updated the table to add the `literature` field, but it will be `null` until the work on #1226 is complete

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please make a small adjustment to the data table?

- [ ] Update "Allelic requirement" column as previously, the field was a string `evidences.rows[x].allelicRequirement`; however, it is now an array called `evidences.rows[x].allelicRequirements` with an "s". Within the column, if there is only one entry in `evidences.rows[x].allelicRequirements`, please display the string. If there are two or more entries in `evidences.rows[x].allelicRequirements`, please list the entries in an unordered list

**Comment by d0choa** [comment]
As discussed:
- [ ] Move reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”

**Comment by d0choa** [comment]
On the latest API there is a minor change in this widget regarding `studyId`. [Example GraphQL query](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=%0Aquery%20test%7B%0A%20%20target(ensemblId%3A%20%22ENSG00000157764%22)%7B%0A%20%20%20%20evidences(efoIds%3A%20%5B%22Orphanet_1340%22%5D%2C%20datasourceIds%3A%20%5B%22gene2phenotype%22%5D)%7B%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20confidence%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20allelicRequirements%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=test).

This minor change implies that we might need to do some small fixes:
- [ ] Add a new column named `Panel` containing the content of `studyId`
- [ ] The link that currently is built in the confidence column will be moved to the `Panel` column and include the panel on it:
`https://www.ebi.ac.uk/gene2phenotype/search?panel=`+ `studyId` + `&search_term=` + `target.approvedSymbol` -> [Example](https://www.ebi.ac.uk/gene2phenotype/search?panel=Skin&search_term=BRAF)

**Comment by d0choa** [comment]
- [ ] can we put the new Panel column between the Allelic requirement and the Confidence columns? It will help with consistency with other tables.

**Comment by LucaFumis** [comment]
This was fixed in PR 271 (merged) https://github.com/opentargets/platform-app/pull/271
