### ISSUE TITLE
Exploring possibilities to map trEMBL identifiers to Esembl gene IDs.

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1229]
This problem is discussed here: #1207 , but the complexity of this problem deserves a more thorough review.

* Currently we have ~20k umapped identifier in the network data most of which are identifiers of unreviewed trEMBL etries with no mapped Ensembl gene.
* To make sure won't lose all these interactions, we can try to map these proteins to targets.

**Comment by d0choa** [comment]
I believe this can be closed, @DSuveges ?
