### ISSUE TITLE
Include publications field in the evidence

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1230]
- [X] Fetch publications from PanelApp API

- [X] Clean publications to include only PubMed IDs

- [x] Include them in the evidence strings

**Comment by ireneisdoomed** [comment]
Closing issue. 

Addressed null values as suggested in #1234. Literature structure looks like this:

`"literature": {
"references": [
{"lit_id": null}]}`

**Comment by AsierGonzalez** [comment]
Is that supported by the JSON schema? The [current definition](https://github.com/opentargets/json_schema/blob/1.7.3/opentargets.json#L1030-L1034) of `lit_id` is as follows:

```
"lit_id": {
          "type": "string",
          "description": "Note for pubmed identifiers, use the URI http://europepmc.org/abstract/MED/[0-9]+",
          "pattern": "NA|http://europepmc.org/abstract/MED/[0-9]+|http://europepmc.org/articles/PMC[0-9]{4,}|[doi|DOI|(https?://)?(dx\u005C.)?doi.org/]*[\u005Cs\u005C.\u005C:]{0,2}(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\u005C\"&\u005C'])\u005CS)+)$"
        }
```

**Comment by ireneisdoomed** [comment]
After discussions in the daily meeting, the `literature` field is only added when the publications array is empty. In that case, we don't have to manage any null values.

`"provenance_type": {
			"literature": {
				"references": [
					{
						"lit_id": "http://europepmc.org/abstract/MED/27604308"
					}
				]
			},
			"database": {
				"dbxref": {
					"id": "Genomics England PanelApp",
					"url": "https://panelapp.genomicsengland.co.uk/",
					"version": "2020-11-04T12:31:39.836564"
				},
				"id": "Genomics England PanelApp",
				"version": "2020-11-04T12:31:39.836552"
			}}`

Literature field currently looks like this. Closing issue.
