### ISSUE TITLE
Create new PheWAS Catalog evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1232]
On the evidence page in the rewrite, can we please create a new data table that displays the PheWAS Catalog evidence data?

**Example GraphQL API query**
[NOD2 in respiratory system disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000684%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000167207%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22phewas_catalog%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20oddsRatio%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20studyCases%0A%20%20%20%20%20%20%20%20variantFunctionalConsequenceId%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Reported disease/phenotype [Phecode] | Variant | Functional consequence | P-value | Cases | Odds ratio |
| --- | --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].diseaseFromSource` | `evidences.rows[x].variantRsId` | `evidences.rows[x].variantFunctionalConsequenceId` | `evidences.rows[x].resourceScore` | `evidences.rows[x].studyCases` | `evidences.rows[x].oddsRatio` | 
| **Sample data** | Respiratory system disease | Chronic pharyngitis and nasopharyngitis | rs9302752 | sequence variant | 0.03152 | 844 | 0.866 |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Variant" column to Ensembl using the following construct - `http://www.ensembl.org/Homo_sapiens/Variation/Explore?v=` + evidences.rows[x].variantRsId (e.g. [rs5743289](http://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs5743289))
3. Round the value in the "P-value" and "Odds ratio" columns to 5 decimal points

As a placeholder, in the "Functional consequence" column, we can show the SO code.

**QC checks**

- NFKBIA (ENSG00000100906) and inflammatory bowel disease (EFO_0003767)
- LPL (ENSG00000175445) and coronary heart disease (EFO_0001645)

**Comment by d0choa** [comment]
It's a known issue that all functional consequences in this datasource have the same value. Don't worry about it. We will fix it at source.

**Comment by d0choa** [comment]
It's an open question if we want to keep the rsId links consistent with Genetics Portal. Currently pointing to dbSNP in the rewrite. Thoughts?

**Comment by AsierGonzalez** [comment]
Personally, I find dbSNP more informative but I don't know if we want to give preference to EBI resources.

**Comment by andrewhercules** [comment]
Can we please make some minor adjustments to the data table?

**Table functionality**
- [ ] Implement "Rows per page" feature to allow users to set number of rows visible in table
- [ ] Allow user to sort by all numeric columns - "P-value", "Cases", and "Odds ratio"
- [ ] By default, sort by p-value (ascending) 

**Table columns**
- [ ] Reorder the last three columns to be "Cases" - "Odds ratio" - "P-value"

**General formatting**
- [ ] Fix the formatting of the values in the "Odds ratio column" as extra zeros are added (e.g. table should show 1.569 instead of 1.56900)
![Screenshot 2020-11-17 at 12 25 53](https://user-images.githubusercontent.com/7490258/99390158-0eb53f80-28d0-11eb-9d58-d8688f3ef402.png)

**External links**
- [ ] Update the links in the "Variant" column to use the identifiers.org service to direct users to dbSNP using the following construct - `https://identifiers.org/ncbi/DBSNP:` + `evidences.rows[x].variantRsId` (e.g. [rs2076756](https://identifiers.org/ncbi/DBSNP:rs2076756)) *note: this is similar to the links constructed for RSIDs in the Open Targets Genetics Portal evidence data table

**Data table number formatting**
- [ ] Ensure tabular, spaced numbers are used
- [ ] Add comma for large integers (e.g. 336,526 vs 336526)
- [ ] Please review the "Features" section on the Inter font website - https://rsms.me/inter/ - to ensure the data table component is using all available number formatting features

**Comment by mirandaio** [comment]
@andrewhercules adjustments have been merged. Feel free to check again and close if done.

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please make one small adjustment to the PheWAS evidence table?

Sample query: [NOD2 and respiratory system disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceTable%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000684%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000167207%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22phewas_catalog%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20oddsRatio%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20studyCases%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20variantId%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=evidenceTable)

- [ ] In the "Variant" column, update the name of the column to "Variant RSID (ID)" and always show the `variantRsId` value and if available, show the `variantId` value in brackets with a link to the variant page in the Open Targets Genetics Portal. This would be similar to [line 57 in the Body.js file for the Open Targets Genetics Portal evidence table](https://github.com/opentargets/platform-app/blob/330187659660041d6557e42a60fe4a842708a10a/src/sections/evidence/OTGenetics/Body.js#L57) except reversed and displayed in the following way:

[rs5743289](https://identifiers.org/dbsnp/rs5743289) ([16_50722863_C_T](https://genetics.opentargets.org/variant/16_50722863_C_T))

Note that sometimes the `variantId` value is `null`

**Comment by d0choa** [comment]
Changes:
- [ ] Move reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
- [ ] Same formatting for variants as in genetics portal regarding font sizes
- [ ] Format *p*-value in header as in genetics portal
