### ISSUE TITLE
Create new UniProt Literature evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1233]
On the evidence page in the rewrite, can we please create a new data table that displays the Gene2Phenotype evidence data?

**Example GraphQL API query**
[APP and nervous system disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000618%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000142192%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22uniprot_literature%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20variantFunctionalConsequenceId%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20proteinAnnotations%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | UniProt - Pathology & Biotech | Literature |
| --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].target.proteinAnnotations.id` | `evidences.rows[x].literature` |
| **Sample data** | Hereditary cerebral hemorrhage with amyloidosis, Arctic type | P05067 | 5 publications |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "UniProt - Pathology & Biotech" to the relevant UniProt page using the following construct - `http://www.uniprot.org/uniprot/` + `evidences.rows[x].target.proteinAnnotations.id` + `#pathology_and_biotech` (e.g. [P05067](http://www.uniprot.org/uniprot/P05067#pathology_and_biotech))
4. In the "Literature" column, please show the number of publications and link the value to the EuropePMC search results page using the following construct, assuming `evidences.rows[x].literature` returns an array of PubMed IDs - `https://europepmc.org/search?query=` + `EXT_ID:` + `evidences.rows[x].literature[y]` + `EXT_ID:` + `evidences.rows[x].literature[y]` ... and so on (e.g. [7 publications](https://europepmc.org/search?query=EXT_ID%3A16364920%20OR%20EXT_ID%3A25435214%20OR%20EXT_ID%3A15035987%20OR%20EXT_ID%3A20130576%20OR%20EXT_ID%3A20179705%20OR%20EXT_ID%3A25907612%20OR%20EXT_ID%3A20141835))

**QC checks**

- JAG1 (ENSG00000101384) and liver disease (EFO_0001421)
- LYST (ENSG00000143669) and Chédiak-Higashi syndrome (Orphanet_167)
- NEFH (ENSG00000100285) in Autosomal dominant Charcot-Marie-Tooth disease type 2 (Orphanet_64746)

**Comment by andrewhercules** [comment]
Can we please make a small adjustment to the data table?

**Column headings**
- [ ] Rename "UniProt - Pathology & Biotech" to "Reported protein"

**Comment by mirandaio** [comment]
@andrewhercules adjustments have been merged. Feel free to check again and close if done.

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API now available, can we please make a small adjustment to the UniProt Literature evidence table?

Sample query: [APP and nervous system disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000618%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000142192%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22uniprot_literature%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20targetFromSourceId%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

- [ ] In the "Reported protein" column, please display the value in `evidences.rows[x].targetFromSourceId`, and please construct a link to UniProt using the following structure: 

`http://www.uniprot.org/uniprot/` + `evidences.rows[x].studyId`

**Comment by d0choa** [comment]
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”. In this case, as opposed to other cases, the `diseaseFromSource` field was not implemented yet
