### ISSUE TITLE
Create new SLAPenrich evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1235]
On the evidence page in the rewrite, can we please create a new data table that displays the SLAPenrich evidence data?

**Example GraphQL API query**
[AKT1 and breast cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22MONDO_0007254%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000142208%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22slapenrich%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20pathwayId%0A%20%20%20%20%20%20%20%20pathwayName%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Pathway | P-value |
| --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].pathwayName` | `evidences.rows[x].resourceScore` |
| **Sample data** | Breast cancer | Signaling by the B Cell Receptor (BCR) | 1.19e-14 |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Pathway" column to Reactome using the following construct - `http://www.reactome.org/PathwayBrowser/#` + `evidences.rows[x].pathwayId` (e.g. [IRS-mediated signalling](http://www.reactome.org/PathwayBrowser/#R-HSA-5658034))
3. Round the value in the "P-value" column to 5 decimal points (e.g. 2.8399999999999998e-14 becomes 2.83999e-14 or 2.84e-14, depending on what is feasible)

**QC checks**

- KDR (ENSG00000128052) and lung adenocarcinoma (EFO_0000571)
- TLR4 (ENSG00000136869) in glioblastoma multiforme (EFO_0000519)

**Comment by andrewhercules** [comment]
Can we please make a small adjustment to the data table?

**Column headings**
- [ ] Rename "Pathway" to "Significant pathway"
- [ ] Rename "Study p-value" to "p-value"

**Comment by d0choa** [comment]
- [ ] by default sort by "p-value" in ascending order

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make a small adjustment to the SLAPenrich evidence data table?

Sample query: [AKT1 and breast cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceData%20%7B%0A%20%20disease(efoId%3A%20%22MONDO_0007254%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000142208%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22slapenrich%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20pathwayId%0A%20%20%20%20%20%20%20%20pathwayName%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=evidenceData)

- [ ] After the "Disease" column, create a new column called "Reported disease/phenotype" and display the value in `evidences.rows[x].diseaseFromSource`

**Comment by d0choa** [comment]
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
