### ISSUE TITLE
Create new PROGENy evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1236]
On the evidence page in the rewrite, can we please create a new data table that displays the PROGENy evidence data?

**Example GraphQL API query**
[EGFR and squamous cell lung carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22EFO_0001071%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000146648%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22progeny%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20pathwayId%0A%20%20%20%20%20%20%20%20pathwayName%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Pathway | P-value |
| --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].pathwayName` | `evidences.rows[x].resourceScore` |
| **Sample data** | lung adenocarcinoma | Clathrin-mediated endocytosis | 3.03713e-14 |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Pathway" column to Reactome using the following construct - `http://www.reactome.org/PathwayBrowser/#` + `evidences.rows[x].pathwayId` (e.g. [IRS-mediated signalling](http://www.reactome.org/PathwayBrowser/#R-HSA-5658034))
3. Round the value in the "P-value" column to 5 decimal points (e.g. 2.8399999999999998e-14 becomes 2.83999e-14 or 2.84e-14, depending on what is feasible)

**QC checks**

- EGFR (ENSG00000146648) and squamous cell lung carcinoma (EFO_0000708) ** this entry has a very low `resourceScore` value and we may need to adjust how we round the score
- PIK3CA (ENSG00000121879) and gastric cancer (MONDO_0001056)

**Comment by javfg** [comment]
@andrewhercules should the decimal places be rounded to 5 instead of 3 as we discussed in the frontend meeting?

**Comment by andrewhercules** [comment]
@javfg yes please! 👍 

And with the [EGFR and squamous cell lung carcinoma association](https://alpha.targetvalidation.org/evidence/ENSG00000146648/EFO_0000708), are we able to render the very low p-value or does it round to 0?

**Comment by javfg** [comment]
> @javfg yes please! 
> 
> And with the [EGFR and squamous cell lung carcinoma association](https://alpha.targetvalidation.org/evidence/ENSG00000146648/EFO_0000708), are we able to render the very low p-value or does it round to 0?

Should be working: https://5fa3e26fc81855000788e078--platform-app.netlify.app/evidence/ENSG00000146648/EFO_0000708

![image](https://user-images.githubusercontent.com/6058151/98236761-ca36b500-1f5b-11eb-9cf9-f79bf57728e0.png)

**Comment by andrewhercules** [comment]
Can we please make a small adjustment to the data table?

**Column headings**
- [ ] Rename "Pathway" to "Significant pathway"
- [ ] Rename "Study p-value" to "p-value"

**Comment by d0choa** [comment]
- [ ] by default sort by "p-value" in ascending order

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make a small adjustment to the PROGENy evidence data table?

Sample query: [EGFR and squamous cell lung carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22EFO_0001071%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000146648%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22progeny%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20pathwayId%0A%20%20%20%20%20%20%20%20pathwayName%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

- [ ] After the "Disease" column, create a new column called "Reported disease/phenotype" and display the value in `evidences.rows[x].diseaseFromSource`

**Comment by d0choa** [comment]
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”

**Comment by d0choa** [comment]
- [ ] Look at potential issue with numeric sorting in *p*-value column
