### ISSUE TITLE
Create new Cancer Gene Census evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1237]
On the evidence page in the rewrite, can we please create a new data table that displays the Cancer Gene Census evidence data?

**Example GraphQL API query**
[WRN and colorectal carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001951%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000165392%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22cancer_gene_census%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20variations%7B%0A%20%20%20%20%20%20%20%20%20%20functionalConsequence%0A%20%20%20%20%20%20%20%20%20%20numberSamplesWithMutationType%0A%20%20%20%20%20%20%20%20%20%20numberSamplesTested%0A%20%20%20%20%20%20%20%20%20%20numberMutatedSamples%0A%20%20%20%20%20%20%20%20%20%20inheritancePattern%0A%20%20%20%20%20%20%20%20%20%20variantAminoacidDescription%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Mutation type | Samples | Cellular mechanism | Literature |
| --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].variations[y].functionalConsequence` | `evidences.rows[x].variations[y].numberSamplesWithMutationType` / `evidences.rows[x].variations[y].numberSamplesTested` | `evidences.rows[x].variations[y].inheritancePattern` | `evidences.rows[x].literature`
| **Sample data** | colorectal adenocarcinoma | <ul><li>SO_0001587</li><li>SO_0001587</li><li>SO_0001587</li><li>SO_0001587</li></ul> | <ul><li>3 / 1219</li><li>57 / 1219</li><li>1 / 1219</li><li>34 / 1219</li></ul> | <ul><li>recessive</li><li>recessive</li><li>recessive</li><li>recessive</li></ul>  | 5 publications

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Display the values in the "Mutation type", "Samples", and "Cellular mechanism" columns as an unordered list
3. In the "Literature" column, please use the literature drawer component used in previous detail views (e.g. Gene2Phenotype) where rows with 2+ literature references open in the drawer and display the PMIDs

**QC checks**

- WRN (ENSG00000165392) and colon adenocarcinonma (EFO_1001949)
- BCL10 (ENSG00000142867) and Gastric Diffuse Large B-Cell Lymphoma (EFO_1000270)
- POLD1 (ENSG00000062822) and esophageal squamous cell carcinoma (EFO_0005922)

**Comment by andrewhercules** [comment]
Can we please make the following adjustments to the data table?

**General formatting**
- [ ] Remove bullet points in the "Mutation Type" and "Samples" columns
- [ ] Format the content in the "Mutation type" column by removing underscores and creating a link using the following construct - `https://identifiers.org/` + `evidences.rows[x].variations[y].functionalConsequence.id` (e.g. [missense variant](https://identifiers.org/SO:0001583))  *note: this is similar to what is done with the Open Targets Genetics data table "Functional consequence" column (e.g. [NOD2 and IBD](https://alpha.targetvalidation.org/evidence/ENSG00000167207/EFO_0003767))

**Columns**
- [ ] Rename "Samples" column to ""Mutated / Total samples" 
- [ ] Remove "Cellular mechanism" column as the field will be deprecated by the next iteration of the API

**New "Role in cancer" component**
 
- [ ] Create a new "role in cancer" reusable component that displays the target's role in cancer data using chips as noted in the design specification below

The component will be reused for the IntOGen evidence table #1238 and on the target profile page.

Please make the chips in the same style as the chips used in the "Methods" column of the intOGen data table- see the [ESR1 and breast carcinoma evidence page](https://alpha.targetvalidation.org/evidence/ENSG00000091831/EFO_0000305) for an example

![Screenshot 2020-11-17 at 11 54 30](https://user-images.githubusercontent.com/7490258/99387359-c3009700-28cb-11eb-867c-f1ce7f52f8cd.png)

The data for the chips is available in the target object:

```
target {
  hallmarks{ 
    attributes{
      reference {
        pubmedId
        description
      }
      name
    } 
  }
}
```

Please note that the GraphQL API will return an array of attributes and this array will need to be filtered , with chips visible for entries where `name == "role in cancer"` ([sample query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001951%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000091831%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22cancer_gene_census%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20hallmarks%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%09attributes%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20reference%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pubmedId%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs))

![Screenshot 2020-11-17 at 11 57 03](https://user-images.githubusercontent.com/7490258/99387527-0fe46d80-28cc-11eb-8abf-ec562607b968.png)

**Comment by d0choa** [comment]
Thanks @andrewhercules. I just want to add that the Cancer Hallmarks widget in the target profile page has the same logic on it. It would be good to reuse the component in the 3 sections

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make some small adjustments to the Cancer Gene Census evidence data table?

- [ ] Update the data used in the "Mutation type" and "Mutated / Total samples" columns as the structure of the data has changed and is now found in an array called `evidences.rows[x].mutatedSamples[y]`. For more information, see this sample query for [WRN and colorectal carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceTable%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001951%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000165392%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22cancer_gene_census%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%09%09%09%09mutatedSamples%7B%0A%20%20%20%20%20%20%20%20%20%20functionalConsequence%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20numberSamplesTested%0A%20%20%20%20%20%20%20%20%20%20numberSamplesWithMutationType%0A%20%20%20%20%20%20%20%20%20%20numberMutatedSamples%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=evidenceTable).

**Comment by d0choa** [comment]
- [ ] The “mutated /total samples” column is not very readable. Instead, try to show the content in the next formatting: XX% (n / n). I would left align it and include the parenthesis in a smaller font (similar to genetics portal variant id (rsid) formatting)
- [ ] If possible sort sub-rows and rows (by % or max %, respectively) in decreasing order

**Comment by d0choa** [comment]
Also for the reusable component:
- [ ] When no role in cancer is available (E.g. [WRN helicase](https://alpha.targetvalidation.org/evidence/ENSG00000165392/EFO_1001951?view=sec:affected_pathway)) display “Unknown” in a chip instead of “N/A”.

**Comment by d0choa** [comment]
- [ ] Polish percentages appearance
- [ ] Sort rows by default by max percentage in row (descending)
