### ISSUE TITLE
Create new intOGen evidence table in rewrite version 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1238]
On the evidence page in the rewrite, can we please create a data table that displays the intOGen evidence data, using work previously done by @LucaFumis and noted in merged into `platform-app` in opentargets/platform-app/pull/126?

**Example GraphQL API query**
[BRAF and non-small cell lung carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_1340%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22gene2phenotype%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20confidence%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20allelicRequirement%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Inheritance pattern | Mutated samples / Total samples | P-value | Methods | Cohort information |
| --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].variations[y].inheritancePattern` | `evidences.rows[x].variations[y].numberMutatedSamples` / `evidences.rows[x].variations[y].numberSamplesTested` | `evidences.rows[x].resourceScore` | `evidences.rows[x].significantDriverMethods`| `evidences.rows[x].cohortShortName` and `evidences.rows[x].cohortDescription` |
| **Sample data** | Lung adenocarcinoma | dominant | 33 / 560 | 1.702e-30 | CBaSE, dNdScv, HotMAPS, MutPanning, CLUSTL, FML, smRegions | LUAD_TCGA Lung adenocarcinoma data from TCGA/PanCanAtlas |

Further details, including design mocks showing method chips and on-hover tooltips, are available in #863; however please note that the "Mutation type" column has been dropped and replaced with the "Inheritance pattern" column. Also, please note that the API is currently returning `null` for `significantDriverMethods` but that will be amended with the latest API release and will return an array of string elements, which can be displayed as chips as noted in the design spec.

Within the data table, can we please do the following?

1. Round the value in the "P-value" column to 3 decimal points?
2. Link the `evidences.rows[x].cohortShortName` in the "Cohort information" column to the inTOgen website using the following construct - `https://www.intogen.org/search?gene=` + evidences.rows[x].target.approvedSymbol` + `&cohort=` + evidences.rows[x].cohortId (e.g. [CBIOP_WXS_LUAD_BROAD](https://www.intogen.org/search?gene=BRAF&cohort=CBIOP_WXS_LUAD_BROAD))

**QC checks**

- BRAF (ENSG00000157764) and multiple myeloma (EFO_0001378) 
- FGFR1 (ENSG00000077782) and ovarian carcinoma (MONDO_0008170)

**Comment by javfg** [comment]
[Example query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidence_intogen%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0001378%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22intogen%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20variations%20%7B%0A%20%20%20%20%20%20%20%20%20%20numberMutatedSamples%0A%20%20%20%20%20%20%20%20%20%20numberSamplesTested%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20significantDriverMethods%0A%20%20%20%20%20%20%20%20cohortShortName%0A%20%20%20%20%20%20%20%20cohortDescription%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=evidence_intogen).

**Comment by d0choa** [comment]
`significantDriverMethods` will be fixed in the next iteration. It's an array of strings but comes null at the moment.

**Comment by andrewhercules** [comment]
My apologies @javfg , I added the incorrect query: [BRAF and non-small cell lung carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0003060%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22intogen%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20cohortId%0A%20%20%20%20%20%20%20%20cohortShortName%0A%20%20%20%20%20%20%20%20cohortDescription%0A%09%09%09%09resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20significantDriverMethods%0A%20%20%20%20%20%20%20%20variations%7B%0A%20%20%20%20%20%20%20%20%20%20functionalConsequence%0A%20%20%20%20%20%20%20%20%20%20inheritancePattern%0A%20%20%20%20%20%20%20%20%20%20numberSamplesTested%0A%20%20%20%20%20%20%20%20%20%20numberMutatedSamples%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by andrewhercules** [comment]
Can we please make the following adjustments to the data table?

**Columns**
- [ ] Remove the "Inheritance pattern" column as the field will be deprecated by the next iteration of the API
- [ ] Rename the "Mutated samples / Total samples" column to "Mutated / Total samples"
- [ ] Rename the "Study p-value" column to "Combined p-value" with a tool tip that links to the IntOGen FAQ page at https://www.intogen.org/faq
- [ ] Rename the "Methods" column to "Cancer driver methods"

**Table functionality**
- [ ] Allow user to search by "Disease", "Cancer drive methods" and "Cohort information" columns
- [ ] By default, sort the table by the value in the "Combined p-value" column in descending order

**New "Role in cancer" component**
 
- [ ] Create a new "role in cancer" reusable component that displays the target's role in cancer data using chips as noted in the design specification below

The component will be reused for the Cancer Gene Census evidence table #1237 and on the target profile page.

Please make the chips in the same style as the chips used in the "Methods" column of the intOGen data table- see the [ESR1 and breast carcinoma evidence page](https://alpha.targetvalidation.org/evidence/ENSG00000091831/EFO_0000305) for an example

![Screenshot 2020-11-17 at 12 12 31](https://user-images.githubusercontent.com/7490258/99388916-31deef80-28ce-11eb-955a-e97fbdc104e9.png)

The data for the chips is available in the target object:

```
target {
  hallmarks{ 
    attributes{
      reference {
        pubmedId
        description
      }
      name
    } 
  }
}
```

Please note that the GraphQL API will return an array of attributes and this array will need to be filtered , with chips visible for entries where `name == "role in cancer"` ([sample query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000305%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000091831%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22intogen%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20hallmarks%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%09attributes%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20reference%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pubmedId%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

![Screenshot 2020-11-17 at 11 57 03](https://user-images.githubusercontent.com/7490258/99387527-0fe46d80-28cc-11eb-8abf-ec562607b968.png)

**Comment by d0choa** [comment]
Thanks @andrewhercules. I just want to add that the Cancer Hallmarks widget in the target profile page has the same logic on it. It would be good to reuse the component in the 3 sections

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make some small adjustments to the intOGen evidence data table?

- [ ] Update the data used in the "Mutation type" and "Mutated / Total samples" columns as the structure of the data has changed and is now found in an array called `evidences.rows[x].mutatedSamples[y]`. For more information, see this sample query for [BRAF and lung cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceTable%20%7B%0A%20%20disease(efoId%3A%20%22MONDO_0008903%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22intogen%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20mutatedSamples%7B%0A%20%20%20%20%20%20%20%20%20%20functionalConsequence%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20numberSamplesTested%0A%20%20%20%20%20%20%20%20%20%20numberMutatedSamples%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20cohortId%0A%20%20%20%20%20%20%20%20cohortShortName%0A%20%20%20%20%20%20%20%20cohortDescription%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20significantDriverMethods%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=evidenceTable)

- [ ] After the "Disease column", add a column called "Reported disease/phenotype" and show the `evidences.rows[x].diseaseFromSource` value

**Comment by d0choa** [comment]
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
- [ ] The “mutated /total samples” column is not very readable. Instead, try to show the content in the next formatting: XX% (n / n). I would left align it and include the parenthesis in a smaller font (similar to genetics portal variant id (rsid) formatting)

**Comment by d0choa** [comment]
- [ ] Polish percentages appearance
