### ISSUE TITLE
Create new SysBio evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1239]
On the evidence page in the rewrite, can we please create a new data table that displays the SysBio evidence data?

**Example GraphQL API query**
[PSEN1 and late-onset Alzheimers disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001870%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000080815%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22sysbio%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%09%09%09%09resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20experimentOverview%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Experiment overview | Literature |
| --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].experimentOverview` | `evidences.rows[x].literature`
| **Sample data** | late-onset Alzheimers disease | n/a | 1 publication |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform

Please note that the GraphQL API returns `null` for `evidences.rows[x].experimentOverview` as that data will be made available based on upstream changes by the data team.

Also, please note that each row will only have one literature reference as this source relies on 4 specific papers. 

**QC checks**

- TAGAP (ENSG00000164691) and inflammatory bowel disease (EFO_0003767)
- CD72 (ENSG00000137101) and coronary heart disease (EFO_0001645)

**Comment by d0choa** [comment]
The idea is to coalesce `studyOverview` and `experimentOverview` and only keep `studyOverview`. `study` seems to be more consistent with other fields (e.g. `studyId`).

The information contained in `studyOverview` is the correct one for SysBio, so we won't expect any changes in the future.

The changes in the next iteration will therefore not affect this work.

**Comment by d0choa** [comment]
Sysbio does crash for this page
https://alpha.targetvalidation.org/evidence/ENSG00000130702/EFO_0001645

**Comment by andrewhercules** [comment]
Can we please make an adjustment to the SysBio evidence data table?

**Columns**
- [ ] Set a max width on the "Study overview" column to prevent layout/readability issues
![Screenshot 2020-11-17 at 13 56 54](https://user-images.githubusercontent.com/7490258/99399051-09122680-28dd-11eb-90c2-8efc714e39ae.png)
- [ ] Limit the content in the "Study overview" column to only show the first 260 characters, with a link that to show more - this would be similar what is currently available in the SysBio data table (e.g. [PSEN1 and Alzheimer's disease](https://www.targetvalidation.org/evidence/ENSG00000080815/EFO_0000249?view=sec:affected_pathway)) based on [lines 162 to 169 in the webapp sysbio-table-directive.js file](https://github.com/opentargets/webapp/blob/c3752925af65fcc788ba53e31f4c6cb4170df0e2/app/src/components/sysbio-table/sysbio-table-directive.js#L162)

**Comment by javfg** [comment]
> * [x]  Limit the content in the "Study overview" column to only show the first 260 characters, with a link that to show more - this would be similar what is currently available in the SysBio data table (e.g. [PSEN1 and Alzheimer's disease](https://www.targetvalidation.org/evidence/ENSG00000080815/EFO_0000249?view=sec:affected_pathway)) based on [lines 162 to 169 in the webapp sysbio-table-directive.js file](https://github.com/opentargets/webapp/blob/c3752925af65fcc788ba53e31f4c6cb4170df0e2/app/src/components/sysbio-table/sysbio-table-directive.js#L162)

The length of characters shown is dynamic depending on the viewport size, but it will always be one line. This is to allow the table to stay responsive.

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make an adjustment to the SysBio evidence data table?

Sample query: [PSEN and late-onset Alzheimer's disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001870%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000080815%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22sysbio%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%09%09%09%09studyOverview%0A%20%20%20%20%20%20%20%20literature%0A%09%09%09%09pathwayName%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

- [ ] Rename the "Experiment overview" column "Gene set" 

- [ ] In the "Gene set" column, display the data in `evidences.rows[x].pathwayName` and after the text, display a tooltip and on-hover show the data in `evidences.rows[x].studyOverview`

**Comment by d0choa** [comment]
-[ ] Rename “Disease” column to “Disease/phenotype” for consistency
