### ISSUE TITLE
migrate Ghost to version 2.0

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#124]
Ghost (platform for our blog) has a new version.

How can we upgrade/migrate to 2-0?
https://blog.ghost.org/2-0/

It is free (the pricing is for hosting only).

It'd be good to have this done before @elipapa leaves for pasture news.

**Comment by elipapa** [comment]
i would argue that this is not `priority: High`. That said it's probably a good chance for handover.

The blog is served from a single VM. Happy to show someone where everything is.. @afaulconbridge ?

**Comment by deniseOme** [comment]
Feel free to change the Priority for medium or low. 

@LucaFumis may be a good person to join @afaulconbridge.

**Comment by afaulconbridge** [comment]
Give that there are no known problems that need this to be done to fix it (though I agree that keeping reasonably up-to-date is a good thing) I'm going to reduce  the priority of this issue.

**Comment by deniseOme** [comment]
Deemed to be low priority plus no problems so far while sticking with previous Ghost version.
