### ISSUE TITLE
Create new CRISPR evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1240]
On the evidence page in the rewrite, can we please create a new data table that displays the SysBio evidence data?

**Example GraphQL API query**
[WRN and colorectal carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001870%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000080815%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22sysbio%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%09%09%09%09resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20experimentOverview%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Priority score | Literature |
| --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].resourceScore` | `evidences.rows[x].literature`
| **Sample data** | colorectal carcinoma | 0.7375 | 1 publication |

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Round the value in the "Priority score" column to 3 decimal points

Also, please note that each row will only have one literature reference as this source relies on a specific paper - [Behan, F. et al, 2019](https://www.nature.com/articles/s41586-019-1103-9).

**QC checks**

- CDK6 (ENSG00000105810) and glioma (EFO_0005543)
- GPX4 (ENSG00000167468) and oral cavity carcinoma (MONDO_0044925)

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make some adjustments to the CRISPR evidence data table?

Sample query: [WRN and cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceDataTable%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000311%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000165392%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22crispr%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20diseaseCellLines%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A&operationName=evidenceDataTable)

- [ ] After the "Disease/phenotype" column, create a new column called "Reported disease/phenotype"

- [ ] In the "Reported disease/phenotype" column, display a string with the number of cell lines and reported disease/phenotype, using the following construct:

`(evidences.rows[x].diseaseCellLines).length` + `evidences.rows[x].diseaseFromSource` + `cell lines`

For example, assuming the first entry from the sample query above: `33 ovarian carcinoma cell lines`

Also, create a link when the user clicks on the string that it opens the drawer component and shows the list of cell lines found in the `evidences.rows[x].diseaseCellLines` array

**Comment by d0choa** [comment]
- [ ] In the drawer, rename title to “Cancer Cell Lines”
