### ISSUE TITLE
Create new Reactome evidence tables in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1241]
On the evidence page in the rewrite, can we please create a new data table that displays the Gene2Phenotype evidence data?

**Example GraphQL API query**
[APC and colorectal carcinoma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_1001951%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000134982%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22reactome%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20pathwayId%0A%20%20%20%20%20%20%20%20pathwayName%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%09literature%0A%09%09%09%09variations%7B%0A%20%20%20%20%20%20%20%20%20%20variantAminoacidDescription%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Pathway | Target modulation | Amino acid variation | Literature |
| --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].pathwayName` | `evidences.rows[x].targetModulation` | `evidences.rows[x].variations[y].variantAminoacidDescription` | `evidences.rows[x].literature` |
| **Sample data** | colorectal adenocarcinoma | APC truncation mutants have impaired AXIN binding | n/a | L-asparagine 1378 replaced with unknown | 12 publications

Please note that the GraphQL API is not exposing the `evidences.rows[x].targetModulation`; however, this field will be available in the next iteration of the API.

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Pathway" column to Reactome using the following construct - `http://www.reactome.org/PathwayBrowser/#` + `evidences.rows[x].pathwayId` (e.g. [IRS-mediated signalling](http://www.reactome.org/PathwayBrowser/#R-HSA-5658034))
3. Ensure that the "Amino acid variation" column can accept an empty array as some evidence strings do not have data for this column (e.g.  DPM3 and congenital disorder of glycosylation type I - see QC checks section)
3. Use the literature drawer component used in other detail views (e.g. Gene2Phenotype) when the evidence row has 2+ literature references 

**QC checks**

- DPM3 (ENSG00000179085) and congenital disorder of glycosylation type I (EFO_0005545)
- FGF8 (ENSG00000107831) and bone development disease (EFO_0005541)

**Comment by andrewhercules** [comment]
Can we please make some small adjustments to the data table?

- [ ] Remove underscores from value in "Target modulation" column
- [ ] Remove bullet points in "Amino acid variation" column if only one value, otherwise show bullet points
- [ ] Allow users to search the text in the "Amino acid variation column"
- [ ] Include the "Rows per page:" feature

![Screenshot 2020-11-13 at 09 10 17](https://user-images.githubusercontent.com/7490258/99050713-18693b00-2590-11eb-8f08-81e397fffb89.png)
[EGFR and cancer](https://alpha.targetvalidation.org/evidence/ENSG00000146648/EFO_0000311)

**Comment by mirandaio** [comment]
@andrewhercules adjustments have been merged. Feel free to check again and close if done.

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make some adjustments to the Reactome evidence data table?

- [ ] Create a new column called "Reported disease/phenotype" and display the `evidences.rows[x].diseaseFromSource` value

- [ ] After the "Pathway" column, create a new column called "Reaction" and display the `evidence.rows[x].reactionId` and use that value to link to Reactome using identifiers.org - `http://identifiers.org/reactome/` + `evidence.rows[x].reactionId` (e.g. [R-HSA-4791278](https://reactome.org/content/detail/R-HSA-4791278))

- [ ] After the new "Reaction" column, create a new column called "Reported target" and display the `evidences.rows[x].targetFromSourceId` and use that value to link to UniProt using identifers.org - `http://identifiers.org/uniprot/` + `evidences.rows[x].targetFromSourceId` (e.g. [P25054](http://identifiers.org/uniprot/P25054))\

- [ ] In the "Amino acid variation" column, display the entries in the `evidences.rows[x].variantAminoacidDescriptions` array

**Comment by d0choa** [comment]
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
