### ISSUE TITLE
Create new ChEMBL evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1244]
On the evidence page in the rewrite, can we please create a new data table that displays the ChEMBL evidence data?

**Example GraphQL API query**
[BRAF and lung cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22MONDO_0008903%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22chembl%22%5D%2C%20size%3A10)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20clinicalPhase%0A%20%20%20%20%20%20%20%20clinicalStatus%0A%20%20%20%20%20%20%20%20clinicalUrls%7B%0A%20%20%20%20%20%20%20%20%20%20niceName%0A%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20drug%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismsOfAction%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20targets%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Drug | Drug type | Mechanism of action | Target | Phase | Status | Source |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].drug.name` | `evidences.rows[x].drug.drugType` |  `evidences.rows[x].drug.mechanismsOfAction[y].mechanismOfAction`  | `evidences.rows[x].drug.mechanismsOfAction[y].targets[z].approvedSymbol` | `evidences.rows[x].clinicalPhase` | `evidences.rows[x].clinicalStatus` |  `evidences.rows[x].clinicalUrls[y].niceName` |
| **Sample data** | non-small cell lung carcinoma | Sorafenib | Small molecule | Serine/threonine-protein kinase B-raf inhibitor | BRAF | Phase II | Completed | ClinicalTrials.gov | 

The data table should look and function like the Known Drugs table found on the disease/phenotype profile page (e.g. [non-small cell lung carcinoma](https://alpha.targetvalidation.org/disease/EFO_0003060)), minus the grey background in the "Drug" column.

![Screenshot 2020-11-06 at 13 00 36](https://user-images.githubusercontent.com/7490258/98368990-1d7a3780-2030-11eb-8003-e95f0790a390.png)

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Drug" column to the relevant profile page in the Platform
3. Link the value in the "Target" column to the relevant profile page in the Platform 
4. Map the value in the "Phase" column to `Phase` + number as roman numeral (e.g. 2 --> Phase II)
5. Show the `clinicalUrls` values in the "Source" column using the drawer-based approach found in the Known Drugs section on the profile pages

Mechanism of action note: TBC

**Comment by d0choa** [comment]
The component crashes for the next target disease pair:
https://alpha.targetvalidation.org/evidence/ENSG00000141510/EFO_0001421

**Comment by mirandaio** [comment]
@d0choa issue should be fixed now

**Comment by andrewhercules** [comment]
Can we please make some adjustments to the data table?

**Table functionality**
- [ ] Implement "Rows per page" feature to allow users to set number of rows visible in table
- [ ] By default, sort by phase (descending order)
- [ ] Allow user to search by all columns

**General formatting**
- [ ] Update the formatting of the values in the "Phase" column to display as roman numerals as seen on the profile pages (e.g. `2` --> `Phase II`)
- [ ] Update how the labels in the "Source" column are displayed
FDA Information --> FDA
Clinical Trials Information --> ClinicalTrials.gov
DailyMed Information --> DailyMed
ATC Information --> ATC

**Columns**
- [ ] Remove the top-row header with "Disease information", "Drug information", "Target information", "Clinical trials information"
- [ ] Rename the column "Drug type" to "Modality"
- [ ] Rearrange the column orders - "Disease/phenotype", "Target", "Drug", "Modality", "Mechanism of action", "Phase", "Status", "Source"
- [ ] Apply grey background to "Disease/phenotype" and "Target" columns to indicate both columns have been fixed
- [ ] If possible, can both the "Disease/phenotype" and "Target" columns be fixed, similar to how the "Drug" column is fixed on the target and disease/phenotype profile pages?

**Other changes**

- [ ] When a drug has more than one target, please show the target that is fixed on the evidence page followed by the number of other targets, otherwise just show the target. For example, on the [BRAF and lung cancer evidence page](https://alpha.targetvalidation.org/evidence/ENSG00000157764/MONDO_0008903): 

![Screenshot 2020-11-24 at 09 55 04](https://user-images.githubusercontent.com/7490258/100078506-80930900-2e3b-11eb-8adb-607e5cc3ef49.png)

- [ ] Similarly, for mechanisms of action, please show the mechanism of action associated to the target fixed on the evidence page and then hide all other mechanisms of action behind a "show more" button. For example, on the [BRAF and lung cancer evidence page](https://alpha.targetvalidation.org/evidence/ENSG00000157764/MONDO_0008903): 

![Screenshot 2020-11-24 at 12 27 32](https://user-images.githubusercontent.com/7490258/100094221-94953580-2e50-11eb-8fca-b723b010b5ae.png)

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make a small adjustment to the ChEMBL evidence data table?

Sample query: [BRAF and lung cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22MONDO_0008903%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22chembl%22%5D%2C%20size%3A10)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20targetFromSourceId%0A%20%20%20%20%20%20%20%20clinicalPhase%0A%20%20%20%20%20%20%20%20clinicalStatus%0A%20%20%20%20%20%20%20%20clinicalUrls%7B%0A%20%20%20%20%20%20%20%20%20%20niceName%0A%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20drug%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismsOfAction%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20targets%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

- [ ] Rename the "Target" column to "Target (Reported protein)"and in the column, beside the target HGNC symbol, please display the `evidences.rows[x].targetFromSourceId` value in brackets and link to UniProt.org using identifiers.org - `https://identifiers.org/uniprot/` + `evidences.rows[x].targetFromSourceId` - see below for examples:

[BRAF](https://alpha.targetvalidation.org/target/ENSG00000157764) ([P15056](https://identifiers.org/uniprot/P15056)) and 8 other targets

[BRAF](https://alpha.targetvalidation.org/target/ENSG00000157764) ([P15056](https://identifiers.org/uniprot/P15056))

**Comment by d0choa** [comment]
- [ ] Similar to the reported disease/phenotype tooltip, display the uniprot accession in a tooltip. The tooltip content would be “Reported target: targetFromSource”. Maintain the link to uniprot if the tooltip can be clickable. Update the header to "Targets"
