### ISSUE TITLE
Create new EVA evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1245]
On the evidence page in the rewrite, can we please create a new data table that displays the EVA evidence data?

**Example GraphQL API query**
[KIT and Piebaldism](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22Orphanet_2884%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157404%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22eva%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20clinicalSignificance%0A%20%20%20%20%20%20%20%20recordId%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20variantFunctionalConsequenceScore%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Reported disease/phenotype | Variant | ClinVar ID | Functional consequence | Clinical significance | P-value | Literature
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].diseaseFromSource` | `evidences.rows[x].variantRsId` | `evidences.rows[x].recordId` | `evidences.rows[x].variantFunctionalConsequence.label` | `evidences.rows[x].clinicalSignificance` | `evidences.rows[x].resourceScore` | `evidences.rows[x].literature` |
| **Sample data** | Piebaldism | partial albinism | rs794726672 | RCV000014859 | Frameshift variant | Pathogenic | 1e-7 | 1 publication

Please note that not all rows will have an entry in `literature`.

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Variant" column to Ensembl using the following construct - `http://www.ensembl.org/Homo_sapiens/Variation/Explore?v=` + `evidences.rows[x].variantRsId` (e.g. [rs5743289](http://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs5743289))
3. Link the value in the "ClinVar ID" column to the ClinVar website using the following construct - `https://www.ncbi.nlm.nih.gov/clinvar/` + `evidences.rows[x].recordId` (e.g. [RCV000014862](https://www.ncbi.nlm.nih.gov/clinvar/RCV000014862/))
4. Link the value in the "Functional consequence" column to the Sequence Ontology website using the following construct - `http://www.sequenceontology.org/browser/current_svn/term/ ` + `evidences.rows[x].variantFunctionalConsequence.id` (e.g. [frameshift variant](http://www.sequenceontology.org/browser/current_svn/term/SO:0001589))
4. Round the p-value to 3 decimal places
5. Use the literature drawer component used in other evidence tables (e.g. Gene2Phenotype) for rows with 2+ literature entries 

**QC checks**

- SOS1 (ENSG00000115904) and Noonan syndrome (Orphanet_648)
- MXI1 (ENSG00000119950) and prostate carcinoma (EFO_0001663)
- HTT (ENSG00000197386) and Huntington disease (Orphanet_399)

**Comment by d0choa** [comment]
The identifiers.org prefixes to build the links are: 
- `SO` for sequence ontology
- `clinvar.record` for clinvar RCV
- `dbsnp` for rsid - this goes against Ensembl suggestion above. Just including here because it's the official service

**Comment by AsierGonzalez** [comment]
Are we also going to display the `review_status` or `star_rating` in `evidence.variant2disease.clinvar_rating`?

**Comment by d0choa** [comment]
Yes we are, but the above work is with the currently available data. Once we have 20.11 data we will add the columns.

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please update the EVA evidence data table?

- [ ] Update "Allelic requirement" column as previously, the field was a string `evidences.rows[x].allelicRequirement`; however, it is now an array called `evidences.rows[x].allelicRequirements` with an "s". Within the column, if there is only one entry in `evidences.rows[x].allelicRequirements`, please display the string. If there are two or more entries in `evidences.rows[x].allelicRequirements`, please list the entries in an unordered list. ** **Please note that very often, this field will be `null`** **

- [ ] Remove the "P-value" column and replace with a column called "Score" and display the `evidences.rows[x].resourceScore` value and by default, sort the table by this column (descending order) 

- [ ] Ensure that the "Variant" column can accept `null` values 

- [ ] In the "ClinVar ID" column, please display the `evidences.rows[x].studyId` as the `recordId` field has been deprecated

- [ ] The field `evidences.rows[x].clinicalSignificance` has become an array called `evidences.rows[x].clinicalSignificances` - please display the elements of that array in the "Clinical significance" column

- [ ] In the "Confidence" column, map the strings returned by the API to [ClinVar's star ratings](https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/#:~:text=Review%20status-,Definition,review%20status%20on%20web%20pages)

Number of stars | String returned by GraphQL API | 
-- | -- 
four | practice guideline |
three | reviewed by expert panel |
two | criteria provided, multiple submitters, no conflicts | 
one | criteria provided, conflicting interpretations | 
one | criteria provided, single submitter | 
none | no assertion for the individual variant | 
none | no assertion criteria provided | 
none | no assertion provided |

For the stars, please use the [FontAwesome star-solid icon](https://fontawesome.com/icons/star?style=solid) with the Open Targets Corporate Blue `#3489ca`

**Comment by d0choa** [comment]
-[ ] please show the `confidence` string when hovering the stars, not to loose the extra granularity that the text message provides

**Comment by d0choa** [comment]
As discussed:
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
- [ ] Add show more rows functionality to table.
- [ ] Add empty stars as they do in [clinvar](https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/)
- [ ] Also add the tooltip on-hover for entires with no stars
- [ ] Remove score column
- [ ] Implement logic to load everything when entries < n (1000?) but disallow search and pagination when entries > 1000
