### ISSUE TITLE
Create new EVA (Somatic) evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1246]
On the evidence page in the rewrite, can we please create a new data table that displays the EVA (Somatic) evidence data?

**Example GraphQL API query**
[BRAF and lung cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22MONDO_0008903%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22eva_somatic%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20clinicalSignificance%0A%20%20%20%20%20%20%20%20recordId%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20variations%7B%0A%20%20%20%20%20%20%20%20%20%20functionalConsequence%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Reported disease/phenotype | ClinVar ID | Functional consequence | Clinical significance | Literature |
| --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].diseaseFromSource`  | `evidences.rows[x].recordId` | `evidences.rows[x].variations[y].functionalConsequence.label` | `evidences.rows[x].clinicalSignificance` | `evidences.rows[x].literature` |
| **Sample data** | lung carcinoma | lung cancer | RCV000014859 | Missense variant | Pathogenic | 5 publications

Please note that not all rows will have an entry in `literature`.

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "ClinVar ID" column to the ClinVar website using identifers.org and the following construct - `https://identifiers.org/clinvar.record/` + `evidences.rows[x].recordId` (e.g. [RCV000014862](https://identifiers.org/clinvar.record/RCV000014862))
3. Reformat the value in the "Functional consequence" column by removing the underscores separating each work (e.g. "inframe_deletion" --> "Inframe deletion")
4. Link the value in the "Functional consequence" column to the Sequence Ontology website using identifers.org the following construct - `https://identifiers.org/so/` + `evidences.rows[x].variations[y].functionalConsequence.id` (e.g. [Frameshift variant](https://identifiers.org/so/SO:0001589))
5. Use the literature drawer component used in other evidence tables (e.g. Gene2Phenotype) for rows with 2+ literature entries 

**QC checks**

- CNOT9 (ENSG00000144580) and hepatocellular carcinoma (EFO_0000182)
- AC058822.1 (ENSG00000282278) and melanoma (EFO_0000756)

**Comment by AsierGonzalez** [comment]
Are we also going to display the `review_status` or `star_rating` in `evidence.clinvar_rating`?

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please update the EVA evidence data table?

Sample query: [KIT and piebaldism](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%22Orphanet_2884%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157404%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22eva%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20clinicalSignificances%0A%20%20%20%20%20%20%20%20score%0A%09%09%09%09literature%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

- [ ] Update "Allelic requirement" column as previously, the field was a string `evidences.rows[x].allelicRequirement`; however, it is now an array called `evidences.rows[x].allelicRequirements` with an "s". Within the column, if there is only one entry in `evidences.rows[x].allelicRequirements`, please display the string. If there are two or more entries in `evidences.rows[x].allelicRequirements`, please list the entries in an unordered list. ** **Please note that very often, this field will be `null`** **

- [ ] Remove the "P-value" column and replace with a column called "Score" and display the `evidences.rows[x].score` value and by default, sort the table by this column (descending order) 

- [ ] Ensure that the "Variant" column can accept `null` values 

- [ ] In the "ClinVar ID" column, please display the `evidences.rows[x].studyId` as the `recordId` field has been deprecated

- [ ] The field `evidences.rows[x].clinicalSignificance` has become an array called `evidences.rows[x].clinicalSignificances` - please display the elements of that array in the "Clinical significance" column

- [ ] In the "Confidence" column, map the strings returned by the API to [ClinVar's star ratings](https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/#:~:text=Review%20status-,Definition,review%20status%20on%20web%20pages)

Number of stars | String returned by GraphQL API | 
-- | -- 
four | practice guideline |
three | reviewed by expert panel |
two | criteria provided, multiple submitters, no conflicts | 
one | criteria provided, conflicting interpretations | 
one | criteria provided, single submitter | 
none | no assertion for the individual variant | 
none | no assertion criteria provided | 
none | no assertion provided |

For the stars, please use the [FontAwesome star-solid icon](https://fontawesome.com/icons/star?style=solid) with the Open Targets Corporate Blue `#3489ca`

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please update the EVA (Somatic) evidence data table?

Sample query: [BRAF and lung cancer](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceTable%20%7B%0A%20%20disease(efoId%3A%22MONDO_0008903%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000157764%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22eva_somatic%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20clinicalSignificances%0A%20%20%20%20%20%20%20%20score%0A%09%09%09%09literature%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=evidenceTable)

- [ ] Update "Allelic requirement" column as previously, the field was a string `evidences.rows[x].allelicRequirement`; however, it is now an array called `evidences.rows[x].allelicRequirements` with an "s". Within the column, if there is only one entry in `evidences.rows[x].allelicRequirements`, please display the string. If there are two or more entries in `evidences.rows[x].allelicRequirements`, please list the entries in an unordered list. ** **Please note that very often, this field will be `null`** **

- [ ] Remove the "P-value" column and replace with a column called "Score" and display the `evidences.rows[x].score` value and by default, sort the table by this column (descending order) 

- [ ] Ensure that the "Variant" column can accept `null` values 

- [ ] In the "ClinVar ID" column, please display the `evidences.rows[x].studyId` as the `recordId` field has been deprecated

- [ ] The field `evidences.rows[x].clinicalSignificance` has become an array called `evidences.rows[x].clinicalSignificances` - please display the elements of that array in the "Clinical significance" column

- [ ] In the "Confidence" column, map the strings returned by the API to [ClinVar's star ratings](https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/#:~:text=Review%20status-,Definition,review%20status%20on%20web%20pages)

Number of stars | String returned by GraphQL API | 
-- | -- 
four | practice guideline |
three | reviewed by expert panel |
two | criteria provided, multiple submitters, no conflicts | 
one | criteria provided, conflicting interpretations | 
one | criteria provided, single submitter | 
none | no assertion for the individual variant | 
none | no assertion criteria provided | 
none | no assertion provided |

For the stars, please use the [FontAwesome star-solid icon](https://fontawesome.com/icons/star?style=solid) with the Open Targets Corporate Blue `#3489ca`

**Comment by d0choa** [comment]
-[ ] please show the `confidence` string when hovering the stars, not to loose the extra granularity that the text message provides

**Comment by d0choa** [comment]
As discussed:
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
- [ ] Add show more rows functionality to table.
- [ ] Add empty stars as they do in [clinvar](https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/)
- [ ] Also add the tooltip on-hover for entires with no stars
- [ ] Remove score column
