### ISSUE TITLE
Create new Expression Atlas evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1247]
On the evidence page in the rewrite, can we please create a new data table that displays the Expression Atlas evidence data?

**Example GraphQL API query**
[CHI3L1 and inflammatory bowel disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000384%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000133048%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22expression_atlas%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20contrast%0A%20%20%20%20%20%20%20%20log2FoldChangeValue%0A%20%20%20%20%20%20%20%20log2FoldChangePercentileRank%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20studyOverview%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Data table**

| Data table column | Disease/phenotype | Experiment contrast | Experiment overview | Log2 fold change | P-value | Percentile rank | Experiment ID
| --- | --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].contrast` | `evidences.rows[x].studyOverview` | `evidences.rows[x].log2FoldChangeValue` | `evidences.rows[x].resourceScore` | `evidences.rows[x].log2FoldChangePercentileRank` | `evidences.rows[x].studyId` |
| **Sample data** | Crohn's disease | 'Crohn's disease, undetermined' vs 'non inflammatory bowel disease control' | DESeq2 version: 1.10.1 | 5.5 | 4.690000000000001e-19 | 99 | E-GEOD-57945

Please note that some `evidences.rows[x].resourceScore` values are returned in scientific notation (9.78e-9) and others are turned as a float (e.g. 0.00000653)

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Round the value in the "P-value" column to 3 decimal points 
3. Link the value in the "Experiment ID" column to the Expression Atlas results page using the following construct - 
`http://www.ebi.ac.uk/gxa/experiments/` + `evidences.rows[x].studyId` + `?geneQuery=` + `evidences.rows[x].target.id` (e.g. [E-GEOD-57945](http://www.ebi.ac.uk/gxa/experiments/E-GEOD-57945?geneQuery=ENSG00000133048))

**QC checks**

- TSLP (ENSG00000145777) and Adams-Oliver syndrome (Orphanet_974)
- PTGS2 (ENSG00000073756) and asthma (EFO_0000270)

**Comment by andrewhercules** [comment]
In some cases (e.g. PTGS2 and asthma), the value in the `evidence.rows[x].studyOverview` field contains HTML tags. Is it possible to render the string as HTML, using a [parsing library](https://medium.com/@uigalaxy7/how-to-render-html-in-react-7f3c73f5cafc)?

![Screenshot 2020-11-07 at 16 25 21](https://user-images.githubusercontent.com/7490258/98446517-dbc3bc80-2115-11eb-9e68-670c4cb3c714.png)

**Comment by d0choa** [comment]
@andrewhercules  looking at this example and the one above, we might need to think about whether to show studyOverview only on some sort of interaction. It does look like not very relevant information sometimes. We can think about this in the next iteration

**Comment by andrewhercules** [comment]
Agreed - I noticed with some of the entries, the `studyOverview` does not provide an explicit overview of the study, but more general details about the methodology. Happy to update for the next iteration.

**Comment by AsierGonzalez** [comment]
There must be an issue with how `studyOverview` is created in the new pipeline because the original evidence string do contain a meaningful description in `evidence.experiment_overview` for one of the examples above that I checked:
```
grep -m 1 "E-GEOD-57945" cttv010-2020-08-23.json | jq-1.6 '.evidence.experiment_overview'
"RNA-seq of 359 treatment-naive pediatric patients with Crohn's disease, patients with ulcerative colitis and control individuals"
```

I suspect that the value shown there (`"DESeq2 version: 1.10.1"`) comes from `evidence.resource_score.method.description`

**Comment by d0choa** [comment]
@AsierGonzalez point is correct. We made a bit of a mess with the `experimentOverview` field in expression atlas. I will work with Miguel to sort this out.

@andrewhercules I would expect the text is going to be a bit more relevant after the fix. I anticipate no changes will be needed in the FE from the above spec.

**Comment by d0choa** [comment]
Quick question for @andrewhercules. The study link points to study + gene. [example](https://www.ebi.ac.uk/gxa/experiments/E-GEOD-93624/Results?geneQuery=ENSG00000167207).

I wonder if it would be more useful to just link to the study? So that users can explore the study and understand the relative fold change of the gene of interest with respect to all other transcripts in the study [example](https://www.ebi.ac.uk/gxa/experiments/E-GEOD-93624/Results).

Feel free to ignore this suggestion

**Comment by andrewhercules** [comment]
With the new iteration of the GraphQL API, can we please make some adjustments to the Expression Atlas evidence data table?

Sample query: [CHI3L1 and inflammatory bowel disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000384%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000133048%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22expression_atlas%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20contrast%0A%20%20%20%20%20%20%20%20log2FoldChangeValue%0A%20%20%20%20%20%20%20%20log2FoldChangePercentileRank%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20studyOverview%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

- [ ] Remove the "Experiment overview" column

- [ ] In the "Experiment contrast" column, after displaying the text returned in the `evidences.rows[x].contrast` field, show a tooltip and on-hover, show the `evidences.rows[x].studyOverview` text

- [ ] In the "Experiment ID" column, change the link to the main study page, using the following construct - `http://www.ebi.ac.uk/gxa/experiments/` + `evidences.rows[x].studyId` (e.g. [E-GEOD-57945](https://www.ebi.ac.uk/gxa/experiments/E-GEOD-57945/Results))

**Comment by d0choa** [comment]
- [ ] Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
- [ ] Add show more rows functionality to table.
- [ ] Add empty stars as they do in [clinvar](https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/)
- [ ] Also add the tooltip on-hover for entires with no stars
- [ ] Remove score column
- [ ] Implement logic to load everything when entries < n (1000?) but disallow search and pagination when entries > 1000
- [ ] Format functional consequence label similarly than genetics portal. "Missense variant" instead of "missense_variant"
- [ ] Make sure numbers use the proper font formatting (as in genetics portal widget)

**Comment by d0choa** [comment]
- [ ] the first point from the previous list was wrong. `diseaseFromSource` comes as `null` for all expressionAtlas. Please just remove the tooltip. Sorry about this

**Comment by d0choa** [comment]
The previous comment does not apply anymore
