### ISSUE TITLE
Create new Europe PMC evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1248]
On the evidence page in the rewrite, can we please create a new data table that displays the Europe PMC evidence data?

**Example GraphQL API query**
[PTGS2 and asthma (with size:10 argument)](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000270%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000073756%22%5D%2C%20enableIndirect%3A%20true%2C%20size%3A10%2C%20datasourceIds%3A%20%5B%22europepmc%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20textMiningSentences%7B%0A%20%20%20%20%20%20%20%20%20%20tStart%0A%20%20%20%20%20%20%20%20%20%20tEnd%0A%20%20%20%20%20%20%20%20%20%20dStart%0A%20%20%20%20%20%20%20%20%20%20dEnd%0A%20%20%20%20%20%20%20%20%20%20section%0A%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Current implementation** 

The current production version of the Platform relies on a multi-step process to generate the data table:

1. Retrieve the PMIDs from our API /evidence endpoint 
2. Retrieve the publication details from Europe PMC's API /search endpoint using the PMIDs from step 1 ([example API call](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:31907365%20OR%20ext_id:31918268%20OR%20ext_id:30971730%20OR%20ext_id:30781615%20OR%20ext_id:31692590%20OR%20ext_id:31889962%20OR%20ext_id:29967100%20OR%20ext_id:29534696%20OR%20ext_id:29299941%20OR%20ext_id:29249187&format=json&resultType=core&pageSize=10)) 
3. Use the  `tStart`, `tEnd`, `dStart`, `dEnd`, `section`, and `text` to determine the placement of the blue (target) and yellow (disease) highlighting
4. Render the publication title, citation, PMID, abstract, year, and other sections (if relevant) 

![Screenshot 2020-11-07 at 16 44 01](https://user-images.githubusercontent.com/7490258/98446844-850bb200-2118-11eb-9fb9-bc5bf5ff6956.png)
[Current production view for PTGS2 and asthma](https://www.targetvalidation.org/evidence/ENSG00000073756/EFO_0000270?view=sec:literature)

**Data table**

My recommendation is that we simplify the text mining representation on the evidence page by only showing the abstract and highlighted text in either the title or abstract.

This is because:

1. We will soon have access to a new Europe PMC pipeline output, which will change the data structure and could remove the need to make a separate query to the Europe PMC /search API endpoint 
2. Sometimes the highlighting does not work and highlights the incorrect word or is not visible as the positions returned in the evidence string are incorrect
3. The text in the "other" sections can vary in length (see "Other: 2 matched sentences" for the "Associations between aspirin use and the risk of cancers: a meta-analysis of observational studies." entry on the [PTGS2 and asthma evidence page](https://www.targetvalidation.org/evidence/ENSG00000073756/EFO_0000270?view=sec:literature))

**Comment by d0choa** [comment]
To provide some context on what might be coming. @andrewhercules is true a few pieces of the data retrieval might change early next year. However, the relevant content for each evidence would not be too different:
- Title - highlighted when appropiate
- Publication metadata - author(s), journal, date, PMID, etc.
- Abstract - highlighted when appropriate
- Other sentences (highlighted) retrieved from the full text article.

**Comment by d0choa** [comment]
I would also revisit the React version of the widget that was implemented last year by @LucaFumis #672. I would anticipate that most of the work is already done.

**Comment by andrewhercules** [comment]
Makes sense - @javfg can you please revisit the previous version built by Luca in #672 and port to the alpha branch?

**Comment by javfg** [comment]
Just to be on the safe side, because I'm not sure I understood correctly what we discussed in the meeting: @mkarmona, when you said some matches might not be in the abstract, do you mean they are in the title? Or can they come from other parts of the article?

**Comment by d0choa** [comment]
What's shown in "Other" in the screenshot above are matches in which target and disease co-occur in the same sentence. The `section` field will tell you where they are in the paper and they might indeed belong to the body of the manuscript. Occasionally, the pipeline might not have access to the full text article. In these cases, all matches will be in the abstract or title.

**Comment by javfg** [comment]
> they might indeed belong to the body of the manuscript

This is what I needed to know. If it is only title/abstract, we could get rid of that 'matches' section altogether, and highlight the title and abstract only.

**Comment by andrewhercules** [comment]
Can we please make some adjustments to the Europe PMC evidence table?

**Table functionality**
- [ ] By default, only show 5 rows in the table 
- [ ] Implement the "Rows per page" feature to allow users to set number of rows visible in table

**Columns**
- [ ] Set a smaller max width on the "Publication" column to prevent layout/readability issues
![Screenshot 2020-11-17 at 14 12 39](https://user-images.githubusercontent.com/7490258/99400531-f8fb4680-28de-11eb-93e2-df56da0b06d0.png)

**Table content**
- [ ] Truncate list of authors as some entries have 50+ authors (e.g. [BRAF and cardiofaciocutaneous syndrome](https://alpha.targetvalidation.org/evidence/ENSG00000157764/Orphanet_1340)) - instead, show only the first author and "et al."

![Screenshot 2020-11-17 at 14 25 40](https://user-images.githubusercontent.com/7490258/99402124-e84bd000-28e0-11eb-9b9c-dade7dc6c7e8.png)

This can be achieved using the existing call to the Europe PMC API ([sample query](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:32323012%20OR%20ext_id:32703499%20OR%20ext_id:31707688%20OR%20ext_id:32521388%20OR%20ext_id:32692912%20OR%20ext_id:32802457%20OR%20ext_id:31598903%20OR%20ext_id:32650968%20OR%20ext_id:32802465%20OR%20ext_id:32269074&format=json&resultType=core&pageSize=10)). Instead of displaying `authorString`, please use the `authorList.authors` array to determine if the publication has more than 1 author. If yes, then use the `fullName` value and append "et al." (e.g. Bhaumik S et al.)

![Screenshot 2020-11-17 at 14 16 54](https://user-images.githubusercontent.com/7490258/99401530-33b1ae80-28e0-11eb-9081-231ef5584a11.png)

**Comment by andrewhercules** [comment]
Once the data is returned sorted by score in descending order - see #1264 - we can reimplement the little bar visualisation that shows the relative strength of the publication and text mining results.

**Comment by d0choa** [comment]
Regarding the above comment:

> Truncate list of authors as some entries have 50+ authors (e.g. BRAF and cardiofaciocutaneous syndrome) - instead, show only the first author and "et al."

To increase the information content, we can alternatively allow for a reasonable number of authors and finish with *et al.* or use "show more". Your call @andrewhercules

**Comment by javfg** [comment]
> * [x]  Truncate list of authors as some entries have 50+ authors (e.g. [BRAF and cardiofaciocutaneous syndrome](https://alpha.targetvalidation.org/evidence/ENSG00000157764/Orphanet_1340)) - instead, show only the first author and "et al."

As we discussed in the meeting yesterday, the component will show a given number of authors and a 'show more' button to expand the full list.

In the end, the number of authors shown initially is dynamic and adjusts to the width of the viewport. Let me know if this should change, but fixing it will break small viewports.
