### ISSUE TITLE
Prototyping new json schema

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1249]
As part of the consolidation of the evidence objects in the backend, we are re-modeling the [json schema](https://github.com/opentargets/json_schema) to reflect the new simplified/flattened design.

Based on the meeting we had on 2020.11.11 the following conclusions were reached:

* We need to maintain a json schema that guides our data providers and can be used as template to generate evidence strings.
* The schema will reflect the concepts of the new platform design, so the units of the schema is going to be data source centric instead of data type.
* Each of the valuable columns will be defined in a common section.
* For each data source there will only be a list of required fields.
* We haven't reached a consensus on how the unique association fields are defined, and at which point of the evidence generation. So for the first iteration of the json schema, the unique_association_fields will be omitted.

The schema is written based on the most recent iteration of the [evidence schema review](https://docs.google.com/spreadsheets/d/11jdPCo_vxY3jaP54xKTsXBshR5HMrpUf5oXJNgtbKm8/edit#gid=1735847104) document.

**Comment by ireneisdoomed** [comment]
As discussed on Nov 12th daily meeting we should keep an eye on:

- Fields present in the submitted evidence that were not taken into account in the cleaned up version.
- Check if the scoring depends on fields that are missing. 
- See which data sources provide PubMed Central IDs
- Maintain [a document](https://docs.google.com/document/d/1X3-T8fZcbYBUlvmMF1mpM9FvYeRXNxv8YPrTg7VfOPM/edit?usp=sharing) for those questions that arise and we want to ask the data providers

**Comment by DSuveges** [comment]
Structured fields:

* `literature`: list of pmids/pmc ids
```
|-- literature: array (nullable = true)
| |-- element: string (containsNull = true)
```

* `diseaseModelAssociatedModelPhenotypes`: list of objects:
```
|-- diseaseModelAssociatedModelPhenotypes: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- id: string (nullable = true)
| | |-- label: string (nullable = true)
```

* `diseaseModelAssociatedHumanPhenotypes`: list of objects:
```
|-- diseaseModelAssociatedHumanPhenotypes: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- id: string (nullable = true)
| | |-- label: string (nullable = true)
```

* `variations`: list of objects
```
|-- variations: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- functionalConsequenceId: string (nullable = true)
| | |-- inheritancePattern: string (nullable = true)
| | |-- numberMutatedSamples: long (nullable = true)
| | |-- numberSamplesTested: long (nullable = true)
| | |-- numberSamplesWithMutationType: long (nullable = true)
| | |-- variantAminoacidDescription: string (nullable = true)
```

* `textMiningSentences`: list of objects:

```
|-- textMiningSentences: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- dEnd: long (nullable = true)
| | |-- dStart: long (nullable = true)
| | |-- section: string (nullable = true)
| | |-- tEnd: long (nullable = true)
| | |-- tStart: long (nullable = true)
| | |-- text: string (nullable = true)
```

* `signigicantDriverMethod`: list of string:
```
|-- significantDriverMethods: array (nullable = true)
| |-- element: string (containsNull = true)
```

*  `clinicalUrls`: list of objects:
```
|-- clinicalUrls: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- niceName: string (nullable = true)
| | |-- url: string (nullable = true)
```

**Comment by DSuveges** [comment]
As for the first round, I close the issue. The updates are not yet merged to the master branch. 
Updates available: https://github.com/opentargets/json_schema/tree/ds_1249_new_json_schema
