### ISSUE TITLE
Evidence source can't be filtered in the evidence page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#125]
For the association below:

https://www.targetvalidation.org/evidence/ENSG00000108255/Orphanet_91492?view=sec:genetic_association

We have Gene2Phenotype used as evidence for the association listed in the table.
However I can't seem to be able to filter the table based on Gene2Phenotype (under Evidence source column).

<img width="73" alt="screen shot 2018-09-13 at 20 19 45" src="https://user-images.githubusercontent.com/6472381/45510544-73296100-b792-11e8-8cec-ccb22be80894.png">

Is this widespread?

**Comment by LucaFumis** [comment]
Just a minor thought: in the filter drop-down, do we want to show the full source text e.g. "Further details in the Genomics England PanelApp for panel 230 and gene CRYBA1" (i.e. as currently in production) or would it make sense to have just the source name e.g. "Genomics England PanelApp" ?

**Comment by ElaineMcA** [comment]
Pushed to production
