### ISSUE TITLE
Adjust Open Targets Genetics evidence table in rewrite version 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1250]
After reviewing the Open Targets Genetics evidence table, can we please make the following adjustments?

**Table search:**
- [x] Allow search for all text columns including ID columns

**Column names**
- [x] Rename "Literature" column to "Publication"
- [x] Rename "Study p-value" to "Association p-value"
- [x] Rename "Study Sample Size" to "Sample size"
- [x] Rename "Locus to Gene Score" to "L2G score"

**Tooltip**
- [x] Add tooltip on "L2G score" column label with the following text and link:

Text: Causal inference score - see [our documentation](https://docs.targetvalidation.org/data-sources/genetic-associations#open-targets-genetics-portal) for more information 
Link: https://docs.targetvalidation.org/data-sources/genetic-associations#open-targets-genetics-portal

**Table sorting**

- [x] By default, sort evidence using the Locus2Gene score in descending order (highest score first, and so on)

**Data table number formatting**
- [x] Ensure tabular, spaced numbers are used
- [x] Add comma for large integers (e.g. 336,526 vs 336526)
- [x] Please review the "Features" section on the Inter font website - https://rsms.me/inter/ - to ensure the data table component is using all available number formatting features

**Comment by javfg** [comment]
@andrewhercules we might want to bring that 'L2G Score' forward to the left of the table if it provides default sorting. It is the last one currently and will be have to be scrolled to in most displays sizes.

**Comment by andrewhercules** [comment]
Good point - for now, can we put the "L2G Score" column between "Literature" and "Variant ID"?

**Comment by d0choa** [comment]
Mmm I'm about hesitant about moving it. The point is that the L2G is a pretty much a conclusion of everything that is listed before.

For consistency with genetics portal: https://genetics.opentargets.org/gene/ENSG00000169174
I would probably keep it at the end.

But the scrolling point is also true...

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API now available, can we please make some small adjustments to the data table?

Sample query: [NOD2 and inflammatory bowel disease](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceTableData%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0003767%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000167207%22%5D%2C%20enableIndirect%3A%20true%2C%20datasourceIds%3A%20%5B%22ot_genetics_portal%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20publicationYear%0A%20%20%20%20%20%20%20%20publicationFirstAuthor%0A%20%20%20%20%20%20%20%20variantId%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%20%7B%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20pValueExponent%0A%20%20%20%20%20%20%20%20pValueMantissa%0A%20%20%20%20%20%20%20%20studySampleSize%0A%20%20%20%20%20%20%20%20oddsRatio%0A%20%20%20%20%20%20%20%20confidenceIntervalLower%0A%20%20%20%20%20%20%20%20confidenceIntervalUpper%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A&operationName=evidenceTableData)

- [ ] In the "Association p-value" column, please display the values found in `evidences.rows[x].pValueExponent` and `evidences.rows[x].pValueMantissa` using correct scientific notation - this is because the `resourceScore` field now contains the Locus2Gene score (see next point)

- [ ] In the "L2G score" column, please display the `evidences.rows[x].resourceScore` value - this is because the field `locus2GeneScore` has been deprecated in the latest API iteration
