### ISSUE TITLE
PheWAS front-end issues in QA

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1254]
After the pipeline run, we have identified several cases where the new data format causes the FE to crash. To keep track:

PheWAS: `unique_association_fields.variant_id ` now accepts two types of data: a `variant_id` consistent with the one for the Genetics Portal data (i.e. 3_169774313_C_T) or a `rsID`. 
1. `Genetic associations` crashes when loading variants with a rsID in the `unique_association_fields.variant_id ` field. [Example](https://qa.targetvalidation.org/evidence/ENSG00000184261/EFO_0003765).
2. When the `variant_id` field is as expected (3_169774313_C_T), we should update the link as it is currently linking to ensemble. Since we are having two types of data in that field, for most cases this would link to `Genetics Portal`  and for others to `ensembl`.

**Comment by d0choa** [comment]
A few considerations that might help defining the specs for the FE task:
- All entries in PheWAS catalog have an rsID but not all have a ref/alt allele id (3_169774313_C_T)
- All entries in PheWAS catalog mapped to ref/alt allele come from the genetics portal variant index.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and included in 20.11 release
