### ISSUE TITLE
Create links from Angular version evidence page to React version evidence page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1259]
To coincide with the beta release of the React rewrite version of the Platform that will include the new evidence pages, we should create a link from the Angular version of the evidence page to the React version of the evidence page.

When constructing the link, please use the same configuration logic so that custom installations of the Platform can turn off the link.

**Comment by LucaFumis** [comment]
PR ready - wait until beta is live before merging: https://github.com/opentargets/webapp/pull/320

**Comment by andrewhercules** [comment]
After the Beta release, but prior to release of 21.02 we need to update these links to http://beta.targetvalidation.org/

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into 3.21.0 release
