### ISSUE TITLE
Add STAG1 to teps-service.js

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1262]
A new TEP has been added for STAG1, could @LucaFumis or @andrewhercules please add the following to [teps-service.js](https://github.com/opentargets/webapp/blob/master/app/src/services/teps-service.js) as usual?

```
ENSG00000118007: {
                id: 'ENSG00000118007',
                symbol: 'STAG1',
                link: 'https://www.thesgc.org/tep/stag1'
}
```

**Comment by andrewhercules** [comment]
Ticket closed as work completed and included in 20.11 release
