### ISSUE TITLE
PanelApp front-end issues

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1263]
In the new evidence page of Panel App it is necessary to take into account that the term `Allelic requirement` can be significantly long. To give an approximation and address the issue, this field can contain up to 17 different strings. 

| Allelic requirement        | Count |
| ------------- |:-------------:|
| BIALLELIC, autosomal or pseudoautosomal      | 52427 |
| MONOALLELIC, autosomal or pseudoautosomal, imprinted status unknown      | 12687  |
| MONOALLELIC, autosomal or pseudoautosomal, NOT imprinted | 9108 |
| BOTH monoallelic and biallelic, autosomal or pseudoautosomal | 8019 |
| X-LINKED: hemizygous mutation in males, biallelic mutations in females | 2982 |
| X-LINKED: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males) | 2514 |
| BOTH monoallelic and biallelic (but BIALLELIC mutations cause a more SEVERE disease form), autosomal or pseudoautosomal | 1312 |
| MITOCHONDRIAL     | 1274 |
| Unknown     | 552 |
| MONOALLELIC, autosomal or pseudoautosomal, paternally imprinted (maternal allele expressed)     | 102 |
| MONOALLELIC, autosomal or pseudoautosomal, maternally imprinted (paternal allele expressed)     | 65 |
| Other - please specifiy in evaluation comments     | 18 |
| Other - please specify in evaluation comments     | 13 |
| MONOALLELIC, autosomal or pseudoautosomal      | 12 |
| Other     | 9 |
| X linked: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males)   | 6 |

The count here is approximative of the weight for every mode of inheritance present in the initial table. Exact numbers cannot be given now since the generation is currently being generated.

**Comment by d0choa** [comment]
Relevant for #1234

**Comment by AsierGonzalez** [comment]
Why are some of the values repeated? For example, `Other - please specify in evaluation comments` appears three times.

Anyway, all those values seem to be meaningful enough that the whole string should be kept.

**Comment by d0choa** [comment]
`specify` vs `specifiy`

**Comment by ireneisdoomed** [comment]
It's just a minor typo... `specifiy` and `specify`.

Presumably we won't get these in the evidences as they're very rare.

**Comment by AsierGonzalez** [comment]
And the two times that `Other - please specifiy in evaluation comments | 18` is an innocuous repetition?

**Comment by ireneisdoomed** [comment]
You're right. It was my mistake when creating the table, my bad. Already fixed.

**Comment by javfg** [comment]
I think we could show a short (1/2 words summary) which opens a tooltip on mouse over.

For that, it would be helpful to have a differentiated part in the string, e.g.: in the list above `X-LINKED: hemizygous mutation in males, biallelic mutations in females` I could separate by the colon and show `X-LINKED` in the  table and the rest in a tooltip. This requires all the strings to contain a colon.

Does that make sense?

**Comment by ireneisdoomed** [comment]
I also think that using the first word is the easiest and most systematic way to go, we cover all cases. What you mention, the tooltip, sounds great.

**Comment by AsierGonzalez** [comment]
The only case that wouldn't work with such rule is the last one, `X linked`

**Comment by ireneisdoomed** [comment]
I'm assuming these 6 are not going to be among the evidences. But yes, I'll update the numbers once I have them.

**Comment by d0choa** [comment]
We can go for the first-word heuristic temporarily. In the long term, we probably want to standardise this field across datasources:

```
>>> df.select(col("sourceId"), col("allelicRequirement")).filter(col("allelicRequirement").isNotNull()).distinct().show(20, False)
+--------------+-----------------------+
|sourceId      |allelicRequirement     |
+--------------+-----------------------+
|gene2phenotype|mitochondrial          |
|gene2phenotype|biallelic              |
|gene2phenotype|x-linked dominant      |
|gene2phenotype|imprinted              |
|clingen       |X-Linked               |
|clingen       |X-linked recessive     |
|clingen       |Semidominant           |
|gene2phenotype|x-linked over-dominance|
|gene2phenotype|hemizygous             |
|gene2phenotype|monoallelic,digenic    |
|gene2phenotype|digenic                |
|clingen       |Other                  |
|gene2phenotype|                       |
|clingen       |Autosomal Recessive    |
|gene2phenotype|biallelic,monoallelic  |
|gene2phenotype|uncertain              |
|gene2phenotype|biallelic,digenic      |
|gene2phenotype|mosaic                 |
|gene2phenotype|monoallelic            |
|clingen       |Autosomal Dominant     |
+--------------+-----------------------+
```

**Comment by ireneisdoomed** [comment]
These are the final numbers with the different `allelic requirement`s present in the Panel App evidence:

| Allelic requirement        | Count |
| ------------- |:-------------:|
| BIALLELIC, autosomal or pseudoautosomal      | 11138 |
| MONOALLELIC, autosomal or pseudoautosomal, imprinted status unknown      | 3944  |
| MONOALLELIC, autosomal or pseudoautosomal, NOT imprinted | 2228 |
| BOTH monoallelic and biallelic, autosomal or pseudoautosomal | 2156 |
| X-LINKED: hemizygous mutation in males, biallelic mutations in females | 646 |
| X-LINKED: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males) | 576 |
| BOTH monoallelic and biallelic (but BIALLELIC mutations cause a more SEVERE disease form), autosomal or pseudoautosomal | 248 |
| MITOCHONDRIAL     | 170 |
| Null values     | 43 |
| Unknown     | 36 |
| MONOALLELIC, autosomal or pseudoautosomal, paternally imprinted (maternal allele expressed)     | 39 |
| MONOALLELIC, autosomal or pseudoautosomal, maternally imprinted (paternal allele expressed)     | 18 |
| Other - please specifiy in evaluation comments     | 3 |
| Other - please specify in evaluation comments     | 2 |
| MONOALLELIC, autosomal or pseudoautosomal      | 2 |
| X linked: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males)   | 2 |
| Other     | 1 |

Please note that we are unfortunately capturing two `X linked` cases.

**Comment by ireneisdoomed** [comment]
Update: there are no `null values ` present under the `allelic_requirement` field anymore.
Instead, this field will not be present in the evidence string for such cases.
