### ISSUE TITLE
GraphQL API to return text mining literature evidence sorted by score 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1264]
Can we please amend the GraphQL API so that it returns text mining literature evidence sorted by score (descending)?

For example, in this [query for PTGS2 and asthma](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000270%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000073756%22%5D%2C%20enableIndirect%3A%20true%2C%20size%3A10%2C%20datasourceIds%3A%20%5B%22europepmc%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20textMiningSentences%7B%0A%20%20%20%20%20%20%20%20%20%20tStart%0A%20%20%20%20%20%20%20%20%20%20tEnd%0A%20%20%20%20%20%20%20%20%20%20dStart%0A%20%20%20%20%20%20%20%20%20%20dEnd%0A%20%20%20%20%20%20%20%20%20%20section%0A%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs), the first five rows have the following scores - 2, 5.2, 5.4, 15.6, 6. Ideally, the row with the top score should be returned first followed by rows with scores in descending order.

**Comment by d0choa** [comment]
I believe this posed some issues the first time we proposed it but I can't remember what the issue was. If it helps, sorting by `score` can be applied to all evidence, not just literature.

Also to clarify, we don't need a server-side sorting functionality. Just the data to come out sorted.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged as part of https://github.com/opentargets/platform-api-beta/pull/48
