### ISSUE TITLE
API target interaction endpoint: interactorA and interactorB resolve to same entity

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/platform#1265]
The issue can be seen in the beta API and in the molecular interactions preview:
the symbol in interactorB column (i.e. the first column) is always the same as the interactorA symbol.

This query shows the issue:
 - most fields are commented out for clarity
 - this happens for all database sources
https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20interactions%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000091831%22)%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20approvedName%0A%20%20%20%20%0A%20%20%20%20interactions(%0A%20%20%20%20%20%20%20%20sourceDatabase%3A%20%22intact%22%0A%20%20%20%20%20%20%20%20page%3A%20%7B%20index%3A%200%2C%20size%3A%201000%20%7D%0A%20%20%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20intA%0A%20%20%20%20%20%20%20%20%20%20%23%20intABiologicalRole%0A%20%20%20%20%20%20%20%20%20%20targetA%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20speciesA%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20mnemonic%0A%20%20%20%20%20%20%20%20%20%20%23%20%7D%0A%20%20%20%20%20%20%20%20%20%20intB%0A%20%20%20%20%20%20%20%20%20%20%23%20intBBiologicalRole%0A%20%20%20%20%20%20%20%20%20%20targetB%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20speciesB%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20mnemonic%0A%20%20%20%20%20%20%20%20%20%20%23%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20scoring%0A%20%20%20%20%20%20%20%20%20%20%23%20count%0A%20%20%20%20%20%20%20%20%20%20%23%20sourceDatabase%0A%20%20%20%20%20%20%20%20%20%20%23%20evidences%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20evidenceScore%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20hostOrganismScientificName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20interactionDetectionMethodMiIdentifier%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20interactionDetectionMethodShortName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20interactionIdentifier%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20interactionTypeShortName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20participantDetectionMethodA%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20%20%20miIdentifier%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20%20%20shortName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20participantDetectionMethodB%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20%20%20miIdentifier%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20%20%20shortName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20interactionDetectionMethodShortName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20expansionMethodShortName%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20pubmedId%0A%20%20%20%20%20%20%20%20%20%20%23%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=interactions

**Comment by mkarmona** [comment]
Fix pushed. I will come with the new minor update with evidences too.
