### ISSUE TITLE
Genomics England parser refactoring and rewrite

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1269]
As part of the process of rewrite of the platform and, more specifically, remodelling of the evidence, [GenomicsEnglandPanelApp.py](https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/GenomicsEnglandPanelApp.py) must be rewritten following the new version of the JSON schema.

**Comment by ireneisdoomed** [comment]
To-dos based on the [review of the fields coming from the data sources](https://docs.google.com/document/d/164qkIj4UfAB7BpwLCoHUjj5TE9a6dtNSwhSzqHGoKHs/edit?usp=sharing):

- [ ] Add a `functionalConsequenceId` field. Action needed: manual mapping from the Mode of Inheritance column to a SO code (different values described [here](https://github.com/opentargets/platform/issues/1263)). 2 options:
1. Store these mappings in a Config file;
2. Have the logic within the parser

- [ ] Should we populate the `diseaseFromSourceId` field with the OMIM codes that are sometimes present or leave it blank?

**Comment by d0choa** [comment]
@ireneisdoomed let me clarify a point in the comment above. The field that would go into `functionalConsequenceId` after SO term mapping would be the `Mode of pathogenicity` not the `Mode of inheritance`. The linked ticket does therefore not add too much info into this task.

As you can see this information is not very frequent (~1%) so it's really not high priority 

```
❯ sed '1d' All_genes_20200928-1959.tsv | cut -f 9 | sort | uniq -c
58162
  60
   1 FALSE
 570 Loss-of-function variants (as defined in pop up message) DO NOT cause this phenotype - please provide details in the comments
  31 Loss-of-function variants (as defined in pop up message) DO NOT cause this phenotype -please provide details in the comments
 163 Other
1611 Other - please provide details in the comments
 165 Other - please provide details in the comments
   1 gain-of-function
   4 loss-of-function (truncating variants and curated list of variants)
   4 other - please provide details in the comments
```

**Comment by ireneisdoomed** [comment]
The first iteration of the script is done. Plans for the second iteration:
- [ ] Review the integration of multiprocessing when making requests to OnToma. I have not seen any improvement in performance over the previous parser. 
- [ ] Revamp the function that removes duplicates.
- [ ] Integrate a better logging system as agreed (see [here](https://docs.google.com/document/d/1-3XzwT6-udzsCyrrh20Hf-FU9qiTFt9vS08ssxMKETk/edit))
- [ ] Map `Mode of pathogenicity` to an SO code to populate  `functionalConsequenceId`
- [ ] Minor fixes commented in the code

**Comment by ktsirigos** [comment]
work is completed.
