### ISSUE TITLE
Updating PheWAS data source parser to accommodate the new JSON schema 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1280]

**Comment by ireneisdoomed** [comment]
To-dos based on the [review of the fields](https://docs.google.com/document/d/164qkIj4UfAB7BpwLCoHUjj5TE9a6dtNSwhSzqHGoKHs/edit?usp=sharing) coming from the data sources:

- [ ] Populate `diseaseFromSourceId` with `phewas_code` column
- [ ] Remove `phewas_code` from `diseaseFromSource`: populate only with `phewas_string`
- [ ] BE will need to include `diseaseFromSourceId` as a UAF in the [config file](https://github.com/opentargets/platform-etl-backend/blob/cbc31e167edf5f8a889628aa01ea87b6abbb8230/src/main/resources/reference.conf).

**Comment by ireneisdoomed** [comment]
The first iteration of the script is done. Plans for the second iteration:
- [ ] Integrate a better logging system as agreed (see [here](https://docs.google.com/document/d/1-3XzwT6-udzsCyrrh20Hf-FU9qiTFt9vS08ssxMKETk/edit))
- [ ] Fetch data from Genetics Portal on the fly, not by reading `phewas_w_consequences.csv`. The major complication here comes from reading data from the bucket directly.
- [ ] Minor fix commented in the code
