### ISSUE TITLE
Updating SLAPenrich data source parser to accommodate the new JSON schema 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1282]

**Comment by ireneisdoomed** [comment]
To-dos based on the [review of the fields](https://docs.google.com/document/d/164qkIj4UfAB7BpwLCoHUjj5TE9a6dtNSwhSzqHGoKHs/edit?usp=sharing) coming from the data sources:
- [ ] `targetFromSourceId` should contain original id -> Gene Symbol
