### ISSUE TITLE
Updating PROGENy data source parser to accommodate the new JSON schema

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1283]

**Comment by ireneisdoomed** [comment]
Issue #713 will be taken into account when rewriting the parser.

Additional to-dos based on the [review of the fields](https://docs.google.com/document/d/164qkIj4UfAB7BpwLCoHUjj5TE9a6dtNSwhSzqHGoKHs/edit?usp=sharing) coming from the data sources:
- [ ] `targetFromSourceId` should contain original id -> Gene Symbol
