### ISSUE TITLE
Reviewing pattern field in the new JSON schema

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1285]

**Comment by d0choa** [comment]
Some suggestions...

- [ ] `clinicalSignificances` as enum

```python
>>> df.select(explode("clinicalSignificances")).distinct().show(20, truncate = False)
+--------------------------------------------+
|col                                         |
+--------------------------------------------+
|uncertain significance                      |
|pathogenic                                  |
|likely benign                               |
|association not found                       |
|other                                       |
|benign                                      |
|association                                 |
|risk factor                                 |
|likely pathogenic                           |
|not provided                                |
|affects                                     |
|protective                                  |
|drug response                               |
|conflicting interpretations of pathogenicity|
+--------------------------------------------+

```
[Documentation](https://www.ncbi.nlm.nih.gov/clinvar/docs/clinsig/)

- [ ] `clinicalUrls.niceName` remove "Information" from strings. We are doing it in the FE at the moment:

   ```scheme
               "enum": [
                 "Clinical Trials Information",
                 "DailyMed Information",
                 "FDA Information",
                 "ATC Information"
               ]
   
   ```

- [ ] `confidence` enum is currently the result of multiple resources in a not very controlled vocabulary. Likely to fail at some point. Do we want to keep it as enum?

- [ ] In `diseaseId` build pattern based on id?

```python
>>> df.select("diseaseId").withColumn("diseaseId", split("diseaseId", "_").getItem(0)).distinct().show(20, truncate = False)
+---------+
|diseaseId|
+---------+
|NCIT     |
|Orphanet |
|GO       |
|HP       |
|EFO      |
|MONDO    |
|DOID     |
|MP       |
+---------+
```

- [ ] Use CHEMBL pattern as in `drugId` 

- [ ] For `literature` only `europepmc` uses PMC identifiers. We should make them use PMIDs and streamline the process. It shouldn't be a problem as we are rewriting that pipeline. I asked Santosh and he said it's not a problem. The action here would be to remove `PMC` from the pattern

   ```python
   >>> df.select(explode("literature").alias("literature"), "datasourceId").filter(col("literature").contains("PMC")).select("datasourceId").distinct().show()
   +------------+
   |datasourceId|
   +------------+
   |   europepmc|
   +------------+
   
   ```

- [ ] `log2FoldChangePercentileRank` is an integer in the ETL schema

- [ ] All `pathwayId` start with the pattern `R-HSA-`

   ```python
   >>> df.select("pathwayId").withColumn("pathwayId", split("pathwayId", "-")).withColumn('FIRST', col("pathwayId").getItem(0)).withColumn('SECOND', col("pathwayId").getItem(1)).select("FIRST", "SECOND").distinct().show(20, truncate = False)
   +-----+------+
   |FIRST|SECOND|
   +-----+------+
   |null |null  |
   |R    |HSA   |
   +-----+------+
   ```

- [ ] All `reactionId` start with the pattern `R-HSA-`

   ```Python
   >>> df.select("reactionId").withColumn("reactionId", split("reactionId", "-")).withColumn('FIRST', col("reactionId").getItem(0)).withColumn('SECOND', col("reactionId").getItem(1)).select("FIRST", "SECOND").distinct().show(20, truncate = False)
   +-----+------+
   |FIRST|SECOND|
   +-----+------+
   |null |null  |
   |R    |HSA   |
   +-----+------+
   ```

- [ ] `PathwayName` is missing the description. "Pathway or gene set name" 

- [ ] Provide example of `publicationFirstAuthor` 

    ```Python
    >>> df.filter(col("publicationFirstAuthor").isNotNull()).select("publicationFirstAuthor").show(5)
    +----------------------+
    |publicationFirstAuthor|
    +----------------------+
    |              Davies G|
    |               Kanai M|
    |             Pirastu N|
    |              Astle WJ|
    |             Kichaev G|
    +----------------------+
    only showing top 5 rows
    ```

- [ ] Add pattern for `publicationYear`. 

```python
>>> df.filter(col("publicationYear").isNotNull()).select("publicationYear").show(5)
+---------------+
|publicationYear|
+---------------+
|           2018|
|           2018|
|           2017|
|           2016|
|           2018|
+---------------+
only showing top 5 rows

```

- [ ] Add enum to `significantDriverMethods`

    ```python
    >>> df.select(explode(col("significantDrivermethods"))).distinct().show()
    +---------------+
    |            col|
    +---------------+
    |oncodriveclustl|
    |    combination|
    |      smregions|
    |     mutpanning|
    |          cbase|
    |        hotmaps|
    |         dndscv|
    |   oncodrivefml|
    +---------------+
    
    ```

- [ ] `targetFromSourceId` provide some examples to show the type of ids that can be included: `ENSG`, `gene symbol`, `uniprot`

- [ ] We can include `ENSMUSG` pattern in `targetInModel` as we only use mouse genes at the moment

    ```python
    >>> df.select("targetInModel").withColumn("targetInModel", split("targetInModel", "0").getItem(0)).distinct().show(20, truncate = False)
    +-------------+
    |targetInModel|
    +-------------+
    |ENSMUSG      |
    |null         |
    +-------------+
    ```

- [ ] `textMining.section` are currently a very short list of options. Probably an enum makes sense here:

    ```Python
    >>> df.select(explode(col("textMiningSentences.section"))).distinct().show(20)
    +--------+
    |     col|
    +--------+
    |   title|
    |   table|
    |   other|
    |  figure|
    |appendix|
    |abstract|
    +--------+
    
    ```

**Comment by ireneisdoomed** [comment]
Updated patterns listed:

| Field Name                            | Pattern                                                                                                  |
| ------------------------------------- | -------------------------------------------------------------------------------------------------------- |
| diseaseModelAssociatedHumanPhenotypes.id | ^HP:\\d+$                                                                                                |
| diseaseModelAssociatedModelPhenotypes.id | ^MP:\\d+$                                                                                                |
| drugId                                | ^(CHEMBL)\\d+$                                                                                           |
| literature                            | \\d+$                                                                                                    |
| pathwayId                             | ^(R-HSA-)\\d+$                                                                                           |
| reactionId                            | ^(R-HSA-)\\d+$                                                                                           |
| publicationYear                       | \\d{4}$                                                                                                  |
| targetInModel                         | ^(ENSMUSG)\\d+$                                                                                          |

And `diseaseId` with the pattern `(^NCIT_C\d+$|^Orphanet_\d+$|^GO_\d+$|^HP_\d+$|^EFO_\d+$|^MONDO_\d+$|^DOID_\d+$|^MP_\d+$)` (does not fit within the table).

All changes described above have been implemented and [merged](https://github.com/opentargets/json_schema/blob/ds_1249_new_json_schema/opentargets.json).

**Comment by d0choa** [comment]
Thanks @ireneisdoomed
