### ISSUE TITLE
Data mismatch when downloading CSV/TSV/JSON files on association pages

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1292]
A user contacted the support desk, noting that the CSV/TSV/JSON files available for download on the target association page return data that is significantly different than what is displayed in the UI.

For example, the CSV/TSV/JSON files for [diseases/phenotypes associated with ESR1](https://alpha.targetvalidation.org/target/ENSG00000091831/associations) have different diseases/phenotypes and different association scores:

**UI:**
![Screenshot 2020-12-15 at 20 42 51](https://user-images.githubusercontent.com/7490258/102270817-5c948600-3f16-11eb-85c0-b07f253e61d7.png)

**CSV**
![Screenshot 2020-12-15 at 20 44 32](https://user-images.githubusercontent.com/7490258/102270812-5b635900-3f16-11eb-8ca5-a1717de71111.png)

Can we please investigate the issue and fix the downloads?

Please note this issue does **not** appear to impact the files available for download on the targets associated with a disease/phenotype page (e.g. [childhood onset asthma](https://alpha.targetvalidation.org/disease/EFO_0004591/associations))

**Comment by d0choa** [comment]
I think I got this one.
The table query has the `BFilter` option with an empty string, whereas the heatmap does not include the `BFilter` parameter by default in the query. Not sure this was an intended functionality. The 2 queries produce different number of results:
- [Including BFilter](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20target(ensemblId%3A%20%22ENSG00000091831%22)%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20associatedDiseases(aggregationFilters%3A%20%5B%5D%2C%20BFilter%3A%20%22%22)%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=assocs) (1644)
- [Without BFilter](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20target(ensemblId%3A%20%22ENSG00000091831%22)%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20associatedDiseases(aggregationFilters%3A%20%5B%5D)%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=assocs) (1713)

I guess the solution would be not to include the `BFilter` in the query when it's an empty string.

**Comment by mirandaio** [comment]
@andrewhercules @d0choa fixed.
