### ISSUE TITLE
Adverse events coming with incorrect adverse event name

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1295]
When querying the adverse events ([Example query](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=%20%20query%20DrugPageQuery%20%7B%0A%20%20%20%20drug(chemblId%3A%20%22CHEMBL2010601%22)%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20hasBeenWithdrawn%0A%20%20%20%20%20%20adverseEvents%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20%20%20logLR%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20&operationName=DrugPageQuery)) it's returning the ChEMBL id instead of the adverse event name.

```
{
  "data": {
    "drug": {
      "name": "IVACAFTOR",
      "adverseEvents": {
        "count": 21,
        "rows": [
          {
            "name": "CHEMBL2010601",
            "count": 1049,
            "logLR": 5609.070079043566
          },
          {
            "name": "CHEMBL2010601",
            "count": 538,
            "logLR": 910.0041520055092
          },
          {
            "name": "CHEMBL2010601",
            "count": 182,
            "logLR": 747.1587249473887
          },

```

**Comment by JarrodBaker** [comment]
@d0choa I've fixed this. I have also taken the chance to include the meddra codes into the GraphQL interface so that the name of the reaction can be more specfiically mapped. 

It will appear when we next redeploy.

**Comment by d0choa** [comment]
Great! I'll spec a FE ticket to display the new info once it's deployed
