### ISSUE TITLE
Querying some drug indications in the API produces "Internal server error"

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1296]
The next [query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=%0Aquery%20indicationCount%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL112%22)%7B%0A%20%20%20%20name%0A%20%20%20%20indications%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Aquery%20indications%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL112%22)%7B%0A%20%20%20%20name%0A%20%20%20%20indications%7B%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=indications) fails attempting to get the indications for Acetaminophen. It produces an "Internal server error".
It does work when getting the count of indications.

```
query indications{
  drug(chemblId: "CHEMBL112"){
    name
    indications{
      rows{
        disease {
          id
        }
      }
    }
  }
}
```

**Comment by cmalangone** [comment]
This specific query requires "EFO_0000405". This EFO term is not present in the disease index.
Disease index contains a subset of the complete EFO ontology. Obsolete terms are not included in disease index too.

**Comment by d0choa** [comment]
I'm having a hard time trying to understand how the data looks like in the new index and if there are any new fields available that might help labelling the absent terms.

I think we can go for short-term and long-term solutions here:
- Short term: Only return disease ids that are resolvable on our index. This will work automatically.
- Long term: Return resolvable entities in disease.id and have another field in the API containing the relevant strings (id, label, etc). This is similar to what we have done in other implementations (e.g. interactions) when a subset of the ids are not resolvable

**Comment by JarrodBaker** [comment]
The simplest approach that I can see is to check which EFO IDs are not returned from Elasticsearch, and just tell the user that there was an error with those results, but return the rest of the result set. 

How does this look @d0choa :

![image.png](https://images.zenhubusercontent.com/5ec7caaa0e8174edc9bdf7a6/5ae1370c-c2ac-486d-800e-a2480e164a46)

All of the fields are null/empty except for the EFO ID.

**Comment by d0choa** [comment]
what we have done in the past with this type of issues is to have 2 fields. The `id` would have the resolvable entities or `null` and a second field (e.g. `diseaseTerm`) would have all the ids as a String.

This way, the FE could optionally show one or another.

This example on interactions might help you understand what I mean: [Example](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20adverseEvent%7B%0A%20%20target(ensemblId%3A%20%22ENSG00000130234%22)%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20interactions%7B%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20intB%0A%20%20%20%20%20%20%20%20targetB%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

Does it make sense?

**Comment by mkarmona** [comment]
This should not happen right ? Entities should be resolved. The problem comes when raw id wasn't properly updated to the right efo.

**Comment by mkarmona** [comment]
This is one of the reasons of including obsoleted terms that have been forwarded to a new one. Drug index , one of the steps has to be resolving the right IDs . I don't like the idea of being optionally resolving even our own data cooked at home .

**Comment by mkarmona** [comment]
@d0choa interactions is not the best matched example to this case. That case is there because non human OT subset matches.

**Comment by d0choa** [comment]
I agree. We are trying to make the most of what we have and this should not be the strategy.
Let's go for the short term solution suggested above: only return resolved entities.

The long term solution should be about getting the mappings right by rescuing obsoleted terms and improving the mappings when possible. We will do that for evidence, so we should include indications in the equation.

**Comment by JarrodBaker** [comment]
This has been done. I have updated Elasticsearch with the new data, and restarted the API (necessary because GraphQL caches queries so it kept returning the error even after the problem was fixed) and made a PR. 

294 indications are no longer included. 9 EFO mappings were included in the ChEMBL data but were not in the disease index:

- HP_0000833
- EFO_0000408
- EFO_0000378
- EFO_0003845
- EFO_0003910
- EFO_0000405
- EFO_0000430
- EFO_0001669
- EFO_1001001
- EFO_0000408

**Comment by d0choa** [comment]
The above query is fixed, so I consider this closed

**Comment by mkarmona** [comment]
@JarrodBaker if I remember that right there is a way to clear the cache although it needs to be exposed to a restricted network through rest API by example. This is not for now of course just to jot it down

**Comment by d0choa** [comment]
For completion, the reasons why the above terms are not in our index:

| id          | Label                                                        | Reason      |
| ----------- | ------------------------------------------------------------ | ----------- |
| HP_0000833  | [obsolete Glucose intolerance](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0000833) | Obsolete    |
| EFO_0000408 | [obsolete_disease state](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000411) | Obsolete    |
| EFO_0000378 | [obsolete_coronary artery disease](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000378) | Obsolete    |
| EFO_0003845 | [obsolete_kidney stone](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003845) | Obsolete    |
| EFO_0003910 | [obsolete_von Willebrand disease](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003910) | Obsolete    |
| EFO_0000405 | [digestive system disease](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000405) | Not in slim |
| EFO_0000430 | [obsolete_ductal adenocarcinoma](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000430) | Obsolete    |
| EFO_0001669 | [obsolete_influenza infection](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001669) | Obsolete    |
| EFO_1001001 | [obsolete_keratoconjunctivitis sicca](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1001001) | Obsolete    |
| EFO_0000408 | [obsolete_disease state](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000411) | Obsolete    |

**Comment by mkarmona** [comment]
@d0choa how much we could save just having a decent obsolete terms rescue system!
