### ISSUE TITLE
Problem with known drugs / clinical precedence in beta API

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1298]
An example of the query currently working in alpha for disease page: [Example](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=query%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_586%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20knownDrugs(size%3A%2010)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20phase%0A%20%20%20%20%20%20%20%20%20%20status%0A%20%20%20%20%20%20%20%20%20%20urls%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20activity%0A%20%20%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedName%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)

An example of how the query does not work in the recently deployed API [Example](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_586%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20knownDrugs(size%3A%2010)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20phase%0A%20%20%20%20%20%20%20%20%20%20status%0A%20%20%20%20%20%20%20%20%20%20urls%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20activity%0A%20%20%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedName%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D).

There could be more than one issue:
- It complains about the `activity` field
- After removing the `activity` field it does not complain but it returns a `null`

**Comment by d0choa** [comment]
For BE purposes, you can remove the `activity` field from the API, if that's not the case already. We will navigate the problem in the FE and perhaps future work in drug index. We will address this in separate tickets.

You can focus on the second part of the problem, why it comes as `null` once the `activity` field is removed: [Example](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_586%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20knownDrugs(size%3A%2010)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20phase%0A%20%20%20%20%20%20%20%20%20%20status%0A%20%20%20%20%20%20%20%20%20%20urls%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedName%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)

**Comment by cmalangone** [comment]
The PR fixed the issue with Phase that is Long .
The current issue is about the definition of Reference
The code
```     (__ \ "references").readWithDefault[Seq[Map[String, String]]](Seq.empty).map(
        s => s.flatMap(m => ctPattern findAllIn m("urls"))
      ) and```
is wrong.

The reference is [Seq[Map[String, **Seq[String]**]]

So the query breaks due the wrong mapping.

**Comment by d0choa** [comment]
The issue does no longer apply
