### ISSUE TITLE
Uniprot and Uniprot Somatic "incorrectly" rescued by beta API

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1299]
While production has removed `uniprot` and `uniprot somatic`, the new ETL has rescued them.
The main reason for this is that the new ETL ingests whatever is in the files, but the uniprot file contains 3 datasources in the same file: `uniprot`, `uniprot_somatic` and `uniprot_literature`. This is not currently affecting FE, but it's displaying some data that we 

I'm inclined to propose the solution that @mkarmona  implemented in the past. Subset the input file to only include `uniprot_literature` before ingesting it into the pipeline.

Long term, we will create the file with the right content, but we are still exploring the data to diagnose the value of it.

**Comment by d0choa** [comment]
@AsierGonzalez provided the filtered file and the pipeline will pick the appropriate file in upcoming runs

**Comment by cmalangone** [comment]
After re run the ETL with the proper evidences a new output was generated

```gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded```

**Comment by d0choa** [comment]
This looks perfect @cmalangone :

```
❯ gsutil ls gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/_SUCCESS
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=cancer_gene_census/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=chembl/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=clingen/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=crispr/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=europepmc/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=eva/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=eva_somatic/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=expression_atlas/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=gene2phenotype/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=genomics_england/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=intogen/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=ot_genetics_portal/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=phenodigm/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=phewas_catalog/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=progeny/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=reactome/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=slapenrich/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=sysbio/
gs://ot-snapshots/etl/outputs/20.11/evidences/succeeded/sourceId=uniprot_literature/
```

**Comment by cmalangone** [comment]
I reload the index: uniprot_literature. The other two indices (uniprot and uniprot_somatic) are removed.
config.conf updated.
