### ISSUE TITLE
Set up Google bucket system for annotation data files & internal data generation

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#130]
**Target Annotation**
The number of file with target annotation data is growing. We currently have the following files:
- cgi_biomarkers_per_variant.tsv
- chemicalprobes_portalprobes.tsv
- chemicalprobes_probeminer.tsv
- v85_hallmark_export.tsv
- tractability_buckets.tsv
- (TEPs to follow)

**Internal Evidence Generation**
The number of internal evidence files is also growing. We currently have the following files:
- PheWAS
- gene2phenotype
- IntOgen
- Genomics England
- PROGENy
- SLAPEnrich
- PhenoDigm

It would be good to be able to track versions for target annotation and internal evidence files like we do for the evidence from data providers because most of these files are also updated, but irregularly. 

**Steps to be taken are:**
- [x] Define Google bucket names
- [x] Set up Google bucket for Target Annotation files
- [x] Set up Google bucket for Internal Evidence JSON files
@MichaelaEBI 
- [x] Define where input file for internal evidence generation should be stored
- [x] Define where cancerbiomarker annotation file should live
@cmalangone 
- [x] Script to retrieve, rename and move all evidence files from data providers
- [x] Script to retrieve all internally generated evidence files
- [x] Script to retrieve all annotation files
- [x] Retrieve number of lines in each evidence file and output into a tsv file with filename & nr. of lines

**Comment by MichaelaEBI** [comment]
**Google bucket names**
otar000-evidence_input already exists and might be used already. At the moment possible places for files are the google bucker otar000-evidence_input, github (tissue curation and translation maps) and HOME_DIR. Suggested google buckets are:
- Internal Evidence: otar000-evidence_input/18.10/input
- Internal Evidence: otar000-evidence_input/18.10/output
- Annotation Files: otar000-annotation_input/18.10

**Comment by afaulconbridge** [comment]
After discussion we've refined the naming schema to:

* otar000-internal_input
    * evidence
        * [release]
            * input
            * output
    * association
        * [release]

**Comment by afaulconbridge** [comment]
This issue is also related to platform#115

**Comment by afaulconbridge** [comment]
Because renaming a bucket is not possible - it has to be created / copied / deleted - and the bucket name is reflected in the public URL, we've decided to pause this for further thought before implementing a decision.

**Comment by MichaelaEBI** [comment]
**Status update:**
- For internal evidence generation we will use the otar000-evidence-input bucket. There will be a separate folder for each OT Release just like in ot-release (so 18.10 is the current one) and within each release folder there will be an input and an output folder - input for the files we use to generate JSON files (output). The files in output will then be moved into the corresponding ot-release bucket.
- Annotation files as listed above will live in the ot-release bucket. The annotation files for 18.10 will live here: Buckets/ot-releases/18.10/ot-annotation-files

@gkos-bio please confirm that this works for PhenoDigm data. You could create a phenodigm folder in Buckets/otar000-evidence_input/18.10 if you have several input files.

**Comment by afaulconbridge** [comment]
Most of the ontology related files have fixed versions at source we can use (e.g. on GitHub, Sourceforge). the one exception is MP (mammalian phenotype ontology) http://www.informatics.jax.org/downloads/reports/mp.owl 
We need a location that we can put specific versions in that we can refer to for consistency.

**Comment by ElaineMcA** [comment]
Coordinate all scripts to create all internal files to put in this bucket.

**Comment by afaulconbridge** [comment]
@cmalangone tocCoordinate all scripts to create all internal files to put in this bucket.

**Comment by MichaelaEBI** [comment]
All completed in https://github.com/opentargets/platform-input-support repository.
