### ISSUE TITLE
Stop using "activity" endpoint in known drugs / clinical precedence widgets

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1300]
Follow up from #1298 

For the next 3 widgets and their summaries:
- Known drugs in target profile page
- Known drugs in disease profile page
- Clinical precedence in drug profile page

Can we stop querying the `activity` endpoint. Instead, display on the same column the content of the `drug.mechanismsOfAction.uniqueActionTypes` as in the next [example query](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=query%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_586%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20knownDrugs(size%3A%2010)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20phase%0A%20%20%20%20%20%20%20%20%20%20status%0A%20%20%20%20%20%20%20%20%20%20urls%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20mechanismsOfAction%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20uniqueActionTypes%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedName%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)

**Comment by d0choa** [comment]
When looking at this problem, please have a look #1143, as we can probably have both fixed at the same time

**Comment by d0choa** [comment]
For clarification, you can rename the column to `Action Type`

**Comment by mirandaio** [comment]
Done in this PR https://github.com/opentargets/platform-app/pull/268 in the beta branch
