### ISSUE TITLE
OnToma: Synchronise supported ontology prefixes with the JSON schema

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1307]
Currently, searching for `hypersensitivity` with OnToma fails because it maps to [GO_0002524 - "hypersensitivity"](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0002524), and GO terms are not supported:

```
>>> t.find_term("hypersensitivity")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 470, in find_term
    found = self._find_term_from_string(query, suggest)
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 514, in _find_term_from_string
    efolup = self.efo_lookup(query)
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 365, in efo_lookup
    return make_uri(self.name_to_efo[name])
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 124, in make_uri
    "Short form: {} not recognized".format(ontology_code))
ValueError: Could not build an URI. Short form: GO_0002524 not recognized
```
This should be fixed if `GO` is added to the first 'elif` in [make_uri](https://github.com/opentargets/OnToma/blob/master/ontoma/interface.py#L115-L119) like this:
```
lif (ontology_code.startswith('HP') or
          ontology_code.startswith('MP') or
          ontology_code.startswith('MONDO') or
          ontology_code.startswith('UBERON') or
          ontology_code.startswith('GO')):
        return 'http://purl.obolibrary.org/obo/' + ontology_code
```

**Comment by d0choa** [comment]
Not sure it applies to this issue, but keep in mind there are other id prefixes in EFO: `NCIT`, `Orphanet`, etc.

**Comment by AsierGonzalez** [comment]
`Orphanet` is covered by that method but `NCIT` is not, so we should check it. Do you have any examples that we could try? I haven't found any terms with that prefix in the Cancer Gene Census evidence file and searching for it in OLS or the OT platform returns EFO terms as the top hits.

**Comment by d0choa** [comment]
You can look at the `diseaseId` example here: https://github.com/opentargets/platform/issues/1285

**Comment by AsierGonzalez** [comment]
Thanks. Based on that list we should also support `DOID`. I'll search for examples of the three cases.

**Comment by AsierGonzalez** [comment]
I can confirm that the same problem applies to matches with NCIT and DOID ids:

- NCIT example:

```
>>> t.get_efo_label('NCIT_C95746')
INFO     - ontoma.interface - EFO OBO parsed. Size: 26845 nodes
'sleepiness'
>>> t.efo_lookup('sleepiness')
INFO     - ontoma.interface - Parsed 126677 Name to EFO mapping 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 365, in efo_lookup
    return make_uri(self.name_to_efo[name])
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 124, in make_uri
    "Short form: {} not recognized".format(ontology_code))
ValueError: Could not build an URI. Short form: NCIT_C95746 not recognized
```

- DOID example:

```
>>> t.get_efo_label('DOID_7551')
'gonorrhea'
>>> t.efo_lookup('gonorrhea')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 365, in efo_lookup
    return make_uri(self.name_to_efo[name])
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 124, in make_uri
    "Short form: {} not recognized".format(ontology_code))
ValueError: Could not build an URI. Short form: DOID_7551 not recognized
```

Their URLs also belongs to the OBO category so they just need to be added to the same `elif` as GO:
```
    elif (ontology_code.startswith('HP') or
          ontology_code.startswith('MP') or
          ontology_code.startswith('MONDO') or
          ontology_code.startswith('UBERON')  or
          ontology_code.startswith('GO') or
          ontology_code.startswith('DOID') or
          ontology_code.startswith('NCIT')):
        return 'http://purl.obolibrary.org/obo/' + ontology_code
```

**Comment by DSuveges** [comment]
I did a systematic check on the available prefixes that we should(?) support. I got the list based on the most recent EFO release (not the OT specific slim version though, but I guess we try to make a rather generic tool)

```bash
wget -q https://github.com/EBISPOT/efo/releases/download/v3.30.0/efo.json
```

These are all possible sources:

|    | source      |   count | example                      | label                                                                      |
|---:|:------------|--------:|:-----------------------------|:---------------------------------------------------------------------------|
|  0 | EFO         |   11274 | EFO_0006529                  | 2TS22C                                                                     |
|  1 | Orphanet    |    6213 | Orphanet_199315              | Familial clubfoot with or without associated lower limb anomalies          |
|  2 | MONDO       |    3309 | MONDO_0002974                | cervical cancer                                                            |
|  3 | CHEBI       |    1533 | CHEBI_26536                  | retinoic acid                                                              |
|  4 | NCBITaxon   |    1497 | NCBITaxon_121558             | Senecio vulgaris subsp. vulgaris                                           |
|  5 | HP          |    1341 | HP_0008115                   | Clinodactyly of the 3rd toe                                                |
|  6 | UBERON      |     914 | UBERON_0011579               | venom gland                                                                |
|  7 | CL          |     699 | CL_0001067                   | group 1 innate lymphoid cell                                               |
|  8 | GO          |     450 | GO_0002524                   | hypersensitivity                                                           |
|  9 | CLO         |     429 | CLO_0032713                  | GM13649                                                                    |
| 10 | PO          |     215 | PO_0025615                   | rosette                                                                    |
| 11 | FBbt        |     110 | FBbt_00001069                | embryonic stomatogastric nervous system                                    |
| 12 | UO          |      98 | UO_0000301                   | microgram per liter                                                        |
| 13 | OBI         |      75 | OBI_0100026                  | organism                                                                   |
| 14 | BTO         |      74 | BTO_0001130                  | prostate gland cancer cell                                                 |
| 15 | RO          |      57 | RO_0001025                   | located_in                                                                 |
| 16 | EO          |      43 | EO_0001001                   | plant treatment                                                            |
| 17 | uberon      |      38 | uberon#branch_of             | branch_of                                                                  |
| 18 | HANCESTRO   |      36 | HANCESTRO_0004               | ancestry category                                                          |
| 19 | ZFA         |      34 | ZFA_0001047                  | slow muscle cell somite 10                                                 |
| 20 | PATO        |      33 | PATO_0001340                 | hermaphrodite                                                              |
| 21 | BSPO        |      25 | BSPO_0001101                 | in_deep_part_of                                                            |
| 22 | BFO         |      18 | BFO_0000050                  | part of                                                                    |
| 23 | IAO         |      16 | IAO_0100001                  | term replaced by                                                           |
| 24 | oboInOwl    |      15 | oboInOwl#hasRelatedSynonym   | has_related_synonym                                                        |
| 25 | UBPROP      |      11 | UBPROP_0000101               | preceding element is                                                       |
| 26 | FMA         |      11 | FMA_3884                     | distal portion of anterior interventricular branch of left coronary artery |
| 27 | NCIT        |       9 | NCIT_C87277                  | Hippuric Acid                                                              |
| 28 | DOID        |       6 | DOID_7551                    | gonorrhea                                                                  |
| 29 | chebi       |       6 | chebi#BRAND_NAME             | BRAND NAME                                                                 |
| 30 | mondo       |       5 | mondo#disease_causes_feature | disease causes feature                                                     |
| 31 | OMIT        |       5 | OMIT_0001676                 | Adenosine Diphosphate                                                      |
| 32 | MP          |       3 | MP_0003254                   | obsolete_bile duct inflammation                                            |
| 33 | SIO         |       3 | SIO_000658                   | immediate_transformation_of                                                |
| 34 | SO          |       3 | SO_0000704                   | gene                                                                       |
| 35 | MPATH       |       3 | MPATH_0                      | pathological entity                                                        |
| 36 | TO          |       2 | TO_0000259                   | heat tolerance                                                             |
| 37 | UBREL       |       2 | UBREL_0000002                | composed_primarily_of                                                      |
| 38 | definition  |       2 | definition                   | definition                                                                 |
| 39 | United      |       2 | United_Kingdom               | United Kingdom                                                             |
| 40 | MA          |       2 | MA_0002714                   | autopod                                                                    |
| 41 | bto         |       2 | bto#develops_from            | derives from/develops from                                                 |
| 42 | PR          |       2 | PR_000003918                 | serum albumin                                                              |
| 43 | core        |       2 | core#prefLabel               | preferred label                                                            |
| 44 | bao         |       2 | bao#BAO_0000925              | Glucose-6-phosphate                                                        |
| 45 | Republic    |       1 | Republic_of_Ireland          | Republic of Ireland                                                        |
| 46 | rdf-schema  |       1 | rdf-schema#seeAlso           | see also                                                                   |
| 47 | efoIri      |       1 | efoIri                       |                                                                            |
| 48 | WBls        |       1 | WBls_0000003                 | embryo Ce                                                                  |
| 49 | owl         |       1 | owl#Thing                    |                                                                            |
| 50 | ZEA         |       1 | ZEA_0015075                  | cob                                                                        |
| 51 | frequency   |       1 | frequency_of_association     | frequency_of_association                                                   |
| 52 | Iran        |       1 | Iran                         | Iran                                                                       |
| 53 | South       |       1 | South_Korea                  | South Korea                                                                |
| 54 | China       |       1 | China                        | China                                                                      |
| 55 | Philippines |       1 | Philippines                  | Philippines                                                                |
| 56 | obo         |       1 | obo#has_role                 | has_role                                                                   |
| 57 | has         |       1 | has_flag                     | has_flag                                                                   |
| 58 | Japan       |       1 | Japan                        | Japan                                                                      |
| 59 | is          |       1 | is_executed_in               | is_executed_in                                                             |
| 60 | India       |       1 | India                        | India                                                                      |
| 61 | OGMS        |       1 | OGMS_0000063                 | disease course                                                             |
| 62 | IDO         |       1 | IDO_0000450                  | pathogenicity                                                              |
| 63 | added       |       1 | added_for_HCA                | added_for_HCA                                                              |
| 64 | creator     |       1 | creator                      | creator                                                                    |
| 65 | FBdv        |       1 | FBdv_00005331                | dorsal closure stage                                                       |


There are quite so many, we should came up with some robust method.

**Comment by ireneisdoomed** [comment]
Transferring to @tskir to study the removal of the hard-coded prefixes.

**Comment by d0choa** [comment]
I believe you might have resolved this, isn't it? @tskir

**Comment by ireneisdoomed** [comment]
If we want to treat the ontology codes in a standardized and systematic way, the [bioregistry](https://bioregistry.io/usage) package is relevant.

**Comment by DSuveges** [comment]
We haven't resolved systematically, instead decided to expand the supported list prefixes on demand, which seems to be a headache, but in reality it rarely happens.

**Comment by DSuveges** [comment]
I quite inclined to close this ticket.
