### ISSUE TITLE
Associations heatmap: incorrect columns in beta version

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1312]
A quick comparison between [alpha](https://alpha.targetvalidation.org/disease/EFO_0000756/associations) and [beta](https://beta--platform-app.netlify.app/disease/EFO_0000756/associations) denotes that the columns in beta are misplaced.

Can we use the new datasource config static file (https://github.com/opentargets/platform/issues/1291) to resolve the position and nice name of each column in the heatmap?

Additionally, the heatmap in beta/alpha should contain 8 columns + overall as described in the config and returned by API. `Genetic associations` it's actually 2 different datatypes in the new API, as opposed to the angular App. Facets are already displayed appropriately.

**Comment by mirandaio** [comment]
Fixed here https://github.com/opentargets/platform-app/pull/279
