### ISSUE TITLE
Production deployment for the platform frontend

### ISSUE THREAD

**Issue by javfg** [opentargets/platform#1317]
This issue will explore the option of deploying the platform frontend to Google Cloud Platform. It comes from talks in meetings and slack.

### Reasons

* Having a unified deployment procedure for the whole platform which includes backend and frontend.
* GCP may improve performance.*

*: We experience random latency issues in Netlify. Originally thought to be related to cache invalidation due to frequent changes in production, but I have noticed they occur even without the bundles changing. After some investigation online, I have found [people](https://community.netlify.com/t/netlify-answers-slowly-on-static-file-access-after-deploy/3246/2) with [similar](https://community.netlify.com/t/slow-connection-after-new-deploy-on-first-load-for-every-user/20625) problems.

This is probably due to the free tier of Netlify aggressively offloading the application files from their CDNs when it is unused for a given amount of time.

Also found an analysis of different cloud hostings which mentions the issue: https://savjee.be/2017/10/Static-website-hosting-who-is-fastest/

> Netlify was a weird one. It has very good performance and is comparable to the other services here. However during my test they did have some spikes in performance and didn’t perform as consistently as the others. Still, it’s an amazing result, considering that it’s a free service.

### Options

There are at least two ways to host the application in GCP: Using a google storage bucket (as it is a static app), or using google app engine.

Both could be easily integrated in the deployment pipeline using either a Cloud Build procedure in Google Cloud or a Github action that compiles the bundle files.

I don't have enough GCP knowledge to decide on the better approach. There are also different considerations depending on which one is used, like connecting the bucket to a load balancer or setting up ssl to provide https.

**Comment by ktsirigos** [comment]
deprecated by work of @mbdebian
