### ISSUE TITLE
Duplicate adverse events returned in API

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1318]
### Observed behaviour

When querying adverse events on the drug index multiple adverse events with the same name are returned.

Query:
```
query ae{
  drug(chemblId: "CHEMBL122"){
    name
    adverseEvents{
      count
      criticalValue
      rows{
        name
        meddraCode
        count
        logLR
      }
    }
  }
}
```

Output
```
{
  "data": {
    "drug": {
      "name": "ROFECOXIB",
      "adverseEvents": {
        "count": 213,
        "criticalValue": 154.01883612042582,
        "rows": [
            {
            "name": "chest pain",
            "meddraCode": "10008479",
            "count": 2349,
            "logLR": 4812.227336306321
          },
          {
            "name": "hyperlipidaemia",
            "meddraCode": "10020665",
            "count": 1133,
            "logLR": 3950.93160055481
          },
          {
            "name": "hyperlipidaemia",
            "meddraCode": "10062060",
            "count": 1133,
            "logLR": 3950.93160055481
          },
          {
            "name": "acute myocardial infarction",
            "meddraCode": "10000931",
            "count": 1171,
            "logLR": 3283.216870261327
          },
          {
            "name": "acute myocardial infarction",
            "meddraCode": "10000930",
            "count": 1171,
            "logLR": 3283.216870261327
          },
          {
            "name": "acute myocardial infarction",
            "meddraCode": "10000929",
            "count": 1171,
            "logLR": 3283.216870261327
          },
         ...
        ]
      }
    }
  }
}
```
### Expected behaviour

Each adverse event should only be listed once.

**Comment by d0choa** [comment]
One of the scenarios I have found is names (e.g. "Diabetes mellitus") mapping to partial matches:
- Diabetes mellitus
- Diabetes mellitus, postpartum
- Diabetes mellitus, antepartum

**Comment by d0choa** [comment]
For other cases (e.g. "Hyperlipidemia") we can only resolve in bio portal one of the multiple matched ids. It makes me wonder if we have obsolete ids of some sort. It's just a guess, I have no idea what's going on.

Hyperlipidemia - 10062060 - [bioportal](http://bioportal.bioontology.org/ontologies/MEDDRA?p=classes&conceptid=10062060)
Hyperlipidemia  - 10020665 - [bioportal](http://bioportal.bioontology.org/ontologies/MEDDRA?p=classes&conceptid=10020665)

**Comment by JarrodBaker** [comment]
I'm still looking into it, but my guess is that the version of Meddra that we have, and the version that the FDA used to generate their event names are different. We had to use a mixture of Meddra 'preferred terms' and 'low level terms' to get complete coverage. 

I don't know anything about bioportal, but they may be on a different version of Meddra  or they may not provide mappings for 'low level terms'.

**Comment by JarrodBaker** [comment]
Useful context: 

- each FDA report comes with a field _reaction\_reactionmeddrapt_ which is a plain english name for an adverse reaction, eg, 'dizziness`.
- Meddra releases updates regularly which adds/deprecates certain names, classifications and codes, we don't know which Meddra version the FDA are using. 
- We want to map the field _reaction\_reactionmeddrapt_ field to a unique _meddraCode_ which can be used to link the indication back to Meddra. 

Implemented solution:
 
From our side I have changed the openfda pipeline in the following way:

- given a meddra name from FDA I try and match against meddra 'preferred terms'
- If that fails I match against medda's 'low level terms'

This seems to cover all cases. 

The problem of multiple similar entries as described in the ticket was created as I had previously created a union of Meddra's preferred and low level terms and used those to match against FDA dataset. It seems some _reaction\_reactionmeddrapt_ appear in both the preferred and low-level term indexes, creating duplicates. 

Outstanding problem: @d0choa 

We don't know which version of Meddra FDA are using, so some of the mapping problems are probably because of version problems. This is compounded when linking to something like _bioportal_ as they may be on a third version.

**Comment by d0choa** [comment]
Great! I will explore the result of this fix once it comes through the API. I presume it will be enough for our purpose. There could be a number a ids that might not be available in bioportal due to the problems above described, but I anticipate they will be a minority considering the `preferred terms` > `low level terms` rule.

Regarding the versioning, the submission of reports might even be in different versions. Not sure FDA would go through the process or re-mapping AERs reported by submitters in the past. That would be a risky task
