### ISSUE TITLE
Update evidence validator accepting the new schema

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1320]
We provide a [validator](https://github.com/opentargets/validator) for the providers to check the evidence strings, so they can check if the exported data confirms the expected format. As part of the rewrite efforts the json schema is completely re-structured. The most impactful change affecting the validator is the exclusion of the `unique_association_fields` field. 

This field is used to calculate hash for every evidence string, and check for uniqueness. As checking uniqueness is now in the domain of the OT data pipelines, it is not required, and the the field is not available. 

**So the following actions are required:**
-[ ] Remove `--hash` option 
-[ ] Update script to not require the presence of the `unique_association_fields` field in the evidence.

**Comment by andrewhercules** [comment]
Thanks @DSuveges! :-) 
Ticket closed as https://github.com/opentargets/validator/pull/27 approved and merged
