### ISSUE TITLE
Several improvements in drug summary page (rewrite)

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1322]
Bundling a few drug index improvements as they can be tackled in one go:

- [x] Not show `Known trade names:` label  when no trade names are available. [Example](https://alpha.targetvalidation.org/drug/CHEMBL1162175)

- [x] Adjust incorrect fonts in top area (e.g. Molecule type, First approval, Max phase, etc.)

- [x] Display child/parent molecules when available making use of the [new endpoints](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20parent%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL941%22)%7B%0A%20%20%20%20name%0A%20%20%20%20parentMolecule%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20childMolecules%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%0Aquery%20child%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL1642%22)%7B%0A%20%20%20%20name%0A%20%20%20%20parentMolecule%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20childMolecules%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A&operationName=child). We want the next text positioned between `max phase` and `synonyms`. For Ixazomib in which `childMolecules.length > 0` show "Child molecule: [IXAZOMIB CITRATE](https://alpha.targetvalidation.org/drug/CHEMBL3545432/)" Instead, for Ixazomib citrate in which `parentMolecule != null` show "Parent molecule: [IXAZOMIB](https://alpha.targetvalidation.org/drug/CHEMBL2141296/)". More info in #1308

- [x] Update description of Mechanism of Action section:

```
Current:
<DRUG> biochemical interactions to produce intended pharmacological effects. Curated from scientific literature and post-marketing package inserts. Source: [ChEMBL](https://www.ebi.ac.uk/chembl/)

When childMolecules.length > 0 | parentmolecule.length != null
<DRUG>, and related molecules <CHILD DRUG 1>, <CHILD DRUG2> <PARENT DRUG1>, biochemical interactions to produce intended pharmacological effects. Curated from scientific literature and post-marketing package inserts. Source: [ChEMBL](https://www.ebi.ac.uk/chembl/)

```

- [x] Improve UI for `Mechanisms of Action` table when many targets are listed ([Example](https://alpha.targetvalidation.org/drug/CHEMBL1059))

- [x] (Captured in #1149) Add new `reference` column to indications table making use of the [new endpoints](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?operationName=parent&query=query%20parent%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL3353410%22)%7B%0A%20%20%20%20name%0A%20%20%20%20indications%7B%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20maxPhaseForIndication%0A%20%20%20%20%20%20%20%20references%7B%0A%20%20%20%20%20%20%20%20%20%20ids%0A%20%20%20%20%20%20%20%20%20%20source%0A%20%20%20%20%20%20%20%20%20%20urls%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A). Implementation is similar to the current Known drugs / Clinical Precedence widgets.  

 - [x] READ COMMENTS BELOW - Add a badge saying "Approved" after phase when `isApproved` flag equals `True`. ([Example](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20approval%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL122%22)%7B%0A%20%20%20%20name%0A%20%20%20%20isApproved%0A%20%20%20%20withdrawnNotice%7B%0A%20%20%20%20%20%20classes%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=approval)). I would place the currently implemented withdrawn warning right after Phase and approval in case it's available.

**Comment by andrewhercules** [comment]
Also, as a low-priority request, is it possible to tune the parameters used to draw small molecules? Specifically to account for larger and smaller molecules?

See https://alpha.targetvalidation.org/drug/CHEMBL2111100 vs https://alpha.targetvalidation.org/drug/CHEMBL112

**Comment by andrewhercules** [comment]
As an idea for the `isApproved` flag, we could rearrange the summary section and include a new field called 'Status' and list 'Approved' if `isApproved == true`. This would scale if we were to include more DrugBank data and include the categories they assign to drugs (e.g. 'Approved', 'Withdrawn', 'Investigational' for [rofecoxib](https://go.drugbank.com/drugs/DB00533))

![Screenshot 2021-01-15 at 10 26 42](https://user-images.githubusercontent.com/7490258/104713793-4435a800-571c-11eb-91ea-589690b4543e.png)

**Comment by d0choa** [comment]
Sounds good, we would benefit from some UI consistency on this section. Could you help us with a slightly more detailed design for the Status field?

**Comment by d0choa** [comment]
Regarding the molecules, @andrewhercules #1167 tries to cover this.

I don't think it would be trivial to just tune the parameters of the layout algorithm. I noticed other molecules suffer from the opposite problem. Even in that case, molecules are sometimes not correct and ChEMBL has similar issues as well.

We aim to try to get the images from ChemSpider which seems to have the best chemical structures. The current blocker was how to bulk-download the structures.

**Comment by d0choa** [comment]
In yesterday meeting, we discussed about the indication references. Some improvements to make:
- [ ] Display the `source` instead of the `ids` when only 1 reference is available. When using the drawer, it would be ok to show the ids listed within the resource.
- [ ] Improve spacing of the table columns.
- [ ] Improve the dictionary of sources to cover all cases.

@mirandaio / @andrewhercules I got an example of all possible different sources using the indications json data:

(Sorry the code is a bit messy)

```python
w2 = Window.partitionBy("source").orderBy(col("id").desc())
test = (indication
        .select("id", explode(col("indications.references")).alias("refs"))
        .select("id", explode("refs").alias("ref"))
        .select("id", col("ref.*")).withColumn("row", row_number().over(w2))
        .filter(col("row") == 1).drop("row")
        .coalesce(1)
        .write
        .json("..."))

```

```json
{
  "id": "CHEMBL998",
  "ids": [
    "R06AX13"
  ],
  "source": "ATC",
  "urls": [
    "http://www.whocc.no/atc_ddd_index/?code=R06AX13"
  ]
}
{
  "id": "CHEMBL998",
  "ids": [
    "1f65158a-fb5e-4864-845f-daf6fed271f4",
    "cd21751e-e62f-40f3-a254-f2db7cf9c101",
    "fa5ddd82-33ba-4cc8-a13f-1a866299367e"
  ],
  "source": "DailyMed",
  "urls": [
    "http://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f65158a-fb5e-4864-845f-daf6fed271f4",
    "http://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cd21751e-e62f-40f3-a254-f2db7cf9c101",
    "http://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa5ddd82-33ba-4cc8-a13f-1a866299367e"
  ]
}
{
  "id": "CHEMBL998",
  "ids": [
    "06ba2cf5-7cb1-44cf-8cda-3974bf964ca7",
    "37e1393b-7176-4480-9299-5bb9db62e19e",
    "637f676f-1f12-4514-8a92-84e620dfd130",
    "a050aa01-8335-4178-b715-6478ba1de419",
    "cfb113fe-468c-4f6c-8ed5-8f0045821f51",
    "e12428cd-6bf8-4597-a78a-1eec44c4a010",
    "e1420f6f-8c08-4c4d-b44d-2d01f96ee123"
  ],
  "source": "FDA",
  "urls": [
    "https://api.fda.gov/drug/label.json?search=set_id:06ba2cf5-7cb1-44cf-8cda-3974bf964ca7",
    "https://api.fda.gov/drug/label.json?search=set_id:37e1393b-7176-4480-9299-5bb9db62e19e",
    "https://api.fda.gov/drug/label.json?search=set_id:637f676f-1f12-4514-8a92-84e620dfd130",
    "https://api.fda.gov/drug/label.json?search=set_id:a050aa01-8335-4178-b715-6478ba1de419",
    "https://api.fda.gov/drug/label.json?search=set_id:cfb113fe-468c-4f6c-8ed5-8f0045821f51",
    "https://api.fda.gov/drug/label.json?search=set_id:e12428cd-6bf8-4597-a78a-1eec44c4a010",
    "https://api.fda.gov/drug/label.json?search=set_id:e1420f6f-8c08-4c4d-b44d-2d01f96ee123"
  ]
}
{
  "id": "CHEMBL99946",
  "ids": [
    "NCT02265367"
  ],
  "source": "ClinicalTrials",
  "urls": [
    "https://clinicaltrials.gov/search?id=%22NCT02265367%22"
  ]
}
```

Based on our conversation yesterday, it would be ok to use the ids field to construct all urls. I will let Jarrod know this is the case.

**Comment by andrewhercules** [comment]
Thank you @d0choa!

@mirandaio can we please adjust the mapping, link construction, and UI?

| Source | `source` string from API | Link structure | Label to display if only 1 record and 1 source |
| --- | --- | --- | --- |
| ClinicalTrials.gov | "ClinicalTrials" | `https://www.clinicaltrials.gov/ct2/show/` + `ids[x]` | ClinicalTrials.gov |
| FDA | "FDA" | `https://api.fda.gov/drug/label.json?search=set_id:` + `ids[x]` | FDA |
| ATC | "ATC" | `http://www.whocc.no/atc_ddd_index/?code=` + `ids[x]` | ATC |
| DailyMed | "DailyMed" | `http://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=` + `ids[x]` | DailyMed |

For the use of labels and the drawer component, can we please follow the implementation of the Known Drugs data table "Source" column? For example, if there is only one ID and one source - and so no drawer component needed - please show the label of the source. (e.g. [ATC](http://www.whocc.no/atc_ddd_index/?code=R06AX13)).

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/285
