### ISSUE TITLE
OT covid tool data update

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1324]
We want to update to use the OT platform 20.11 data. (a bit late for it).
Also there is new interactions data that could be plugged.

After data is updated. We will need to create a github release and link it to the FE

**Comment by ireneisdoomed** [comment]
A new version of the COVID-19 tool has been released with the following updates:
- New COVID19 related and human interactions from IntAct
- Updated human genome dataset
- Updated Open Targets data with new tractability and COVID19 literature data coming from the 21.02 release.
