### ISSUE TITLE
Update ontology visualisation interaction behaviour 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1327]
Can we please adjust the ontology visualisation on the disease/phenotype profile page?

- [ ] When a user hovers over either the node or the name, bold the selection and show the full disease/phenotype label and the ID in a tooltip
- [ ] Allow the user to click either the node or label

![new_ontology_on_hover](https://user-images.githubusercontent.com/7490258/104717290-f8393200-5720-11eb-842b-dcfbe78f55a7.jpg)

Example: [Noonan syndrome](https://beta--platform-app.netlify.app/disease/Orphanet_648)

**Comment by andrewhercules** [comment]
Moved to `21.06` release

**Comment by ktsirigos** [comment]
closing issue as work done.
