### ISSUE TITLE
Experiments data missing in API response for STRING

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1330]
After reviewing the data with @andrewhercules we concluded the "Experiments" datasource is missing in the STRING API response.

- [GAPDH interactions in STRING website](https://string-db.org/cgi/network?taskId=bGqcXntCSj2Z&sessionId=b5QNyZUzvfOT)
- [GAPHD interactions in GraphQL API](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0Aquery%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000111640%22)%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20interactions(sourceDatabase%3A%22string%22)%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20intA%0A%20%20%20%20%20%20%20%20intB%0A%20%20%20%20%20%20%20%20targetA%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20targetB%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20evidences%7B%0A%20%20%20%20%20%20%20%20%20%20interactionDetectionMethodShortName%0A%20%20%20%20%20%20%20%20%20%20interactionDetectionMethodMiIdentifier%0A%20%20%20%20%20%20%20%20%20%20evidenceScore%0A%20%20%20%20%20%20%20%20%20%20interactionScore%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by DSuveges** [comment]
So, when looking at the String input file, it indeed has an `experimental` column:

```bash
curl -s https://stringdb-static.org/download/protein.links.detailed.v11.0/9606.protein.links.detailed.v11.0.txt.gz | gzcat | head 
```

```
protein1 protein2 neighborhood fusion cooccurence coexpression experimental database textmining combined_score
9606.ENSP00000000233 9606.ENSP00000272298 0 0 332 62 181 0 125 490
9606.ENSP00000000233 9606.ENSP00000253401 0 0 0 0 186 0 56 198
9606.ENSP00000000233 9606.ENSP00000401445 0 0 0 0 159 0 0 159
9606.ENSP00000000233 9606.ENSP00000418915 0 0 0 61 158 0 542 606
9606.ENSP00000000233 9606.ENSP00000327801 0 0 0 88 78 0 89 167
9606.ENSP00000000233 9606.ENSP00000466298 0 0 0 141 131 0 98 267
9606.ENSP00000000233 9606.ENSP00000232564 0 0 0 62 171 0 56 201
9606.ENSP00000000233 9606.ENSP00000393379 0 0 0 61 131 0 43 150
9606.ENSP00000000233 9606.ENSP00000371253 0 0 0 61 0 0 224 240
```

However the script in platform input support does expect to have a columns called `experiments`

```python
    # The following STRING channels can be mapped to detection methods on MI onotology:
    detection_method_mapping = {
        'coexpression': {'name': 'coexpression', 'mi_id': 'MI:2231'},
        'coexpression_transferred': {'name': 'coexpression_transferred', 'mi_id': ''},
        'neighborhood': {'name': 'neighborhood', 'mi_id': 'MI:0057'},
        'neighborhood_transferred': {'name': 'neighborhood_transferred', 'mi_id': ''},
        'fusion': {'name': 'fusion', 'mi_id': 'MI:0036'},
        'homology': {'name': 'homology', 'mi_id': 'MI:2163'},
        'experiments': {'name': 'experiments', 'mi_id': 'MI:0591'},
        'experiments_transferred': {'name': 'experiments_transferred', 'mi_id': ''},
        'cooccurence': {'name': 'cooccurence', 'mi_id': 'MI:2231'},
        'database': {'name': 'database', 'mi_id': ''},
        'database_transferred': {'name': 'database_transferred', 'mi_id': ''},
        'textmining': {'name': 'textmining', 'mi_id': 'MI:0110'},
        'textmining_transferred': {'name': 'textmining_transferred', 'mi_id': ''},
    }
```

Its coming from the time when we used the homology expanded dataset:

```bash
curl -s https://stringdb-static.org/download/protein.links.full.v11.0/9606.protein.links.full.v11.0.txt.gz | gunzip | head
```

```
protein1 protein2 neighborhood neighborhood_transferred fusion cooccurence homology coexpression coexpression_transferred experiments experiments_transferred database database_transferred textmining textmining_transferred combined_score
9606.ENSP00000000233 9606.ENSP00000272298 0 0 0 332 0 0 62 0 181 0 0 0 125 490
9606.ENSP00000000233 9606.ENSP00000253401 0 0 0 0 0 0 0 0 186 0 0 0 56 198
9606.ENSP00000000233 9606.ENSP00000401445 0 0 0 0 0 0 0 0 160 0 0 0 0 159
9606.ENSP00000000233 9606.ENSP00000418915 0 0 0 0 0 0 61 0 158 0 0 542 0 606
9606.ENSP00000000233 9606.ENSP00000327801 0 0 0 0 0 69 61 0 78 0 0 0 89 167
9606.ENSP00000000233 9606.ENSP00000466298 0 0 0 0 0 141 0 0 131 0 0 0 98 267
9606.ENSP00000000233 9606.ENSP00000232564 0 0 0 0 0 0 62 0 171 0 0 0 56 201
9606.ENSP00000000233 9606.ENSP00000393379 0 0 0 0 0 0 61 0 131 0 0 0 43 150
9606.ENSP00000000233 9606.ENSP00000371253 0 0 0 0 0 0 61 0 0 0 0 0 224 240
```

I'll open a PR for this.

**Comment by DSuveges** [comment]
Fix merged to [platform input support](https://github.com/opentargets/platform-input-support/pull/23)
