### ISSUE TITLE
Potential grouping by biological role issue in interactions (Signor) feed

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1331]
After reviewing the data with @andrewhercules, we concluded there is a potential issue in the Signor data feed (and potentially others)

When looking at the [Signor website for CDK1](https://signor.uniroma2.it/relation_result.php?id=P06493), there are 2 different relations that contain WEE1 as a partner. In the first, CDK1 is the regulator and contains 2 evidence (SIGNOR-139465 and SIGNOR-123824) and in the second WEE1 is the regulator and contains one piece of evidence (SIGNOR-139491).

When looking at our [API](http://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20target(ensemblId%3A%22ENSG00000170312%22)%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20approvedName%0A%20%20%20%20%0A%20%20%20%20interactions(%0A%20%20%20%20%20%20%20%20sourceDatabase%3A%20%22signor%22%0A%20%20%20%20%20%20%20%20page%3A%20%7B%20index%3A%200%2C%20size%3A%201000%20%7D%0A%20%20%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20intA%0A%20%20%20%20%20%20%20%20%20%20intABiologicalRole%0A%20%20%20%20%20%20%20%20%20%20targetA%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20speciesA%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20mnemonic%0A%20%20%20%20%20%20%20%20%20%20%23%20%7D%0A%20%20%20%20%20%20%20%20%20%20intB%0A%20%20%20%20%20%20%20%20%20%20intBBiologicalRole%0A%20%20%20%20%20%20%20%20%20%20targetB%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20speciesB%20%7B%0A%20%20%20%20%20%20%20%20%20%20%23%20%20%20mnemonic%0A%20%20%20%20%20%20%20%20%20%20%23%20%7D%0A%20%20%20%20%20%20%20%20%20%20%23%20scoring%0A%20%20%20%20%20%20%20%20%20%20%23%20count%0A%20%20%20%20%20%20%20%20%20%20%23%20sourceDatabase%0A%20%20%20%20%20%20%20%20%20%20evidences%20%7B%0A%20%20%20%20%20%20%20%20%20%20%09interactionIdentifier%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=assocs). The 3 pieces of evidence have been grouped together with the same biological role (incorrect):

```
          {
            "intABiologicalRole": "regulator",
            "targetA": {
              "approvedSymbol": "CDK1"
            },
            "intBBiologicalRole": "regulator target",
            "targetB": {
              "approvedSymbol": "WEE1"
            },
            "evidences": [
              {
                "interactionIdentifier": "SIGNOR-123824"
              },
              {
                "interactionIdentifier": "SIGNOR-139465"
              },
              {
                "interactionIdentifier": "SIGNOR-139491"
              }
            ]
          },

``` 

It would be good to check if this problem is limited to Signor or does apply to other datasources as well

**Comment by DSuveges** [comment]
When looking at the specific pair of interactions:

```bash
curl -s ftp://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/2021-01-18/data/interactor_pair_interactions.json \
  | grep P06493  | grep P30291  | grep -i signor | jq
```
Returns only one interaction:

```json
{
  "interactorA": {
    "organism": {
      "taxon_id": 9606,
      "mnemonic": "human",
      "scientific_name": "Homo sapiens"
    },
    "id_source": "uniprotkb",
    "id": "P06493",
    "biological_role": "regulator"
  },
  "interactorB": {
    "organism": {
      "taxon_id": 9606,
      "mnemonic": "human",
      "scientific_name": "Homo sapiens"
    },
    "id_source": "uniprotkb",
    "id": "P30291",
    "biological_role": "regulator target"
  },
  "source_info": {
    "database_version": "Not Available",
    "source_database": "signor"
  },
  "interaction": {
    "causal_interaction": null,
    "evidence": [
      {
        "pubmed_id": "15070733",
        "participant_detection_method_B": [
          {
            "mi_identifier": null,
            "short_name": null
          }
        ],
        "interaction_detection_method_mi_identifier": "MI:0364",
        "interaction_detection_method_short_name": "inferred by curator",
        "participant_detection_method_A": [
          {
            "mi_identifier": null,
            "short_name": null
          }
        ],
        "expansion_method_mi_identifier": null,
        "host_organism_tax_id": 9606,
        "interaction_type_mi_identifier": "MI:0217",
        "expansion_method_short_name": null,
        "host_organism_scientific_name": "Homo sapiens",
        "interaction_identifier": "SIGNOR-123824",
        "interaction_type_short_name": "phosphorylation"
      },
      {
        "pubmed_id": "16085715",
        "participant_detection_method_B": [
          {
            "mi_identifier": null,
            "short_name": null
          }
        ],
        "interaction_detection_method_mi_identifier": "MI:0364",
        "interaction_detection_method_short_name": "inferred by curator",
        "participant_detection_method_A": [
          {
            "mi_identifier": null,
            "short_name": null
          }
        ],
        "expansion_method_mi_identifier": null,
        "host_organism_tax_id": 9606,
        "interaction_type_mi_identifier": "MI:0217",
        "expansion_method_short_name": null,
        "host_organism_scientific_name": "Homo sapiens",
        "interaction_identifier": "SIGNOR-139465",
        "interaction_type_short_name": "phosphorylation"
      },
      {
        "pubmed_id": "16096060",
        "participant_detection_method_B": [
          {
            "mi_identifier": null,
            "short_name": null
          }
        ],
        "interaction_detection_method_mi_identifier": "MI:0364",
        "interaction_detection_method_short_name": "inferred by curator",
        "participant_detection_method_A": [
          {
            "mi_identifier": null,
            "short_name": null
          }
        ],
        "expansion_method_mi_identifier": null,
        "host_organism_tax_id": 9606,
        "interaction_type_mi_identifier": "MI:0217",
        "expansion_method_short_name": null,
        "host_organism_scientific_name": "Homo sapiens",
        "interaction_identifier": "SIGNOR-139491",
        "interaction_type_short_name": "phosphorylation"
      }
    ],
    "interaction_score": null
  }
}
```
So it seems Intact does not discriminate the biological roles when one is `regulator` and the other is `regulator_target`. I this boils down on how Intact represents Signor data. It worth sending them an email.

**Comment by DSuveges** [comment]
We have communicated the issue with Intact and they are addressing the problem but probably for the next release.
