### ISSUE TITLE
Implement new Phenotypes data table on disease/phenotype profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1332]
The new GraphQL API `disease` endpoint now exposes more phenotypes data. And so we can replace the current unordered list with a more comprehensive data table. Further details and spec TBC.

Example diseases with phenotypes: [Cowden Syndrome](https://alpha.targetvalidation.org/disease/Orphanet_201), [Noonan Syndrome](https://alpha.targetvalidation.org/disease/Orphanet_648), [ulcerative colitis](https://alpha.targetvalidation.org/disease/EFO_0000729)

**Comment by andrewhercules** [comment]
Data is now available from the development API branch - see [sample query](https://hpo-1-0-dot-api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20diseasePheno%7B%0A%20%20disease(efoId%3A%20%22Orphanet_955%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20phenotypes(page%3A%20%7Bindex%3A0%2C%20size%3A500%7D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20phenotypeHPO%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20namespace%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20phenotypeEFO%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20evidence%20%7B%0A%20%20%20%20%20%20%20%20%20%20aspect%0A%20%20%20%20%20%20%20%20%20%20bioCuration%0A%20%20%20%20%20%20%20%20%20%20diseaseFromSourceId%0A%20%20%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20%20%20evidenceType%0A%20%20%20%20%20%20%20%20%20%20frequency%0A%20%20%20%20%20%20%20%20%20%20frequencyHPO%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20qualifierNot%0A%20%20%20%20%20%20%20%20%20%20onset%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20modifiers%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20references%0A%20%20%20%20%20%20%20%20%20%20sex%0A%20%20%20%20%20%20%20%20%20%20resource%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) 

Can we please implement the following data table based on [the design spec](https://docs.google.com/presentation/d/1tMG8WmDkY6ZojO6291MjO0EkuSlEbQTgj2pKJZktdHw/edit?ts=6006f69d#slide=id.gb6f7132765_0_0)?

![Phenotypes_spec](https://user-images.githubusercontent.com/7490258/105176516-41242880-5b1d-11eb-9977-cd7e865008d5.png)

Please note the following: (TBC)

- Please expand the number of entries in `row.evidence` - each entry should be in its own row


QC checks:

- [ ] Acroosteolysis dominant type - Orphanet_955
- [ ] ulcerative colitis - EFO_0000729
- [ ] Early infantile epileptic encephalopathy - Orphanet_1934

**Comment by andrewhercules** [comment]
@LucaFumis the spec is complete

@d0choa please review the spec above. I slightly adjusted the "References" column as the identifers.org link structure won't work due to the prefixes - instead we can link directly to the HPO website

**Comment by d0choa** [comment]
It looks fantastic. Thank you @andrewhercules

**Comment by d0choa** [comment]
@LucaFumis @andrewhercules The name of the widget was never updated. I would recommend changing the name to avoid confusion with "phenotypes" that show up in our disease profile pages.

More importantly, the sources need to be updated to HPO and MONDO as described in the spec.

**Comment by andrewhercules** [comment]
Noted - I've added to the feedback document for the next round of polish

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `beta`

Polish work will be captured in subsequent Beta Release polish ticket

**Comment by andrewhercules** [comment]
@LucaFumis for Integration Day tomorrow - 24 February - can we please make the following small adjustments?

1. Change the name of the detail view to "Clinical signs and symptoms"
2. Change the letter acronym to "CS"
3. Update the "Source: EFO" list to include
- MONDO (https://mondo.monarchinitiative.org/)
- HPO (https://hpo.jax.org/app/)

**Comment by LucaFumis** [comment]
Last requested changes were implemented for Integration day. Ticket can be closed, I imagine.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main` for Beta release
