### ISSUE TITLE
I would like to have an example for EuropePMC for the new JSON schema

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1340]
Provide an example evidence from EuropePMC of how it looks with the current JSON schema and how it should look like when they use the new schema

**Comment by d0choa** [comment]
Example of the new evidence. A few disclaimers:
- Based on iter13 - 20.11 data
- Some fields here won't be necessary in the input evidence (e.g. `id`).
- Desired further enhancements on the evidence, have not yet been included here 
- Overall, this evidence needs to be reviewed manually and some changes will be added
- Evidences are selected "randomly" from high-scoring evidence based on the below algorithm

```
w2 = Window.partitionBy("sourceId").orderBy(col("score").desc())
out = df.withColumn("row", row_number().over(w2)).filter(col("row") == 1).drop("row")
out.write.json("/Users/ochoa/exampleEvidence.json")
```

@ktsirigos you can try to find the same evidence in the old pipeline. (ask @AsierGonzalez if you don't know how to do it)
@ireneisdoomed, we should iterate in the desired evidence further.

NOTE: I truncated the next evidence for illustrative purposes:

```
{
  "diseaseFromSourceId": "EFO_0000311",
  "resourceScore": 137.4,
  "literature": [
    "31508364"
  ],
  "targetId": "ENSG00000146648",
  "textMiningSentences": [
    {
      "dEnd": 24,
      "dStart": 19,
      "section": "title",
      "tEnd": 14,
      "tStart": 11,
      "text": "Rethink of EGFR in Cancer With Its Kinase Independent Function on Board"
    },
    ...
  ],
  "targetFromSourceId": "P00533",
  "datasourceId": "europepmc",
  "datatypeId": "literature",
  "diseaseFromSource": "Cancer",
  "diseaseId": "EFO_0000311",
  "id": "5bf3b0e28e52103081e59dfb0055a47363c225a6",
  "score": 1,
  "sourceId": "europepmc"
}
```

**Comment by ktsirigos** [comment]
@d0choa I need the full evidence because I have two hits, one in full text and one in abstract. Thanks!

**Comment by ireneisdoomed** [comment]
@ktsirigos You can see the whole string here. 
 [https://app.zenhub.com/files/143733948/dc736ea8-5e4b-4c0b-be38-351163879e9b/download](https://app.zenhub.com/files/143733948/dc736ea8-5e4b-4c0b-be38-351163879e9b/download)

**Comment by d0choa** [comment]
It was agreed that EPMC will submit data, that will no longer comply with the evidence json schema.
