### ISSUE TITLE
When clicking data type of sub category, the number is not changed

### ISSUE THREAD

**Issue by junaruga** [opentargets/platform#135]
Hello,

I might find a bug.

How to reproduce

1. Search by "BRCA2" on top page.
2. Click "Bubbles" tab.
3. Click the left side data type: "Somatic mutations (146)" on, then the title is changed to "146 diseases associated with BRCA2", and the bubble is changed.
4. Click the sub category "European Variation ... (14)"

Expectation: the title should be changed to "14 diseases associated with BRCA2", and the bubble should be changed.
Actual: the title was not changed keeping "146 diseases associated with BRCA2", and also the bubble is not changed.

The captured page is here.
![opentargets_target_filter](https://user-images.githubusercontent.com/121989/45933069-7983be00-bf86-11e8-91e1-0d5c882dd9fe.png)

By the way,

1. Search by "BRCA2" on top page.
2. Click "Bubbles" tab.
3. Click the left side data type: "Somatic mutations (146)" on, then the title is changed to "146 diseases associated with BRCA2", and the bubble is changed.
4. Click the left side data type: "Somatic mutations (146)" "off"
5. Click the sub category "European Variation ... (14)"

After that, the title is correctly changed to "14 diseases associated with BRCA2", and the bubble is correctly changed.

**Comment by deniseOme** [comment]
Hi @junaruga, thanks for getting in touch and reporting this.

We will be looking into fixing this. In the meantime I'm glad to hear you have found a workaround by ticking "Somatic mutations" off, then ticking only "European Variation ..." for the expected display of 14 diseases. 

I will let you know when this is fixed.

Apologies for the slight delay in getting back to you here. You may want to consider reporting issues like these to our Support team (support at targetvalidation dot org) as our Helpdesk is monitored on a hourly basis for prompt replies to our users.

**Comment by junaruga** [comment]
@deniseOme Alright. Thanks for your help! I am quite casual user of Open Targets. It's not urgent :)

**Comment by andrewhercules** [comment]
Ticket closed as Angular web app will be deprecated in Q1 - 2020 and replaced with a new React version.

@peatroot, in the React rewrite version of the Platform application, can you please amend the Associations view so that this bug is fixed, similar to [this solution](http://jsfiddle.net/mU3FV/7/)?
