### ISSUE TITLE
Create scaffold for the snakemake pipeline

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1354]

**Comment by DSuveges** [comment]
A working prototype of the snakemake workflow is available in the [snakemake_scaffold](https://github.com/opentargets/evidence_datasource_parsers) branch. 

**Files added:**
1. `Snakemake`: workflow file describing the rules
2. `configuration.yaml`: configuration for the workflow + input/output files for the parsers. 

**How to run:**
1. Creating key file for the service account:
```bash
FILENAME=FILENAME="$(pwd)/gcp-account.json"
gcloud iam service-accounts keys create ${FILENAME} --iam-account=platform-input-support@open-targets-eu-dev.iam.gserviceaccount.com
```
2. Store the filename in an env. variable:
```bash
export GOOGLE_APPLICATION_CREDENTIALS=${FILENAME}
```
3. Run pipeline:
```bash
snakemake  --cores 3
```

**TODOs:**
* Currently the pipeline writes into my google bucket, which needs to be updated. (Setting the correct location for all the parsers is not urgent at the moment)
* We might want to choose an other service account, and it has to be properly configured to have access to all the required buckets.
* Config file at this point is hardcoded in the Snakefile, it is not the best idea, but makes easier to run. At the end we can remove and make it optional. `--configfile=<config.yaml>`
