### ISSUE TITLE
Add cross-references to drug profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1356]
The GraphQL `drug` endpoint will soon expose cross-references with IDs that we can use to construct links to other websites.

![Screenshot 2021-01-22 at 09 51 08](https://user-images.githubusercontent.com/7490258/105475545-6046c580-5c97-11eb-8f1f-71b5cdae1e0a.png)
[Query for CHEMBL122](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20drugXrefs%20%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL122%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20crossReferences%7B%0A%20%20%20%20%20%20source%0A%20%20%20%20%20%20reference%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=drugXrefs) 

Based on a review of the data provided by ChEMBL, we will use the following cross-references to build external links:

- DrugBank
- ChEBI
- DailyMed 
- DrugCentral
- Wikipedia

Can we please add cross-references to the existing section displaying the ChEMBL ID? The UI style would follow that of cross-references found in the target profile page - source followed by ID (with hyperlink) followed by single pipe to separate each source.

![Screenshot 2021-01-22 at 09 41 43](https://user-images.githubusercontent.com/7490258/105475628-794f7680-5c97-11eb-8761-2b36c306a625.png)

The table below lists the source string provided by the GraphQL API and the associated link structure for implementation.

| Source (from API response) | URL structure | Example | ID for QC test
| --- | --- | --- | --- |
| "drugbank" | `https://identifiers.org/drugbank:` + `crossReferences.reference[0]` | DrugBank: [DB05553](https://identifiers.org/drugbank:DB05553) | CHEMBL1162175 - regrelor | 
| "chEBI" | `https://identifiers.org/CHEBI:` + `crossReferences.reference[0]` | ChEBI: [46195](https://identifiers.org/CHEBI:46195) | CHEMBL122 - acetaminophen |
| "DailyMed" | `https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=` + `crossReferences.reference[0]` | DailyMed: [atezolizumab](https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=atezolizumab) | CHEMBL3707227 - atezolizumab |
| "DrugCentral" | `https://drugcentral.org/drugcard/` + `crossReferences.reference[0]` | DrugCentral: [4924](https://drugcentral.org/drugcard/4924) | CHEMBL3137343 - pembrolizumab |
| "Wikipedia" | `https://en.wikipedia.org/wiki/` + `crossReferences.reference[0]` | Wikipedia: [Tamoxifen](https://en.wikipedia.org/wiki/Tamoxifen) | CHEMBL83 - tamoxifen | 

Please note that all five selected cross-references will not be available for every drug. For example, [CHEMBL122](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20drugXrefs%20%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL122%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20crossReferences%7B%0A%20%20%20%20%20%20source%0A%20%20%20%20%20%20reference%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=drugXrefs) only has DrugBank, ChEBI, and Wikipedia cross-references whereas [CHEMBL3137343](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20drugXrefs%20%7B%0A%20%20drug(chemblId%3A%20%22CHEMBL3137343%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20crossReferences%7B%0A%20%20%20%20%20%20source%0A%20%20%20%20%20%20reference%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=drugXrefs) only has DailyMed and DrugCentral cross-references.

**Comment by d0choa** [comment]
![Screenshot 2021-02-01 at 14 22 02](https://user-images.githubusercontent.com/5097586/106470849-e8e41380-6498-11eb-8def-74500f7cd6ee.png)

Can we please account for the `%20` of the DailyMed links in the FE?
https://beta--platform-app.netlify.app/drug/CHEMBL3353410

**Comment by mirandaio** [comment]
@d0choa DailyMed links have been fixed!
