### ISSUE TITLE
Update disease synonyms FE due to endpoint changing in API

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1358]
## Context
Due to the increased granularity of information on the disease synonyms endpoints the FE logic needs to be updated, otherwise the application will crash.

The API currently returns an array of strings when querying the synonyms endpoint:

```
query diseasePheno{
  disease(efoId: "MONDO_0021251") {
    id
    name
    isTherapeuticArea
    synonyms
  }
}
```

```
{
  "data": {
    "disease": {
      "id": "MONDO_0021251",
      "name": "endometrium neoplasm",
      "isTherapeuticArea": false,
      "synonyms": [
        "endometrial tumor",
        "neoplasm of the endometrium",
        "tumor of the endometrium",
        "neoplasm of endometrium",
        "endometrium tumor",
        "endometrial neoplasm",
        "endometrium neoplasm (disease)",
        "tumor of endometrium"
      ]
    }
  }
}
```

When updated, the API will display more granular information including `relation` and `terms`:

```
query diseasePheno{
  disease(efoId: "MONDO_0021251") {
    id
    name
    isTherapeuticArea
    synonyms {
      relation
      terms
    }
  }
}
``` 

```
{
  "data": {
    "disease": {
      "id": "MONDO_0021251",
      "name": "endometrium neoplasm",
      "isTherapeuticArea": false,
      "synonyms": [
        {
          "relation": "hasExactSynonym",
          "terms": [
            "endometrial tumor",
            "tumor of endometrium",
            "neoplasm of endometrium",
            "endometrium tumor",
            "endometrium neoplasm (disease)",
            "tumor of the endometrium",
            "endometrial neoplasm",
            "neoplasm of the endometrium"
          ]
        },
        {
          "relation": "hasRelatedSynonym",
          "terms": [
            "endometrial neoplasm"
          ]
        }
      ]
    }
  }
}
```
[Currently working API query](https://hpo-1-0-dot-api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20diseasePheno%7B%0A%20%20disease(efoId%3A%20%22MONDO_0021251%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20isTherapeuticArea%0A%20%20%20%20synonyms%20%7B%0A%20%20%20%20%20%20relation%0A%20%20%20%20%20%20terms%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

There are 4 types of relationships that can be returned by the API attending to different levels of specificity of the synonyms

## Action

We want to update the disease synonyms logic in the FE using the same UI and provide the relation(s) when on-hovering the chips.

In order to achieve this there is one consideration to make. In cases like the example above in which `endometrial neoplasm` can be in more than one category, we want the term to appear once in the UI but listing both categories (`hasExactSynonym, hasRelatedSynonym`) when on-hovering the chip.

Please @andrewhercules and @LucaFumis feel free to raise any question or suggestion

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `beta`
