### ISSUE TITLE
Disease crashing on null phenotypes

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1376]
Count coming as `null`

```
query dis{
  disease(efoId: "HP_0000726"){
    id
    name
    phenotypes{
      count
    }
  }
}
```

```
{
  "data": {
    "disease": {
      "id": "HP_0000726",
      "name": "Dementia",
      "phenotypes": null
    }
  }
}
```

**Comment by d0choa** [comment]
I suspect this is a case in which there are no phenotypes linked.

For consistency, what's the expected behavior @mkarmona ? phenotypes object null or phenotypes.count = 0.

**Comment by d0choa** [comment]
@LucaFumis will handle it as is. Don't worry @cmalangone / @mkarmona

**Comment by cmalangone** [comment]
@LucaFumis and @d0choa 
I fixed a couple of cases : Cancerbiomarker and disease

```
query dis{
  disease(efoId: "HP_0000726"){
    id
    name
    phenotypes{
      count
      rows  {
        phenotypeHPO {
          id
        }
      }
    }
  }
}
```

**Comment by d0choa** [comment]
All functionality rescued. Data is also returned in a more friendly format
