### ISSUE TITLE
Investigate and integrate Google Tag Manager container

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1379]
Currently both the Platform and Genetics Portal use various third-party JavaScript tags to import functionality and features (e.g. Google Analytics' analytics.js, HubSpot, refiner.io). Each of these services require their own tag and might not be relevant to partner or private instances of either tool.

If we switch to Google Tag Manager, we can make use of different third party tags and import directly into a single container. Further information and general installation instructions are available in [the Google Tag Manager documentation](https://support.google.com/tagmanager/answer/6103696). 

Can we please investigate and demo some of the Rect npm modules created to support Google Tag Manager? 

- [react-gtm-module](https://www.npmjs.com/package/react-gtm-module)
- [react-google-tag-manager](https://www.npmjs.com/package/react-google-tag-manager)

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/301
