### ISSUE TITLE
openFDA pipeline writes output in parquet format too

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1380]
Append parquet format as output to the configurator to keep [that generated](gs://open-targets-data-releases/21.02/templates/openfda-application.conf)
- gs://open-targets-data-releases/21.02/templates/openfda-application.conf

**Comment by cmalangone** [comment]
In order to generate parquet files I added the functionality.
https://github.com/opentargets/platform-etl-openfda-faers/pull/23

The files are already available for 21.02 here
```
gs://open-targets-data-releases/21.02/output/etl/openfda-faers
````
