### ISSUE TITLE
Display actionType instead of uniqueActionTypes in Known drugs widgets in profile pages

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1383]
Following the work from @JarrodBaker on #1378, we need to update the 3 known drugs / clinical precedence widgets, from the profile pages.

At the moment, the column `Action Type` displays the content of `uniqueActionTypes` (drug-level). However, the information displayed in the row should rather be about the at the drug-target level. In order to accommodate this information, we need to map the actionType that corresponds to each target from the following response.

CHEMBL425  is a good example of why the uniqueActionTypes was incorrect:

```
query dr{
  drug(chemblId: "CHEMBL425"){
    id
    mechanismsOfAction{
      uniqueActionTypes
      rows{
        mechanismOfAction
        actionType
        targetName
      }
    }
  }
}
```

```
{
  "data": {
    "drug": {
      "id": "CHEMBL425",
      "mechanismsOfAction": {
        "uniqueActionTypes": [
          "INHIBITOR",
          "AGONIST"
        ],
        "rows": [
          {
            "mechanismOfAction": "Arachidonate 5-lipoxygenase inhibitor",
            "actionType": "INHIBITOR",
            "targetName": "Arachidonate 5-lipoxygenase"
          },
          {
            "mechanismOfAction": "Peroxisome proliferator-activated receptor gamma agonist",
            "actionType": "AGONIST",
            "targetName": "Peroxisome proliferator-activated receptor gamma"
          },
          {
            "mechanismOfAction": "Cyclooxygenase inhibitor",
            "actionType": "INHIBITOR",
            "targetName": "Cyclooxygenase"
          }
        ]
      }
    }
  }
}
```

**Comment by d0choa** [comment]
Queries above updated

**Comment by andrewhercules** [comment]
With the action type data now available per target, can we please update the Known Drugs tables on the target and disease/phenotype profile page to show the action type associated with the specific target?  This data is now available from the `drugs.mechanismsOfAction.rows.actionType` field.

For example, on the [PPARG profile page](https://beta--platform-app.netlify.app/target/ENSG00000132170), some of the entries (e.g. Mesalamine) show "AGONIST" and "INHIBITOR"; however, it should only say "AGONIST" based on the API response.

![Screenshot 2021-02-09 at 14 15 12](https://user-images.githubusercontent.com/7490258/107376086-633c1580-6ae1-11eb-9d3c-3b12f1f30b0b.png)

Similarly, on the [ulcerative colitis profile page](https://beta--platform-app.netlify.app/disease/EFO_0000729), the entry for Olsalazine shows both "INHIBITOR" and "AGONIST" for the target ALOX5; however, it should only say "INHIBITOR"

![Screenshot 2021-02-09 at 14 18 13](https://user-images.githubusercontent.com/7490258/107376320-a9917480-6ae1-11eb-8d28-61dc2aa1d575.png)

**Comment by mirandaio** [comment]
Done here https://github.com/opentargets/platform-app/pull/293
