### ISSUE TITLE
CD86 transcripts in Browser view

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#139]
We show CD86-205 in the Browser view as a non-coding transcript (it's a retained intron type of transcript) and coloured in grey, whereas CD86-208, not protein coding too, is shown as processed transcript and coloured in blue.

It's confusing for users and it does not reflect 100% what Ensembl shows:

http://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000114013;r=3:122077844-122103657;t=ENST00000483949

Wouldn't it be better to keep consistent with the names (biotypes) as Ensembl's, so CD86-205 would be retained intron instead of non-coding?

<img width="726" alt="screen shot 2018-09-26 at 19 01 35" src="https://user-images.githubusercontent.com/6472381/46142819-14fb8400-c250-11e8-8714-f766f4c3aaa3.png">

**Comment by MichaelaEBI** [comment]
This issue has been resolved: https://www.targetvalidation.org/target/ENSG00000114013
