### ISSUE TITLE
Drug cross-references not displayed

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1391]
Drug cross-references are not displayed for some molecules (e.g. [MIFAMURTIDE](https://beta--platform-app.netlify.app/drug/CHEMBL2111100))

I suspect the recent work in #1356 is not working when the `crossReferences` field contains a null

```
query dr{
  drug(chemblId: "CHEMBL2111100"){
    id
    crossReferences{
      source
      reference
    }
  }
}
```

```
{
  "data": {
    "drug": {
      "id": "CHEMBL2111100",
      "crossReferences": null
    }
  }
}
```

**Comment by mirandaio** [comment]
Fixed by https://github.com/opentargets/platform-app/commit/faeda4e451d1bdb559448274058f6159f82a509b
