### ISSUE TITLE
Update COVID-19 Target Prioritisation tool front-end with new data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1394]
There is new data for the COVID-19 Target Prioritisation tool, using data from our upcoming 21.02 release - see #1324 for more information.

Based on a review of the notes in #1160 and the [ot_covid19-frontend](https://github.com/opentargets/ot_covid19-frontend) codebase (specifically the [update.js](https://github.com/opentargets/ot_covid19-frontend/blob/master/src/db/update.js) file), the process to refresh the data is:

1. Download the [latest release data in JSON (.zip) format](https://github.com/opentargets/ot_covid19/releases/tag/v1.2)
2. Rename the file to `targets_integrated_data-rev_10.zip`
3. Upload the `.zip` file in the [open-targets-covid-prioritisation](https://console.cloud.google.com/storage/browser/open-targets-covid-prioritisation) bucket
4. Update the [current_revision.json](https://storage.googleapis.com/open-targets-covid-prioritisation/current_revision.json) to be:

```
{
"current_revision": "targets_integrated_data-rev_10"
}
```

Can we please update the data in time for the 21.02 release on Wednesday 17 February?

**Comment by DSuveges** [comment]
Done. All modifications are made.

**Comment by andrewhercules** [comment]
Ticket closed as the COVID-19 Target Prioritisation tool has been updated with the latest 21.02 ddata.

Three things were noted in the deploy process:

1. The file type must be `.zip` as `.gzip` files will not be processed correctly. If the file type in the Google Cloud bucket is `.gzip`, you will see the following console log error:

![Screenshot 2021-02-16 at 11 29 42](https://user-images.githubusercontent.com/7490258/108068035-7f97ff00-7059-11eb-96a1-2ff51d371295.png)

2. The JSON file contained in the `.zip` file must have a `.json` extension. If the file does not have a `.json` extension, you will see the following console log error:

![Screenshot 2021-02-16 at 11 41 36](https://user-images.githubusercontent.com/7490258/108068211-b110ca80-7059-11eb-8568-39a2c6b15c18.png)

3. Google caches the [current_revision.json file](https://storage.googleapis.com/open-targets-covid-prioritisation/current_revision.json) for a default of 3600 seconds, which can cause issues with the console log showing the incorrect version. To fix this, you can re-upload the `current_revision.json` file and adjust the `Cache-Control` metadata and set to `no-cache`.
