### ISSUE TITLE
Migrate to community-approved permalinks when possible in PIS

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1395]
As discussed in #1212, we would benefit from migrating some URLs to more permanent links. Please review our links in platform-input-support and update paths when appropriate.

**Comment by cmalangone** [comment]
hpo_phenotypes: (the release tag the code we need just owl)
    uri: http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa
disease:
      uri: https://github.com/EBISPOT/efo/releases/download/v3.28.0/efo_otar_slim.owl
 hpo: (the release tag the code we need just owl)
      uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
 mondo:
      uri: https://github.com/monarch-initiative/mondo/releases/download/v2021-04-07/mondo.owl

This is the last release config
@d0choa can you please confirm that it is okay this last config?
