### ISSUE TITLE
Updating the output of the COVID-19 data integration pipeline

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1396]
Currently the covid-19 tool creates gzipped compressed json (`targets_integrated_data.json.gz
`) and csv (`targets_integrated_data.csv.gz`). These files are not ready to be digested by the covid frontend. The required steps:

1. Get the current data version from [current_revision.json](https://console.cloud.google.com/storage/browser/_details/open-targets-covid-prioritisation/current_revision.json) and increment.
2. Uncompress the gzipped json into a file: `targets_integrated_data-rev_${VERSION}.json` reflecting the new version
3. Zip compress the json file to `targets_integrated_data-rev_${VERSION}.zip`
4. Upload the zip file to the bucket and update the json with the new version.

The steps 1-3 should be included in the Make file + generation of the new `current_revision.json` file. So without any manual intervention these two files can be directly uploaded into the bucket.

This update required by the elaborate process described under issue #1394

**Comment by andrewhercules** [comment]
Ticket closed as COVD19 Target Prioritisation tool will be deprecated
