### ISSUE TITLE
are microRNAs in the genes' dictionary for text mining?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#140]
User at a workshop expected to see IBD associated with mir21 based on this paper https://www.nature.com/articles/ncomms13507.

No associations for mir21 at all: https://www.targetvalidation.org/target/ENSG00000284190).

We need to check with Europe PMC if microRNAs are included (or not) in their genes dictionary.

We do use this paper as text mining evidence for the association between IBD and VMP1, which overlaps with mir21: https://www.targetvalidation.org/evidence/ENSG00000062716/EFO_0003767?view=sec:literature

![screen shot 2018-09-28 at 15 51 42](https://user-images.githubusercontent.com/6472381/46215954-7b5ad200-c336-11e8-945c-c291c98b0da8.png)

Many microRNAs either don't have associations in our Platform or when they do the evidence is Genetic associations or RNA expression, not text mining.

**Comment by ElaineMcA** [comment]
Confirmed with ePMC that microRNAs are not included.  Closing this ticket as additional work will be scoped and covered under new proposal.
