### ISSUE TITLE
Some of the links on the COVID portal to OT Platform are broken

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1402]
The COVID portal links out to the OpenTargets alpha portal on a number of points, but that host is not up:
* Drugs. Link looks like this: `https://alpha.targetvalidation.org/search?q=ASPIRIN&page=1`

**Comment by andrewhercules** [comment]
Ticket closed as links fixed temporarily to direct users to `beta.targetvalidation.org`.

Note: when new version of Platform is released, all links will need to be updated - see #1449 for more information
