### ISSUE TITLE
Add more obsoleted disease terms to disease dataset

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1404]
A reason for adding obsoleted disease terms to the new disease dataset is to be able to rescue evidence mapped to obsoleted EFO terms.

An example use-case is that ChEMBL has some evidence annotated against `EFO_0000378` - `obsolete_coronary artery disease`.

In the owl file, the term is present, and we correctly exclude it from the final dataset:

```
    <!-- http://www.ebi.ac.uk/efo/EFO_0000378 -->

    <owl:Class rdf:about="http://www.ebi.ac.uk/efo/EFO_0000378">
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <obo:IAO_0100001>http://www.ebi.ac.uk/efo/EFO_0001645</obo:IAO_0100001>
        <efo:obsoleted_in_version>3.24.0</efo:obsoleted_in_version>
        <efo:reason_for_obsolescence>Duplication with http://www.ebi.ac.uk/efo/EFO_0001645</efo:reason_for_obsolescence>
        <rdfs:label>obsolete_coronary artery disease</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
    
```
 
However, we are not including this term `EFO_0000378` to the list of `obsoleteTerms` of the standing coronary artery disease term -> `EFO_0001645`. Ideally we want to do this recursively in the unlikely event there is a chain of obsoleted terms.

```
>>> disease.filter(col("id") == "EFO_0001645").show(1, vertical = True)
-RECORD 0--------------------------------
 id               | EFO_0001645          
 children         | [EFO_1000881, EFO... 
 code             | http://www.ebi.ac... 
 dbXRefs          | [NCIt:C26732, MSH... 
 description      | Narrowing of the ... 
 name             | coronary artery d... 
 obsoleteTerms    | null                 
 ontology         | [false, false, [E... 
 parents          | [MONDO_0000473, E... 
 sko              | null                 
 synonyms         | [, [Coronary Arte... 
 therapeuticAreas | [EFO_0000319, OTA... 
 ancestors        | [OTAR_0000010, MO... 
 descendants      | [EFO_1001483, MON... 
 ```

**Comment by cmalangone** [comment]
Unfortunately the efo slim file ( efo_otar_slim.owl) does not contain the info about obselete term.
The full efo owl file (efo.owl) contains it.
Moreover, we currently retrieve the obsolete term using has_alternative_id.

**Comment by d0choa** [comment]
Waiting for reply from EFO https://github.com/EBISPOT/efo/issues/979

**Comment by d0choa** [comment]
@cmalangone, sample file has been included by Zoe including `obsolete terms` and the `has_disease_location` https://github.com/EBISPOT/efo/issues/979#issuecomment-790737169
We will need to confirm we are happy with the changes before the next EFO release.

**Comment by cmalangone** [comment]
PIS 21.04 generates the obsoleted disease
