### ISSUE TITLE
Add location to disease dataset

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1405]
An interesting information not yet included in the disease dataset is the disease location.

For example, the `psoriasis` term ([EFO_0000676](http://www.ebi.ac.uk/efo/EFO_0000676)) contains information regarding which body part is affected by the disease. In this example, the ontology uses the term `has_disease_location` ([EFO_0000784](http://www.ebi.ac.uk/efo/EFO_0000784)) to map to the body part `zone of skin` ([UBERON_0000014](http://purl.obolibrary.org/obo/UBERON_0000014)). Zoe confirmed this data is stable within EFO.

```
    <!-- http://www.ebi.ac.uk/efo/EFO_0000676 -->

    <owl:Class rdf:about="http://www.ebi.ac.uk/efo/EFO_0000676">
    ...
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.ebi.ac.uk/efo/EFO_0000784"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000014"/>
            </owl:Restriction>
    ...
```

Can we add this information to the dataset in a new field named `location`. I presume it will be an array of ids instead of a single string. Once this is done it would be good to expose it in the API.

We will explore separately the integration of this information in the front-end, probably using the [expression atlas anatogram](https://github.com/ebi-gene-expression-group/anatomogram). Other future applications might relate to using baseline expression for the tissue in the disease of interest.

**Comment by cmalangone** [comment]
@d0choa : the file we use is efo_slim and it seems this info is not avaialble.
Can you please let me know if this is the case?

**Comment by d0choa** [comment]
Waiting for EFO response https://github.com/EBISPOT/efo/issues/981

**Comment by d0choa** [comment]
@cmalangone, Zoe has implemented a version of the slim with disease location on it: https://github.com/EBISPOT/efo/issues/981#issuecomment-785835964

She is waiting for feedback, before pushing it to the next EFO release.

**Comment by cmalangone** [comment]
I am going to add a question in the ticket 981 about synonyms info.
