### ISSUE TITLE
Explore source of mappings between recombinant proteins (drugs) and their natural genes/proteins

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1406]
Certain recombinant proteins (drugs) (e.g. [Insulin](https://beta.targetvalidation.org/drug/CHEMBL1201631) or [glucagon](https://beta.targetvalidation.org/drug/CHEMBL266481))  have also their natural proteins that are valid drug targets (e.g. [insulin](https://beta.targetvalidation.org/target/ENSG00000254647) or [glucagon](https://beta.targetvalidation.org/target/ENSG00000115263)).

It would be good to have a mapping between the naturally occurring proteins and their recombinant equivalents.

After a quick exploration, I was not successful finding this information on ChEMBL, Uniprot or Unichem. DrugBank does contain this information under the `External Links` section (e.g. [Insulin](https://go.drugbank.com/drugs/DB00030) and [glucagon](https://go.drugbank.com/drugs/DB00040)). 

At the moment, we have 455 peptide drugs but only a relative small fraction would fit into this category of naturally occurring peptides. 

```python
>>> drug.filter(col("drugType") == "Protein").select(col("name"), col("id")).count()
455

>>> drug.filter(col("drugType") == "Protein").select(col("name"), col("id")).show(5)
+--------------------+-------------+
|                name|           id|
+--------------------+-------------+
|   GOSERELIN ACETATE|CHEMBL1200501|
|          LANREOTIDE|CHEMBL1201185|
|       ALBUMIN HUMAN|CHEMBL1201451|
|CORTICOTROPIN ZIN...|CHEMBL1201609|
|           LEPIRUDIN|CHEMBL1201666|
+--------------------+-------------+
only showing top 5 rows
```

**Comment by andrewhercules** [comment]
The data displayed in the `External Links` section of a DrugBank drug profile page is available in the [full DrugBank XML download](https://go.drugbank.com/releases/latest). Within the file, there are two different sections where external link data is available: `{http://www.drugbank.ca}external-identifiers` and `{http://www.drugbank.ca}external-links`.

The external UniProt ID mentioned by @d0choa would be found in the `{http://www.drugbank.ca}external-identifiers` section. 

```
# import library to parse XML
import xml.etree.ElementTree as ET

# parse full database and load into memory
tree = ET.parse('data/database.xml')
root = tree.getroot()

# access record for Insulin human (https://go.drugbank.com/drugs/DB00030)
item = tree.getroot()[28]

# set namespace
ns = '{http://www.drugbank.ca}'

# find external identifiers 
db_ext_ids = item.findall('{ns}external-identifiers/{ns}external-identifier'.format(ns = ns))

# iterate through list of external identifiers entry and print object with resource and identifier
for ext_id in db_ext_ids:
    external_id_obj = {}
    external_id_obj['resource'] = ext_id.findtext(ns + 'resource')
    external_id_obj['url'] = ext_id.findtext(ns + 'identifier')
    print(external_id_obj)
```

```
{'resource': 'Drugs Product Database (DPD)', 'url': '20125'}
{'resource': 'Drugs Product Database (DPD)', 'url': '7672'}
{'resource': 'Drugs Product Database (DPD)', 'url': '7671'}
{'resource': 'ChEBI', 'url': '5931'}
{'resource': 'PubChem Substance', 'url': '46506231'}
{'resource': 'KEGG Compound', 'url': 'C00723'}
{'resource': 'KEGG Drug', 'url': 'D03230'}
{'resource': 'GenBank', 'url': 'AY137503'}
{'resource': 'PharmGKB', 'url': 'PA164744571'}
{'resource': 'UniProtKB', 'url': 'Q8HXV2'}
{'resource': 'Therapeutic Targets Database', 'url': 'DAP000802'}
{'resource': 'Wikipedia', 'url': 'Insulin'}
```

Note: this code was adapted from a series of [Python notebooks exploring DrugBank data](https://github.com/dhimmel/drugbank) written by @dhimmel.

**Comment by d0choa** [comment]
@ireneisdoomed could you check with ChEMBL that they don't have this information, before we commit to use it from drugbank.

**Comment by ireneisdoomed** [comment]
Paula from ChEMBL has confirmed to me that although they have an accession for each of the entities, they're stored independently without any mapping or crossref between them.

We could raise this at the monthly meeting this Thursday.

**Comment by d0choa** [comment]
There is a separate problem. ChEMBL and DrugBank don't reference each other for Peptide molecules. I believe it goes outside the scope of Unichem. This makes things even harder

**Comment by d0choa** [comment]
After discussion with @ireneisdoomed, we concluded generating a static mapping file is the best option, due to the lack of references between the relevant resources: ChEMBL, Uniprot and DrugBank. Exploration is concluded and work will follow on #1417.
