### ISSUE TITLE
Font loading issue in Safari

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1409]
As previously discussed, the font does not load properly in Safari.

The next gif was created by emptying the cache and reloading the page: 

![font_issue](https://user-images.githubusercontent.com/5097586/108563366-4087d900-72f9-11eb-8d83-b16b6bb7d090.gif)

@andrewhercules feel free to re-assign when appropiate

**Comment by andrewhercules** [comment]
Based on a preliminary assessment of the issue, we have two options:

1. We can change the `npm` package as the [GitHub page for `typeface-inter`](https://github.com/ajmalafif/typeface-inter) states that the Typefaces project has been deprecated and replaced with [FontSource](https://github.com/fontsource/fontsource).

2. We can use Google Fonts to import [Inter](https://fonts.google.com/specimen/Inter) via CDN or download the font files and integrate into the codebase. We would need to ensure that we import the different weights used throughout the `platform-app` - see [Google Fonts documentation](https://developers.google.com/fonts/docs/css2) for more information

Once a decision has been made on how to import the font, please ensure that the [theme.js](https://github.com/opentargets/platform-app/blob/main/src/theme.js) and [index.scss](https://github.com/opentargets/platform-app/blob/main/src/index.scss) files have the correct fall-back fonts and default to the system-installed `sans-serif` font.

Please use BrowserStack to test that the fonts are correctly loaded for different browsers and operating systems.

**Comment by mirandaio** [comment]
This is happening in other browsers as well.
