### ISSUE TITLE
missing association based on text mining evidence 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#141]
User at a workshop expected to see an association between PDCD4 and IBD based on this paper: https://www.ncbi.nlm.nih.gov/pubmed/23224068

We do use this paper to associate PDCD4 with dysplasia:
https://www.targetvalidation.org/evidence/ENSG00000150593/EFO_0008501?view=sec:literature

We may need to go back to the text mining algorithm and find out how the co-occurence between PDCD4 and IBD can be picked up.

p.s. note, there is no EFO term for carcinogenesis.

**Comment by MichaelaEBI** [comment]
This might be useful: the EuropePMC website allows exploration of the text mining evidence for Open Targets: https://europepmc.org/abstract/MED/23224068?fromSearch=singleResult&fromQuery=23224068 From this becomes somewhat obvious why the association with IBD has been 'missed'. For example, the paper always talk about IBD-associated dysplasia.

**Comment by MichaelaEBI** [comment]
The OTAR2056 Literature project will improve target-disease association identification based on text mining, NLP and machine learning.
