### ISSUE TITLE
Define datatypes in ETL configuration and modify current datatypes

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1410]
At the moment, the ETL uses the field named `datatypeId` to define the datatypes based on the evidence. This information is more relative to the datasource rather than each of the pieces of evidence. Also, in order for us to change the datatypeIds, we require to interact with providers and parsers which is slow and tedious.

Instead, I want to propose to configure which datasource belongs to which datatypes in the ETL configuration file. This change will allow to iterate much quicker on current and future datasources.

Apart from including the necessary logic, we also have the need to modify the current datatypes. @iandunham pointed that the beta version of the platform lists 2 different datatypes ("Genetic associations (variants)" and "Genetic associations (genes") aka `genetic association` and `genetic literature` ) when the previous pipeline only showed 1 ("Genetic associations"). I found that the reason is that the datatypes where [modified in the data_pipeline](https://github.com/opentargets/data_pipeline/blob/13763f31d6d5d8229da943a22715656949493743/mrtarget/common/EvidenceString.py#L187) to merge `genetic_literature` and `genetic_association`. After discussion with Ian, we agreed this is the best definition of datatypes.

If we are able to configure which datasources belong to which datatypes, the desired configuration would be the next:

```
+------------------+-------------------+
|          sourceID|               type|
+------------------+-------------------+
|ot_genetics_portal|genetic_association|
|               eva|genetic_association|
|    phewas_catalog|genetic_association|
|       eva_somatic|   somatic_mutation|
|uniprot_literature|genetic_association|
|           clingen|genetic_association|
|         phenodigm|       animal_model|
|           intogen|   somatic_mutation|
|  genomics_england|genetic_association|
|          reactome|   affected_pathway|
|  expression_atlas|     rna_expression|
|           progeny|   affected_pathway|
|cancer_gene_census|   somatic_mutation|
|            sysbio|   affected_pathway|
|            chembl|         known_drug|
|    gene2phenotype|genetic_association|
|         europepmc|         literature|
|        slapenrich|   affected_pathway|
|            crispr|   affected_pathway|
+------------------+-------------------+
```

**Comment by mkarmona** [comment]
@d0choa this PR makes the ETL franken-robust to `datatypeId`. So the logic is

1. if no data type id in the raw data source then data type id will be `other`
2. if there is a data type id coming in the raw evidence will remain in place
3. but if there is a `datatype-id` field in the configuration for that data source it will replace by the original

The logic is somehow bullet-proof as no matter what you do you will end up with a data type id.
