### ISSUE TITLE
Update Molecular Interactions widget UI

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1412]
To prepare for the release of the Molecular Interactions widget in the 21.04 release, we should adjust some of the UI elements to improve the usability of the widget.

Further details TBC

[Notes from preliminary UX and data review](https://docs.google.com/document/d/1nDn2crtAVVGqyiEkMFkf2FSzor9U-QKNwvcGTdOz71M)

**Comment by LucaFumis** [comment]
Prioritised items have been addressed. Pending PR review (unfortunately it's a very long PR though).

**Comment by andrewhercules** [comment]
Ticket closed as work completed and reviewed and merged into `main`
