### ISSUE TITLE
Capture changes in evidence schema/data originated on evidence migration tasks

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1413]
Please EDIT the next list to include all changes in schema and/or data that originated while developing the json schema or during the evidence migration process.

## List of changes

- `pathwayId` is now an array (`pathways`) containing structs of the type `{ id: XXX, name: XXX}` (reactome)
- New fields: `beta`, `betaConfidenceIntervalLower`, `betaConfidenceIntervalUpper` (for genetics portal evidence)
- Renamed fields: `oddsRatioConfidenceIntervalLower`, `oddsRatioConfidenceIntervalUpper` (formerly `confidenceIntervalLower` and `confidenceIntervalUpper`) (genetics portal)
- **New datasource**: `uniprot_variants`. See [schema](https://github.com/opentargets/json_schema/blob/4608417d0f745046c98a0491d9bb27c481d07b5f/opentargets.json#L874) to see what fieds we are getting. And to see what fields are to be shown on frontend.  Score is coming from resourceScore and we want to include `variantRsId` as an unique field.
- (to be completed)

## At a later stage

- Compare the 2 schemas (old vs new), but this is unlikely to pick the data changes (from null to non-null).
- BE: Include `diseaseFromSourceId` as a UAF in the [config file](https://github.com/opentargets/platform-etl-backend/blob/cbc31e167edf5f8a889628aa01ea87b6abbb8230/src/main/resources/reference.conf) for `PheWAS`.
- BE: PIS needs to now get the ClinGen evidence file from `gs://otar000-evidence_input/ClinGen/json`, instead of `gs://otar000-evidence_input/ClinGen`
- Specify what requires BE and FE work

**Comment by ireneisdoomed** [comment]
The work on the changes to be done by BE are described and tracked in this document:

https://docs.google.com/document/d/1ws_cCtdXXg67L3yOVsTxtGgnMFdESB5ZRM1qk1mR1KI/edit
