### ISSUE TITLE
Genetics portal evidence - include beta and corresponding standard error

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1414]
GWAS evidence sourced from the OT genetics portal contains association parameters: 
* Sample size
* p-value
* Odds ratio
* Standard error

Associations run on continuous traits however don't have odds ratio, instead the effect size is measured in beta. The relevant data table in OT genetics contains this information, however not yet extracted. This should also be added the evidence string and the relevant fields in the json schema should also be added.

**Required Actions:**

- [x] Update evidence parser
- [x] Update JSON schema
- [ ] Update ETL if necessary 
- [ ] Update frontend to show new columns

**Comment by d0choa** [comment]
tasks will continue in #1413
