### ISSUE TITLE
Refactor and merge OpenFDA pipeline with main ETL

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1416]
Given the similarities and redundancy, we are getting after the implementation of the main ETL pipeline we need to refactor and merge the [openfda](https://github.com/opentargets/platform-etl-openfda-faers) into [ETL](https://github.com/opentargets/platform-etl-backend).
Something is worth keeping with this is doing paired with #1415 .

**Comment by mbdebian** [comment]
This is done.
