### ISSUE TITLE
Implement ChEMBL target class in new ETL

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1422]
As part of the work in refactoring the target ETL, we want to include the ChEMBL target class field inside the target object. This is an action to ensure backwards compatibility to the association faceting by target class.

Based on my understanding, the data is retrieved from files PIS retrieves from ChEMBL API:
- https://www.ebi.ac.uk/chembl/api/data/protein_class.json
- https://www.ebi.ac.uk/chembl/api/data/target_component.json
A first action, would be to identify if these can be retrieved directly from ChEMBL ES. 

`protein_class.json` contains the different classes by `protein_class_id`

```
  "protein_classes": [
    {
      "l1": "Enzyme",
      "l2": null,
      "l3": null,
      "l4": null,
      "l5": null,
      "l6": null,
      "l7": null,
      "l8": null,
      "protein_class_id": 1
    },
    {
      "l1": "Adhesion",
      "l2": null,
      "l3": null,
      "l4": null,
      "l5": null,
      "l6": null,
      "l7": null,
      "l8": null,
      "protein_class_id": 2
    },
 ```
 
`target_component.json` contains the annotation of each target target component.
Both datasets can be mapped using `accession` and `protein_classification_id` == `protein_class_id `.
The current target object has the information in the next shape:

```
 |    |-- classes: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- l1: struct (nullable = true)
 |    |    |    |    |-- id: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- l2: struct (nullable = true)
 |    |    |    |    |-- id: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- l3: struct (nullable = true)
 |    |    |    |    |-- id: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- l4: struct (nullable = true)
 |    |    |    |    |-- id: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- l5: struct (nullable = true)
 |    |    |    |    |-- id: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- l6: struct (nullable = true)
 |    |    |    |    |-- id: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
```
 
Instead, we want a data model like the next one:

```
|-- targetClass: array (nullable = true)
|    |-- element: struct (containsNull = true)
|   |    |-- level: long (nullable = true)
|   |    |-- label: string (nullable = true)
|   |    |-- id: long (nullable = true)
```

**Comment by dhimmel** [comment]
I was able to [process](https://github.com/related-sciences/nxontology-data) the PubChem export into Python's networkx / [nxontology](https://github.com/related-sciences/nxontology). Can read this in Python like:

```python
from nxontology import NXOntology
url = "https://github.com/related-sciences/nxontology-data/raw/71cf538dc5c258ada880d58663b0205b7b7f8561/087_chembl_target_tree.json"
nxo = NXOntology.read_node_link_json(url)
```

Running `nxo._get_name_to_node_info()` logs the following warnings about nodes with duplicate names:

```
Node name duplicated for nodes 500 & 501: 'N-formyl methionyl peptide receptor'
Node name duplicated for nodes 535 & 536: 'Glycohormone receptor'
Node name duplicated for nodes 541 & 542: 'Protease-activated receptor'
Node name duplicated for nodes 583 & 584: 'Parathyroid hormone receptor'
Node name duplicated for nodes 585 & 586: 'Vasoactive intestinal peptide receptor'
Node name duplicated for nodes 587 & 588: 'Corticotropin releasing factor receptor'
Node name duplicated for nodes 592 & 593: 'Calcium sensing receptor'
```

Something perhaps to be aware of. Also would like to get in touch with ChEMBL to learn more, so please let me know if you're aware of the right contact there.

**Comment by d0choa** [comment]
Sorry for the slow response @dhimmel. I shared your comments with ChEMBL. Hopefully they will get back to you soon

**Comment by d0choa** [comment]
ChEMBL came back with some comments:

> The ChEMBL protein family classification is a bespoke classification, reflecting some of the preferred or widely used community classifications for different protein families. It does not aim to be comprehensive, but is focussed around the main families that have been historically important for drug discovery. The classification is maintained manually, with new classes being added as/when needed (usually when a significant number of targets in a particular family appear in ChEMBL, or where they are of particular significance e.g., targets of approved drugs/candidates).
> 
> Kinases - [Manning et al kinome paper](https://doi.org/10.1126/science.1075762)
> GPCRs - [Guide to Pharmacology/IUPHAR](https://www.guidetopharmacology.org/GRAC/ReceptorFamiliesForward?type=GPCR), GPCRDB
> Transporters - [Mostly from TCDB](https://www.tcdb.org/browse.php)
> Epigenetic  - domain-based classification from [SGC Chromohub](https://chromohub.thesgc.org/static/ChromoHub.html) (many epigenetic proteins have multiple domains, so multiple classifications)
> Proteases - [MEROPS](https://www.ebi.ac.uk/merops/)
> Enzymes – EC number
> UniProt keywords may have been used to classify other groups e.g. secreted proteins.
> 

They commented the classification could be better maintained and it might not reflect the most modern targets.

We will include this in the Platform documentation for future reference cc @HelenaCornu

**Comment by dhimmel** [comment]
Thanks @d0choa. ChEMBL's response is helpful to wrt which sources are used to construct the taxonomy. Perhaps I can follow up directly with ChEMBL with some of my more data related questions. Is there a GitHub repo / email address / other method of contact that is best?
