### ISSUE TITLE
Propose alternative target safety information schema 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1425]
As part of the target dataset work, we want to re-structure the hyper-normalised safety object.

At the moment, the 3 main objects `adverse_effects`, `safety_risk_info` and `experimental_toxicity` reflect 3 different datasources. This is not an adequate data modelling as the source is not a reason to structure the information. In fact it can be seen that some fields such as `organs_systems_affected` are repeated in the schema in multiple locations, which is not a good symptom.

The plan is to explore with the support of @BZdrazil an alternative schema that might better accommodate the currently available safety information.

```
 |-- safety: struct (nullable = true)
 |    |-- adverse_effects: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- inhibition_effects: struct (nullable = true)
 |    |    |    |    |-- acute_dosing: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |    |-- chronic_dosing: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |    |-- developmental: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |    |-- general: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |-- unspecified_interaction_effects: array (nullable = true)
 |    |    |    |    |-- element: string (containsNull = true)
 |    |    |    |-- organs_systems_affected: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |-- activation_effects: struct (nullable = true)
 |    |    |    |    |-- acute_dosing: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |    |-- chronic_dosing: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |    |-- general: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |-- references: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |    |    |-- ref_label: string (nullable = true)
 |    |    |    |    |    |-- ref_link: string (nullable = true)
 |    |-- safety_risk_info: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- organs_systems_affected: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- code: string (nullable = true)
 |    |    |    |    |    |-- mapped_term: string (nullable = true)
 |    |    |    |    |    |-- term_in_paper: string (nullable = true)
 |    |    |    |-- safety_liability: string (nullable = true)
 |    |    |    |-- references: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |    |    |-- ref_label: string (nullable = true)
 |    |    |    |    |    |-- ref_link: string (nullable = true)
 |    |-- experimental_toxicity: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- data_source: string (nullable = true)
 |    |    |    |-- data_source_reference_link: string (nullable = true)
 |    |    |    |-- experiment_details: struct (nullable = true)
 |    |    |    |    |-- assay_description: string (nullable = true)
 |    |    |    |    |-- assay_format: string (nullable = true)
 |    |    |    |    |-- assay_format_type: string (nullable = true)
 |    |    |    |    |-- cell_short_name: string (nullable = true)
 |    |    |    |    |-- tissue: string (nullable = true)
```

**Comment by ireneisdoomed** [comment]
In this document we will be tracking the progress on the modelling: 
https://docs.google.com/spreadsheets/d/1W_KJoozote06h3-mrVeHZN02VVXrpwG42nhGjUR-0Gk/edit?usp=sharing

**Comment by ireneisdoomed** [comment]
## iter 5 

After the revision of v16 and a meeting with Barbara ([notes](https://docs.google.com/document/d/1ZqJzqzmtQZtCL4XibRYfXfPWWm7WBzeY8ZAdBmcouFk/edit#heading=h.sv0t2lgq60yt)), I've made some updates to the schema that make the data comparable and streamlined.

-  We will be dropping eTOX for now until this source can be adapted to the schema
-  Experimental toxicity will only consist of Tox21 data, now called `ToxCast` after the recuration of the dataset.
-  ToxCast is no longer parsed from the experimental toxicity spreadsheet. This dataset is and will be generated by the datateam and will live here `gs://otar001-core/ExperimentalToxicity`. The latest file is `ToxCast_2021-08-11.tsv`
- All the fields correspondence from ToxCast to the schema are described in the schema tracker: https://docs.google.com/spreadsheets/d/1W_KJoozote06h3-mrVeHZN02VVXrpwG42nhGjUR-0Gk/edit#gid=1070448726
- I have done the same job for the rest of the data sources so that BE has clearer instructions. It is also easier for me to debug the dataset.
- An event and eventId need to be assigned to Force, Lamore and HeCaToS. This is also explained in the spreadsheet, but a summary would be. The case for HeCaToS might be trickier to parse:
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/6ca736b7-7895-4521-9e84-9fabbd4f5da9)
- We are dropping the `url` field. As these can be hardcoded, I will indicate FE to reference them so that a pipeline run is not needed in case the URL is changed.
- I have updated and revised the uniqueness of the fields, they are stated in the `Unique` column. @JarrodBaker, please let me know if you find any situation where explosion is not desirable.

**Comment by ireneisdoomed** [comment]
### Update
As discussed with @JarrodBaker:
- [X] I have moved the files previously available at `gs://otar001-core/ExperimentalToxicity`to `gs://otar001-core/TargetSafety/data_files`. The filename that PIS will need to pick from this folder follows the pattern: `ToxCast_YYYY-MM-DD.tsv`
- [X] I have added a new column to the ToxCast dataset: `efoId` is now equal to an empty string as a placeholder. This column will contain the EFO ID resulting from mapping `biological_process_target` to EFO. The correspondence of this field to the schema has been updated in the [schema tracker](https://docs.google.com/spreadsheets/d/1W_KJoozote06h3-mrVeHZN02VVXrpwG42nhGjUR-0Gk/edit#gid=1070448726) as well.

As a side note: there is an open issue to EFO ([#1217](https://github.com/EBISPOT/efo/issues/1217)) to import to EFO the GO terms that describe all the possible biological processes existing in the ToxCast dataset.

**Comment by ireneisdoomed** [comment]
The schema for the target safety annotation has been freezed as of [iter 5](https://docs.google.com/spreadsheets/d/1W_KJoozote06h3-mrVeHZN02VVXrpwG42nhGjUR-0Gk/edit#gid=578682516), and is within scope to use it in our forthcoming release.

We plan to expand the schema in future iterations, as we integrate more datasets - for example, the AOPWiki one (more on [#1442](https://github.com/opentargets/platform/issues/1442)).

For now, I consider this work as done.
