### ISSUE TITLE
Create new publications drawer

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1427]
Within the Platform, many of our evidence strings are backed by publications with a PubMed ID. Currently, we display either:

- The single PubMed ID if there is only 1 publication
- A link labelled `x entries` that opens the publications drawer, which displays the list of PubMed IDs

For example, the screenshot below shows both implementations found in the Reactome section on the evidence page for [CFTR and cystic fibrosis](https://beta.targetvalidation.org/evidence/ENSG00000001626/Orphanet_586)

![Screenshot 2021-03-04 at 12 21 23](https://user-images.githubusercontent.com/7490258/109963305-2af4b500-7ce4-11eb-8276-88a03cdfaeaf.png)

To improve usability of the publications drawer, we would like to call the Europe PMC API and use their `search` endpoint to retrieve the publication citation and abstract - see [example query](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:32569671%20OR%20ext_id:33129112%20OR%20ext_id:33186889%20OR%20ext_id:32248739%20OR%20ext_id:32541922%20OR%20ext_id:32615091%20OR%20ext_id:32467321%20OR%20ext_id:33171331%20OR%20ext_id:32720736%20OR%20ext_id:32720736&format=json&resultType=core&pageSize=10). This would be similar to we offer in the Text Mining section on the evidence page.

There is considerable variability of the number of publications found in a single evidence string. For example, we have 4 evidence strings from Cancer Gene Census that build the association between [EGFR and lung adenocarcinoma](https://beta.targetvalidation.org/evidence/ENSG00000146648/EFO_0000571) and the number of publications range from 2 to [630](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20%7B%20target%28ensemblId%3A%22ENSG00000146648%22%29%7B%20approvedSymbol%20approvedName%20evidences%28efoIds%3A%5B%22EFO_0000571%22%5D%2C%20datasourceIds%3A%20%5B%22cancer_gene_census%22%5D%29%7B%20count%20rows%7B%20literature%20%7D%20%7D%20%7D%20%7D).

![Screenshot 2021-03-04 at 12 15 53](https://user-images.githubusercontent.com/7490258/109962953-c0dc1000-7ce3-11eb-9b10-dc1e4ac9a65d.png)

To ensure that we do not overload the Europe PMC API, we should apply some front-end logic where we restrict the number of publications shown to 10 and only query the Europe PMC API for 10 records at a time. This is similar to what we currently do with the classic version of the Platform - see [EGFR and lung cancer in the classic view](https://www.targetvalidation.org/evidence/ENSG00000146648/MONDO_0008903?view=sec:literature) along with the [Europe PMC API query for the first 10 results](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:32569671%20OR%20ext_id:33129112%20OR%20ext_id:33186889%20OR%20ext_id:32248739%20OR%20ext_id:32541922%20OR%20ext_id:32615091%20OR%20ext_id:32467321%20OR%20ext_id:33171331%20OR%20ext_id:32720736%20OR%20ext_id:32720736&format=json&resultType=core&pageSize=10).

While this component would initially be used within the drawer component on the evidence page, the title/citation/abstract style could be adapted for the Text Mining evidence section and the Bibliography sections on the profile pages.

**Comment by andrewhercules** [comment]
@carcruz, the [publications drawer design specification](https://docs.google.com/presentation/d/1iKfHhXyx3SKlzzrl1wWvcX0y5VcbQLFZXOkFOnp8a3A) has been updated to reflect different scenarios and different user interactions.

### API response and data review

In reviewing the data for the EGFR and lung adenocarcinoma association - specifically [the row in the Cancer Gene Census data table with 630 publications](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20%7B%20target%28ensemblId%3A%22ENSG00000146648%22%29%7B%20approvedSymbol%20approvedName%20evidences%28efoIds%3A%5B%22EFO_0000571%22%5D%2C%20datasourceIds%3A%20%5B%22cancer_gene_census%22%5D%29%7B%20count%20rows%7B%20literature%20%7D%20%7D%20%7D%20%7D) - there can be publications with a PubMed ID that also match IDs used by other types of publications. 

For example, the ID `2540` matches a publication and a thesis ([API response](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:2540&format=json&resultType=core&pageSize=10)).

Based on the [Europe PMC API documentation](https://europepmc.org/docs/EBI_Europe_PMC_Web_Service_Reference.pdf), we should be able to set `src:MED` in our API call to restrict to MedLine and PubMed. However, the `src:MED` parameter does not appear to work with multiple query IDs ([example 1](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:2540%20src:MED%20OR%20ext_id:32720736&format=json&resultType=core&pageSize=10) or [example 2](https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:2540%20src:MED%20OR%20ext_id:32720736%20src:MED&format=json&resultType=core&pageSize=10)).

Instead, it appears that we may need to filter the response and only show the `"source": "MED"` entries. I do not know how widespread this issue is, but can we please ensure that we only use Europe PMC API response data where `"source": "MED"`?

### Design spec - user opens the publications drawer

When user opens the publications drawer, please show up to 10 publications with the title, author list, year, volume, issue, and page numbers, using the citation and visual style found in the existing Text Mining and Bibliography sections.

After the first 10 publications, please include a button that allows users to view the next 10 publications.

![Publications Drawer Design Specification](https://user-images.githubusercontent.com/7490258/110637036-e5812d80-81a4-11eb-9db6-02353f9963dc.jpg)

Underneath each publication entry, please include a "Show abstract" button with a [plus-square](https://fontawesome.com/icons/plus-square?style=regular) icon that users can click to view the abstract. 

Within the Europe PMC API response, if it flags:
- `"isOpenAccess": "Y"` - please display the [unlock-alt](https://fontawesome.com/icons/unlock-alt?style=solid) icon and the label "Open Access"
- `"inEPMC": "Y"` or `"inPMC": "Y"` - please display the [file-alt](https://fontawesome.com/icons/file-alt?style=regular) icon and the label "Full Text Available" 

If there is no abstract returned by the Europe PMC API, please disable the "Show Abstract" button and colour the button, icon, and text in light grey - `#e0e0e0` 

![Publications Drawer Design Specification (2)](https://user-images.githubusercontent.com/7490258/110637138-fe89de80-81a4-11eb-977b-7335a456e8b4.jpg)


### Design spec - user clicks the "Show Abstract" button

On-click, please change the button text to "Hide Abstract" and the icon to [minus-square](https://fontawesome.com/icons/minus-square?style=regular)

![Publications Drawer Design Specification (1)](https://user-images.githubusercontent.com/7490258/110637095-f3cf4980-81a4-11eb-8e49-42d286ac99aa.jpg)

**Comment by d0choa** [comment]
sounds good. Let me know if you don't hear from them in a couple of days

**Comment by andrewhercules** [comment]
The Europe PMC team have responded - see below:

> /search endpoint has a limit of 1000 characters including booleans for a single request. Therefore it would be better to use the POST method for a longer query since it does not have the same limit. Please remember to set the pageSize parameter to 1000. Note that the syntax for multiple PMID searches is SRC:MED AND (EXT_ID:12458655 OR EXT_ID:16046457 OR EXT_ID:12458656) for a search of three PMIDS. The /search API query looks like this: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=SRC:%22MED%22%20AND%20(EXT_ID:12458655%20OR%2016046457%20OR%2012458656).
> 
> I also want to mention that we have an open source component that supplies a widget to display citations details in a web site, if that's helpful. Please see https://github.com/EuropePMC/biojs-vis-pmccitation.
> 
> You may find it useful to join our Developer Forum, where you can discuss using the APIs with Europe PMC developers and fellow users: https://groups.google.com/a/ebi.ac.uk/forum/#!forum/epmc-webservices

Based on their response, I think a `POST` request would be best given the limit of 1000 characters with a `GET` request. @ireneisdoomed analysed the Platform evidence and the evidence string from Cancer Gene Census for lung adenocarcinoma and EGFR has the largest number of PubMed IDs (630). We should be able to set the `pageSize` parameter to `1000` and set the `sort` parameter to `P_PDATE_D` to retrieve all publications sorted by publication date (most recent first). This would allow Platform users to search and sort the results.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and reviewed and merged into `main`
