### ISSUE TITLE
Blank content when searching in table component while in page > 1

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1428]
When searching in table component while in pages that are not the first one, there is a risk of running out of options in the given page.

As discussed in the past, we would like the table component to go to page 1 as soon as a user starts typing in the search box.

**Comment by mirandaio** [comment]
Tables that have this issue:
- Safety https://beta.targetvalidation.org/target/ENSG00000091831
- Clinical signs and symptoms https://beta.targetvalidation.org/disease/Orphanet_586
