### ISSUE TITLE
Harmonize ontology mapping process

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#143]
In several places, we have subtly different processes for ontology mapping from string (e.g. OnToma vs evidence_datasource_parsers).

These should be harmonised into one place for consistency, and maintainability.

**Comment by afaulconbridge** [comment]
opentargets/platform#357 is partially related - we should ensure the feedback process is harmonized too

**Comment by afaulconbridge** [comment]
Moving under "Roadmap: Harmonize evidence_datasource_parsers" opentargets/platform#535

**Comment by d0choa** [comment]
Additional information about how every datasource implements the mapping can be found here:
https://docs.google.com/spreadsheets/d/1vtDB7reA8-IDcgJSqjoL5e_JkyqY8728XVYnJW-qBj4/edit#gid=0

Harmonisation will be part of the new data submission guidelines. We'll generate tickets accordingly
