### ISSUE TITLE
Fix publications link in Mouse Phenotypes type

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1431]
Users testing the `Beta` release have reported two issues with the publications links in the Mouse Phenotypes section. These issues occur when there are no publications or when there is more than 1 publication. 

### No publications

For some targets (e.g. [PAPPA](https://beta.targetvalidation.org/target/ENSG00000182752)), the `pubMedId` string is blank - see the [GraphQL API response](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20mousePhenotypes%7B%20target%28ensemblId%3A%22ENSG00000182752%22%29%7B%20mousePhenotypes%7B%20phenotypes%7B%20genotypePhenotype%7B%20pubmedId%20%7D%20%7D%20%7D%20%7D%20%7D) for more information. However, the UI still shows "1 publications" and a broken link to Europe PMC.

Instead, if there are no publications returned by the GraphQL API, please show `N/A`.

![Screenshot 2021-03-15 at 09 46 31](https://user-images.githubusercontent.com/7490258/111134328-69576300-8573-11eb-8379-0195fddcb22b.png)

### Multiple publications

For some targets (e.g. [ESR1](https://beta.targetvalidation.org/target/ENSG00000091831)), the `pubMedId` string returns a pipe-separated string list of publications - see the [GraphQL response](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20mousePhenotypes{%20target(ensemblId:%22ENSG00000091831%22){%20mousePhenotypes{%20phenotypes{%20genotypePhenotype{%20pubmedId%20}%20}%20}%20}%20}) for more information. However, the UI still shows "1 publications" and a broken link to Europe PMC.

Instead, please separate the string by `|` and use the resulting list of PubMed IDs to link to Europe PMC. Please also display the correct number of publications (e.g. "3 publications")

![Screenshot 2021-03-15 at 09 51 24](https://user-images.githubusercontent.com/7490258/111134952-05816a00-8574-11eb-874c-f1156bd578ca.png)

**Comment by ktsirigos** [comment]
Please also make sure that **1 publications** is changed to **1 publication** when applicable.

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/312
