### ISSUE TITLE
Fix ProbeMiner link in Chemical Probes section

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1432]
Users testing the `Beta` version have reported that the ProbeMiner link is broken and directs users to the `Beta` release homepage.

![Screenshot 2021-03-15 at 09 55 04](https://user-images.githubusercontent.com/7490258/111135424-8c364700-8574-11eb-8c0e-f1a56a3591ab.png)

Can we please update the ProbeMiner link to use the `target.chemicalProbes.probeminer` value returned by the GraphQL API?

Example GraphQL queries:
- [MAT2A](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20probeMiner%7B%0A%20%20target%28ensemblId%3A%22ENSG00000168906%22%29%7B%0A%20%20%20%20chemicalProbes%7B%0A%20%20%20%20%20%20probeminer%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
- [ADAM33](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20probeMiner%7B%0A%20%20target%28ensemblId%3A%22ENSG00000168906%22%29%7B%0A%20%20%20%20chemicalProbes%7B%0A%20%20%20%20%20%20probeminer%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
- [PTEN](http://platform-api-beta.opentargets.io/api/v4/graphql/browser?query=query%20probeMiner%7B%0A%20%20target%28ensemblId%3A%22ENSG00000171862%22%29%7B%0A%20%20%20%20chemicalProbes%7B%0A%20%20%20%20%20%20probeminer%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by mirandaio** [comment]
Done here https://github.com/opentargets/platform-app/pull/311
