### ISSUE TITLE
Update links and icons in footer component

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1433]
To prepare for a full production release of the new version of the Platform, we should update the footer component.

Can we please update the footer component to look like the specification below? Please pay particular attention to the layout and responsiveness of the component to prevent overlapping content and content overflow issues. 

![Screenshot 2021-03-15 at 10 46 59](https://user-images.githubusercontent.com/7490258/111141732-ca833480-857b-11eb-9298-dc671ce02da8.png)

**About**

| Label | Link | Note |
| --- | --- | --- |
| Platform version: 1.0.0 | `https://github.com/opentargets/platform-app/releases/tag/` + `releaseVersion`  | Display version number based on GitHub release number |  
| Data release: 21.04 | _Link TBC_ | |
| Community forum | `https://community.opentargets.org` | |
| Privacy notice | `https://www.ebi.ac.uk/data-protection/privacy-notice/open-targets` | |
| Terms of use | `https://docs.targetvalidation.org/terms-of-use` | | 

**Help**

| Label | FontAwesome icon | Link |
| --- | --- | --- |
| Documentation | `fas fa-question-circle` | `https://docs.targetvalidation.org` |
| helpdesk@opentargets.org | `fas fa-envelope` | `mailto:helpdesk@opentargets.org` | 

**Follow us**

| FontAwesome icon | Link |
| --- | --- |
| `fab fa-discourse` | `https://community.opentargets.org` |
| `fab fa-twitter` | `https://twitter.com/opentargets` | 
| `fab fa-linkedin-in` | `https://www.linkedin.com/company/open-targets` |
| `fab fa-github` | `https://github.com/opentargets` |
| `fab fa-youtube` | `https://www.youtube.com/opentargets` |

**Partners**

| Label | Link |
| --- | --- |
| Bristol Myers Squibb | `https://www.bms.com` |
| EMBL-EBI | `http://www.ebi.ac.uk` |
| GSK | `http://www.gsk.com` |
| Sanofi | `https://www.sanofi.com` |
| Wellcome Sanger Institute | `http://www.sanger.ac.uk` |

**Open Targets**

| Label | Link |
| --- | --- |
| Science | `https://www.opentargets.org/science` |
| Publications | `https://www.opentargets.org/publications` |
| Genetics Portal | `https://genetics.opentargets.org` |
| Jobs | `https://www.opentargets.org/jobs` |
| Blog | `https://blog.opentargets.org` |

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/317
