### ISSUE TITLE
Fix bug in data downloads on associations pages where filters have been applied 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1435]
A user has contacted the helpdesk with a bug report that relates to the data download functionality on the associations page. 

After applying a series of filters, the user attempted to download the file in CSV, TSV, and JSON formats. However, the downloaded file contains all of the associations and not the ones filtered and shown in the UI. 

This behaviour was noted on both the target and disease/phenotype associations pages.

### Screenshots

**Filters applied on SOCS1 associations page**
![Screenshot 2021-03-16 at 09 41 49](https://user-images.githubusercontent.com/7490258/111288225-e64e0f80-863b-11eb-854d-792f0cc4be70.png)

**CSV downloaded after applying filter on SOCS1 associations page**
![Screenshot 2021-03-16 at 09 42 11](https://user-images.githubusercontent.com/7490258/111288237-e817d300-863b-11eb-96d1-1bea27d1f65f.png)

### Examples

**[Wilson Disease - Orphanet_905](https://beta.targetvalidation.org/disease/Orphanet_905/associations)**
- Selected "Drugs" in the "Data Types" filter, which returns 3 associations 
- Expecting a CSV/TSV/JSON with 3 associations
- Downloaded file contains all 236 associations 

**[SOCS1 - ENSG00000185338](https://beta.targetvalidation.org/target/ENSG00000185338/associations)** 
- Selected "Cardiovascular disease" in the "Therapeutic Areas" filter, which returns 36 associations
- Expecting a CSV/TSV/JSON with 36 associations
- Downloaded file contains all 562 associations

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/316
