### ISSUE TITLE
Include drug warnings dataset

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1436]
Following the conversation on #1419, ChEMBL has made available a new dataset/endpoint in ChEMBL 28. This dataset is very relevant for our work on target safety. It reports drug withdrawals and black box warnings in a nicely structured dataset.

We want to:

1- Include the ChEMBL drug warnings data as described in #1419 in a new dataset different from our drug index. We are ok with the data structure as it is in ChEMBL. The only addition we want to make is to add an extra field with the `warning_class` mapped to the respective MedDRA id using the same mapping the FAERS data currently has. It should result into something similar to the next table:

![image](https://user-images.githubusercontent.com/5097586/111290643-43e35b80-863e-11eb-98ad-70164e4fdabb.png)

There is a degree on uncertainty about the parent/child propagation. In ChEMBL, warnings are propagated from children to parents. But we don't know if this happens in the data or later in the API. We want to reproduce the same propagation behaviour. @ireneisdoomed is trying to find out. 

2- Clean up our drug (molecule) index:
- Keep the `hasBeenWithdrawn` boolean as is
- Keep the `blackBoxWarning` boolean as is
- Drop `withdrawnNotice` field as it will be redundant with the new dataset.

cc'ing @ireneisdoomed and @andrewhercules as part of the spec.

**Comment by JarrodBaker** [comment]
I've updated the ETL (branch 1436-drug-warning) and API (branch 1436-drug-warning-dataset) and both are ready to go. 

I've deployed an app engine instance (https://api-drug-warnings-dot-open-targets-eu-dev.ew.r.appspot.com/) that has the changes, and loaded Elasticsearch with the new data. 

A query of the new data via GraphQL would look like: 
```
  drug(chemblId:"CHEMBL121"){
    id
    drugWarnings{
      toxicityClass
      country
      description
      references {
        id
        source
        url
      }
      warningType
      year
      meddraSocCode
    }
  }
```
The `withdrawnNotice` field has been removed.

@d0choa I'll give the ticket to you. Can you please pass on to the best person on the FE to make the necessary changes. Once they are done I'll merge everything and delete the app engine instance.

**Comment by d0choa** [comment]
After discussion with @JarrodBaker. We will merge these changes to dev and work from there, instead of a parallel branch of the API

**Comment by d0choa** [comment]
Other follow up actions are discussed in separate tickets
