### ISSUE TITLE
Systematic review of 21.04 evidence

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1441]
We want to identify any potential issues on submitted evidence. To do that, we need to process all evidence and extract notNull values for all fields in all datasources.

**Comment by ireneisdoomed** [comment]
Spreadsheet with the metrics:

https://docs.google.com/spreadsheets/d/1uB6aq-mu0Y5-L4zCqGzaUAC4Jmy0ejC-ibeXmRwODBs/edit#gid=786410773

**Comment by ireneisdoomed** [comment]
The data team is currently in the process of developing an application to facilitate the consultation of metrics for the whole team.

As a preliminary solution, the WIP app is deployed in Heroku and can be consulted here: https://ot-release-metrics.herokuapp.com

The application has 3 functionalities:
- Compare metrics. To compare the gross numbers between two pipeline runs. This tab is intended to replicate the behaviour of the spreadsheet we were working on so far (https://docs.google.com/spreadsheets/d/1xXCDS5h7dKQdwTvidaEGhyryCfoKm1A6TJW9gYPSrws/edit#gid=525819953)
- Explore metrics. For more detailed consultation and grouping of the different metrics associated with a particular pipeline run.
- Stats. Currently empty but where we expect to show trends in our data.
