### ISSUE TITLE
Design new schema for the HallMarks

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1444]
See target ticket.

**Comment by DSuveges** [comment]
# New cancer hallmarks object design

## The data

* The data is uploaded into the COSMIC evidence input bucket [here](gs://otar007-cosmic)
* The hallmark file eg. [CTTV007-10-02-2021_v94_hallmarks.tsv.gz](gs://otar007-cosmic/archives/CTTV007-10-02-2021_v94_hallmarks.tsv.gz) is a gzipped tsv file. 
* How the file looks (number of rows: 3715):

| GENE_SYMBOL | CELL_TYPE                | PUBMED_PMID | HALLMARK                 | IMPACT   | DESCRIPTION                                                  | CELL_LINE         |
| :---------- | :----------------------- | ----------: | :----------------------- | :------- | :----------------------------------------------------------- | :---------------- |
| ABI1        | hepatocellular carcinoma |    28339046 | proliferative signalling | promotes | overexpression of ABI1 increases and KD decreases cell proliferation | HepG2 and MHCC97H |
| ABI1        | hepatocellular carcinoma |    28339046 | invasion and metastasis  | promotes | overexpression of ABI1 increases and KD decreases cell migration and invasion | HepG2 and MHCC97H |
| ABI1        | nan                      |    16025998 | role in cancer           | TSG      | TSG                                                          | nan               |
| ABI1        | nan                      |     9694699 | role in cancer           | fusion   | fusion                                                       | nan               |
| ABI1        | nan                      |    23552839 | role in cancer           | TSG      | TSG                                                          | nan               |

* `GENE_SYMBOL` - Genes are identified by their HGNC gene symbol. (317 unique gene, so on average ~10 annotation per gene)

* `CELL_TYPE` and `CELL_LINE` on which the given annotation was reported. 

  * 516 entries have cell line annotation of 306 cell lines.
  * 1997 entries have cell type annotation of 529 unique cell types

* `PUBMED_ID`: publication from which the given annotation was extracted. (except one, all annotation has pubmed identifier of 2498 publication)

* `HALLMARK`: this column is not really the "hallmark" annotation. This is the column telling the annotation type. This column has value in every row. There are 22 different possible types, out of 10 are the actual hallmark annotations:

  ```
  ['proliferative signalling',
   'invasion and metastasis',
   'suppression of growth',
   'angiogenesis',
   'change of cellular energetics',
   'genome instability and mutations',
   'escaping programmed cell death',
   'tumour promoting inflammation',
   'cell replicative immortality',
   'escaping immune response to cancer']
  ```

  The remaining annotation types:

  ```
  2                           role in cancer
  4                         function summary
  5                           fusion partner
  6                              mouse model
  8          differentiation and development
  9     global regulation of gene expression
  13           types of alteration in cancer
  14                         clinical impact
  15          impact of mutation on function
  16                   cell division control
  19                              senescence
  21               interaction with pathogen
  ```

* `IMPACT`- impact type the annotation eg. the hallmark annotations can `promotes` or `surpresses`, while `role in cancer` annotation can tell if it's a tumor suppressor. Impact is missing in 1793 rows, while it can take 15 possible values.

* `DESCRIPTION`: Description of the annotation. This information is seen in the description column of the hallmarks table. Available for all columns and contains 2966 unique values.

## Current representation

Schema:

```
root
 |-- hallmarks: struct (nullable = true)
 |    |-- attributes: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- attribute_name: string (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |-- cancer_hallmarks: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- promote: boolean (nullable = true)
 |    |    |    |-- suppress: boolean (nullable = true)
 |    |-- function_summary: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
```

### Cancer_hallmarks object

* When taking a look at the post-pipeline target data, what we see is what we would expect in the hallmark object:

  ```python
  (
      spark.read.parquet(target_file)
      .select(
          F.explode(F.col('hallMarks.cancer_hallmarks')).alias('cancer_hallmarks')
      )
      .select(
          F.col('cancer_hallmarks.label')
      )
      .distinct()
      .show()
  )
  ```

  This query returns the 10 distinct hallmark annotations as expected.

### Function_summary object

* For `function_summary` only the `col(HALLMARK) == 'functions'` mapped.

### Attributes object

* In the `attributes` field we have the rest of the annotations:

  ```python
  (
      spark.read.parquet(target_file)
      .select(
          F.explode(F.col('hallMarks.attributes')).alias('attributes')
      )
      .select(
          F.col('attributes.attribute_name')
      )
      .distinct()
      .show()
  )
  ```

  Exactly 11 annotation types. 

  | attribute_name                       |
  | :----------------------------------- |
  | fusion partner                       |
  | global regulation of gene expression |
  | differentiation and development      |
  | impact of mutation on function       |
  | cell division control                |
  | mouse model                          |
  | types of alteration in cancer        |
  | senescence                           |
  | clinical impact                      |
  | interaction with pathogen            |
  | role in cancer                       |

**What are these values exactly:** 

* `fusion partner`: in the description field there is a protein the target was found fusioned with. 
* `global regulation of gene expression`: more of a functional summary too. Eg. *induces stabilisation of histone deacetylase 1 (HDAC1) in a kinase activity-dependent manner*
* `differential and development`: annotation on said characters *promotes adipocyte differentiation*
* `impact of mutation on function`: functional changes of mutations related to cancerous transformation eg *provides androgen upregulated promoter in fusion with ETV1* 
* `cell divison control`: relevant effect on said cell functions eg. *regulates mitotic spindle assembly and orientation and chromosome segregation* 
* `mouse model`: Description of a relevant mouse model. eg. *p.E76K conditional knock-in promotes colitis-associated colorectal cancer development* 
* `types of alteration in cancer`: if any notable mutation of this target is found in cancerous growth and differentiation. Eg *missense mutation in 42% of tumours, the most common being p.E76K* 
* `senescence`: if senescence is associated with this gene. eg. *hepatocyte-specific KD induces hepatocyte senescence in mice with oncogene-driven hepatocellular carcinoma*
* `clinical impact`: eg. *elevated expression is associated with reduced survival*
* `interaction with pathogen`: eg. *cellular corepressor that inhibits the expression of HPV-encoded E6 and E7 oncoproteins which antagonise p53 and pRB tumour suppressor activity* 
* `role in cancer`: this is the only currently utilized annotation. Impact and description both set. eg.  IMPACT: *TSG*; DESCRIPTION: *TSG*. Mostly the impact is the same as the description, but not always. Currently the frontend captures/shows the description field.

## Proposed new representation

```
root
 |-- hallmarks: struct (nullable = true)
 |    |-- attributes: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- attribute_name: string (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |-- cancer_hallmarks: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |    |    |-- label: string (nullable = true)
 |    |    |    |-- impact: boolean (nullable = true)
```

### Attributes object

The attributes would be shown as a separate table with three columns: 

1. attribute name eg. role in cancer
2. would provide a description for the given attribute
3. would provide a link to the relevant publication

This object would contain the `functions` annotations as well, as this information conceptionally also belongs here. There's no need for splitting this data into a separate object as we currently do. 

### cancer_hallmarks object

* The hallmarks would be kept in a separate object as now. Only change is to remove the boolean fields and just carry over the `IMPACT` column, this is enough to reproduce the hallmarks annotation. Having a separate column for the `suppress` and `promote` is excessive and is not aligned with the way we are representing the data either on the front end.

### Caveat

We still won't capture and capitalize the cell type and cell line annotation. As currently we don't really have any immediate plans to use them, I would rather exclude these fields for now.

**Comment by JarrodBaker** [comment]
This has been completed and the data can be seen here: gs://ot-team/jarrod/target-outputs/v7/

I'll close the ticket once the PR is merged.
