### ISSUE TITLE
Remove links to classic version of Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1447]
To prepare for the production release of `Beta`, can we please remove the links to the classic version of the Platform on the target, disease/phenotype, drug, associations, and evidence pages? 

Also, can we please remove the link to the classic version of the Platform displayed in the yellow notification box on the homepage?

**Comment by mirandaio** [comment]
As agreed, tabs will remain in drug page and will be removed from evidence page.
