### ISSUE TITLE
Display black box and withdrawn warnings on drug profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1450]
Based on the work of #1419 and #1438, the Platform can now display the manually curated black box and withdrawn warnings from ChEMBL. 

```
query drugWarnings {
  drug(chemblId: "CHEMBL121") {
    id
    drugWarnings {
      toxicityClass
      country
      description
      references {
        id
        source
        url
      }
      warningType
      year
      meddraSocCode
    }
  }
}
```
The data is now available in the dev API - [sample query for CHEMBL121](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20drugWarnings{%20drug(chemblId:%22CHEMBL121%22){%20id%20drugWarnings{%20toxicityClass%20country%20description%20references%20{%20id%20source%20url%20}%20warningType%20year%20meddraSocCode%20}%20}%20})

Based on a review of the data, drugs can have:

- Single black-box warning (e.g. CHEMBL473)
- Multiple black-box warning (e.g. CHEMBL1118)
- Single withdrawn warning (e.g. CHEMBL1201352)
- Multiple withdrawn warnings (e.g. CHEMBL122)
- Both black-box and withdrawn warnings (e.g. CHEMBL121)

## Design specification

The full design specification is available on the [team Google Drive](https://docs.google.com/presentation/d/1UV7Jax9CsR-7SIJb9JYGxb_QOHonEr2Q-nDmxgwB0Jg)

### Drug profile page header section

Please change the existing withdrawn warning component found in the drug profile page header:

![Option_3_three_icons_same](https://user-images.githubusercontent.com/7490258/112334953-bd6cf080-8cb3-11eb-99bb-e86d144756f2.png)

With the "Status:" entry, please implement the following:

- If `drug.data.isApproved` is `true`, display the [FontAwesome check-circle icon](https://fontawesome.com/icons/check-circle?style=solid) in Open Targets grey `#5a5f5f` along with the label "Approved"
- If `drug.data.blackBoxWarning` is `true`, display the [FontAwesome exclamation-circle icon](https://fontawesome.com/icons/exclamation-circle?style=solid) in Open Targets grey `#5a5f5f` along with the label "Black box warning"
- If `drug.data.hasBeenWithdrawn` is `true`, display the [FontAwesome times-circle icon](https://fontawesome.com/icons/times-circle?style=solid) in Open Targets grey `#5a5f5f` along with the label "Withdrawn"
- Remove the on-hover pop-up showing the withdrawn information as that data will be deprecated by the GraphQL API

### Summary widget:

![Drug Warning Design Specification (1)](https://user-images.githubusercontent.com/7490258/112028577-3cd1b700-8b30-11eb-961c-085332656fbe.png)

Notes:
- Please display "Withdrawn" if `drug.data.hasBeenWithdrawn` is `true`
- Please display "Black Box" if `drug.data.blackBoxWarning` is `true`

### Detail view

![Drug Warning Design Specification (2)](https://user-images.githubusercontent.com/7490258/112048501-63025180-8b46-11eb-8e0d-531daff6bb80.png)

Notes:

- For the section description, please display "Manually curated withdrawn and black box warnings for DRUG NAME. Source: ChEMBL" and link "ChEMBL" to `https://www.ebi.ac.uk/chembl/`

- Within the table, if any cell value is `null` or `[ ]`, please display "N/A"

- Please display the API response data as follows:

| Column | API response field | Example value | Can field be `null`? | Notes |
| --- | --- | --- | --- | --- |
| Warning type | `data.drugWarnings[x].warningType` | "Withdrawn" | NO | API response will be either "Withdrawn" or "Black Box Warning" |
| Description | `data.drugWarnings[x].description` | "Increased risk of ischaemic heart disease" | YES | field call be `null` |
| ChEMBL warning class | `data.drugWarnings[x].toxicityClass` | "Misuse" | YES | Field can be `null` |
| MedDRA SOC code |  `data.drugWarnings[x].meddraSocCode` | 10007541 | YES | Field is an `int`; field can be `null` |
| Country/region |  `data.drugWarnings[x].country` | "United States; United Kingdom; United States; Spain; Germany; France" | YES |  Field can be `null`; field can contain single or multiple countries/regions (see CHEMBL273575) |
| Year |  `data.drugWarnings[x].year` | 1986 | YES |  Field is an `int`; field can be `null` |
| References | `data.drugWarnings[x].references[y]` | Object containing `id', `source`, `url` | YES | Field is an array; field can be an empty array `[ ] ` |

- For the value in the "MedDRA SOC code" column, please construct a link using the following construct - `https://identifiers.org/meddra:` + `data.drugWarnings[x].meddraSocCode` (e.g. https://identifiers.org/meddra:10007541, [10007541](https://identifiers.org/meddra:10007541))

- For the References column, please use the drawer component and organise each entry by `source` value and display the `id`, similar to what is done for multiple records in the Known Drugs tables on the profile pages. Also, instead of displaying "x records" (e.g. 5 records), please display a list of the unique sources for each warning. For example, if a warning as 3 FDA records, please display "FDA" within the "References" column and when a user clicks, please open the drawer component. Conversely, if the warning as 1 PubMed, 1 USGPO, and 2 FDA records, please display "FDA, PubMed, USGPO".

**Comment by d0choa** [comment]
2 minor requests @mirandaio:
- [ ] Can you activate the show more rows?
- [ ] Can you show the Year as N/A when not available

**Comment by mirandaio** [comment]
@d0choa done here https://github.com/opentargets/platform-app/pull/321
