### ISSUE TITLE
Remove "Genetic associations (genes)" column from associations heatmap

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1452]
Due to changes in the development API noted in #1410, the datatypes have changed and the "Genetic associations (genes)" column is now blank as there is no data. For example, see the [inflammatory bowel disease](https://main--platform-app.netlify.app/disease/EFO_0003767/associations) associations page.

![Screenshot 2021-03-29 at 12 20 07](https://user-images.githubusercontent.com/7490258/112829498-1f00d680-9089-11eb-82c4-b8e1a11f49cc.png)

Can we please remove this column?

**Comment by d0choa** [comment]
In the static file we need to:
- remove: Genetic associations (genes) aka `genetic_literature`
- rename: Genetic associations (variants) aka `genetic_associations` -> Genetic associations

**Comment by d0choa** [comment]
Looks great. Thanks @mirandaio
