### ISSUE TITLE
Remove TEC from Ensembl in new target

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1454]
Ensembl uses the symbol [TEC (To be Experimentally Confirmed)](http://www.ensembl.org/info/genome/genebuild/biotypes.html) as content in some of the fields.

As this just denotes the absence of data, we want the name `TEC` to be removed and replaced with the relevant null value for that type. TEC has been detected on:

- biotype
- approvedName

Given I have a genes: 
```
+---------------+-----------------------------------+-------+
|id             |approvedName                       |biotype|
+---------------+-----------------------------------+-------+
|ENSG00000278859|novel transcript                   |TEC    |
|ENSG00000278885|TEC                                |TEC    |
|ENSG00000279076|TEC                                |TEC    |
|ENSG00000279136|TEC                                |TEC    |
```

This would become:

```
+---------------+-----------------------------------+-------+
|id             |approvedName                       |biotype|
+---------------+-----------------------------------+-------+
|ENSG00000278859|novel transcript                   |null    |
|ENSG00000278885|null                               |null    |
|ENSG00000279076|null                                |null    |
|ENSG00000279136|null                                |nul    |
```

**Comment by mkarmona** [comment]
@d0choa do you mean biotype `tec` to be removed those right?

**Comment by d0choa** [comment]
Yes both. Sorry I was not very clear

**Comment by d0choa** [comment]
to provide a bit more context to @JarrodBaker, TEC is being grounded in EPMC pipeline to 600+ ids, because 600+ genes have approvedName == TEC. Not great 😔. Of course there is an actual [TEC gene](http://m.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000135605;r=4:48135783-48269838)

**Comment by JarrodBaker** [comment]
This has been completed and will be available next time I run Dataproc (future v6). It removes 1057 entries.
