### ISSUE TITLE
Investigate potential JSON schema viewers

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1455]
Based on the work in #1411, a sample JSON is now available that contains the fields generated by the ETL pipelines for each dataset. 

**Command:**
`gsutil -m cat gs://ot-snapshots/etl/outputs/21.03.1/metadata/\*\*/part\* | jq '.' | less > data_download.json`

**Output file:**
[sample-data-download-response.json.zip](https://github.com/opentargets/platform/files/6228843/sample-data-download-response.json.zip)

The JSON also contains the schema for each dataset in the `serialisedSchema` field.

Can we please investigate potential JSON schema viewers, for example [material-ui-json-schema-viewer](https://www.npmjs.com/package/material-ui-json-schema-viewer) and [json-schema-viewer](https://www.npmjs.com/package/json-schema-viewer)? Is it feasible to display the dataset schema based on the `serialisedSchema` string?

If we can display the schema, would the package support?

1. By default, fields are collapsed due to the large size of some dataset schemas (e.g. evidence)
2. Allow users to download the schema

The feedback on whether this is feasible will inform the ongoing discussions around the [data download page specification](https://docs.google.com/presentation/d/1RqsKxYIaHfG4wE1-ZbZhpGp8yYALsjF5Lg4ZW2KSiNo/edit#slide=id.gccd856735a_0_0).

**Comment by mirandaio** [comment]
After investigating [react-json-view](https://www.npmjs.com/package/react-json-view) we are able to collapse deeply nested fields or large datasets. We are also able to download the schema.

**Comment by andrewhercules** [comment]
Ticket closed as initial implementation of data downloads page will not contain schema
