### ISSUE TITLE
Identify FE changes in evidence due to json schema v2 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1456]
Collate expected changes in evidence

**Comment by ireneisdoomed** [comment]
The document tracking all the changes to be made by the FE team is here:

https://docs.google.com/document/d/1z40qOgOj9MQLAQXvITQKEY84JUFhFNKsY9URJwwCkyg/edit?usp=sharing

**Comment by d0choa** [comment]
@andrewhercules feel free to close this ticket when you are done with it

**Comment by andrewhercules** [comment]
Ticket closed as document has been reviewed and specification tickets created and assigned to epic #1479
