### ISSUE TITLE
Molecular interactions between targets are not shown properly

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1458]
No interaction is listed for IL2RA on the [deploy preview](https://deploy-preview-307--platform-app.netlify.app/target/ENSG00000134460) However intact shows interactions for IL2RA to for example IL2. If you [look up IL2](https://deploy-preview-307--platform-app.netlify.app/target/ENSG00000109471), IL2RA is listed as interacting partner. 

The problem is caused by the fact that interactions are only returned by `interactorA`.

**Comment by d0choa** [comment]
IL2 as interactor A returns IL2RA as interactor B

```
query t {
  target(ensemblId: "ENSG00000109471") {
    approvedSymbol
    interactions(sourceDatabase: "intact"){
      count
      rows{
        targetB{
          approvedSymbol
          id
        }
      }
    }
  }
}
```

```
{
  "data": {
    "target": {
      "approvedSymbol": "IL2",
      "interactions": {
        "count": 1,
        "rows": [
          {
            "targetB": {
              "approvedSymbol": "IL2RA",
              "id": "ENSG00000134460"
            }
          }
        ]
      }
    }
  }
}
```

However, IL2RA as interactor A returns a null interactions object
```
query t {
  target(ensemblId: "ENSG00000134460") {
    approvedSymbol
    interactions(sourceDatabase: "intact"){
      count
      rows{
        targetB{
          approvedSymbol
          id
        }
      }
    }
  }
}
```

```
{
  "data": {
    "target": {
      "approvedSymbol": "IL2RA",
      "interactions": null
    }
  }
}
```

**Comment by d0choa** [comment]
Problem solved by duplicating and transposing the data in the matrix when necessary.
Thanks @cmalangone.
