### ISSUE TITLE
Update UniProt literature section on evidence page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1470]
Can we please make the following changes to the UniProt literature section on the evidence page?

**Confidence**
- [ ] Add a new column called "Confidence" between the "Reported Protein" and "Literature" columns and display the `confidence` value (e.g. medium or high)

**Comment by d0choa** [comment]
To prevent confusion, this ticket refers to "uniprot literature" as mentioned in the title and not to ClinVar somatic as mentioned in the body

**Comment by andrewhercules** [comment]
Specification updated to fix typo

**Comment by andrewhercules** [comment]
Ticket closed as work completed and reviewed and merged into `main`
