### ISSUE TITLE
Update ChEMBL section on evidence page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1472]
Can we please update the ChEMBL section on the evidence page?

**Start Date**
- [ ] Create a new column called "Start Date" and display between the "Status" and "Source" columns
- [ ] Display the year value returned in the `studyStartDate` value (note: the API returns the date as YYYY-MM-DD, but we will only display the YYYY value)

**Status**
- [ ] Continue to display the `clinicalStatus` field and if `studyStopReason` is not an empty string, display a tooltip with the label "Study stop reason:" and display the `studyStopReason`

**Comment by d0choa** [comment]
just to prevent any confusion, the last point is about adding the tooltip to the already existing "Status" column
