### ISSUE TITLE
Update PhenoDigm section on evidence page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1473]
Can we please update the PhenoDigm section on the evidence page?

**Mouse model allelic composition**
- [ ] Link the `biologicalModelAllelicComposition` value to the Jackson Laboratory website using the identifiers.org construct - `https://identifiers.org/` + `biologicalModelId` (e.g. [MGI:2442292](https://identifiers.org/MGI:2442292))

_Update 21 April 2021_

As noted in #1403, the `biologicalModelId` field is currently returning values that are not IDs - for example, [primary immunodeficiency and CCDC83](https://main--platform-app.netlify.app/evidence/ENSG00000150676/Orphanet_101997) has an entry where the `biologicalModelId` is `NOT-RELEASED-1365f850b4` ([GraphQL API query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20reactomeData%20{%20disease(efoId:%20%22Orphanet_101997%22)%20{%20name%20evidences(ensemblIds:%20[%22ENSG00000150676%22],%20datasourceIds:%20[%22phenodigm%22])%20{%20count%20rows{%20biologicalModelId%20target{%20id%20approvedSymbol%20}%20}%20}%20}%20})). In the next pipeline run, the GraphQL API will return `null` if there is no MGI ID available - please ensure the logic used to build the link captures `null` values and do not link the `biologicalModelAllelicComposition` text if `biologicalModelId` is `null`.

**Comment by d0choa** [comment]
This link can be built using identifiers.org

**Comment by andrewhercules** [comment]
Specification updated to use identifiers.org and the [MGI namespace](https://registry.identifiers.org/registry/mgi)

**Comment by andrewhercules** [comment]
Ticket closed as work completed and reviewed and merged into `main`
