### ISSUE TITLE
Update Expression Atlas section on evidence page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1474]
Can we please update the Expression Atlas section on the evidence page?

**Experiment confidence** 
- [ ] Create a new column called "Experiment confidence" and display after the "Experiment details" column
- [ ] Display the `confidence` value (e.g. high, medium)

**Comment by carcruz** [comment]
https://github.com/opentargets/platform-app/pull/342

**Comment by andrewhercules** [comment]
Ticket closed as work completed and reviewed and merged into `main`
