### ISSUE TITLE
POSTGAP column returned from an API call

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#148]
This data source seems to be returned from a call like this:

https://api.opentargets.io/v3/platform/public/association/filter?&disease=EFO_0000305&scorevalue_min=0.999

Any chance to disable this as it may get users confused?

<img width="277" alt="screen shot 2018-10-03 at 15 28 57" src="https://user-images.githubusercontent.com/6472381/46417279-30b7cc00-c721-11e8-9fed-1a5f4341cb09.png">

**Comment by ElaineMcA** [comment]
Closing for the moment as low priority compared with other work for API.  Not a blocker for users.

**Comment by d0choa** [comment]
I found the same issue in both the API and the associations file. 
The value is always '0', so I suppose is not used at any point in the pipeline.
It's still low priority, but it shouldn't take much time to fix it at some point.
"postgap: 0" is repeated **6,607,648** times in the 19.04 associations file

**Comment by iandunham** [comment]
Thisis from when we were working on a version that would use evidence from postgap. It may be a placeholder for the future GWAS score as well
