### ISSUE TITLE
Generate sitemaps for 21.04 release

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1480]

**Comment by andrewhercules** [comment]
Sitemaps have been generated using 21.04 data available in the `ot-snapshots` 

The sitemaps include profile pages and associations pages for all targets and diseases. There is also a sitemap for the drug profile pages. 

**[21.04_sitemaps.zip](https://github.com/opentargets/platform/files/6370137/21.04_sitemaps.zip)**

Please make a `/sitemaps` directory at the root level of the front-end application so that Google will recognise the index.xml sitemap at `https://platform.opentargets.org/sitemaps/index.xml`.

**Comment by d0choa** [comment]
Question. Wouldn't this index the development branches in netlifly?

**Comment by andrewhercules** [comment]
No because Netlify includes an `X-Robots-Tag: noindex` header in the response - see their [deploy preview documentation](https://docs.netlify.com/site-deploys/overview/#search-engine-indexing) for more information.

The issue that we have is that named branch previews - e.g. `https://am-json-schema--platform-app.netlify.app` - can be indexed. Netlify doesn't set a response header on these previews. To prevent indexing of these previews and branches, we can either:

1. Set all Netlify deploys to have a basic-auth username and password
2. Add a `robots.txt` file to the `platform-app` that prevents any search indexing and overwrite this file in the production deployment process

**Comment by andrewhercules** [comment]
Ticket closed as sitemaps generated, uploaded to `/sitemaps` directory, and merged into `main`
