### ISSUE TITLE
Handle redirects from targetvaliation.org to platform.opentargets.org

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1482]
In the 21.04 release, we would like to start using https://platform.opentargets.org/ as the main URL for the Platform. We currently use https://www.targetvalidation.org/ and would like to set up redirects from targetvalidation.org --> opentargets.org.

Ideally, the redirects should also include the path. For example https://www.targetvalidation.org/target/ENSG00000232810 would redirect to https://platform.opentargets.org/target/ENSG00000232810.

The paths we want to redirect are:

- Homepage (/)
- Associations pages (/target/ID/associations and /disease/ID/associations)
- Evidence pages (/evidence/TARGET-ID/DISEASE-ID)
- Target profile page (/target/ID)
- Disease profile page (/disease/ID)

There are some redirects that we do not need to do as those pages or URL structures have been deprecated. For example, redirecting from the existing drug summary page (e.g. https://www.targetvalidation.org/summary?drug=CHEMBL122) or from an associations page with facets applied (e.g. https://www.targetvalidation.org/disease/EFO_0001421/associations?view=t:priority&fcts=datatype:genetic_association;somatic_mutation;known_drug;affected_pathway).

**Comment by mkarmona** [comment]
@andrewhercules here, I can see two things

1. at domain level (there is not rewrite whatsoever as the rewrite is a HTTP protocol level
2. at HTTP level

The option (2) I can only see the path rewrite for the `summary?drug=....` into `drug/ID`. This implies rewriting the full path but Google LB does not allow to do that, I am afraid (see [here](https://cloud.google.com/load-balancing/docs/https/setting-up-url-rewrite) and the quote below). 

> Important: The rewrite is prepended to the path as is. Full path rewrites are not supported. HTTP(S) Load Balancing only implements path prefix rewrites. For example, you can rewrite: host.name/path1/resource1 to host.name/path2/resource1. You cannot rewrite host.name/path1/resource1 to host.name/path1/resource2.

Rewrite happens at the application level so I would suggest adding this rule to the react application. Regarding permanent rewrites I will explore other options.

**Comment by andrewhercules** [comment]
@mkarmona thank you! We can ignore the drug summary page and other pages with parameters in the URL as those are not indexed or externally linked.

Ideally, we should implement `301` redirects for:

- Homepage (/)
- Associations pages (/target/ID/associations and /disease/ID/associations)
- Evidence pages (/evidence/TARGET-ID/DISEASE-ID)
- Target profile page (/target/ID)
- Disease profile page (/disease/ID)

**Comment by andrewhercules** [comment]
In Netlify, we have set up `platform.opentargets.org` as a domain alias for `targetvalidation.org`. If `301` redirects are not possible, could we explore this instead?

It does mean that we lose some of the benefits of our search engine optimisation and would have to start indexing `platform.opentargets.org`. We would have to specific `platform.opentargets.org` as the canonical page. This is doable and would take a few months to reindex but could be a solution if redirects are not possible.

**Comment by mkarmona** [comment]
@andrewhercules looking closely at the GLB configuration seems that they added that functionality :astonished: . It shows both options, prefix rewrite and full although it needs to be the same ending but works for the use case you lately described

![image](https://user-images.githubusercontent.com/5394232/115380943-ffae2280-a1ca-11eb-9940-95dfab6a215c.png)

**Comment by andrewhercules** [comment]
Ticket closed as `_redirects` file updated in the webapp `/app` directory, tested, and merged into `webapp-decommission` branch
