### ISSUE TITLE
Search results page show blank page and console log errors

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1483]
On `dev`, the search results page is crashing with a blank page and console log error - see https://main--platform-app.netlify.app/search?q=MYC&page=1. 

However, in `beta`, the search results page is visible - see https://beta.targetvalidation.org/search?q=MYC&page=1

This may be due to a change in the GraphQL API response to build the top-hit panel.

Can we please investigate why the search results page is crashing and apply a fix?

**Comment by d0choa** [comment]
Sorry we forgot to specify this in the work related to #1450.

What's happening here is that the query is trying to get the `withdrawnNotice` to populate the mouse-over tooltip for withdrawn drugs. `withdrawnNotice` is no longer available so the query crashes.

@andrewhercules any suggestion? I would be ok removing the on-hover interaction and just leave the label. We can harmonise the styling to look as in the drug profile page.

- Working version in [beta](https://beta.targetvalidation.org/search?q=rofecoxib&page=1)
- Crashing version in [dev](https://main--platform-app.netlify.app/search?q=braf&page=1)
