### ISSUE TITLE
Remove the Variation & Genomic Context summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1484]
Once we have migrated to the new Platform infrastructure, the genome browser that powers the Variation & Genomic Context summary widget and detail view will no longer work. This is because the genome browser is tightly coupled with the REST API, relying on the /evidence endpoint to generate the lollipops.

Can we please temporarily remove the Variation & Genomic Contexts summary widget and detail view? 

We will continue to work on a replacement browser view post-release.

**Comment by d0choa** [comment]
In case there is any doubt, we want to remove it from the codebase, not just the UI.
