### ISSUE TITLE
What do fields in the results from an API call mean?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#149]
This call 

https://api.opentargets.io/v3/platform/public/association/filter?&disease=EFO_0000305&scorevalue_min=0.999

will return some fields/columns that I'm not too sure what they mean e.g.

* is_direct e.g. 3367, 2919
* target.gene_info.name e.g. 0, 62, 22
* target.gene_info.symbol e.g. 3787, 7092
* target.id e.g. 1, 3, 0, 10, 4
--

Could anyone help here please?

**Comment by mkarmona** [comment]
@deniseOme trying to answer your questions (so sorry betting back to you so late about this)

- `is_direct` means get associations for that disease but the ones that have at least one evidence linking target and disease directly but not through traversing the ontology
- `target.gene_info.name` it should correspond to the approved HGNC name
- `target.gene_info.symbol` it should correspond to the approved HGNC symbol
- `target.id` an unique identifier and we settled down with the ensembl id (ref one not the version as we also select which ensembl version release to use for the pipeline run [see here](https://github.com/opentargets/data_pipeline/blob/master/mrtarget/Settings.py#L393)) 

does this help you with your questions?
