### ISSUE TITLE
Update Terraform provisioner to use deployment-specific robots.txt file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1497]
As noted in #1496, the `platform-app` will contain two `robots.txt` files that can be used depending on the deployment context.

Can we please update the Terraform provisioner so that in `production`, we use the `robots.txt.production` file and rename to `robots.txt`?

For any other deployment contexts (e.g. dev, staging, etc.), please use the default `robots.txt` file provided in the `platform-app` codebase.

**Comment by mbdebian** [comment]
Related [Issue](https://github.com/opentargets/terraform-google-opentargets-platform/issues/1)

**Comment by andrewhercules** [comment]
Thank you @mbdebian!

Ticket closed as provisioner updated and displaying correct `robots.txt` file depending on the deployment context:

**Production**
![Screenshot 2021-04-29 at 17 24 08](https://user-images.githubusercontent.com/7490258/116585011-dea6a980-a90f-11eb-9bf4-f67e01907170.png)

**Development / QA**
![Screenshot 2021-04-29 at 17 23 25](https://user-images.githubusercontent.com/7490258/116585090-ef571f80-a90f-11eb-9b56-9896ad9434ca.png)
