### ISSUE TITLE
Change Bibliography category dropdown to per-category toggles

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1498]
As mentioned by @mkarmona, our new Bibliography section will allow for users to select more than one category (e.g. targets AND diseases). 

The current implementation is a single-select drop down, which limits users to only selecting one category. We would like to change this so that users can select multiple categories, with the default that all categories are selected.

Material UI offers different options that we can integrate:

- Switches: https://material-ui.com/components/switches/
- Toggles: https://material-ui.com/components/toggle-button/
- Checkboxes: https://material-ui.com/components/checkboxes/

**Comment by ktsirigos** [comment]
closing this as work is done
