### ISSUE TITLE
OTAR042 -Tractability: Create high fidelity prototype to demonstrate proposed user interaction journey

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#15]
Interactive prototype needed to demonstrate interaction on:

- Disease association page
- Target profile page
- Batch search page

**Comment by andrewhercules** [comment]
Interactive prototype can be viewed at http://bit.ly/ot-tract-2

**Comment by andrewhercules** [comment]
Interactive prototype presented to OT Platform Core team meeting yesterday.
- [Presentation slides](https://docs.google.com/presentation/d/15HZzMt2kCafqca4b7IYQPXgzCelq9uzI8KuJl8xAakk/edit?usp=sharing)
- [Feedback notes](https://docs.google.com/document/d/1i6_ZnxJD0CNIAHVSECe8e_lHqeL5FcuKvzvbM19DC3g/edit?usp=sharing)

Based on feedback, it was agreed that we will explore building a new Prioritisation View that would support users in prioritising a list of targets. This view would existing alongside the existing Associations View. I will update the interactive prototype and will post a link on GitHub when ready for review.

The initial UI designs for the [target profile page](https://fkzaso.axshare.com/#g=1&hi=1&p=target_profile_page) and [batch search page](https://fkzaso.axshare.com/#g=1&hi=1&p=batch_search_page) were approved as they answer the two key questions of the project, namely "Is my target tractable?" and "For my target, which modalities are most likely to be successful?"

**Comment by andrewhercules** [comment]
Using a modified Associations view as a base, I have created two Prioritisation views that make the tractability data visible. There are subtle differences between the two options, but Both can scale and accommodate additional tractability modalities and future target characteristics (e.g. safety score, availability of mouse models, etc.).

**Version 1:**

![prioritisation_view_-_v1](https://user-images.githubusercontent.com/7490258/44342769-f00f3680-a483-11e8-8dcb-25db3bf7852a.png)

**Version 2:**

![prioritisation_view_-_v2](https://user-images.githubusercontent.com/7490258/44342585-68c1c300-a483-11e8-9d67-0a3034748a5d.png)

Any thoughts/comments are much appreciated! :-)

**Comment by iandunham** [comment]
Both look good. Slight preference for version 2. I think that it would be great if it was possible not to show some of the data types in this view e.g. text mining either by the column headers or the filters behaving in a slightly different way here

**Comment by andrewhercules** [comment]
Thanks for the feedback @iandunham! :)

In addition to text mining, what are the other data types that could be hidden from this view?

**Comment by iandunham** [comment]
I was thinking that this would be configurable so you could choose, but certainly affected pathways, animal models could be off by default. We could add into the key target attributes whether an animal model exists, up or down regulation of expression in the disease, the tissue specificity, etc.

**Comment by andrewhercules** [comment]
I had a quick chat with @LucaFumis and we might be able to make something work with the existing facets - showing/hiding columns. I don't know if we want to introduce too much user configuration options because that might lead to a request to be able to recalculate the score on the fly - a definite use case but one that would result in a considerable amount of work.

**Comment by andrewhercules** [comment]
Here are three mockups showing the toggling of columns ([supported by DataTables](https://datatables.net/examples/api/show_hide.html)) based on the current data types facet. I have deliberately removed the data types facet to prevent user confusion and to make this view more about prioritising based on the data type, rather than the data provider. 

I have also checked that this view could work with the existing API calls and would result in a shorter list of targets. For many diseases, if we remove text mining, affected pathways, and animal models, the number of targets significantly decreases (e.g. Alzheimers - 3157 to 1552, breast carcinoma - 10545 to 6130). 

**Only showing associations with genetic associations, somatic mutations, drugs, and RNA expression data:**

![prioritisation_view_-_v3](https://user-images.githubusercontent.com/7490258/44413149-831e9e00-a562-11e8-8d90-fb4f4f32957e.png)

**Only showing associations with genetic associations, somatic mutations, drugs, RNA expression, and text mining data:**

![prioritisation_view_-_v3_1](https://user-images.githubusercontent.com/7490258/44413171-903b8d00-a562-11e8-8ad4-1bd2ce3810d3.png)

**Show associations with all data types as evidence:**

![prioritisation_view_-_v3_2](https://user-images.githubusercontent.com/7490258/44413176-93cf1400-a562-11e8-811f-10357c8bea6d.png)

**Comment by andrewhercules** [comment]
In the proposed view, no, they wouldn't be able to do that. If that's something we wanted to do, it would require extensive changes to the facets API endpoints and front-end code to ensure that the two always stay in sync.

Interesting point about the blue bar - it wasn't something I had considered as I used font weight and font size to denote the parent-child relationship between the overall score cell and the sub-score cells. I figured that since the overall score is still technically part of the association evidence - and is scored in the same colour - it could fall under that heading. I'll add that to my feedback form and get more user input. :)

**Comment by iandunham** [comment]
Would be useful to look at what other data we can bring in to the target attributes section. I can think of 
- expression (up or down regulated in a disease context)
- expression (tissue relevance if we had an assessment relative to disease)
- animal model (mouse) exists

Also said above but reiterating this
