### ISSUE TITLE
OTAR044 Networks: Review interactions graph database

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#150]
Interactions between molecules generated in a graph format as part of OTAR-044. A neo4j graph database dump is available at ftp://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/ot_graphdb.zip

Neo4j format currently generated from SQL database (using a tool) - approach used to date has been based on curation practices.

We need to take a look at what they've produced so far, and decide how it fits with what we want.

**Comment by afaulconbridge** [comment]
This issue is to:
- [ ] load the data dump currently available
- [ ] review the content - node types, edge types, patterns, structure, modelling representation - and feed back to Molecular Interactions
- [ ] consider how and where such interaction information might be fed into the pipeline, and what consequences that would have for how we would like it to be provided

**Comment by afaulconbridge** [comment]
I've been able to load the data dump into a Neo4j instance in Docker and take a look at the graph. 

It is very large and complicated, with many different node and edge types. I suspect it is rather over-normalized and can be simplified (e.g. there seems to be an inheritance pattern of node labels).

Awaiting documentation from Molecular Interactions for guidance before investigating further.

**Comment by afaulconbridge** [comment]
After discussion, need to establish a few stats to understand the data:
- [ ] Number of targets present
- [ ] Number of links per target (distribution)
- [ ] Distribution of scores

**Comment by ElaineMcA** [comment]
@MichaelaEBI  and @afaulconbridge to confirm when reviewed and create appropriate tickets.

**Comment by peatroot** [comment]
FYI @afaulconbridge, OrientDB has an importer for Neo4J DBs, which somebody has used for reactome: https://github.com/santo-it/reactome-orientdb. If you [start a docker instance of OrientDB](https://hub.docker.com/_/orientdb/), reactome is one of the example DBs you can explore.

**Comment by MichaelaEBI** [comment]
**From Noemi on November 21, 2018:**
Currently you can have a look to the miTab clustered interaction data that we have in our ftp:

ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact-micluster.zip

This file has the characterisation score that Pablo was mentioning in the formats meeting. It contains all the possible pair of molecules in IntAct for every species. Currently we don’t have a version of this file only for human, but if you think that this format will suit the purpose for OT we can start adjusting our pipelines to create one.

**Comment by afaulconbridge** [comment]
I've created a VM on GCP that will load the latest data on start. Removing myself from this ticket.

**Comment by MichaelaEBI** [comment]
The neo4j database was too complex for Open Targets needs. We received the relevant fields of the network data as a data dump in July and are now working with that.
