### ISSUE TITLE
Update ProtVista component to v 2.6.1

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1503]
As noted by Ian, there appear to be some bugs in the ProtVista (e.g. all same variants, no consequence filter). 

This was seen with ENSG00000167207 and ENSG00000104312; however other genes (e.g. ENSG00000143641) look correct. 

Can we please update the ProtVista component to the latest version? Once updated, we can then review to see if there is a data issue that we should report to UniProt.

**Comment by d0choa** [comment]
@andrewhercules I was looking at this before.
Apparently we are using the last released version based on [GitHub](https://github.com/ebi-webcomponents/protvista-uniprot/releases) 

```
 "protvista-uniprot": "^2.5.5"
 ```
 
 However, the underlying webcomponents keep under active development:
 https://github.com/ebi-webcomponents/nightingale
 
Do you mind reaching out to Xavier and asking what we should do and what their plans are on `protvista-uniprot`.

**Comment by andrewhercules** [comment]
Sure, will do - I'll follow up with Xavier and the UniProt team to see what the best solution is

**Comment by andrewhercules** [comment]
Just an update that I have sent Xavier an email with screenshots as the ProtVista view for [NOD2 in the Platform](https://platform.opentargets.org/target/ENSG00000167207) is different than the [ProtVista view for NOD2 on UniProt](https://www.uniprot.org/uniprot/Q9HC29/protvista).

Similar behaviour has also been observed with RIPK1 and ESR1 where the variants are incorrect (e.g. all Gs or all As) and the consequence and provenance information is missing and those filters do not work.

**Comment by andrewhercules** [comment]
Xavier has responded with the following:

> The API model for variation changed a while back and this is usually what it looks like when the ProtVista version is outdated...are you sure you are using 2.6.1? It might be worth explicitly setting this version in package.json (without the '^'). 
Let me know if this helps.

Based on his suggested, I updated the `package.json` in my local development environment and set `"protvista-uniprot": "2.6.1"`. This resolved the issue and now the variants and functional consequence data is properly displayed.

For example, ESR1:

![Screenshot 2021-04-29 at 17 05 56](https://user-images.githubusercontent.com/7490258/116582574-6b039d00-a90d-11eb-9c7c-709ebbc78f41.png)

For example, RIPK1:

![Screenshot 2021-04-29 at 17 06 24](https://user-images.githubusercontent.com/7490258/116582591-7060e780-a90d-11eb-882b-dfdf6448baf9.png)

Can we please update the `package.json` file and explicitly use version `"protvista-uniprot": "^2.6.1"`?

**Comment by d0choa** [comment]
...as Xavier said without the `^`

**Comment by andrewhercules** [comment]
Ahh yes, my apologies - have fixed the version number! 👍

**Comment by ktsirigos** [comment]
closing issue as work done.
