### ISSUE TITLE
Platform Output Support

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1505]
Platform Output Support (POS) is the third component in the back-end data and infrastructure generation pipeline. POS is an automatic and unified place to perform a release of OT Platform to the public. The other two components are Platform Input Support (PIS) and the ETL. POS will be responsible for:

- infrastructure task: 

  - [Fill in ElasticSearch](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1514) 
  - Fill in ClickHouse
  - Create the images

- publishing datasets in different services 

  - Copy the input into the release bucket. Eg. from `ot-snapshot` to `data-releases-prod`
  - Generate BigQuery
  - Copy the output into the release bucket.
  - Copy the release into FTP (rclone vs gsutil sync)
  - Script for the association dumps

- technical chores:

  - combined datasets metadata
  - [site maps](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1485)
  - [move old release data to cold storage](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1516)
 
- data validation:
 
  - check the number of ES documents should match the number of BQ entries. 

## Potential user interface for command line program: 

```
resources = elasticsearch | clickhouse | bigquery
storage = ftp | bucket
environment = dev | prod

>> pos create [resources]

>> pos validate [resources]

>> pos clean # remove all 

>> pos metadata site-maps # used for google crawler on front end

>> pos copy <storage> <storage>

>> pos deploy <env>

```

## Overview of workflow (Background)

1. PIS writes to <bucket>
2. ETL performs data manipulations
3. POS generates infrastructure (via Terraform), moves data to where it needs to be (ftp, BigQuery, etc), releases/promotes candidates.

**Comment by cmalangone** [comment]
List of things that might be involved with POS:
*) Copy the input into the release bucket. Eg. from ot-snapshot to data-releases-prod
*) Copy the release into FTP

**Comment by JarrodBaker** [comment]
Possible technologies: 
  - Terraform
  - SBT
  - Google Cloud Functions
  - Python / Scala CLI
  - Travis
  - Ammonite scripts

Combination of Terraform for infrastructure components (images) and SBT project.

**Comment by mkarmona** [comment]
**combined datasets metadata** is a file with all JSONLines from JSON and parquet from ETL into a new one. This file is required for the frontend web app to generate the download page. @mbdebian @cmalangone a chat with FE to know a bit more about all that needs to be bundled or not

```sh
gsutil -m cat gs://open-targets-data-releases/21.04/output/etl/json/metadata/**/part\*
```

**Comment by d0choa** [comment]
File currently requires both `json` and `parquet`:

```
gsutil cat 'gs://open-targets-data-releases/21.04/output/etl/*/metadata/**/*.json'
```

**Comment by mkarmona** [comment]
>combined datasets metadata is a file with all JSONLines from **JSON** and **parquet** from ETL into a new one

**Comment by ktsirigos** [comment]
@cmalangone can we close this? Seems the work is done here?
