### ISSUE TITLE
Security vulnerability in REST API dependency

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#151]
https://github.com/opentargets/rest_api/network/dependencies

The Pallets Project flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask

requirements.txt update suggested:
flask ~> 0.12.3

![image](https://user-images.githubusercontent.com/1447134/46477637-fe6ea300-c7e2-11e8-94a5-2a1f49f2a441.png)

**Comment by d0choa** [comment]
All work will be focused on new API
