### ISSUE TITLE
Re-activate paywalled Google Cloud bucket download 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1513]
Temporarily, we allowed the public download from the `open-targets-data-releases` bucket because there is a file being served to the FE ([file path](https://storage.googleapis.com/open-targets-data-releases/alpha-rewrite/static/ontology/diseases_efo.jsonl)).

Once there is a formula to ensure the file is available for FE, both in development and production, we want to move that bucket to paywall again. We want to reduce any liabilities in terms of costs.

**Comment by cmalangone** [comment]
Done
