### ISSUE TITLE
Benchmark associations against gold standard in the release metrics script

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1515]
Information from @d0choa follows:

---

this is the main code. It has a lot of things on it, that are not really required (e.g. plotting etc.)
https://drive.google.com/file/d/1Bj0OfTUzfWZo6Ck6xYnjtcIlzWzN7JAX/view?usp=sharing
It uses this script to load some data first (although not all the data is really required)
https://drive.google.com/file/d/11oSm0oSYxfpssGRJFMsZMLBZCTZQ-VE0/view?usp=sharing
This is the pharmaprojects dataset I have used so far:
https://drive.google.com/file/d/13Jp7uhtIqogAi9u0c-aUlVAsnaeCpkqR/view?usp=sharing
Pharmaprojects traits were mapped from Mesh to EFO using this static file (from OxO):
https://drive.google.com/file/d/1-PLhiBH8Sg2GIj2ThxsvsjN-PRp8X027/view?usp=sharing
But it would make more sense to read that info from our disease index from now on

**Comment by d0choa** [comment]
To compensate for my absolute lack of specification...

The objective is to be able to "benchmark" how associations perform on our releases. We want to:
- Use as gold standard a list of targets of approved drugs. Alternatively, this set could be changed to other gold standards (e.g. all targets of drugs in clinical trials)
- Compute the odds ratio enrichment (and 90 or 95% CI)  for each datasource associations and overall on targets of approved drugs.
- Compute the AUC (and 90 or 95% CI) for each datasource and overall when predicting targets of approved drugs using the association score as a predictor.

A plot containing the metrics for 20.02 data (old schema). (Note: the axis says evidence when in fact it refers to associations)
![image](https://user-images.githubusercontent.com/5097586/117270673-5cf3d600-ae51-11eb-909c-c5e96c1c0344.png)

As today, there is a bug (#1508) in the association scores provided in the datasets that don't reflect what returned by the API. Performance metrics might not be accurate until that bug is fixed.

**Comment by tskir** [comment]
Transferring relevant discussions from https://github.com/opentargets/ot-release-metrics/pull/3:

### Questions
- **Gold standard provenance**
  + [x] Where is the main gold standard dataset, `informa_abbvie.tsv`, obtained from? Googling led me to this file: https://raw.githubusercontent.com/AbbVie-ComputationalGenomics/genetic-evidence-approval/master/data/target_indication_nmsh.tsv; however, it appears to be smaller than the one we have. — URL is correct, it comes from Pharmaprojects; discrepancy may be due to a difference in supplementary vs. repository. See paper for details. Possible alternative is ChEMBL, which has approval status, but not indication for specific disease.
  + [x] Where are the MeSH mappings obtained from? — From OxO, this can be downloaded as a flatfile, and MeSH to EFO coverage is good.
  + [x] What are the numbers in the MeSH mapping file, e.g. “EFO:0000274 / atopic eczema / MeSH:D003876 / **0.700000** / Dermatitis, Atopic”? Are those mapping scores? Do we want to use them in any way? — Look into the source (OxO).
- **Metric calculation.** Given both the performance hit and proliferation of the number of metrics, we need to decide whether we want to calculate AUC and OR:
  + [x] Both for direct and indirect associations? — Yes.
  + [x] Over all approval status tiers (approved, phase 3, phase 2, ...)? — Do two: Approved (yes/no) and In trials (any phase).
  + [x] Over approval year tiers (2009-2018, 1998-2008, ...)? — No.
- **General questions.**
  - [x] Do we have an expected timeline on fixing https://github.com/opentargets/platform/issues/1508? Since the scores in the downloadable files are wrong, it seems like a rather critical bug. Do we expect the 21.04 files to be recalculated, or will this just be fixed for the 21.06 release? — The scores are actually almost OK, just inconsistent (two different implementations).

**Comment by tskir** [comment]
### Remaining actions
- Gold standard provenance
  + [ ] Add information about provenance
  + [ ] See if there is a newer version of the data
- MeSH mapping provenance
  + [ ] Add information about provenance
  + [ ] See if there is a newer version of the data
  + [ ] Look into the score column (probably) in the mappings
- Calculation updates
  + [ ] Calculate confidence intervals in addition to values
  + [ ] Calculate two sets: approved (yes/no) and in trials (any phase)
  + [ ] Look into ways to improve performance
- Calculation comparisons
  + [ ] Double check the calculations
  + [ ] Compare with data calculated by David (20.02). Expectations:
    * literature—whole pipeline has changed
    * ClinVar — look into that
    * intogen should be essentially the same
    * genetic portal should be exactly the same
- Exchange and representation updates
  - [ ] Reorganise file format for backend/frontend exchange: either have multiple files, or migrate to something more structured
  - [ ] Think about how to represent/plot this in the frontend
  - [ ] Add frontend implementation

**Comment by d0choa** [comment]
@tskir and @ireneisdoomed are we happy to consider this ticket closed? There is a working benchmark at the moment. Can we consider any pending actions as follow up tickets?

**Comment by ireneisdoomed** [comment]
This piece of work is closed with PR [#13](https://github.com/opentargets/ot-release-metrics/pull/13) and PR [#3](https://github.com/opentargets/ot-release-metrics/pull/3).
