### ISSUE TITLE
Deprecate the Open Targets REST API

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1521]
With the launch of the next-generation Platform, we must deprecate the REST API as it contains outdated data and schema.

@cmalangone, once I have confirmed with all partners and collaborators that we are safe to shut down the REST API, can you please do the following?

- [x] Shut down the VMs and other infrastructure supporting the `production` REST API and `qa` REST API
- [x] Archive any necessary repos

I will update the classic Platform documentation along with other links and sites that reference the REST API.

**Comment by cmalangone** [comment]
REST API and ElasticSearch are down.

**Comment by cmalangone** [comment]
@ktsirigos and I will Archive any necessary repos this Friday during our meeting

**Comment by ktsirigos** [comment]
work completed
