### ISSUE TITLE
Display navbar content on home page (and big screen) 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1522]
We want to explore the possibility to show the navigation menu content on the homepage when a big screen is available.

Nothing fancy just use whatever standard implementation is available in Material UI. Some examples to get the point:
- [Example for React Bootstrap](https://react-bootstrap.github.io/components/navbar/#navbars-mobile-friendly)
- [Example for React Material UI](https://betterprogramming.pub/making-a-basic-header-responsive-with-materialui-and-react-2198fac923c8)

**Comment by andrewhercules** [comment]
Also, note that navigation menu currently not working on `main` branch

**Comment by andrewhercules** [comment]
@carcruz could you please investigate this?

@d0choa would like the navigation menu to be visible on the homepage but then collapsed into the hamburger menu icon on the other pages (e.g. target profile page, search, evidence, etc.).

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main`
