### ISSUE TITLE
Migrate Ghost from self-hosted version to hosted version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1523]
Currently, we host our Ghost v1.22.7 blog using a small Google Cloud VM (1CPU, 2GB). Upon review, it was determined that updating to the latest version — Ghost v4 — would be difficult to due to compatibility issues and the need to install multiple updates.  

In order to utilise the new features available in Ghost v4, we have decided to host our Ghost blog with https://ghost.org/. 

Last week, we imported all existing content (including posts and images), authors/contributors/editors, and settings from our self-hosted version. 

@HelenaCornu can you please review the new version of the blog, making adjustments to the layout, content (e.g. tags), and features?  

Once you have approved it for migration, we can sign up for the "Starter" plan at $9 USD/month. 

We will then ask @cmalangone to:

1. Update the `blog.opentargets.org` CNAME to point to the new host
2. Turn off the VM in the `open-targets-prod` project

**Comment by cmalangone** [comment]
@HelenaCornu just let me know when you have the info about the CNAME

**Comment by andrewhercules** [comment]
Ticket closed as blog content has been migrated to Ghost.org, CNAME updated, and Google VM shutdown
