### ISSUE TITLE
Add canonical <link> tags

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1524]
In the [classic Platform webapp](https://github.com/opentargets/webapp/search?q=canonical_url), we generated a canonical `<link rel="canonical" href="xxxxx">` tag for each page. The canonical link supported our search engine optimisation efforts by declaring the public Platform URL as the URL to be indexed in cases where multiple instances of the same page might be available (e.g. Netlify branch deploy preview).

Can we please reimplement canonical `<link rel="canonical" href="xxxxx">` tags for each static page and page type?

baseUrl: `https://platform.opentargets.org`

| Page | `href` value construct | Example tag |
| --- | --- | --- |
| Homepage | `baseUrl` | `<link rel="canonical" href="https://platform.opentargets.org">`|
| Variants page | `baseUrl` + `/` + `variants` | `<link rel="canonical" href="https://platform.opentargets.org/variants">` |
| Data downloads page | `baseUrl` + `/` + `downloads` | `<link rel="canonical" href="https://platform.opentargets.org/downloads">` |
| Target associations page | `baseUrl` + `/target/` + `targetId` + `/` + `associations` | `<link rel="canonical" href="https://platform.opentargets.org/target/ENSG00000091831/associations">`|
| Disease associations page | `baseUrl` + `/disease/` + `diseaseId` + `/` + `associations` | `<link rel="canonical" href="https://platform.opentargets.org/disease/EFO_0000685/associations">`|
| Evidence page | `baseUrl` + `/evidence/` + `targetId` + `/` + `diseaseId` | `<link rel="canonical" href="https://platform.opentargets.org/evidence/ENSG00000232810/EFO_0000685">`|
| Target profile page | `baseUrl` + `/target/` + `targetId` | `<link rel="canonical" href="https://platform.opentargets.org/target/ENSG00000232810">`|
| Disease profile page | `baseUrl` + `/disease/` + `diseaseId` | `<link rel="canonical" href="https://platform.opentargets.org/disease/EFO_0003767">`|
| Drug profile page | `baseUrl` + `/drug/` + `drugId` | `<link rel="canonical" href="https://platform.opentargets.org/drug/CHEMBL1431">`|

**Comment by andrewhercules** [comment]
Ticket added to 21.06 release

**Comment by ktsirigos** [comment]
closing issue as work done.
