### ISSUE TITLE
Move evidence page GraphQL queries to .gql files

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1526]

**Comment by d0choa** [comment]
```
❯ find . -type f -name '*.js' -exec grep -H "= gql\`" {} \; | grep -i /evidence
```

- [ ] ./src/sections/evidence/ClinGen/Body.js:const CLINGEN_QUERY = gql`
- [ ] ./src/sections/evidence/ClinGen/Summary.js:const CLINGEN_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/EVA/Body.js:const CLINVAR_QUERY = gql`
- [ ] ./src/sections/evidence/EVA/Summary.js:const EVA_SUMMARY = gql`
- [ ] ./src/sections/evidence/PheWASCatalog/Body.js:const PHEWAS_CATALOG_QUERY = gql`
- [ ] ./src/sections/evidence/PheWASCatalog/Summary.js:const PHEWAS_CATALOG_SUMMARY = gql`
- [ ] ./src/sections/evidence/UniProtVariants/Body.js:const UNIPROT_VARIANTS_QUERY = gql`
- [ ] ./src/sections/evidence/UniProtVariants/Summary.js:const UNIPROT_VARIANTS_SUMMARY = gql`
- [ ] ./src/sections/evidence/CancerGeneCensus/Summary.js:const CANCER_GENE_CENSUS_SUMMARY = gql`
- [ ] ./src/sections/evidence/OTGenetics/Summary.js:const OPEN_TARGETS_GENETICS_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/GenomicsEngland/Summary.js:const GENOMICS_ENGLAND_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/CRISPR/Body.js:const CRISPR_QUERY = gql`
- [ ] ./src/sections/evidence/CRISPR/Summary.js:const CRISPR_SUMMARY = gql`
- [ ] ./src/sections/evidence/UniProtLiterature/Body.js:const UNIPROT_LITERATURE_QUERY = gql`
- [ ] ./src/sections/evidence/UniProtLiterature/Summary.js:const UNIPROT_LITERATURE_SUMMARY = gql`
- [ ] ./src/sections/evidence/ExpressionAtlas/Body.js:const EXPRESSION_ATLAS_QUERY = gql`
- [ ] ./src/sections/evidence/ExpressionAtlas/Summary.js:const EXPRESSION_ATLAS_SUMMARY = gql`
- [ ] ./src/sections/evidence/SysBio/Summary.js:const SYSBIO_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/Chembl/Body.js:const CHEMBL_QUERY = gql`
- [ ] ./src/sections/evidence/Chembl/Summary.js:const CHEMBL_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/EVASomatic/Body.js:const EVA_SOMATIC_QUERY = gql`
- [ ] ./src/sections/evidence/EVASomatic/Summary.js:const EVA_SOMATIC_SUMMARY = gql`
- [ ] ./src/sections/evidence/EuropePmc/Summary.js:const EUROPE_PMC_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/Progeny/Summary.js:const PROGENY_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/SlapEnrich/Summary.js:const SLAPENRICH_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/Phenodigm/Summary.js:const PHENODIGM_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/Gene2Phenotype/Summary.js:const GENE_2_PHENOTYPE_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/IntOgen/Summary.js:const INTOGEN_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/evidence/Reactome/Summary.js:const REACTOME_SUMMARY = gql`
- [ ] ./src/pages/EvidencePage/Profile.js:const EVIDENCE_PROFILE_QUERY = gql`
- [ ] ./src/pages/EvidencePage/EvidencePage.js:const EVIDENCE_PAGE_QUERY = gql`

**Comment by ktsirigos** [comment]
work done
