### ISSUE TITLE
Move target profile page GraphQL queries to .gql files

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1529]

**Comment by d0choa** [comment]
```
❯ find . -type f -name '*.js' -exec grep -H "= gql\`" {} \; | grep -i /Target
```

- [ ] ./src/sections/target/Tep/Summary.js:const TEP_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/CancerHallmarks/Summary.js:const CANCER_HALLMARKS_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/Bibliography/Body.js:const TARGET_LITERATURE_OCURRENCES = gql`
- [ ] ./src/sections/target/Bibliography/Summary.js:const SIMILARENTTIES_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/ProteinInformation/Summary.js:const PROTEIN_INFORMATION_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/ChemicalProbes/Summary.js:const CHEMICAL_PROBES_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/KnownDrugs/Body.js:const KNOWN_DRUGS_BODY_QUERY = gql`
- [ ] ./src/sections/target/KnownDrugs/Summary.js:const KNOWN_DRUGS_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/CancerBiomarkers/Body.js:const BIOMARKERS_QUERY = gql`
- [ ] ./src/sections/target/CancerBiomarkers/Summary.js:const CANCER_BIOMARKERS_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/Tractability/Summary.js:const TRACTABILITY_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/MolecularInteractions/Body.js:const INTERACTIONS_STATS_QUERY = gql`
- [ ] ./src/sections/target/MolecularInteractions/Summary.js:const MOLECULAR_INTERACTIONS_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/MousePhenotypes/Summary.js:const MOUSE_PHENOTYPES_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/Expression/SummaryTab.js:const EXPRESSION_QUERY = gql`
- [ ] ./src/sections/target/Expression/Summary.js:const EXPRESSION_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/Pathways/Summary.js:const PATHWAYS_SUMMARY_FRAGMENT = gql`
- [ ] ./src/sections/target/GeneOntology/Summary.js:const GENE_ONTOLOGY_SUMMARY_FRAGMENT = gql`
- [ ] ./src/pages/TargetPage/ClassicAssociationsTable.js:const TARGET_ASSOCIATIONS_QUERY = gql`
- [ ] ./src/pages/TargetPage/Profile.js:const TARGET_PROFILE_QUERY = gql`
- [ ] ./src/pages/TargetPage/ProfileHeader.js:const TARGET_PROFILE_HEADER_FRAGMENT = gql`
- [ ] ./src/pages/TargetPage/TargetPage.js:const TARGET_PAGE_QUERY = gql`
- [ ] ./src/pages/TargetPage/Wrapper.js:const ASSOCIATIONS_VIZ_QUERY = gql`
- [ ] ./src/pages/TargetPage/ClassicAssociations.js:const TARGET_FACETS_QUERY = gql`

**Comment by mirandaio** [comment]
Closed by https://github.com/opentargets/platform-app/pull/376 

The only query that has not been extracted is the one found here https://github.com/opentargets/platform-app/blob/main/src/pages/TargetPage/Profile.js because it's built programmatically.
