### ISSUE TITLE
Improve MedDRA cross-references in EFO

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1533]
To keep track of the [issue](https://github.com/EBISPOT/efo/issues/1088) opened to EFO to improve the MedDRA/EFO coverage.

**Comment by ireneisdoomed** [comment]
EFO has imported over 2000 high confidence MedDRA x-refs into EFO where the MedDRA label and the EFO/Orphanet label are the same.

They will be gradually importing the less confident ones to elucidate whether the x-refs are broad, exact, narrow or related.

As EFO dynamically imports MONDO, DOID, and HP terms, these xrefs have to be assessed by them, and not by EFO. So the corresponding issues have been opened:
- [Request to MONDO](https://github.com/monarch-initiative/mondo/issues/3122)
- [Request to DOID](https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/947)
- [Request to HP](https://github.com/obophenotype/human-phenotype-ontology/issues/6999)

**Comment by d0choa** [comment]
All ontologies but MONDO have completed the task as today. No action is required on our side
