### ISSUE TITLE
OnToma: Rewrite, refactor and benchmark OnToma codebase

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1534]
_Below summary added and maintained by @tskir_

### The rewrite
- [x] Submit PR: https://github.com/opentargets/OnToma/pull/18

### Rewrite benchmark, iteration 1
- [x] Select term sources for benchmark: ClinVar, PhenoDigm, gene2phenotype
- [x] Create a random sample of terms to benchmark
- [x] Run OnToma before the rewrite
- [x] Bugfix: `identifier.org` URL handling
- [x] Bugfix: use the original manual mapping source instead of the boilerplate
- [x] Run OnToma after the rewrite

### Rewrite benchmark, iteration 2
- [x] Feature: implement returning multiple columns for every result
- [x] Adjust benchmark commands to output query, full URI, and label
- [x] Update the tests to reflect new output format
- [x] Update the documentation to reflect new output format
- [x] Adjust benchmark instructions to add PanelApp phenotypes
- [x] Re-run the updated benchmark
- [x] Write and document the benchmark collate script
- [x] Fetch EFO label and inclusion status in the script 
- [x] Set up the benchmark spreadsheet
- [x] Curate the validation set of 400 mappings
- [x] Calculate final benchmark results: (sens 96%, prec 75%) → (sens 61%, prec 97%)

### v1.0.0 release preparation
Part 1
- [x] Fix pytest collection issue
- [x] More careful check for EFO cache consistency
- [x] Address code review comments, iteration 1

Part 2
- [x] Retry on GitHub “API rate limit exceeded” response
- [x] Add parameter to specify EFO release to use
- [x] Improve error message when the EFO release is missing files
- [x] Address code review comments, iteration 2

Part 3
- [x] Apply hotfix to pin EFO to v3.31.0
- [x] Extract remaining points into separate issues
- [x] Amend and adjust the release notes

Part 4
- [x] Merge the PR
- [x] Release v1.0.0 on GitHub
- [x] Release v1.0.0 on PyPi
- [x] Add instructions for releasing on PyPi
- [x] Fix documentation build failure

Part 5
- [x] Submit the follow-up PR
- [x] Set up the Open Targets ReadTheDocs account
- [x] Follow up with Eliseo about ReadTheDocs account
- [x] Follow up with Zoe about EFO bug

Part 6
- [x] Amend v1.0.0 release on GitHub
- [x] Rebuild ReadTheDocs versions

**Comment by tskir** [comment]
So, to start compiling the list for the unification, we have:
* EVA: https://github.com/EBIvariation/eva-opentargets/tree/master/eva_cttv_pipeline/trait_mapping
* OnToma: https://github.com/opentargets/OnToma
* Whatever logic (probably cross-refs) which was used by the [old PhenoDigm parser](https://github.com/opentargets/evidence_datasource_parsers/blob/ee604e27d760981631cd61d3ba4429674cedfc5e/modules/MouseModels.py)

@ireneisdoomed I believe you also mentioned some mapping process used for the PanelApp, do you think you could point me in the direction of this? I've tried taking a look at https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/GenomicsEnglandPanelApp.py, but as far as I can see it uses vanilla OnToma + some manually curated mappings, so perhaps there's something else?

**Comment by ireneisdoomed** [comment]
The mapping logic for Panel App is indeed vanilla OnToma with this added feature: 

> - Exact matches to an EFO term are used directly.
> - Sometimes an OMIM code can be present in the disease string. OnToma is then queried for both the OMIM code and the respective disease term. If OnToma returns a fuzzy match for both, it is checked whether they both point to the same EFO term. Being this the case, the term is considered as an exact match.

The other particularity of Panel App is that a number of disease labels are captured in a manually curated file due to the diversity between their reported labels and the diseases described in the ontologies, as described in [#1400](https://github.com/opentargets/platform/issues/1400). This file is used as a source by Zooma and at the moment they are using an obsolete version.

**Comment by DSuveges** [comment]
It's worth checking the logic in the [gene2phenotype](https://github.com/opentargets/OnToma/pull/16) parser as well.

**Comment by tskir** [comment]
After some fights with ReadTheDocs build system, I'm delighted to announce that all actions are now complete and this huge ticket is now officially done :tada:
