### ISSUE TITLE
Correct Ensembl protein IDs that appear wrong in target A/target B interactions

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1539]

**Comment by cmalangone** [comment]
the issue is in this piece of code
  .withColumn("targetA", when(col("gene_id").isNull, col("intA")).otherwise(col("gene_id")))
and
  .withColumn("targetB", when(col("gene_id").isNull, col("intB")).otherwise(col("gene_id")))

**Comment by cmalangone** [comment]
Released the new dataset.
The issue is fixed.
