### ISSUE TITLE
Bibliography widget crashing on certain query

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1540]
Page crashes when visiting COVID-19 disease page [link](https://platform.opentargets.org/disease/MONDO_0100096), and selecting `ACE2` and `CAMOSTAT`.

**Comment by andrewhercules** [comment]
Issue resolved in `main` branch for 21.06 release

https://main--platform-app.netlify.app/disease/MONDO_0100096

![Screenshot 2021-06-21 at 13 44 39](https://user-images.githubusercontent.com/7490258/122763964-da0acb80-d296-11eb-8b35-ec7bfe54080a.png)

**Comment by ktsirigos** [comment]
closing this as work is done
