### ISSUE TITLE
Generate a list of essential drugs for testing purposes

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1541]
A small subset of drug IDs that represents a variety of different types is essential to feed our drug API tests.  @JarrodBaker will need it to be integrated into the API test suite.

**Comment by d0choa** [comment]
@andrewhercules add your usual suspects here as well, so Irene takes them into account.

**Comment by andrewhercules** [comment]
Here are the drugs that I commonly look at when reviewing new release data

CHEMBL121:
This molecule has both withdrawn and black-box warnings

CHEMBL122:
This drug has a withdrawn warning, but a new study record from December 2020 — [NCT04684511](https://clinicaltrials.gov/ct2/show/NCT04684511) — should bring in new evidence for [hemophilic arthropathy (MONDO_0043240](http://purl.obolibrary.org/obo/MONDO_0043240).

CHEMBL160
This drug has multiple spellings (e.g. Ciclosporin, Cyclosporine) - important that `molecule` dataset and API return all synonyms 

CHEMBL1431 and CHEMBL1059
These drugs target a protein complex or family so expect 20+ targets returned in the mechanisms of actions data.

CHEMBL822 and CHEMBL1201736
These drugs have non-human targets

CHEMBL2104790 and CHEMBL1201301
These drugs have no curated mechanism of action

CHEMBL4594260 and CHEMBL3414621:
These are parent-child molecules. Within the `indication` dataset, the approved indication (sarcoma) has been tagged to the child molecule (CHEMBL4594260) only, whereas we have ChEMBL evidence for the parent molecule (CHEMBL3414621) and sarcoma.

CHEMBL4594350
This drug is not found in our `molecule` dataset or API as the mechanism of action ([KRAS inhibitor](https://go.drugbank.com/drugs/DB15568) - see [PubMed #31658955](https://pubmed.ncbi.nlm.nih.gov/31658955/)) and clinical trials ([5 ongoing trials](https://clinicaltrials.gov/ct2/results?cond=&term=MRTX-849)) have not been curated upstream.

**Comment by d0choa** [comment]
Please don't use `CHEMBL4594350` from @andrewhercules for testing :)

**Comment by andrewhercules** [comment]
Yes, `CHEMBL4594350` isn't suitable for testing — it's just my own reminder about searching for the KRAS inhibitors MRTX-849 and AMG-510 😂

**Comment by d0choa** [comment]
@andrewhercules can you get top10 drugs in analytics?

**Comment by andrewhercules** [comment]
Here's the top 10 for 2021:

CHEMBL2051955
CHEMBL221959
CHEMBL1431
CHEMBL2010601
CHEMBL803
CHEMBL1201581
CHEMBL1431
CHEMBL2108709
CHEMBL656
CHEMBL807

**Comment by d0choa** [comment]
I would add to the previous list:

CHEMBL3301572
Nusinersen is an oligonucleotide. Targeting mRNA. Unfortunately, we don't have the target.

CHEMBL255863
Nilotinib is suppose to target BCR-ABL gene fusion. Not greatly captured by ChEMBL or us.

**Comment by ireneisdoomed** [comment]
@JarrodBaker Can we close this?
