### ISSUE TITLE
rename api repository to a new one

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1542]
From `platform-api-beta` to `platform-graphql-api`. dependencies to double-check and correct if needed:

- travis
- quay.io
- terraform
- ...

**Comment by cmalangone** [comment]
@JarrodBaker and @mbdebian 
Starting this job and update the steps execution here

**Comment by cmalangone** [comment]
The name 

- [ ] Rename github and .travis
- [ ] Travis config
- [ ] Quay info
- [ ] Change the GraphQL appEngine info
