### ISSUE TITLE
Update deployment process to use sitemaps from platform-output-support

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1545]
Given the new sitemaps generated in https://github.com/opentargets/platform/issues/1485, `platform-output-support` will be responsible for the generation of sitemaps (https://github.com/opentargets/platform/issues/1505) and the deployment step will be responsible for taking the front-end codebase and injecting the new sitemaps (https://github.com/opentargets/platform/issues/1545). 

Can we please adjust the deployment process to use the sitemaps generated by `platform-output-support`?

**Comment by mbdebian** [comment]
I'll have a look at this, thanks @andrewhercules

**Comment by mbdebian** [comment]
[ot-sitemaps](https://github.com/opentargets/ot-sitemap-cli) is being integrated with Travis (https://github.com/opentargets/ot-sitemap-cli/pull/3) for automated assembly of the jar file that will be run by the provisioner, currently being tested at this terraform provisioner [branch](https://github.com/opentargets/terraform-google-opentargets-platform/tree/sitemaps)

**Comment by andrewhercules** [comment]
Ticket closed as sitemaps generated and indexed by Google and Bing
