### ISSUE TITLE
Remove sitemaps directory from front-end codebase

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1546]
Given the new sitemaps generated in https://github.com/opentargets/platform/issues/1485, `platform-output-support` will be responsible for the generation of sitemaps (https://github.com/opentargets/platform/issues/1505) and the deployment step will be responsible for taking the front-end codebase and injecting the new sitemaps (https://github.com/opentargets/platform/issues/1545). 

Can we please remove the `/sitemaps` directory?

**Comment by ktsirigos** [comment]
closing issue as work done.
