### ISSUE TITLE
Update `platform-app` documentation

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1556]
Can we please update the [`sections.md` documentation](https://github.com/opentargets/platform-app/blob/main/docs/sections.md)?

- Review content to ensure it is correct and reflects our current practices
- Add recommendation on extracting GraphQL queries to their own file 
- Add steps on how to integrate new publications drawer widget
- In the "Other examples" section, update examples to include evidence page widget, remove Related Diseases example and Comparative Genomics example

**Comment by andrewhercules** [comment]
Re-scoping for 21.09

**Comment by ktsirigos** [comment]
work completed, merged into main.
