### ISSUE TITLE
Associated Targets Page : Experience Lag when trying to filter the subclass items. 

### ISSUE THREAD

**Issue by bhandaris4** [opentargets/platform#1562]
There is a noticeable amount of lag when filtering the options from Data Types or Target Classes.

**Comment by andrewhercules** [comment]
Hi @bhandaris4!

Thank you for reporting this. So that we can investigate further, can you please provide me with additional details? For example, what disease or target associations pages were you visiting? Was this seen on the public version of the Platform or a private internal instance?

Thank you!

**Comment by bhandaris4** [comment]
I have experienced the lag in almost all test data associated to Targets and Diseases. Since targets have less number of filtering options, the lag is very minimal, but with diseases, there is noticeable amount of lag. 

One of the test data I used is : schizophrenia

1. Go to URL : https://platform.opentargets.org/disease/EFO_0000692/associations
2. On Associated Targets tab, Expand PathWay-Types or TargetClasses and check/uncheck the items and sub-items. 
3. You will notice a considerable amount of lag. 

This happens with most of the listings on the page. 

I will be attaching a short video clip shortly.

**Comment by andrewhercules** [comment]
@bhandaris4, when you select a filter option (e.g. pathway type) on an associations page, the ClickHouse infrastructure is (re)computing the association scores using our associations-on-the-fly approach. At the same time, it is also recalculating the available filters (e.g. selecting a pathway type might mean there is no genetic or known drugs evidence). And so the "lag" and loading state is expected given the complex calculations handled by ClickHouse.
