### ISSUE TITLE
Filter : Parent List-item sum exceeds the sum of sub-list items

### ISSUE THREAD

**Issue by bhandaris4** [opentargets/platform#1563]
The total value of the parent item is more than the sum of all children items added together.

The numbers of the total results seem to fluctuate as we make changes to selection on the child items. When selecting multiple sub-list items for data filter purpose, the sum of individual total do not match to the total search results. 

 Steps to Reproduce : 

In OpenTarget Platform, search for any Disease, Drug or Target. (I searched for 
schizophrenia or EFO_0000692)
![Error on Cell-Cell-Communicaton Total Count_TargetClasses](https://user-images.githubusercontent.com/84523825/119027103-f5bb4300-b973-11eb-80b1-27c3652b58c0.jpg)
![Error on Enzyme Total Count_TargetClasses](https://user-images.githubusercontent.com/84523825/119027117-f9e76080-b973-11eb-8b88-7de154d8f7e8.jpg)
![Error on MembraneReceptor Total Count_TargetClasses](https://user-images.githubusercontent.com/84523825/119027132-fd7ae780-b973-11eb-9be5-d4b5f549a357.jpg)

In Associates Tab, go to Filter by Target Specific Filters > Target Classes
Select Membrane Receptor. Verify the total target associated is 194. 
Expand the Membrane Receptor and add the Target Associations of each sub-item. 
Verify the Membrane Receptor total is more than the total of membrane-total sub-items.

**Comment by DSuveges** [comment]
It's practically the same issue as in #1564
