### ISSUE TITLE
Download Table As links fail to function when when data count is higher

### ISSUE THREAD

**Issue by bhandaris4** [opentargets/platform#1565]
I attempted to download the table data in CSV format for various sections of the application like Drug Information, Known Drug etc. The download fails sometimes (mostly with large data sets > 200).

Error Message : This Page isn't responding. Wait/Exit Page.

**Comment by andrewhercules** [comment]
Hi @bhandaris4!

Thank you for reporting this. We are currently working on the table component and expect to push further changes in 21.06 that will address these issues. 

Can you confirm, was this issue seen when trying to download a specific file format? All file formats?

Thank you!

**Comment by andrewhercules** [comment]
Another user has contacted the help desk, reporting that they are unable to download data tables.

```
I’ve been trying to use the opentargets platform to identify gene-disease association information.
 
Whilst it is working for the overall high level csv, I’m struggling to download successfully any csv files from the “Evidence for x gene in y disease”for the Europe PMC, ChEMBL, COSMIC etc csv files (where it offers to download table as JSON, CSV and TSV but then doesn’t allow me to actually download these files.
```

I am flagging this as high-priority for our next release — 21.06 — scheduled for release w/c 28 June 2021.

**Comment by bhandaris4** [comment]
The issue has been persistent with almost all file formats if the data count is higher. But that does not mean it wont work for a larger data set at all.

**Comment by bhandaris4** [comment]
Trying to attach the error screenshots, but it won't accept them.

**Comment by andrewhercules** [comment]
@carcruz, can you please do a quick investigation into this? 

The Known Drugs table on the profile pages (e.g. [asthma](https://platform.opentargets.org/disease/EFO_0000270/associations)) does not download in CSV/TSV/JSON format. 

I wondered if there's an issue with the [getWholeDataset function](https://github.com/opentargets/platform-app/blob/main/src/sections/common/KnownDrugs/Body.js#L200) or [useCursorBatchDownloader](https://github.com/opentargets/platform-app/blob/main/src/hooks/useCursorBatchDownloader.js#L23). Or perhaps a recent change to the table component?

**Comment by mirandaio** [comment]
There were some changes in the behaviour of cursor paging which were not addressed in the downloads. To fix, we should change `while (chunksFetched < chunksToFetch || cursor === null) {` to `while (chunksFetched < chunksToFetch) {` in `useCursorBatchDownloader` @carcruz

**Comment by carcruz** [comment]
Thanks @mirandaio,  the fix is working as expected. PR up https://github.com/opentargets/platform-app/pull/402

**Comment by ktsirigos** [comment]
closing this as work is done
