### ISSUE TITLE
Target safety: reference to HeCaToS is broken

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1566]
The [reference link to HeCaToS](http://www.hecatos.eu/IManager/Download/687/66208/16240/1534958/EN/16240_1534958_NCDS_D1.5_Package_of_predictive_models_of_target-pathway-ADME_activities__M21.pdf) throws 404 error.

Actions:
- [x] Update link in the working spreadsheet for safety data 
- [x] @JarrodBaker has parsed the spreadsheet into 2 static files (adverse events, safety risk). We would need to regenerate them.

**Comment by d0choa** [comment]
Please don't include the link in the data. Only include `urls` when they can not be easily built from the source or you can have one page for entry that you can not compose based on the data.

If we know the source is HeCaTos we can build the link in the FE.

**Comment by ireneisdoomed** [comment]
The HeCaToS reference website (www.hecatos.eu) is and will remain closed, according to Prof. Kleinjans, the point of contact for the project.

The alternative link out is the Cordis website (https://cordis.europa.eu/project/id/602156/reporting), where all the different results and publications can be consulted. This URL will be static, so there's no point in storing it in the schema. 

Can FE take it from here and change the link from http://www.hecatos.eu/IManager/Download/687/66208/16240/1534958/EN/16240_1534958_NCDS_D1.5_Package_of_predictive_models_of_target-pathway-ADME_activities__M21.pdf
to
https://cordis.europa.eu/project/id/602156/reporting ?

The tooltip of the link should also be removed, as we are no longer linking to the specific deliverable document.

**Comment by andrewhercules** [comment]
For the front-end, can we please adjust the [safety link and tooltip logic](https://github.com/opentargets/platform-app/blob/5c11d12cf957c6fa6053d0eb3fc22d235ec82993/src/sections/target/Safety/SafetyTables.js#L255)? Specifically, when `"refLabel": "HeCaToS"`, can we please update the `refLink` to  `https://cordis.europa.eu/project/id/602156/reporting` as noted above?

[MTOR - ENSG00000198793 query](https://api.platform.opentargets.org/api/v4/graphql/browser?query=query%20targetSafety%20{%20target(ensemblId:%22ENSG00000198793%22){%20safety{%20safetyRiskInfo{%20references{%20refLink%20refLabel%20}%20}%20}%20}%20})

**Comment by ktsirigos** [comment]
closing issue as work done.
