### ISSUE TITLE
Propose an event for safety risk information data sources

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1567]
The latest version (iter 3) of the [new safety object ](https://docs.google.com/spreadsheets/d/1W_KJoozote06h3-mrVeHZN02VVXrpwG42nhGjUR-0Gk/edit?ts=606ecf7d#gid=1514939258) does not describe any safety liability. 

From these data sources, we currently annotate a general description of the target's role. This description is not currently covered in any field of the new schema.

Actions:

- [x] Reconsider the value of the ["Safety Liability" column] (https://docs.google.com/spreadsheets/d/1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0/edit#gid=1760619926) for inclusion in the new scheme. --> We will keep it for now and eventually drop it if it not in use.

- [x] Curated publications are all referring to clinical cardiotoxicity cases Can we extract a less general liability from the source?

**Comment by BZdrazil** [comment]
Safety targets from Force et al. and Lamore et al. can also be annotated with EFO terms describing the adverse event.

For targets from Lamore et al. I suggest to annotate them with the phenotype/adverse effect “cardiac arrhythmia” (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004269)

For targets from Force et al. I would annotated with the more general term “heart disease” (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003777)

**Comment by ireneisdoomed** [comment]
Thank you very much @BZdrazil!

After revision, the proposed safety liabilities for the annotation of safety risk information data sources will be as follows:
- **Force et al. (2011)**: Heart disease - EFO_0003777
- **Lamore et al. (2017)**: cardiac arrhythmia - EFO_0004269

For the evidence coming from HeCaToS, it is essentially a duplication of Force et al., since the annotation of the latter comes from a deliverable set in the context of the HeCaToS program: https://drive.google.com/file/d/11YFuHIOYhWOYS76sOQt0V-ZzVU0YEH_2/view

Therefore, **HeCaToS** will be annotated following the same approach as Force et al: Heart disease - EFO_0003777

**Comment by ireneisdoomed** [comment]
Thank you very much @BZdrazil!

After revision, the proposed safety liabilities for the annotation of safety risk information data sources will be as follows:
- **Force et al. (2011)**: Heart disease - EFO_0003777
- **Lamore et al. (2017)**: cardiac arrhythmia - EFO_0004269

For the evidence coming from HeCaToS, it is essentially a duplication of Force et al., since the annotation of the latter comes from a deliverable set in the context of the HeCaToS program: https://drive.google.com/file/d/11YFuHIOYhWOYS76sOQt0V-ZzVU0YEH_2/view

Therefore, **HeCaToS** will be annotated following the same approach as Force et al: Heart disease - EFO_0003777

**Comment by BZdrazil** [comment]
Thanks for the information! I agree that the HeCaToS annotations are overlapping (I wasn't aware they were exact duplicates!) of the literature data sets. Will we keep the annotations to the HeCaToS project? IMO it is not really needed if it was a duplication effort. Also it was an EBI internal project, right, so would bt say much to people from outside anyway?
