### ISSUE TITLE
References in the Known Drugs table are invalid

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1568]
The Source column in the Known Drugs table for a disease is not correct.

For example, for the disease [MONDO_0002974](https://platform.opentargets.org/disease/MONDO_0002974), this column is mostly blank and the name of the references we are capturing is not nicely formatted (`undefined entry` instead of the urls.name field from the API response): 

![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/ae8faa15-50cd-4853-a26b-4fafdc30da9b)

The GraphQL query returns the data correctly, so it must come from the FE side. 
```
query assocs {
  disease(efoId:"MONDO_0002974") {
    name
		knownDrugs {
      rows {
        target {
          approvedSymbol
        }
      	drug {
          name
        }
        urls {
          url
          name
        }
      }
    }
}
}
```

**Comment by andrewhercules** [comment]
Scoping this for inclusion in the 21.06 release.

This issue has been found on the target and disease/phenotype profile pages (Known Drugs) and drug profile pages (Clinical Precedence).

**Comment by ktsirigos** [comment]
closing this as work is done
