### ISSUE TITLE
Standardise CT Phase format across the Platform

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1569]
Phases of clinical trials are often referred to in roman numerals whereas we are using a different style for this in different places along the Platform:

1. In the Known Drugs table for a particular disease - Column `Phase`,
2. In the description of a particular drug - Field `Max Phase`,
3. In the Indications table for a particular drug - Column `Max Phase`,
4. In the Clinical Precedence table for a particular drug -  Column `Phase`

We should standardise the way we display this information to follow a consistent style. I suggest that the clinical trial phase should be in Roman numerals following this format: `Phase ` + `{phase} in roman numerals` as we do for the ChEMBL target/disease evidence widget:
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/bb181609-dae7-409b-85c3-58a5cc1a4033)

Do you think that including the keyword Phase in all the fields could be intrusive or confusing? Please share any comments.

**Comment by ktsirigos** [comment]
closing this as work is done
