### ISSUE TITLE
Disease Page content load very slow; sometimes taking upto minutes. 

### ISSUE THREAD

**Issue by bhandaris4** [opentargets/platform#1570]
Searching for any disease would take longer to load the page content to full. I have experienced for around 30 secs to couple of minutes as well. The longest it took is for my search for pneumonia on 5/24/2021 at around 3:34 pm EST, which did not load on its own for next 4 or 5 minutes (or until I manually interfered) 

https://platform.opentargets.org/disease/EFO_0003106/associations

**Comment by andrewhercules** [comment]
@bhandaris4 thank you for reporting this. We continue to monitor the performance of the associations pages, but note that in some cases the performance of the associations page could be slower due to ClickHouse calculating associations-on-the-fly scores.
