### ISSUE TITLE
Update EVA clinical significances

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1573]
Two more levels of clinical significance values have been added to the schema (PR [#123](https://github.com/opentargets/json_schema/pull/123)): `confers sensitivity` and `conflicting data from submitters`.

2 actions need to be taken:
- [x] Add them to the ETL reference [config file](https://github.com/opentargets/platform-etl-backend/blob/ca1835387cd683a65a21a8958e7513d1e3b1620b/src/main/resources/reference.conf#L310).
- [x] Update the documentation

**Comment by ireneisdoomed** [comment]
@DSuveges:

> There are 5 tiers in the score map: 0, 0.3, 0.5, 0.7, 0.9. I think confers sensitivity rather matches 0.5, while conflicting data from submitters matches 0.3.

**Comment by DSuveges** [comment]
Decision based on discussion at standup:

* `confers sensitivity`: 0.9
* `conflicting data from submitters`: 0.3

**Comment by DSuveges** [comment]
RP for the config file: https://github.com/opentargets/platform-etl-backend/pull/136
