### ISSUE TITLE
Update "Targets" column in ChEMBL evidence table

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1576]
As noted in #1575, there are instances where the target information for the drug is not available in the `mechanismsOfAction` array.  This causes the "Targets" column to be blank. For example, this can be seen on the [HAO1 and Primary hyperoxaluria type 1 evidence page](https://platform.opentargets.org/evidence/ENSG00000101323/Orphanet_93598).

<img width="1455" alt="119987285-c4b6c000-bfbc-11eb-8548-d8574d90e67b" src="https://user-images.githubusercontent.com/7490258/119992015-fe3dfa00-bfc1-11eb-9cd9-e4bb091bee30.png">

Can we please adjust the logic so that if  `mechanismsOfAction.rows.targets` is `[]` ([example](https://api.platform.opentargets.org/api/v4/graphql/browser?query=query%20drugEvidence{%20target(ensemblId:%22ENSG00000101323%22){%20id%20approvedSymbol%20evidences(efoIds:[%22Orphanet_93598%22],%20datasourceIds:[%22chembl%22]){%20count%20rows%20{%20disease%20{%20id%20name%20}%20drug%20{%20id%20name%20drugType%20mechanismsOfAction%20{%20rows%20{%20mechanismOfAction%20targets%20{%20id%20approvedSymbol%20}%20}%20}%20}%20clinicalPhase%20clinicalStatus%20studyStartDate%20studyStopReason%20urls%20{%20niceName%20url%20}%20}%20}%20}%20})), we display the `rows.target.approvedSymbol` and use the `rows.target.id` to link to the relevant target profile page ([example](https://api.platform.opentargets.org/api/v4/graphql/browser?query=query%20drugEvidence%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000101323%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20evidences%28efoIds%3A%20%5B%22Orphanet_93598%22%5D%2C%20datasourceIds%3A%20%5B%22chembl%22%5D%29%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20target%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20drugType%0A%20%20%20%20%20%20%20%20%20%20mechanismsOfAction%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20targets%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20clinicalPhase%0A%20%20%20%20%20%20%20%20clinicalStatus%0A%20%20%20%20%20%20%20%20studyStartDate%0A%20%20%20%20%20%20%20%20studyStopReason%0A%20%20%20%20%20%20%20%20urls%20%7B%0A%20%20%20%20%20%20%20%20%20%20niceName%0A%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A))?

**Comment by ktsirigos** [comment]
closing this as work is done
