### ISSUE TITLE
Duplicated result appear in both of web platform and download data when seaching disease=cancer, gens=7SK

### ISSUE THREAD

**Issue by rika-N** [opentargets/platform#1578]
Duplicated result appear in both of web platform and download data when seaching disease=cancer, gens=7SK.

recreation the issue: 

- web platform
       step1.  Access  cancer page (https://platform.opentargets.org/disease/EFO_0000311/associations)
       step2.  Then search -> 7SK

-  download data: 
       step1.  Call overallDatasourceHarmonicScore of cancer
       step2.  Search 7SK
       
  
 
![image](https://user-images.githubusercontent.com/65329214/120053610-0f404700-c066-11eb-91b4-1ec68d54d425.png)

**Comment by andrewhercules** [comment]
In reviewing this cancer associations page (filtered by 7SK), it appears that 7SK is RNA found on different chromosomes and has different Ensembl IDs. And so each Ensembl ID has its own evidence page.

- https://platform.opentargets.org/evidence/ENSG00000277313/EFO_0000311
- https://platform.opentargets.org/evidence/ENSG00000275933/EFO_0000311
- https://platform.opentargets.org/evidence/ENSG00000276626/EFO_0000311
- https://platform.opentargets.org/evidence/ENSG00000202198/EFO_0000311
- https://platform.opentargets.org/evidence/ENSG00000273591/EFO_0000311
- https://platform.opentargets.org/evidence/ENSG00000271394/EFO_0000311
- https://platform.opentargets.org/evidence/ENSG00000274303/EFO_0000311

All 7 evidence pages listed above have the same 3 rows in the Europe PMC section, referring to two PubMed IDs — 27752877 (2 x duplicated) and 22377309.

![Screenshot 2021-06-01 at 17 00 19](https://user-images.githubusercontent.com/7490258/120355230-05834180-c2fb-11eb-88ad-2cb4952129f2.png)

However, 2 of the evidence pages also have RNA expression evidence:

https://platform.opentargets.org/evidence/ENSG00000271394/EFO_0000311
https://platform.opentargets.org/evidence/ENSG00000274303/EFO_0000311

![Screenshot 2021-06-01 at 17 00 27](https://user-images.githubusercontent.com/7490258/120355301-16cc4e00-c2fb-11eb-9a1e-4493d860d64c.png)

Flagging this for our data team to review and comment if the "duplication" is valid.

@ireneisdoomed, @DSuveges, @tskir, @d0choa

**Comment by andrewhercules** [comment]
Ticket closed as 7SK has multiple Ensembl IDs (as noted above) and the text mining pipeline is unable to distinguish which Ensembl ID to use for the occurrence of 7SK in the literature.
