### ISSUE TITLE
Create spreadsheet to track datasource licences

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1582]
Using the datasources listed in the [evidence](https://platform-docs.opentargets.org/evidence), [target](https://platform-docs.opentargets.org/target), [disease/phenotype](https://platform-docs.opentargets.org/disease-or-phenotype), and [drug](https://platform-docs.opentargets.org/drug) documentation pages, can we please create a Google docs or spreadsheet with the following information?

- Name of data source
- Website 
- Licence
- Licence website
- URL where licence mentioned or inferred
- Does licence allow for commercial use?
- Any additional restrictions?
- Date licence checked

For example, for ChEMBL we would have:

- ChEMBL
- https://www.ebi.ac.uk/chembl/
- Creative Commons Attribution-Share Alike 3.0 Unported License
- https://creativecommons.org/licenses/by-sa/3.0/
- TRUE
- Attribution; share-alike
- 2 June 2021

Please note that some entity data sources have "hidden" dependencies on other data sources. For example, we enrich the adverse events data with MedDRA term codes which is allowed based on the [MedDRA non-commercial subscription](https://www.meddra.org/subscription/subscription-type).

**Comment by ktsirigos** [comment]
licenses summary can be found [here](https://docs.google.com/spreadsheets/d/1m3_eSPr2NatMVHulkbX8I8Hyt8fAu70zq416A9JgwQs/edit#gid=0).
