### ISSUE TITLE
Apply new licence to all active GitHub repos in the Open Targets organisation

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1584]
Once the new licence text is ready - see #1583 - can we please update the LICENCE files of all of our active repositories?

@cmalangone has recommended that we update the licence text and then open a pull request so that the technical team can merge the changes into the most appropriate branch. She also mentioned that GWAS Catalog has developed a process for updating their codebase licences yearly. Please speak with her before beginning this project and consider meeting with GWAS Catalog to learn more about their approach.

**Comment by andrewhercules** [comment]
All Open Targets GitHub repositories can be updated with the Apache 2.0 licence provided by GitHub.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by ktsirigos** [comment]
all repos have the Apache 2.0 license now.
