### ISSUE TITLE
Create new Orphanet evidence table

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1587]
As noted in #1577, there is new evidence data available from Orphanet. Can we please implement a data table and add to the evidence page? 

Example for testing: [KIF7 (ENSG00000166813) in Multiple epiphyseal dysplasia, Al-Gazali type (Orphanet_166024)](https://platform.opentargets.org/evidence/ENSG00000166813/Orphanet_166024)

As of 2 June 2021, the data is not yet available from the GraphQL API. However, as the fields are similar to other genetic association evidence data sources, we can implement a placeholder component.

Further details TBC

**Comment by andrewhercules** [comment]
Can we please generate a new evidence section called "Orphanet"?

For the section description, can we please use the following text?

> Expert-reviewed data supporting the relationship between `target.approvedSymbol` and `disesase.name`. Source: [Orphanet](https://www.orpha.net/consor/cgi-bin/Disease_Genes.php)

Within the evidence page section, can we please create a data table that displays the following columns?

| Disease/phenotype | Reported protein | Allele origin | Confidence | Literature
| --- | --- | --- | --- | --- |
| `data.rows[x].disease.name` | `data.rows[x].targetFromSource`| `data.rows[x].alleleOrigins` | `data.rows[x].confidence` | `data.rows[x].literature |
| | | | |

[Sample query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20orphanetEvidence%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000166813%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20evidences%28datasourceIds%3A%20%5B%22orphanet%22%5D%2C%20efoIds%3A%20%5B%22Orphanet_166024%22%5D%29%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20diseaseFromSourceId%0A%20%20%20%20%20%20%20%20diseaseFromSourceMappedId%0A%20%20%20%20%20%20%20%20targetFromSource%0A%20%20%20%20%20%20%20%20targetFromSourceId%0A%20%20%20%20%20%20%20%20alleleOrigins%0A%20%20%20%20%20%20%20%20confidence%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
 
Within the "Disease/phenotype" column, please display the `diseaseFromSource` using the tooltip approach used in in other evidence data tables (e.g. ClinVar).

Within the "Reported protein" column, please display the `data.rows[x].targetFromSource` and construct a link to the relevant target profile page using the `data.rows[x].targetFromSourceId`.

For the values in the "Allele origin" column, the `alleleOrigins` field is an array. Please display the entries in the array as a single string, separated with a semi-colon `;`.

Within the "Literature" column, please use the literature drawer component that utilises the EuropePMC API to display the citation, abstract, and full-text availability. Also, please note that the `literature` field may be `null` or an empty array as not all evidence strings have a publication — please account for this scenario.

**Comment by ktsirigos** [comment]
closing issue as work done.
