### ISSUE TITLE
Align parent-child molecule logic of MoAs and indications with ChEMBL

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1590]
After a focused conversation with ChEMBL (3/6/21), we received an explanation on the way mechanisms of action, drug warnings and indications are treated on their API. The logic for the 3 cases is to propagate information from the child molecule to the parent molecule. Discussions also covered different problems this implementation might cause, including lack of mechanisms of action in the child molecules. ChEMBL plans to fulfil the gaps by curation. We also explained the logic why we started to include child molecules in order to broaden our set of molecules/labels for literature, pharmacovigilance, etc.

 In order to maximise alignment with ChEMBL and minimise inconsistencies, we want to implement the same logic on our side: parent molecules will contain their own data and the distinct information from all their child molecules. Child molecules will instead only capture their own information not receiving information from any other molecule. Same logic will apply to indications, MoAs and drug warnings.

**Comment by mkarmona** [comment]
Still unclear whether this asynchronicity comes from an unfixed issue from Chembl or rather a legit chemical justification. @d0choa can you provide a real case that backs the least one, if such the case? Depends on where the problem origins we should adapt accordingly or we wait for them to fix it.

**Comment by d0choa** [comment]
There is no fix on their side. We did implement something that does not align with ChEMBL parent-child molecule definition and propagation of information, because we did not know what was the logic encoded in their API. We can now realign to avoid inconsistencies and prevent future problems.

**Comment by mkarmona** [comment]
Thanks, @d0choa. Given what you said, what is the purpose then of having a parent-child molecule relationship? If I understood correctly, you can't hypothetically use it to infer or to fill in inherited information.
