### ISSUE TITLE
Style the embedded Discourse comments on the blog

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/platform#1594]
We have now embedded Discourse with the blog, so that readers can comment on blog posts by responded to the corresponding topic created in the Open Targets Community. 

The option to comment is not very obvious at the moment, but there is a way to [add a stylesheet to the Community for embedded content](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963#styling-your-embedded-content) by adding custom CSS/HTML to the theme.

**Comment by ktsirigos** [comment]
@andrewhercules @helena updates on this?

**Comment by andrewhercules** [comment]
@HelenaCornu and I will work to re-implement comments on the blog and then this ticket can be closed

**Comment by HelenaCornu** [comment]
I have reuploaded the Liebling 1.06 theme to the blog, after adding the embed code from Discourse to post.hbs according to [the instructions from Ghost](https://ghost.org/integrations/discourse/).
