### ISSUE TITLE
Formulating d/t evidence based on OTAR CRISP/Cas9 project data

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1597]
For internally available OpenTargets Platform release, we are preparing some exclusive datasets based on OTAR experimental projects. 

- [x] CRISP/Cas9 screening results: MAGeCK output tables. - write parser
- [x] Formulate a study table that contains enough study level information to make the evidence useful.
- [x] Generalise implementation to enable the ingestion of other similar datasets

**Comment by andrewhercules** [comment]
@DSuveges, responses to our questions about scoring/threshold for two projects now available on the team Google Drive:

[OTAR033](https://docs.google.com/document/d/1IgrX0QKZ7lmHWSxtZr6oHvDe9og730XicY4jWjnNNkA/edit)
[OTAR036](https://docs.google.com/document/d/1DGezgGdI1q0yMs1-SpJe-sqTqX6u5-JJbTrEyiMoAkM/edit)

**Comment by DSuveges** [comment]
Thank @andrewhercules I'm adding these details into a "study" table that my script picks and incorporates into the evidence.

**Comment by DSuveges** [comment]
The first draft of the evidence is available here: [gs://ot-team/dsuveges/CRISPR_screens/otar_crispr.json.gz](gs://ot-team/dsuveges/CRISPR_screens/otar_crispr.json.gz)

**Example evidence**:

```json
{
  "targetFromSourceId": "AP2M1",
  "resourceScore": 0.00495,
  "effectDirection": "upper",
  "studyId": "OTAR036_TAU_uptake_1",
  "description": "Comparison of functional populations of iPSC neurons based on their ability to take up monomeric/aggregated tau protein",
  "cohortPhenotypes": [
    "Neurodegeneration",
    "Dementia",
    "Tauopathy(ies)",
    "Alzheimer’s Disease",
    "Frontotemporal dementia",
    "Pick’s Disease"
  ],
  "diseaseCellLines": [
    "iPSC derived neurons"
  ],
  "datasourceId": "ot_crispr",
  "datatypeId": "affected_pathway",
  "diseaseFromSource": "Neurodegeneration",
  "diseaseFromSourceMappedId": "HP_0002180"
}
```

**Based on discussion do these modifications:**

* No automatic disease mappings. All diseases are coming from manual curation.
* `dataTypeId`: `ot_crispr` -> this will allow a separate column in the association heatmap.
* Writing separate logic for ENCORE, as the data is provided in a different format.
* Threshold might be applied on different column - implement this flexibility.

**Comment by d0choa** [comment]
Some suggestions:

1. I would remove `cohortPhenotypes`. The purpose of this field is to encapsulate all the phenotypes that a given cohort of individuals have. It's implicit to the field that all or some individuals have all the phenotypes listed in `cohortPhenotypes`. In this case, you're listing all the diseases this model might explain. I would just explode them as `diseaseFromSource` / `diseaseFromSourceMappedId` and that's it.

2. `diseaseCellLines` did contain cell lines, whereas here we are talking about a cell types. We might need a new field which is likely to work for other things in the future. We should try to push and see if they are in some way reflected in the CL ontology.  We can ask the experimentalist back.
