### ISSUE TITLE
Create logic to hide OTAR project widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1599]
Currently, the `main` branch contains a placeholder for an [Open Targets Projects component](https://github.com/opentargets/platform-app/tree/main/src/sections/disease/OTProjects).

Can we please create configuration logic (e.g. `showOTARProjects`) that hides the summary widget and detail view by default? 

As a follow-up task when the data is ready, we can adjust the deployment process and create profiles that will be responsible for setting the correct configuration for the widget.

**Comment by ktsirigos** [comment]
closing this as work is done
