### ISSUE TITLE
New Target Enabling Packages (TEPs) for 18.10 OT Release

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#160]
The SGC is on a roll, there are three new [TEPs](https://www.thesgc.org/tep) available since our August release:

- PARP14: https://www.targetvalidation.org/target/ENSG00000173193
- NUDT7: https://www.targetvalidation.org/target/ENSG00000140876
- HCN4: https://www.targetvalidation.org/target/ENSG00000138622

These need to be added to: https://github.com/opentargets/webapp/blob/893fcb951caaf312d86447f952e66256fd9c537d/app/src/services/teps-service.js

**Comment by LucaFumis** [comment]
Fixed in commit https://github.com/opentargets/webapp/commit/c3db27f9bbab810165a8f1fe91a851be0a73d3c5
