### ISSUE TITLE
Multiple drug profile pages producing internal server errors in dev

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1602]
Multiple drug profile pages produce internal server errors in `development`:
https://main--platform-app.netlify.app/drug/CHEMBL468
https://main--platform-app.netlify.app/drug/CHEMBL2110732

**Comment by JarrodBaker** [comment]
This looks like a problem with `adverseEvents`: 
![image.png](https://images.zenhubusercontent.com/5ec7caaa0e8174edc9bdf7a6/2bbb3d2d-a46b-4d7d-a9b2-b20c2b6cf87e)

```
[debug] models.Helpers - {
  "chembl_id" : "CHEMBL468",
  "reaction_reactionmeddrapt" : "plasma cell myeloma",
  "uniq_report_ids_by_reaction" : 9911,
  "uniq_report_ids_by_drug" : 13835,
  "A" : 625,
  "C" : 13210,
  "B" : 9286,
  "D" : 4613472,
  "aterm" : -1727.280550418942,
  "cterm" : -77392.38527226652,
  "acterm" : -80444.07090379274,
  "llr" : 1324.4050811072811,
  "meddraCode" : "10035226"
}
play.api.libs.json.JsResultException: JsResultException(errors:List((/event,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/count,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/critval,List(JsonValidationError(List(error.path.missing),WrappedArray())))))
```

**Comment by JarrodBaker** [comment]
It's a problem with how the ElasticSearch instance was created. The index has the wrong data. The FAERS pipeline outputs two datasets, one raw and one grouped by ChEMBL ID. The raw data is as appears in the comment above, we need to use the data grouped by ChEMBL ID. 

As a temporary fix I'll recreate the ES index with the correct data, and then work with Cinzia to update POS to make sure we load the correct data in future.

**Comment by d0choa** [comment]
Thanks @JarrodBaker. Feel free to create tickets for any follow up action. Closing this as resolved.
