### ISSUE TITLE
Add projectId to Open Targets Genetics evidence data table

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1608]
Details TBC - pending work in #1606 and #1607 and the final pipeline run

**Comment by andrewhercules** [comment]
@carcruz, can we please adjust the Open Targets Genetics evidence data table and add a column "Study source" after the "Publication" column.

Within the "Study source" column, can we please display the mapped term depending on the `projectId` value returned by the GraphQL API?

| API value | Mapped value to be displayed in UI |
| --- | --- |
| FINNGEN | FinnGen |
| GCST | GWAS Catalog |
| SAIGE | UK Biobank |
| NEALE | UK Biobank |
| any other value | N/A |

For an example association with all 4 sources, see [the TPO (ENSG00000115705) in hypothyroidism (EFO_0004705) evidence page](https://main--platform-app.netlify.app/evidence/ENSG00000115705/EFO_0004705) and [GraphQL API query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20%7B%0A%20%20disease%28efoId%3A%22EFO_0004705%22%29%7B%0A%20%20%20%20evidences%28ensemblIds%3A%5B%22ENSG00000115705%22%5D%2C%20datasourceIds%3A%5B%22ot_genetics_portal%22%5D%29%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20studySampleSize%0A%20%20%20%20%20%20%20%20variantId%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20publicationYear%0A%20%20%20%20%20%20%20%20publicationFirstAuthor%0A%20%20%20%20%20%20%20%20pValueExponent%0A%20%20%20%20%20%20%20%20pValueMantissa%0A%20%20%20%20%20%20%20%20oddsRatio%0A%20%20%20%20%20%20%20%20oddsRatioConfidenceIntervalLower%0A%20%20%20%20%20%20%20%20oddsRatioConfidenceIntervalUpper%0A%20%20%20%20%20%20%20%20beta%0A%20%20%20%20%20%20%20%20betaConfidenceIntervalLower%0A%20%20%20%20%20%20%20%20betaConfidenceIntervalUpper%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20projectId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D).

**Comment by ktsirigos** [comment]
closing this as work is done
