### ISSUE TITLE
Add data release version to homepage search box

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1609]
To ensure that users know which version of the data they will see in the Platform, can we please add a section to the homepage search box that lists the data version, which links to `https://platform-docs.opentargets.org/release-notes`?

![Screenshot 2021-06-17 at 20 47 05](https://user-images.githubusercontent.com/7490258/122463190-34610f00-cfad-11eb-98ae-2bded35bfe19.png)

There are two ways we can access the data version.

1. Use the API `meta` endpoint ([sample query](https://api.platform.opentargets.org/api/v4/graphql/browser?query=query%20{%20meta{%20dataVersion{%20year%20month%20iteration%20}%20}%20})). This would be similar to what we do for the data downloads page — see [lines 75-90](https://github.com/opentargets/platform-app/blob/5e56234d4ada0169d181bba99f543080841aef2d/src/pages/DownloadsPage/DownloadsPage.js#L75) of the DownloadsPage.js file.
2. On [line 45](https://github.com/opentargets/terraform-google-opentargets-platform/blob/409144c13b1d590319fe87ea2e17f5e79926ed13/profiles/deployment_context.2104_3#L45) of the Terraform deployment profile, there is a value `config_webapp_data_context_release` that lists the data version.

**Comment by andrewhercules** [comment]
Based on a suggestion from @d0choa about users that may not be familiar with our release versioning, I have adjusted the design spec to the following:

![Screenshot 2021-06-17 at 20 47 05](https://user-images.githubusercontent.com/7490258/122463229-42169480-cfad-11eb-8802-287c67dcfc8b.png)

Can we please build a function that maps the `meta` response to the month label (e.g. `6` maps to `June`) and combines the `year` response value with `20` to make the full year (e.g. `2021`)?

**Comment by ktsirigos** [comment]
work is done.
