### ISSUE TITLE
Genetics portal evidence fail validation

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1617]
A series of evidence fail validation against the most recent schema due to a imperfect pattern match against the `diseaseFromSourceMappedId` eg.

```json
{
  "datasourceId": "ot_genetics_portal",
  "datatypeId": "genetic_association",
  "targetFromSourceId": "ENSG00000105705",
  "diseaseFromSourceMappedId": "CHEBI_5931",
  "publicationFirstAuthor": "FINNGEN_R5",
  "publicationYear": 2021,
  "diseaseFromSource": "Diabetes, insuline treatment (Kela reimbursement)",
  "studyId": "FINNGEN_R5_KELA_DIAB_INSUL",
  "studySampleSize": 218792,
  "pValueMantissa": 8.4,
  "pValueExponent": -14,
  "projectId": "FINNGEN",
  "oddsRatio": 1.114493453620326,
  "oddsRatioConfidenceIntervalLower": 1.0832138096143218,
  "oddsRatioConfidenceIntervalUpper": 1.146676350631839,
  "resourceScore": 0.3674289882183075,
  "variantRsId": "rs8100204",
  "variantId": "19_19282905_G_A",
  "variantFunctionalConsequenceId": "SO_0001627"
}
```

The enforced pattern says: 
`"pattern": "(^NCIT_C\\d+$|^Orphanet_\\d+$|^GO_\\d+$|^HP_\\d+$|^EFO_\\d+$|^MONDO_\\d+$|^DOID_\\d+$|^MP_\\d+$|^OTAR_\\d+$)",
`
So only a handful of EFO prefixes are supported and there always be some exception. Currently needed but not supported prefixes: `CHEBI` and `PATO`.

**Decision to make:**
1) Check the failing evidence strings and update pattern 
2) Remove pattern altogether and apply a less stringent check.

**Comment by DSuveges** [comment]
(Other than this issue, all evidence passed validation.)

**Comment by d0choa** [comment]
#2 with something like `(\w+)_(\w+)` ? Your call

**Comment by DSuveges** [comment]
Ensure the precision of elastic matches the validation rules.

**Comment by DSuveges** [comment]
**Action:** 
* OR values not be able to represent with single precision float will be removed.

**Comment by d0choa** [comment]
@ireneisdoomed and @DSuveges, is the merged PR closing this issue?

**Comment by ireneisdoomed** [comment]
@d0choa Yes - everything validates and no casting is happening.
