### ISSUE TITLE
OnToma: Further improvements

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1619]
This is a catch-all follow-up ticket for https://github.com/opentargets/platform/issues/1534 (OnToma v1.0.0 rewrite), to make the scope of the latter reasonable. It aggregates all improvements which might be benefitial to implement for the future releases.

* **Algorithm**
  - [ ] If the input is a ontology identifier and steps 1–4 were not successful, we can attempt to resolve the name using OLS/other sources and then try steps 5–8
  - [ ] Implement step 9, inexact synonyms from OWL
  - [ ] Implement step 10, all quality suggestions from ZOOMA
  - [ ] Automatically resolve obsolete terms to their current versions
  - [ ] Detect when new EFO version comes out to update the cache
  - [ ] Automatically detect whether the input is an ontology identifier instead of relying on a flag from a user
* **Performance and operation**
  - [ ] Make manual xref and string mapping tables part of the cache
  - [ ] Implement parallel execution
  - [ ] Look into why OnToma objects aren't broadcastable in Spark (if this is still the case)
  - [ ] Query ZOOMA, OxO, OLS in batch
  - [ ] HTTP error handling and retry for ZOOMA, OxO, OLS
  - [ ] Properly set up logging; see https://github.com/opentargets/OnToma/pull/18#discussion_r666272530
* **Customisation**
  - [ ] Allow to specify the list and priority of lookup steps
  - [ ] Calculate the number of results provided by each step
  - [ ] Allow to use either OT slim, or the full EFO
  - [ ] Implement verbose output mode with additional information
  - [ ] Allow the user to choose output representation of the mapped ontology terms (internal normalised/Open Targets schema/full URI)
  - [ ] Output unmapped queries to a separate file and set up the curation approach similarly to how this is done in EVA/ClinVar
  - [ ] Allow configuration of OxO and ZOOMA query parameters
  - [ ] More fine-grained specification of which synonym scopes to use (broad/narrow/related/...)
* **Discussions**
  - [ ] Do we want any of the other modes, like other ontology lookup (HP/ORDO/MONDO) or direct OLS lookup?
  - [ ] Discuss which package management system to use (setup/requirements/pipenv)
  - [ ] Discuss which CI system to use (GitHub Actions/CircleCI/Travis)
  - [ ] Discuss if we want automatic PIP deployment by the CI
  - [ ] Discuss how to handle documentation (if ReadTheDocs: access issues)
  - [ ] Argparse vs. click; see also comments: https://github.com/opentargets/OnToma/pull/18#discussion_r666276608
* **Documentation**
  - [ ] How to release a new version
  - [ ] Local installation and testing
  - [ ] More details about the underlying operation of OnToma
  - [ ] More details on input and output formats
  - [ ] Add some information from v1.0.0 release to the documentation
* **Integration with additional resources**
  - [ ] The EVA pipeline (needs to be eventually replaced by OnToma)
  - [ ] The new grounding pipeline
  - [ ] https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md
  - [ ] Look more carefully into the OWL file to see the various ways of how cross-refs etc. could be represented
* **Benchmark for ontology-to-ontology mapping**
  - [ ] Implement the same benchmark for OMIM codes
  - [ ] Commit test traits and validation set to repository
  - [ ] Automatically calculate sensitivity and precision metrics
  - [ ] Amend benchmark documentation
  - [ ] Re-run the updated benchmark
* [ ] **Revisit discussions from https://github.com/opentargets/OnToma/pull/18**
* [ ] Further work on improving sensitivity
* [ ] Check whether OTAR slim file contains any extraneous records such as tissue types

**Comment by d0choa** [comment]
Closing as we are not expecting to do any work soon. Ticket will be very useful for future reference
