### ISSUE TITLE
Hide "N/A" if `variantRsid` is `null`

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1621]
Currently, the Open Targets Genetics Portal evidence table shows "N/A" if the `variantRsid` value from the API is `null`.

![Screenshot 2021-06-24 at 14 57 45](https://user-images.githubusercontent.com/7490258/123276127-ccef1600-d4fc-11eb-835e-5924fc8511ff.png)

Can we please remove the "N/A" if `variantRsid` is `null`?

![Screenshot 2021-06-24 at 14 58 49](https://user-images.githubusercontent.com/7490258/123276117-cb255280-d4fc-11eb-9e8e-3cba2d07c390.png)

Example: [TG (ENSG00000042832) in Hashimoto's thyroiditis (EFO_0003779) evidence page](https://main--platform-app.netlify.app/evidence/ENSG00000042832/EFO_0003779) and [GraphQL API query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20%7B%0A%20%20disease%28efoId%3A%22EFO_0003779%22%29%7B%0A%20%20%20%20evidences%28ensemblIds%3A%5B%22ENSG00000042832%22%5D%2C%20datasourceIds%3A%5B%22ot_genetics_portal%22%5D%29%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20target%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20studySampleSize%0A%20%20%20%20%20%20%20%20variantId%0A%20%20%20%20%20%20%20%20variantRsId%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%20%20publicationYear%0A%20%20%20%20%20%20%20%20publicationFirstAuthor%0A%20%20%20%20%20%20%20%20pValueExponent%0A%20%20%20%20%20%20%20%20pValueMantissa%0A%20%20%20%20%20%20%20%20oddsRatio%0A%20%20%20%20%20%20%20%20oddsRatioConfidenceIntervalLower%0A%20%20%20%20%20%20%20%20oddsRatioConfidenceIntervalUpper%0A%20%20%20%20%20%20%20%20beta%0A%20%20%20%20%20%20%20%20betaConfidenceIntervalLower%0A%20%20%20%20%20%20%20%20betaConfidenceIntervalUpper%0A%20%20%20%20%20%20%20%20variantFunctionalConsequence%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20projectId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by ktsirigos** [comment]
closing this as work is done
