### ISSUE TITLE
Extend publication drawer component to handle EPMC IDs

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1622]
Details TBC

**Comment by ktsirigos** [comment]
@andrewhercules, do you want to comment here?

**Comment by andrewhercules** [comment]
Ticket closed as no further work planned on drawer component to expand to use Europe PMC IDs. The underlying target-disease evidence field only accepts PubMed IDs so we only need to use that Europe PMC API endpoint. At a later stage, we may decide to include other types of publications (e.g. preprints) in which case the drawer component will need to be expanded to use those IDs.
