### ISSUE TITLE
Update `ot-sitemap-cli` to adjust date in `<lastmod>` tag

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1624]
After submitting sitemaps for our 21.06, Google notified me that the sitemaps have a date formatting error in the `<lastmod>` tag. This error does not prevent Google from indexing the site as it doesn't really consider the `<lastmod>` tag in its indexing algorithms. 

![Screenshot 2021-06-30 at 12 25 51](https://user-images.githubusercontent.com/7490258/123952979-a0c11280-d99e-11eb-8e73-dd6385f3f134.png)

According to the Google Search documentation, if a sitemap specifies a time in the `<lastmod>` tag, it must also specify a timezone. This appears to only be a requirement for Google as Bing does not require explicit mention of the time zone. 

In the `ot-sitemap-cli` can we please adjust the code so that the `<lastmod>` tag does not include the time but only displays the [W3C Datetime-compliant](https://www.w3.org/TR/NOTE-datetime) date? (e.g. 2005-02-21)

**Comment by JarrodBaker** [comment]
I'll take this @mbdebian: it's my mistake.

**Comment by andrewhercules** [comment]
Perfect - thank you @JarrodBaker! 

And no worries - it's just Google being very picky as other search engines accept the date as originally formatted 😂
