### ISSUE TITLE
Issue with scores discrepancy

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1627]
The user reports the following problem:

I have now downloaded the new data, but I am a bit puzzling with the scores. Unfortunately I am not able to reproduce the score mentioned in the website. For example, in the website the top hit for PCSK9 is with familial hypercholesterolemia with an overall association score of 0.86. However, when I look at the downloaded data I get 0.826922 for the same association. I used "associationByOverallDirect" to get the overall score. 

Additionally, when I look for only the Genetic association from "associationByDatatypeDirect" the top hit for PCSK9 is Coronary artery disease with a score of 0.936360, where in the website, the top hit is familial hypercholesterolemia with score of 0.91. But the CAD is at the 8th position with the score of 0.75.

I was wondering whether I am looking at the wrong place! Could you please help me to reproduce the score as it's mentioned on the website.

**Comment by mkarmona** [comment]
There were two separate issues with this

1. duplicated data during the ingestion process
2. issue introduced in the precomputed associations which has been fixed in [PR 158](https://github.com/opentargets/platform-etl-backend/pull/158)

**Comment by mkarmona** [comment]
@cmalangone please close this issue when you have done the redeploy and the offline associations
