### ISSUE TITLE
Expand summary widget and detail view to show data provenance logo or icon

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1629]
In the classic version of the Platform, private instances were able to display a logo or icon beside custom data.

To coincide with ongoing work to support partner instances of the Platform, can we please expand the summary widget and detail view component to show a data provenance icon (e.g. corporate logo, Font Awesome icon)?

Further details and design specification TBC for the 21.09 (September 2021) release.

**Comment by ktsirigos** [comment]
@andrewhercules is this relevant to do?

**Comment by andrewhercules** [comment]
Ticket closed as Partner Preview Platform contains lock icon and this can be used by other Platform instances to highlight custom internal data
