### ISSUE TITLE
Drugs with a blackbox warning flag and no additional information about the warning

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1637]
The profile page for [ABARELIX - CHEMBL1252](https://platform.opentargets.org/drug/CHEMBL1252) displays the black box warning flag for the drug, but there is no corresponding information in the data table.

![Screenshot 2021-07-13 at 12 46 04](https://user-images.githubusercontent.com/7490258/125446349-538c7415-5767-4d0c-8a47-0d1205a903dd.png)

The same view is also seen on the [CHEMBL profile page for ABARAELIX](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1252/).

The [original package insert](https://www.accessdata.fda.gov/drugsatfda_docs/nda/2003/21-320_Plenaxis_Prntlbl.pdf) for the drug notes "immediate-onset systemic allergic reactions, some resulting in hypotension and syncope". 

Should this drug have a black box warning for vascular toxicity (MedDRA 10027433), similar to [METFORMIN - CHEMBL1431](https://platform.opentargets.org/drug/CHEMBL1431)?

And as a related question, are there other examples of drugs found in the Platform drug index where there is no information about the warning, other than the flag?

**Comment by d0choa** [comment]
@ireneisdoomed has some background on this I believe

**Comment by JarrodBaker** [comment]
Looking at CHEMBL1252 what is displayed on the Platform is all that we're getting from ChEMBL:
```
+--------------+------------------+-------------------------+-------------+---------------+-------------------+----------+------------+-----------------+------------+
|_metadata     |molecule_chembl_id|parent_molecule_chembl_id|warning_class|warning_country|warning_description|warning_id|warning_refs|warning_type     |warning_year|
+--------------+------------------+-------------------------+-------------+---------------+-------------------+----------+------------+-----------------+------------+
|[[CHEMBL1252]]|CHEMBL1252        |CHEMBL1252               |null         |null           |null               |5         |[]          |Black Box Warning|null        |
+--------------+------------------+-------------------------+-------------+---------------+-------------------+----------+------------+-----------------+------------+
```

**Comment by andrewhercules** [comment]
Ticket closed as ChEMBL have been notified of the issue and we expect it to be resolved with the release of CHEMBL29. For more information, see https://github.com/opentargets/platform/issues/1616#issuecomment-869625869
