### ISSUE TITLE
Add transgene insertion mouse lines from JAX for phenotypes

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#164]
@gkos-bio commented on [Tue Feb 14 2017](https://github.com/opentargets/data_pipeline/issues/79)

e.g. : Tg(SOD1*G93A)1Gur
http://www.informatics.jax.org/allele/key/7775

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_pipeline/issues/79#issuecomment-403784983)

@gkos-bio do you know if this has been done?

---

@gkos-bio commented on [Wed Aug 15 2018](https://github.com/opentargets/data_pipeline/issues/79#issuecomment-413217290)

No. Should look at it for release 18.10. Priority is low.

**Comment by andrewhercules** [comment]
This issue has been closed as it has been captured on [the Master Feature Prioritisation worksheet](https://docs.google.com/spreadsheets/d/1jZMKv6fDum6aEOqernfuwSv__f8CBFK6PZoRo9m0mWE/edit#gid=0) available on the team's Google Drive.

CC: @d0choa
