### ISSUE TITLE
Update Tractability summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1644]
With the new `target` ETL and API data format — along with the inclusion of the PROTAC data workflow — we need to update the Tractability summary widget and detail view.

The query string has significantly changed and is now:

```
query targetInfo {
  target(ensemblId: "ENSG00000091831") {
    approvedSymbol
    id
    tractability {
      id
      modality
    }
  }
}
```
Example queries: [AR](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000169083%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%09%09tractability%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20modality%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), [TNF](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000232810%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20tractability%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20modality%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), [CDK20](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000156345%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20tractability%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20modality%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

The response has also changed as the API returns the full label of the assessment as `id` along with the `modality` value:

Small molecule - `"modality": "SM"`
Antibody - `"modality": "AB"`
Other clinical modalities - `"modality": "OC"`
PROTAC - `"modality": "PR"`

### Summary widget

For the summary widget, please adjust the query and continue to show the full modality labels of the modalities that have an entry in the `tractability` array (e.g for AR, it would be Small molecule, PROTAC, Antibody).

### Detail view

Instead of displaying the heatmap-style overview — which some users mistake for clickable elements — we will display separate unordered lists for each of the four modalities.

Within each list, please display each of the `id` values in an unordered list. 

If the `value` for a given `id` is `true`, please display the [FontAwesome check-circle icon](https://fontawesome.com/v5.15/icons/check-circle?style=solid) in Open Targets blue `#3489ca` and please bold the `id` text.

Conversely, if `value` for a given `id` is `false`, please display the [FontAwesome times-circle icon](https://fontawesome.com/v5.15/icons/times-circle?style=regular) and the `id` text in Open Targets light grey `#e0e0e0`.

![Tractability (with PROTAC workflow)](https://user-images.githubusercontent.com/7490258/128865883-1e358fb9-4ff6-4934-90a6-df512705a034.png)

Please note that for some targets - e.g. [PAGE4 (ENSG00000101951)](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000101951%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20tractability%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20modality%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), [HEY2 (ENSG00000135547)](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000135547%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20tractability%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20modality%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) or [KLLN (ENSG00000227268)](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000227268%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20tractability%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20modality%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) - it is expected that all of the labels will be light grey as a tractability assessment was completed but the target did not get a positive hit in any bucket.

![Tractability (with PROTAC workflow) (1)](https://user-images.githubusercontent.com/7490258/128920853-293f3b49-fa9e-45f2-bd12-b4b4622b7a5a.png)

Additionally, other targets like LINC02694 (ENSG00000175779) will have no tractability data as they were not included in the pipeline assessment. Note that the GraphQL API returns an empty array, rather than `null` — please update the summary widget logic to handle this scenario.

**Comment by ktsirigos** [comment]
work done and merged
