### ISSUE TITLE
Remove Cancer Biomarkers summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1645]
As noted in https://github.com/opentargets/platform/issues/1641#issuecomment-895041911, the Cancer Biomarkers summary widget and detail view are to be removed from the target profile page. Instead, the data will be processed by the ETL pipeline and made available as evidence. 

Can we please remove the Cancer Biomarkers summary widget and detail view?

**Comment by ktsirigos** [comment]
work done and merged
