### ISSUE TITLE
Make contact email address a configuration variable

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1646]
Currently, the contact email address — `helpdesk@opentargets.org` — is hard-coded in the [footer and navigation bar components](https://github.com/opentargets/platform-app/blob/main/src/constants.js) and the [404 not found page](https://github.com/opentargets/platform-app/blob/main/src/pages/EmptyPage/EmptyPage.js).

Can we please extract this as a configuration variable that private instances can set during their deployment process, with `helpdesk@opentargets.org` as the default address and the address used for the public version of the Platform?

**Comment by ktsirigos** [comment]
work completed, merged into main.
