### ISSUE TITLE
Update email address shown in front-end error message

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1649]
When there is an error with the front-end web application, we display the following error message:

> Something went wrong. Please contact Open Targets at support@targetvalidation.org

Can we please update the email address to `helpdesk@opentargets.org`? 

Please do not hard-code in the email address but instead use the help desk email configuration variable that will be set in ticket #1646.

**Comment by d0choa** [comment]
Occasionally, the error contains more information when captured at the API level: internal server error, field not available, etc.

@andrewhercules I have mixed feelings about showing this message, but feel free to scope it or discard it with this work.

**Comment by ktsirigos** [comment]
work completed, merged into main.
