### ISSUE TITLE
Update Netlify build images

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1650]
Netlify has informed us that builds for the following sites will fail after 19th September 2021 due to the deprecation of the "Trusty" image that is built on Ubuntu 14.04:

    jolly-fermi-eb9986 (Genetics Portal pre-launch web page)
    general-manager-mabel-68027 (DoRothEA)
    genetics-app (Genetics Portal)
    paratrooper-antelope-70721 (classic Platform)
    platform-app (next-gen Platform)

Netlify recommends that we select the `Ubuntu Focal 20.04 (beta)` build image based on the [Netlify build image migration documentation](https://answers.netlify.com/t/please-read-end-of-support-for-trusty-build-image-everything-you-need-to-know/39004).

**Comment by ktsirigos** [comment]
work completed.
