### ISSUE TITLE
the bibliography component keeps the folded/unfolded status of the abstracts whether you change to a new page

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1655]
The correct behaviour should be keeping the status per publication so when the page change it needs to set the folding to the current new publications.
![image](https://user-images.githubusercontent.com/5394232/126975409-aa969802-702f-4332-b18c-3157e12ec4b7.png)
![image](https://user-images.githubusercontent.com/5394232/126975453-524440f4-71d8-42e6-b651-311154e452fb.png)

**Comment by d0choa** [comment]
+1

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main`
