### ISSUE TITLE
Enable text-file compression in production version of platform-app

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1660]
A benchmark of platform.opentargets.org home page using [Google PageSpeed](https://developers.google.com/speed/pagespeed/insights/) reports that the site does not pass the [Core Web Vitals assessment](https://web.dev/vitals/).

Among the several suggested improvements, it's suggesting a 2.2 seconds improvement just by enabling text compression in text files (more dramatically in the javascript bundle).

Instead of generating plain text files (e.g. bundle.js), can we explore the possibility of producing a gzipped files (e.g. bundle.js.gz) in the production bundle? Possibly at build time.

**Comment by d0choa** [comment]
Reassigning, but still not done

**Comment by d0choa** [comment]
@mirandaio has made the compressed files available through the bundle. Now it's up-to @mbdebian to decide whether that's the best approach or relying on nginx for the compression.

**Comment by mbdebian** [comment]
I have patched our production web servers to increase efficiency when serving the web application content.
