### ISSUE TITLE
Update target profile page cross-references

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1662]
In the new target ETL and API schema, the cross-references displayed at the top of the target profile page will need to be updated as the query string and data format has changed.

![Screenshot 2021-07-29 at 16 18 57](https://user-images.githubusercontent.com/7490258/127519556-a90d2108-563b-441c-b99f-4609146cb56e.png)

```
query targetInfo {
  target(ensemblId: "ENSG00000091831") {
    approvedSymbol
    id
    proteinIds{
      id
      source
    }
    dbXrefs{
      id
      source
    }
  }
}
```
Example query: [ESR1](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000091831%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20proteinIds%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%20%20dbXrefs%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**For all cross-references listed below, please note that genes may not have the relevant data to generate the cross-reference or the API may not return data (e.g. there is no Project Score entry for [TNF](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000232810%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20proteinIds%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%20%20dbXrefs%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)). Please ensure that the component can handle this and does not crash.**

### Ensembl

Please update the link construction and use the `target.id` value and the identifers.org resolver:

`https://identifiers.org/ensembl:` + `target.id` (e.g. [ENSG00000139618](https://identifiers.org/ensembl:ENSG00000139618))

### UniProt

The UniProt ID is now available in `target. proteinIds.id` where `target.proteinIds.source == "uniprot_swissprot"`.

Please update the link construction and use the correct UniProt ID (noted above) and the identifers.org resolver:

`https://identifiers.org/uniprot:` + UniProt ID (e.g. [P0DP23](https://identifiers.org/uniprot:P0DP23))

### GeneCards

Please update the link construction and use the `target.approvedSymbol` value and the identifiers.org resolver:

`https://identifiers.org/genecards:` + `target.approvedSymbol` (e.g. [ABL1](https://identifiers.org/genecards:ABL1))

### HGNC

Please update the link construction and use the `target.approvedSymbol` value and the identifiers.org resolver:

`https://identifiers.org/hgnc.symbol:` + `target.approvedSymbol` (e.g. [DAPK1](https://identifiers.org/hgnc.symbol:DAPK1))

### Project Score

The Project Score ID is now available from our `target` API endpoint in `target.dbXrefs.id` where `target.dbXrefs.source == ProjectScore`. Please remove the dependency on querying the Project Score API to get the ID.

Please update the link construction and use the Project Score ID to link to the Project Score website using the following construct:

`https://score.depmap.sanger.ac.uk/gene/` + Project Score ID (e.g. [SIDG08129](https://score.depmap.sanger.ac.uk/gene/SIDG08129)

**Comment by andrewhercules** [comment]
@LucaFumis can you please make an adjustment to the cross-references section and list all UniProt accessions (with links) where `"source": "uniprot_swissprot"`?

There are 48 targets where the `proteinIds` array has more than 1 entry where `"source": "uniprot_swissprot"`. [GNAS (ENSG00000087460)](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetMultipleUniProtAccessions%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000087460%22%29%20%7B%0A%20%20%20%20approvedSymbol%0A%20%20%20%20id%0A%20%20%20%20proteinIds%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) is the target that has the most with 4: 
```
"proteinIds": [
        {
          "id": "O95467",
          "source": "uniprot_swissprot"
        },
        {
          "id": "P63092",
          "source": "uniprot_swissprot"
        },
        {
          "id": "P84996",
          "source": "uniprot_swissprot"
        },
        {
          "id": "Q5JWF2",
          "source": "uniprot_swissprot"
        },
]
```

Can we please update the cross-references section and include all UniProt accessions where `"source": "uniprot_swissprot"`?

![Screenshot 2021-08-11 at 16 13 00](https://user-images.githubusercontent.com/7490258/129056711-79bc1df7-3cf3-4a51-8ff5-58c4da1f5c8c.png)

**Comment by ktsirigos** [comment]
@carcruz can you please make the change noted by @andrewhercules for showing multiple UniProt ids?
