### ISSUE TITLE
Include alphaFold homology models through ProtVista viewer

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1664]
The Protvista viewer in the Uniprot site shows the structures of the AlphaFold structural models.

<img width="1347" alt="Screenshot 2021-07-30 at 18 30 46" src="https://user-images.githubusercontent.com/5097586/127690298-e0450292-2397-49d6-96b2-723c7cd2a7da.png">

Can we please...

- [ ] Check with @xwatkins if it's as trivial as updating to the [version 3.3.0 of Protista](https://github.com/ebi-webcomponents/nightingale/commits?author=xwatkins) and whether is safe to do it as it's not tagged as a release. The [relevant changes](https://github.com/ebi-webcomponents/nightingale/commit/c231347594b47a1561194ee09da9ea7bac7bcfcc) look associated with 3.3.0.

- [ ] If confirmed, update to Protvista 3.3.0

@HelenaCornu keep an eye on this feature

**Comment by andrewhercules** [comment]
Tagged this issue with `21.09` to remind the team to update the ProtVista viewer before the bundle is generated for the 21.09 release

**Comment by d0choa** [comment]
Following up on @andrewhercules comment, we need to check the console for errors before accepting a final release. The current version throws some errors on trying to access various resources. I suspect the consequence is missing data on some of the protvista tracks.

**Comment by xwatkins** [comment]
If the errors are `404` errors to the proteins API you can safely ignore them. We do not know ahead of the call whether there are features of a specific type for an entry, and the API returns a `404 not found` if there are none. We are working towards a better encapsulation of these errors.

**Comment by andrewhercules** [comment]
@carcruz can you please update the [protvista-uniprot NPM package](https://www.npmjs.com/package/protvista-uniprot) package to version `2.7.5` and test to ensure that it works?

Targets to test:
- NOD2 - ENSG00000167207
- IL4 - ENSG00000113520
- TSLP - ENSG00000145777

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main`
