### ISSUE TITLE
Hide all target profile page sections in `main`

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1666]
With the new `target` ETL and API data format, the target profile page crashes. 

Can we please temporarily hide all sections on the target profile page? As we work through the issues attached to epic #1641 and #1638, we will rescue and reimplement each section's summary widget and detail view components to support the 21.09 release.

![Screenshot 2021-08-02 at 13 10 34](https://user-images.githubusercontent.com/7490258/127860053-2e32244b-f37f-4fc2-bf25-641a82e411a0.png)

**Comment by ktsirigos** [comment]
work completed, merged into main.
