### ISSUE TITLE
Fix queries causing evidence page to crash

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1668]
With the new `target` ETL and API data format, the evidence page query is crashing.

My initial hypothesis is that the error is due to changes in how we access the target synonyms and descriptions as noted in #1661 and #1663.

The target description is available from a new field — `functionDescriptions`:

```
query targetInfo {
  target(ensemblId: "ENSG00000232810") {
    approvedSymbol
    approvedName
    functionDescriptions
  }
}
```

The target synonyms are also available in a new array — `synonyms`:

```
query targetInfo {
  target(ensemblId: "ENSG00000232810") {
    approvedSymbol
    id
    synonyms{
      label
      source
    }
  }
}
```

Can we please update the [query file](https://github.com/opentargets/platform-app/blob/main/src/pages/EvidencePage/Profile.js) and how the data is used in the [evidence page profile header component](https://github.com/opentargets/platform-app/blob/main/src/pages/EvidencePage/ProfileHeader.js)?

**Comment by ktsirigos** [comment]
work completed, merged into main.
