### ISSUE TITLE
Systems Biology Gene Sets (Evidence)

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#167]
@MichaelaEBI commented on [Tue May 15 2018](https://github.com/opentargets/data_pipeline/issues/277)

@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/73)

Include Systems Biology-derived gene sets in the Open Targets platform under "Pathways & Systems Biology"

- [x] Map out [process to include Systems Biology gene sets](https://docs.google.com/document/d/16YI0wy4mij3hMF_l-NKdCf-oedQFRgxbtlxF4xXFUPc/edit)
- [x] [Curate papers](https://docs.google.com/spreadsheets/d/1D1tJhvrOK2hamFtWp2mY_wRD_AVn9XRSstvMZV2u-K4/edit#gid=0)
- [x] Define JSON for SysBio evidence
- [x] Define scoring model for SysBio evidence (plan ahead for CRISPR & network module data)
- [x] Implement scoring model for SysBio evidence for 19.02 OT release
- [x] Generate sample data (JSON) from IBD Key Driver Gene Set paper
- [x] Identify and curate sample papers that identify key driver genes for various diseases
- [x] Validate and process sample JSON file using pipeline code
- [x] Define changes that need to be made throughout the platform

**Comment by MichaelaEBI** [comment]
Entry for the scoring table for the 19.02 release: "Systems Biology (p-values or rank-based scores are used for scoring if provided (scaled to [0.5,1], otherwise a score of 0.5 is assigned)."

**Comment by MichaelaEBI** [comment]
Has been implemented for 19.02.
