### ISSUE TITLE
Investigate why Expression Atlas heat map component not showing

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1671]
In production, if a user clicks on the "Experiments (Expression Atlas)" tab in the Baseline Expression section, they see an error message:

![Screenshot 2021-08-02 at 14 08 23](https://user-images.githubusercontent.com/7490258/127867072-d53afad3-f8a0-4a2f-8693-96dbdb7e4b3b.png)

This error is seen across multiple targets, including ESR1, TNF, IL13, and BRCA2.

Is this due to the bundling error that we previously reported to the team?

**Comment by d0choa** [comment]
ESR1 example:
https://platform.opentargets.org/target/ENSG00000091831

does work in expression atlas side:
https://www.ebi.ac.uk/gxa/search?geneQuery=%5B%7B%22value%22%3A%22ESR1%22%7D%5D&species=homo%20sapiens&conditionQuery=%5B%5D&bs=%7B%22homo%20sapiens%22%3A%5B%22ORGANISM_PART%22%5D%7D&ds=%7B%22kingdom%22%3A%5B%22animals%22%5D%7D#baseline

API response seems to be reaching platform.

**Comment by andrewhercules** [comment]
Just adding some of the discussion on Slack about the issue

![Screenshot 2021-09-20 at 13 00 03](https://user-images.githubusercontent.com/7490258/133998669-771ad0ae-c654-4371-8ca0-81d3105f7587.png)

As discussed in today's team lead meeting, the Expression Atlas team have been made aware of the issue. @mirandaio has created and deployed a simple React application with only the Expression Atlas widget and it does not show. 

Pending the outcome of conversations with the Expression Atlas team, we make temporarily hide the tab until the component is fixed. A final decision on this will be made by Friday 24th September.

**Comment by d0choa** [comment]
@mirandaio demo:
https://github.com/mirandaio/expression-atlas-demo

**Comment by andrewhercules** [comment]
Ticket reassigned to 21.11 release pending further updates from the Expression Atlas team

**Comment by mirandaio** [comment]
Expression atlas widget has been hidden temporarily until issues are fixed.

**Comment by andrewhercules** [comment]
For the `21.11` release, @mirandaio can you please rescue the heat map component?

**Comment by andrewhercules** [comment]
Ticket closed as Expression Atlas heatmap rescued, merged into `main`, and released in `21.11`
