### ISSUE TITLE
Change tractability response to include `false` entries and adjust order

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1672]
The new `target` ETL and API response only returns `true` tractability assessments.

So that we can differentiate between targets where an assessment has been run and all are `false` versus a target where no assessment has been run, can we please update the ELT and API to return `false values?

Also, can we please return the assessments in the same order as the columns in the input file?

**Comment by d0choa** [comment]
Sorry, because I was the one asking to remove the `false` entries. We have reassess and we think there is value on keeping them
