### ISSUE TITLE
Update Gene Ontology summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1675]
With the new `target` ETL pipeline and API response, we can expose more relevant GO annotation data, including the evidence code, evidence source, and gene product

```
query targetInfo {
  target(ensemblId: "ENSG00000146648") {
    id
    approvedSymbol
    geneOntology {
      term{
        id
        name
      }
      aspect
      evidence
      geneProduct
      source
    }
  }
}
```
Sample query: [EGFR](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000146648%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20geneOntology%20%7B%0A%20%20%20%20%20%20term%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20aspect%0A%20%20%20%20%20%20evidence%0A%20%20%20%20%20%20geneProduct%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

In the current production API, the GO term string is returned with the category label at the beginning following by a colon (e.g. "P:cellular response to cadmium ion"). However, the new `target` ETL and API endpoint returns a field called `aspect` that contains a capital letter that can be mapped to a specific category label:

`C` -> "Cellular Component"
`F` -> "Molecular Function"
`P` -> "Biological Process"

### Summary widget

- [ ] Please use the same widget, but note the differences in categorising the terms based on the `aspect` field noted above

### Detail view

- [ ] Please remove the old table component and update to the new table component

- [ ] Create a new data table:

| Category | GO term | Gene product | Evidence code | Source |
|---|---|---|---|---|     
| `geneOntology[x].aspect` <br /> *mapped to full label (see above) | `geneOntology[x].term.name` | `geneOntology[x].geneProduct` | `geneOntology[x].evidence` | `geneOntology[x].source` |

- [ ] In the "GO term" column, link the `geneOntology[x].term.name` to the EBI QiuckGo website using identifiers.org — `https://identifiers.org/` + `geneOntology[x].term.id`

- [ ] In the "Gene product" column, link to EBI QuickGo using the following construct — `https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=` + `geneOntology[x].geneProduct` + `&goId=` + `geneOntology[x].term.id`. (e.g. [Q8IZN7](https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q8IZN7&goId=GO:0005576))

- [ ] For the "Evidence code" column header, please display a tooltip with the following text:

> GO annotations include an evidence code that indicates how the annotation to a particular term is supported. Evidence codes fall into six general categories:
> 
> - Experimental evidence (EXP, IDA, IPI, IMP, IGI, IEP, HTP, HDA, HMP, HGI, HEP)
> - Phylogenetic evidence (IBA, IBD, IKR, IRD)
> - Computational evidence (ISS, ISO, ISA, ISM, IGC, RCA)
> - Author statements (TAS, NAS)
> - Curatorial statements (IC, ND)
> - Automatically generated annotations (IEA)
>  
> For more information, please visit http://geneontology.org/docs/guide-go-evidence-codes/

- [ ] For the "Source" column, there are a mix of sources available in the underlying data — PMID, DOI, Reactome, and GO_REF (e.g. [EGFR](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000146648%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20geneOntology%20%7B%0A%20%20%20%20%20%20term%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20aspect%0A%20%20%20%20%20%20evidence%0A%20%20%20%20%20%20geneProduct%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), [DEFB107B](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000198129%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20geneOntology%20%7B%0A%20%20%20%20%20%20term%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20aspect%0A%20%20%20%20%20%20evidence%0A%20%20%20%20%20%20geneProduct%0A%20%20%20%20%20%20source%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)). The `source` value follows the same construct, regardless of the source — `sourceName:sourceId` (e.g. "GO_REF:0000044" or "DOI:10.1016/j.ijms.2006.01.054"). Please parse the `source` string and extract both the source and ID values and construct links to the relevant website:

| `Source` | Interaction or external link |
| --- | --- |
| PMID | use the publications drawer to show the citation and abstract using the sourceId |
| Reactome | `https://identifiers.org/reactome:` + sourceId |
| DOI | `https://doi.org/` + sourceId |
| GO_REF | `https://identifiers.org/` + sourceId |

**Comment by JarrodBaker** [comment]
There is an endpoint on the API for querying GO terms created in response to opentargets/platform#1547 (spun out of opentargets/platform#1537), eg:

```
 geneOntologyTerms(goIds: ["GO:0000122"]){
    id
    name
  }
```
returns:
```
"geneOntologyTerms": [
      {
        "id": "GO:0000122",
        "name": "negative regulation of transcription by RNA polymerase II"
      }
    ]
```

Does this already meet the needs of the FE to unblock the ticket @andrewhercules ?

**Comment by andrewhercules** [comment]
Thank you @JarrodBaker! I will update the ticket to reflect the new endpoint

**Comment by d0choa** [comment]
@JarrodBaker can we implement it so that the GO terms are resolvable entities within the same query? This has been the most common approach across the API and it prevents FE having to query multiple endpoints.

An example of this behaviour is for example the resolution of the `variantFunctionalConsequenceId` field into sequence ontology terms within the evidence endpoints.

```
query otQuery{
  target(ensemblId: "ENSG00000167207") {
    approvedSymbol
    evidences(efoIds: "EFO_0000384", datasourceIds: "ot_genetics_portal"){
      rows{
        variantId
        variantFunctionalConsequence{
          id
          label
        }
      }
    }
  } 
}
```

**Comment by JarrodBaker** [comment]
@d0choa: that shouldn't be a problem. I think I might have misunderstood why we generated the index of ontology terms. 

Am I right in thinking that basically what we want is for the API to expose this interface on Target so that the geneOntology section contains the name of the id: 
```
query targetInfo {
  target(ensemblId: "ENSG00000146648") {
    id
    approvedSymbol
    geneOntology{
      id
      name  # new field resolving gene ontology id to name
      aspect
      evidence
      geneProduct
      source
    }
  }
}
```

**Comment by d0choa** [comment]
Thanks! The way it's been done in a few places in the past is more like the next:

```
query targetInfo {
  target(ensemblId: "ENSG00000146648") {
    id
    approvedSymbol
    geneOntology{
      term{
        id
        name
      }      
      aspect
      evidence
      geneProduct
      source
    }
  }
}
```

But it's essentiality the same thing.

**Comment by d0choa** [comment]
@cmalangone has implemented some of these. She might be able to point to some implementations

**Comment by JarrodBaker** [comment]
I've updated the API (not yet deployed) such that the query from @d0choa will work. I'll write in the release channel once the changes are live.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main`
