### ISSUE TITLE
Update Safety summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1676]
With the new `target` ETL pipeline and API response, we have new target safety insights curated by the data team.

The target safety data has a new schema and will only require one data table.

```
query targetSafetyInfoAR {
  target(ensemblId: "ENSG00000169083") {
    id
    approvedSymbol
    safetyLiabilities{
      biosample{
        tissueLabel
        tissueId
        cellLabel
        cellFormat
        cellId
      }
      datasource
      effects{
        direction
        dosing
      }
      event
      eventId
      literature
      study{
        name
        description
        type
      }
    }
  }
}
```
Sample query: [AR](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetSafetyInfoAR%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000169083%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20safetyLiabilities%7B%0A%20%20%20%20%20%20biosample%7B%0A%20%20%20%20%20%20%20%20tissueLabel%0A%20%20%20%20%20%20%20%20tissueId%0A%20%20%20%20%20%20%20%20cellLabel%0A%20%20%20%20%20%20%20%20cellFormat%0A%20%20%20%20%20%20%20%20cellId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20datasource%0A%20%20%20%20%20%20effects%7B%0A%20%20%20%20%20%20%20%20direction%0A%20%20%20%20%20%20%20%20dosing%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20event%0A%20%20%20%20%20%20eventId%0A%20%20%20%20%20%20literature%0A%20%20%20%20%20%20study%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

Can we please make the following changes to the summary widget and detail view based on the [design specification](https://docs.google.com/presentation/d/1_P0j0CARWIsB7BhuaL6q7ViEcF9N0jp0coSWPsib56c) reviewed by @d0choa and @ireneisdoomed?

### Summary widget

- [x] Update the summary widget to show "`n` unique safety events where `n` is the total number of unique safety events returned in the `target.safetyLiabilities` array (note: the uniqueness should be based on the `target.safetyLiabilities[x].event` field)

![Target Safety](https://user-images.githubusercontent.com/7490258/131715940-4be3fb46-7925-47fb-b3c2-8fe99aca358a.png)

### Detail view

- [x] Update the description to read:

> Reported safety effects and risk information for **target.approvedSymbol** . Source: [Open Targets](https://platform-docs.opentargets.org/target/safety).

- [x] Create a new data table with the following columns:

| Safety event | Biosamples | Dosing effects | Experimental studies | Source |
| -- | -- | -- | -- | -- |
| `safetyLiabilities[x].event` | Length of `safetyLiabilities.biosamples` | FontAwesome icons in blue or grey depending on `safetyLiabilities[x].effects[y]` | Length of `safetyLiabilities[x].study` | `safetyLiabilities[x].datasource` |
| Decreased memory | 2 biosamples | FontAwesome arrow-alt-circle-down in `#3489ca`<br /> FontAwesome arrow-alt-circle-down in `#e0e0e0` | N/A | Bowes, et al. (2012) |
| Regulation of steroid biosynthetic process | 1 biosample | FontAwesome arrow-alt-circle-down in  `#e0e0e0` <br /> FontAwesome arrow-alt-circle-down in `#e0e0e0` | 4 studies | ToxCast

- [x] Add the "Show more rows" functionality

- [x] Add the search bar and allow users to search by all columns

- [x] In the "Safety event" column, display the `event` field. If the `eventId` field is not `null`, link the `event` label to the relevant disease/phenotype profile page (e.g.  [Decreased attention](https://platform.opentargets.org/disease/NCIT_C117245)). If `eventId` is `null`, just display the `event` label.

![Target Safety (1)](https://user-images.githubusercontent.com/7490258/131718958-df71eab4-f17d-4be0-b083-409f3e520932.png)

- [x] In the "Biosamples" column, display the length of the `biosamples` array and open the drawer component. Inside, display one of two unordered lists — "Organ system" and "Assay". For the "Organ system" list, display each `biosample[x].tissueLabel` and link OLS using identifiers.org — `https://identifiers.org/` + `biosample.tissueId`. For the "Assay" list, display each `biosample[x].cellFormat` and `biosample[x].cellLabel`. 

![Target Safety (5)](https://user-images.githubusercontent.com/7490258/131722615-dc1995de-e2cb-4780-b156-f69423f183aa.png)

![Target Safety (3)](https://user-images.githubusercontent.com/7490258/131720796-f0c3ae20-72dc-4215-9205-6a37ef0f0ec0.png)

![Target Safety (4)](https://user-images.githubusercontent.com/7490258/131720801-f0eecae9-331c-439c-ba1c-d09e92867c96.png)

- [x] In the "Dosing effects" column, display the FontAwesome [`arrow-alt-circle-down`](https://fontawesome.com/v5.15/icons/arrow-alt-circle-down?style=solid) and [`arrow-alt-circle-up`](https://fontawesome.com/v5.15/icons/arrow-alt-circle-up?style=solid) icons in `#e0e0e0`. If `safetyLiabilities[x].effects[y].direction` is `inhibition`, change the `arrow-alt-circle-down` to `#3489ca`. Conversely, if `safetyLiabilities[x].effects[y].direction` is `activation`, change the `arrow-alt-circle-up` to `#3489ca`. Note that there are examples where both icons should be `#3489ca` (e.g. [CHM1 and "blurred vision"](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetSafetyInfoCHRM1%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000168539%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20safetyLiabilities%7B%0A%20%20%20%20%20%20biosample%7B%0A%20%20%20%20%20%20%20%20tissueLabel%0A%20%20%20%20%20%20%20%20tissueId%0A%20%20%20%20%20%20%20%20cellLabel%0A%20%20%20%20%20%20%20%20cellFormat%0A%20%20%20%20%20%20%20%20cellId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20datasource%0A%20%20%20%20%20%20effects%7B%0A%20%20%20%20%20%20%20%20direction%0A%20%20%20%20%20%20%20%20dosing%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20event%0A%20%20%20%20%20%20eventId%0A%20%20%20%20%20%20literature%0A%20%20%20%20%20%20study%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)) and many examples when both icons will remain `#e0e0e0` as `event` is `null` (e.g. [ESR1 and receptor binding](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetSafetyInfoESR1%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000091831%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20safetyLiabilities%7B%0A%20%20%20%20%20%20biosample%7B%0A%20%20%20%20%20%20%20%20tissueLabel%0A%20%20%20%20%20%20%20%20tissueId%0A%20%20%20%20%20%20%20%20cellLabel%0A%20%20%20%20%20%20%20%20cellFormat%0A%20%20%20%20%20%20%20%20cellId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20datasource%0A%20%20%20%20%20%20effects%7B%0A%20%20%20%20%20%20%20%20direction%0A%20%20%20%20%20%20%20%20dosing%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20event%0A%20%20%20%20%20%20eventId%0A%20%20%20%20%20%20literature%0A%20%20%20%20%20%20study%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)).

If the icon is active (`#3489ca`), display a tooltip with the `event[x].direction` and `event[x].dosing` values.

![Target Safety (6)](https://user-images.githubusercontent.com/7490258/131722815-d3871ae6-9b55-404d-aa37-580f11238e4c.png)

![Target Safety (7)](https://user-images.githubusercontent.com/7490258/131722827-a1df9745-7582-4860-a720-71c256474c9a.png)

- [x] In the "Experimental studies" column, display the length of the `study` array and open the drawer component. Inside, display each study entry — `study.name`, `study.type`, and `study.description`.

![Target Safety (8)](https://user-images.githubusercontent.com/7490258/131723162-18144d58-eaf5-4f2e-a68e-26f98ee28225.png)

![Target Safety (9)](https://user-images.githubusercontent.com/7490258/131723172-aef95073-c5ed-40d8-953a-2738be5db723.png)

- [x] In the "Source" column, display the `safetyLiabilities[x].datasource` value. If `safetyLiabilities[x].literature` is not `null`, it will contain a PubMed ID. If available, use the `safetyLiabilities[x].literature` value and open the publications drawer to show the citation and abstract.

**Comment by ireneisdoomed** [comment]
Awesome @mirandaio, many thanks!

There is something we forgot to indicate in the instructions, though.
The references of the sources without a PubMed ID must be handled in the FE, so:
- if `safetyLiabilities[x].datasource == ToxCast` we should link to `https://www.epa.gov/chemical-research/exploring-toxcast-data-downloadable-data`
- if `safetyLiabilities[x].datasource == HeCaToS ` we should link to `https://cordis.europa.eu/project/id/602156/reporting`
- if `safetyLiabilities[x].datasource == Urban et al. (2012)` we should link to `https://doi.org/10.1002/9781118098141.ch2`

**Comment by mirandaio** [comment]
Hi @ireneisdoomed can you double check here https://deploy-preview-446--platform-app.netlify.app/target/ENSG00000169083 if the links are working accordingly? Thanks!

**Comment by ireneisdoomed** [comment]
In the case of ToxCast, the string you should be expecting is `ToxCast`. Currently the API returns `Toxcast` but this is something we will be fixing.

Otherwise it looks great, unless @andrewhercules has any comment :)

**Comment by andrewhercules** [comment]
Looks good to me! 👍
