### ISSUE TITLE
Update Pathways summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1678]
With the new `target` ETL pipeline and API response, we can update the Pathways summary widget and detail view.

Full specification below — see https://github.com/opentargets/platform/issues/1678#issuecomment-897736303

**Comment by JarrodBaker** [comment]
This is now available in the API. For example:

```
query targets {
  target(ensemblId: "ENSG00000168143") {
    id
    pathways {
      pathway
      pathwayId
      topLevelTerm
      url
    }
  }
}
```

**Comment by andrewhercules** [comment]
The Reactome pathway data is now returned in the API `pathways` field.

Can we please update the Pathways summary widget and detail view?

### Summary widget

- [ ] Update the logic to show "`n` Reactome pathways" where `n` is the length of the `pathways` array

### Detail view

- [ ] Remove the old table component and replace with the new table component

- [ ] Implement a data table:

| Pathway | Top-level parent pathway | View target and pathway |
| `pathways[x].pathway` | `pathways[x].topLevelTerm` |  link |

In the "Pathway" column, please link to Reactome using identifiers.org - `https://identifiers.org/reactome:` + `pathways[x].id`.

In the "View target and pathway" column, can we please display "[map-marker] Reactome pathway browser" where [map-marker] is the [FontAwesome map-marker icon](https://fontawesome.com/v5.15/icons/map-marker?style=solid) and link to Reactome using the following construct:

`https://reactome.org/PathwayBrowser/#/` + `pathways[x].id` + `&FLG=` + `target.approvedSymbol`

**Comment by JarrodBaker** [comment]
@andrewhercules do you need the `url` field to be returned from the API? From the above comment it looks like you're going to generate your own url, in which case I'd remove that field from the API/ETL.

**Comment by andrewhercules** [comment]
@JarrodBaker, yes can you please remove the `url` field from the ETL and API — we can construct a link using the ID and the identifiers.org registry service 👍

**Comment by mirandaio** [comment]
As discussed in meeting, Reactome third party widget will be removed.
