### ISSUE TITLE
Create explanatory diagram of data pipeline steps

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#168]
@elipapa commented on [Thu Jan 11 2018](https://github.com/opentargets/data_pipeline/issues/234)

---

@ElaineMcA commented on [Fri Aug 17 2018](https://github.com/opentargets/data_pipeline/issues/234#issuecomment-413890070)

High level as is and to be diagram for pipeline created by Miguel here:
https://drive.google.com/drive/folders/1BnweLwngFWOkB6F3Md6Oeut8wLDzOr0h

Further diagram on the data pipeline specific steps generated by @afaulconbridge.  Now under discussion as part of automating QC processes for further releases.

18.10: https://drive.google.com/drive/folders/1OPOPdILF4erCSF-fgB72VCyYwNgKH7sR

Latest view:
https://drive.google.com/drive/folders/1OPOPdILF4erCSF-fgB72VCyYwNgKH7sR

A freeze of diagram denoting changes in pipeline along with summary release announcement will be shared with key collaborators.

**Comment by ElaineMcA** [comment]
Related to https://github.com/opentargets/platform/issues/66

**Comment by hammer** [comment]
Related to https://github.com/opentargets/platform/issues/661

**Comment by d0choa** [comment]
Most recent version of the diagram in #661 resolves this issue
