### ISSUE TITLE
cm-latest.conf not found in platform-input-support

### ISSUE THREAD

**Issue by NJeanray** [opentargets/platform#1680]
Hello Open Targets Team,

I'm trying to deploy an instance of Open Targets locally, and I'm encountering some issues regarding the platform-input-support module installation. 

I cloned the repository and then, I ran :
`time docker run --rm -v /platform-input-support:/usr/src/app -e PIS_CONFIG=/usr/src/app/cm-latest.conf -e GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/svn-account.json -e GOOGLE_BUCKET=open-targets-data-releases/21.04-test/ quay.io/opentargets/platform-input-support:master -steps tep`

I got this error : 

> platform-input-support.py: error: File not found: /usr/src/app/cm-latest.conf
> ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python3', 'platform-input-support.py', '-steps', 'tep']' command failed.  (See above for error)
> Command exited with non-zero status 2
> 0.07user 0.04system 0:03.19elapsed 3%CPU (0avgtext+0avgdata 59404maxresident)k
> 0inputs+0outputs (0major+7405minor)pagefaults 0swaps

Looking at file cm-latest.conf, I cannot find it in the Github repository.

Could you please help ?

Thanks in advance,
Nathalie

**Comment by andrewhercules** [comment]
Hi @NJeanray!

The command that you tried will run `platform-input-support` with a custom configuration script and will also make a request for Google application credentials used by our collaborators. We recommend that you remove the configuration file portion - `PIS_CONFIG=/usr/src/app/cm-latest.conf` - and remove the Google portion - `GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/svn-account.json -e GOOGLE_BUCKET=open-targets-data-releases/21.04-test/`.

Please try and run the following instead:

`time docker run --rm -v /platform-input-support:/usr/src/app quay.io/opentargets/platform-input-support:master -steps tep`

This will use the default configuration file found in the repo - [config.yaml](https://github.com/opentargets/platform-input-support/blob/master/config.yaml).

Also, please note that this repo is still under active development and could change. Once we have finalised the codebase and approach, we will update the documentation.

**Comment by andrewhercules** [comment]
Ticket closed as README.MD for `platform-input-support` has been updated in the latest 21.09.5 release:

https://github.com/opentargets/platform-input-support/blob/21.09.5/README.md
