### ISSUE TITLE
Create Genetic Constraint summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1682]
With the new `target` ETL pipeline and API response, we can now display the genetic constraint data from gnomAD. 

```
query targetInfo {
  target(ensemblId: "ENSG00000170509") {
    id
    approvedSymbol
    geneticConstraint{
      constraintType
      exp
      obs
      oe
      oeLower
      oeUpper
      score
      upperBin
      upperBin6
      upperRank
      
    }
  }
}
```
[Sample query for HSD17B13](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000170509%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20geneticConstraint%7B%0A%20%20%20%20%20%20constraintType%0A%20%20%20%20%20%20exp%0A%20%20%20%20%20%20obs%0A%20%20%20%20%20%20oe%0A%20%20%20%20%20%20oeLower%0A%20%20%20%20%20%20oeUpper%0A%20%20%20%20%20%20score%0A%20%20%20%20%20%20upperBin%0A%20%20%20%20%20%20upperBin6%0A%20%20%20%20%20%20upperRank%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

Please note that if a target does not have Genetic Constraint data, the API responds with an empty array - `[]` - instead of `null`.

### Summary widget

- [x] Use the `target.geneticConstraint` array to display up to 3 terms separated by bullets (similar to how we separate out categories in the Gene Ontology, Tractability, and Baseline Expression widgets)

| `geneticConstraint.constraintType` | Label to display |
| --- | --- |
| "syn" | "Synonymous" |
| "mis" | "Missense" |
| "lof" | "pLoF" |

 ### Detail view

- [x] For the section description, please display the following placeholder text:

> Pathogenicity metrics for the Ensembl canonical transcript of **TARGET-SYMBOL**. Source: [gnomAD](https://gnomad.broadinstitute.org/)

- [ ] Display a data table similar to what is available in gnomAD (e.g. [HSD17B13](https://gnomad.broadinstitute.org/gene/ENSG00000170509?dataset=gnomad_r2_1)). Please use the [design specification available on the team Google Drive](https://docs.google.com/presentation/d/1zjmHn-kaf1ZJ9a2YB8qE4Iqpi5MtbyRMPC2kD735_wg) 

| Category | Expected SNVs | Observed SNVs | Constraint metrics |
| --- | --- | --- | --- |
| `geneticConstraint.constraintType` | `geneticConstraint.exp` | `geneticConstraint.obs` | Z = `geneticConstraint.score` <br /> o/e = `geneticConstraint.oe` (`geneticConstraint.oeLower` - `geneticConstraintc.oeUpper`) |

![Genetic Constraint (2)](https://user-images.githubusercontent.com/7490258/129160914-3169a2b4-833e-40fb-946e-26b817d46558.jpg)

![Genetic Constraint (1)](https://user-images.githubusercontent.com/7490258/129160933-ae3feed9-2916-4873-8e0c-7a85fa7f7e4d.jpg)

The Constraint Assessment section is between 0 and 5 circles that are in the Open Targets Blue `#3489ca`. The number of circles that are in blue depends on the `upperBin6` value, which ranges from `0` to `5`.

![Genetic Constraint](https://user-images.githubusercontent.com/7490258/129161089-0b20055c-aecc-4611-b8f2-d85bd603907b.jpg)

Underneath the circle, please display a link to gnomAD's gene profile page using the following construct — https://gnomad.broadinstitute.org/gene/ + `target.id`. Please label the link "`target.approvedSymbol` constraint report".

For the Constraint Assessment section tooltip, please display:

> gnomAD Genetic Constraint rank: `upperRank`
>
> Binned representation of {target.approvedSymbol} rank in the loss-of-function observed/expected upper bound fraction (LOEUF) distribution. Higher scored assessments correspond to strong selection against predicted loss-of-function (pLoF) variation in the particular gene.

**Comment by andrewhercules** [comment]
@d0choa, as a placeholder for the description I have used:

> Pathogenicity metrics for the Ensembl canonical transcript of **TARGET-SYMBOL**. Source: [gnomAD](https://gnomad.broadinstitute.org/)

Please feel free to the description.

**Comment by d0choa** [comment]
About the description:

> Mutational constraint observed in TARGET-SYMBOL canonical transcript in natural populations. Source: [gnomAD](https://gnomad.broadinstitute.org)

**Comment by d0choa** [comment]
About the Constraint assessment tooltip:

> Binned representation of {target.approvedSymbol} rank in the loss-of-function observed/expected upper bound fraction (LOEUF) distribution. Higher scored assessments correspond to strong selection against predicted loss-of-function (pLoF) variation in the particular gene.

**Comment by andrewhercules** [comment]
@mirandaio, the widget looks great! 👍 

After discussing with @d0choa, can we please make the following adjustment?

1. Rename the "TARGET-SYMBOL constraint report" to the number of blue circles and a mapped term — see table below. The hyperlink address can remain, linking users to the gnomAD website

| Number of blue circles | Display label |
| --- | --- |
| 5 | 5/5 - very high constraint |
| 4 | 4/5 - high constraint |
| 3 | 3/5 - medium constraint |
| 2 | 2/5 - low constraint |
| 1 | 1/5 - very low constraint |
| 0 | 0/5 - very low constraint | 

<img width="404" alt="Screenshot 2021-09-01 at 15 16 57" src="https://user-images.githubusercontent.com/7490258/131703986-9f71aff6-70ca-42b8-a8a0-695a725f7f9c.png">
