### ISSUE TITLE
Remove `urlApiBeta` from `platform-app` configuration

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1683]
The `urlApiBeta` configuration variable is not used within the `platform-app` codebase. Can we please remove?

**Comment by andrewhercules** [comment]
@LucaFumis I have re-assigned this for post 21.09 release as I know you have made config file changes for the partner-preview instance.

**Comment by LucaFumis** [comment]
Thank you @andrewhercules - yes, this has in fact been addressed in the partner preview branch, so will be all done when we merge that work into main.
