### ISSUE TITLE
Rescue Bibliography summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1689]
The format of the Bibliography data has not changed with the new `target` ETL.

Can we please rescue and reimplement the existing queries and summary widget and detail view components for Bibliography data?

**Comment by ktsirigos** [comment]
work completed, merged into main.

**Comment by d0choa** [comment]
The component does not list publications for some targets in main but works fine in production.

- [PTEN in main](https://main--platform-app.netlify.app/target/ENSG00000171862)
- [PTEN in production](https://platform.opentargets.org/target/ENSG00000171862)

**Comment by andrewhercules** [comment]
Upon further review based on @d0choa's comment above, there are other targets where the Bibliography section is empty, including:

- PTEN (ENSG00000171862
- BRAF (ENSG00000157764)
- NTRK1 (ENSG00000198400)
- PDGFRB (ENSG00000113721)
- RET (ENSG00000165731)

Some of these targets also have an error with Known Drugs — see #1698.

In the console, it reports an "Internal Server Error" and the API returns an `errors` array — see the [PDGFRB query](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=%0Aquery%20SimilarEntitiesQuery%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000113721%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedName%0A%20%20%20%20similarEntities%28size%3A15%29%20%7B%0A%20%20%20%20%20%20score%0A%20%20%20%20%20%20object%20%7B%0A%20%20%20%20%20%20%20%20...%20on%20Target%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20...%20on%20Drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20...%20on%20Disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20literatureOcurrences%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20%20%20pmcid%0A%20%20%20%20%20%20%20%20publicationDate%0A%20%20%20%20%20%20%20%20sentences%20%7B%0A%20%20%20%20%20%20%20%20%20%20section%0A%20%20%20%20%20%20%20%20%20%20matches%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20mappedId%0A%20%20%20%20%20%20%20%20%20%20%20%20matchedLabel%0A%20%20%20%20%20%20%20%20%20%20%20%20sectionStart%0A%20%20%20%20%20%20%20%20%20%20%20%20sectionEnd%0A%20%20%20%20%20%20%20%20%20%20%20%20startInSentence%0A%20%20%20%20%20%20%20%20%20%20%20%20endInSentence%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) and [RET query](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=%0Aquery%20SimilarEntitiesQuery%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000165731%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedName%0A%20%20%20%20similarEntities%28size%3A15%29%20%7B%0A%20%20%20%20%20%20score%0A%20%20%20%20%20%20object%20%7B%0A%20%20%20%20%20%20%20%20...%20on%20Target%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20approvedSymbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20...%20on%20Drug%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20...%20on%20Disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20literatureOcurrences%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20%20%20pmcid%0A%20%20%20%20%20%20%20%20publicationDate%0A%20%20%20%20%20%20%20%20sentences%20%7B%0A%20%20%20%20%20%20%20%20%20%20section%0A%20%20%20%20%20%20%20%20%20%20matches%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20mappedId%0A%20%20%20%20%20%20%20%20%20%20%20%20matchedLabel%0A%20%20%20%20%20%20%20%20%20%20%20%20sectionStart%0A%20%20%20%20%20%20%20%20%20%20%20%20sectionEnd%0A%20%20%20%20%20%20%20%20%20%20%20%20startInSentence%0A%20%20%20%20%20%20%20%20%20%20%20%20endInSentence%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D).

**Comment by d0choa** [comment]
At the moment this problem seems to be caused by an already diagnosed problem in the API response. See #1648
We can revisit, once the API data comes fixed

**Comment by ktsirigos** [comment]
bibliography widget works fine now on the target profile page.

#1648 is related to disease profile page query, not target query.

**Comment by d0choa** [comment]
I agree with @ktsirigos. We can address the bug fixes in #1648. Only to keep the record straight, the problem also affects the target profile page as described [here](https://github.com/opentargets/platform/issues/1648#issuecomment-900272273)
