### ISSUE TITLE
Upgrade gene2phenotype evidence to the new terminology 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1694]
As reported by @emcdonagh-OT, gene2phenotype will be updating their terminology as part of the geneCC next September- [More info](https://www.ebi.ac.uk/gene2phenotype/updates_to_our_terms).

We will need to:
- [ ] review the gene2phenotype parser to prevent any potential issues (e.g. SO mapping)
- [ ] revise the ETL config to make sure evidence is correctly scored

**Comment by ktsirigos** [comment]
Gene2phenotype has been updated on their side.

**Comment by d0choa** [comment]
Based on discussion, we are committing this work to 22.02, @DSuveges can you assign accordingly?

**Comment by DSuveges** [comment]
I'm closing this ticket as the tasks around g2p dataset update is captured here: #1880
