### ISSUE TITLE
Facets: selecting child checkbox keeps parent selected

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#17]
@LucaFumis commented on [Tue May 15 2018](https://github.com/opentargets/webapp/issues/277)

### Observed behaviour
Target association page for BRAF, select 'Genetic Associations' under datatypes.
Now expand the Genetic associations facet via the little caret on the right: this displays the datasources for genetic association.
Select 'uniprot' (or any other).
The data doesn't change. The URL still shows the datatype as selected.
This seems to be longstanding.

### Expected behaviour
Selecting a child facet should deselect the parent facet (at least for datatypes), as parent data encompasses children data.
If for some reason this is not possible, then a user should not be able to select child filter if parent is selected

### Environment
* Version: 3.6.2
* Browser: Chrome, any

---

@LucaFumis commented on [Tue Aug 07 2018](https://github.com/opentargets/webapp/issues/277#issuecomment-411112691)

I had started looking into this but the facets code is non-trivial and will need to spend a little more time on it.

**Comment by d0choa** [comment]
No action is expected in this ticket as all efforts are focused on the React app
