### ISSUE TITLE
Rescue Intogen, Cancer Gene Census and ClinVar somatic evidence widgets

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1701]
The three widgets have a shared component that it's crashing.

The reason is because they query a section in the target object that has changed slightly the structure. An example is the ([Intogen subquery](https://github.com/opentargets/platform-app/blob/337af2f8558cfc717314475cda692784e0df1244/src/sections/evidence/IntOgen/sectionQuery.gql#L35)). It works in production but crashes in the new API.

We need to update the next fragment: 

```
  target(ensemblId: "ENSG00000157764") {
    id
    hallmarks {
      attributes {
        reference {
          pubmedId
          description
        }
        name
      }
    }
  }
```

Next the updated query.

```
  query{
    target(ensemblId: "ENSG00000157764") {
    id
    hallmarks {
      attributes {
        description
        pmid
        name
      }
    }
  }
}
```

**Comment by ktsirigos** [comment]
work done and merged
