### ISSUE TITLE
Remove OtTableRF and all dependencies from platform-app

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1707]
With the migration to the new target profile page, we can finally deprecate the [OtTableRF](https://github.com/opentargets/platform-app/blob/337af2f8558cfc717314475cda692784e0df1244/src/components/OtTableRF.js) component and all its dependencies (e.g. [FilteringOtTableRF.js](https://github.com/opentargets/platform-app/blob/337af2f8558cfc717314475cda692784e0df1244/src/components/FilteringOtTableRF.js))

All current references to this component (Chemical Probes, Gene Ontology and Mouse Phenotypes) will be replaced in work scoped before 21.09.

Please remove OtTableRF and all dependencies.

**Comment by andrewhercules** [comment]
Ticket closed as work to remove the old table component captured in:

- https://github.com/opentargets/platform/issues/1639
- https://github.com/opentargets/platform/issues/1677
- https://github.com/opentargets/platform/issues/1675

**Comment by andrewhercules** [comment]
Reopening ticket to ensure that bundle prepared for 21.09 has all OtTableRF components and code removed

**Comment by LucaFumis** [comment]
Chemical probes widget: table component has been updated (still not merged though).

**Comment by andrewhercules** [comment]
@mirandaio can you please remove the OtTableRF code from the `platform-app`?
