### ISSUE TITLE
Change URL of OpenFDA in the drug page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#171]
In a page like this:
https://www.targetvalidation.org/summary?drug=CHEMBL1201823

when scrolling down to adverse effects and clicking on OpenFDA it gives an error message.

I believe that their URL has changed.

Can we point to https://open.fda.gov/apis/drug/event/ instead of the current https://open.fda.gov/drug/event/?

Also, please add the "period" after OpenFDA.

**Comment by LucaFumis** [comment]
Fixed in commit 8eabd7f2174a2ee04735735b4f9a048a9d616b3c
