### ISSUE TITLE
Update Data Download page in parter preview Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1717]
On the data downloads page, can we please add a notification about the type of data files available and how to access the raw data?

>  Important Note:
> These data files do not contain any of the custom data found in this version of the Platform. They are the same files that are available from the public Platform. To download the data for a specific project, please visit the [Open Targets Intranet](http://home.opentargets.org/) and submit a data request.

This notification should only be visible in the partner preview version, so can we please encapsulate this in logic with a flag that can be set and changed in the `config.js` deployment file?

**Comment by ktsirigos** [comment]
work completed
