### ISSUE TITLE
Change header in partner preview Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1718]
To ensure that users are aware they are visiting the partner preview Platform, can we please adjust the navigation bar to read "Open Targets Platform - Partner Preview", followed by a reusable component showing the [FontAwesome `fa-lock` icon](https://fontawesome.com/v5.15/icons/lock?style=solid) and a tooltip message?

<img width="1050" alt="Screenshot 2021-08-24 at 17 22 26" src="https://user-images.githubusercontent.com/7490258/130653527-e4430aae-33d8-404e-a671-d826ea8bba14.png">

With the `fa-lock` icon, can we please show the following tooltip on-hover?

> The partner preview Platform contains all data found in the public Platform along with pre-publication data from Open Targets' projects and new features developed by the Platform team. Please do not share data or screenshots outside of the consortium partners. For more information, please email helpdesk@opentargets.org."

Please ensure that the "- Partner Preview", `fa-lock` icon, and tooltip are captured in a configuration variable that by default is set to `false`.  In the partner preview Platform deployment context will overwrite and set to `true`.

Note: this lock icon and tooltip component will be reused elsewhere in the platform, including on the evidence and associations pages.

**Comment by ktsirigos** [comment]
work completed
