### ISSUE TITLE
Pipeline README.md states that mrtarget can be installed via pip

### ISSUE THREAD

**Issue by Docproc** [opentargets/platform#172]
The pipeline [README.md](https://github.com/opentargets/data_pipeline/blob/master/README.md) states that the data pipeline can be installed from PyPi via `pip install mrtarget` - however there is no such package on PyPi, although other `opentargets` packages do exist.

**Comment by mkarmona** [comment]
@Docproc, I don't think we should even consider offering the pipeline through pypi at the moment. Let's see how the `pipeline` evolves and then we can revisit this issue. Just to be clear here, the indication you are pointing to must be removed. Thanks anyway for spotting this out.

**Comment by Docproc** [comment]
I'd suggest leaving this issue open until the erroneous text is removed from the README (I know @MichaelaEBI is working on this)

**Comment by afaulconbridge** [comment]
I think this ticket has been super-seeded by opentargets/platform#259 which is to rewrite and update the Readme file more generally - and which should include solving this issue.

**Comment by MichaelaEBI** [comment]
I removed the 'Package Users' section from the readme file in the readme_update branch.
