### ISSUE TITLE
Rescue OTAR project summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1720]
Can we please rescue the [OTAR projects widget](https://github.com/opentargets/platform-app/tree/main/src/sections/disease/OTProjects)?

In a previous Platform release, the summary widget and detail view were hidden using [the `flagShowOTARProjects` config](https://github.com/opentargets/platform-app/blob/135d3837936dfe1ad2f2b437a4797a6afd90ce9f/src/config.js#L14). By default, the summary widget and detail view should be hidden and we will set it to be shown in the deployment context profile.

For both the summary widget and detail view, the query remains the same:

```
query diseaseOTARProjectInfo {
  disease(efoId: "EFO_ID") {
    id
    name
    otarProjects {
      otarCode
      status
      projectName
      reference
    }
  }
}
```
Sample query: [colorectal cancer](https://api.partner-platform.devppreview21081.opentargets.xyz/api/v4/graphql/browser?query=query%20otarProjectData%20%7B%0A%20%20disease%28efoId%3A%20%22EFO_0005842%22%29%20%7B%0A%20%20%20%20otarProjects%20%7B%0A%20%20%20%20%20%20otarCode%0A%20%20%20%20%20%20status%0A%20%20%20%20%20%20projectName%0A%20%20%20%20%20%20reference%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
_*Note: you must be connected to EBI VPN to run the query_

Can we please make two adjustments to the detail view data table?

- [x] Update the component to use the partner preview Platform API (currently it uses a static JSON file)
- [x] Drop the "Disease" column
- [x] Sort the table by the "Status" column with "Active" projects appearing first
- [x] Add the lock icon component and tooltip to the summary widget and detail view

![OTAR Project Data and Evidence Design Specification (3)](https://user-images.githubusercontent.com/7490258/130821415-b6bcb3bc-e1d0-4136-8f6f-cf35eaa4b58c.png)

![OTAR Project Data and Evidence Design Specification (4)](https://user-images.githubusercontent.com/7490258/130821412-e1969409-4d6f-4510-87c5-d70e86f634cd.png)

**Comment by ktsirigos** [comment]
work done
