### ISSUE TITLE
Create new OTAR CRISPR summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1721]
New prepublication data has been [ingested by the ETL pipeline](https://github.com/opentargets/platform-etl-backend/blob/9594e336929ccdbbbddaedda41a32e483258a78c/src/main/resources/reference.conf#L716) with relevant fields also exposed by the API.

The data has a datatype of `ot_partner` and the datasource is `ot_cripsr`.

And so we can now display the data on the evidence page using the following query stucture.

```
query otarProjectDataEvidence {
  disease(efoId: "EFO_xxxxxxxx") {
    evidences(ensemblIds: ["ENSGxxxxxxxxxxx"], datasourceIds: ["ot_crispr"]) {
      count
      rows {
        disease {
          id
          name
        }
        projectId
        contrast
        studyOverview
        cellType
        cellLineBackground
        crisprScreenLibrary
        statisticalTestTail
        resourceScore
      }
    }
  }
}
```
Sample queries are available on [slide 5 of the design specifications document](https://docs.google.com/presentation/d/1vgSRvlF_HRdgan-7Ds4bCUnrA-sL31ZJlqiZhDopfY4/edit#slide=id.gec481d1ba8_0_10) .

Can we please build an OTAR CRISPR summary widget and detail view for the evidence page, based on the following [design specifications](https://docs.google.com/presentation/d/1vgSRvlF_HRdgan-7Ds4bCUnrA-sL31ZJlqiZhDopfY4/edit#slide=id.ge8c679aa27_0_32)?

### Summary widget

- [x] Display "Open Targets CRISPR" and the FontAwesome lock-icon and tooltip component used elsewhere (e.g. #1718)

- [x] Display the number of entries

![OTAR Project Data and Evidence Design Specification (6)](https://user-images.githubusercontent.com/7490258/131341016-c654f3ee-9aae-4b88-af46-5cc019f5f121.png)

### Detail view

- [x] Display the "OTAR project data" datatype chip

- [x] Display a placeholder section description and link the source "Open Targets" label to the Open Targets Intranet available at http://home.opentargets.org/:

> Prepublication CRISPR knockout screens from Open Targets (OTAR) experimental projects, associating **TARGET-SYBMOL** and **DISESE NAME.** Source: [Open Targets](http://home.opentargets.org/)

- [x] Create a data table

| Reported disease | OTAR project code | Study overview | Cell type | CRISPR screen library | Significance |
| -- | -- | -- | -- | -- | -- |
`disease.name` | `projectId` | `contrast` if not `null`, otherwise show `studyOverview` | `cellType` | `crisprScreenLibrary` | `resourceScore` with `statisticalTestTail` as a FontAwesome icon |

- [x] In the "Contrast" column, if `contrast` is not `null`, show the `contrast` value and on-hover, show `studyOverview`. However, if `contrast` is `null`, just display the `studyOverview` field with no tooltip (request: can we fix the width of the column so that longer study overview strings wrap to the next line?)

- [x] In the "Cell Type" column, please display a tooltip with the `cellLineBackground` value if not `null`
 
- [x] In the "Significance" column: display the `resourceScore` value and beside, show the FontAwesome [caret-square-up](https://fontawesome.com/v5.15/icons/caret-square-up?style=solid) if the `statisticalTestTail` value is `upper tail` and show the [caret-square-down](https://fontawesome.com/v5.15/icons/caret-square-down?style=solid) if the `statisticalTestTail` value is `lower tail`; on-hover, show the `statisticalTestTail` value`; style both icons using the primary colour (`#407253`) variable

- [x] Sort the table by the "Significance" column with the lowest `resourceScore` at the top
 
- [x] Include the ability to search the data table, download in CSV/TSV/JSON formats, and to show more rows
 
![OTAR Project Data and Evidence Design Specification (9)](https://user-images.githubusercontent.com/7490258/131544169-6a90da5d-607e-48d8-9c63-fbd1325f6813.png)

![OTAR Project Data and Evidence Design Specification (10)](https://user-images.githubusercontent.com/7490258/131544210-beb31d5b-6776-4086-b9f5-1a57c92870ad.png)

**Comment by ktsirigos** [comment]
work done
