### ISSUE TITLE
Update OTAR project to EFO mapping file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1722]
The original OTAR project --> EFO mapping file has been updated and is available on the [team Google Drive](https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs)

To prepare for the next pipeline run, can we please make the following changes?

- [x] Check cancer/oncology terms and align with latest [EFO release v3.33.0](https://github.com/EBISPOT/efo/releases/tag/v3.33.0) @ktsirigos 
- [x] Add any new projects @andrewhercules/@ktsirigos
- [x] Review disease/phenotype mappings @andrewhercules 
- [x] Review project status (Active, closed) @ktsirigos 
- [x] Review data availability @sarahyoung3 
- [x] Update publications, preprints, and other publication data @ktsirigos

**Comment by sarahyoung3** [comment]
Data availability and project status updated @ktsirigos @andrewhercules

**Comment by ktsirigos** [comment]
- Added 1 more project ([OTAR050](http://home.opentargets.org/OTAR050)) that was missing.

**Comment by sarahyoung3** [comment]
@ktsirigos - OTAR050 is the same as OTAR2050 that is already listed

**Comment by andrewhercules** [comment]
Thanks everyone for updating the file! 👍 

We will discuss in tomorrow's meeting as we may change the column labels to align with existing API fields.

**Comment by ktsirigos** [comment]
work completed.
