### ISSUE TITLE
Add MousePhenotypes ingest/egress to PIS/POS

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1724]
The data team has developed the mouse phenotypes data set used in the Open Targets platform. This data is made available through the API but is not used by the ETL. The data needs to be ingested via PIS, and inserted into ES via POS. 

Acceptance tests

- [ ] When I look at PIS I see that the file `gs://ot-team/dsuveges/evidence_test/phenodigm.pheno.json.gz` is saved to the data release bucket.
- [ ] When I look at POS I see a script that reads the file and ingests it into ElasticSearch. 

Notes: 
 - The file comes compressed and as a single unit. It might be necessary to decompress/split the file to allow the elastic loader to process it.

**Comment by JarrodBaker** [comment]
@DSuveges so we know where we can find the mouse phenotypes file in the future, is there a specific place where we should look? eg. `gs://open-targets/otar001-core/mousePhenotypes`?

**Comment by DSuveges** [comment]
@JarrodBaker The current pattern of the output file when running the parser looks like this:
```
gs://otar000-evidence_input/PhenoDigm/json/phenodigm-{timeStamp}.mousePhenotypes.json.gz
```
When `timeStamp` is in `yyyy-mm-dd` format. Please let us know if you have any concern. We can copy this file over to a different bucket with a fixed name if that would be more suitable for the ETL, or the file can be picked up by PIS. We are happy to accommodate the backend needs.

**Comment by ireneisdoomed** [comment]
@DSuveges I know the BE team has plans to rearrange the location of the input and output files because it is quite sparse at the moment.
I am personally uploading all the target-specific datasets to `gs://open-targets/otar001-core`. I would stick with this bucket for the mouse phenotypes too as Jarrod suggests.

**Comment by DSuveges** [comment]
Sounds good to me. @tskir, We have to make sure the snakefile is updated accordingly.

**Comment by JarrodBaker** [comment]
This issue has been duplicated by opentargets/platform#1769. Closing to avoid confusion.
