### ISSUE TITLE
Set relevant configuration for partner preview Platform deployment

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1729]
Prior to production run of partner preview Platform, we need to ensure that the following configuration is set in the `config.js` file and changed in the partner preview deployment context.

- Show relevant sections (OTAR projects, OTAR CRISPR)
- Show different navigation bar
- Show data downloads page notification
- Set correct API
- Set primary colour
- Set `colorRange` to change associations heat map and bubbles/tree views
- Set Google Tag Manager

**Comment by LucaFumis** [comment]
All options have been (or were already) included in the config except for the different navigation bar.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main`
