### ISSUE TITLE
Update associations heat map for partner preview Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1730]

**Comment by d0choa** [comment]
The first step that's required for this is to update the static content in the next files:

- [dataSources.js](https://github.com/opentargets/platform-app/blob/lf-partner-preview/src/dataSources.js)
- [dataTypes.js](https://github.com/opentargets/platform-app/blob/lf-partner-preview/src/dataTypes.js)

To include as placeholders, until confirmed by @andrewhercules:
- [ ] dataSources.js: `{ id: 'ot_crispr', label: "Open Targets CRISPR" }`
- [ ] dataTypes.js: `{ id: 'ot_partner', label: "Open Targets Projects" }`

**Comment by ktsirigos** [comment]
work done
