### ISSUE TITLE
Remove empty strings as `approvedSymbol` in new target

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1733]
As many as 19,795 targets have an empty string as `approvedSymbol`.

After review by @cmalangone and @JarrodBaker we found that a big fraction of these is due to Ensembl removing some symbols referring to contig names.

This is creating a downstream issue in which `approvedSymbol` empty strings are being merged with `targetFromSourceId` empty strings in Phewas evidence (#1731). Hopefully this will fix the issue.

```
>>> target.filter(F.col("approvedSymbol") == "").select("id", "approvedSymbol").show(5)
+---------------+--------------+
|             id|approvedSymbol|
+---------------+--------------+
|ENSG00000201701|              |
|ENSG00000205041|              |
|ENSG00000213016|              |
|ENSG00000213717|              |
|ENSG00000216781|              |
+---------------+--------------+
only showing top 5 rows

>>> target.filter(F.col("approvedSymbol") == "").count()
19795                                                                           
```

**Comment by JarrodBaker** [comment]
Issue fixed by [PR](https://github.com/opentargets/platform-etl-backend/pull/192)
