### ISSUE TITLE
Integrate cancer_biomarkers into the ETL

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1737]
We are adding Cancer Biomarkers as a new evidence source for the upcoming release (21.09). We need to make the necessary changes in the ETL for it to be integrated.

### 1. Schema
The current schema is in a mature state and no changes are expected:</summary>

```python
root
 |-- biomarkerName: string (nullable = true)
 |-- biomarkers: struct (nullable = true)
 |    |-- geneExpression: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- id: string (nullable = true)
 |    |    |    |-- name: string (nullable = true)
 |    |-- variant: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- functionalConsequenceId: string (nullable = true)
 |    |    |    |-- id: string (nullable = true)
 |    |    |    |-- name: string (nullable = true)
 |-- confidence: string (nullable = true)
 |-- datasourceId: string (nullable = true)
 |-- datatypeId: string (nullable = true)
 |-- diseaseFromSource: string (nullable = true)
 |-- diseaseFromSourceMappedId: string (nullable = true)
 |-- drugFromSource: string (nullable = true)
 |-- drugId: string (nullable = true)
 |-- drugResponse: string (nullable = true)
 |-- literature: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- targetFromSourceId: string (nullable = true)
 |-- urls: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- niceName: string (nullable = true)
 |    |    |-- url: string (nullable = true)
```

#### 1.1 New fields
This source is bringing a few of new fields that need to be exposed in the API, namely:
- [ ] `biomarkerName`: str
- [ ] `biomarkers`: struct
- [ ] `drugFromSource`: str
- [ ] `drugResponse`: str

### 2. Resolvable fields
- [ ] `biomarkers.variant.functionalConsequenceId` consists of Sequence Ontology codes that need to be resolved so that we can display the label in the FE.
- [ ] `biomarkers.geneExpression.id` consists of Gene Ontology codes that need to be resolved so that we can display the label in the FE.

### 3. Source config
The config file for this data source has already been added to `reference.conf`.
All strings have a score of 1 which is later on downweighted to 0.5 due to its datatype: 
```
{
       id: "cancer_genome_interpreter"
       unique-fields: [
         "biomarkerName",
         "confidence",
         "diseaseFromSource",
         "drugFromSource",
         "drugResponse"
       ],
       score-expr: "1.0"
     }
```

### 4. Evidence location
Evidence strings will follow the same pattern as the other sources found in `otar000-evidence_input`. They will be in a compressed JSON file here: gs://otar000-evidence_input/CancerBiomarkers/json, with the filename following the pattern: `cancer_biomarkers-YYYY-MM-DD.json.gz`

**Comment by cmalangone** [comment]
Added cancerbiomarker evidence to PIS

**Comment by cmalangone** [comment]
Added the conf info to the ETL
https://github.com/opentargets/platform-etl-backend/pull/202
