### ISSUE TITLE
Benchmark different threshold values for PhenoDigm evidence

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1743]
As suggested by @d0choa during one of the stand-ups, we can use the association benchmark script to evaluate how well different thresholds for PhenoDigm evidence perform. This would allow us to be less arbitrary in choosing the said theshold.

**Comment by d0choa** [comment]
I believe @ireneisdoomed had some extra results on this

**Comment by d0choa** [comment]
Duplicated from #1782
