### ISSUE TITLE
Fix data issues in the safety dataset

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1745]
There are some issues in the way the "Known Target Safety Risks" dataset was parsed, that are generating inconsistencies in the new safety object when compared with the production version. Some actions need to be done:

#### 1. Check how the parsing for **Lynch et al** data is done:
- Some Bowes events are somehow being exploded into Lynch evidence. I think it is only the acute ones. If we take ACHE as an example ([new v](https://deploy-preview-443--platform-app.netlify.app/target/ENSG00000087085) / [production](https://platform.opentargets.org/target/ENSG00000087085)):
    - `decreased gastrointestinal motility` is not part of the Lynch evidence. It is coming from Bowes.
#### 2. Check how the parsing for **Bowes et al** is done:
- The events listed do not correspond to Bowes but Lynch. If we take ADORA2A as an example ([new v](https://deploy-preview-443--platform-app.netlify.app/target/ENSG00000128271) / [production](https://platform.opentargets.org/target/ENSG00000128271)):

<details>
<summary>This is the list of events that should be appearing:</summary>

```python
coronary vasodilation
hypotension
Hyporeflexia
Tachycardia
negative regulation of platelet aggregation
negative regulation of leukocyte activation
negative regulation of locomotion
substance-induced sleep disorder
positive regulation of platelet aggregation
Increased blood pressure
nervousness
sexual arousal
insomnia
```
</details>

- Instead the 6 events that are displayed correspond to the ones annotated in Lynch.
- I presume the problem is due to the fact that these evidence almost never have a dosing effect associated (`effects.dosing == None`)
- the `biosamples` field must be therefore appropriately populated  (`cardiovascular system; central nervous system`, in this case)
#### 3. Add event information to **Force, Lamore and HeCaToS** as follows:
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/b472743c-1ca7-4210-ba8d-c6a22160d384)
#### 4. We are missing evidence when the event is not mapped to EFO. E.g. CHRNA1 ([nev v](https://deploy-preview-443--platform-app.netlify.app/target/ENSG00000138435) / [production](https://platform.opentargets.org/target/ENSG00000138435))
- See `"antihypertensive agent", "muscle relaxant"` from **Urban.** We are not picking up these records because these events are part of the unmapped to EFO set (`NO_EFO_mapping` sheet in the spreadsheet).
- In this case we are also missing Bowes's because of the above mentioned issue, where we list Lynch's events as being from Bowes.
#### 6. Change "Toxcast" data source name to `ToxCast`

Happy to provide more context or instructions if these are not clear enough.

**Comment by JarrodBaker** [comment]
Is number 4 a bug @d0choa , @ireneisdoomed . If we can't map the annotation to an EFO should we include the information?
