### ISSUE TITLE
Ontology: wrong order in therapeutic area codes / labels in association object

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#175]
@emepyc commented on [Wed Mar 15 2017](https://github.com/opentargets/data_pipeline/issues/93)

In the `association object -> disease -> efo_info -> therapeutic_area` we store the `labels` and the `codes` of the therapeutic areas as 2 independent arrays. The ordering of both are not always the same, so for example we see:

```
          "therapeutic_area": {
            "labels": [
              "hematological system disease",
              "neoplasm"
            ],
            "codes": [
              "EFO_0000616",
              "EFO_0005803"
            ]
          },
```
where EFO_0000616 is the code for neoplasm and EFO_0005803 is the code for hematological system disease.

Example from the rest api:
https://api.opentargets.io/v3/platform/public/association/filter?disease=EFO_0001642

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_pipeline/issues/93#issuecomment-403784446)

@mkarmona do you know if this is still an issue?

**Comment by afaulconbridge** [comment]
Bumping this to 19.02 since it can't be fit in 18.12 Also dropping priority, since no one is complaining about it...

**Comment by afaulconbridge** [comment]
Flagged by a user, so this is both still an issue and of interested to be solved.

**Comment by ElaineMcA** [comment]
From support ticket troubleshooting provided by @afaulconbridge: 
The correct way to solve it would be to change the API response to be more like the following:         

 "path": [
            [
              {
                "label": "disease",
                "uri": "http://www.ebi.ac.uk/efo/EFO_0000408"
              },
              {
                "label": "disease by anatomical system",
                "uri": "http://purl.obolibrary.org/obo/MONDO_0021199"
              },
              {
                "label": "disease of genitourinary system",
                "uri": "http://www.ebi.ac.uk/efo/EFO_0009663"
              },
              {
                "label": "reproductive system disease",
                "uri": "http://www.ebi.ac.uk/efo/EFO_0000512"
              },

(that's from EFO3, but the principle is the same)

However, that would require changes to the front end and API - both are scheduled for major work later this year already. At that point, we'll be able to solve this issue as a side-effect.

**Comment by AsierGonzalez** [comment]
Is this correct @afaulconbridge? 
> However, that would require changes to the front end and API - both are scheduled for major work later this year already. At that point, we'll be able to solve this issue as a side-effect.

My understanding is that it requires (hopefully smallish) changes to the pipeline itself, wherever the disease label and uri information is retrieved.

**Comment by afaulconbridge** [comment]
This should be fixed when EFO3 branch is merged into master.
