### ISSUE TITLE
Measuring overlap between PheWAS Catalog and GeneticsPortal evidence

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1755]
Due to old gene symbols used by PheWAS catalog, we see a large number of invalid evidence in the 21.09 release. It raises the question if it make sense to keep this datasource at all considering the significant overlap with the GeneticsPortal dataset.

The measurement of the overlap between the two datasets can justify retaining both sources. However if we see that the additional value by PheWAS is not substantial enough, this datasource will be dropped.

Things to consider:
- [ ] Diseases are curated two different ways for the two datasets.
- [ ] Targets might be complicated to match due to obsolete symbols.
- [ ] Publications and variant information might be useful to identify overlapping evidence.

**Comment by iandunham** [comment]
Can we map these via the synonyms?

**Comment by d0choa** [comment]
Yes, the mapping can be done as the data team has been doing for a while. We have been working on streamlining some processes and the problem of mapping outdated and potentially ambiguous symbols came out again.

What we are trying to assess here is independent of the mapping problem. At the moment, the PheWAS catalogue feed is a static picture of the meta-analysis of a quite old GWAS catalogue dump. We are trying to get metrics to get a more informed decision on the current value of the resource. The original study reported 66% of the signals were covered by the GWAS analysis already. The expectation is that the value shrunk due to much better powered recent studies.

@iandunham @DSuveges are there any other considerations we might be missing here?  How worth you think a PheWAS analysis on the genetics portal could be? Shall we be looking at treeWAS or any most recent methodologies instead?

**Comment by DSuveges** [comment]
It could be a huge effort to run such analyses, however we have the right set of genetic data with the right disease annotations. I'm not quite aware of the advantage of treeWAS over pheWAS, but it worth bringing up in the genetics meeting. I'm sure Maya and Jeremy knows better. It's almost like a separate OTAR project.

Regarding PheWAS Catalog, I'm also concerned about the "aging" of the data as it was build on the early 2012 release of the GWAS Catalog.

**Comment by iandunham** [comment]
The original motivation behind including the PheWAS catalog was to get a PheWAS dataset. Given the age of the data and the fact that we have PheWAS in the Genetic Portal from UKBB and Finngen, I think it is reasonable to consider dropping this, and replacing it with an equivalent analysis from the Genetics Portal - if I understand correctly this almost comes for free. I think there has been some examination of TreeWAS - I don't think the aims of the analysis are the same necessarily although related.

**Comment by Jeremy37** [comment]
I don't know that old paper, but getting PheWAS from the genetics data should be simple.
What format would be needed?
I see that the current scoring in the Platform documentation uses PheWAS p values all the way up to 0.5. We filter sumstats for p < 0.05, which I think might be a reasonable cutoff for including anything as nonzero evidence.

**Comment by DSuveges** [comment]
Thanks @Jeremy37 for chipping in! So the following file is used to generate disease/target evidence:
`gs://otar000-evidence_input/PheWAS/data_files/phewas-catalog-19-10-2018.csv`

This is how it looks like:
```
"chromosome"  "basepair"  "gene"  "snp"         "phewas_code"  "phewas_string"            "cases"  "odds_ratio"  "p"
4             110659067   "*CFI"  "rs10033900"  "008"          "Intestinal infection"     406      1.107         0.1561
4             110659067   "*CFI"  "rs10033900"  "010"          "Tuberculosis"             36       1.075         0.7598
4             110659067   "*CFI"  "rs10033900"  "038"          "Septicemia"               605      0.943         0.3265
4             110659067   "*CFI"  "rs10033900"  "041"          "Bacterial infection NOS"  1040     1.007         0.8808
4             110659067   "*CFI"  "rs10033900"  "053"          "Herpes zoster"            604      1.006         0.9194
4             110659067   "*CFI"  "rs10033900"  "054"          "Herpes simplex"           228      0.8786        0.1811
4             110659067   "*CFI"  "rs10033900"  "070"          "Viral hepatitis"          255      0.9781        0.8057
4             110659067   "*CFI"  "rs10033900"  "070.3"        "Viral hepatitis C"        96       0.9007        0.4759
4             110659067   "*CFI"  "rs10033900"  "078"          "Viral warts & HPV"        874      1.012         0.8246
```

How such test would be run? I'm quite interested, as have never done this before. How much new value does it generate compared to the input summary stats?

**Comment by DSuveges** [comment]
So regarding the overlap, PheWAS brings in quite a large number of associations not covered by the Genetics Portal. The number looks like this (calculated on indirect evidence to account for the possible differences in curating diseases):

```
+------------------------------------+------+                                   
|sources                             |count |
+------------------------------------+------+
|[ot_genetics_portal, phewas_catalog]|43641 |
|[phewas_catalog]                    |428755|
|[ot_genetics_portal]                |838952|
+------------------------------------+------+
```

This is the code:
```python
indirect_df = (
    spark.read.parquet('gs://open-targets-pre-data-releases/21.06.6.1/output/etl/parquet/associationByDatasourceIndirect')
    .filter(
        (col('datasourceId') == 'phewas_catalog')  | (col('datasourceId') == 'ot_genetics_portal')
    )
    .distinct()
    .persist()
)


(
    indirect_df
    .groupBy(['diseaseId', 'targetId'])
    .agg(
        array_sort(collect_set(col('datasourceId'))).alias('sources')
    )
    .groupby('sources')
    .count()
    .show(truncate=False)
 )
```

For me it shows the following consequences:
* PheWAS catalog brings in a surprisingly large number of associations not covered by the Genetics Portal.
* If that's true, it makes sense to consider running such tests on our newer and more complete summary stats.
* Or we should consider if the applied threshold is stringent enough to ensure quality of evidence.

**Comment by ktsirigos** [comment]
Connected to [#1744](https://github.com/opentargets/platform/issues/1744)

**Comment by d0choa** [comment]
The conclusion after discussion with @MayaGhoussaini and others, it's that although a lot of PheWAS catalog signals might not have been identified through GWAS, they would probably not pass modern standards. The fact that some associations are not reproduced by more modern and powered GWAS is concerning.

We will therefore drop PheWAS catalog as a Platform data source. Actions are described in #1899
