### ISSUE TITLE
UniProt data does not seem to be pulled into gene-data correctly

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#176]
@emepyc commented on [Tue May 09 2017](https://github.com/opentargets/data_pipeline/issues/120)

@deniseOme commented on [Mon May 08 2017](https://github.com/opentargets/webapp/issues/125)

On https://www.targetvalidation.org/target/ENSG00000175164, there is no info re. 

Subunit:
Subcellular location:
UniProt Keywords:

However subcellular location and keywords seem to be available in UniProt:
http://www.uniprot.org/uniprot/P16442#subcellular_location

Same behaviour in beta:
https://beta.opentargets.io/target/ENSG00000175164

There is a converse issue in that some index entries ([O76039 on Target CDKL5](https://alpha.targetvalidation.org/target/ENSG00000008086)) have subcellular locations which are not presented on the [Uniprot web interface](https://www.uniprot.org/uniprot/O76039#subcellular_location).

---

@emepyc commented on [Tue May 09 2017](https://github.com/opentargets/webapp/issues/125#issuecomment-300246463)

Probably a data issue: we may not be in sync with latest version of uniprot?
@ckongEbi can you please take a look? It is probably fine to close this issue if that is the case

---

@ckongEbi commented on [Tue May 09 2017](https://github.com/opentargets/webapp/issues/125#issuecomment-300294432)

we can see this information in **17.04_uniprot-data/uniprot-gene/P16442** 
![screen shot 2017-05-09 at 21 32 51](https://cloud.githubusercontent.com/assets/6169985/25871493/94349c14-34ff-11e7-9b23-9b1f62dfdec2.png)

But those section are empty in 17.04_gene-data/genedata/ENSG00000175164
![screen shot 2017-05-09 at 21 33 56](https://cloud.githubusercontent.com/assets/6169985/25871516/ae9bd752-34ff-11e7-9dcb-c063ada683e0.png)

**Comment by MichaelaEBI** [comment]
This issue is still current, I checked the Open Targets and UniProt links provided.

**Comment by AsierGonzalez** [comment]
This information is missing from the gene index and the [API target endpoint](https://platform-api.opentargets.io/v3/platform/private/target/ENSG00000175164). From the 60,564 genes in the 19.11 gene index, 49,232 lack subunits, 44,562 lack subcellular location and 41,466 lack keywords. My guess is that this information is extracted from the [UniProt XML file](
https://storage.cloud.google.com/open-targets-data-releases/19.11/input/annotation-files/uniprot-2019-10-31.xml.gz
). I would need help from @cmalangone to understand how that file is parsed and evaluate whether this is information is missing or if it is being missed.

**Comment by JarrodBaker** [comment]
@d0choa Currently the API does not use the Uniprot `keywords` field (they were extracted during the `data-pipeline` but are thrown away in the ETL). Do we want to include these in the Target step or can I ignore them?

**Comment by d0choa** [comment]
`Keywords` contains ligands which are relevant for us, it would be good to keep them
