### ISSUE TITLE
Review data downloads static file information before 21.09 release

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1760]
Several datasets will change in 21.09. We need to review the blacklisted datasets and probably add descriptions to some of the newly available datasets

**Comment by andrewhercules** [comment]
Once the ETL pipelines have been run, I will ask the back-end team to generate a JSON with the list of datasets and can update the descriptions and list of datasets to be shown and hidden.

[21-04-release-datasets-mapping-file-downloads-page.zip](https://github.com/opentargets/platform/files/7204622/21-04-release-datasets-mapping-file-downloads-page.zip)

**Comment by andrewhercules** [comment]
- Code to generate downloadData.json file with list of all datasets:
`gsutil cat 'gs://open-targets-pre-data-releases/21.09.2/output/etl/*/metadata/*/part-*.json'`
* Note: replace `21.09.2` with the relevant pipeline release version

- Dataset mapping files with names, descriptions, and show/hide status:
https://docs.google.com/spreadsheets/d/1_266iRiVlCRii9cVLJ6__GCQVCw88QypEp6kXz8OcfQ

**Comment by andrewhercules** [comment]
Ticket closed as work completed, merged into `main`, and included in the [21.09.5 `platform-app` release bundle](https://github.com/opentargets/platform-app/releases/tag/21.09.5).
