### ISSUE TITLE
Adapt link out logic to change of name of Target Safety source

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1761]
[#207](https://github.com/opentargets/platform-etl-backend/pull/207) fixes the name of the ToxCast data source in the target safety dataset. 

We have to change the logic that builds the reference to this data source in the front end. It is just a matter of changing `Toxcast` to `ToxCast`[ in the code.](https://github.com/opentargets/platform-app/blob/de9a9bc49147bef4c47081ccd8ada2616fa2772e/src/sections/target/Safety/SafetyTable.js#L32)

**Comment by JarrodBaker** [comment]
The 'HeCaToS' data source has also been removed.
