### ISSUE TITLE
Hide "Experiments (Expression Atlas)" tab in Baseline Expression section

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1766]
Can we please temporarily hide the "Experiments (Expression Atlas)" tab?

The tab will be rescued and reinstated once it has been fixed upstream by the Expression Atlas team.

**Comment by mirandaio** [comment]
Done in this commit https://github.com/opentargets/platform-app/commit/69d2ba347e1765782ff243e5a2da1fcbb6b36f56
