### ISSUE TITLE
Release Pipeline: Missing Mouse Phenotype resource (PIS, POS)

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#1769]
The mouse phenotype resource must be add to PIS.
The recent file under 
gs://otar001-core/MousePhenotypes/

PIS is not managing this resource and this missing file cannot be added to the ES.

Actions to take:
  

- [x] Add mouse phenotype to PIS

- [x] Add mouse phenotype to POS (Similar to SO behaviour, the file is not elaborate using ETL, so the info must be add directly to the ES)

**Comment by JarrodBaker** [comment]
POS expects an input json (unzipped) file in the following location `gs://${GS_DIRECT_FILES}/input/mousePhenotypes/*` for loading in ES and BQ.
