### ISSUE TITLE
Internal server error accessing expression data in 21.09.3

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1770]
ADORA2A expression data produces internal server error

```
query{
  target(ensemblId: "ENSG00000128271") {
    id
    expressions {
      rna {
        level
      }
      protein {
        level
      }
    }
  }
}
```

**Comment by cmalangone** [comment]
The error is bounded to the ES data and the expression index data
In the specific cae is missing the efo_code
{
              "label": "thymus",
              "organs": [],
              "anatomical_systems": [],
              "rna": {
                "value": 0,
...
Checking the expression step (ETL)

**Comment by d0choa** [comment]
I suspect this connects again to the prehistoric #393

**Comment by cmalangone** [comment]
These tissues are missing
  "cartilage",
  "choroid plexus",
  "dorsal raphe",
  "sole of foot",
  "thymus",

Fix with a PR to the code
