### ISSUE TITLE
Include 'general' as a possible value in the target safety dosing field

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1774]
### Context
When @JarrodBaker parsed the existing target safety data, I asked him to leave the field `effects.dosing` blank whenever the data source reported this field to be `General`. My rationale was that the term general implies lack of knowledge, rather than an inclusive term meaning that the effect was seen at acute and chronic doses.

This does not look right in the UI, as there is no logic implemented when this term is null: 
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/a1babe09-5e68-4ccc-93fe-92564181631c)

### Solution
We want to bring back the `general` value to `effects.dosing` to avoid having nulls so that the possible values for this field are: 'chronic', 'acute', 'general'.

This should currently happen in the ETL as both `ae.json` and `sr.json` include this granularity. I believe [this is the line of code](https://github.com/opentargets/platform-etl-backend/blob/b9a636e933ca5130c25e8a44b7f18142b5f49d07/src/main/scala/io/opentargets/etl/backend/target/Safety.scala#L92) that needs to be changed.

**Comment by ireneisdoomed** [comment]
There are 81 diseases (1%) that are not present in the disease to phenotype dataset we produce as compared to 21.06. 

This dataset is built by establishing a  relationship of a cross referenced OMIM ID in the disease index with the phenotypes dataset from HPO.
I can confirm that this is mostly coming from EFO, as for 76 out the 81 diseases these **OMIM codes are not present** in the ontology in the first place.

I'm investigating the other 5.

**Comment by JarrodBaker** [comment]
Is your comment @ireneisdoomed related to this ticket or is it separate? If it's something else please create a new ticket. (note there are now templates available in ZenHub to give tickets some more structure :))

**Comment by ireneisdoomed** [comment]
That was an update for [#1775](https://github.com/opentargets/platform/issues/1775). Apologies for the confusion and thank you so much for sorting this one out.
