### ISSUE TITLE
Investigate missing phenotypes data shown in "Clinical Signs & Symptoms" detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1775]
In the first `21.09` release pipeline run, we lost some phenotypes data that is shown in the Clinical Signs & Symptoms 
section on the disease/phenotype profile page.

For example, for [colorectal neoplasm (EFO_0004142)](https://platform.opentargets.org/disease/EFO_0004142), the production version of the Platform has a data table with 7 rows.

![Screenshot 2021-09-27 at 11 58 32](https://user-images.githubusercontent.com/7490258/134895963-8cb1623e-6843-48d5-8f2b-e2f50f761842.png)

![Screenshot 2021-09-27 at 11 59 49](https://user-images.githubusercontent.com/7490258/134896127-21685a8d-ebb7-4f69-b5e0-610ced7f232d.png)

However, the Clinical Signs & Symptoms section on the [colorectal neoplasm (EFO_0004142) in `main`](https://main--platform-app.netlify.app/disease/EFO_0004142) does not have any data.

![Screenshot 2021-09-27 at 11 58 21](https://user-images.githubusercontent.com/7490258/134895989-44d310b3-f36c-424c-a5fe-3df1098fed51.png)

I also noticed the same issue with melanoma (EFO_0000756), comparing [production](https://platform.opentargets.org/disease/EFO_0000756) versus [`main`](https://main--platform-app.netlify.app/disease/EFO_0000756). And according to analysis from @ireneisdoomed, we lost phenotypes data for 81 diseases when comparing the `21.09` release run with the data from `21.06`.

Based on conversations with @d0choa, we wonder if the issue has been caused by missing OMIM references and the work done by EFO on the cancer branch. 

@cmalangone can you please investigate once we have officially released `21.09`?

**Comment by ireneisdoomed** [comment]
There are 81 diseases (1%) that are not present in the disease to phenotype dataset we produce as compared to 21.06.

This dataset is built by establishing a relationship of a cross referenced OMIM ID in the disease index with the phenotypes dataset from HPO.
I can confirm that this is mostly coming from EFO, as for 76 out the 81 diseases these OMIM codes are not present in the ontology in the first place.

I'm investigating the other 5.

**Comment by ktsirigos** [comment]
is this resolved? Still 'main' does not return data.

**Comment by andrewhercules** [comment]
No, not yet. It will be resolved in the `21.11` release. It is only a small percentage that are impacted by the upstream changes.

**Comment by andrewhercules** [comment]
@ireneisdoomed, I'm pushing this to `22.02`.

Do we need to ask EFO to include the relevant OMIM IDs so we can rescue the data and the links to the HPO dataset?

**Comment by ireneisdoomed** [comment]
@andrewhercules Thank you for reminding me.

I've opened [a ticket](https://github.com/EBISPOT/efo/issues/1368) for them to investigate.

**Comment by JarrodBaker** [comment]
Can this ticket be closed @ireneisdoomed, @d0choa ?
