### ISSUE TITLE
Change `results` and `unfiltered` dataset names in ETL

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1777]
In the ETL pipeline, our processing of the openFDA data results in two datasets — `results` and `unfiltered` — however, these names do not provide enough information to potential users about what the datasets contain.

Can we please change the name of these datasets?

`results` --> `significantAdverseEvents`
`unfiltered` --> `adverseEvents`

**Comment by cmalangone** [comment]
the change is done in the ETL and POS
https://github.com/opentargets/platform-output-support/pull/6
