### ISSUE TITLE
Investigating overlap of Humsavar database and evidence sourced from uniprot.

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1779]
The humsavar dataset can be downloaded from Unirpot: [https://www.uniprot.org/docs/humsavar](https://www.uniprot.org/docs/humsavar)

The dataset highly similar to the disease/target evidence dataset we are sourcing from Uniprot. The question is how much overlap can we found between the two, and explore if there's a point from add a new source, or given sufficiently large overlap we can use humsavar as a data source (like clinvar).

Humsavar publication [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0210475).

**Comment by d0choa** [comment]
I don't think the link to the publication is correct.

**Comment by DSuveges** [comment]
# HUMSAVAR


**Exploring the HUMSAVAR dataset**

* Getting basic stats: evidence count, association count, target count, disease count
* Comparing with the existing Uniprot evidence set: overlap by association.

#### Acquiring dataset:

* Downloading humsavar from `https://www.uniprot.org/docs/humsavar.txt` load as pyspark dataframe.
* Downloading the original uniprot evidence set from: 

### Basic stats

* Number of evidence: 80,129
* Number of evidence with no uniprot identifier: 0
* Number of evidence with no genes: 27 (discrepancy between gene and uniprot annotation)

* Number of evidence with no disease annotation: 41,354 (with 11,855 genes)
* Number of evidence disease annotation: 38775

* Number of associations: 6318. genes: 4190, diseases: 4529
* Number of associations with MIM : 4002. genes: 2914, diseases: 3843

## Humsavar vs uniprot evidence

#### Acquiring dataset:

Dataset downloaded from `gs://otar011-uniprot/cttv011-11-10-2021.json.gz`

### Comparison 


#### Approach 1:

To compare the two datasets, I only considered associations. The humsavar dataset was filtered for entries with OMIM identifiers, I made no attempt to map the dieseases to EFO. The uniprot evidence set was joined with humsavar dataset by `omim` disease identifier AND `uniprot` target identifiers (the uniprot evidence set has OMIM identifier in the `diseaseFromSourceId` field).

Out of the 4002 unique association from humsavar 3815 was found in the Uniprot dataset. It suggests humsavar is a subset of the uniprot dataset. The 187 missing associations are comprised of 123 distinct diseases (from which 3 was not found in Uniprot dataset), and 182 distinct targets (from which 159 was not found in the uniprot dataset.)

**Conclusion**:

I think the humsavar dataset is likely a subset of the curated evidence set curated by Uniprot due to the large overlap. However some of the evidence in the humsavar dataset has no disease annotation at all, indicating it might be generated automatically by parsing Uniprot entires.

#### Approach 2

Given one third of the diseases have no OMIM identifiers, we should try to map those diseases to EFO then try to join with the uniprot evidence set.

1. Extract evidence from humsavar dataset where no OMIM identifiers availabe.
2. Generate associations.
3. Map diseases to EFO using OnToma.
4. Join with Uniprot evidence based on uniprot id and EFO id. 

**Conclusion**:

If exclude all associations where OMIM identifiers available we get 2193 unique disease/target pairs of 626 unique diseases. Of which 1567 (of 93 diseases) could be mapped. The overlap between this mapped dataset and the Uniprot evidence set was quite poor:

| source   |   count |
|:---------|--------:|
| humsavar |    1557 |
| both     |      10 |
| uniprot  |    7386 |

When checking the discrepancies, I saw these protein sequence altering mutations were identified in cancer samples, so we cannot really trust as true disease/target evidence.

### Conclusion

I think the humsavar dataset is automatically generated based on Uniprot entries and does not have enough value to consider as an additional disease/target evidence source on top of the existing manually curated Uniprot dataset.

Analysis notebook [here](https://github.com/DSuveges/random_notebooks/blob/master/issue-1779-exploring_humsavar/Humsavar_test.ipynb)

**Comment by d0choa** [comment]
Thanks @DSuveges. This answers 2 of my questions:
a) is humsavar an alternative name for our uniprot feed
b) does humsavar contain value by itself.
No further actions required based on your analysis
