### ISSUE TITLE
inconsistent response for targets without mouse phenotypes

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#178]
@emepyc commented on [Fri Dec 01 2017](https://github.com/opentargets/data_pipeline/issues/221)

In the target index, phenotypes are given in an array. But targets without a phenotype are reporting an empty object instead of an empty array:

https://platform-api.opentargets.io/v3/platform/private/target/ENSG00000171862
https://platform-api.opentargets.io/v3/platform/private/target/ENSG00000124659

**Comment by d0choa** [comment]
No work is expected in current API to address this issue
