### ISSUE TITLE
Mouse phenotypes/PhenoDigm review and actions for 21.09

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1788]
### Summary for the release
- [x] Write and edit the summary, first iteration
- [x] Mention additional generated links

### Issue with a reduced number of genes
- [x] Investigate and find out the reason
- [x] State the decision in this ticket

### Issue with flat files downloads
- [x] Check the issue in production
- [x] Create the ticket
- [x] Report in the release channel

**Comment by tskir** [comment]
#### A note on the reduction of the number of reported mouse phenotypes

This was discussed on the meeting 2021-09-30 with @ireneisdoomed and @DSuveges. Posting the summary here for provenance purposes.

Previously, mouse phenotypes were processed from the flat files hosted on the MGI website. The flat files in question include all mouse phenotypes, even those which don't have any mapping to a human phenotype or disease. An example of such a phenotype is something like a “short tail”, which doesn't have any conceivable alternative in a human body.

Now both the PhenoDigm evidence strings and the mouse phenotypes dataset are being generated from IPMC SOLR API. Because it is based on PhenoDigm results, it only includes the phenotypes which are mapped to human phenotypes/diseases, leading to the observed decrease in the number of entries in the mousePhenotypes dataset.

During the meeting we decided that:
1. From the Platform point of view, it _makes sense_ to to only process/display only those mouse phenotypes which can be ultimately linked to human phenotypes/diseases, because it aligns with our focus on human clinical genetics.
2. Additionally, from the technical point of view, processing all phenotypes would involve parsing additional flat files and needlessly complicating the existing PhenoDigm pipeline.

The decisions had been forwarded to Helena & Andrew and are now displayed in the release notes: https://blog.opentargets.org/open-targets-platform-21-09-release/#mouse-genome-informatics

**Comment by d0choa** [comment]
Let's discuss this. I think it goes against the original intention of the mouse phenotypes widget.

**Comment by tskir** [comment]
Sure, we can do this during the next stand-up meeting.

I'm going to close this issue, because all actions have been done and the change has been implemented & the release notes processed. But we can open a follow-up issue(s) depending on what we decide in our discussions.
