### ISSUE TITLE
Create generic ETL throughput step

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1791]
As a developer I want to generate ETL metadata for raw inputs which are used directly in the Open Targets Platform because the metadata files are used by the FE team to dynamically generate content. 

## Background

The ETL generates a set of metadata with each step that it runs including information about output format, location and data structure. Some data is not generated by the ETL and therefore do not have any associated metadata. This means that both POS and the FE need special logic to deal with this situation. 

Relates to opentargets/platform#1790 where there was a discussion of data outside of the ETL not being handled correctly downstream.

## Tasks

- [ ] Update the ETL with a generic step (`identity`) which takes an input file, and writes it to the common output area along with the metadata in the same way as other steps. 

## Acceptance tests

1. When I run step `identity` on the ETL it generates an output file in the configured format along with the metadata in the same way as other steps which perform manipulations.

**Comment by mkarmona** [comment]
@JarrodBaker, I would call it `targetIdentity` as the dataset must be filtered by our target dataset. There are many genes coming from DNA scaffolding we don't want to include in the output because it is just polluting and making the dataset noisy.

**Comment by JarrodBaker** [comment]
Do we want to do any further processing on it though? The dataset exists, but the only way it is brought into the platform is by a query from a target to MP in the API. Any thoughts @d0choa?

**Comment by mkarmona** [comment]
@JarrodBaker although the query is clear and it will bring just the allowed ones offering the dataset as outputs bring extra implications. The main one is the dataset must no contain unnecessary targets out of our index space.

**Comment by JarrodBaker** [comment]
In that case we need a dedicated mouse phenotypes step to contain that logic. Do we still want the feature in this ticket @mkarmona ? The ability to pipe through inputs and generate the metadata? I'd be inclined to implement a MP step and put this issue in the icebox until we actually need the functionality.

**Comment by JarrodBaker** [comment]
Resolved through opentargets/platform#1803
