### ISSUE TITLE
Urban et al is missing the link out

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1797]
**Describe the bug**
Safety records from `Urban et al (2012)` are not linking to the source.

**Expected behaviour**
We want all safety datasources to link out to the primary resource. We must add a reference for Urban et al records in the FE logic similarly as we do with ToxCast.
Reference: `https://doi.org/10.1002/9781118098141.ch2`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://platform.opentargets.org/target/ENSG00000142208
2. Scroll down to the Safety table
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/6eb3c8f0-0655-4be5-9019-de157d13c4d3)

**Additional context**
Whenever the reference is a publication (Lamore, Bowes, Lynch), these are stored in the `literature` field in the data.
When the reference is of a different nature (ToxCast, Urban et al), the link out is built in the FE.
There is not any logic to handle Urban et al cases.

**Comment by andrewhercules** [comment]
@ireneisdoomed if you anticipate adding new datasources for Safety information, we should create a different API field that can contain non-publication references. At a certain point, the front-end will contain too much logic and extra information that is not available for programmatic users querying the API or using BigQuery or the data downloads. 

I have assigned to `21.11` and we can adjust in the next release.

**Comment by LucaFumis** [comment]
I'd added a fix for the link a while back - if needed we can merge it in:
https://github.com/opentargets/platform-app/commit/7be516518633c25483282800e56e52b11cc22335

**Comment by ireneisdoomed** [comment]
Links will be exposed in the API, @LucaFumis. Thanks!

I'll create the ticket for you as soon as we run the pipeline and the links are available in the endpoint.
