### ISSUE TITLE
Issues with flat files downloads for the mouse phenotypes section

### ISSUE THREAD

**Issue by tskir** [opentargets/platform#1801]
To reproduce: go to https://platform.opentargets.org/target/ENSG00000001626, click on “Mouse Phenotypes”, then click on “Download table as...” (JSON/CSV/TSV). The downloaded flat files will have the following issues:

### CSV and TSV
Contain `[object Object]` in place of the actual values. For TSV:
```
mouseGene	phenotype	category	allelicComposition
Cftr	abnormal hepatocyte morphology	[object Object]	
Cftr	increased susceptibility to infection	[object Object]	
Cftr	cachexia	[object Object]	
```

For CSV:
```
"mouseGene","phenotype","category","allelicComposition"
"Cftr","abnormal hepatocyte morphology","[object Object]",""
"Cftr","increased susceptibility to infection","[object Object]",""
"Cftr","cachexia","[object Object]",""
```

### JSON
Contains a technical field which should not be present (`"__typename": "ModelPhenotypeClasses"`), and also the `allelicComposition` field is empty.

```json
  {
    "mouseGene": "Cftr",
    "phenotype": "abnormal hepatocyte morphology",
    "category": [
      {
        "__typename": "ModelPhenotypeClasses",
        "id": "MP:0005370",
        "label": "liver/biliary system phenotype"
      }
    ],
    "allelicComposition": ""
  }
```

**Comment by andrewhercules** [comment]
Ticket closed as bug fixed and merged into `main`
