### ISSUE TITLE
Recover evidence with an invalid disease by using xrefs

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1807]
As a **developer** I want **to recover the evidence with invalid diseases which have a valid cross-reference to a term in EFO.**

## Background

In the process of analysing the invalid diseases with the most evidence, I have realised that we are not picking up the evidence with a disease ID not included in EFO but for which there is a disease ID with a cross-reference to that missing ID.

Take [MONDO_0001708](http://purl.obolibrary.org/obo/MONDO_0001708) as an example. This term has not been imported to EFO and hence there are 200 invalid evidence annotated with it.
But EFO currently has [DOID_13406](http://purl.obolibrary.org/obo/DOID_13406), with a reference to the MONDO ID. We could be recovering this evidence if we corrected the mapping to the DOID ID.

Also, a part of the data team work is to QC these cases and ask EFO to add any missing cross-references we might find. And currently this work does not result in any changes for the already mapped evidence we get from the data providers.

## Discussion
There are multiple ways that we could post-process such invalid evidence to point them to the right EFO ID. Some that I can think of:

1. Correct `diseaseFromSourceMappedId` by querying Ontoma with the disease label or ID. Currently **Ontoma does look at the cross-references** to find a proper mapping.
```
otmap.find_term('MONDO_0001708', code=True)
INFO     - ontoma.interface - Processed: MONDO_0001708 → [OnTomaResult(query='MONDO_0001708', id_normalised='DOID:13406', id_ot_schema='DOID_13406', id_full_uri='http://purl.obolibrary.org/obo/DOID_13406', label='pulmonary sarcoidosis')]
```

2. Implement a similar step in the ETL by using the `dbXrefs` field of the disease index.

3. Report these cases back to our data providers to have their evidence pointing to an EFO ID.

What do you think? I am happy to discuss how relevant you think this ticket is and how we can best tackle it.

**Comment by d0choa** [comment]
If I understand this correctly, `diseaseFromSourceMappedId` is incorrect in the sense that ID is not in EFO, therefore is not a true mapped id.

I believe any solution should come back to the source of that decision. Whether it was ontoma assigning it or annotation from a provider. These situations also emerge when the ontology updates and annotations get outdated.

**Comment by ireneisdoomed** [comment]
Yes, that is the case.
OnToma, to the best of my knowledge, does not return anything outside EFO. So if I ask EFO to add a cross-reference or synonym, the tool will pick it up. On the other hand, we don't process submitted evidence since it is already mapped. That's what I wanted to discuss in this ticket.

You are in favour of #3, then.

**Comment by d0choa** [comment]
Let's stick to #3, I think all the alternative plans add a degree of uncertainty in the mapping process. Xrefs are not always reliable
