### ISSUE TITLE
Analyse Eric Fauman's target/trait GS

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1818]
### Context
Eric Fauman has shared with us the results of a curation process where he has manually built a set of  ≈ 3500 gene/trait pairs based on GWAS signals.

### Analysis
The value of such dataset has been assessed to determine if we can make use of it:
#### 1. as a source for gene/disease evidence.
(Point #2 and #3 in the Jupyter file)
When comparing it to the associations we get from ClinVar, only 2% of Eric's gene/trait pairs are present in ClinVar.
When doing the same analysis with the whole evidence set, the percentage of overlapping associations raises to 29%.

However, I think that the novelty associations are not compatible with those of the Platform. Almost all of the trait IDs that are not covered in the Platform refer to metabolites (HMDB terms). 

Therefore, **I don't see a value in including it as an evidence source.**

#### 2. as an extension to the current gold standard used to build the locus2gene model.
(Point #1 in the Jupyter file)
When comparing it to our current GS, only 9% of Eric's GS was covered in ours.

#### 3. as a benchmark for the current L2G predictions.
(Point #4 in the Jupyter file)
When comparing whether the causal gene predicted by the L2G algorithm corresponds to the same causal gene annotated by Eric, I have found that 18% (674 / 3665) of Eric's gene/trait pairs overlap with those inferred from L2G. The overlap increases to ≈ 45% (674/1481) if the metabolite related traits are filtered out of Eric's GS.

### Actions
It feels sensible to study the incorporation of this dataset to the Gold Standard. I will comment on my results with @MayaGhoussaini to discuss further actions.

### Notes
- The analysis was done on a Jupyter which can be found here: https://github.com/ireneisdoomed/random_notebooks/blob/main/eric_gs/Analysis.ipynb
- Please note that all of these reports include a preliminary step where the disease ontology is expanded for the dataset that is being compared against Eric's GS. This is done to address differences in ontology granularities.
- Eric's GS cannot be shared as this data is pending publication.

**Comment by ireneisdoomed** [comment]
@MayaGhoussaini, @Jeremy37, @xyg123, @mohdkarim, and I had a discussion yesterday to discuss the findings. There are the follow-up questions that came up:

1. Eric Fauman's tweets form part of the gold standard in use by the L2G pipeline. We should expect to see all of these being present in his newer GS. Is this the case? **No. 105 out of the 385 fall out from the newer.**

This is how the gene/trait pairs overlap:

![image](https://user-images.githubusercontent.com/45119610/143609591-689a74b7-dd16-437f-ba6b-3878d690557f.png)

(Point 1.2 on the Jupyter)

2. When taking a look at how well L2G predictions perform against Eric's new GS, it is interesting to see what is the overlap at different scores. We should expect to see a less pronounced discrepancy at higher scores. Is this the case? **Yes.**

This is how the intersection between the associations in the GS and the L2G are distributed across the L2G score.
![image](https://user-images.githubusercontent.com/45119610/143615992-0353f9e0-19fb-439b-aeea-264abf27182a.png)

To give a better idea:
![image](https://user-images.githubusercontent.com/45119610/143616031-432db09b-2702-4237-ae5d-ad9f367a2ee9.png)

(Point 4.2 on the Jupyter)

**Comment by d0choa** [comment]
@ireneisdoomed please let me know if you need help with potential follow ups. I'm closing the exploration work
