### ISSUE TITLE
Investigate differences in `evidenceCount` field in associations datasets

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1819]
### Describe the bug

Based on a [Community post](https://community.opentargets.org/t/difference-between-direct-and-indirect-links-in-data-downloads/376), it appears that the `evidenceCount` values in our `associationByDatasource` and `associationByDatatype` datasets are incorrect. Both the `direct` and `indirect` versions are affected by this issue.

### Observed behaviour

When parsing and querying the `associationByDatasourceDirect` and `associationByDatasourceIndirect` datasets, the association for CFTR (ENSG00000001626) and cystic fibrosis (Orphanet_586), returns an evidence count of `2188` for the `eva` datasource. However, on the [CFTR and cystic fibrosis evidence page](https://platform.opentargets.org/evidence/ENSG00000001626/Orphanet_586), there are `2409` evidence strings from `eva`. And so `221` records are missing from the `evidenceCount` field.

When parsing and querying the `associationByDatatypeDirect` and `associationByDatatypeIndirect` datasets, the same association returns an evidence count of `2289` for the `genetic_associations` datatype. However, this should be `2510`. And so it appears the same 221 `eva` records are also missing from the `evidenceCount` field in the datatype datasets.

### Expected behaviour

The `evidenceCount` values for a given datasource or datatype should match what is displayed in the web interface. 

### Additional context**

The CFTR and cystic fibrosis association is noteworthy because cystic fibrosis does not have any child terms and so we should expect that the direct and indirect counts are the same.

**Comment by mkarmona** [comment]
the thing is, there are pieces of evidence with a score of 0. But when the evidence is prepared for the associations they are filtered out to not waste resources.

```scala
    val dfs = IoHelpers.readFrom(mappedInputs)
    val evidences = dfs("evidences").data
      .selectExpr(evidenceColumns: _*)
      .where(col(evScore) > 0D)
```

In the case of EVA, it contains mutations that are not pathogenic or the clinical significance is unknown so that implies score 0
```scala
@ evs.filter($"sourceId" === "eva" and $"targetId" === "ENSG00000001626" and $"diseaseId" === "Orphanet_586").count 
res11: Long = 2409L

@ evs.filter($"sourceId" === "eva" and $"targetId" === "ENSG00000001626" and $"diseaseId" === "Orphanet_586" and $"score" > 0).count 
res13: Long = 2188L

evs.filter($"sourceId" === "eva" and $"targetId" === "ENSG00000001626" and $"diseaseId" === "Orphanet_586" and $"score" === 0).selectExpr("targetId", "diseaseId", "score", "explode(clinicalSignificances) as clinicalSig").show 
+---------------+------------+-----+------------+
|       targetId|   diseaseId|score| clinicalSig|
+---------------+------------+-----+------------+
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
|ENSG00000001626|Orphanet_586|  0.0|not provided|
+---------------+------------+-----+------------+
only showing top 20 rows
```
and giving closer to which clinical significances are the offending ones
```scala
@ 
evs.filter($"sourceId" === "eva" and $"targetId" === "ENSG00000001626" and $"diseaseId" === "Orphanet_586" and $"score" === 0).selectExpr("targetId", "diseaseId", "score", "explode(clinicalSignificances) as clinicalSig").select("clinicalSig").distinct.show 
+------------+
| clinicalSig|
+------------+
|      benign|
|not provided|
+------------+
```

therefore, the counts sound correct to me.
