### ISSUE TITLE
Broken external links in the "Mechanism of Action" column in evidence page drugs tables

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#182]
@andrewhercules commented on [Wed Jun 20 2018](https://github.com/opentargets/data_pipeline/issues/288)

@andrewhercules commented on [Mon Jun 04 2018](https://github.com/opentargets/webapp/issues/286)

### Observed behaviour
In the Mechanism of Action column in the known drugs table, the external links do not work if there are both publications and non-publications links. 

For example, on the [CACNA1B in asthma evidence page](https://www.targetvalidation.org/evidence/ENSG00000148408/EFO_0000270?view=sec:known_drug), the `ISBN` link is `http://europepmc.org/abstract/MED/18299583,http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/022544s008lbl.pdf,http://www.isbnsearch.org/isbn/0121844536,http://en.wikipedia.org/wiki/Gabapentin`, a comma-separated list of all the external links that the API returns. Instead, it should just be `http://www.isbnsearch.org/isbn/0121844536`. See below for a screenshot of the issue.

![screen shot 2018-06-04 at 11 33 10](https://user-images.githubusercontent.com/7490258/40913534-cbb06526-67ec-11e8-9698-af9dbf545880.png)

The same issue can be found on other evidence pages including [BRAF and lung carcinoma](https://www.targetvalidation.org/evidence/ENSG00000157764/EFO_0001071?view=sec:known_drug) and [KDR and liver disease](https://www.targetvalidation.org/evidence/ENSG00000128052/EFO_0001421?view=sec:known_drug). The issue can also be found on target profile pages (e.g. [KCNQ3](https://www.targetvalidation.org/target/ENSG00000184156)) and disease profile pages (e.g. [liver disease](https://www.targetvalidation.org/disease/EFO_0001421)).

### Expected behaviour
The links should be properly formatted so that only one link appears per external link reference. So taking the above example of [CACNA1B in asthma evidence page](https://www.targetvalidation.org/evidence/ENSG00000148408/EFO_0000270?view=sec:known_drug), in the Mechanism of Action column, there should be the following links:

[1 publication](http://europepmc.org/abstract/MED/18299583)
[FDA](http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/022544s008lbl.pdf)
[ISBN](http://www.isbnsearch.org/isbn/0121844536)
[Wikipedia](http://en.wikipedia.org/wiki/Gabapentin)

### Environment
* Version: 3.6.11
* Browser: Chrome, Firefox

---

@LucaFumis commented on [Mon Jun 04 2018](https://github.com/opentargets/webapp/issues/286#issuecomment-394332663)

This needs to be fixed at data level / API first. Splitting the string on commas is not a big problem but must have corresponding `nice_name`s. 
Ideally we have *one link only* per `url` array item.

---

@andrewhercules commented on [Wed Jun 20 2018](https://github.com/opentargets/webapp/issues/286#issuecomment-398766582)

Thanks @LucaFumis. I'll close the issue here and copy it to the `data_pipeline` repo.

---

@MichaelaEBI commented on [Mon Jul 16 2018](https://github.com/opentargets/data_pipeline/issues/288#issuecomment-405261783)

I looked into this and it looks like the data is not separated properly in the CHEMBL evidence file. In 'evidence' - 'target2drug' - 'urls' there are usually three types of links:
```
  "evidence": {
    "target2drug": {
      "urls": [
        {
          "nice_name": "ChEMBL molecule information",
          "url": "https:\/\/www.ebi.ac.uk\/chembl\/compound\/inspect\/CHEMBL98"
        },
        {
          "nice_name": "ChEMBL target information",
          "url": "https:\/\/www.ebi.ac.uk\/chembl\/target\/inspect\/CHEMBL325"
        },
        {
          "nice_name": "DailyMed",
          "url": "http:\/\/dailymed.nlm.nih.gov\/dailymed\/lookup.cfm?setid=cd86ee78-2781-468b-930c-3c4677bcc092#section-13"
        }
      ],
```
Looking at the data, it seems that whenever there is more than one link for the third category (i.e., not ChEMBL target or molecule information), then they have a random nice_name and all links are concatenated:
```
  "evidence": {
    "target2drug": {
      "urls": [
        {
          "nice_name": "ChEMBL molecule information",
          "url": "https:\/\/www.ebi.ac.uk\/chembl\/compound\/inspect\/CHEMBL940"
        },
        {
          "url": "https:\/\/www.ebi.ac.uk\/chembl\/target\/inspect\/CHEMBL2363032",
          "nice_name": "ChEMBL target information"
        },
        {
          "nice_name": "ISBN",
          "url": "http:\/\/europepmc.org\/abstract\/MED\/18299583,http:\/\/www.accessdata.fda.gov\/drugsatfda_docs\/label\/2012\/022544s008lbl.pdf,http:\/\/www.isbnsearch.org\/isbn\/0121844536,http:\/\/en.wikipedia.org\/wiki\/Gabapentin"
        }
      ],
```

I will check with Paula from ChEMBL to see whether they can fix this for 18.08. @ckongEbi and myself will follow up on this.

---

@MichaelaEBI commented on [Tue Jul 17 2018](https://github.com/opentargets/data_pipeline/issues/288#issuecomment-405643635)

Paula is looking into it and will change it so that we get nice_name - URL pairs for external links.

---

@afaulconbridge commented on [Thu Sep 20 2018](https://github.com/opentargets/data_pipeline/issues/288#issuecomment-423093257)

If this is "fixed" can it be closed @MichaelaEBI ?

**Comment by MichaelaEBI** [comment]
Yes, as far as I can see it has been fixed since 18.08.
