### ISSUE TITLE
Compress static files using brotli compression

### ISSUE THREAD

**Issue by mirandaio** [opentargets/platform#1824]
As a user I want to download the static assets of the platform app compressed using the brotli compression algorithm.

## Background

We are taking several measures to improve the loading performance of the Platform web app. One way is to use a compression algorithm that produces smaller file sizes. Here is a comparison of our JavaScript and CSS static assets using `gzip` and `brotli` compression:

| File | gzip (kB) | brotli (kB) | Reduction (%) |
| --- | ----------|---------|-----------------|
| main.368b8ca3.chunk.js | 181 | 113 | 37.57 |
| 2.56d48644.chunk.js | 552 | 423 | 23.37|
|3.b9a680db.chunk.js | 907 | 675 | 25.58|
|main.d58c781b.chunk.css | 1.7 | 0.69 | 59.41|
|2.261e08bd.chunk.css | 22.5 | 16.5 | 26.67|
|3.881a34dc.chunk.css | 18.2 | 14.3 | 21.43|

## Tasks

- [ ] Configure nginx to serve static assets using brotli compression

## Acceptance tests

1. When I go to https://platform.opentargets.org the size of the assets being downloaded are similar in size to the assets downloaded when visiting https://platform-app.netlify.app (since Netlify already uses brotli compression).
2. When I check in developer tools that the static assets have the `Content-Encoding` value of the response header set to `br`.

**Comment by mbdebian** [comment]
This will be in production in the next release.

**Comment by mirandaio** [comment]
Looks good, the static files are compressed correctly with brotli compression 👍
