### ISSUE TITLE
Integrate HPO from tag rather than master

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#1828]
For the sake of reproducibility in linking diseases to phenotypes, it would be helpful if platform-input-support was importing a static HPO version rather than pulling from master as in https://github.com/opentargets/platform-input-support/blob/e8385d8723b647dc77ddeac92665dfbbdedff828/config.yaml#L104-L105:

```yaml
    hpo:
      uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
```

The [obophenotype/human-phenotype-ontology](https://github.com/obophenotype/human-phenotype-ontology) project is cutting regular releases so is there any reason not to link against those [tags](https://github.com/obophenotype/human-phenotype-ontology/tags) instead?  That config property could be rewritten as:

```yaml
    hpo:
      uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2021-10-10/hp.owl
```

**Comment by d0choa** [comment]
@cmalangone I'm assuming this is a very quick fix

**Comment by cmalangone** [comment]
Hi @d0choa: this suggestion is already implemented in the new PIS refactoring.
Between today and tomorrow we aim to have a new PIS version based on yapsy plugin.

**Comment by ktsirigos** [comment]
can I close then or should we wait?

**Comment by cmalangone** [comment]
@ktsirigos can we wait please?

**Comment by ktsirigos** [comment]
absolutely! Whenever you are ready :)

**Comment by cmalangone** [comment]
Please find the change requested here:
https://github.com/opentargets/platform-input-support/blob/master/config.yaml#L20
