### ISSUE TITLE
Terraform provisioner for custom FE config file

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#1837]
As a developer I want to include the FE customisation config file as an external resource because this action will make readable and efficient the process of deployment.

## Background
FE provides a specific customisation of the webapp configuration file. (Eg. background colour and components).
Currently terraform hosts the configuration file in the main file as a list of attributes/values.

## Tasks

- [x] FE: #1838
- [x] BE/FE: to decide the location where to store the file
- [x] BE: to change terraform to host the new info (provisioner)

## Acceptance tests
When Terraform script is deployed the webapp must work with or without the customisation info.

**Comment by mbdebian** [comment]
Implemented as javascript configuration profiles under '/profiles' in the web application public folder.
The terraform provisioner has already been extended for supporting this mechanism in Open Targets Platform and Partner Preview deployments.
