### ISSUE TITLE
Generate JSON config file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1838]
Details TBC pending further conversations with back-end team

**Comment by mbdebian** [comment]
This has already been implemented as a javascript config file within folder '/profiles' in the public folder of the application.
Terraform provisioner has already been extended for supporting this feature in Open Targets Platform and Partner Preview deployments.

@andrewhercules , are we going to use this approach for Genetics Portal as well?

**Comment by andrewhercules** [comment]
That's great - thank you @mbdebian! 👍 

Yes, we will take the same approach with the Genetics Portal — I'll add to the `genetics-app` refactor epic https://github.com/opentargets/genetics/issues/511

**Comment by mbdebian** [comment]
I'll close this issue then, thanks @andrewhercules !!!
