### ISSUE TITLE
Update ProtVista viewer component to latest version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1839]
Currently, the `platform-app` uses `"protvista-uniprot": "^2.7.5",`. However, the `npm` package was [recently updated](https://www.npmjs.com/package/protvista-uniprot). Can we please update to the latest version of the ProtVista viewer package?

**Comment by d0choa** [comment]
I believe the 3D structures don't load in Safari. WebGL issues? Could you try to reproduce @LucaFumis?
