### ISSUE TITLE
Debug FAERS Target pipeline

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1844]
**Describe the bug**
I have noticed two potential bugs in the output of the FAERS Target pipeline:
1. The significant target adverse reactions is not exactly a subset of all adverse target reactions.
2. There are cases where the number of linked targets for a drug is greater than the number of actual targets listing an AE inferred from that same drug.

**Observed behaviour**
1. There are significant target/event pairs that do not appear in the unfiltered dataset. **Note:** This does not occur with drugs AEs.
```
>>> significantAdverseTargetReactions.select('event', 'chembl_id', 'targetId', 'llr', 'critval').join(
    adverseTargetReactions.withColumnRenamed('reaction_reactionmeddrapt', 'event').select('event', 'chembl_id', 'targetId').distinct(),
    on=['event', 'chembl_id', 'targetId'], how='left_anti'
).show(3)
+-------------------+------------+---------------+------------------+-----------------+
|              event|   chembl_id|       targetId|               llr|          critval|
+-------------------+------------+---------------+------------------+-----------------+
|acute kidney injury|CHEMBL289480|ENSG00000010322|195.84136964049594|8.493369839319712|
|           delirium|CHEMBL289480|ENSG00000010322| 15.25061893917973|8.493369839319712|
|            prurigo|CHEMBL289480|ENSG00000010322|12.377978259030897|8.493369839319712|
+-------------------+------------+---------------+------------------+-----------------+

>>> adverseTargetReactions.filter(F.col('reaction_reactionmeddrapt') == 'acute kidney injury').filter(F.col('targetId') == 'ENSG00000010322').count()
0
```

2. `CHEMBL3622533` has 14 linked targets. The FAERS analysis only lists 1 target related to `CHEMBL3622533`.
```
>>> print(drug_idx.filter(F.col('chembl_id') == 'CHEMBL3622533').show())
+-------------+--------------------+----+
|    chembl_id|             targets|size|
+-------------+--------------------+----+
|CHEMBL3622533|[ENSG00000094631,...|  14|
+-------------+--------------------+----+

>>> print(adverseTargetReactions_2.filter(F.col('chembl_id') == 'CHEMBL3622533').show())
+-------------+-----------------+----+
|    chembl_id|          targets|size|
+-------------+-----------------+----+
|CHEMBL3622533|[ENSG00000051382]|   1|
+-------------+-----------------+----+
```

**Expected behaviour**
1. All significant target/event pairs are included in the unfiltered dataset.
2. AEs for a target derived from a drug include all the linked targets of that drug.

**To Reproduce**
The output of the pipeline can be found at: `gs://ot-team/mbernal/data/output/fda`
A notebook with my analysis is available here: https://github.com/ireneisdoomed/random_notebooks/blob/main/FAERS/OpenFDA_target.ipynb

**Additional context**
This work is within the context of the extraction of **on target significant adverse events from the FAERS data**.
The pipeline is a new implementation and essentially mimics the drugs one. Targets are extracted from the mechanism of action dataset. The significant events for a target are then calculated using the Monte Carlo simulation.

**Comment by mbdebian** [comment]
Thanks a lot for your review on this @ireneisdoomed ! I must have made a mistake somewhere along the way.
I'll review the openfda computation for targets!
Cheers,
Manuel

**Comment by mkarmona** [comment]
@ireneisdoomed I double-checked the issue and it seems the code you pasted below uses drugs as an additional component for the composed index join. Once the target vector is exploded the drug column stops being considered as a `groupBy` column as the analysis is reaction target pair.
