### ISSUE TITLE
Facet aggregations not working on development version

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1848]
When visiting target association pages (not disease), the datatypes are disabled and they always report counts of 0.
The problem looks widespread across all targets: [ACHE](https://main--platform-app.netlify.app/target/ENSG00000087085/associations), [BRAF](https://main--platform-app.netlify.app/target/ENSG00000157764/associations), [CFTR](https://main--platform-app.netlify.app/target/ENSG00000001626/associations),...
 
<img width="418" alt="Screenshot 2021-11-12 at 15 33 30" src="https://user-images.githubusercontent.com/5097586/141492540-65e9f5af-2db2-4e1b-8107-4e9c5463cccf.png">

By looking at a single target response, it looks like a problem in the BE aggregations:

```
{
    "data": {
        "target": {
            "id": "ENSG00000105397",
            "approvedName": "tyrosine kinase 2",
            "associatedDiseases": {
                "count": 430,
                "aggregations": {
                    "uniques": 430,
                    "aggs": [
                        {
                            "name": "dataTypes",
                            "uniques": 430,
                            "rows": [
                                {
                                    "key": "genetic_association",
                                    "uniques": 0,
                                    "aggs": [
                                        {
                                            "key": "eva",
                                            "uniques": 3,
                                            "__typename": "Aggregation"
                                        },
                                        {
                                            "key": "phewas_catalog",
                                            "uniques": 142,
                                            "__typename": "Aggregation"
                                        },
                                        {
                                            "key": "ot_genetics_portal",
                                            "uniques": 35,
                                            "__typename": "Aggregation"
                                        },

``` 

The expected behaviour is that the datatypes will have non-null counts as currently happening in production: [ACHE](https://platform.opentargets.org/target/ENSG00000087085/associations), [BRAF](https://platform.opentargets.org/target/ENSG00000157764/associations), [CFTR](https://platform.opentargets.org/target/ENSG00000001626/associations)

**Comment by JarrodBaker** [comment]
It might have been me: I added a facet for 'tractability other modalities' and might have broken something.
