### ISSUE TITLE
Add "API query" button to secondary table in molecular interactions widget (target profile)

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1850]
While the first table of the molecular interactions widget in the [target profile page](https://main--platform-app.netlify.app/target/ENSG00000133019) contains the new API query functionality, the right table does not have the same functionality.

Could we please add it to the table?

(I'm assuming there is no technical problem on having 2 tables in the same widget but please raise it otherwise)

<img width="1466" alt="Screenshot 2021-11-12 at 16 18 00" src="https://user-images.githubusercontent.com/5097586/141499543-b45fd86d-7b34-4468-b728-f6b7c9a0d932.png">

**Comment by mirandaio** [comment]
The data for the table on the right already comes with the query for the first table.

**Comment by d0choa** [comment]
I missed that. There are a few things that are not coming along nicely because GQL and UI are not totally aligned. 2 GQL endpoints would generate slimmer responses. But this is outside the scope of this ticket.
