### ISSUE TITLE
Adjust logic in Project Score detail view showing cell lines

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1852]
The evidence schema has been updated so that the `diseaseCellLines` is now an array of objects, each with a `name`, `id`, `tissue`, and `tissueId` field.

Can we please update the [Project Score data table component](https://github.com/opentargets/platform-app/blob/main/src/sections/evidence/CRISPR/Body.js) to use the new `diseaseCellLines` array?

When the drawer opens, please display the following for each object:

`name` with a hyperlink to the Cell Model Passport website using the following construct - `https://cellmodelpassports.sanger.ac.uk/passports/` + `id`

So for example:

- [HCC-78](https://cellmodelpassports.sanger.ac.uk/passports/SIDM01068)
- [HOP-62](https://cellmodelpassports.sanger.ac.uk/passports/SIDM00133)

**Comment by LucaFumis** [comment]
I can take a look.

**Comment by andrewhercules** [comment]
Awesome - thank you @LucaFumis! :)

**Comment by andrewhercules** [comment]
Ticket closed as work completed, merged into `main`, and released in `21.11`
