### ISSUE TITLE
Update logo on Partner Preview Platform homepage

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1857]
As a **user** I want **to see the Partner Preview Platform logo** because **that will give me a visual cue that I am visiting the Partner Preview version of the Platform**

## Background

Currently, the logo shown on the homepage of the Partner Preview Platform is the standard Open Targets Platform logo. However, in past iterations of the Platform, we have adjusted the logo to include the `alpha`, and `beta` statuses. 

## Tasks

- [] Update the logo to use the new Partner Preview Platform logo

![Open_Targets_Platform_Logo_Partner_Preview](https://user-images.githubusercontent.com/7490258/142010739-dcba5179-ce08-4b9a-a611-001e98e9ca6c.png)
[SVG version of logo in .zip file](https://github.com/opentargets/platform/files/7547545/Open_Targets_Platform_Logo_Partner_Preview.svg.zip)

## Acceptance tests

1. When I go to the homepage, I see the new Partner Preview logo

**Comment by LucaFumis** [comment]
I've discussed with @andrewhercules that we've included the text "Partner Preview" as a string in the profile (instead of a separate logo), so it can be set to anything else if required (e.g. a specific partner name). However with this approach it doesn't feature the lock icon.

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `main`
