### ISSUE TITLE
Update API Scala version

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1869]
As a developer I want to update to the most recent version of Scala because otherwise we progressively lose third-party library support. 

## Background

The API is currently using Scala 2.12.12. Scala 3 is backward compatible with Scala 2.13, so if we can move to 2.13 we'd be able to use new third party libraries developed against Scala 3 (which will be most going forward). 

Note: The ETL uses the same version, but cannot be updated until Spark supports a higher version.  

## Tasks

- [ ] Check all dependencies/plugins/Travis for 2.13 support:
```
libraryDependencies ++= Seq(guice, caffeine)
libraryDependencies += "com.github.pathikrit" %% "better-files" % "3.9.1"
libraryDependencies += "com.typesafe.slick" %% "slick" % "3.3.3"
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "5.1.0" % Test
libraryDependencies += "org.scalatestplus" %% "scalacheck-1-15" % "3.2.8.0" % Test

val playVersion = "2.8.6"
libraryDependencies += "com.typesafe.play" %% "play" % playVersion
...
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.9.2"
libraryDependencies += "com.typesafe.play" %% "play-slick" % "5.0.0"

val sangriaVersion = "2.1.0"
libraryDependencies += "ru.yandex.clickhouse" % "clickhouse-jdbc" % "0.2.6"
libraryDependencies += "org.sangria-graphql" %% "sangria" % sangriaVersion
libraryDependencies += "org.sangria-graphql" %% "sangria-play-json" % "2.0.1"

lazy val catsVersion = "2.4.2"
lazy val cats = Seq(
  "org.typelevel" %% "cats-core" % catsVersion,
...
)


lazy val monocleVersion = "2.1.0"
lazy val monocle = Seq(
  "com.github.julien-truffaut" %% "monocle-core" % monocleVersion,
...
)

val s4sVersion = "7.9.2"
libraryDependencies ++= Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-core" % s4sVersion,
...
)
```
- [ ] Update `build.sbt`, `travis.yml` with new Scala version

## Acceptance tests

When I run `grep 'scalaVersion' build.sbt` I see `scalaVersion := "2.13.xx"`

**Comment by cmalangone** [comment]
@JarrodBaker I support your idea but please check Google Cloud Dataproc service. Probably we need to create our "cluster" with scala, java, google libraries and so on.

**Comment by ktsirigos** [comment]
work completed :)
