### ISSUE TITLE
Duplicate files in Reactome FTP folder

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#1874]
The files prefixed `part-00008` through `part-00015` in `ftp://ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.11/output/etl/json/reactome/` are identical to the ones prefixed `part-00000` through `part-00007`.

When I downloaded all files in the `output/etl/json/reactome/` folder for 21.11 and tried to index the lines in an Elasticsearch database using the `"id"` field as the identifier, every single doc in the index was overwritten by a duplicate. Upon closer inspection, the second half of the set of files turned out to consist of verbatim copies of the first half.

I'd expect each `id` to only occur once in this data type, as would've been the case if files `part-00008-*` and later were either unique or absent.

### To Reproduce
Steps to reproduce the behaviour:
1. Download the files with a command such as
```sh
wget -rl inf -nH --cut-dirs=8 'ftp://ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.11/output/etl/json/reactome'
```
2. Compare the first eight files with the second eight, for instance by running
```sh
for i in $(seq 0 7); do
    diff \
        reactome/part-$(printf %05d $i)-* \
        reactome/part-$(printf %05d $(($i + 8)))-*
    echo "Exit status: $?"
done
```
3. See the loop complete without listing any differences between the respective pairs of files or ever reporting an exit status of `1`, as diff would if a pair of files was not identical.

**Comment by DSuveges** [comment]
Thank you so much for reporting the issue @fedde-s! It's indeed a problem on our side. Recently we were having issues with copying files to the EBI ftp area. These issues were mostly related to a recent data centre migration of the institute. At this point I highly suspect the above problem is also related given the data looks good in our Google Cloud buckets. I notified the backend team and the files will be updated soon. We'll keep you posted!

**Comment by DSuveges** [comment]
Hi @fedde-s, we took a closer look into the issue and it was not a problem with rsync. The duplication exists earlier and a bug has been identified in the ETL pipeline. Our back-end colleagues are applying a fix and the duplication will be sorted very soon. In the meantime, the data itself is good if you apply a `.distinct()`. This issue has no effect on evidence and associations. I'll update this ticket once the files on ftp are sorted.

**Comment by DSuveges** [comment]
The folder is updated. The json chunks contain 2,546 objects all unique. Now I'm closing the ticket, but please feel free to reopen if you have any further comments.
