### ISSUE TITLE
API links in menu and main page lead to different GraphQL UIs

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#1877]
The **API** link in the top-right menu leads to a shiny new `/api` route within the single-page app, but the **Access data with our GraphQL API** link under **Getting started** on the home page leads to the older page exposed by the Scala-based API server.

I'd noticed the new GraphiQL browser on <https://platform.opentargets.org/api> and tried to navigate back to it, but when I scrolled down the home page and clicked the link there, I found myself on <https://api.platform.opentargets.org/> instead, looking at the three-link page that the Scala code serves, including the [to-be-phased-out](https://graphql.org/blog/2020-04-03-web-based-graphql-ides-for-the-win/) GraphQL Playground.

I expected to reach same page via both links, probably the newer GraphiQL view of the React app.

### To Reproduce
Steps to reproduce the behaviour:
1. Go to <https://platform.opentargets.org/>
2. Click on **API** in the top-right menu
3. Find yourself on an interactive GraphQL browser page with the URL <https://platform.opentargets.org/api>, that still shows the platform's footer and toolbar
4. Go back
5. Scroll down to the heading **Get started with the Platform**
6. Click on the second icon under that heading, labelled **Access data with our GraphQL API**
7. Find yourself on a much simpler page with the URL <https://api.platform.opentargets.org/>, showing just three links to paths on that same host.

**Comment by fedde-s** [comment]
Do feel free to close if this is not a bug per se, and my expectations were wrong.

**Comment by andrewhercules** [comment]
Ticket will be scoped as part of the 22.02 release.

@LucaFumis can you please adjust the link on the homepage so that the "Access data with our GraphQL API" link points to `https://platform.opentargets.org/api`?

**Comment by ktsirigos** [comment]
issue addressed
