### ISSUE TITLE
Update TEP.py module to use TSV file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1879]
Currently, the [TEP.py module](https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/TEP.py) scrapes the SGC website to generate a list of available TEPs that is then ingested into our ETL.

I have been in conversations with the SGC and they making a TSV file with TEPs information available for download:

> Dear Andrew,
> 
> Thank you very much for your email and for your request. We will implement a link on the website to download the TEP table in tsv. format in the coming days. I will let you know once the link has been implemented.
> 
> Best wishes,
> SGC

Once the file is available, can we please update the TEP.py module to use the TSV file to generate the TEPs file?

**Comment by DSuveges** [comment]
The downloadable tsv file is available here: `https://www.thesgc.org/sites/default/files/fileuploads/available-teps.tsv`

**Comment by DSuveges** [comment]
I have updated the parser, so the tsv file is fetched from the website and processed.

**Comment by ireneisdoomed** [comment]
PR [#108](https://github.com/opentargets/evidence_datasource_parsers/pull/108) has been merged.
