### ISSUE TITLE
Gene2Phenotypes - Updating evidence datasource parsers

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1882]
After investigating new Gene2Phenotype data (#1880), same field names have been changed in the new release of Gene2Phenotypes. To account for these changes, the corresponding parser needs to be updated as well. 

* No new filed is captured.
* None of the new fields will be captured so no changes required in the schema.

**Comment by DSuveges** [comment]
On 20/12/2021 noticed the downloadable tsv file is available at: `https://www.thesgc.org/sites/default/files/fileuploads/available-teps.tsv`

**Comment by ireneisdoomed** [comment]
PR [#107](https://github.com/opentargets/evidence_datasource_parsers/pull/107) has been merged.
