### ISSUE TITLE
Genetics production google project

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#189]
Currently both dev and production for the genetics platform is running in the same google cloud project. 

For safety and maintainability, we should migrate the production components into a new project `open-targets-genetics-prod`.

This includes:
 - [ ] clickhouse / elasticsearch image
 - [ ] clickhouse / elasticsearch instance groups (one per region)
 - [ ] clickhouse / elasticsearch internal load balance (one per region)
 - [ ] api instance templates
 - [ ] api instance groups (one per region)
 - [ ] global load balancer

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/genetics #217](https://github.com/opentargets/genetics/issues/217) via [**ZenHub**](https://www.zenhub.com/)
