### ISSUE TITLE
Map chemicals to pdb structures

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1892]
The molecules dataset from OpenTargets has ChEMBL identifiers. These identifiers can be mapped to PDB compound identifiers using UniChem resources. These compound identifiers then can be used to find PDB structure identifiers where the given molecule is in the complex.

**Requirements**:
- [x] Explore possibilities to establish these links in a reliable fashion
- [x] Document process
- [x] Generate stats on the mapping: number of molecules with structures, number of structure
- [x] Write up the process in a standalone function or script
- [ ] The resulting table is stored in a Google Cloud bucket.

**Comment by MarineGirardey** [comment]
Cf. [script on GitHub](https://github.com/MarineGirardey/OpenTargetInternship/blob/main/scripts/script_structure_in_molecule.py)

**Comment by MarineGirardey** [comment]
# From ChEMBL identifiers to PDB structures identifiers
**- Result extracts -**

### Molecules from parquet files

| MOLECULE_CHEMBL_ID |
| ------------------------- |
| CHEMBL1079742              |
| CHEMBL1083993             |
| CHEMBL110458                |
| CHEMBL1169388              |
| CHEMBL1173055              |
| CHEMBL1200443             |
| CHEMBL1200910              |

### ID in UniChem

**src 1 : ChEMBL ID**
**src 2 : PDB ID**

| From src:'1'            | To src:'3' |
------------------- | --------- |
| CHEMBL313405   |       ABZ   |
| CHEMBL1399676 |       MQN  |
| CHEMBL2347208|       1HL     |
| CHEMBL334167   |       SG2    |
| CHEMBL3342582|       8CF    |
| CHEMBL328910   |       DOB   |
| CHEMBL1364        |       UEG   |

### Table obtained after joining parquet molecules and UniChem molecules

| MOLECULE_CHEMBL_ID | MOLECULE_PDB_ID |
|-------------------------- | -------------------- |
| CHEMBL313405                |            ABZ                 |
| CHEMBL334167                |            SG2                 |
| CHEMBL328910                |            DOB                |
| CHEMBL1364                     |            UEG                |
| CHEMBL614                       |            PZA                 |
| CHEMBL295698                |            KLN                |
| CHEMBL1427                      |            HPA                |

### Apply function on DataFrame to get foreach PDB identifiers the structures associated

|MOLECULE_CHEMBL_ID|MOLECULE_PDB_ID|        STRUCTURE_ID|
|-------------------------|---------------------|--------------------|
|      CHEMBL313405        |            ABZ                 | [1s9g, 6qbb]           |
|      CHEMBL334167        |            SG2                 | [1kwr]                       |
|      CHEMBL328910        |            DOB                | [1dod, 1doe, 1pbb]  |
|        CHEMBL1364           |            UEG                | [4c5l, 4c5n, 5eb3...|
|         CHEMBL614            |            PZA                 | [3r4x, 3r55, 5fpd... |
|      CHEMBL295698        |            KLN                 | [2jjp, 2v0m]             |
|        CHEMBL1427            |            HPA                | [1a9q, 1a9r, 1a9t...  |

### Statistics 

| Stats                                                                             | Count   |
| -------------------------------------------------- | ------- |
|Total molecules in UniChem database                       | 14452   |
|Molecules in parquet                                                   | 12594   |
|Molecules from parquet found in UniChem               | 3657     |
|Percentage of parquet molecule found in UniChem | 29          |
|Total structures                                                             | 137175  |
|Molecules without structure                                        | 12          |

**Comment by MarineGirardey** [comment]
### Unichem cross reference dataset has been replaced by Inchikeys data set because the mapping was more important with Inchikeys.

**Inchikeys dataset**
```
+------+---------------------------+
|CCD_ID|InChIKey                   |
+------+---------------------------+
|000   |CXHHBNMLPJOKQD-UHFFFAOYSA-N|
|001   |NBYCDVVSYOMFMS-VMPREFPWSA-N|
|002   |MWZOULASPWUGJJ-NFBUACBFSA-N|
|003   |NNZDBCPMOOEFTE-UHFFFAOYSA-N|
|004   |ZGUNAGUHMKGQNY-ZETCQYMHSA-N|
|005   |LDSJMFGYNFIFRK-IUCAKERBSA-N|
|006   |KKTYZYHUPKXLPL-RIQJEONASA-N|
```
`36500` rows
`3752` molecules from parquet files (`12594` rows) are mapped by Inchikeys

**Unichem dataset**
```
+-------------+---------------+
|    chembl_id|pdb_compound_id|
+-------------+---------------+
| CHEMBL313405|            ABZ|
|CHEMBL1399676|            MQN|
|CHEMBL2347208|            1HL|
| CHEMBL334167|            SG2|
|CHEMBL3342582|            8CF|
| CHEMBL328910|            DOB|
|   CHEMBL1364|            UEG|
```
`14452` rows
`3657` molecules from parquet files (`12594` rows) are mapped by Unichem

For more information cf. Notebook [unichem_inchikey.ipynb](https://github.com/MarineGirardey/OpenTargetInternship/blob/mgirardey-updates/statistics/unichem_inchikey.ipynb)
