### ISSUE TITLE
remove the UI check for SO_0002165

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#19]
@emepyc commented on [Tue Dec 05 2017](https://github.com/opentargets/webapp/issues/227)

The api was not giving a label for that functional consequence. Once it is fixed at the data / api level we should remove this check from the webapp.

---

@LucaFumis commented on [Wed Jan 17 2018](https://github.com/opentargets/webapp/issues/227#issuecomment-358283590)

Has this been fixed already?
Searching the code for "SO_0002165" only points to the static variants.html page)

---

@emepyc commented on [Wed Jan 17 2018](https://github.com/opentargets/webapp/issues/227#issuecomment-358287636)

Yes, I think this is fixed and the hack removed. To be sure, ask @ckongEbi to revise and close  https://github.com/opentargets/data_pipeline/issues/223

---

@ckongEbi commented on [Wed Jan 17 2018](https://github.com/opentargets/webapp/issues/227#issuecomment-358290395)

What is the rest call for this? to check that this has been fixed from the backend. 

---

@LucaFumis commented on [Thu Jan 18 2018](https://github.com/opentargets/webapp/issues/227#issuecomment-358670642)

Thank you @emepyc - just had a look through this with @ckongEbi. 
The hack is still in place and the label still missing. Not a problem though.

Few info to find this quickly next time:

This affects *rare diseases* table in genetic associations on the evidence page:
http://www.targetvalidation.org/evidence/ENSG00000197386/Orphanet_399

Look in `src/components/rare-disease-table/rare-disease-table-directive.js`for 'SO 0002165' (without the underscore - I missed that yesterday)

---

@LucaFumis commented on [Wed May 16 2018](https://github.com/opentargets/webapp/issues/227#issuecomment-389494012)

FYI this issue is still outstanding.

**Comment by LucaFumis** [comment]
Quick update: issue still outstanding.
In the API call for example above there is evidence code for **SO_0002165** in `evidence.evidence_codes` but no corresponding details in `evidence. evidence_codes_info`.

**Comment by LucaFumis** [comment]
It seems that this has now been fixed at data level and the correct label is being displayed.

The 'hack' can be removed in next release or mini-release (is already being bypassed as the specified condition doesn't occur).
