### ISSUE TITLE
Fix error message showing on Platform `/api` page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1901]
**Describe the bug**

When a user visits https://platform.opentargets.org/api, there is an error message displayed in the right-hand side of the embedded GraphQL playground. 

<img width="1656" alt="Screenshot 2022-01-25 at 15 43 34" src="https://user-images.githubusercontent.com/7490258/151009764-2a02c4d4-d7b9-43c0-b339-c7888e6f303d.png">

**Observed behaviour**

Currently, the error message says:
```
{
  "message": "Unexpected token < in JSON at position 1",
  "stack": "SyntaxError: Unexpected token < in JSON at position 1"
}
```

**Expected behaviour**

Instead of showing an error message, the right-hand side of the embedded GraphQL API playground should be blank.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to https://platform.opentargets.org/api
2. See error message on right-hand side of embedded GraphQL playground

**Comment by ktsirigos** [comment]
issue addressed
