### ISSUE TITLE
Update ChEMBL in PIS

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1904]
As a result of the work described in [#1878](https://github.com/opentargets/platform/issues/1878), we need to update PIS for the ChEMBL evidence.

## The update
ChEMBL evidence used to be a submitted file that PIS picked from `gs://otar008-chembl` getting the latest file that followed the pattern `cttv008-DD-MM-YYYY.json.gz`

Now the ChEMBL evidence is enriched by the Data team, so PIS needs to be updated. The new location follows the same structure as the rest of the internal evidence, that is:

- **New bucket**: `gs://otar000-evidence_input/ChEMBL/json`
- **New pattern**: `chembl-YYYY-MM-DD.json.gz`

@opentargets/be-team Could you please take care of this?

**Comment by cmalangone** [comment]
https://github.com/opentargets/platform-input-support/pull/new/cm_change_chembl_evidence_conf_1904

**Comment by ireneisdoomed** [comment]
Work completed (https://github.com/opentargets/platform-input-support/pull/63)
