### ISSUE TITLE
ClinVar publications only available from RCVs with OMIM as a submitter

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#1905]
I'm not entirely sure if this is true, but it seems that publication data (i.e. PMIDs) on clinical variants are only present for EVA/ClinVar records when OMIM is a submitter contributing to the record.  For example, the "Literature" field in the "ClinVar" section of https://platform.opentargets.org/evidence/ENSG00000196712/EFO_0000565 is always null except for one record (cross linked to https://www.ncbi.nlm.nih.gov/clinvar/RCV000000380/) where the PMID is linked for the OMIM publication.  I've noticed this pattern for a number of target + disease pairs.

Is this by design?  There are clearly publication records linkable for other ClinVar associations, so I was curious why they seem to be getting ignored.

**Comment by eric-czech** [comment]
Sounds right, I don't see any value in them either now that I'm looking closer.

I'll close this out but let you know if we find any use for those citations or any others that seem to be slipping through the cracks somehow.

**Comment by DSuveges** [comment]
Hi @eric-czech, please take a look at [this ticket](https://github.com/EBIvariation/eva-opentargets/issues/166) at EVA, our data provider, who processes the ClinVar data and prepares the disease/target evidence. Under this ticket you'll see details on the decision to keep literature references only that support the disease/target associations.
