### ISSUE TITLE
PIS does not pick some of the latest files

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1908]
**Describe the bug**
PIS has been run to consolidate the data for the 22.02 release. Some of the **target annotation files** are not the most recent ones uploaded to their respective buckets.

**Observed behaviour**
List of offending datasets:

- [x] **Mouse phenotypes**. This is due to a change made by the Data team where we've changed the name of the file from camel to snake case. The new pattern would be `mouse_phenotypes-YYYY-MM-DD.json.gz`
- [x] **Chemical probes**. The bucket is correct but not the file. This is the good one chemicalprobes-2022-01-25.json`
- [x] **Tractability**. PIS's picked the latest from last year. The good one: `Tractability_22.02_tractability_buckets_2022-01-19.tsv`
- [x] **TEP**. The bucket is correct but not the file. The good one:` tep-2022-01-24.json.gz`
- [x] **Hallmarks**. The good one: `CTTV007-19-01-2022_v95_hallmarks.tsv.gz`
- [x] **Adverse events in Target Safety**. I am not sure about this one. The raw filename specifies the date but the one exposed by PIS does not.

**Expected behaviour**
If the buckets are correctly specified, PIS shouls pick the latest file of them.

**Comment by JarrodBaker** [comment]
@cmalangone The only outstanding problem the adverse events in target safety. Can you please add a suffix so we have the data versioned?

**Comment by JarrodBaker** [comment]
@ireneisdoomed the problem with TEP was us pulling the data from `gs://otar001-core/TEPs/data_files` instead of `gs://otar001-core/TEPs/`. If there isn't a good reason to have a directory structure under `TEP` I'll flatten it out by moving everything from `data_files` to its parent directory. Sound ok?

**Comment by ireneisdoomed** [comment]
@JarrodBaker Thanks for investigating. The idea for that was to keep a similar structure for all the annotation but to be fair, after checking some directories we are not being very consistent, so it is not really the case.

@DSuveges We usually store the raw data used in the evidence generation so we can trace it back. This would be in `data_files` and we would store the processed output in `json`. Should we do the same in this case? I've personally never used these files to debug anything so I'm not sure about the value. At the same time, I think that storing the metadata of our runs like in the ETL is a clearer and nicer solution. What do you think?
