### ISSUE TITLE
Update `<title>` tag for `/downloads` page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1928]
Currently, the /downloads page has a "Variant definitions |  Open Targets Platform" as the HTML `<title>` attribute.

![Screenshot 2022-02-07 at 14 21 21](https://user-images.githubusercontent.com/7490258/152805908-9b486efb-9d66-4730-b8ef-eda0f494d8c8.png)

Can we please update to "Data downloads | Open Targets Platform"?

**Comment by ktsirigos** [comment]
work completed
