### ISSUE TITLE
Pipeline QC: Automated QC distribution of scores

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#194]
As part of the automated QC we should report some very roughly bucketed distribution of scores, for val, evidence, and association steps. For example 5 buckets of width 0.2

**Comment by MichaelaEBI** [comment]
This ticket needs more detail about how this will be implemented and how it will be reported, ie, a data file, automatic generation of plots? 
This could be done after the pipeline ran successfully and could be part of a bigger effort to also compare different releases, ie. a summary of which diseases, targets and associations are new or were dropped.

**Comment by afaulconbridge** [comment]
This ticket is for part of the automated QC, and therefore would follow that reporting pathway - currently, a tsv file similar to https://docs.google.com/spreadsheets/d/1CeAk4LlnrTFFgzSJJyRuLr09wIj2bDbQuU2PuNFubOI/edit?usp=sharing

Generating pretty plots, or other changes QC process, are outside the scope of this issue. This issue is very specifically for a quick and dirty first pass approximation within the existing automated QC framework.

**Comment by d0choa** [comment]
A new version of this task is under review and we'll described in a separate issue
