### ISSUE TITLE
Ensure global proxy of ensembl routes correctly

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#196]
Global users of the OpenTargets platform experience high latency when EBI (or other non-global) resources are accessed e.g. from South Korea to the UK, it is about a second for the time the first byte (TTFB).

We currently have an nginx proxy in three locations around to world to leverage google CDN to improve this. Unfortunately, this only works for second and subsequent requests. For example, see https://www.targetvalidation.org/target/ENSG00000091513 in the "Variants, isoforms and genomic context"  section with and without a SSH tunnel ( https://cloud.google.com/community/tutorials/ssh-tunnel-on-gce ) .

Ensembl does have some mirrors  (see http://www.ensembl.org/info/about/mirrors.html and http://www.ensembl.org/info/about/legal/mirror_policy.html ) but they appear to operate in a non-standard way. This issue is to ensure that we are accessing ensembl via the appropriate geo-located mirror.

**Comment by ktsirigos** [comment]
No proxy related to the rewrite.
