### ISSUE TITLE
Update the linkout to ClinGen

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1960]
When the ClinGen widget was designed the database was searchable by the Expert Panel (#1227), which is given in the `studyId` field.

This is no longer the case, so the link embedded in the "Classification" column does not return anything relevant to the evidence.

For example, the [link](https://search.clinicalgenome.org/kb/gene-validity/Hearing%20Loss) to search the `Hearing Loss` panel for the association between [Waardenburg-Shah syndrome and EDN3](https://platform.dev2202.opentargets.xyz/evidence/ENSG00000124205/Orphanet_897):
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/a0f5bb2b-ae54-4a54-b84b-cf499fa51a86)

@andrewhercules, If we change the URL to search their website at `https://clinicalgenome.org/search/?q=` do we get the functionality back? If this is still not relevant, I propose removing the link.

![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/918845f2-483d-4d93-a4a1-747d5d1aa76d)

Note: this is already in production.

**Comment by d0choa** [comment]
This is the expected panel for the above case https://clinicalgenome.org/affiliation/40007
But we continue to have no way to access the ID through the downloads.

We should probably drop the link and include the panel as a string in a different column. Similar to what we do with gene2phenotype

@andrewhercules?

**Comment by ireneisdoomed** [comment]
After discussion with the Data team, I can confirm that such ID referring to the panel is not provided in the data file. However, we do have a link to the g/d association page in Clingen, which is more valuable. This is already provided in the evidence in the `urls.url` field.

Therefore, my suggestion is:

1. To drop the [linkout](https://github.com/opentargets/platform-app/blob/bd2e475bc7606a12252b19726bfd0d0fd48cd953/src/sections/evidence/ClinGen/Body.js#L73) in the `Classification` column to the broken page.
2. As @d0choa suggested, add a new `Panel` column where:
- the text comes from `studyId`, which will display the name of the panel of experts (E.g. "Hearing Loss")
- this text links out to the association page that comes from `urls.url` (E.g. "https://search.clinicalgenome.org/kb/gene-validity/CGGV:assertion_7f88c34c-a093-4fc8-b84a-49c7d2dd327f-2018-05-08T160000.000Z"). This array always contains one element and is never null.

Alternatively, we could structure the links differently. This would require more actions in other tables:
1. If the data source has a reference page for the _association_, we include the link in the `Confidence` column (since it also refers to the association). The case for ClinGen, Panel App, ClinVar (this is displayed in an independent column with the ClinVar ID), and G2P (site currently down).
2. If the data source has a reference page for the _Panel_, we include it in the `Panel` column. The case for ClinGen, PanelApp and G2P.

Any thoughts? @DSuveges

**Comment by andrewhercules** [comment]
Ticket scoped for `22.04` release and added to [release intentions document](https://docs.google.com/document/d/1DcQ1CVg0jgQpJlKSvVCQkcYznwaAKiUcY0khToA0Ubg/edit#heading=h.eu86k7xr40xz)

**Comment by DSuveges** [comment]
I think if we have the direct link to the target/gene summary page, we should use that. I checked and it is available for every evidence.

**Comment by d0choa** [comment]
Do you mean something like this @DSuveges?
https://search.clinicalgenome.org/kb/genes/HGNC:3178
This sounds like a good alternative. And the link is easy to build with our API
