### ISSUE TITLE
Update the Platform footer component

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1962]
Can we please make the following changes to the Platform footer component?

![Screenshot 2022-02-18 at 12 46 56](https://user-images.githubusercontent.com/7490258/154685719-1aad50f3-ed82-4105-bd9f-4d4960e30d58.png)

- [x] In the "Partners" section, between "GSK" and "Sanofi", add "Pfizer" with a link to `https://pfizer.com/`

- [x] In the "Follow us" section, remove the Discourse icon and link

- [x] In the "Help" section, change the documentation icon to the [FontAwesome book icon](https://fontawesome.com/icons/book?s=solid)

- [x] In the "Help" section, remove the envelope icon and `helpdesk@opentargets.org` email address and replace with the [FontAwesome circle-question icon](https://fontawesome.com/icons/circle-question?s=solid) and the label "Ask a question" that l links (in a new tab) to `https://community.opentargets.org/`

**Comment by LucaFumis** [comment]
Hi @andrewhercules, quick question: do we want to update the helpdesk email address accordingly also in the hamburger menu? 
I'd imagine that's the case (currently they are both pulled from config), but just to confirm.

**Comment by andrewhercules** [comment]
Good point @LucaFumis!

In the hamburger menu, can we please change the "Community" link to "Ask a question"? And for now, we can leave the "Contact Us" option with the help desk email, although @ktsirigos and @HelenaCornu may want to change that at a later date.

**Comment by d0choa** [comment]
Just a random thought @andrewhercules. Isn't discourse more than just "Ask a question"? I mean we also have announcements and other general discussions (although not that many).
