### ISSUE TITLE
"BET inhibitors" not available via ChEMBL data source

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#197]
As per clinical trials, there are 22 trials returned for the search term "BET inhibitors":
https://clinicaltrials.gov/ct2/results?cond=&term=BET+inhibitors&cntry=&state=&city=&dist=

BRD4: no drug in ChEMBL or Open Targets but the clinical trial is available (however they use a different target name - BET inhibitors)

@ElaineMcA @MichaelaEBI  to check with ChEMBL if they can assist.

**Comment by MichaelaEBI** [comment]
Added to our brand new ChEMBL data curation sheet. Will contact ChEMBL to follow up on this.

**Comment by MichaelaEBI** [comment]
ChEMBL is on the case. I will close this ticket. Progress of ChEMBL curation can be followed here: https://docs.google.com/spreadsheets/d/1fO97H4BJ_Lxu1GHHytibYZg92MTUTrjgRxDQ_ksK1aw/edit#gid=0
