### ISSUE TITLE
ETL does not support BZIP2 format

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1972]
**Describe the bug**
ETL fails to process input data that has been compressed in BZIP2.

**Observed behaviour**
Expression Atlas is advocating for using BZIP2 instead of GZIP for its better compression mechanism.
Apparently, the ETL does not support such format, hence failing when processing the new Expression Atlas evidence. To address this, the file has been unzipped so that it can be processed.

**Questions**
- Should we accommodate the pipeline to process this format? Pablo, from Expr. Atlas, says that they can revert this change if this becomes problematic.
- What is it exactly that is failing, @cmalangone? I am able to load this file with Spark.

**Comment by cmalangone** [comment]
@ireneisdoomed Apache Spark 3.0.1 doesn't support  BZIP2 compression.

**Comment by cmalangone** [comment]
@mbdebian and @JarrodBaker will add more details after 22.02 release

**Comment by JarrodBaker** [comment]
What was the error here @cmalangone? I haven't been able to reproduce the problem.
