### ISSUE TITLE
move to quay and travis

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#198]
Make things simpler than before and trying to join forces. `data_pipeline` is open so move to a free for open source services without restrictions is crucial as we are getting quota problems with circleci.
Branches automatically allowed to build on travis are:
```yaml
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
  - "/mk.*/"
  - "/af.*/"
  - "/ck.*/"
  - "/ms.*/"
  - "/MS.*/"
  - "/gp.*/"
  - "/pl.*/"
```
gp for Glenn Proctor and pl for Pieter Lukasse

Projects already working with travis and quay

| Repo name | Travis | Quay | Codecov | CircleCI |
| --------- | ------------------- | ---------------- | --------- |  --------- |
| data_pipeline | :large_blue_circle: |  :large_blue_circle: | :large_blue_circle: | :black_circle:  |
| rest_api | :large_blue_circle: | :large_blue_circle: | :large_blue_circle: | :black_circle:  |
| opentargets-py | :large_blue_circle: | :white_circle: | :large_blue_circle: | :black_circle: |
| webapp | :large_blue_circle:  | :large_blue_circle: | :white_circle: | :black_circle: |
| ontology-utils | :large_blue_circle: | :white_circle: | :large_blue_circle: | :black_circle: |
| validator | :large_blue_circle: | :large_blue_circle: | :large_blue_circle: | :black_circle: |
| evidence_datasource _generators | :red_circle: | :red_circle: | :red_circle: | :black_circle: |
| OnToma | :red_circle: | :white_circle: | :red_circle: | :large_blue_circle: |
| json_schema | :large_blue_circle: | :white_circle: | :white_circle: | :black_circle: |

Legend:

- :large_blue_circle: means currently working
- :red_circle: means currently not working
- :white_circle: means not applicable
- :black_circle: means removed

**Comment by afaulconbridge** [comment]
Should `json_schema` be here too @mkarmona? It can't have coverage or a docker image, but we should be able to put CI checks on syntactic validity at least.

**Comment by mkarmona** [comment]
a circleci column is missing saying about circleci dependency removed

**Comment by afaulconbridge** [comment]
Added a column and a colour for circleci removal, but not filled in the data yet

**Comment by afaulconbridge** [comment]
Updated.

**Comment by afaulconbridge** [comment]
ontology-utils is on travis and removed from circleci on af-cleanup branch
