### ISSUE TITLE
OTAR042 -Tractability: Review of project data CSV file

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#2]
Final version of csv to be received by 10Aug2018.

csv reviewed by Andrew and Michaela

**Comment by andrewhercules** [comment]
Currently waiting for an updated CSV from Chris - expected to receive within the next few days. Once received, will review with @MichaelaEBI and develop data specification

**Comment by andrewhercules** [comment]
Updated CSV file has been received from Chris and put into the OT Platform Google Drive in [/OT Projects / OTAR042:Tractability / 2. Data](https://drive.google.com/drive/folders/1TAJmrYuTmksgEJDZaCvcW_fER0tEbKqH?usp=sharing)

**Comment by andrewhercules** [comment]
I have updated [the spreadsheet that describes the tractability buckets, categories, and supporting information](https://docs.google.com/spreadsheets/d/1Yjdp3qzdOQCbgNzHEPOw6dtCyugPu26_RhE4epm8wuU/edit?usp=sharing). I will send a link to Chris to verify that categories and descriptions are correct.

Once approved by Chris, the data in the spreadsheet can be used for docs/training and for front-end tooltips.

**Comment by andrewhercules** [comment]
Chris has verified that [the spreadsheet that describes the tractability buckets, categories, and supporting information](https://docs.google.com/spreadsheets/d/1Yjdp3qzdOQCbgNzHEPOw6dtCyugPu26_RhE4epm8wuU/edit?usp=sharing) is correct. 

Review of CSV file is complete.
