### ISSUE TITLE
Evaluate synonyms from EFO

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#213]
In some cases, EFO synonyms have a low information content. For example,  in EFO 3 "heart disease" lists:

CARDIAC DIS
Cardiac Disease
Cardiac Diseases
Disease, Cardiac
Disease, Heart
Diseases, Cardiac
Diseases, Heart
HEART DIS
Heart Diseases
cardiac disease
disease of heart
heart disease
heart disease or disorder
heart disorder
heart trouble

EFO will be looking at a policy for synonyms, and improving the representation. We should chase this up in a few months time (towards end of Q1 2019.

It has been suggested that these lists could be improved by looking for both "[A], [B]" and "[A] [B]" and only keeping the latter, using a "stemming" approach to plurals, and by using other lists of synonyms.

**Comment by afaulconbridge** [comment]
See EFO issue EBISPOT/efo#276

**Comment by afaulconbridge** [comment]
Related to opentargets/platform#269

**Comment by d0choa** [comment]
While information content might be low, it's useful for some of our applications such as search.
Some problems still arise from MONDO synonyms. These days, they very often contain other diseases in the ontology.

I'm closing as it doesn't seem to introduce any particular challenges in our side
