### ISSUE TITLE
Remove unused fields from /private/disease/<efoId> endpoint

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#216]
The following fields are used by the front-end:
```
children
code
definition
efo_synonyms
label
path
```

The following fields are not and could therefore be removed entirely from the REST API to reduce bloat. Many take the value null, [] or {} seemingly all the time. They may be useful within the back-end codebase, but could be removed from the API at least.
```
data_release
path_codes
path_labels
phenotypes
therapeutic_labels
```

**Comment by d0choa** [comment]
@mkarmona looking at this to start implementation of the graphQL schema

**Comment by d0choa** [comment]
Closing as the new graphQL API will provide a new set of agreed fields
