### ISSUE TITLE
post rest api endpoint for diseases does not seem to work?

### ISSUE THREAD

**Issue by emepyc** [opentargets/platform#219]
@mkarmona I'm trying the make POST requests to the disease endpoint (https://api.opentargets.io/v3/platform/private/disease) following the doc in http://api.opentargets.io/v3/platform/docs#operation/postDiseaseById

neither of these seem to work:

```
curl -H "Content-Type: application/json" -X POST -d '{"disease":["Orphanet_99688"]}' 'https://api.opentargets.io/v3/platform/private/disease'
```

```
        disease_response = requests.post(
            self._ot_api_url + "private/disease",
            json={
                "disease": disease_ids,
                "facets": "false",
            },
            headers={
                "Accept": "application/json",
            },
        )
```

both with `{'message': 'Internal Server Error'}` as a response.

Also, the documentation for POST requests to the /private/target endpoint looks wrong in http://api.opentargets.io/v3/platform/docs#operation/postTargetByENSGID 
The documentation states that this should work:

```
{
  "target":["target1", "target2"],
  "facets" = "true"
}
```

but the key for targets should be "id" instead of "target", in fact this is what is being called by the platform (batch search page: https://www.targetvalidation.org/summary?targets=231160,245105,198763,73756,95303,108219,198369,105401,134882,197272,181915,119919,105397,178623,107968,133195,171522,116288,169508,143365,95110,109787,179344,153064,108094,116833,151151,111537,114859,12779,169220,103375,189067,108423,133703,138031,178828,197114,130592,100368,164308,111424,108688,181634,164512,182256,113327,163285,79263,115232,100311,143622,167207,187796,85978,162594,90339,5844):

```
{
  "id":["ENSG00000231160",...],
  "size":58,
  "fields":["ensembl_gene_id","drugs","approved_symbol","reactome","uniprot_id"]
}
```

btw, I have tried to use "id" also in the disease endpoint but no luck:

```
$ curl -H "Content-Type: application/json" -X POST -d '{"id":["Orphanet_99688"]}' 'https://api.opentargets.io/v3/platform/private/disease'
```

I know that the `private` methods can change without notice (or bumping up the version), but it would be nice to keep the documentation in sync with the code  / actual endpoints

**Comment by d0choa** [comment]
All work is focused on new API
