### ISSUE TITLE
Genomics England evidence data has an invalid publication field

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#22]
@emepyc commented on [Fri Dec 01 2017](https://github.com/opentargets/webapp/issues/226)

This required a hack in the webapp to look for the incorrect value ('NA')

https://github.com/opentargets/data_pipeline/issues/220

---

@LucaFumis commented on [Wed Jan 17 2018](https://github.com/opentargets/webapp/issues/226#issuecomment-358286946)

For the webapp this is in `components/rare-disease-table/rare-disease-table-directive.js` and has a handy comment `TODO: https://github.com/opentargets/webapp/issues/226`

---

@LucaFumis commented on [Mon Jun 25 2018](https://github.com/opentargets/webapp/issues/226#issuecomment-399918041)

Data issue; still outstanding.
An example can be seen here: https://www.targetvalidation.org/evidence/ENSG00000157764/Orphanet_79364

**Comment by MichaelaEBI** [comment]
Current example: https://www.targetvalidation.org/evidence/ENSG00000139618/EFO_0000311

**Comment by MichaelaEBI** [comment]
The actual issue is that publications are not a required part for reviews of gene membership to Genomic England disease panels. [BRAF is linked to 'breast carcinoma'](https://www.targetvalidation.org/evidence/ENSG00000139618/EFO_0000311) in several panels and in panel [255](https://panelapp.genomicsengland.co.uk/panels/255/gene/BRCA2/) (for Neurofibromatosis Type 1) one reviewer added PMIDs and in panel [158](https://panelapp.genomicsengland.co.uk/panels/158/gene/BRCA1/) (for Familial breast cancer) none of the reviews contain a PMID. The reviews for a gene to belong to a Genomics England panel are the 'references' for this data source.

**Comment by andrewhercules** [comment]
Reassigned to 20.11 pending further conversations with Genomics England

**Comment by ireneisdoomed** [comment]
Our current files do not currently include any information regarding "Publications". We have discussed this issue in the meeting held on October 7th.

Today I have emailed GEL to follow-up on whether it is possible to update the files for the next release.

**Comment by ireneisdoomed** [comment]
Eleanor from GEL has answered indicating that the best option would be to feed the "Publications" field by querying their API.
Two ways to approach this:

> - through the genes endpoint - https://panelapp.genomicsengland.co.uk/api/v1/genes/ which gives you all genes on all panels.  You could then filter by the confidence level (green, amber, red, grey which correspond to 3,2,1,0 in the API values), and version and type of panel the gene is on. 
> - go to the panels endpoint first https://panelapp.genomicsengland.co.uk/api/v1/panels/ - filter out the panels you are interested in by version and panel type, and then for each panel get the gene information using the panel ID e.g. https://panelapp.genomicsengland.co.uk/api/v1/panels/398/genes/. 

I will work on this in the next couple of days.

**Comment by AsierGonzalez** [comment]
That suggests that the publications are per gene and not per gene-disease(panel) pair, right?

**Comment by ireneisdoomed** [comment]
The API querying has been optimized - being able to get all the Publications terms without any raised errors.

This issue no longer applies.
