### ISSUE TITLE
Inconsistent linkouts from disease and target profile pages

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#220]
Not urgent, but important.

In the disease and target profile pages sometimes our linkouts go to:

1) original source of the data (e.g. orphanet, PDBe)
2) our docs (e.g. EFO)
3) a blog post (e.g. for LINK in bibliography)

I'd advocate for consistency here.
And would favour pointing to the original resource (PDBe, LINK, etc) based on the @andrewhercules's recommendation for Open Targets Genetics Gene page "Linkbacks are great, but we should be focussed on giving our users the right mix of external links and contextual information as this helps with SEO - we are seen as an authority on a topic."

But if we decided on pointing only to the docs, we need to create entries for PDBe, Orphanet, etc...

Thoughts?

**Comment by deniseOme** [comment]
Please also note that there is no consistency when using upper case on some of the names:

Target tractability (both capitalised) but Protein interactions (only the first word is capitalised).

**Comment by MichaelaEBI** [comment]
A good start would be to document the inconsistencies so that we can work through them systematically. @deniseOme would you be able to do that?

**Comment by deniseOme** [comment]
Sure, @MichaelaEBI . Here it is:

https://docs.google.com/spreadsheets/d/14eGsLhvq6sqOSwkEgKWpam-Cj-RXpKXmjvMqmZy9Z8s/edit#gid=0

Feel free to change the way the information has been recorded.

**Comment by MichaelaEBI** [comment]
This is great, thanks @deniseOme .

**Comment by andrewhercules** [comment]
@LucaFumis, for 19.09, can we please make the following adjustments?

**Target Profile Page**
- [ ] Target tractability: please change the `Source: Open Targets` link to https://docs.targetvalidation.org/faq/what-is-target-tractability 
- [ ] Bibliography: please change the `Source: LINK` link to http://link.opentargets.io/

**Disease Profile Page**
- [ ] Phenotypes: please change the `Source: EFO, Orphanet` links to https://www.ebi.ac.uk/efo/ AND https://www.orpha.net
- [ ] Bibliography: please change the `Source: LINK` link to http://link.opentargets.io/
- [ ] Classification: please change the `Source: Open Targets` link to https://docs.targetvalidation.org/faq/describing-diseases
