### ISSUE TITLE
can't specify datatype in POST requests to /public/association/filter

### ISSUE THREAD

**Issue by emepyc** [opentargets/platform#221]
In the rest api documentation for getting associations: http://api.opentargets.io/v3/platform/docs#operation/getAssociationFilter, `GET` requests have several fields you can use like `size`, `datatype`, `datasource`, etc, so you can do this:

```
$ curl 'https://api.opentargets.io/v3/platform/public/association/filter?disease=EFO_0000253&datatype=genetic_association&size=1'
```

In the doc it is not clear if all those fields can also be set if making a `POST` request (http://api.opentargets.io/v3/platform/docs#operation/postAssociationFilter).

This works:

```
$ curl -X POST -d '{"size":1, "disease":["Orphanet_99688","EFO_0000253"]}' --header 'Content-Type: application/json' https://api.opentargets.io/v3/platform/public/association/filter
```

but this does not (gives 0 results even if there are associations based on genetics):

```
$ curl -X POST -d '{"datatype":"genetic_association", "disease":["Orphanet_99688","EFO_0000253"]}' --header 'Content-Type: application/json' https://api.opentargets.io/v3/platform/public/association/filter
```

bug or a feature? why in `POST` requests I can set the size of the query and not the datatype I want to filter by? If feature, it would be nice to document 😄 
@mkarmona

**Comment by AsierGonzalez** [comment]
I will look into this with @mkarmona to see if there is a bug here

**Comment by d0choa** [comment]
No more work is expected in the former API/Swagger
