### ISSUE TITLE
Provide files to enable OT data in EBI search

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#227]
Technical meeting held Monday 29Oct2018 with EBI Search team:

These are XML/JSON default formats for EBI Search :
https://www.ebi.ac.uk/seqdb/confluence/display/EXT/XML+dump+file

https://www.ebi.ac.uk/seqdb/confluence/display/EXT/JSON+data+format

During the meeting you mentioned there are 3 types of datasets in OpenTarget, targets, diseases and associations.

In general, each entry needs a corresponding URL to your website so users can find details about the entry. 

I can find links to target and disease datasets:
https://www.targetvalidation.org/target/ENSG00000139618

https://www.targetvalidation.org/disease/EFO_0000384

For me the associations data looks like linking/evidence information between targets and diseases. If I am not wrong, we can consider to have two datasets (targets & diseases) and then display additional link named "associations" on both datasets. 
This is a mock up search result page.. the link on "Crohn's diseases" will point to https://www.targetvalidation.org/disease/EFO_0000384

"View associated targets" will go to https://www.targetvalidation.org/disease/EFO_0000384/associations

This is one of possible suggestions. As you know the data better than us, you can make a decision. 
If you want, we can index your sample data and then try/see on wwwdev site. So please feel free to ask us to index your sample data if you want to try. 

For the time being, we can put aside the issue about which categories OpenTarget datasets should be put. As we talked there is no technical issue but we just need agreement and confirmation. :)

@afaulconbridge to confirm complexity/ estimate please for level of effort involved to achieve this.

**Comment by d0choa** [comment]
Closed because of inactivity.
