### ISSUE TITLE
Ontology: Additional refactor areas to investigate and plan

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#228]
Possible areas for refactoring summarised during core team meeting update 29Oct2018:

**- [ ] Removal of manual hard coded mapping for TAs:**
TAs should be provided via Mondo (EFO 3)
Help to update high level terms and give more coverage (across diseases and phenotypes)

- Possible to simplify filters/ facets to match TAs that are provided to us?
- Check versus EFO 3 beta for what has been given to ensure that 18.12 release runs smoothly

(Expect EFO V3 to be released early 2019).

- [ ] Descriptions are not currently being pulled in for all diseases currently
- Our code needs to be fixed here

- [ ] Phenotypes are not being pulled in for all on DPP - often empty
- Again, our code may need to be updated to enable.

**Comment by afaulconbridge** [comment]
Closing, will mostly be done for 19.11
