### ISSUE TITLE
Target profile page rewrite: Create reusable header component

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#239]

**Comment by andrewhercules** [comment]
The general layout of the header can be found on [the OT Platform Team Google Drive](https://drive.google.com/open?id=14WMg9I_prKaTw2Bv8DdluBajNZzSSukD).

In keeping with the current style of the Platform header, can the blue background extend across the entire browser window, with the Open Targets Platform word mark, search bar, notification bell, and menu icon inside a 1200px wide container? 

Also, in the mockup, you'll notice that I'm using icons from Font Awesome for the menu, notification bell, and search. But we can use another icon library if needed - whatever integrates best with the React app and front-end framework.

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user, I want to know which Open Targets service I am using
2. As a user, I want to be able to search for a given entity when I am on any page
3. As a user, I want to see a notification when there has been a new data release
4. As a user, I want to be able to access the menu with links to the documentation, downloads, support email, etc.

### Component design

![header](https://user-images.githubusercontent.com/7490258/49086564-b9984300-f24c-11e8-851c-a57a41de6d65.png)

**[Full size version](https://drive.google.com/open?id=1vThmanXSjEON6qayXj_h9_ddnEFDbjbE)**
 
### Key design and interaction notes

- Please make the background of the header and menu dark blue `#006593`
- Please use [the white version of the Open Targets Platform wordmark](https://drive.google.com/open?id=134fI_GXAMlCwoGH5X4ji2kQiVBnHLMCe)
- Please make the icon in the search box [the search icon from FontAwesome](https://fontawesome.com/icons/search?style=solid) (e.g. `<i class="fas fa-search"></i>`)
- Please make the notification icon [the bell icon from FontAwesome](https://fontawesome.com/icons/bell?style=solid) (e.g. `<i class="fas fa-bell"></i>`) *note: similar to the current platform, can we please add configuration so that it can be turned on and off when there is a new data release?*
- When a user clicks on the 'Menu' button, can we please animate the menu and follow something like [the Pure CSS hamburger fold-out menu on right-side example](https://codepen.io/erikterwan/pen/grOZxx) from CodePen?
- Please make the X to close the menu [the times icon from FontAwesome](https://fontawesome.com/icons/times?style=solid) (e.g. `<i class="fas fa-times"></i>`)
- Please make the new batch search icon [the list-alt icon from FontAwesome](https://fontawesome.com/icons/list-alt?style=regular) (e.g. `<i class="far fa-list-alt"></i>`)

### Design assets

1. The word mark and helix icon are available on the [OT Core Platform Team Google Drive](https://drive.google.com/drive/folders/1eTtx_w140QBKpCMSqRUaM0Va7hbtH_5L)
2. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by andrewhercules** [comment]
- [ ] Change search input field from select to new Material-UI select
- [ ] Implement menu as per spec above
- [ ] Create list of menu items in a config file that can be customised
- [ ] Update spec with list of menu items (simple) that will be available by default

**Comment by LucaFumis** [comment]
I've addressed the implementation of the menu (including simple configuration) in a slightly simpler format than specs above, pending PR merge - @andrewhercules perhaps we can have a quick chat/review sometimes this week...

**Comment by d0choa** [comment]
A more comprehensive review of the components will be completed at a later stage.
I consider this done for the moment
