### ISSUE TITLE
Batch search - exact protein name matches but still 'offers suggested matches'

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#24]
@MichaelaEBI commented on [Wed Jun 06 2018](https://github.com/opentargets/webapp/issues/287)

### Observed behaviour
In a batch search of 133 proteins, CD27 & MYO1G had suggested matches even though there are exact matches for these two proteins.

### Expected behaviour
These two proteins to appear in the 'Exact matches' box.

### Environment
[How did you see the bug?]
* Version: online
* Browser: Safari

---

@deniseOme commented on [Wed Jun 06 2018](https://github.com/opentargets/webapp/issues/287#issuecomment-395049981)

I thought this had been fixed by @mkarmona before the 18.04 release.

---

@MichaelaEBI commented on [Wed Jun 06 2018](https://github.com/opentargets/webapp/issues/287#issuecomment-395050758)

I just chatted with him on Slack - I did a batch search with 133 proteins and observed this behaviour again. Miguel will look into this on Friday.

---

@deniseOme commented on [Wed Jun 06 2018](https://github.com/opentargets/webapp/issues/287#issuecomment-395051991)

Even if you do a batch search with the two offending gene symbols, the expected behaviour won't be observed.

Good to know the bug is back, in case users report the same. Is it worth merging this with the previous ticket?

---

@deniseOme commented on [Wed Jun 06 2018](https://github.com/opentargets/webapp/issues/287#issuecomment-395053606)

#274 #134

---

@MichaelaEBI commented on [Thu Jun 07 2018](https://github.com/opentargets/webapp/issues/287#issuecomment-395330383)

Denise, yes, please feel free to merge with previous ticket - I did not find #134 yesterday.

---

@MichaelaEBI commented on [Fri Jun 08 2018](https://github.com/opentargets/webapp/issues/287#issuecomment-395674214)

Another search with nearly 200 genes today revealed that these two gene names also result in suggested matches even though there are exact matches: PRMT5 & FGFR1. For PRMT5 there are the following three suggestions in addition to PRMT5:
 COPRS
 PRMT5-AS1
 PRMT5P1
The last two will be suggestions based on name and the first one is a suggestion based on its approved name: [coordinator of PRMT5 and differentiation stimulator](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:28848)
I don't know how the batch search works, but I think that there should be no need to search any further if there are exact matches.

For FGFR1 the following are suggested. Most of them are based on name matches with FGFR1, some I have no idea:
FGFR1OP
FGFR1OP2
FGFR1
FGFR1OP2P1
FOPNL ([FGFR1OP N-terminal like](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:26435))
FGFR2
FGFR4
FGFR3
RET ([no idea why this one comes up](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:9967))
TADA2B ([no idea why this one comes up](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:30781))

**Comment by andrewhercules** [comment]
Closing this ticket as batch search functionality and protein name matching have been updated, which has resolved this issue. See below for a screenshot of batch search taken today:

![screen shot 2019-01-02 at 13 44 03](https://user-images.githubusercontent.com/7490258/50594460-989ebf80-0e94-11e9-98d0-acabccb0700f.png)
