### ISSUE TITLE
Target profile page rewrite: Create "Drugs" summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#242]

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user, I want to know how many drugs target this gene and the modalities of the drugs. 
2. As a user, I want to know how many clinical trials involve the modulating of this gene and what the breakdown of the trials are by phase.

### Summary widget

![known-drugs](https://user-images.githubusercontent.com/7490258/49014953-99e41a80-f179-11e8-881e-c7d88b0f8dfb.png)
 
### Key design and interaction notes

- For the modalities, if the modality exists in the data, please make the icon purple (#7B196A), otherwise the icon should be light grey (#E2DFDF)
- Beside each modality, please put the number of drugs that match that modality in brackets
- For the clinical trials histogram, please make the bars purple (#7B196A) and in the title, please put the total number of trials

### Design assets

1. Modality icons are available on the [OT Core Platform Team Google Drive](https://drive.google.com/drive/folders/1VrT9F7oFEImvW_EAMY-57454UI7LUMGT)
2. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
Proposed schema:
```
type DrugModalityAggregation {
  antibody: Int!
  enzyme: Int!
  oligonucleotide: Int!
  oligosaccharide: Int!
  protein: Int!
  smallMolecule: Int!
  other: Int!
}
type DrugTrialsByPhaseAggregation {
  phase: Int!
  trialCount: Int!
}
type TargetSummaryDrugs {
  drugCount: Int!
  drugModalities: DrugModalityAggregation!
  trialsByPhase: [DrugTrialsByPhaseAggregation!]!
}
```

**Comment by mirandaio** [comment]
@peatroot looks good!

**Comment by andrewhercules** [comment]
I've taken a look at the widget and am re-opening this issue as we need to address a few layout issues:

1. A vertical scroll-bar appears, indicating there is a content if a user scrolls down the widget, however there's no content. 
2. I like that we've started to consider the responsiveness of the widgets - and that in this case, the modalities section disappears. However, on smaller screens, there is a quite a bit of white space and we need to alter how wide the widget should be at screens less than 960px.

**Comment by andrewhercules** [comment]
@mirandaio to investigate if we can build a design pattern where all widgets on screens between 600px and 960px take up 6 columns and widgets on screens of less than 600px take up 12 columns

**Comment by andrewhercules** [comment]
Ticket closed as widget is responsive depending on the browser window
