### ISSUE TITLE
Target profile page rewrite: Create "Related Targets" summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#245]

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user, I want to know if a gene has related targets based on diseases in common

### Summary widget (showing different states depending on data)

![related-targets](https://user-images.githubusercontent.com/7490258/49020555-a328b380-f188-11e8-9ada-3664e6c528d9.png)

**[Full size version](https://drive.google.com/open?id=19ermfPOZK7lWjw5bOiCc4dKAIkQbbEr0)**
 
### Key design and interaction notes

- If we have data for a given gene, please make the widget icon, widget border, and widget text dark grey (#5A5F5F) 
- The number displayed should be the number of related targets, up to a maximum of 20 (e.g. for some targets, the number will be less than 20)
- If we do not have data for a given gene, please make widget icon, widget border, and widget text light grey (#E2DFDF) 

### Design assets

1. The widget icon is available on the [OT Core Platform Team Google Drive](https://drive.google.com/drive/folders/1OAA1xshawme_xGVfgtk4QxDOFlIEpz5X)
2. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
Proposed schema:
```
type TargetSummaryRelatedTargets {
  relatedTargetsCount: Int!
}
```

**Comment by andrewhercules** [comment]
Issue re-opened as widget [on demo site](https://platform-app.netlify.com/target/ENSG00000091831) is not based on the spec.

It was agreed that rather than listing the total number of targets related to a given target, we would have static text that indicates we are showing up to the top 20 related targets - see [above spec comment](https://github.com/opentargets/platform/issues/245#issuecomment-441660722) for more information.

**Comment by peatroot** [comment]
@andrewhercules , why not show more than 20 in the detail? I think the previous discussion assumed we would have the section currently visible in the platform (ie. with bubbles and connectors). There is no longer stopping us from displaying them all in the table with Venn diagrams we now have.

**Comment by andrewhercules** [comment]
Okay, what if instead the widget said:

_View the top 20+ targets related to TARGET based on shared disease associations_

That would give us the flexibility to show more than 20 targets - and perhaps then, in the detail view, we set the table to default to showing 20 targets per page?

**Comment by andrewhercules** [comment]
@mirandaio, can we update the widget text based on the number of related targets?

If there are more than 20 related targets, we show '20+' as the number - this will be the default for the majority of targets in the Platform:
`View the top 20+ targets related to TARGET based on shared disease associations`

If there are 20 or fewer related targets, we show that number:
`View the top # targets related to TARGET based on shared disease associations`

**Comment by andrewhercules** [comment]
Widget updated in line with spec - ticket marked as done and closed.

*Note: ticket may be re-opened should the structure of the data from the API change - back-end/data teams having preliminary discussion about reducing number of related targets to 20 to speed up the pipeline
