### ISSUE TITLE
Target profile page rewrite: Create "Related Targets" detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#246]

**Comment by deniseOme** [comment]
FYI, a user at the SME forum on 1st Nov 2018 would have liked to be able to filter the similarity widget based on TAs. e.g. just see the targets that share diseases in neoplasm.

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user, I want to know about the targets that are related to a given target, based on diseases in common

### Detail view

![related-targets](https://user-images.githubusercontent.com/7490258/49214119-d56f2680-f3bd-11e8-8bf6-8afd8233b245.png)

**[Full size version](https://drive.google.com/drive/folders/1GEltZ8Dc8oKW9V7T8NZf-Q1t5WI7c8Gr)**
 
### Key design and interaction notes

- The entire interaction will follow what is [currently available on the Platform](https://www.targetvalidation.org/target/ENSG00000091831?view=sec:related_targets), just with updated colours as per our new colour palette 

There are a few reasons for this:

1. Consistency: the [recent NAR paper](https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gky1133/5193331) focussed on this feature and included screenshots of the current workflow. 
2. Data: the data and structure returned by the API limits what we can do

### Design assets

1. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
Proposed schema (T-T only; no disease associations information):
```
type RowRelatedTarget {
  A: Target!
  B: Target!
  diseaseCountA: Int!
  diseaseCountB: Int!
  diseaseCountAAndB: Int!
  diseaseCountAOrB: Int!
}
type TargetDetailRelatedTargets {
  rows: [RowRelatedTarget!]!
}
```

**Comment by andrewhercules** [comment]
After discussing this detail view with @peatroot, I've updated the mockup - see below.

### Use case(s)

1. As a user, I want to know about the targets that are related to a given target, based on diseases in common

### Detail view

![related-targets-v2](https://user-images.githubusercontent.com/7490258/49448159-3177e780-f7d0-11e8-83d7-886ceba6da00.png)

**[Full size version](https://drive.google.com/open?id=1F3pkWUQ47vPXWIsD3Z0uJ78GenFj_j74)**
 
### Key design and interaction notes

- The data table will show a maximum of 20 rows
- The HGNC symbol in the `Related target` column will link to the respective target profile page
- The `See diseases in common` link will be a link to the batch search results page for the two targets
- The Venn diagram will show the number of diseases associated with each target and the overlap, using the same library used in the existing Platform visualisation

### Design assets

1. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by AsierGonzalez** [comment]
Hi @andrewhercules,

I like the idea but I also find a bit redundant the information in columns 2,3,4 and the venn diagram in column 5. Do you have any thoughts about this?

**Comment by ElaineMcA** [comment]
Decisions agreed from FE meeting 05Dec2018:

1. Change title to " Targets that share disease associations with ESR1"
2. Address repetition in columns by moving venn diagram to LHS
3. Update column title in table from " number of diseases in common" to say " Number of associated diseases"

**Comment by andrewhercules** [comment]
Based on the feedback from yesterday's meeting, I have update the mockup - see below.

![related-targets-v3](https://user-images.githubusercontent.com/7490258/49581780-f3eb9980-f94a-11e8-83a5-a44d570ee603.png)

**Comment by andrewhercules** [comment]
This issue is being re-opened as [the current implementation](https://platform-app.netlify.com/target/ENSG00000091831/related-targets) does not match [the agreed spec that was updated](https://github.com/opentargets/platform/issues/246#issuecomment-444842635) after the front-end/UX meeting on 5 December 2018.

In it's current implementation, the Venn diagram is not very useful at showing the overlap between the two targets. Instead, the Venn diagram should be in the same column as the link to the batch search page and, at a minimum, show the number of shared disease associations.

Also, the overall layout and style of the view will need to be updated as per [the overall detail view modal layout spec](https://github.com/opentargets/platform/issues/375).

**Comment by peatroot** [comment]
@andrewhercules , you cannot display the numbers in the Venn diagram, as the text may overlap and there is no guarantee on the size of the circles being sufficient for the text to fit.

**Comment by andrewhercules** [comment]
Instead of having the circles proportional to the number of diseases, can we instead have them a fixed size with the number in the middle with a defined (but static) overlap that can also show the number of overlapping disease associations?

Also, if we combined the `Venn diagram` and `Number of shared disease associations` into the same column, would this prevent the user from being able to sort by the number of shared disease associations?

**Comment by peatroot** [comment]
I think it would be better to keep the standard meaning of a Venn diagram, ie. that the size of the section is proportional to the set count.

With regard to sorting, there's no technical restriction, the comparator function of a given column can operate on different fields (of the row) to what is displayed in a given cell.

**Comment by andrewhercules** [comment]
While I can understand the rationale for having the size of the circles proportional to the number, it reduces the usability of the visualisation for a few reasons:

1. The target symbols overlap

![screen shot 2018-12-21 at 9 04 19 am](https://user-images.githubusercontent.com/7490258/50346496-86219f00-0500-11e9-91d5-a448a12d6344.png)

2. Similar to the existing Platform, we can't provide context about the data. A noted shortcoming of the mockup is that it doesn't explain what all three numbers mean - perhaps that could go in the description section? Nevertheless, for this detail view, we should focus on the number of shared disease associations and direct users to the batch search page for further analysis.

![screen shot 2018-12-21 at 9 14 24 am](https://user-images.githubusercontent.com/7490258/50351298-bde41300-050f-11e9-8ad5-c981aed4c6ac.png)

3. If you sort the Venn Diagram column, the colours change to blue - and some smaller circles are completely subsumed by larger ones. This makes it very difficult to distinguish between the circles.

![screen shot 2018-12-21 at 9 15 16 am](https://user-images.githubusercontent.com/7490258/50346637-f6302500-0500-11e9-8150-3c315262462d.png)

I'm still in favour of using static sized circles and adding some contextual information like the target symbol in each circle. Static sizes also mean we can fix the max height of the modal for this detail view and set the overlap area as a link to the batch search page. Also, depending on future developments with the data and pipeline, we could also drop a few of the columns identified as redundant by @AsierGonzalez.

**Comment by andrewhercules** [comment]
Ticket closed as QC work completed
