### ISSUE TITLE
Browser cache will cause issues when updating to new OT release

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#249]
Steps to reproduce:
- deploy an older release (e.g. 18.06 or older) and browse some of the gene profile pages
- deploy 18.10 on the same server and browse the same gene profile pages. They will report the wrong number of associated diseases on the top header of the page (see screenshot below). The issue is gone after clearing the browser cache.

![cache_error](https://user-images.githubusercontent.com/2900303/47921138-2ae60f80-deb4-11e8-892e-1df1635d75a2.png)

**Comment by mkarmona** [comment]
Thanks, @pieterlukasse for reporting this issue, but I am afraid I can not help you with this problem as it is related to two main things: browser caching and API cache headers. We don't maintain multiple versions online but we rather have only one deployed. Also, we use global CDN up-front our API and we flush it out and it keeps the cache expiration for us. So you may want to inject your own [cache related headers](https://stackoverflow.com/questions/35283853/how-to-force-user-to-refresh-cache) to your internal API. I hope this helps you out with this.

**Comment by pieterlukasse** [comment]
@mkarmona if the solution would indeed be to tweak the API webserver, then I think it would best be done in the [docker configuration here](https://github.com/opentargets/rest_api/tree/master/docker), right? In this case, I think we should reopen this ticket.
