### ISSUE TITLE
point to the original sources of data in profile pages

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#25]
@deniseOme commented on [Mon Aug 07 2017](https://github.com/opentargets/webapp/issues/177)

As discussed on slack (random channel), we have to add one a link to Ensembl and hyperlink Protein trees and ortologues under Gene trees.

We should be consistent across all those tabs saying where the data comes from. Sub tabs within a tab needs to be populated as well.

---

@andrewhercules commented on [Fri Jun 22 2018](https://github.com/opentargets/webapp/issues/177#issuecomment-399453592)

Flagging this for inclusion in our next mini-release. @LucaFumis, I'll create a document with the description and source link and get the team to review before we implement.

---

@LucaFumis commented on [Fri Jul 06 2018](https://github.com/opentargets/webapp/issues/177#issuecomment-403004708)

I've added the link for protein trees and ortologues under Gene trees. Will wait for the list of description + source links for the other part. Marking as "needs info".

**Comment by andrewhercules** [comment]
@LucaFumis, here's a list of [all source links](https://docs.google.com/document/d/1Ch3kYEO8ZcZn3gI1_pjMF7FHLdV1BNYrOiVy4JYJBVw/edit?usp=sharing) for the target and disease profile pages. All of the tabs on the evidence page have source links.

Can we use the same format - explanation text in grey box (if applicable) followed by source link? See below for an example.

![screen shot 2018-08-15 at 15 15 44](https://user-images.githubusercontent.com/7490258/44152736-344eebea-a09e-11e8-8023-9bdb641d3f06.png)

**Comment by LucaFumis** [comment]
Deployed in version 3.7.4
