### ISSUE TITLE
Target profile page rewrite: Create "Protein Information" detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#255]

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user, I want to know more about a gene
2. As a user, I want to see the protein sequence annotation
3 As a user, I want to see the best structure of the protein

### Detail view

![protein-information-uniprot-keywords](https://user-images.githubusercontent.com/7490258/49216781-cdb28080-f3c3-11e8-8925-aedc9972381b.png)

![protein-information-subunit](https://user-images.githubusercontent.com/7490258/49216782-cdb28080-f3c3-11e8-8fea-5b7e47257e63.png)

![protein-information-subcellular-location](https://user-images.githubusercontent.com/7490258/49216783-cdb28080-f3c3-11e8-8d9c-48de22cf5695.png)

![protein-information-protein-structure](https://user-images.githubusercontent.com/7490258/49216784-ce4b1700-f3c3-11e8-901a-636238e85507.png)

![protein-information-sequence-annotation-visualisation](https://user-images.githubusercontent.com/7490258/49216785-ce4b1700-f3c3-11e8-8dd8-ff478180c178.png)

**[Full size versions](https://drive.google.com/drive/folders/1GEltZ8Dc8oKW9V7T8NZf-Q1t5WI7c8Gr)**
 
### Key design and interaction notes

- The tab bar allows users to toggle between the five different views
- For the "Sequence annotation visualisation" tab, please display the UnitProt ProtVista view (see #262)
- For the "Protein Structure" tab, please put a placeholder - at a later date, we will integrate the PDBe viewer
- For the "Sub-cellular location" tab, please use the COMPARTMENTS viewer (see #260) from the Jensen lab to visualise the locations and provide a list of locations with hyperlinks to the relevant location page on UniProt (e.g. https://www.uniprot.org/locations/SL-0191)

### Design assets

1. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
Proposed schema:
```
type UniprotSubCellularLocation {
  id: String!
  name: String!
  description: String!
}
type UniprotKeyword {
  id: String!
  name: String!
  category: String!
}
type TargetDetailProtein {
  uniprotId: String
  pdbId: String
  keywords: [UniprotKeyword!]
  subCellularLocations: [UniprotSubCellularLocation!]
  subUnit: [String!]
}
```

**Comment by ElaineMcA** [comment]
Decisions from FE meeting 05Dec2018:

1.  Protein information - 3D structure tab from PDBe - can we use new Uniprot visualisation here?
2.  Confirmed: For the "UniProt keywords" tab, please display all keywords as buttons that link to the respective keywords page on UniProt (e.g. https://www.uniprot.org/uniprot/P03372#subcellular_location)

**Comment by andrewhercules** [comment]
Based on the research done by @peatroot - see #260 for more information - I've updated the mockup for the `Sub-cellular location` tab. It will have the same layout and interaction as the `UniProt keywords` tab in that we will display a flat list of terms as clickable buttons that direct users to the appropriate UniProt page.

![protein-information-subcellular-location](https://user-images.githubusercontent.com/7490258/50682750-c5271880-1007-11e9-8204-aa87d24dbb1e.png)

The full-size of this mockup is available on the [OT Core Platform Team Google Drive](https://drive.google.com/drive/folders/1GEltZ8Dc8oKW9V7T8NZf-Q1t5WI7c8Gr)

**Comment by andrewhercules** [comment]
Ticket closed as QC work completed
