### ISSUE TITLE
Target profile page: Protein Information tab hangs

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#263]
E.g. go to TNF profile and click on Protein Information tab:

![image](https://user-images.githubusercontent.com/2900303/47995611-2446da80-e0f6-11e8-9b0f-31b4264217ef.png)

**Comment by iandunham** [comment]
It's working fine here.  You need to give more information

![screenshot 2018-11-05 at 11 31 25](https://user-images.githubusercontent.com/1729980/47995820-83a0ec80-e0ee-11e8-97d2-2384566f7819.png)

**Comment by pieterlukasse** [comment]
This is what my browser says:

![image](https://user-images.githubusercontent.com/2900303/47997419-0a0ffb00-e0fc-11e8-9978-d7ac0b0ea0a1.png)

```
system.src.js:1041 GET https://ebi-uniprot.github.io/CDN/protvista/protvista.min.js net::ERR_BLOCKED_BY_CLIENT
W @ system.src.js:1041
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:1776
(anonymous) @ system.src.js:2801
(anonymous) @ system.src.js:3379
(anonymous) @ system.src.js:3711
(anonymous) @ system.src.js:4103
(anonymous) @ system.src.js:4568
(anonymous) @ system.src.js:4837
(anonymous) @ system.src.js:408
Promise.then (async)
s @ system.src.js:402
i @ system.src.js:388
(anonymous) @ system.src.js:544
a @ system.src.js:342
(anonymous) @ system.src.js:838
Promise.then (async)
import @ system.src.js:831
(anonymous) @ system.src.js:1800
import @ lazy-service.js:11
(anonymous) @ plugin-loader-directive.js:63
$digest @ OpenTargetsWebapp-3rdParty.js?v=3.9.0:284
$apply @ OpenTargetsWebapp-3rdParty.js?v=3.9.0:287
(anonymous) @ OpenTargetsWebapp-3rdParty.js?v=3.9.0:423
jg @ OpenTargetsWebapp-3rdParty.js?v=3.9.0:175
d @ OpenTargetsWebapp-3rdParty.js?v=3.9.0:175
OpenTargetsWebapp-3rdParty.js?v=3.9.0:260 Error: (SystemJS) XHR error loading https://ebi-uniprot.github.io/CDN/protvista/protvista.min.js
	Error: XHR error loading https://ebi-uniprot.github.io/CDN/protvista/protvista.min.js
	Error loading https://ebi-uniprot.github.io/CDN/protvista/protvista.min.js "Possibly unhandled rejection: {"originalErr":{}}"
```

**Comment by peatroot** [comment]
Following up on the `net::ERR_BLOCKED_BY_CLIENT` suggests that your client (Chrome?) might be rejecting the url through an adblocker, @pieterlukasse. Could that be the reason it's not working?

**Comment by pieterlukasse** [comment]
@peatroot yes, that could be it. I do have an adblocker.

**Comment by pieterlukasse** [comment]
@LucaFumis isn't there a way to easily detect this in the frontend and warn the user about the adblocker? I don't know how big this issue is...i.e. I don't know how many users actually browse using an adblocker. I also reported it at AdBlock now to see what they will say. Maybe it is a bug in the AdBlock software.

**Comment by LucaFumis** [comment]
Hi @pieterlukasse, for the blocked call I get a status `(blocked:other)`. 
Will try see if we can catch that. Other calls for similar plugin dependencies seem to work fine (although pulling resources from EBI directly)...

**Comment by ElaineMcA** [comment]
@pieterlukasse - closing this as issue based upon confirmation that ETL ran prior to Christmas together.

**Comment by pieterlukasse** [comment]
hi @ElaineMcA, this one is a frontend issue and is actually not related to the ETL. Therefore I think it should stay open.
