### ISSUE TITLE
OTAR042 - Tractability: version 2 front-end release

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#264]
Proposed features for the 18.12 release:

1.  Adding the [on-hover flower in the Prioritisation view](https://drive.google.com/open?id=1tsoLQA48uOgiopTKXIWD7cO_8nxrwpoY) 
*note: data is already available from the relevant API endpoint 

2.  Adding the [tractability facet](https://drive.google.com/open?id=1AQS3TcgX0zh5NEbMouD-YbrNRPX6P9bR) to both the Prioritisation and Association views
*note: facet data has already been injected into API, but still need to confirm the facet logic with the back-end team prior to front-end implementation

3.  Adding summary tractability data to the [batch search page](https://drive.google.com/open?id=1gpI-W4dkm8E2naSLv9i5GvJEX6vChkeN)
*note: data is not yet available from the `/platform/private/target (POST)` API endpoint - see issue #265

**Comment by LucaFumis** [comment]
(1) on hover flower and (3) batch search summary are done.
(2) Tractability facet is still outstanding: depends on #265

**Comment by andrewhercules** [comment]
@luca, the on-hover flower looks great!

Prior to finalising it for QA testing, can we please make a few small changes?

1. When the flower shows the data for the antibody modality, some of the petal names aren't visible due to the size of the petal (e.g. Predicted Tractable - mid to low). Can we please adjust the size of the petals to allow the full label to be seen? And on that point, can we also slightly increase the font so that all of the labels are more readable?

2. The `Modality` label for the small molecule flower lists the modality as `smallmolecule`. Can we please change this to `small molecule`? And if possible, can we also include the modality icon for both small molecule and antibody?

3. For the `View evidence` button, can we please change the text to read `View evidence for TARGET and DISEASE`? This will give users context as to what row in the table they have selected.

**Antibody:**
![on-hover-flower-antibody](https://user-images.githubusercontent.com/7490258/49368277-2a74aa80-f6e6-11e8-9323-f8e5ba68a865.png)
