### ISSUE TITLE
Pipeline refactor: Remove elasticsearch

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#266]
Remove the use of elastic search in pipeline process steps.

To be process overview with ES feeds attached.

![Screen Shot 2018-11-06 at 11.04.38.png](https://images.zenhubusercontent.com/5b1fa88baeda732edf64baaf/ab7b33bf-64e1-4d00-9023-3b59604ec665)

**Comment by afaulconbridge** [comment]
We need to review which indexes are actually used by the API, and which are used by subsequent pipeline stages

**Comment by ElaineMcA** [comment]
Decision taken to close most associated issues based upon low priority and value at this point in platform refactor.

Pending further strategic decisions on use of ES and Graph DB and plans around move to GraphQL.
