### ISSUE TITLE
Validator documentation outdated

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#270]
https://github.com/opentargets/json_schema/tree/1.2.8 states the validation should be done using `scripts/json_schema_validator.pl <your file>` while it should point to https://github.com/opentargets/validator

**Comment by MichaelaEBI** [comment]
This will be addressed for the 18.12 release. We are currently re-organising the repository wikis, updating the pipeline readme and the python validator.

**Comment by ElaineMcA** [comment]
1.2.8 is no longer supported.  Issue is resolved in master.  Any additional changes will be considered as part of JSON schema review.

**Comment by pieterlukasse** [comment]
@ElaineMcA `master` branch has no documentation README.md file anymore. Was this a mistake?
