### ISSUE TITLE
Target profile page rewrite: Decide on front-end UI framework

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#274]
In order to finalise the design specs for the dashboard, we need to decide on which front-end UI framework to use.

Below are some options we can consider, but I'm happy to consider other ones too:

* Bootstrap
* Material Design
* AntD
* Semantic UI

**Comment by mirandaio** [comment]
Team has decided to continue using [material-ui](https://material-ui.com), which was used for the genetics platform.
