### ISSUE TITLE
Update Open Targets Downloads

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#275]
Please add your thoughts and ideas below.

The Download Section on the Open Targets Website currently offers two files to download for each release:
- Association objects (2018-10, 234MB)
- Evidence objects (2018-10, 2.67Gb)

Most files that are needed to run the pipeline (for 18.12 all files) are directly accessed from a Google bucket via a link, ie., http://storage.googleapis.com/ot-releases/18.08/slapenrich-27-07-2018.json.gz

**What additional download options should we offer?**
* Very soon we will have a file in the data_pipeline that lists the links of all input files (DB downloads, gene annotation files, evidence strings) and the readme on GitHub can link to it.
* A link to a tar-archive of all gene annotation files on the website in the download section
* A link to a tar-archive of all JSON files on the website in the download section

**Overview of files associated with Open Targets:**
**_Input files:_**
1. Database downloads of UniProt, Ensembl, reactome, EFO etc.
2. Gene annotation files (tractability, chemical probes, hallmarks, cancer biomarkers)
3. Evidence strings in JSON format

**_Output files:_**
1. Data dumps (Association and Evidence objects in JSON)
2. Snapshots to re-create the platform
3. A list of all targets (UniProt Acc. & Ensembl ID) that have associations

**Comment by afaulconbridge** [comment]
Also "config file used to produce release XX.XX" should be available, and we should have links to the Docker images we have available and the instructions to run them i.e. https://docs.targetvalidation.org/faq/spin-your-own-instance#rest-api and https://docs.targetvalidation.org/faq/spin-your-own-instance#web-application

**Comment by afaulconbridge** [comment]
We're planning on having intermediate files corresponding to each elasticsearch index e.g. EFO, ECO, uniprot, etc. Should these be made available? I don't expect they would be super useful to most people, but we might as well make them available to people debugging reproducibility issues.

**Comment by MichaelaEBI** [comment]
Once the readme is updated and we clearly say in there where files for running the pipeline can be found, we probably don't have to make everything single file available on the website. I think website users will most likely be researchers who are interested in a particular data file, ie., chemical probes. Anyone who wants to run the pipeline will come to GitHub.

We can think about the intermediate files when we have them. If we have the initial files in a google bucket with clear links from the readme, that would go a long way.
