### ISSUE TITLE
OnToma - remove test dependency on external services

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#277]
The tests for OnToma depend on external services (i.e. ols, zooma, oxo, etc) and in particular specific responses from those service. These tests are not just in the `tests` directory, but also within the docstrings that are executable. 

This means that when those services update, these tests break through no changes on our part. 

We should change the tests to use mocked services that are entirely within OnToma rather than depending on live external services. This could be through containers, or mocks, or by adjusting the tests.

PS - *the tests are a good thing* _do not_ attempt to solve this issue by disabling them!

**Comment by d0choa** [comment]
Based on a recent [review of the mappings](https://docs.google.com/spreadsheets/d/1vtDB7reA8-IDcgJSqjoL5e_JkyqY8728XVYnJW-qBj4/edit#gid=0), OnToma is only used by PheWAS catalog. Most of the functionalities included in OnToma are now covered by other services (e.g. oxo, zoom, etc). We identified that OnToma was very useful back in the time but it's probably an extra hassle these days.
