### ISSUE TITLE
Address memory machien and memory requirements for val and evs with global stats

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#282]
Rewrite the way these steps are computed in order to be easily runnable by partners and by ourselves

**Comment by ElaineMcA** [comment]
Work under this ticket will also resolve https://github.com/opentargets/platform/issues/207

**Comment by afaulconbridge** [comment]
This is being done using library https://cgarciae.github.io/pypeln/

**Comment by afaulconbridge** [comment]
Work in progress on branch https://github.com/opentargets/data_pipeline/tree/mk-evs-rewrite

**Comment by mkarmona** [comment]
@afaulconbridge @MichaelaEBI @AsierGonzalez the new unified val+evs step takes far less memory and less time. Currently, there is no GLOBAL_STAT or whatsoever as that computation sounds a bit random and we would like to discuss how to address the problem if any.
![captura de pantalla -2018-11-19 13-29-40](https://user-images.githubusercontent.com/5394232/48710279-b1faed80-ebff-11e8-80b8-75d7074351be.png)

So, now you will be able to use new parameters to run this step
```
--val --enable-fs --output-path="." --num-workers=16 --num-writers=8
# if you don't use --enable-fs then elasticsearch will be used to generate validated and scored ones
```
