### ISSUE TITLE
Fix evidence string prefixing at source

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#283]
In the ChEMBL evidence strings, the `target.activity` field is something like http://identifiers.org/cttv.activity/drug_positive_modulator, but this is mapped to just `drug_positive_modulator` by the `data_pipeline` (see [here](https://github.com/opentargets/data_pipeline/blob/950cd1a136edbda1ef15db9a09b14aafbbbef08d/mrtarget/modules/EvidenceString.py#L314)).

It would be better to ask providers to remove this and simplify our pipeline. There are several other instances in the `data_pipeline` that can be found by searching for `[-1]`.

**Comment by afaulconbridge** [comment]
This also applies to other evidence sources. In a perfect world, we should use real ontology terms for these - not an ad-hoc controlled vocabulary of strings.

**Comment by MichaelaEBI** [comment]
An overview of these terms can be found [here](https://github.com/opentargets/input_data_format/blob/master/json_schema/cttv_uris_namespaces.md#cttv-biological-activity-in-disease-ontology).

It makes sense to use a controlled vocabulary. It might make sense to use existing ontology terms if we can and create the missing terms. There is a lot on for 18.12 already, so this will probably take a backseat until early next year.
