### ISSUE TITLE
Simplify ChEMBL evidence strings

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#285]
The evidence strings we receive from ChEMBL contain several unused fields. These should never be put into the data pipeline. The unused fields should be removed once the validation doesn't depend on `unique_association_fields` (which is a blocker raised by @afaulconbridge).

Also, the evidence strings contain several dead or useless url references, such as http://identifiers.org/cttv.target/protein_complex, https://github.com/CTTV/association_score_methods/blob/master/CTTV008_ChEMBL/description.md.

The following categories are with respect to the `webapp`.

## Unused
```
unique_association_fields.chembl_targets
unique_association_fields.chembl_molecules
unique_association_fields.chembl_targets
unique_association_fields.efo_classification
drug.withdrawn_year
drug.withdrawn_reason
drug.withdrawn_country
evidence.drug2clinic.resource_score.method
evidence.drug2clinic.evidence_codes
evidence.drug2clinic.is_associated
evidence.drug2clinic.date_asserted
evidence.drug2clinic.resource_score.type
evidence.drug2clinic.provenance_type
evidence.target2drug.<* except urls>
literature.references
validated_against_schema_version
target.complex_members
target.complex_type
target.target_type
target.target_name
unique_association_fields.unique_id
unique_association_fields.url
```

## Used
```
sourceID
drug.molecule_name
drug.molecule_type
drug.max_phase_for_all_diseases
drug.id
evidence.drug2clinic.status
evidence.drug2clinic.max_phase_for_disease
evidence.drug2clinic.urls
evidence.drug2clinic.resource_score.value
evidence.target2drug.urls
evidence.target2drug.literature.references
disease.id
target.activity
target.id
target.target_class
access_level
```

## Unknown/difficult to check
```
type
```

**Comment by AsierGonzalez** [comment]
Do any of the urls actually exist? I also had a quick look into this and what @MichaelaEBI told me was that they don't exist but that they need a url for some reason...

**Comment by peatroot** [comment]
Not sure @AsierGonzalez, but this issue may also be relevant: https://github.com/opentargets/platform/issues/283.

**Comment by MichaelaEBI** [comment]
The URLs are part of an Open Targets Ontology which I am trying to document because we will need to add new terms for the SysBio data. I do not know why the term were never actually created on identifier.org, but I am working on this.

Regarding the fields, there are some fields that are relevant to the data providers, other will be useful if we have to trouble shoot something (date_asserted for example) and some will be useful in the future (the drug.withdrawn fields for example).

As I said in our discussion earlier, it is probably best to define which fields the front end uses and to ensure that the API only returns those fields.

**Comment by peatroot** [comment]
Thanks @MichaelaEBI.

Having URLs somewhere is no problem, but they are just annoying from a front-end perspective, since we only want the term and therefore have to do lots of string splitting. I agree that the list of options should be documented somewhere, but the API should not return URLs where they are not useful.

The fields above (used/unused) came from a scan of the webapp codebase, so the list is just there for reference in case some of the unused fields can be removed.

**Comment by d0choa** [comment]
This can be relevant for @mkarmona in order to define the contract in the API
