### ISSUE TITLE
Review ChEMBL evidence strings (eg., duplicate literature references)

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#286]
1. ChEMBL evidence strings appear to contain the same content under keys `literature.references` and `evidence.target2drug.provenance_type.literature.references`. The webapp uses evidence.target2drug.provenance_type.literature.references in the case of ChEMBL evidence strings.
- [x] Investigate whether 'literature' is duplicated in ChEMBL evidence strings.
2. 'max_phase_for_disease' in ChEMBL evidence strings is actually 'clinical_trial_phase'
- [x] ChEMBL will rename 'max_phase_for_disease' to 'clinical_trial_phase' once we change the JSON schema `json_schema/opentargets.json`:
```
"max_phase_for_disease": {
                  "type": "object",
                  "$ref": "#/definitions/diseasephase"
                },
```
```
 "required": [
                "resource_score",
                "provenance_type",
                "is_associated",
                "date_asserted",
                "evidence_codes",
                "max_phase_for_disease"
              ]
```

**Comment by MichaelaEBI** [comment]
Only 252,375 of 465,039 ChEMBL evidence strings contain a literature field and not all of these have the literature.references content repeated in target2drug.provenance_type.literature.references. I will investigate further.

**Comment by peatroot** [comment]
The `webapp` uses `evidence.target2drug.literature.references` in the case of ChEMBL evidence strings.

**Comment by MichaelaEBI** [comment]
@afaulconbridge - ChEMBL is trying to change the 'target_type' field to contain the actual target type as defined in the ticket above but they are getting the validation error shown below. It it easy to allow the target type terms listed above?
 
```
$VAR1 = bless( {
                 'message' => 'allOf failed: allOf failed: Not in enum list: http://identifiers.org/cttv.target/gene_allele, http://identifiers.org/cttv.target/gene_evidence, http://identifiers.org/cttv.target/gene_in_LD_region, http://identifiers.org/cttv.target/gene_in_epigenetic_regulation_complex, http://identifiers.org/cttv.target/gene_variant, http://identifiers.org/cttv.target/pro_protein, http://identifiers.org/cttv.target/protein_evidence, http://identifiers.org/cttv.target/transcript_evidence, http://identifiers.org/cttv.target/transcript_isoform, http://identifiers.org/cttv.target/protein_isoform, http://identifiers.org/cttv.target/gene_or_protein_or_transcript.',
                 'path' => '/'
               }, 'JSON::Validator::Error' );
```
