### ISSUE TITLE
move tracker code to separate file to allow deploy specific tracker code

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#29]
@elipapa commented on [Mon Jun 26 2017](https://github.com/opentargets/webapp/issues/145)

move the tracker code to its own js file would make it easier to mount it as a separate file when deploying. eg. `docker run -v /path/to/local/piwik/token:/app/external/piwik/js webapp`

kind of the same way we do for certificates, but probably better in a separate stand-alone directory

---

@andrewhercules commented on [Fri Aug 10 2018](https://github.com/opentargets/webapp/issues/145#issuecomment-412128390)

Triage notes:

- Piwik code moved to its own file in [app/piwik.js](https://github.com/opentargets/webapp/tree/master/app)
- Can do the same with the Google Analytics code currently found on [lines 337 to 354 of app/index-tmpl.html](https://github.com/opentargets/webapp/blob/master/app/index-tmpl.html#L337)

**Comment by LucaFumis** [comment]
Deployed in version 3.7.4
