### ISSUE TITLE
Remove data_release field in elasticsearch

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#297]
Currently document have a "data-release" field embedded within every document. This is wasteful, since it doesn't matter and is embedded in the index name anyway. It is harmful to renaming indexes or moving documents.

When this is removed, we need to double check that it doesn't cause any problems for downstream e.g. for API or UI

**Comment by mkarmona** [comment]
@afaulconbridge addressed [here PR 364](https://github.com/opentargets/data_pipeline/pull/364)
