### ISSUE TITLE
"start lost" variants missing from variants definition

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#298]
Following a user support email re. start lost variants (not listed in our variants page: https://www.targetvalidation.org/variants), I have looked for some examples of this consequence term in Ensembl and found these ones:

rs74315284 (https://www.targetvalidation.org/evidence/ENSG00000162399/Orphanet_112?view=sec:genetic_association)
rs74315365 (https://www.targetvalidation.org/evidence/ENSG00000135828/Orphanet_1331?view=sec:genetic_association)
rs28942098 (https://www.targetvalidation.org/evidence/ENSG00000134371/EFO_0005754?view=sec:genetic_association)

Actions:
1) update the list of consequence terms in the variants page 

p.s. Note that these all get the missense variants in the ClinVar records. Is it worth investigating why? Shall we contact ClinVar to find out why they not have it as start lost?

**Comment by ElaineMcA** [comment]
@MichaelaEBI can you please give your thoughts on this?  Tagged as EVA related for moment.  Happy to help with any actions...

**Comment by deniseOme** [comment]
@ElaineMcA The list of consequence terms in the variants page has now been updated here:
https://github.com/opentargets/webapp/blob/master/app/src/pages/static/variants.html

**Comment by deniseOme** [comment]
Email sent to ClinVar. Awaiting response.

<img width="844" alt="screen shot 2019-01-02 at 12 51 49" src="https://user-images.githubusercontent.com/6472381/50592800-9422d880-0e8d-11e9-816d-0b4bad3bfb5c.png">

**Comment by deniseOme** [comment]
ClinVar may incorporate the consequence "start lost". So if one (user/developer) wonders why there is inconsistency between our annotation of this variant and ClinVar's, here it is:

![screen shot 2019-01-09 at 09 47 34](https://user-images.githubusercontent.com/6472381/51171890-ef9b9000-18a9-11e9-8fc9-40d174baab41.png)
