### ISSUE TITLE
Target profile page rewrite: Implement the pathways widget

### ISSUE THREAD

**Issue by mirandaio** [opentargets/platform#302]

**Comment by peatroot** [comment]
The summary currently just displays the number of pathways (from Reactome). It might be preferable to show a present/absent view of the top level pathways in the summary.

<img width="440" alt="screenshot 2018-11-19 at 13 13 27" src="https://user-images.githubusercontent.com/7376272/49019410-bb4b0380-f185-11e8-9ac0-6c232b320dfb.png">

**Comment by mirandaio** [comment]
Duplicate https://github.com/opentargets/platform/issues/251
