### ISSUE TITLE
Add  Neuro Behavior Ontology as a valid source of ontology terms

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#32]
@gkos-bio commented on [Mon Jan 16 2017](https://github.com/opentargets/json_schema/issues/5)

All the neuro behaviour ontology terms imported in HP should be accepted during the validation step.
For instance, http://purl.obolibrary.org/obo/NBO_0000244 is the IRI that represents 'pathological anxiety'

**Comment by ElaineMcA** [comment]
@afaulconbridge - please close if covered already under your other Ontology related tickets.

**Comment by afaulconbridge** [comment]
The issue with this is firstly that it's not permitted under the JSON schema, so that needs to be updated before anything further can be done.

**Comment by ElaineMcA** [comment]
Separate to scope for EFO3.   Work and value for partners requires more extensive analysis before proceeding.
