### ISSUE TITLE
Remove evidence-data index

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#324]
We should evaluate usage of this index, and move to generating a file that can be read within `data_pipeline` and separately loaded into elasticsearch if necessary for `rest_api`

**Comment by afaulconbridge** [comment]
This is used by the API

**Comment by afaulconbridge** [comment]
As part of opentargets/data_pipeline#364 this can be written to file. We still need to investigate how the association step of the data pipeline read it (from the file or from elasticsearch) and how the API reads it from Elasticsearch, and if any further changes are required.

**Comment by ElaineMcA** [comment]
Decision taken to close based on low priority and value at this point in platform refactor.
