### ISSUE TITLE
Remove external API use: gene plugin HGNC

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#326]
HGNC plugin calls:

http://ftp.ebi.ac.uk:80/pub/databases/genenames/hcop/human_all_hcop_sixteen_column.txt.gz

**Comment by Docproc** [comment]
I think this is already done.

https://github.com/opentargets/data_pipeline/blob/master/mrtarget/plugins/gene/hgnc.py downloads from the URL referenced by `data_config.hgnc_complete_set` which is already dealt with correctly in the config file:

```
hgnc-complete-set: https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/hgnc_complete_set-2019-04-10.json
```

Note that the original description of this issue refers to orthologs which appears to also already be dealt with:

```
hgnc-orthologs: https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/human_all_hcop_sixteen_column-2019-04-10.txt.gz
```
