### ISSUE TITLE
Remove external API use: reactome

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#327]
Reactome step calls :
- http://www.reactome.org/download/current/ReactomePathways.txt
- http://www.reactome.org/download/current/ReactomePathwaysRelation.txt

**Comment by afaulconbridge** [comment]
Partially related to opentargets/platform#371

**Comment by afaulconbridge** [comment]
This will need some coordination with opentargets/platform#146 harmonize user configuration

**Comment by cmalangone** [comment]
Closed issue with PR /opentarget/data_pipeline#327

**Comment by cmalangone** [comment]
Closed issue with PR /opentargets/data_pipeline#327
