### ISSUE TITLE
Remove external API use: gene plugin Chembl

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#329]
Chembl plugin to Gene step and Search step calls:
- https://www.ebi.ac.uk/chembl/api/

**Comment by cmalangone** [comment]
The platform-input-support downloads ChEMBL REST API files in zip format. 
The files are stored in a google bucket.
The data config file will use the bucket as input for the ChEMBL data.

**Comment by afaulconbridge** [comment]
This should be solved by PR opentargets/data_pipeline#463
