### ISSUE TITLE
Validator page needs a description

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#332]
We will link out to https://pypi.org/project/opentargets-validator/ from Glenn's blog post.

It'd be really helpful to add a description to this page.

**Comment by ElaineMcA** [comment]
@deniseOme can you advise if you have what you need for description and can close?  Thanks.

**Comment by deniseOme** [comment]
I have suggested a text (https://github.com/opentargets/validator/pull/13), which has been merged into master.

The description is not live though. 
@ElaineMcA, can we close this issue when the change is actually in place? 

<img width="1160" alt="screen shot 2019-01-04 at 08 36 58" src="https://user-images.githubusercontent.com/6472381/50679601-06193000-0ffc-11e9-9875-4783e105bbe6.png">

**Comment by afaulconbridge** [comment]
This will happen automatically on the next 0.5.0 release.

**Comment by deniseOme** [comment]
All good. Thanks @ElaineMcA for the reminder.
