### ISSUE TITLE
Target profile page rewrite: Create "Chemical Probes" summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#333]

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user, I want to know if there are any chemical probes that have been developed for a given gene

### Summary widget (showing different states depending on data)

![chemical-probes](https://user-images.githubusercontent.com/7490258/49021638-074c7700-f18b-11e8-8390-3211a8cd8faa.png)

**[Full size version](https://drive.google.com/open?id=1eYS9nIExB9MjPdpdr_LcDnKaNPYRYkWK)**
 
### Key design and interaction notes

- Please make the checkmark [the check icon from FontAwesome](https://fontawesome.com/icons/check?style=solid) (e.g. `<i class="fas fa-check"></i>`)
- Please make the X [the times icon from FontAwesome](https://fontawesome.com/icons/times?style=solid) (e.g. `<i class="fas fa-times"></i>`)
- If we have any data for a given gene, please make the widget icon, widget border, and widget text dark grey (#5A5F5F)
- If we have specific data for a given gene (e.g. probe data from Chemical Probes Portal), please make the background of the box purple (#7B196A) and the checkmark white (#ffffff) and likewise, if we don't have the specific data, please make the background of the box white and the X icon light grey (#E2DFDF)
- If we do not have data for a given gene, please make widget icon, widget border, and widget text light grey (#E2DFDF)

### Design assets

1. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
@andrewhercules, can we drop the source list beneath the table. It breaks the pattern across widgets, but the information is duplicated in the above design.

**Comment by andrewhercules** [comment]
I know it's not ideal given that it's a direct duplication of content, but I'd suggest that we keep the source list to promote consistency. In the case of this widget, I've flagged it as one that I'd like to explore a bit further once we have the drug index and updated tractability data - perhaps it will no longer be needed?

@peatroot, that being said, if there's a way to configure the widgets to show/hide the source - and perhaps for our partners whether the source is internal or external - that would be useful for future widgets and future planning. What do you think?

**Comment by peatroot** [comment]
Ok, let's leave the sources in. We can consider adding a toggle, but I'd be in favour of only supporting toggles like that in the configuration if partners have actually asked for it. The current configuration in the `webapp` is quite extensive, but we don't really know how much of it is used.

**Comment by peatroot** [comment]
Proposed schema:
```
type TargetSummaryChemicalProbes {
  hasStructuralGenomicsConsortium: Boolean!
  hasChemicalProbesPortal: Boolean!
  hasOpenScienceProbes: Boolean!
  hasProbeMiner: Boolean!
}
```

**Comment by andrewhercules** [comment]
I'm re-opening this as we will need to find a way around the content overflow issue. What exactly is the problem caused by smaller screen resolutions? At at what resolution is the issue seen?

**Comment by peatroot** [comment]
@andrewhercules , at 1295px width, the text *Structural Genomics Consortium* wraps, making the checkbox grid take up the full widget, with reasonable margins. The text *Data on potential chemical probes available from* might just fit if we can avoid this happening (eg. writing *SGC* instead), but it looks a bit cramped. I could also reduce the font size a bit?

**Comment by peatroot** [comment]
![image](https://user-images.githubusercontent.com/7376272/49963442-e8cad780-ff0f-11e8-8a94-4955bd078ba4.png)
(taken at 1295px width)

**Comment by andrewhercules** [comment]
Noted about the responsiveness issue for the text - we can possibly address in a subsequent iteration.

@MichaelaEBI, the amended widget view above, is that okay? The detail view will still provide further information about the individual probes.

**Comment by MichaelaEBI** [comment]
It looks great. The "Data on potential chemical probes" is not ideal anyway since the first three should be high quality probes. Only Probe Miner (with a space!) provides information on potential probes.

If it helps we could replace "Structural Genomics Consortium" with "SGC Chemical Probes" since that is what the section on their website is called.

**Comment by andrewhercules** [comment]
@MichaelaEBI, is it okay if we just use SGC for now, to compensate for the overflow and responsiveness issue identified above?

**Comment by MichaelaEBI** [comment]
SGC is fine, but "SGC Chemical Probes" is shorter than "Chemical Probes Portal" so should not cause any problem, right?

**Comment by andrewhercules** [comment]
True, my only concern is that we'd have:

SGC, SGC Chemical Probes ...

Since we're just listing sources - and not providing any links - I'm not that concerned about the repetition. But just want to make sure it's scientifically correct :)

**Comment by MichaelaEBI** [comment]
Chemical Probes Portal, Open Science Probes and Probe Miner (note the space in Probe Miner) are also repeated. I guess it doesn't really matter what we use, we should just be consistent, ie., use the same wording in the table and below. Also, we are using an acronym for the Structural Genomics Consortium but not the other ones.

**Comment by andrewhercules** [comment]
Okay, so let's use the following for the summary widget table, the summary widget sources, and in the detail view data table:

SGC
Chemical Probes Portal
Open Science Probes
Probe Miner

**Comment by mirandaio** [comment]
@andrewhercules text has been updated (SGC, space in Probe Miner). Can you check this issue here https://platform-app.netlify.com/target/ENSG00000091831 and see if we can close this? Thanks!

**Comment by andrewhercules** [comment]
Looks good @mirandaio. I've updated the status to "Done" and will close this ticket.
