### ISSUE TITLE
Target profile page rewrite: Create target information block

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#335]

**Comment by andrewhercules** [comment]
Looks good! :-)

Can we please remove the icon in the `View TARGET profile in Open Targets Genetics` button? Upon review, it's repetitive as the same icon is used in the header beside the gene symbol.

**Comment by mirandaio** [comment]
@andrewhercules Done 👍

**Comment by andrewhercules** [comment]
Perfect - ticket closed as work on this component is done
