### ISSUE TITLE
Remove global_stats from pipeline

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#338]
Following our assessment of global_stats (summarised [here](https://docs.google.com/document/d/1oNS4ZrSExVweD39Je7LC8PgPPu2ImlzKON-7U3CCJVc/edit)) the following three items will be implemented for 18.12: 
- [x] Remove global_stats from the pipeline (which will result in an additional 0.5 mio associations)
- [x] Change the weight factor for atlas data from 0.5 to 0.2
- [x] Do not propagate atlas data (253,061 indirect associations have a single evidence string from atlas - with 2, 3, … 10 evidence strings from atlas there are 75982, 28045, 15048, 8455, 5835, 3464, 2695, 1982, 1520 = 143,026 additional associations)

**Comment by mkarmona** [comment]
see #opentargets/data_pipeline/pull/377

**Comment by afaulconbridge** [comment]
We probably shouldn't close issues until the PR has been merged to master.
