### ISSUE TITLE
Consider removing PDBe structure information

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#342]
The `webapp` currently shows the 3d protein structure on the target profile page. On opening the section, the front-end code makes a call to `https://www.ebi.ac.uk/pdbe/api/mappings/best_structures/<uniprotId>`, which gives the PDB structure identifiers, sorted by descending `coverage`. We then display the first one.

The REST API response for `/private/target/<ensgId>` also contains a `pdb` field, which appears to be unused in the front-end. This contains the same PDB structure identifiers, but the are sorted alphabetically by PDB identifier and do not contain the coverage, *so the best structure cannot be inferred*. It might therefore simplify the `data_pipeline` to remove this, unless it's used internally somehow?

**Comment by ElaineMcA** [comment]
Closing as I believe that data feed discussions from OTAR2-048 project will encompass this.  @MichaelaEBI please re-open if appropriate based on upcoming project meetings.
