### ISSUE TITLE
Target profile page rewrite: Create collapsed and sticky target information block

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#345]

**Comment by andrewhercules** [comment]
### Use case(s)

1. As a user that has scrolled down the dashboard on the target profile page, I want to see basic information about the target to ensure I am on the correct page - this information includes:

- HGNC symbol
- Full gene name
- Ensembl ID
- UniProt ID
- Link to the gene profile page on the Open Targets Genetics Portal

*Note: this use case is based on the analytics reports from 1 September to 30 November 2018 which show that more than 25% of our traffic comes from browsers where the screen size is 768px or less. It is also based on the fact that, in production, we are likely to have at least 4 rows of widgets to accommodate all of the existing accordion tabs on the target profile page*

### Component design

![sticky-target-info-block-on-scroll-down](https://user-images.githubusercontent.com/7490258/49376625-b0e9b600-f6ff-11e8-814d-a05e4112b1a8.png)

**[Full size version](https://drive.google.com/open?id=1msnmOOJ884JvUwmY32WZ5f9hoE17e1ie)**
 
### Key design and interaction notes

- Once a user has scrolled down the page and the target description and synonyms are no longer in view, please collapse and hide the header component, the target description blog, and the target synonym block
- Once the blocks have been collapsed, the target-info-block should be no more than 130px in height with only the following information:
    - Target icon
    - HGNC symbol
    - Full target name
    - Ensembl and UniProt IDs
    - Link to gene page on OT Genetics
    - Tabs allowing user to toggle between Associations View and Target Profile Overview*
- If the user then scrolls back up the page to a point where the target description or synonyms are in the browser window, please expand and show these blocks
- One of the inspirations for this feature is the interaction pattern found on [the Carter digital agency website](https://www.carterdigital.com.au/)

_*Note: to maximise the space available for widgets and target data, we can consider removing the tabs from the collapsed information block_

### Design assets

1. The icons are available on the [OT Core Platform Team Google Drive](https://drive.google.com/drive/folders/10gRFd-293HSra-p4czjQTWkYQQJAgHew)
2. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by d0choa** [comment]
@andrewhercules could you evaluate if any of this still makes sense with the new design. I would advice against a sticky information block as it's some valuable space that you can not take back. Space might be valuable in small screens.

**Comment by andrewhercules** [comment]
@d0choa, I agree that it does take up valuable space which could be better used by showing actual content.

If we find that users are uncertain about the context of the page they are on (e.g. what target or disease?), perhaps we can alter the menu box to include contextual information. But I would recommend that we explore this once the majority of the pages are complete to see if its a scalable and sustainable solution, particularly for the evidence pages.
