### ISSUE TITLE
Allow search by pathway

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#353]
It would be a useful feature to be able to search by a pathway description. The action taken on successful search needs discussion, but we might direct the user to the batch search for all targets within the pathway.

Example: User types `Cell-Cell communication` or `R-HSA-1500931`.

This would require some work on the `rest_api`.

**Comment by andrewhercules** [comment]
This issue has been closed as it has been captured on [the Master Feature Prioritisation worksheet](https://docs.google.com/spreadsheets/d/1jZMKv6fDum6aEOqernfuwSv__f8CBFK6PZoRo9m0mWE/edit#gid=0) available on the team's Google Drive.

CC: @d0choa
