### ISSUE TITLE
Improve ontology mapping

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#357]
The ontology mapping done by OnToma looks a bit clunky for PheWAS. In some cases the mapped term is either too generic or more specific than the actual term (e.g. Primary/intrinsic cardiomyopathies -> dilated cardiomyopathy - [EFO_0000407](http://www.ebi.ac.uk/efo/EFO_0000407)). In some other cases, the mapped term is not even a disease (Disorders of penis -> penis - [UBERON_0000989](http://purl.obolibrary.org/obo/UBERON_0000989))

@MichaelaEBI and I have been curating the mappings for PheWAS but this issue may affect other data sources. According to @afaulconbridge, what OnToma does is call other services like ZOOMA and OLS so there seems to be little we can do. He suggests we feed the ontologies group back with the curated PheWAS mappings to see if they can improve them. Perhaps one request may me to be able to map terms to certain ontologies or entities, so that we would be sure that we get diseases and not an organ or a measurement (e.g. [Alzheimer's disease biomarker measurement](http://www.ebi.ac.uk/efo/EFO_0006514)).

**Comment by iandunham** [comment]
Talk to @gkos-bio about this. The idea is that we supply resolved mapping back to SPOT who can then  update the matching through ZOOMA.

On the disease only mapping this is ideal when the term is a disease, but in a substantial number of cases the term represents a measurement e.g. high blood pressure is  part of blood pressure measurement so we still want to be able to get these.

In the web version of ZOOMA you can restrict to certain ontologies - maybe you can do that through the API call as well. But you might want to implement this as first search disease ontologies, and then phenotypes and measurements

**Comment by AsierGonzalez** [comment]
In PheWAS it's quite common to entries that in reality are combinations of multiple diseases, e.g. "Cystitis and urethritis", ''Inflammatory bowel disease and other gastroenteritis and colitis" or "Other disorders of metabolic, endocrine, immunity disorders".

These combinations are very challenging to resolve and I would say that only of the three cases above has a simple solution; namely, when all the diseases have a common parent in the ontology the term could be mapped to it: ''Inflammatory bowel disease and other gastroenteritis and colitis" -> "digestive system disease".

I cannot think of a similar approach to apply to the other two situations. I would argue that in cases like the third one, which are too generic, are left unmapped, but what about to closely related diseases that do not share a common parent? Interestingly, "Cystitis and urethritis" was mapped to [_cystitis_]( http://www.ebi.ac.uk/efo/EFO_1000025) in 2017 and [_urethritis_](http://www.ebi.ac.uk/efo/EFO_0003878) in 2017.

Do you have any suggestions?

**Comment by iandunham** [comment]
The SPOT team has some ways to deal with this that I don't think that we are using properly - combinations of ontology terms. This would also apply to measurements or terms like response to drug. We need to discuss with them what the way is to move forward is. Mapping the term to a parent term is OK but loses resolution.

**Comment by AsierGonzalez** [comment]
Another question for the SPOT team: Are there any differences between "abdominal pain" [(HP_0002027)](http://purl.obolibrary.org/obo/HP_0002027) and "pain in the abdomen" [(EFO_0003766)]( http://www.ebi.ac.uk/efo/EFO_0003766) apart from one coming from HPO and the other from EFO?

Both terms have the same hierarchy in EFO:

![screenshot 2018-12-07 at 09 41 22](https://user-images.githubusercontent.com/11410715/49640559-d596a400-fa05-11e8-9f88-536353087f7c.jpg)

**Comment by d0choa** [comment]
This task is covered by #420
