### ISSUE TITLE
Non-validation pipeline steps wrongly log ‘setting schema version string to master’

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#363]
When I run the pipeline via the makefile and override the `SCHEMA_VERSION` variable, all steps of the data loading pipeline that do not have `--val` as the command flag still log that it's being set to the default `master`.

Can I safely assume that these messages are incorrect, and the steps are not actually doing anything to the schema version used in this pipeline run?

**Comment by afaulconbridge** [comment]
Your assumption is correct. The `SCHEMA_VERSION` is only used in the `--val` step so this message can be safely ignored elsewhere. This message will go away, and configuration in general improved, as part of opentargets/platform#146
