### ISSUE TITLE
Additional evidence for Animal Models

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#37]
@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/evidence_datasource_parsers/issues/5)

Currently we have the mouse mutations from MGI in the Mouse phenotypes section of the Target profile page. This includes at least 400 entries from Mutagenetix
https://mutagenetix.utsouthwestern.edu/

We could increase mapping of mouse phenotypes to human disease to give extra evidence  - @gkos-bio to look at whether Phenodigm process covers everything in MGI. 

cc: @iandunham

**Comment by AsierGonzalez** [comment]
Bringing data in from other model organisms (zebrafish, rat, pig) should also be studied.

**Comment by d0choa** [comment]
Closing as not actionable. Animal models to be reviewed in the future
