### ISSUE TITLE
Target profile page rewrite: Overall detail view modal layout

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#375]

**Comment by andrewhercules** [comment]
Full spec will be uploaded tomorrow

**Comment by andrewhercules** [comment]
### Detail view

For all detail views, the general layout will fall into two categories - those that are just data tables (e.g. Drugs) and those that have tabs (e.g. Pathways, Protein Information)

#### Data table

![general-layout-data-table](https://user-images.githubusercontent.com/7490258/49999503-ef4c6400-ff8e-11e8-8fe5-3a3ad94f0f13.png)

#### Tabs

![general-layout-tabs](https://user-images.githubusercontent.com/7490258/49999504-ef4c6400-ff8e-11e8-9b7a-ad6d61d73cc1.png)

### Key interaction and design considerations

1. The HGNC symbol and widget name should be at the top
2. Below the gene symbol and widget name is a description of the data found in the detail view. For now, please use the descriptions found in the respective mockups. If a description is missing, please use the description currently found in the Platform.
3. Below the description should be a list of the source(s) of the data along with links to their respective websites
4. In the top-right corner, please create a close button that is an X inside of a circle with the word "Close" underneath
5. to be updated ...

### Design assets

1. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by LucaFumis** [comment]
This should be mostly done as per PR https://github.com/opentargets/platform-app/pull/26 addressing the close button and modal headers consistency. Can be reviewed after the holidays.

**Comment by ElaineMcA** [comment]
@ review for pull request.

Protein info and pathways - detail views have the tabs (image 2 above).  Please make sure that these are included in the views via the appropriate tickets.

**Comment by andrewhercules** [comment]
Ticket to be closed as modal layout updated as per spec
