### ISSUE TITLE
Rewrite gene step to run plugins per-gene

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#376]
Currently, the gene step is structured so that the plugins are run in sequence, and each plugin handles all genes before the next plugin starts. This curtails the performance and degree of parallelism that is possible.

It should be rewritten so that each gene is run independently through all of the pipelines. Ideally, as part of opentargets/platform#362 each plugin should be a separate process (or processes) joined together by pypeln.

**Comment by d0choa** [comment]
The gene step rewrite is in the agenda. We'll factor in this feedback at the appropriate time.
