### ISSUE TITLE
Target profile page rewrite: Filters and search bar for data tables on detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#377]

**Comment by andrewhercules** [comment]
The specs for the data tables in the detail view show both the filtering widgets from DC.js and a search bar. Can we please investigate if we can make both work together?

If not, at the next Integration Day, I can run some quick usability tests to find out if users prefer the filter visualisations or ability to search a data table.

**Comment by mirandaio** [comment]
@andrewhercules Yes, we can integrate the filtering from the dropdown at the top of each column with the filtering from DC. We have a working version of how that works here https://platform-app.netlify.com/target/ENSG00000091831/cancer-biomarkers

**Comment by andrewhercules** [comment]
Looks good - thanks :)

Can we also allow users to unselect a filter option? So for example, in the screenshot below, I filtered for rows where the biomarker is `ESR1:Y537S`.

![screen shot 2019-02-01 at 11 00 05](https://user-images.githubusercontent.com/7490258/52119328-a3be4a00-2610-11e9-9db1-86bb916f3d2a.png)

However, I cannot unselect this filter option - which users can currently do in the Platform.

![screen shot 2019-02-01 at 11 04 41](https://user-images.githubusercontent.com/7490258/52119550-4d054000-2611-11e9-8103-a6974cc1d2e4.png)

**Comment by LucaFumis** [comment]
I'll add this to the drugs details table too.

**Comment by andrewhercules** [comment]
Ticket closed as QC work completed.

_Note: this ticket will be referenced in future work on developing a design pattern library for all Open Targets websites and services_
