### ISSUE TITLE
Remove external API use: gene plugin mousephenotypes

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#379]
mouse phenotypes gene plugin calls:

- mouse-phenotypes-orthology: http://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt
- mouse-phenotypes-report: http://www.informatics.jax.org/downloads/reports/MGI_PhenoGenoMP.rpt

This will need some coordination with opentargets/platform#146 harmonize user configuration

**Comment by Docproc** [comment]
I think this has already been done - the latest (19.04) data.yml file has

```
mouse-phenotypes-orthology: https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/HMD_HumanPhenotype-2019-04-10.rpt
mouse-phenotypes-report: https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/MGI_PhenoGenoMP-2019-04-10.rpt
```

which pulls from the OT Google bucket, not the informatics.jax URLs mentioned in the issue description.
