### ISSUE TITLE
enrich in batch search based on pathways not in reactome

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#380]
@elipapa commented on [Tue Jan 02 2018](https://github.com/opentargets/roadmap/issues/110)

## Description
* [ ] **WHY - What is the problem this feature would answer?**  

Private deployments of the platform usually leverage other pathway resources. 
It would be useful for the enrichment analysis to leverage that data as well.

* [ ] **HOW are we going to solve the problem?**  

Perhaps we could make gene sets or pathway as a separate entity.

* [ ] **WHAT would this look like?**

**Comment by andrewhercules** [comment]
This issue has been closed as it has been captured on [the Master Feature Prioritisation worksheet](https://docs.google.com/spreadsheets/d/1jZMKv6fDum6aEOqernfuwSv__f8CBFK6PZoRo9m0mWE/edit#gid=0) available on the team's Google Drive.

CC: @d0choa

**Comment by andrewhercules** [comment]
This issue has been closed as it has been captured on [the Master Feature Prioritisation worksheet](https://docs.google.com/spreadsheets/d/1jZMKv6fDum6aEOqernfuwSv__f8CBFK6PZoRo9m0mWE/edit#gid=0) available on the team's Google Drive.

CC: @d0choa
