### ISSUE TITLE
Improve Expression section on Summary page of batch search

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#381]
@nikiforosk commented on [Mon Jan 16 2017](https://github.com/opentargets/roadmap/issues/43)

# What problem does this feature solve?

While testing the first iteration of batch search (pull request #16) [participants gave the following feedback about the Expression section](https://docs.google.com/document/d/1ZDPWqSHhw4Kl_cOqBkTTaWNOG5VikrOLapeA2NCGz5w/edit#heading=h.1gh737vji8or):

- Say where these data come from (I think @emepyc has done this already).
- Display target names: Currently only the first 2-3 letters are shown.
- Show more targets (rows) by default: Several participants changed the “Show 20 entries” to "100" so that they could see all targets.
- Sort **from highest to lowest** when clicking on an organ (column): This sorts the heatmap from lowest-highest (The same used to happen with the Associations table but @LucaFumis changed it).
- [Colours in heatmap were not showing right for first participant](https://docs.google.com/document/d/1enEr1SsNjTJfGSj4rJdlp4IzQw6AP0EpsHVdyeBEpdo/edit#bookmark=id.akqxv6psbb45) (Was this because of IE11 or of her screen?)
- Hide the "Cells" column [as at least one participant couldn't tell what this meant](https://docs.google.com/document/d/1Hm83eVnMTzYT_q2-sggSaOSUzeYaYLnOTfKdEIiOAVM/edit#heading=h.qxr7p947n3).

Notably, the expression heatmap was understood and well received by all participants. [One participant made a screenshot of it and put it in her powerpoint draft report](https://docs.google.com/document/d/1Hm83eVnMTzYT_q2-sggSaOSUzeYaYLnOTfKdEIiOAVM/edit#heading=h.qxr7p947n3)!

## Other considerations
- Download heatmap image (and data?)
- Think about how to show values for tissues within an organ (This may become a separate issue)

## Calling Gtex
We are not supposed to call the Gtex API more than once per second. @emepyc may have to address this when the Expression section becomes live (unless we have the Gtex data via Atlas by then).

[x] Description complete

# What would it look like?

Our current Expression section looks like this:
<img width="1222" alt="03-summary-expression-screen shot 2016-11-10 at 13 50 24" src="https://cloud.githubusercontent.com/assets/20280139/21989442/ce31dc70-dc02-11e6-8066-b928bfcc5390.png">

It seems that we can address most of the issues above without significantly changing the display.

[] Design complete

# How would we measure success of this feature?

- Positive user feedback for redesigned section
- Views / downloads of the heatmap (can we measure that ???)

[] Metrics complete

---

@elipapa commented on [Tue Jan 17 2017](https://github.com/opentargets/roadmap/issues/43#issuecomment-273107380)

for the time being we will probably limit the display to ~20 targets. until we have data on our backend.

if the user wants more genes, the section is not displayed

**Comment by andrewhercules** [comment]
Ticket closed as it relates to ticket #21
