### ISSUE TITLE
Drug summary page: Drugs missing disease associations

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#382]
By checking an animation on the drug summary page for EFALIZUMAB I can see this drug used to have diseases associated with it e.g. psoriasis:
<img width="715" alt="screen shot 2018-12-20 at 20 08 27" src="https://user-images.githubusercontent.com/40168275/50343161-d0fddf80-051d-11e9-922a-5189f709cf53.png">

Note the number of targets in the video is also different from production; 3 targets in the former, one in the latter (ITGAL only).
EFALIZUMAB summary page: https://www.targetvalidation.org/summary?drug=CHEMBL1201575
Other examples with no diseases:
https://www.targetvalidation.org/summary?drug=CHEMBL428647
https://www.targetvalidation.org/summary?drug=CHEMBL1201568
https://www.targetvalidation.org/summary?drug=CHEMBL1201572
https://www.targetvalidation.org/summary?drug=CHEMBL1201831
https://www.targetvalidation.org/summary?drug=CHEMBL1201580
https://www.targetvalidation.org/summary?drug=CHEMBL924
I have now included this as a check during our manual QC (in the 'other checks' sheet).

**Comment by ElaineMcA** [comment]
Initial investigations by @peatroot @faulcon @Denise @Michaela, this appears to be an API issue.
 
The diseases section @Denise refers to loads from the following call, which returns a 200 with `data=[]`.
https://api.opentargets.io/v3/platform/public/search?q=EFALIZUMAB&size=100&filter=disease&search_profile=drug

@afaulconbridge:
In my re-runs of `data_pipeline` for the `run-on-gcp.sh` script they are also missing `drugs.evidence_data` so it suggests that this is a software problems not a transient error of some kind

**Comment by afaulconbridge** [comment]
Solved by opentargets/data_pipeline#425 

A better example is https://www.targetvalidation.org/summary?drug=CHEMBL477772
