### ISSUE TITLE
RNA expression evidence: inconsistency between association page and evidence page for immune system disease

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#383]
A Sanofi user has reported that when clicking on the RNA expression session in [evidence for ETV7 in immune system disease](https://www.targetvalidation.org/evidence/ENSG00000010030/EFO_0000540) page, it does show data. This is unexpected as title of the session (i.e. RNA expression) is greyed out, suggesting there shouldn't be any data in there:

<img width="953" alt="screen shot 2018-12-23 at 09 15 35" src="https://user-images.githubusercontent.com/6472381/50383563-629c5700-06ae-11e9-892b-6101b03d72d8.png">

Should this data be in there at all?
From 18.12, we no longer propagate mRNA evidence from children to parent terms. The aforementioned evidence is seen for children terms (e.g. ankylosing spondylitis, systemic lupus erythematosus and a few others) of immune system disease, but not directly for immune system disease.

-------
The user's journey was the following:
1) "Looking at all targets associated to immune system disease:
https://www.targetvalidation.org/disease/EFO_0000540/associations
2) I filtered to a gene ETV7, and from here I see genetic evidence but not RNA expression from the heat map. But in the detailed gene/disease page I see evidence against SLE for both genetic (link below) and expression data types.
https://www.targetvalidation.org/evidence/ENSG00000010030/EFO_0000540?view=sec:genetic_association"

Then the user’s questions:
"I am confused about the direct/indirect thing. I thought if I search SLE as a disease I would see in the heat map associations where the evidence-disease is either SLE or deeper in the taxonomy. But if I search a disease that is very high on the tree (immune system diseases) I should get a summary of all evidence either directly or deeper on the tree. This seems reflected in the target-disease evidence drill down page, but some unexpected behaviors:

a) Why did expression data availability not reflected in the heat map?
b) In the disease-target drill down page the expression data tab is grayed out even though data are present"

-------
@mkarmona's comments from slack:

<img width="622" alt="screen shot 2018-12-23 at 12 33 27" src="https://user-images.githubusercontent.com/6472381/50383591-0128b800-06af-11e9-8273-e7d0ee65bf37.png">

**Comment by ElaineMcA** [comment]
Two issues:

(i) propagation - data discussion

(ii) if data is present, then tab should be displayed as active - FE activity

**Comment by LucaFumis** [comment]
I just double checked the code for the evidence page, and it follows the same approach as the association page (i.e. heatmap).

The various page sections (accordion) are displayed as enabled/disabled (greyed out) based on the corresponding section in the flower.

The flower is populated with data from the `associations` endpoint in the API. For the example above it's https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000010030&disease=EFO_0000540&facets=false

This returns `association_score` and `evidence_count`.
Same as in the association page, we take **both** into account as there can be **evidence with score 0**; for each datatype we check
 - if score>0 **or**
 - if evidence count > 0

This is a data issue: in the example above the API returns returns score 0 and evidence 0. Even though it then returns evidence...

**Comment by d0choa** [comment]
All the FE logic will be applied differently in the React rewrite. No action expected in the Angular app
