### ISSUE TITLE
Python client on readthedocs: improvements/amendements

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#385]
The landing page of our Python client is available at https://opentargets.readthedocs.io/en/stable/#id1.

This address is provided on the homepage of the Open Targets Platform), therefore with potential high-vis. The python client page needs improvement/correction:

 - [x] Can we include "Open Targets Platform" instead of "targetvalidation.org" and link the former to the latter?

 - [x] The sentence  "Open Targets REST API" redirects to https://www.targetvalidation.org/ as the link used is https://www.targetvalidation.org/documentation/api, which has been deprecated in the past. 

This sentence should link to "https://api.opentargets.io/v3/platform/docs/swagger-ui" instead.

<img width="518" alt="screen shot 2019-01-04 at 09 29 27" src="https://user-images.githubusercontent.com/6472381/50681409-51830c80-1003-11e9-808e-21de93170ec0.png">

 - [x] Do we really need the sentence "`api.opentargets.io`_ "? It's currently linking to the python client page itself. So it's not adding anything new and it looks odd.

 - [x] Change Andrea's email to "andrea.pierleoni at gmail dot com" instead of "andreap at ebi dot ac dot uk"

**Comment by MichaelaEBI** [comment]
This has been updated and can be previewed here: https://github.com/opentargets/opentargets-py/blob/MichaelaEBI-patch-1/docs/source/index.rst

@deniseOme if you are happy with the changes, you can close this issue.

**Comment by AsierGonzalez** [comment]
Should we also remove the two "TODO"s in the [Utility](https://opentargets.readthedocs.io/en/stable/high_level_api.html) and [Connection](https://opentargets.readthedocs.io/en/stable/low_level_api.html) pages? I don't really know if this is as simple as editing the [high_level_api.rst](https://github.com/opentargets/opentargets-py/blob/9da211e9294b274bd3ba0fffeedc02842bbe4542/docs/source/high_level_api.rst) and [low_level_api.rst](https://github.com/opentargets/opentargets-py/blob/9da211e9294b274bd3ba0fffeedc02842bbe4542/docs/source/low_level_api.rst) files. Or do we need a separate ticket to look into what these pages actually describe and decide if they should be updated/removed?
