### ISSUE TITLE
Hard coded Swagger api URLs in quay images 

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#386]
The backend image taken from https://quay.io/repository/opentargets/rest_api?tag=latest&tab=tags seems to have the following URL "baked in" for the Swagger pages (I am using quay.io/opentargets/rest_api:18.10.1):
```
https://${APPENG_VERSION}.${GOOGLE_PROJECT_ID}.appspot.com
```
Would be nice if the default URL is the server URL on which the swagger pages are being browsed. See screenshots below:

1) The page is browsed at https://localhost:9209/v3/platform/docs/swagger-ui#/filter/getAssociationFilter, but the swagger request URL states https://${APPENG_VERSION}.${GOOGLE_PROJECT_ID}.appspot.com/v3/platform/public/association/filter?facets=false&scorevalue_min=0

![image](https://user-images.githubusercontent.com/2900303/50775893-bce50c80-1297-11e9-93b4-ad8c469d807b.png)

In this example, ideally it would point to `https://localhost:9209` instead of `https://${APPENG_VERSION}.${GOOGLE_PROJECT_ID}.appspot.com`

**Comment by afaulconbridge** [comment]
Indeed, yes this is a problem. Its baked into the image as part of the CircleCI image creation step, which is doubly bad. I think the correct answer here is to make it configurable as part of the rest_api, defaulting to localhost.

**Comment by pieterlukasse** [comment]
The public api is still pointing to the wrong location, see
https://api.opentargets.io/v3/platform/docs/swagger-ui#/filter/getEvidenceFilter

**Comment by pieterlukasse** [comment]
Would it be better to let `host` here 
https://github.com/opentargets/rest_api/pull/184/files#diff-f80712f775f73de50396c040079c0d07R3
point to a variable instead of the public server? Will that work?

**Comment by afaulconbridge** [comment]
The API location is now https://platform-api.opentargets.io/v3/platform/docs/swagger-ui#/filter/getEvidenceFilter

Indeed that is the right way to do it @pieterlukasse .

Ideally, we would like to bring the configuration together for the API first, see opentargets/platform#560

**Comment by pieterlukasse** [comment]
CC @rnugraha, because he was actually interested in using the api and seeing this work in the swagger page.

**Comment by afaulconbridge** [comment]
Closing, the plan is for the API to eventually move to GraphQL and therefore the swagger docs become redundant.
