### ISSUE TITLE
ECO LUT index must contain eco_score uris

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#388]
All uris contained [in this file](https://raw.githubusercontent.com/opentargets/data_pipeline/master/mrtarget/resources/eco_scores.tsv) must be also contained in the ECO LUT index. As an example of missing for `missense_variant`

```
GET 18.12_eco-data/_search 
{
  "query": {
    "match": {
      "code": "http://purl.obolibrary.org/obo/SO_0001583"
    }
  }
}
```
Result of the query:
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 9,
    "successful": 9,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

**Comment by afaulconbridge** [comment]
They are already present, but the LUTs use short codes not full iris. See commit opentargets/data_pipeline/commit/b07c7d1a1a4ab17a8de7c0f96f191c6e952bd079 for resolution.
