### ISSUE TITLE
UKBiobank Parser

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#39]
@ckongEbi commented on [Mon Jun 11 2018](https://github.com/opentargets/evidence_datasource_parsers/issues/13)

New parser similar to GWAS needed for UKBiobank Parser. On last update, Ed has did the mappings and Gautier were to validate those and we can produce JSON for them. 

---

@ckongEbi commented on [Mon Jun 11 2018](https://github.com/opentargets/evidence_datasource_parsers/issues/13#issuecomment-396192566)

The parser is ready `https://github.com/opentargets/evidence_datasource_parsers/blob/ck-progeny/modules/UKBiobank.py`  but need to run with data with complete disease mappings

@iandunham @gkos-bio 

---

@ckongEbi commented on [Tue Jul 24 2018](https://github.com/opentargets/evidence_datasource_parsers/issues/13#issuecomment-407410365)

@ElaineMcA we will need the UKbiobank data with disease mapping curated to proceed. Check with Ed or Gautier on the curation status

**Comment by afaulconbridge** [comment]
Given that the long-term plan is to get the uk biobank data via the genetics portal, can this ticket be closed?  @ElaineMcA @mkarmona might have opnions on that.

**Comment by afaulconbridge** [comment]
I know no reason to keep this ticket open, closing.
