### ISSUE TITLE
Add score for ECO code ECO:0000204 "Author statement"

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#390]
We have some evidence that refer to ECO code http://purl.obolibrary.org/obo/ECO_0000204 "Author statement" but that is missing from the `eco_scores.tsv` file.

This ECO code needs to be added to the file, and an appropriate score modified decided upon.

**Comment by afaulconbridge** [comment]
Related to this, it would be nice if we leveraged the structure of the ontology for the ECO code scoring. E.g. by applying modifiers for child terms to a fixed base.

**Comment by d0choa** [comment]
Related with #4

**Comment by DSuveges** [comment]
We are no longer using ECO codes for scoring in the platform anymore.
