### ISSUE TITLE
Unclear which images to use for rest_api and webapp for 18.12

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#392]
When upgrading a local installation to 18.12, it is not clear which image to take from the following repositories:

- https://quay.io/repository/opentargets/webapp?tag=latest&tab=tags
- https://quay.io/repository/opentargets/rest_api?tag=latest&tab=tags

Can you please help us with this? Going forward, it would be great if this information could also be part of the release notes that comes with each new version.

**Comment by afaulconbridge** [comment]
For 18.12 quay.io/opentargets/rest_api:prod-20180828-1238 and quay.io/opentargets/webapp:v3.10 should work. Note that we don't use the docker image of the webapp in production (its deployed from source via Netlify).

**Comment by pieterlukasse** [comment]
@afaulconbridge the tag for rest_api is 4 months old. Are you sure this is correct? There were a lot of changes in https://github.com/opentargets/rest_api since then.

**Comment by afaulconbridge** [comment]
You're right @pieterlukasse It seems that automated tagging broke at some point in the past. Sorry for the confusion. You should use quay.io/opentargets/rest_api:18.12.0
