### ISSUE TITLE
ECO_0000356 and ECO_0000357 deprecated

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#394]
We have a number of evidence strings that use ECO_0000356 ( differential gene expression evidence from microarray experiment ) and ECO_0000357 ( differential gene expression evidence from RNA-seq experiment ) but those have been deprecated by ECO and should be replaced, probably with ECO_0000009 ( transcript expression evidence ) or a [child term](https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000009).

This should be fixed upstream by Expression Atlas.

**Comment by AsierGonzalez** [comment]
I have checked and ECO_0000356 and ECO_0000357 are the only ECO codes that Atlas use. I will talk to them.

**Comment by afaulconbridge** [comment]
This will require some changes to the JSON schema, described in opentargets/platform#399

**Comment by afaulconbridge** [comment]
The changes have been made to JSON schema as version 1.5.0 which can be validated with URL https://raw.githubusercontent.com/opentargets/json_schema/1.5.0/opentargets.json

**Comment by AsierGonzalez** [comment]
Closing as it seems to have been resolved in the lastest data submission.

**Comment by MichaelaEBI** [comment]
Has been resolved in the March data submission.
Old ECO codes:
```
gsutil cat gs://otar010-atlas/cttv010-2019\* | gunzip | grep ECO_0000356 | wc -l
       0
gsutil cat gs://otar010-atlas/cttv010-2019\* | gunzip | grep ECO_0000357 | wc -l
       0
```
New ECO codes:
```
gsutil cat gs://otar010-atlas/cttv010-2019\* | gunzip | grep ECO_0000058 | wc -l
  307123
gsutil cat gs://otar010-atlas/cttv010-2019\* | gunzip | grep ECO_0000295 | wc -l
   89222
```
