### ISSUE TITLE
Update Google Analytics to track events on Disease and Target Association pages

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#395]
Currently, we only track events related to the facets on the Associations pages. To get a better sense of the user journey, I'd like to understand which view(s) users select on the page and how they interact with the content (e.g. on-hover and on-click events). 

Can we please update the Associations and Prioritisation Views to [track the events listed in this spreadsheet](https://drive.google.com/open?id=1N1hf6bNqY2gLFsY8719kNYNJdJHO5ZeA0s_5xQuuNNI)?

**Comment by andrewhercules** [comment]
@LucaFumis, hope you don't mind, but I thought we could work through this together and I can introduce you to Google Analytics event tracking. 

cc-ing @ElaineMcA for release planning

**Comment by LucaFumis** [comment]
Added tracking as per spreadsheet. 
Missing specific bubble and tree view tracking: this is non essential and would require changes to external npm modules.
Some (non essential) tracking might be fired inconsistently due to DataTables handling of certain events and we'll monitor this.

**Comment by andrewhercules** [comment]
Perfect - thanks @LucaFumis
