### ISSUE TITLE
Compile list of targets with potential safety concerns

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#396]
There are review articles with lists of drug targets that should be 'approached' with caution (courtesy of Andrew L.):
- http://www.sciencedirect.com/science/article/pii/S1056871916301472
- https://www.nature.com/articles/nrd3845
- and a somewhat more detailed and specific one on kinase-related cardiotox (of course, this might also be a reason to pursue such targets for certain diseases...): https://www.ncbi.nlm.nih.gov/pubmed/28453775

It might be useful to flag these targets in the Open Targets Platform:
- [x] Compile a list of all targets in these papers with as much information as the papers provide
- [x] Assess whether this information should be included in the Open Targets Platform
- [x] If the data is to be included, add Ensembl IDs, UniProt Accs or HGNC gene names to the list

**Comment by EPetsalaki** [comment]
https://docs.google.com/document/d/1GifGiztJuTbM5l3EI9Tfe-Hix4rIYQEc9iqFmLmGgI4/edit

**Comment by EPetsalaki** [comment]
Meeting with Ian and Michaela took place January 29, 2019. The meeting notes can be found [here](https://docs.google.com/document/d/12wOYFDFRUKN_9xkBkFGj90v9P3g_zToGnls_Jpc7ElQ/edit).
