### ISSUE TITLE
EFO3 Therapeutic areas

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#397]
OpenTargets uses a number of "therapeutic areas" - for faceting etc. In general these are ontology terms directly under disease ( http://www.ebi.ac.uk/efo/EFO_0000408 ). For direct child terms of disease that are not a "therapeutic area" they are combined under a created "other" therapeutic area ( http://www.targetvalidation.org/disease/other ). Two other terms and their children are also added to other; "injury" ( http://www.ebi.ac.uk/efo/EFO_0000546 ) and "mental health" ( http://www.ebi.ac.uk/efo/EFO_0003935 ). Several terms from elsewhere are also used as therapeutic areas; "phenotype" ( http://www.ebi.ac.uk/efo/EFO_0000651 ), "measurement" ( http://www.ebi.ac.uk/efo/EFO_0001444 ), "biological process" ( http://purl.obolibrary.org/obo/GO_0008150 ), "function" ( http://www.ifomis.org/bfo/1.1/snap#Function ).

The complete list of EFO2 therapeutic areas are:
- http://www.ebi.ac.uk/efo/EFO_1000018 : bladder disease
- http://www.ebi.ac.uk/efo/EFO_0000319 : cardiovascular disease
- http://www.ebi.ac.uk/efo/EFO_0000405 : digestive system disease
- http://www.ebi.ac.uk/efo/EFO_0001379 : endocrine system disease
- http://www.ebi.ac.uk/efo/EFO_0003966 : eye disease
- http://www.ebi.ac.uk/efo/EFO_0000508 : genetic disorder
- http://www.ebi.ac.uk/efo/EFO_0000524 : head disease
- http://www.ebi.ac.uk/efo/EFO_0005803 : hematological system disease
- http://www.ebi.ac.uk/efo/EFO_0000540 : immune system disease
- http://www.ebi.ac.uk/efo/EFO_0003086 : kidney disease
- http://www.ebi.ac.uk/efo/EFO_0005741 : infection disease
- http://www.ebi.ac.uk/efo/EFO_0000589 : metabolic disease
- http://www.ebi.ac.uk/efo/EFO_0000616 : neoplasm
- http://www.ebi.ac.uk/efo/EFO_0000618 : nervous system
- http://www.ebi.ac.uk/efo/EFO_0000512 : reproductive system
- http://www.ebi.ac.uk/efo/EFO_0000684 : respiratory system
- http://www.ebi.ac.uk/efo/EFO_0002461 : skeletal system
- http://www.ebi.ac.uk/efo/EFO_0000701 : skin disease
- http://www.ebi.ac.uk/efo/EFO_0001421 : liver disease
- http://www.targetvalidation.org/disease/other : other
- http://www.ebi.ac.uk/efo/EFO_0000651 : phenotype
- http://www.ebi.ac.uk/efo/EFO_0001444 : measurement
- http://purl.obolibrary.org/obo/GO_0008150 : biological process
- http://www.ifomis.org/bfo/1.1/snap#Function : function

For EFO3, the good news is that all of these terms continue to exist. One special case is http://www.targetvalidation.org/disease/other which is an OpenTargets construct and not in EFO2, but the two specific terms that are placed into that ("injury" http://www.ebi.ac.uk/efo/EFO_0000546 and "mental health" http://www.ebi.ac.uk/efo/EFO_0003935) do continue to exist.

The bad news for EFO3 is that these therapeutic areas are, in many cases, no longer direct child terms of disease. For example, in EFO2 "bladder disease" was a direct child of "disease" but in EFO3 it looks like:

```
+-disease
  +-disease affecting anatomical system
  | +-urinary system disease
  |   +-bladder disease
  |
  +-disorder of anatomical region
    +-bladder disease
```

This means that the previous therapeutic areas code will not work, and will be more complicated to implement. In addition, the "other" categorisation algorithm used for EFO2 will need to be changed for EFO3. Without taking appropriate precautions, it would put "bladder disease" into its own therapeutic area but "urinary system disease" into "other".

After discussion, one of the solutions might be to "tag" terms that are Open Targets "therapeutic areas". In the Open Targets data pipeline, we can then easily calculate the routes to parent terms that are "therapeutic areas" without having to slide and dice EFO. This approach also has the advantage the EFO then know which terms are being used in this way, and can apply additional checks e.g. to ensure "eye disease" is never a child term of "nervous system disease". A downside of this is that any changes to add or remove "therapeutic areas" would have to be done through EFO releases, but this is thought to be a small issue as EFO releases monthly and the changes are rarely necessary.

**Comment by iandunham** [comment]
Have you talked to Simon about this? The TA division was one of the areas we flagged with them for EFO3, and which was supposed to be made simpler.

**Comment by afaulconbridge** [comment]
Done as part of opentargets/ontology-utils#7
