### ISSUE TITLE
Consistency in mouse phenotypes data

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#398]
The `mouse_phenotypes` field of the REST API response can be either an array or an (empty) object depending on the target. The empty object case seems to be the behaviour when no information is available, but it would be preferable if this were an empty array or just `null`.

The problem may be at the API level or upstream in the evidence strings.

Examples
* as array: https://api.opentargets.io/v3/platform/private/target/ENSG00000091831
* as empty object: https://api.opentargets.io/v3/platform/private/target/ENSG00000127419

**Comment by d0choa** [comment]
No work expected in this task
