### ISSUE TITLE
Validator does not give error when input file does not exist

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#407]
The opentargets_validator script (https://github.com/opentargets/validator) will not give an error if the input file does not exist.

Desired solution: give a "file not found"  or "empty input" error if no file was found or no input was given.

**Comment by afaulconbridge** [comment]
Thanks, I think this is a good idea that should be easy to implement. I'll look into it after the 19.02 release.

**Comment by pieterlukasse** [comment]
@afaulconbridge was this one fixed? I can test again tomorrow.

**Comment by afaulconbridge** [comment]
closing, please reopen if still an issue
