### ISSUE TITLE
Consolidate REST-API documentation and tutorials

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#409]
## Description
* [ ] **WHY - What is the problem this feature would answer?**  

More details on the different problems to address can be found in our [google doc](https://docs.google.com/document/d/1_GFRiEYMBSkDTFjolCA0EWu_IOSgBPRiW6GSCgPkYkg/edit)

* [ ] **HOW are we going to solve the problem?**  
"There are several stages (text below taken straight from Ian's message on slack)

1. The detailed documentation of the APIs we provided and how best to support this. This needs a discussion for both th current technology and the future ones so that we can support properly.

2. Providing more entry level tutorials around how to use the APIs to get specific types of data that we want to support - at the level of blogs and tutorials. This is essential to ease most bioinformaticians along the road to using our resources.

3. Making it easy to find our docs, tutorials and blogs and ensuring any that are out of date are either updated or deprecated.

**We can do 3 from where we are now, and then build successively through 2 and 1**"

* [ ] **WHAT would this look like?**

 
### Progress Tracker

**Related tickets**
#94  "example POST requests in swagger UI are not valid"
#105 "extend openapi specs to improve public API documentation"
#219 "post rest api endpoint for diseases does not seem to work?"

#95 "handle more gracefully an empty query for POST besthitsearch"

#291 "Update API Documentation (including python client)"

#385 "Python client on readthedocs: improvements/amendements"
#441 
#442 
#443 
#558

**Comment by deniseOme** [comment]
[Meeting notes](https://docs.google.com/document/d/1y2DmsA2pHYawIc1h3FHxvRvIGQi4FTqxzySwSkxxs_k/edit#)

**Comment by MichaelaEBI** [comment]
Ideal user journey for API, a work in progress by @ElaineMcA Maya & @MichaelaEBI 

API Documentation
**1. Overview of what we offer**
- What is the Open Targets REST-API?
- URL-based access
- Command line access
- Client-based access (Python & R)

**Swagger**
Role of Swagger? 
Where can people convert a trait name into an EFO ID to use with Swagger/the API?
Indicate that target.id is Ensembl ID. Where can users get that ID from?

**Working with JSON output**
- What information does the JSON contain, what is the structure of the responses for the different endpoints.
- What is an endpoint
- View with online JSON viewer
- Install a browser extension to view results in 'nice' format immediately
- mention command line tool jq which allows to view JSON and to extract data

**Comment by deniseOme** [comment]
@LucaFumis, @afaulconbridge @ElaineMcA, would it be possible to have the amended text on the swagger page as per https://github.com/opentargets/rest_api/blob/master/api-description.md?

**Comment by ElaineMcA** [comment]
Internal hackathon held 20-Aug-2019.

Notes and follow-up actions from hackathon are detailed in a central document on internal google drive [here](https://drive.google.com/drive/folders/0AOMozGkUtCmbUk9PVA).

Summary: 
- Tutorials reviewed, page outline updated and API examples updated/corrected to ensure they work with CURL in terminal - more accessible for all users.
- Also purpose of installing JQ explained.
Note: After initial review of tickets outstanding has been completed, priority and resources to be discussed with David O.

**Comment by d0choa** [comment]
While important, we consider most of our effort should be focused on documenting the next version of the API.

The corresponding ticket will be open when appropriate
