### ISSUE TITLE
EVA variants in ExAC?

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#41]
@deniseOme commented on [Fri Jul 28 2017](https://github.com/opentargets/data_release/issues/43)

Hi @ckongEbi,

@iandunham and I went through the ExAC resources and discussed we could find out which variants in EVA map to the ExAC data.

The ExAC info could be available somehow in the Open Targets Platform so that users can find out more about the allele representation of a given variant in healthy individuals (e.g. depending on the frequency of the allele one can have an indication the allele/variant may not be relevant to the disease among other use cases of genotyping/sequencing data in healthy populations). 

This is what EVA has got at the moment:
http://www.ebi.ac.uk/eva/?variant=17:64224271:C:T&species=hsapiens_grch37#population-stats-grid-div

with a link to ExAC study e.g.
http://www.ebi.ac.uk/eva/?eva-study=PRJEB8661

![screen shot 2017-07-28 at 17 22 16](https://user-images.githubusercontent.com/6472381/28726486-58e6d80e-73b9-11e7-92d6-584ad9a93240.png)

Worth exploring this in the near future.

**Comment by d0choa** [comment]
gnomAD data is currently available in the Genetics Portal and we'll work to expand our rare variation data from it.
No action is expected in the short term related to exac/gnomad and EVA
