### ISSUE TITLE
Deprecated DailyMed links in our evidence page gets replaced by an FDA API call

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#410]
![screen shot 2019-01-25 at 17 17 33](https://user-images.githubusercontent.com/6472381/51833801-609e6700-22f0-11e9-9114-f304bb8f3a9e.png)
In this ex: https://www.targetvalidation.org/evidence/ENSG00000175482/EFO_0001075?view=sec:known_drug

when I click on the link in the last column of the table, to see what evidence has been curated and used for our associations, I get redirected to:
https://api.fda.gov/drug/label.json?search=set_id:ffc0a4be-6091-4157-837e-3637c1e121a6

I've checked this with Paula (from ChEMBL) who said that this can happen when the DailyMed links become obsolete and it's a deliberate decision on their part to change from the DailyMed to the api.fda.gov

However in between their releases and ours, a link can become obsolete (but not changed to the FDA API call by ChEMBL) and what we show in the UI is the dailymed index page (homepage), which gives no specific information.

Question: are we happy with pointing the evidence to api.fda.gov and showing a JSON response to a user who likely does not have an idea what a JSON response like that can be interpreted?

![screen shot 2019-01-28 at 11 30 34](https://user-images.githubusercontent.com/6472381/51833719-29c85100-22f0-11e9-8ce3-1330d1509963.png)

![](https://files.slack.com/files-pri/T02UV853T-FFP9G97DZ/screen_shot_2019-01-25_at_17.17.33.png)

**Comment by MichaelaEBI** [comment]
There are two issues here:
1. The original DailyMed link is obsolete and a link to the [DailyMed homepage](https://dailymed.nlm.nih.gov/dailymed/index.cfm) is provided as described by Paula.
2. The second issue is the link to the FDA API: 16,820 of 471,028 evidence strings contain links to the FDA API which is probably not what we expect. I will follow up on this.

**Comment by deniseOme** [comment]
Low priority.
