### ISSUE TITLE
Update the Open Targets Platform about page to include most recent NAR paper

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#413]
The page https://www.targetvalidation.org/about still points to the 2017 paper.

Can we change this to the 2019 paper please so that is in line with what we have on the homepage?

![screen shot 2019-01-29 at 15 47 09](https://user-images.githubusercontent.com/6472381/51921021-75592880-23de-11e9-9a4c-fa179c5d291b.png)

Perhaps this can be done for the 19.02 release?

**Comment by ElaineMcA** [comment]
Reviewed on QA and release ready.
