### ISSUE TITLE
outdated --mp step mentioned in wiki page

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#417]
Documentation at https://github.com/opentargets/data_release/wiki/OT011-Data-Processing-(Backend) mentions this step:
```
# Mammalian Phenotype Ontology: For input files see `mrtarget/resources/ontology_config.ini`
python -m mrtarget.CommandLine --mp --log-level DEBUG ${DATA_RELEASE_VERSION}
```
but --mp was removed some time ago already: https://github.com/opentargets/data_pipeline/commit/53a10fbb68308037cf69be2508fccd4027fe3251#diff-207eb651f06282de6163d352571c1d11

Desired solution: up to date wiki page.

**Comment by MichaelaEBI** [comment]
The --mp step has been removed from the wiki and the information in the wiki will soon be moved to the readme.
