### ISSUE TITLE
Update disease mapping for PheWAS

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#420]
**Asier to fill in details about disease mapping status**

This is in progress and needs more work to be finished. Documents related to this can be found here: https://drive.google.com/drive/folders/1eS3MHRZeyjWQCOQXBJP4Lv-icn-Ra6mL

**Comment by AsierGonzalez** [comment]
In December we wen't through the 733 diseases whose mapping had changed compared to the 2017 mapping. However, there are still 659 disease-EFO mappings to be checked, which will be progressively looked into in the next months.

**Comment by MichaelaEBI** [comment]
We will schedule a mappathon with a few people to get this done for 19.08.

**Comment by d0choa** [comment]
@smnorthen has done some progress curating some extra mappings.

**Comment by smnorthen** [comment]
Review includes check of matches (of which some have changed) and fuzzy matches. Some PheWAS mappings with multiple medical concepts in a single term will need to receive 2 or more EFO IDs to account for the multiple disease concept. Some new EFO disease terms will need to be added to the ontology as discussed with the SPOT team.

**Comment by smnorthen** [comment]
1,360 PheWAS traits have been mapped against EFO. Some traits, which contain multiple medical concepts, have been mapped against multiple EFO IDs; single medical concepts traits have been mapped against a single EFO ID. 
Some new EFO terms were added to the ontology from HP and Mondo (86 HP terms and 28 Mondo terms) - see https://github.com/EBISPOT/efo/issues/728.
133 traits are missing from EFO and will be added at a later stage. A separate EFO SPOT github ticket will be raised for this.
@AsierGonzalez will be running the PheWAS pipeline.

**Comment by AsierGonzalez** [comment]
The new mappings file has replaced the old one in the mappings repository: https://github.com/opentargets/mappings/blob/master/phewascat.mappings.tsv

**Comment by AsierGonzalez** [comment]
Mappings file in the repo above updated with the latest EFO updates, which includes around 30 new requested terms now included in EFO. This completes the mapping of PheWAS Catalog traits to EFO.
