### ISSUE TITLE
Replace SNP2GENE with Genetics platform

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#426]
We should use the genetics platform to do snp to gene mappings, instead of the perl script calling VEP API. See https://github.com/opentargets/snp_to_gene and https://github.com/opentargets/data_release/wiki/OT007-SNP2GENE-Pipeline

This will be more performant and consistent and reliable. It will need to work for both GWAS and EVA sources.

**Comment by iandunham** [comment]
We need to ensure that the output is comparable for EVA, if you do this

**Comment by afaulconbridge** [comment]
There is also a question of if this should be applied to PheWAS or not, since that also uses SNPs and they should probably be mapped consistently to targets.

**Comment by AsierGonzalez** [comment]
This is related to the work that @DSuveges is doing to integrate the locus2gene score, so I assign it to him.

**Comment by hammer** [comment]
@DSuveges we'd love to help out with this project, or at the least do code reviews! Please let us know if you have any interest in working together.

**Comment by DSuveges** [comment]
Hi @hammer, we are currently exploring the possibilities on how to source GWAS associations from the Genetics portal, and what the impact on the predicted disease/target associations would be on the Platform. So at this point we not yet there to change the pipeline, but will let you know for sure! Thanks for your help in advance.

**Comment by d0choa** [comment]
SNP2GENE won't be replaced by the Genetics Portal as suggested by this ticket. While the Genetics Portal will use the more sophisticated Locus2Gene scoring to find causal genes, some of our evidence (e.g. GWAScatalog, EVA/Clinvar) will still require a more traditional approach.

Progress detailed in #815 Epic
