### ISSUE TITLE
Generate GWAS evidence from genetics platform

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#427]
We currently receive evidence strings directly from GWAS catalogue. However, this data is also fed into the genetics platform, so we can isntead generate evidence strings from the genetics platform covering the same data.

This would be more maintainable, controlled, and performant.

**Comment by iandunham** [comment]
Note this requires the locus-wise scoring from the genetics platform, plus full EFO mapping for UK Biobank

**Comment by MichaelaEBI** [comment]
I am closing this ticket for now. It will be a little while yet until the Open Targets Platform will receive GWAS data from the Genetics Platform and it is on everyone's radar. Specific tickets will be created when work will commence on this.
