### ISSUE TITLE
19.02 release candidate:  GO and interactions sections not loading in batch search

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#430]
For batch search,  gene ontology (GO) and interactions (omnipath) not successfully loading:

https://qa.targetvalidation.org/summary?targets=121281,85978,187796,13725,164308,143226,176920,90339,115267,136634,115607,162594,134460,115232,5844,105855,173531,167207,95110,197943,134242,158714,166949,79263,106952,105397

? May be related to changes made to proxy - TBD @LucaFumis @mkarmona.

![screen shot 2019-02-11 at 17 27 54](https://user-images.githubusercontent.com/40168275/52581501-d04d3f80-2e22-11e9-8f8e-a03fe1c2e5a3.png)
![screen shot 2019-02-11 at 17 27 28](https://user-images.githubusercontent.com/40168275/52581502-d0e5d600-2e22-11e9-8778-17ffa4dbc41c.png)

**Comment by mkarmona** [comment]
![captura de pantalla -2019-02-11 21-18-37](https://user-images.githubusercontent.com/5394232/52594156-b02d7880-2e42-11e9-82d3-17778f5bd960.png)
@ElaineMcA @LucaFumis it does not work either on current production. Can you please work out what is it going on with that required service (GO service) and what did they change in order to apply same correction to our proxy? thanks

**Comment by peatroot** [comment]
The GProfiler tool used to have an unusual interface, but seems to now offer REST (see [docs here](https://biit.cs.ut.ee/gprofiler/page/apis)). Currently investigating the necessary changes needed.

**Comment by peatroot** [comment]
By unusual, I mean that the POST body was something like the following, rather than a JSON blob.
```
output=mini&organism=hsapiens&significant=1&sort_by_structure=1&ordered_query=0&as_ranges=0&no_iea=0&underrep=0&hierfiltering=none&user_thr=1&min_set_size=0&max_set_size=0&threshold_algo=analytical&domain_size_type=annotated&query=CD6+IL18RAP+IL10+TYK2+NXPE1+FUT2+MST1+FCGR2A+ITGB8+SP140+ADCY7+ATG16L1+ITGA4+SLAMF8+IFIH1+IL2RA+NOD2+PTPN22+ERAP2+IL23R+ITGAL+CARD9+SMAD3+ICAM1+PLCG2+TNFSF8
```

**Comment by ElaineMcA** [comment]
Target profile page sections for ITGAL not loading in QA currently:  https://qa.targetvalidation.org/target/ENSG00000005844

Variants, isoforms and genomic context
Protein structure
Gene tree

All relevant sections (no data expected for biomarkers or hallmarks) load in production currently without issue.  https://www.targetvalidation.org/target/ENSG00000005844

**Comment by peatroot** [comment]
@ElaineMcA, suggest the above is reported as independent issues, since this is unlikely to be related to the GO issue in batch search.

**Comment by peatroot** [comment]
The change in API response structure seems to have removed the list of targets per GO term. The consequence is that the final two columns (*Number of targets* and *Targets*) will have to be removed.

**Comment by LucaFumis** [comment]
Thank you @peatroot for fixing this.

**Comment by ElaineMcA** [comment]
Reviewed on QA and release ready.
