### ISSUE TITLE
Inconsistent target symbol and id found on drug summary page due to bestHitSearch

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#432]
It has been observed by a user that, on the [OLAPARIB drug summary page](https://www.targetvalidation.org/summary?drug=CHEMBL521686), PARP1 as listed under the target synonyms of the mechanisms of action table links to PARP14 instead.

The chain of events to produce the target synonyms section of the *mechanisms of action* table for a given `drugId`:
* single GET https://www.ebi.ac.uk/chembl/api/data/mechanism?molecule_chembl_id=<drugId> and extract multiple `target_chembl_id`s from the response
* multiple GET https://www.ebi.ac.uk/chembl/api/data/target?target_chembl_id=<target_chembl_id> and extract `GENE_SYMBOL` from each response
* single POST https://api.opentargets.io/v3/platform/private/besthitsearch with body `{filter: 'target', q: [...<GENE_SYMBOLs>], search_profile: 'target'}` and extract multiple `ensemblId`s from response

The issue is that our `bestHitSearch` returns the `ensemblId` of PARP14 when you search for the symbol PARP1.

**Comment by mkarmona** [comment]
@peatroot can you please check with the param `search_profile: 'batch' ` instead the parameter you are currently using `'target'`? that should fix the problem for that query. By example this query for [PARP1, 2 and 3](https://platform-api.opentargets.io/v3/platform/private/besthitsearch?filter=target&q=PARP1&q=PARP2&q=PARP3&search_profile=batch)

**Comment by d0choa** [comment]
This problem doesn't apply anymore
