### ISSUE TITLE
Literature section does not load for Evidence for 'PAEP in inflammatory bowel disease' page

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#433]
On the Evidence for '[PAEP in inflammatory bowel disease](https://www.targetvalidation.org/evidence/ENSG00000122133/EFO_0003767?view=sec:literature)' page, the references are not loaded in the literature section.

**Comment by MichaelaEBI** [comment]
First investigations (from Slack):
**Luca:** I suspect it’s because the call we make to EPMC doesn’t return a `pmid` for one of the results (PMC4669991)
https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id:28932092%20OR%20ext_id:28932092%20OR%20ext_id:28259136%20OR%20ext_id:PMC4669991%20OR%20ext_id:PMC4669991%20OR%20ext_id:24058568%20OR%20ext_id:23620660%20OR%20ext_id:22315509%20OR%20ext_id:21487562&format=json&resultType=core
and we check against that to merge our data and empc data when populating the table.
**Miguel:** `PMC4669991` this one right? is there a way in their api saying just return pubids?
**Luca:** Yes, that’s the one @mkarmona I don’t know about the API, but can have a look.
I can see that generally id == pmid so maybe we can match against that in the webapp… I’ll give it a try and investigate (edited)

**Comment by LucaFumis** [comment]
To confirm, this is an issue at EPMC api/data level. I haven't seen options to tweak the response in relation to this (the option we call, `resultType=core`, works for our requirements).

I have added some checks to use `id` if `pmid` is missing and in case to handle gracefully missing data - commit c264685f.

**Comment by ElaineMcA** [comment]
Reviewed and release ready on QA.
