### ISSUE TITLE
19.02 GWAS data - 26 evidence strings have a score of 0

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#434]
In the 19.02 data, 26 GWAS evidence strings have a score of 0. First investigations revealed that these evidence strings have very small p-values (< 1e-1000).

**Comment by MichaelaEBI** [comment]
It looks like the association score of '0' is related to the very small p-values. Below is a summary of the 4 studies that have this issue.

Studies:
http://europepmc.org/abstract/MED/26910538 (x1) - On the [GWAS catalog website](https://www.ebi.ac.uk/gwas/publications/26910538) there is one variant with a p-value > 1e-1000.
http://europepmc.org/abstract/MED/29403010 (x9) - On the [GWAS catalog website](https://www.ebi.ac.uk/gwas/publications/29403010) there is one variant with a p-value > 1e-1000 (=3e-1255) that is mapped to 9 different genes.
http://europepmc.org/abstract/MED/29875488 (x 15) - On the [GWAS catalog website](https://www.ebi.ac.uk/gwas/publications/29875488), these 15 variants are the only ones in this study with a p-value < 1e-1000
http://europepmc.org/abstract/MED/30048462 (x1) - On the [GWAS catalog website](https://www.ebi.ac.uk/gwas/publications/30048462) there is one variant with a p-value > 1e-1000.

All 4 studies were part of the 18.12 release, but I do not see the very small p-values in the OT platform:
```
michaela$ gsutil cat gs://ot-releases/18.12/evidences/gwas\* | gunzip |  grep http://europepmc.org/abstract/MED/29403010 | wc -l
    1849
michaela$ gsutil cat gs://ot-releases/18.12/evidences/gwas\* | gunzip |  grep http://europepmc.org/abstract/MED/26910538 | wc -l
       8
michaela$ gsutil cat gs://ot-releases/18.12/evidences/gwas\* | gunzip |  grep http://europepmc.org/abstract/MED/29875488 | wc -l
    3509
michaela$ gsutil cat gs://ot-releases/18.12/evidences/gwas\* | gunzip |  grep http://europepmc.org/abstract/MED/30048462 | wc -l
    1515
```

In python, p-values >1e-323 are converted to '0'.
```
>>> a=1e-323
>>> a
1e-323
>>> a=1e-324
>>> a
0.0
```

**Comment by LucaFumis** [comment]
Added a fix for small p-values (returned as strings instead of numbers) in the webapp https://github.com/opentargets/webapp/commit/4666c66a909b6360105ae4a8207d909dae7376ed which should cover part of this issue.

**Comment by AsierGonzalez** [comment]
The 19.06 GWAS evidence file also contains 207 evidence with `p-value=0` and 31 where the p-value is a string instead of a number. Neither case is supported by the JSON schema so those strings are invalid but the pipeline still seems to process at least some of them: https://www.targetvalidation.org/evidence/ENSG00000181577/EFO_0004762

**Comment by AsierGonzalez** [comment]
The 26 evidence strings with an association score of `0` are the ones from the group of 31 with non-numeric p-values that end up in the valid evidence index.

**Comment by AsierGonzalez** [comment]
- **0 p-values:** After talking to James Hayhurst from GWAS Catalog, we know that `p-value=0` are not real values from GWAS. They are caused by below precision values being converted to 0. Threfore, it has been agreed with @mkarmona and James that from 19.11 the p-values in the GWAS catalog evidence will be defined as mantissa and exponent instead of scientific notation. Consequently, we need to change the schema to accept the p-value in this format:

```
"resource_score": {
        "type": "pvalue",
        "method": {
          "description": "pvalue for the snp to disease association."
        },
        "mantissa": 1,
        "exponent": -84
      }
```

- **Non-numeric p-values:** They are due to a bug in the GWAS pipeline that they will solve

**Comment by AsierGonzalez** [comment]
GWAS have implemented the requested changes and have generated a new file with the 19.09 evidence and the new format: they now represents p-values as mantissa (int, NB p-values are stored to 1 significant figure in the GWAS Catalog) and exponent (int).
OT to test the new format and make the necessary changes for 19.11.

**Comment by LucaFumis** [comment]
Hi @AsierGonzalez will this be included in 19.11?
I imagine it will require some small front end changes...

**Comment by AsierGonzalez** [comment]
Hi @LucaFumis, GWAS have implemented the changes and we now have both the float p-value and the mantissa and exponent notation.
```
"resource_score":{
  "type": "pvalue",
  "method": {
    "description": "pvalue for the snp to disease association."
  },
  "value": 1e-13,
  "mantissa": 1,
  "exponent": -13
}
```
However, I think that back-end have not had time to integrate these changes into the pipeline so I don't know if the information will be made available via the API.

**Comment by cmalangone** [comment]
I assigned myself the ticket for the BE part. We can discuss it for 20.02

**Comment by d0choa** [comment]
@DSuveges will investigate whether the new `mantissa` and `exponent` can be used in the generation of the score. It's unlikely to have any effect in the scoring as all low p-values might be outside the range that the 0-1 scores cover.

I will create a separate ticket for FE to use the `mantissa` and `exponent` to build the p-value instead of using the `value` field.

**Comment by DSuveges** [comment]
The evidence score generation is done using the raw p-value as defined in the [EvidenceString.py](https://github.com/opentargets/data_pipeline/blob/d5919fbf1c5552d9af5ff304b8e4758e2bf85356/mrtarget/common/EvidenceString.py#L686) file. 

However the script then tries to convert it to the negative logarithm, which is failing when zero as p-value is passed. This `ValueError` is caught and the lowest p-value is assigned [link](https://github.com/opentargets/data_pipeline/blob/d5919fbf1c5552d9af5ff304b8e4758e2bf85356/mrtarget/common/EvidenceString.py#L675):

```python
def get_log(n):
    try:
        return math.log10(n)
    except ValueError:
        return math.log10(range_max)
```

So the code is resilient to very low p-values. It leaves us two options:

1. Convert the exponent and the mantissa to p-value (occasionally leading to 0 p-value), then back to the negative log to scale. This option has the lowest impact on the existing codebase. Only one extra statement is required.
2. Using the exponent and the mantissa, directly calculate the neg.log p-value, and use this for scaling. I think this makes the most sense, however it has some implications in the above linked code. But at the end the code will be a bit cleaner as the `_get_score_from_pvalue_linear` function will not be needed.

The statement to get the neg.log p-value from the exponent and mantissa:

```python
neg_log = -exponent - math.log10(mantissa)
```

**Comment by AsierGonzalez** [comment]
From 20.02 GWAS catalog data will be processed using the Genetics Portal pipeline and the scores are now of the `locus_to_gene` type, which is defined as a probability in the schema, so this issue no longer applies. The probability cannot be 0 either, but there are none in the current file.

**Comment by AsierGonzalez** [comment]
The issue with 0 p-values has been resolved. The values smaller than 1e-302 are capped to that value and their real value is stored as mantissa and exponent.

**Comment by d0choa** [comment]
Pending FE action in #816.
