### ISSUE TITLE
19.02 release candidate: Some target profile page sections for ITGAL not loading

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#435]
The following target profile page sections for ITGAL not loading in QA currently: https://qa.targetvalidation.org/target/ENSG00000005844

Variants, isoforms and genomic context
Protein structure
Gene tree

All relevant sections (no data expected for biomarkers or hallmarks) load in production currently without issue. https://www.targetvalidation.org/target/ENSG00000005844

**Comment by LucaFumis** [comment]
All relevant sections in above example should work now.

**Comment by ElaineMcA** [comment]
Reviewed and release ready on QA.  Thanks.
