### ISSUE TITLE
Remove GProfiler from nginx proxy

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#437]
As part of the fix for https://github.com/opentargets/platform/issues/430, the PR https://github.com/opentargets/webapp/pull/300 calls the new GProfiler API directly. As a result, the proxy settings in the `rest_api` can be removed. See https://github.com/opentargets/rest_api/blob/c8cac0c24c7bd15902c83233447a590d1823e0f0/docker/nginx-proxy.conf#L134-L152. It is highly unlikely the proxy adds much of a speed up for users, since batch search queries to this service are all likely to be different.

This should not be removed before the 19.04 release so as to give time to assess the changes.

**Comment by afaulconbridge** [comment]
moving to 19.06 since it needs to be "not before" 19.04
