### ISSUE TITLE
Showing 1 to 50 of N targets

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#439]
Hello,

I was testing the interface this morning on the disease association page.
there is one small bug with the target list filter.
If I load a list of 49 targets, the filter works but the text in the association view is not updated.
It will indicated "Showing 1 to 50 of N targets" with N being the total number of associations for the disease not the 49 targets that I've loaded.

**Comment by ElaineMcA** [comment]
Could we add this to the 19.02 release?  Not high priority so can be mini release.  @LucaFumis thanks as always.

**Comment by LucaFumis** [comment]
Hi Gautier,
this seems to be the same as https://github.com/opentargets/platform/issues/414 and should be fixed in `qa`.
Could you please try out `qa` with your specific example/list?

**Comment by ElaineMcA** [comment]
Reviewed on QA with a few sample lists and release ready.
