### ISSUE TITLE
New drug for Huntington Disease

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#44]
@ckongEbi commented on [Fri Dec 15 2017](https://github.com/opentargets/data_release/issues/51)

There is a new drug ONIS-HTT(Rx) in initial trial phase for Huntington Disease. 

[http://www.aljazeera.com/news/2017/12/drug-offers-hope-treating-huntington-disease-171211145705425.html](url)

This is the clinical trial:

[https://clinicaltrials.gov/ct2/show/NCT02519036](url)

We need to ensure it comes through our ChEMBL data feed. 

cc: @deniseOme, @iandunham 

---

@deniseOme commented on [Fri Dec 15 2017](https://github.com/opentargets/data_release/issues/51#issuecomment-351970708)

Thanks @ckongEbi for logging this after my email. As I said, the drug is supposed to target the HTT gene. 

Shouldn't this be in ChEMBL already as the start date of clinical trial is 2015?

---

@ckongEbi commented on [Fri Dec 15 2017](https://github.com/opentargets/data_release/issues/51#issuecomment-351978175)

@deniseOme, they might have the trials in their database but as this drug/MOA is not in ChEMBL currently, the link to create the JSON is missing. 

---

@ckongEbi commented on [Tue Dec 19 2017](https://github.com/opentargets/data_release/issues/51#issuecomment-352751528)

ChEMBL will update once they have more news. No expected date provided for now. 

---

@ckongEbi commented on [Mon Jan 22 2018](https://github.com/opentargets/data_release/issues/51#issuecomment-359417758)

should feed through the data feed once ChEMBL_24 released in Feb. But might not get into OT 18.02 release though.  

---

@ckongEbi commented on [Fri Apr 13 2018](https://github.com/opentargets/data_release/issues/51#issuecomment-381165476)

The drug will get into ChEMBL but not OT for the reason below. 
@deniseOme 
On 13/04/2018 09:28, Maria Paula Magarinos wrote:
> Hi ChuangKee,
>
> The drug is not in ChEMBL yet. We are working in a process to load compounds from Clinical Trials into ChEMBL when necessary. However in this particular case, because the target of the drug is not a protein but RNA, the target won’t have a Uniprot ID and therefore it won’t be included in the JSON fie.
> Cheers,
Ok , we will take note, thanks!
>
>
> Paula
>

---

@iandunham commented on [Fri Apr 13 2018](https://github.com/opentargets/data_release/issues/51#issuecomment-381171300)

Our model doesn't specify the modality that is used to modulate the target. So we treat all modalities (through protein or RNA, or anything else) as mediated through the conceptual entity of 'target'. The target has a uniprot id in this case (for the HTT protein) so they could use that, or if they don't wnat to do that they can use the Ensembl gene id

---

@ckongEbi commented on [Fri Apr 13 2018](https://github.com/opentargets/data_release/issues/51#issuecomment-381171638)

@iandunham right, will revisit when they get the compound into ChEMBL 

---

@iandunham commented on [Fri Apr 13 2018](https://github.com/opentargets/data_release/issues/51#issuecomment-381172374)

There might be other drugs that they are not annotating with a target for this reason - would be worht reopening the discussion with them soon.

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_release/issues/51#issuecomment-403864926)

@MichaelaEBI @ElaineMcA @iandunham post-discussion with ChEMBL. They are still working on adding this new drug to ChEMBL , while we agree to try to use the ENSG id for the RNA target

**Comment by MichaelaEBI** [comment]
This data is still not in Open Targets. I will follow up on it.

**Comment by MichaelaEBI** [comment]
I am not sure whether IONIS-HTTRx has been added to ChEMBL yet, it is [not listed as targeting the Huntingtin protein](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL5514/). As of 19.09 we receive data for 4 mRNA drug targets, but the Huntingtin gene (ENSG00000197386) is not among them. One of these 4 mRNA targets, Dystrophin pre-mRNA, is submitted as evidence with Ensembl ID ENSG00000198947 and a [ChEMBL Target Report Card](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL3826826/) exists. No Target Report Card exists for Huntingtin (pre-)mRNA.
