### ISSUE TITLE
LINK API /data endpoint returns 502

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#444]
The LINK API is currently returning a 502 for the /data endpoint. This is not used in the www.targetvalidation.org site, but is used in link.opentargets.io, making the latter not functional.

An example call (for BRAF): http://link.opentargets.io/data?query=ENSG00000157764

**Comment by peatroot** [comment]
This is temperamental. Sometimes a successful response is received, sometimes not. Perhaps a timeout issue?

**Comment by afaulconbridge** [comment]
I suspect one of the three elasticsearch nodes has hit a memory leak limit. I'll reboot them one at a time, and then we can see if this persists.

**Comment by afaulconbridge** [comment]
I've rebooted the nodes, but they are all short of disk space. I've reduced it to zero replicas to free some space, and elasticsearch is now reallocating the shards between the servers. I'll give it a few days to settle down, then force merge the indexes (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-forcemerge.html) which should save space again, and then reenable the single replica.

**Comment by afaulconbridge** [comment]
Ticket opentargets/platform#447 is related.

**Comment by afaulconbridge** [comment]
The elasticsearch cluster is back to "green" status, but with a single replica. I'm going to let it settle down for a few hours and see if the api url http://link.opentargets.io/data?query=ENSG00000157764 becomes functional again - currently it is not.

**Comment by afaulconbridge** [comment]
This seems to be back now. I'm going to close this ticket fo rnow - please re-open if this issues re-appears in the near future.
