### ISSUE TITLE
Roadmap: Streamline existing ontology code for migration to EFO 3 and MONDO

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#446]
## Description
* [ ]  **WHY - What is the problem this feature would answer?**
  Multiple ontologies are referenced by Open Targets (e.g. EFO, HPO, MP) to assure consistent mapping across different data sources.
  As part of maintenance plans, the intention is to review both current process and code to simplify and separate from the main data pipeline code as well as resolve any open maintenance tickets and improve mapping and coverage.

* [ ]  **HOW are we going to solve the problem?**
Step 1:
Separate ontology code from data pipeline code, assuring QC checks versus existing code in use are in place and extended.

Step 2:
Review phenotype categories - in order to enable a common highest level categorisation to be used to map across all of the ontologies.

Resultant updates for disease profile page and target profile pages will be scoped as appropriate.

Future step:
Consider extending Disease profile page to include similar phenotypes (in addition to similar diseases).

**Comment by d0choa** [comment]
Additional information about how every datasource implements the mapping can be found here:
https://docs.google.com/spreadsheets/d/1vtDB7reA8-IDcgJSqjoL5e_JkyqY8728XVYnJW-qBj4/edit#gid=0

Harmonisation will be part of the new data submission guidelines. We'll generate tickets accordingly
