### ISSUE TITLE
Bibliography sections on target profile page and disease profile page not loading

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#447]
### Description

The `Bibliography` sections on the target profile page and disease profile page are not loading properly. Instead, the UI displays an empty space and the console log identifies a number of errors.

_Platform interface:_

![screen shot 2019-02-19 at 16 20 00](https://user-images.githubusercontent.com/7490258/53030212-4d4f6900-3462-11e9-9bd1-861f20edd29a.png)

_Browser console log:_

![screen shot 2019-02-19 at 16 22 54](https://user-images.githubusercontent.com/7490258/53030411-a5866b00-3462-11e9-88cf-1a595c3a52ca.png)

### Environment:

Safari, Chrome, Firefox

**Comment by peatroot** [comment]
Likely related to https://github.com/opentargets/platform/issues/444.

**Comment by afaulconbridge** [comment]
I think library/link has recovered to a point where this problem is solved. Please re-test and confirm.
