### ISSUE TITLE
quantitative data for genes on which cell types they are expressed in

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#45]
@elipapa commented on [Fri Jan 12 2018](https://github.com/opentargets/data_release/issues/55)

@elipapa commented on [Tue Feb 21 2017](https://github.com/opentargets/platform_issues/issues/9)

> I'd like to see quantitative data for genes on which cell types they are expressed in. For example, "Gene A" is expressed highly in "Cell type B" but not at all in "Cell type C".

---

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_issues/issues/9#issuecomment-281212821)

Quantitative expression data could be extracted from http://www.immgen.org/databrowser/index.html for lymphocytes and http://servers.binf.ku.dk/bloodspot/ for other blood cells

---

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_issues/issues/9#issuecomment-296716747)

@ckongEbi will ask/compare with expression atlas submission

---

@ckongEbi commented on [Tue Apr 25 2017](https://github.com/opentargets/platform_issues/issues/9#issuecomment-296963061)

@elipapa can you move this to data-providers repo https://github.com/opentargets/data-providers-docs/issues, i take it up with atlas

**Comment by ElaineMcA** [comment]
@iandunham  - Ian, is this still relevant and how does this differ from the data we have in the platform already?

**Comment by iandunham** [comment]
It's a variant of what we have now. File under future enhancements of expression data (if you have such a topic)

**Comment by d0choa** [comment]
We'll review these ideas in the context of scRNAseq baseline expression. We'll prioritise using the data through ExpressionAtlas if possible
