### ISSUE TITLE
Remove apiproxy.opentargets.io

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#450]
In the GCP project open-targets-prod there is a DNS name for apiproxy.opentargets.io but this is no longer required in the production infrastructure post 19.02

This should eventually be retired, but note that anyone running pre-19.02 instance of the platform will need to update and therefore this change will need to be coordinated with partners.

**Comment by andrewhercules** [comment]
@afaulconbridge, given we've had a number of releases since 19.02, could we retire this and close the ticket?

**Comment by afaulconbridge** [comment]
Yes. In case we need this in future, the settings are:
```
apiproxy.opentargets.io. NS 21600  ns-cloud-e1.googledomains.com.
                                   ns-cloud-e2.googledomains.com.
                                   ns-cloud-e3.googledomains.com.
                                   ns-cloud-e4.googledomains.com.
apiproxy.opentargets.io. SOA 21600 ns-cloud-e1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300
```
