### ISSUE TITLE
Roadmap: Improve drug coverage within platform

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#451]
### **Objective**
Improved handling of drug data and increased drug coverage in OT Platform (DrugBank/PubChem, drug combinations, non-protein targets)

**Use cases**
_**1. Aggregate drug evidence**_
- Drug index can return data aggregated by phase and status
- Drug index that can be queried for all drugs for a specific target

_**2. Show all drugs in batch search**_
- See 1.

_**3. Consistent OT API responses (= consistent data!)**_
- Populate drug index with ChEMBL API endpoints which should be consistent with evidence strings (to be investigated and discrepancies resolved)

_**4. Reduce use of external APIs**_
- See 3.

_**5. Show partner compounds**_

_**6. Improve search**_
- Improve mapping of drug brand names to generic names
- Allow users to search by different drug IDs (ChEMBL and/or internal partner IDs)
- Provide user with direct way to access drug summary page

_**7. Increase drug coverage**_
- More than 2,000 drugs with unknown target(s) are currently not in OT platform

### **How:**
The implementation has been planned in distinct iterations:

_- [ ] Iteration 1: Drug Summary Page focus_ : Release 19.06 . #589 

- Review and re-design the drug summary page (conferring with partners)
- Facilitate the addition of private data in partner private instances
- First implementation of a drug index to feed the data for this page
- Work with ChEMBL to include additional data via their submissions and enable opportunity to aggregate as part of next iteration.

_- [ ] Iteration 2:  Aggregation of data_ : Release 19.09 #682 

_- [ ] Iteration 3:  Fine tune search capability_

Further iterations will be summarised/update as required

**Comment by ElaineMcA** [comment]
Refresh on implementation plans for this epic scheduled for 11Mar2019 team meeting.

**Comment by ElaineMcA** [comment]
Investigations on aggregation completed as part of 19.09 activities.  Concerns related to scalability remain therefore, technical implementation will be reviewed and plan formulated for 19.11

**Comment by d0choa** [comment]
While some of this tasks are still ongoing, they have been reassigned to other epics
