### ISSUE TITLE
update opentargets-py author information

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#453]
Andrea is still listed as a contact and author for the opentargets-py client documentation. This should be updated to general "open targets core team" and support email

**Comment by deniseOme** [comment]
Well spotted. Perhaps we should have Open Targets Platform team instead of Open Targets Core team as there is Genetics core team as well...

I think we should still acknowledge Andrea though.

**Comment by afaulconbridge** [comment]
Andrea is still listed as the commit author in the git repository, so anyone can see exactly who did what if they are interested.

This has been merged as opentargets/opentargets-py#33 - we can do another PR if there are further changes needed.
