### ISSUE TITLE
batch search results no longer filtered down to list of targets in the file

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#454]
Use any list of targets in the batch search tool e.g. the sample list.

When clicking on the disease name, the **expected** behaviour is to go to the associations page of the chosen disease and see the heat map table showing **only** the targets from my list, rather than the overall number of targets.

The URL seems to be correct i.e.
https://www.targetvalidation.org/disease/EFO_0003767/associations?targets=143365,130592,116288,73756,143622,105397,134882,111424,178623,169508,100368,133703,95110,100311,108094,163285,113327,107968,198369,108219,108423,181915,108688,119919,116833,171522,95303,178828,79263,85978,138031,153064,179344,115232,109787,169220,197114,105401,197272,151151,189067,167207,164512,164308,5844,162594,133195,245105,187796,114859,111537,181634,12779,103375,182256,90339,231160,198763

But somehow when this is displayed it is as if the URL were https://www.targetvalidation.org/disease/EFO_0003767/associations
with all associations and no filter applied.

This was working prior to the new release.

Reported by one of our users, who provided the following images.
![image001](https://user-images.githubusercontent.com/6472381/53372046-c6126180-3949-11e9-8688-8fd6dcfea9d9.jpg)
![image002](https://user-images.githubusercontent.com/6472381/53372048-c6aaf800-3949-11e9-90de-dea21f048f42.jpg)

**Comment by LucaFumis** [comment]
Thanks @deniseOme. I suspect this was introduced when I fixed the target list bug as they both appeared to share URL parameters: the handling of these was updated for the target list but obviously not for the batch search.
