### ISSUE TITLE
landing page to https://platform-api.opentargets.io

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#455]
We must be showing a better landing page at that uri. I guess we have here the same problem with genetics-api landing page at that uri

**Comment by afaulconbridge** [comment]
Is this a real issue? Has any user gone there and not understood the response? I don't think this is worth investigating.

**Comment by mkarmona** [comment]
@afaulconbridge it is not worth at all. it says release 19.06 and priority low. It is more cosmetic changes than another thing. As OT, having a unified face or a proper redirect. I noted it here just to keep it as something to have a look if enough time or too easy to place a static HTML file @andrewhercules

**Comment by andrewhercules** [comment]
@mkarmona, is there an HTML file I can directly edit? Or would it be better for me to make a separate file and send to the back-end team to add to the API site?

**Comment by mkarmona** [comment]
@andrewhercules there is no single html at all; I do serve a template from genetics-api but no single html from platform-api. But please, this is low priority, just kick it forward at the moment.

**Comment by d0choa** [comment]
No action is expected for the REST API. We'll address for the new API currently under development
