### ISSUE TITLE
Bug when visualizing targets associated to a disease for the first time

### ISSUE THREAD

**Issue by oplantalech** [opentargets/platform#456]
## Problem description
I have installed Open Targets and when I select a disease for the first time, I see a page with no information regarding its associated targets:
![screenshot](https://user-images.githubusercontent.com/20278013/53481860-41752f80-3a7e-11e9-845b-74bb4b84e503.png)

If I look at the console, I see a failing request to `api/v3/platform/public/association/filter` which responds with this message: "Too many requests. Please look at the "X-Usage-Limit-Wait" header for the time to wait for an other call."

If I refresh the page then it renders correctly.

## Information about the installation
Docker setup with 3 containers:

- container for Elasticsearch, with an image based on Elasticsearch 5.6.13 but with the X-Pack plugin uninstalled.
- container for the open targets api, using the following image: quay.io/opentargets/rest_api:18.12.0
- container for the open targets app, using the following image: quay.io/opentargets/webapp:v3.10

**Comment by LucaFumis** [comment]
Hi Oleguer,
I just had a chat about this with @mkarmona. There had been some code updates in regards to the `X-Usage-Limit-Wait` and the version you're using is probably prior to this.
We suggest you try running the latest 18.12 version, which is `18.12.6`. 
Do let us know how it goes.

Kind regards,
Luca

**Comment by oplantalech** [comment]
Hi Luca,
I have tested the version `18.12.6` and it does not seem to have the bug anymore.

Thanks for the quick reply and the help. I will close this issue.

Regards,
Oleguer
