### ISSUE TITLE
Revisit ontology visualization for EFO3

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#457]
Moving to EFO3 means that the ontology hierarchy will be richer (more intermediate nodes, more paths).

Currently the ontology visualisation always keeps all nodes on screen. 

This means that for many terms the text on the visualization is too small to be legible.

Compare the old version:

![EFO2 brain disease visualization](https://storage.googleapis.com/open-targets-efo-3/brain_disease-graph.old.png)

with the new version:

![EFO3 brain disease visualization](https://storage.googleapis.com/open-targets-efo-3/brain_disease-graph.new.png)

**Comment by afaulconbridge** [comment]
One solution might be to replace the widget with the one used by OLS e.g. https://www.ebi.ac.uk/ols/ontologies/efo/terms/graph?iri=http://www.ebi.ac.uk/efo/EFO_0005774

**Comment by ElaineMcA** [comment]
@andrewhercules: thoughts?
Adam plans to have a backend with EFO3 working that people can test by end of this week.  Something we can raise with Ian @ Monday meeting also in terms of priority relative to other work items.

**Comment by andrewhercules** [comment]
For now, we will leave the visualisation as-is but will update the disease profile page so that the Classification tab is not automatically open when a user visits the disease profile page. If I take a cursory glance at Google Analytics, it looks like the majority of our users close that tab when they visit the disease profile page.

Once we start the front-end rewrite of the disease profile page, we'll likely consider switching to the OLS viewer because it handles other types of directed acyclic graphs (e.g. GO).

@afaulconbridge, just to confirm, we're shipping EFO3 in the next release? If so, I'll update the 19.04 release intentions with a ticket to collapse the Classification tab on page load.

**Comment by afaulconbridge** [comment]
@andrewhercules yes, that's the plan and currently I don't see any blockers to that.

**Comment by afaulconbridge** [comment]
Another example of this is diabetic retinopathy,  EFO_0003770

Compare the old version:

![EFO2 brain disease visualization](https://storage.googleapis.com/open-targets-efo-3/diabetic_retinopathy-graph.old.png)

with the new version:

![EFO3 brain disease visualization](https://storage.googleapis.com/open-targets-efo-3/diabetic_retinopathy-graph.new.png)

**Comment by andrewhercules** [comment]
Thanks for confirming @afaulconbridge. 😄  

I suspect that for many diseases, we'll see a similar increase in the complexity of the visualisation. I've created a placeholder ticket - #462 - which I'll update with details on collapsing the Classification tab on page load. We'll implement for 19.04 and look to build a more scalable solution for the Classification widget on the new dashboard layout.

**Comment by afaulconbridge** [comment]
Moving to 19.06 since we've reverted to EFO2 for 19.04

**Comment by ElaineMcA** [comment]
FE meeting 08May2019:

Graph option/ prepared by Gareth to potentially solve challenge above. 

@peatroot, Please add links to your notebook to share here:

Note: Tree on associations page could also use this same graphical approach as basis and is more urgent to fix for users as we move to EFO 3 (versus "classification" visualisation on Disease Profile page).

Next steps:
- Develop further for tree view replacement and confirm performance
- If performant, test designs via UX once ready

**Comment by peatroot** [comment]
[EFO v2](https://observablehq.com/@peatroot/efo-visualisation)
[EFO v3](https://observablehq.com/@peatroot/efo-visualisation-v3)

**Comment by d0choa** [comment]
Work complete as part of EFO3 migration finished in 19.11
