### ISSUE TITLE
Add new Target Enabling Package to teps-service.js file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#458]
A new TEP has been added to the listing of available TEPs on [the SGC's TEP website](https://www.thesgc.org/tep). Can we please add the following to the `webapp/app/src/services/teps-service.js` file for the 19.04 release?

MLLT1 - ENSG00000130382

**Comment by MichaelaEBI** [comment]
**May 2019:** A [new TEP](https://www.thesgc.org/tep/galt) has been added for GALT and its upstream enzyme GALK1. This TEP will look at both proteins, so the TEP link should be added to both proteins:

GALT: ENSG00000213930
GALK1: ENSG00000108479

**Comment by MichaelaEBI** [comment]
Re-opening this ticket with updated comment above.

**Comment by andrewhercules** [comment]
Changing to 19.06 release @LucaFumis and @ElaineMcA

**Comment by deniseOme** [comment]
@MichaelaEBI @ElaineMcA @d0choa , there are four new TEPs that should be updated for 19.09:

- ANO10 aka TMEM16K(ENSG00000160746)
- KLHL20 (ENSG00000076321)
- KEAP1 (ENSG00000079999)
- ALAS2 (ENSG00000158578)

Perhaps before including these (up-to-date as as per today), we should checke if SGC increases its [available TEPs](https://www.thesgc.org/tep) over the summer.

**Comment by AsierGonzalez** [comment]
The four TEPs mentioned above by @deniseOme need to be added yet and there are two other new ones:

- KALRN (ENSG00000160145) 
- RAC1 (ENSG00000136238)

Note that in order to add these two TEPs issue #712 needs to be solved as this is one TEP targeting a protein complex so the URL for both of them is https://www.thesgc.org/tep/kalrnrac1.

**Comment by andrewhercules** [comment]
As mentioned in #712, I have added links to the TEPs data to ensure that users are directed to the correct page on the SGC website.

@LucaFumis, can you please use this file - [TEPs_file_with_links.zip](https://github.com/opentargets/platform/files/3573765/TEPs_file_with_links.zip) - to replace the current data found in the [teps-service.js file](https://github.com/opentargets/webapp/blob/master/app/src/services/teps-service.js)? 

The new file includes a `link` attribute, which you can use to generate the link to the respective SGC TEP page. I tested all of the links and they direct users to the correct page.

**Comment by MichaelaEBI** [comment]
I just got an email from Shauna at SGC: 

We have set up the redirects on our end so that:
https://www.thesgc.org/tep/galt, https://www.thesgc.org/tep/galk1 and https://www.thesgc.org/tep/galt-galk1 redirect to https://www.thesgc.org/tep/galtgalk1

https://www.thesgc.org/tep/kalrn and https://www.thesgc.org/tep/rac1 redirect to https://www.thesgc.org/tep/kalrnrac1

**Comment by ElaineMcA** [comment]
Pushed with 19.09 release on 24-Sep-2019.

**Comment by AsierGonzalez** [comment]
There is a new TEP for `TASK1` (`KCNK3` in OT): https://www.thesgc.org/tep/task1.
This should be added into https://github.com/opentargets/webapp/blob/master/app/src/services/teps-service.js:
```
ENSG00000171303: {
                id: 'ENSG00000171303',
                symbol: 'KCNK3',
                link: 'https://www.thesgc.org/tep/task1'
}
```
Can you please look into it @LucaFumis?

**Comment by AsierGonzalez** [comment]
A new TEP has been added for `MTHFR`. If @LucaFumis, you could kindly add the following to the usual place, please:

```
ENSG00000177000: {
                id: 'ENSG00000177000',
                symbol: 'MTHFR',
                link: 'https://www.thesgc.org/tep/mthfr'
}
```
