### ISSUE TITLE
Python2 End of life

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#459]
Python2.7 will stop being supported from 1st Jan 2020 and this includes a number of library etc too https://pythonclock.org/

We should move to python3 for all code, and https://python-future.org/futurize.html can help us to do that while also being compatible with python2 in the mean time.

**Comment by pieterlukasse** [comment]
+1 for moving the code.
Question: why would we want to stay compatible with python 2?

**Comment by afaulconbridge** [comment]
The though process is is that it would be too big to move everything at once - so it would be better to do a multi-step process of gradually improving python3 compatibility on a stage-by-stage basis while maintaining python2 compatibilty.

**Comment by afaulconbridge** [comment]
Started work on branch af-py3-futurize

**Comment by hammer** [comment]
@afaulconbridge are you targeting a particular release for this work?

**Comment by d0choa** [comment]
All the pipeline currently runs on Python3. It doesn't mean all dependencies meet this criteria
