### ISSUE TITLE
Latest data pipeline release tries to fetch non-existent base data files by default

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#463]
I tried to run the latest release of the data loading pipeline that was linked to be released to us a few days ago, 19.02.1, and it almost immediately crashed as the base data files it tried to download from Google storage for that release did not exist:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/open-targets-data-releases/19.02/input/annotation-files/ReactomePathways-2019-01-09.txt
make: *** [/usr/src/app//log/out.rea.log] Error 1
Makefile:37: recipe for target '/usr/src/app//log/out.rea.log' failed
```

**Comment by fedde-s** [comment]
The URL appears in the built-in list of data URLs for the 19.02.1 release here: https://github.com/opentargets/data_pipeline/blob/19.02.1/mrtarget.data.yml#L24

**Comment by fedde-s** [comment]
I do see similarly-named files with different dates in the same bucket: https://console.cloud.google.com/storage/browser/open-targets-data-releases/19.02/input/annotation-files

Is the yaml file included in the release out of date, or have the files for the 19.02 release accidentally been taken offline?

**Comment by afaulconbridge** [comment]
Hi @fedde-s 

We've separated the configuration for the code from the configuration for the data release. This makes it easier to work with the pipeline, and easier to reproduce the data release.

If you want to run the pipeline with the 19.02.1 data you can point the code from the tagged data pipeline version (e.g. from Docker) at the data config file that we used: https://storage.googleapis.com/open-targets-data-releases/19.02/input/mrtarget.data-2019-02-05.v3.yml That file will then point to the appropriate stable URLs for reproducability. This can be done with the `--data-config` command line parameter or `DATA_CONFIG` environment variable. That URL should be included in the release notes for 19.02 and the equivalent for subsequent releases.

The python repository should only do a minimal test run by default, so people don't accidentally start downloading and  processing hundreds of gigabytes of files.

**Comment by fedde-s** [comment]
Sounds good!

How should I know to look for such a file, next time? For now, [the readme](https://github.com/opentargets/data_pipeline/tree/19.02.1#data) directed me to [a seemingly complete built-in config file](https://github.com/opentargets/data_pipeline/blob/19.02.1/mrtarget.data.yml), and running the code took that file as the default and showed me the error message above.

**Comment by fedde-s** [comment]
@afaulconbridge 
> That URL should be included in the release notes for 19.02 and the equivalent for subsequent releases.

Ah, I see, that sounds like the right place for it!

**Comment by fedde-s** [comment]
That would just leave the error message I got by using the built-in default file a minor usability issue.

**Comment by fedde-s** [comment]
@pieterlukasse what do you think?

**Comment by pieterlukasse** [comment]
@fedde-s @afaulconbridge I think that in this case it makes most sense to not have this file https://github.com/opentargets/data_pipeline/blob/19.02.1/mrtarget.data.yml in the repo, or perhaps just call it `mrtarget.data.yml.EXAMPLE` so that it is clear that it is just an example file and that it should actually not be used _as is_ by the pipeline.

**Comment by fedde-s** [comment]
I think the file hasn't been in the repo for several releases now. This issue has been fixed and the fix has been released.
