### ISSUE TITLE
Implement data table on evidence page for OTAR015 CRISPR/Cas9 data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#466]
Preliminary notes:

- Basic data table implementation
- Data table to be displayed under the `Pathways and systems biology` tab
- Cells within data table may contain link to Project Score website

Full design spec to be confirmed once data mapping is complete

**Comment by MichaelaEBI** [comment]
Proposal for table columns for the Evidence page:
- Disease (label & EFO ID)
- Links to Project Score pages for target and disease (links)
- Score
- Method*: CRISPR screens in cell lines representing the following cancers xxx, xxx and xxx. (Add links here?)
- Publication

JSON to be defined
*To be written for each of the 14 cancer/tissue types

**Comment by andrewhercules** [comment]
@LucaFumis, can we please hardcode in the PMID for Fiona's paper (30971826)?

http://europepmc.org/abstract/MED/30971826

Also, can we put all three tables - Affected Pathways, Systems Biology, and CRISPR-Cas9 (Cancer Cell Lines) - in tabs?
