### ISSUE TITLE
Batch search: drug section results do not return all UI results

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#469]
If I batch search the following list, under the analysis 'Drugs' there are 4 entries (PSMD11, PSMC6, PSMA1 and PSMB6). But if you search each gene individually, you'll see nearly every gene being associated with ~90 drugs. 

Regarding batch search and return results- can you clarify what it's returning under Drug? 

For example, using batch search on the list below, under the analysis 'Drugs' section, there are 4 entries (PSMD11, PSMC6, PSMA1 and PSMB6). 

In UI, if each gene is searched individually, nearly every gene is associated with ~90 drugs. 

Use case: I want a list of which genes are targets of which drugs using batch search function.

PSMA1
PSMA2
PSMA3
PSMA5
PSMA7
PSMB1
PSMB2
PSMB3
PSMB4
PSMB5
PSMB6
PSMB7
PSMC1
PSMC3
PSMC5
PSMC6
PSMD1
PSMD11
PSMD13
PSMD14
PSMD2
PSMD3
PSMD4
PSMD6
PSMD7
PSMD8

**Initial investigations into differing results:**

The batch search presents the following data:

https://github.com/opentargets/webapp/blob/22a48384f2fa6269c85cddc88f035f8b6f56389d/app/src/components/multiple-targets/multiple-targets-drugs-summary-directives.js

There are some inherent limitations:
(i) We assign a limit of 10,000 evidence strings on line 52, the cumulative list of genes driving the search has likely exceeded the limit of evidence strings set and so, the full list of drugs is not being returned for this section. 

(ii) We build rows in the data table within the batch search using lines 65 -111 using the response from the API.  The limitation is that on line 73, if the drug NAME exists already in the data table, it is currently counted as a "duplicated drug" even though it may indeed be linked to a different gene or a different disease.

For discussion as part of drug index - to see what might be addressed readily or at minimum added as explanation of results approach for this section as part of ongoing batch search work perhaps.

**Comment by MichaelaEBI** [comment]
@andrewhercules is this issue still relevant?

**Comment by andrewhercules** [comment]
@MichaelaEBI, yes it is still an issue and the front-end will need to rebuild aspects of this feature in the React rewrite version (and possibly in the Angular app? @d0choa):

1. Use more than 10,000 evidence strings
2. Change how the data is aggregated on the front-end under a given drug

**Comment by andrewhercules** [comment]
Adding to the 19.11 release

**Comment by andrewhercules** [comment]
This has been reassigned to the 20.02 release

**Comment by d0choa** [comment]
No action is expected in the current API
