### ISSUE TITLE
Create GraphQL API in Scala

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#472]
Key objective:
As FE rewrite work defines the GraphQL schema required for the webapp in React, plan and execute creating of a long-term production-quality GraphQL API to serve backend data from Elasticsearch and to be written in Scala

**Comment by ElaineMcA** [comment]
Review of a draft schema for TPP is currently scheduled for review at end Jun 2019.

**Comment by ElaineMcA** [comment]
BE work anticipated to commence in September timeframe.

**Comment by d0choa** [comment]
The [platform-api](https://github.com/opentargets/platform-api) is the GraphQL API that the front end team has maintained while developing the new [web app](https://github.com/opentargets/platform-app). This API was never in production.

Recently, the BE team has picked on it and started developing in Scala what it will be our future API. This project is contained in [platform-api-beta](https://github.com/opentargets/platform-api-beta). As you can see it's still early on the development of this API but you can expect a lot of activity in the next 2-3 months. It will eventually replace our production API.

Sorry about the confusion. We expanded the description of the repos to prevent future misunderstandings.

**Comment by hammer** [comment]
Thanks for the clarification! It's nice to see both OT P and OT G using Sangria for the GraphQL server.

**Comment by hammer** [comment]
@d0choa it's a sensitive topic but given that the creator and primary developer of Sangria [passed away recently](https://github.com/sangria-graphql/sangria/issues/445) and the remaining development team has had a hard time [obtaining control of the repo](https://github.com/sangria-graphql/sangria/issues/446), has there been any discussion of moving to an alternative server side library like [graphene](https://graphene-python.org/)?

**Comment by d0choa** [comment]
We are quite happy with how Sangria works at the moment and the fact that we can consistently use it in the OT P and OT G is definitely a plus. We are keen to try to use Scala in a good part of our post-pipeline steps and Sangria is fitting well in that setup. We'll look closely what happens in the next weeks/months and whether it makes sense to redirect our efforts in the future. We have the impression there is enough interest to keep the project alive, but it's hard to know at this point

**Comment by andrewhercules** [comment]
Issue pushed to 20.02 release

**Comment by andrewhercules** [comment]
Ticket closed as GraphQL API deployed as part of Alpha release. Further iterations to GraphQL API may be made as we begin to process and expose the associations and evidence data.
