### ISSUE TITLE
ChEMBL Evidence strings: Remove non-binding protein complex members

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#474]
If the binding subunit of a protein complex drug target is known, it makes sense to only retrieve evidence strings for the binding subunit instead of all subunits. When removing the other subunits, the complex_members field/list is empty which causes JSON validation to fail.

Example: This target has 3 subunits, and the binding subunit is only one of them (P23921). In the November file there are three lines. In each one there is one of the subunits as target_id, and the rest as complex_members:
```
"id":"http://identifiers.org/uniprot/P23921”
"complex_members":["http://identifiers.org/uniprot/P31350,http://identifiers.org/uniprot/Q7LG56”]

"id":"http://identifiers.org/uniprot/P31350"
"complex_members":["http://identifiers.org/uniprot/P23921,http://identifiers.org/uniprot/Q7LG56”]

"id":"http://identifiers.org/uniprot/Q7LG56"
complex_members":["http://identifiers.org/uniprot/P23921,http://identifiers.org/uniprot/P31350"]
```

Changes to the JSON schema are required for ChEMBL to implement this change.

**Comment by afaulconbridge** [comment]
Why would we get evidence strings for the other two subunits at all? Why not just get an evidence string for the binding subunit as it is at the moment, and not send the other evidence strings i.e. only send one string.

**Comment by afaulconbridge** [comment]
Work in progress at opentargets/json_schema/af-chembl-complex

**Comment by afaulconbridge** [comment]
New JSON schema available at https://raw.githubusercontent.com/opentargets/json_schema/1.6.0/opentargets.json

I believe chembl have implemented this change, so closing this ticket. Feel free to reopen if more work is required.
