### ISSUE TITLE
ChEMBL evidence: Update target_types

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#475]
Questions to this and other ChEMBL-evidence string-related issues are documented [here](https://docs.google.com/document/d/1E-bta37byB-f3lOD6DZYYkx71tbiLQgv25gAKWtKzgk/edit).

Currently 'target_type' is http://identifiers.org/cttv.target/protein_evidence in all ChEMBL evidence strings. It would be useful to retrieve the actual target type (protein, protein complex etc.). I am not sure whether the target_type field is the correct place for this information to be stored. The 'available' terms are all listed [here](https://github.com/opentargets/input_data_format/blob/master/json_schema/cttv_uris_namespaces.md#cttv-biological-activity-in-disease-ontology) and in `json_schema/opentargets.json':
```
        "target_type": {
          "type": "string",
          "enum": [
            "http://identifiers.org/cttv.target/gene_allele",
            "http://identifiers.org/cttv.target/gene_evidence",
            "http://identifiers.org/cttv.target/gene_in_LD_region",
            "http://identifiers.org/cttv.target/gene_in_epigenetic_regulation_complex",
            "http://identifiers.org/cttv.target/gene_variant",
            "http://identifiers.org/cttv.target/pro_protein",
            "http://identifiers.org/cttv.target/protein_evidence",
            "http://identifiers.org/cttv.target/transcript_evidence",
            "http://identifiers.org/cttv.target/transcript_isoform",
            "http://identifiers.org/cttv.target/protein_isoform",
            "http://identifiers.org/cttv.target/gene_or_protein_or_transcript"
          ],
          "description": "Type of target; if you do not have detailed information, select from gene_evidence, protein_evidence or transcript_evidence"
        },
```

- [x] Define terms that ChEMBL would use as target type.
- PROTEIN COMPLEX
- PROTEIN COMPLEX GROUP
- PROTEIN FAMILY
- SELECTIVITY GROUP (this one does probably not apply to ChEMBL evidence)
- SINGLE PROTEIN
- CHIMERIC PROTEIN
- PROTEIN-PROTEIN INTERACTION
- NUCLEIC-ACID

- [ ] Investigate required JSON schema change.

**Comment by MichaelaEBI** [comment]
Questions for ChEMBL:
- How/where is protein complex subunit that is bound by compound indicated?
- Is it possible to 'rank' targets?
- When are protein families targets? Are all protein members 'equal' targets?

**Comment by MichaelaEBI** [comment]
**Questions for ChEMBL**
**1. When are protein families used as a drug target?**
Protein families are only used if the drug is not binding a specific family member. In the case of amisulpride, the protein family should probably be removed from the target list.
**2. Can drug targets be ranked?**
It is not easy to rank drug targets because ChEMBL considers functional evidence in addition to binding data. This could be look into in the context of a longer-term project.
**3. Where can information about the subunit that is bound by a drug be found?**
This information can currently only be found in the binding site note in the  [Browse drug targets](https://www.ebi.ac.uk/chembl/drug/targets) tab and in the mechanism API response. However, the note does not provide ChEMBL or UniProt IDs for the actual proteins. This will be added to the mechanism API endpoint (and the evidence strings). Open Targets will change the JSON schema asap so that ChEMBL evidence strings contain only the known binding subunit (see issue #474 )
**4. Information about target types**
ChEMBL evidence strings currently contain "http://identifiers.org/cttv.target/protein_evidence" as the target type for all evidence strings (see this issue). Open Targets will discuss changing the JSON schema so that ChEMBL can provide the actual target type and this information can then be used on the front end of Open Targets to display all targets for a drug. At the moment the list of protein targets for a drug can be quite long if it targets a protein complex or a protein family.

**Comment by afaulconbridge** [comment]
Work in progress at opentargets/json_schema/af-chembl-complex

**Comment by afaulconbridge** [comment]
This is done in schema https://raw.githubusercontent.com/opentargets/json_schema/1.6.0/opentargets.json so closing
