### ISSUE TITLE
EPMC: Better handling of acronyms (Targets & Disease)

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#48]
@ckongEbi commented on [Tue Jan 16 2018](https://github.com/opentargets/data_release/issues/60)

- [ ] Explore options to compare Open Targets Library/[LINK](http://blog.opentargets.org/link/) with Europe PMC text mining (obtain data from OT Library via API etc.)

Hi CK,

 Can you ask the EMPC to fix this in their next release of the data.

Gene UCN3 has a synonym SPC and Open targets states that there are over 300 references to UCN3 and respiratory disease but the issue is that there is a lung cancer cell line called SPC-A1 and this is what is picked up by the text mining.

It’s somewhat misleading if users are checking for disease associations of targets (by headline data/numbers only).

SPC also stands for small primary cancers (SPC).I have seen other examples for other genes too.
Is there a  way of refining the text mining e.g.  to include SPC but NOT SPC-A1?

More generally, because EMPC is only mining proteins and diseases, they miss the all point about other entities (in this case SPC-A1 refers to a cell line).

That’s what Andrea tried to solve with Spacy.

If they add a dictionary of cell lines a better handling of acronyms, this would probably solve some of our problems.

Best wishes,
Gautier

cc @gkos-bio @iandunham 
 

---

@ckongEbi commented on [Wed Jan 17 2018](https://github.com/opentargets/data_release/issues/60#issuecomment-358275507)

EPMC will add this to their blacklist when generating evidence. We can extend that from the compiled TP data from integration day currently working on by @MichaelaEBI. 

A longer term acronym & cell line strategy with EPMC to be discussed.

---

@ckongEbi commented on [Thu Jan 18 2018](https://github.com/opentargets/data_release/issues/60#issuecomment-358692141)

 TP data from integration day here https://docs.google.com/spreadsheets/d/1RiYCYdD-XHPbEszQKsZvKkC2Y2utAKNj9oC_YgpWEeU/edit#gid=0

---

@ckongEbi commented on [Fri Jan 19 2018](https://github.com/opentargets/data_release/issues/60#issuecomment-359018786)

Acronym filtering to be done on OT side. 

On 19/01/2018 11:00, Chuang Kee Ong wrote:
>
> To confirm, it will be status quo for the Epmc pipeline feed, as OT work in parallel to improve the acronym recognition.
>
> @Francesco, can you point me to the current blacklist used by the pipeline?
>
> Cheers,
>
> CK
>
> On 18/01/2018 17:45, Ian Dunham wrote:
>>
>> I don't think that we can add these to a simple black list.
>>
>> We will look at what we can do based on the acronym recognition we have developed in the OT library and filter the Europmc feed after you give it to us.
>>
>> On 18/01/2018 17:27, Johanna McEntyre wrote:
>>> Hi Chuang Kee
>>>
>>> These are good examples that we should keep to feed into an improved algorithm at some point in the future.  But we do not 
>>> have the mechanisms to make such specific rules on a term-by-term basis. Rather, we would do something like: a general rule that would check first to see if a cell-line tagger would tag a gene symbol in that context, and if so, do not tag it as a gene. But we do not have the OT resources to do this kind of work.
>>>
>>> We know need to improve the precision of three-letter acronyms in general, but again, we do not have the staff to do this currently.
>>>
>>> We can run the pipeline as is and do simple things like add terms to a black list. This is what was agreed until a "next phase" is established. 
>>>
>>> Do you want us to add 
>>> - CPA
>>> - SPC
>>> - CD34
>>> to the blacklist?
>>>
>>> Thanks,
>>>
>>> Jo
>>>
>>>
>>>> On 18 Jan 2018, at 15:59, Chuang Kee Ong <ckong@ebi.ac.uk> wrote:
>>>>
>>>> Hi Jo, 
>>>>
>>>>     Whilst looking at some of the evidence, these are some examples which we have identified. We will be looking out for more, but can we get a sense of whether the below examples can be implemented in a straightforward way?
>>>>
>>>> Thanks
>>>>
>>>> CK
>>>>
>>>>  1.  http://targetvalidation.org/evidence/ENSG00000174059/EFO_0002428
>>>> FP Target Assignment:
>>>>
>>>> CD34 is a receptor, here it is used to describe a cell line ('CML CD34+ cells' or 'CML CD34 progenitor cells')
>>>>
>>>> suggestion: Add new rule check that CD34 is not directly followed by: '+', ' cell', ' progenitor cell', ' hematopoietic cell'
>>>>
>>>>   2. http://www.targetvalidation.org/evidence/ENSG00000091704/EFO_0000616
>>>>
>>>> FP Target Assignment:
>>>>
>>>> CPA1 (carboxypeptidase A1, synonym CPA) refers to various things in these papers -

**Comment by iandunham** [comment]
There are several examples of misrecognised acronyms in the text mining evidence on https://www.targetvalidation.org/disease/EFO_0008485/associations

**Comment by MichaelaEBI** [comment]
This will be addressed as part of the OTAR2056 literature project.
