### ISSUE TITLE
Drug index: Evaluate including FDA adverse events

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#481]
FDA provides bulk downloads at https://open.fda.gov/apis/drug/event/download/ These could be pre-loaded into the drug index by the pipeline to avoid the frontend having to make API calls.

**Comment by MichaelaEBI** [comment]
There is already a ticket related to FDA adverse events - I'll add this comment to that ticket: https://github.com/opentargets/platform/issues/74
