### ISSUE TITLE
EFO3: Review of changes compared to EFO2

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#484]
Running the pipeline with EFO3 results in an increase of associations from 3 to 6 million. This change needs to be investigated so that necessary adjustments can be made before the 19.04 Open Targets release.

- [x] Identify diseases that are only in the "disease" therapeutic area, and no others [AF]
This [list](https://docs.google.com/spreadsheets/d/1Wrpb0OYJ5F5dx7WNrLnPbvZmGKJ9RW3DVF2istuDeuE/edit#gid=0) has been generated by Adam.
- [x] Analyse where the new associations come from - new terms or increase in associations for existing terms [MS]
  To do this Adam needs to generate a JSON API dump

**Comment by afaulconbridge** [comment]
Dumps available at https://storage.googleapis.com/open-targets-efo-3/19.02-efo3_association_data.json.gz and https://storage.googleapis.com/open-targets-efo-3/19.02-efo3_association_data.json.gz

**Comment by MichaelaEBI** [comment]
**Analysis of diseases gained and lost**
2 diseases lost when using EFO3:
[EFO_0003935 - mental health](https://www.targetvalidation.org/disease/EFO_0003935/associations), used by ChEMBL only.
[Other disease](https://www.targetvalidation.org/disease/other) has 10,340 targets associated with it. [ChEMBL evidence for TSHR ](https://www.targetvalidation.org/evidence/ENSG00000165409/other)is all thyroid-related.
2,179 diseases gained in EFO3: the EFO IDs can be found [here](https://docs.google.com/spreadsheets/d/1D5tRCWeNw5Od-pwgiG_URzqGs-iVCQuY1hhCc16H2pY/edit#gid=0).

To be continued (will add the number of associations per new disease) ...

**Comment by ElaineMcA** [comment]
Follow-up action for @afaulconbridge specific to ePMC:
- ID new papers included in this release with new EFO3 terms - do they make sense or not?

**Comment by afaulconbridge** [comment]
"ID new papers included in this release with new EFO3 terms - do they make sense or not?" This is not a well defined question, and therefore is not something I can answer.

In the absence of a definitive way forward, I will produce a set of ePMC evidence strings in 19.04 that have diseases that were not in 19.02 evidence strings. Hopefully this will be useful to answer the appropriate question, whatever that may be.

**Comment by afaulconbridge** [comment]
File avaliable at https://storage.googleapis.com/open-targets-efo-3/epmc-2019-03-27.filtered.json.gz (~36MB)

**Comment by iandunham** [comment]
If we can sample some of the papers - 100 or so, that are identified with new EFO terms not in EFO2 , and pull out the sentences, I can check that they make sense. 

Also can we count how many of the additional papers in 19.04 vs 19.02 are to new EFO3 terms in 19.04 only, how many are to old EFO2 terms in 19.02, and how many are to old EFO2 terms but new in 19.04

**Comment by ElaineMcA** [comment]
Key decisions: 

1. Revert to 19.02  input file from ePMC in particular for 19.04 release and follow-up with ePMC team in advance of 19.06 release.

2.  To ensure that existing Open Targets features are of course retained with the move to EFO 3, whilst assuring that data is updated as committed every two months.  

To achieve this:
 
(i) we will revert to using EFO 2 for this release to allow sufficient technical time to address QC items thoroughly: #183 #578 #579

(ii) this will result in a revised release date of w/e 03May2019 - anticipated short delay of 2-3 days from our initial schedule (end April)

**Comment by afaulconbridge** [comment]
Since we've decided to use EFO2 for 19.04 I'm moving this to 19.06

**Comment by ElaineMcA** [comment]
Per meeting 17May2019:

1. need to analyse and ID associations which have only indirect evidence and assess what specific terms/nodes drive these volumes for EFO 3 and discuss internally w/Ian to confirm final "SLIM" list for curation by SPOT.

2. Discuss curation process with SPOT team in parallel.

3. Define steps and estimate work involved to implement SLIM EFO3.
