### ISSUE TITLE
Client warning about deprecated yaml.load()

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#485]
When running the client, I get a message:

/home/faulcon/ot/local/lib/python2.7/site-packages/opentargets/conn.py:299: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

We should follow this up and resolve the underlying problem.

**Comment by d0choa** [comment]
No action is expected
