### ISSUE TITLE
Cancer biomarkers data missing some EFO IDs

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#486]
The `diseases` field of the cancer biomarkers data is an array of objects of the form below.
```
{
  id: '<EFO_ID>',
  label: '<EFO_LABEL>'
}
```

Some of these objects have an empty string for the `id` field. An example is on the *KIT* page for biomarker *KIT (D816)*. API call is below.
https://platform-api.opentargets.io/v3/platform/private/target/ENSG00000157404

Unmapped diseases from example above are:
- Myelodisplasic syndrome
- Myelodisplasic proliferative syndrome

**Comment by peatroot** [comment]
Unmapped diseases from example above are:
* Myelodisplasic syndrome
* Myelodisplasic proliferative syndrome

**Comment by MichaelaEBI** [comment]
These two disease are now mapped and the EFO IDs should come through in the 19.04 release.

**Comment by MichaelaEBI** [comment]
The update did not make it into the 19.04 release - I will check and make sure it goes into 19.06.

**Comment by MichaelaEBI** [comment]
This should now be fixed with https://github.com/opentargets/data_pipeline/pull/500

Check in 19.06 data release.

**Comment by MichaelaEBI** [comment]
Checked in the [19.06 QA version](https://qa.targetvalidation.org/target/ENSG00000157404) and the links to these two diseases now work:
- Myelodysplastic syndrome
- Myelodysplastic proliferative syndrome
