### ISSUE TITLE
EFO3: Update disease mappings done by Open Targets

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#487]
With the move to EFO3, some disease mappings that were done by the Open Targets team should probably be updated to be more accurate.

**1. Identify data and annotation sources that are affected and then update the mappings.**
 - annotation
   - [ ] Cancer Biomarkers
   - [ ] Target safety - adverse reactions
 - evidence
   - [ ] PheWAS
   - [ ] PROGENy
   - [ ] SLAPEnrich
   - [ ] genomics england
 - Others ...

**2. Look into automating the mapping process**

**Comment by afaulconbridge** [comment]
Related to #420 Update disease mapping for PheWAS

**Comment by afaulconbridge** [comment]
Related to #357 Improve ontology mapping

**Comment by afaulconbridge** [comment]
Related to #143

**Comment by d0choa** [comment]
After the update to EFO3 (19.11), a few datasources can benefit from the extended dictionary of annotations. We covered the most relevant ones and the rest of updates will come as a consequence of updating the corresponding datasources.
