### ISSUE TITLE
WORKERS_NUMBER variable not listed in data pipeline step log

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#489]
Each mrtarget command starts by logging the environment variables that will affect how it runs, and the default values for some of the options not specified:

```
Command Line Args:   --as
Environment Variables:
  DATA_CONFIG:       /mnt/load-custom-data.yaml
  ES_PREFIX:         19.02
  ELASTICSEARCH_NODES:ot-es:9200
Defaults:
  --log-config:      mrtarget/resources/logging.ini
  --redis-host:      localhost
  --redis-port:      6379
  --val-workers-validator:4
  --val-workers-writer:4
  --val-queue-validator-writer:1000
  --metric-file:     release_metrics.txt
```

This list does not include the `$WORKERS_NUMBER` environment variable when it's set, even though [several steps are affected by it](https://github.com/opentargets/data_pipeline/blob/19.02.1/mrtarget/Settings.py#L98).

**Comment by fedde-s** [comment]
I see that there have been [efforts to implement seeming replacements for this variable](https://github.com/opentargets/data_pipeline/pull/461/files#diff-2af26c82f9dec804f9156931593f463fR67). Does that mean that future major releases of the pipeline will no longer be affected by the variable?

**Comment by afaulconbridge** [comment]
Yes, this is indeed an issue for 19.02.1 as a temporary side-effect of the new configuration.

For 19.04 and onwards, the number of workers is customizable per stage and per part of each stage, and described in the debug output and `--help` output too. The relevant environment variables are below, though they will also be configurable in a ops YAML file or via the command line.

 - `VAL_WORKERS_VALIDATOR`
 - `VAL_WORKERS_WRITER`
 - `AS_WORKERS_PRODUCTION`
 - `AS_WORKERS_SCORE`
 - `DDR_WORKERS_PRODUCTION`
 - `DDR_WORKERS_SCORE`

The `WORKERS_NUMBER` variable will be removed as a stand-alone envidonment variable

**Comment by afaulconbridge** [comment]
@pieterlukasse @fedde-s can you confirm if this issue is resolved sufficiently, and if so close this issue please?

**Comment by afaulconbridge** [comment]
In the absense of confirmation, I'm closing this issue. Feel free to re-open if you need more information.

**Comment by fedde-s** [comment]
19.04 has not yet been released as far as I'm aware, so no, it has not yet been resolved.
