### ISSUE TITLE
Drug index: Add withdrawn drug information to ChEMBL evidence

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#49]
@ckongEbi commented on [Thu Jan 18 2018](https://github.com/opentargets/data_release/issues/61)

Expand the ChEMBL evidence to capture withdrawn drug information, 

https://www.ebi.ac.uk/chembl/api/data/molecule/?format=json&molecule_chembl_id=CHEMBL408

and down score it when we are doing the processing. 

---

@ckongEbi commented on [Mon Jan 22 2018](https://github.com/opentargets/data_release/issues/61#issuecomment-359414972)

@iandunham , from the discussion with chEMBL, we could have

1) **drug withdrawal** information - which we can add it into the drug profile page?
https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL408
![screen shot 2018-01-22 at 12 49 19](https://user-images.githubusercontent.com/6169985/35221607-af77f852-ff72-11e7-96e1-a62393f61053.png)

2) **clinical trials** withdrawal information - assume this is what we need for down scoring (this information is already in our current JSON), as the examples shows, withdrawal might not completely due to efficacy issue. 
https://clinicaltrials.gov/ct2/show/NCT01478308?id=%22NCT01478308%22&rank=1

---

@iandunham commented on [Mon Jan 22 2018](https://github.com/opentargets/data_release/issues/61#issuecomment-359419537)

The first option is fine. 

However for the second what we want is to get is not the clinical trial status of withdrawn, which is as you say is an assessment of the state of a particular trial. This could be for several reasons, including trivial ones we are not interested in. However if there is an efficacy reason given that would be useful to us.

However the main point was that we should get the fact that a drug has been withdrawn for a particular disease, as described in the withdrawn database, to affect the overall scoring. I suggested putting this in the clinical trials status as a quick fix bit this has obviously caused confusion. Instead we could make a new field e.g. Withdrawn_status and fill this in with the withdrawal information. We could then use the presence of this field to down weight evidence on a drug

---

@iandunham commented on [Mon Jan 22 2018](https://github.com/opentargets/data_release/issues/61#issuecomment-359421553)

So we should do the first, but we also want the drug evidence to have a withdrawn status if it has been flagged in the withdran database 

---

@ckongEbi commented on [Mon Jan 22 2018](https://github.com/opentargets/data_release/issues/61#issuecomment-359445259)

As a first step we will add the 'drug_withdrawal' information in the JSON feed (drug section) 
https://www.ebi.ac.uk/chembl/api/data/drug?molecule_chembl_id=CHEMBL408&format=json
, we could then decide how to down-weight evidence with this drug presence. 

---

@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/data_release/issues/61#issuecomment-359767553)

JSON schema updated for ChEMBL to populate withdraw drug information in the data feed.

![screen shot 2018-01-23 at 11 49 19](https://user-images.githubusercontent.com/6169985/35274377-d3a8cf5a-0033-11e8-8b62-11287369bb5d.png)

---

@ckongEbi commented on [Mon Mar 12 2018](https://github.com/opentargets/data_release/issues/61#issuecomment-372288569)

initial exploratory analysis done on `18.04` for @iandunham to explore further

1) Total evidence with T-D that has at least 1 link with withdrawn drugs => 10234
2) Unique T-D that has at least 1 evidence with withdrawn drugs => 388
3) Unique T-D that has more than 1 evidence with withdrawn drugs => 284.  

dunham [11:46 AM]
Can you get together a spreadsheet of these examples (the ones in points 2 and 3) with links to the platform evidence pages for each, please? I'd like to investigate further.

**Comment by MichaelaEBI** [comment]
Withdrawn information has been added and removed from ChEMBL evidence and can now be found in the Drug index.
