### ISSUE TITLE
Target profile page rewrite: Replace uses of OtTable with OtTableRF

### ISSUE THREAD

**Issue by mirandaio** [opentargets/platform#490]
Replace uses of OtTable with OtTableRF throughout the code base.

**Comment by andrewhercules** [comment]
Closing this ticket as when I run [a search for `OtTable` in the platform-app repo](https://github.com/opentargets/platform-app/search?q=OtTable&unscoped_q=OtTable), it returns no results.

@mirandaio, please re-open if there are other instances that need to be changed
