### ISSUE TITLE
JSON decode error at --ddr(?) step

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#493]
Found this error, I believe in --ddr step (see part where it says `19.02_relation-data`):
```
":201}},{"index":{"_index":"19.02_relation-data","_type":"relation-shared-target","_id":"EFO_...-EFO_...","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"created":true,"status":201}},
...
,{"index":{"_index":"19.02_relation-data","_type":"relation-shared-target","_id":"EFO_...-EFO_...","_vers', 
JSONDecodeError("Expecting ':' delimiter: line 1 column 8128 (char 8127)",)).  retrying in 5s...
```
Is the --sea or --ddr step producing invalid JSON?

 (note: I removed EFO codes from log above to avoid custom data leaking out)

**Comment by pieterlukasse** [comment]
notify @afaulconbridge

**Comment by afaulconbridge** [comment]
I think this might be a network connection issue where the response from elasticsearch is truncated. See https://github.com/opentargets/data_pipeline/blob/master/mrtarget/common/ElasticsearchLoader.py#L23 for one place where the "chunk size" i.e. number of elasticsearch documents in a single request.

**Comment by pieterlukasse** [comment]
@afaulconbridge thanks. I tried with `chunk_size=200` and this does not seem to solve it. Maybe this comment helps: https://github.com/elastic/elasticsearch-py/issues/638#issuecomment-324686108?

**Comment by pieterlukasse** [comment]
@afaulconbridge setting the `range(4)` to `range(1)` (so no multi-threading) here https://github.com/opentargets/data_pipeline/blob/19.02-dev/mrtarget/modules/GeneData.py#L468, solved the issue for #498  (at least the error reported there did not occur anymore). So maybe the comment linked above is spot on.

**Comment by afaulconbridge** [comment]
Ugh, yeah that makes sense as another side-effect of `fork()`. 

For 19.04 and onwards, the multiprocessing on the --gen step has been removed, since in practice it didn't give a performance increase. This makes it more robust, since there is less opportunity for these sorts of issues.

**Comment by pieterlukasse** [comment]
Good to hear about the --gen step. Will keep this one open for tracking progress at --ddr step. Once multi-threading issues have been solved there, then I can test again to check if this issue is gone.

**Comment by afaulconbridge** [comment]
I'm going to label this as "done" meaning that it needs be retested after 19.04

**Comment by pieterlukasse** [comment]
I don't see this issue in 19.04.5 anymore.
