### ISSUE TITLE
--gen step ignoring default config file `mrtarget.ops.yml` 

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#495]
The `mrtarget.ops.yml` file has the following configuration line:
```
gen-plugin-places: [mrtarget/plugins/gene]
```
However, running the --gen step still requires it to be explicitly set as an argument to the command line, like:
```
 --gen-plugin-places mrtarget/plugins/gene 
```
This should not be necessary if the code would fall back to the defaults in `mrtarget.ops.yml`.

**Comment by pieterlukasse** [comment]
In 19.02.1. Notify @afaulconbridge

**Comment by pieterlukasse** [comment]
The confusion is in that the README states that `mrtarget.ops.yml` is a default file, while it is actually *not* used as default in `cfg.py`:
```python
    p.add('--ops-config', is_config_file=True,
        env_var="OPS_CONFIG", help='path to ops config file')
```

**Comment by pieterlukasse** [comment]
discussion results: `mrtargets.ops.yml` will continue to be a default, but with all commented out. Then other items like `gen-plugin-places` will have sensible defaults.

**Comment by afaulconbridge** [comment]
This should be done for 19.04 and opentargets/data_pipeline#476 should update documentation and example ops config

**Comment by pieterlukasse** [comment]
tested in 19.04.5 and seems to be solved :+1:
