### ISSUE TITLE
too much unused space on my screen

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#496]
My laptop screen ratio causes an association page mostly filled with whitespace by default. Can we minimise it?

![Captura de pantalla -2019-03-20 09-35-25](https://user-images.githubusercontent.com/5394232/54674348-241f0880-4af4-11e9-8c34-d0827871809e.png)

**Comment by andrewhercules** [comment]
Will be addressed with the new rewrite project - see https://platform-app.netlify.com/target/ENSG00000091831 for a sample of the new header
