### ISSUE TITLE
Baseline expression in mouse

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#50]
@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/data_release/issues/63)

Check with Atlas about whether they include these data on immune cells for v2 of the data  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE37448 

We can then include mouse cell expression data in the baseline expression and/or we can develop a comparative display like this one 

http://rstats.immgen.org/comparative/comparative_search.php?human_symbol=CD4&probeset_id=203547_at&mouse_symbol=CD4&pearson=-0.216967&human_module=979&mouse_module=72&species=human. 

we need to work with immunologists to decide what are suitable profiles of cells they need.

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_release/issues/63#issuecomment-403788600)

We need to scope out more details about what we need and use cases of the mouse baseline data.

**Comment by MichaelaEBI** [comment]
Out of scope for now.
