### ISSUE TITLE
PROXY configuration unclear

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#501]
Proxy configuration documentation is currently unclear and incomplete in [webapp](/opentargets/webapp).

**Comment by pieterlukasse** [comment]
Notify: @afaulconbridge 

I tried to propose some improvements here: https://github.com/opentargets/webapp/pull/303/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by pieterlukasse** [comment]
One question I had regarding the PROXY config: are only certain domains allowed? I tried using the proxy prefix to fetch some data from an internal server and this failed.

**Comment by afaulconbridge** [comment]
Correct. You would need to add them to nginx_conf/nginx.template

**Comment by afaulconbridge** [comment]
Correct. The webapp /proxy should redirect to the proxy that is (as of 19.02) built into the rest api, which is where the additional domains would need to be added. https://github.com/opentargets/rest_api/tree/master/docker

**Comment by pieterlukasse** [comment]
aha! Thanks! Should we document this in [webapp](/opentargets/webapp)?

**Comment by afaulconbridge** [comment]
I think the full documentation should be in rest_api but yes it should also be mentioned in the webapp. Do you want to update your existing PR a bit?

**Comment by pieterlukasse** [comment]
@afaulconbridge ok, yes, I will update https://github.com/opentargets/webapp/pull/303 a bit.

**Comment by pieterlukasse** [comment]
@afaulconbridge updated the PR.

**Comment by pieterlukasse** [comment]
@afaulconbridge I also made this one https://github.com/opentargets/rest_api/pull/187

**Comment by pieterlukasse** [comment]
@afaulconbridge I added this one as well to make the configuration easier at runtime: https://github.com/opentargets/rest_api/pull/188

**Comment by afaulconbridge** [comment]
These PRs have been merged now (303 is approved but pending final merge), so I think this is complete? What do you think @pieterlukasse ?

**Comment by pieterlukasse** [comment]
excellent. Thanks @afaulconbridge 👍
