### ISSUE TITLE
Which ECO codes to use?

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#508]
Some of the public evidence data is using ECO:0000357. When looking at ECO website it seems this is only an alias of ECO:0000295. Should ECO:0000295 be used instead when making new datasets? Will ECO:0000357 be deprecated at some point?

**Comment by pieterlukasse** [comment]
cc @afaulconbridge : can you help us with this one?

**Comment by AsierGonzalez** [comment]
Hi Pieter, do you mean expression data? See #394, ECO:0000356 and ECO:0000357 are deprecated and we asked the expression atlas team to update them. They have implement the changes and the new ECO codes will be there in the next release.

**Comment by afaulconbridge** [comment]
@pieterlukasse @fedde-s is @AsierGonzalez reply sufficient to close this ticket?

**Comment by pieterlukasse** [comment]
yes, thanks
