### ISSUE TITLE
Target profile page rewrite: Create conditional block for TEPs data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#509]
### Use Cases

1. As a user of the Platform, I would like to see if a Target Enabling Package (TEP) has been created for my target of interest by the Structural Genomics Consortium.

2. As a user of the Platform, if a TEP is available, I would like to see a clear link to the relevant page on the Structural Genomics Consortium website so that I can conduct further research on the TEP.

### Detail Views

_View when page loads and user has **not** hovered on the tooltip_

![teps_1_tooltip_not_visible](https://user-images.githubusercontent.com/7490258/54992052-35658a80-4fb6-11e9-87d7-715b352b1567.png)

**[Full size version](https://drive.google.com/open?id=1ERVdwAKWkLPyi5rRiZDleB4Av9dJMAB-)**

_View when user has hovered on the tooltip_

![teps_2_tooltip_visible](https://user-images.githubusercontent.com/7490258/54992060-3d252f00-4fb6-11e9-8da6-4a0451968d1e.png)

**[Full size version](https://drive.google.com/open?id=1s30GcS3FaoENw03YGtJwtOzXe-rBMjVO)**

### Design and Interaction Notes

1. Because TEPs are only available for 19 targets - which represent less than 0.01% of the 28,000+ targets currently available within the Platform - it is not suitable for the summary widget and detail view design pattern. Instead, please create a section on the target profile page (between the Synonyms section and the Associations View/Target Profile Overview tab) that is visible if a TEP exists. If a TEP does not exist, please do not show the section.

2. For the tooltip icon, please use [the question-circle icon from FontAwesome](https://fontawesome.com/icons/question-circle?style=solid).
 
3. When a user hovers over the tooltip, please display the following message:

``TEPs provide a critical mass of reagents and knowledge on a protein target to allow rapid biochemical and chemical exploration and characterisation of proteins with genetic linkage to key disease areas.``

4. For the link to the individual TEP page, please display the HGNC symbol and TEP in bold as per the spec in the Detail Views section above (e.g. **PARP4 TEP**). For the link itself, please use the following link structure:

``https://www.thesgc.org/tep/HGNC-SYMBOL``

So for example, the TEP link for PARP14 would be `` https://www.thesgc.org/tep/PARP14`` and for LIMK1 it would be ``https://www.thesgc.org/tep/LIMK1``.

5. For the link to the Structural Genomics Consortium website in the text, please link to ``https://www.thesgc.org/``.

6. Please style both links in Open Targets Corporate Blue - ``#3489ca``

### Design Assets

1. [SGC logo](https://drive.google.com/open?id=1Lz5l9CKVD0sOSGHslV5ayTSxcrCzazmd)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by d0choa** [comment]
The TEPs have been conditionally included as a link instead of a box. They contain the respective tooltip informing about what they are and linking to the Structural Genomics Consortium. I considered this done, unless you @andrewhercules have a good reason to bring back the box
