### ISSUE TITLE
Additional gene-drug interaction data from DGIdb

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#51]
@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/data_release/issues/64)

Talk to chembl about coverage of the gene-drug interaction data - 
e.g. BRAF has 100 entries in dgidb (http://dgidb.org/api/v2/interactions.json?genes=BRAF)
vs 13 entris given to us from chebml (http://www.targetvalidation.org/target/ENSG00000157764).

Are these all synonyms ? or is there additional data : Can we include the DGIdb data pnto the drug entity page via a drug search e.g. http://dgidb.org/api/v2/interactions.json?drugs=dabrafenib or into the target profile page as in the target search http://dgidb.org/api/v2/interactions.json?genes=BRAF How much new will we get vs Chembl data feed?

---

@ckongEbi commented on [Tue Jan 30 2018](https://github.com/opentargets/data_release/issues/64#issuecomment-361563173)

@iandunham  updated ChEMBL on the initial comparison, whether there are plans for them to integrate DGIdb into ChEMBL. 

comparing drug-gene interactions for BRAF between:

DGIdb vs OT : 
http://dgidb.org/api/v2/interactions.json?genes=ENSG00000157764
https://api.opentargets.io/v3/platform/private/target/ENSG00000157764

These is a list of drug interactions found in DGIdb but NOT in OT platform: 

EVEROLIMUS
CAPMATINIB
CHEMBL523411
PHENMETRAZINE
NERATINIB
DACTOLISIB
SB590885
LENVATINIB
CHEMBL373011
IRINOTECAN
OBATOCLAX
DOXORUBICIN
ARQ-092
Ro-4987655
AEW-541
TRASTUZUMAB
MLN-2480
LAPATINIB
CI-1040
PALBOCICLIB
PACLITAXEL
VORINOSTAT
TUBASTATIN A
MK-2206
PICTILISIB
PF-00477736
LY-294002
DABRAFENIB
BEVACIZUMAB
Ribociclib
TIVOZANIB
Voruciclib
PLX-4720
GSK-2636771
SORAFENIB
DASATINIB
ERLOTINIB
PA-799
PF-04217903
CHEMBL217354
BI-2536
ALPELISIB
PLX-3397
AZD-6482
ATEZOLIZUMAB
AFATINIB
VENETOCLAX
IMATINIB
CHEMBL458997
IDELALISIB
COBIMETINIB
PIMASERTIB
LEUCOVORIN
GANETESPIB
CHEMBL526479
NIVOLUMAB
OMIPALISIB
UPROSERTIB
CHEMBL525191
CEDIRANIB
GEDATOLISIB
TEMSIROLIMUS
CETUXIMAB
TRAMETINIB
Refametinib
PANITUMUMAB
PANOBINOSTAT
FLUOROURACIL
SELUMETINIB
E-6201
CRIZOTINIB
SAR-260301
CHEMBL1231206
OXALIPLATIN
INK-128
BINIMETINIB
PEMBROLIZUMAB
TAK-733
NAVITOCLAX
PD-0325901
GEFITINIB
PILARALISIB (CHEMBL3218575)
BUPARLISIB
SARACATINIB
ZSTK-474
CHEMBL2204502

---

@ckongEbi commented on [Tue Jan 30 2018](https://github.com/opentargets/data_release/issues/64#issuecomment-361626871)

further explanations from ChEMBL.

For example Anna was looking into the evidence linking BRAF with everolimus. One of the sources is CKB, and here:
https://ckb.jax.org/gene/show?geneId=673 (see “Gene level evidence”)

they show a list of genetic variants of these gene and the response to different treatments, one of the treatments is everolimus. They say which gene variantes are resistant or sensitive to the treatment but it’s not drug-target information.

Cheers,

Paula

On 30/01/2018 14:42, Maria Paula Magarinos wrote:
> I don’t think we have any of these except for FDA and some from PubChem. We checked quickly and apparently many of these sources are not drug-target information
>
>> On 30 Jan 2018, at 13:16, Chuang Kee Ong <> wrote:
>>
>>
>>
>> On 30/01/2018 11:58, Maria Paula Magarinos wrote:
>>> Hi ChuangKee,
>>>
>>> This database seems to have very heterogeneous data sources and they don’t all fit into the type of data we integrate in ChEMBL. Is there a particular data source that you are interested? If so we could look into it.
>> sure, do you know which of Interactions data has already in ChEMBL and I find out, which one we are interested in. 
>>
>> http://dgidb.org/sources#
>>
>> Thanks Paula!
>>>
>>> Cheers,
>>>
>>> Paula
>>>

**Comment by MichaelaEBI** [comment]
Given the response above from ChEMBL that DGIdb contains gene-drug interactions rather than target-drug relationships and the fact that DGIdb now seems to import ChEMBL activity data I will close this ticket.
