### ISSUE TITLE
Target profile page rewrite: Create Variants and Genomic Context summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#513]
### Use Cases

1. As a user of the Platform, I want to see if my target of interest has variants that are associated with common diseases and/or mutations that are associated with rare diseases. 

### Summary Widget Views

![variants_and_genomic_context_summary_widget](https://user-images.githubusercontent.com/7490258/55015089-1b42a100-4fe4-11e9-98a3-9fd65863cb11.png)

**[Full-size version](https://drive.google.com/open?id=1xDBJN4uQYXpuByt75lDuiudZsOuE8cJR)**

### Design and Interaction Notes

1. If data on variants in common diseases and/or mutations in rare diseases is available (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831)), please use the following text in Open Targets Grey - ``#5a5f5f``:

``X variants in Y common diseases`` or  ``X mutations in Y rare diseases``

X = number of variants or mutations from API response
Y = number of common diseases or rare diseases from API response

Also, please colour the icon in Open Targets Grey - ``#5a5f5f``.

2. If data on variants in common diseases and/or mutations in rare diseases is not available (e.g. [HEXA](https://www.targetvalidation.org/target/ENSG00000213614) or [TFEB](https://www.targetvalidation.org/target/ENSG00000112561)) , please use the following text in Open Targets Light Grey - ``#e2dfdf``:

``0 variants in 0 common diseases`` or  ``0 mutations in 0 rare diseases``

Also, please colour the icon in Open Targets Light Grey - ``#e2dfdf``.

3. If no data is available for both variants in common diseases and mutations in rare diseases (e.g. [HOTAIR](https://www.targetvalidation.org/target/ENSG00000228630)), please use the following text in Open Targets Light Grey - ``#e2dfdf``:

``0 variants in 0 common diseases`` or  ``0 mutations in 0 rare diseases``

Also, please colour the icon in Open Targets Light Grey - ``#e2dfdf``. And please colour the widget container box outline in Open Targets Light Grey - ``#e2dfdf``.

4. When a user hovers over the summary widget and the target has data on variants in common diseases and/or mutations in rare diseases, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Variant and genomic context icon](https://drive.google.com/open?id=1Wa7LE6QcBunv_b5wcMP7BNxt0BIOdp-y)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by andrewhercules** [comment]
SVG icon has been updated to resolve Illustrator export issue

**Comment by d0choa** [comment]
I understand this is done. Please re-open if necessary
