### ISSUE TITLE
Produce a subset of evidences filtered by a curated list of genes

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#515]
The tool [platform-input-support](https://github.com/opentargets/platform-input-support) has to

1. produce a subset of evidences filtered by a curated list of genes
2. append a suffix for a clear indication that that input is needed for testing purposes
3. include this [list of genes](https://github.com/opentargets/data_pipeline/blob/master/mrtarget/resources/minimal_ensembl.txt) from this file and remove from the origin

**Comment by mkarmona** [comment]
@cmalangone this is the compiled list of genes
[top_gene_list.txt](https://github.com/opentargets/platform/files/3059932/top_gene_list.txt)

any update about this please let's centralise through @deniseOme as she should be the one adding or removing any gene.

**Comment by cmalangone** [comment]
Created a branch cm_515_subset_evidences

**Comment by cmalangone** [comment]
Create a second branch cm_515_new_approach with a faster algorithm

**Comment by ElaineMcA** [comment]
Request for team feedback issued 10May.  Check on Monday 13May meeting- for next steps.

**Comment by cmalangone** [comment]
The task is completed
