### ISSUE TITLE
Changes to ChEMBL evidence strings - small front end changes required

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#518]
For 19.04 the JSON schema for ChEMBL evidence strings has been changed slightly as outlined in [this document](https://docs.google.com/document/d/1409mFEsQJ0ej7dmV0U_r-lFsZcLVMABfuQS5GQdmQpo/edit).

The one thing that I can think of now that will affect the front end is the change of max_phase_per_disease to clinical_trial_phase.

**Comment by afaulconbridge** [comment]
This data should be available viaplatform-api-qc.opentargets.io thanks to @cmalangone
