### ISSUE TITLE
Data source research - Post-translational modifications

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#52]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/66)

PTMs are already included in the Uniprot protein browser. There might be proteomics experiments identify differentially PTM'ed proteins --> would this be evidence of target-disease associations? 

- [ ] Literature search to confirm that this makes sense
- [ ] Look at PRIDE and whether it contains relevant experiments
- [ ] Identify other PTM repositories

**Comment by MichaelaEBI** [comment]
Part of the Expression Atlas Project (OTAR 043). Will close this ticket because more specific tickets will be generated.
