### ISSUE TITLE
Target profile page rewrite: Create Variants and Genomic Context detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#521]
### Use Cases

1. As a user of the Platform, I want to see the variants of a given target associated with common diseases, mutations of a given target associated with rare diseases, and transcripts of a given gene, all within an interactive genome browser so that I can understand the genomic context of my target of interest.

2. As a user of the Platform, if I have clicked on a particular variant or mutation, I want to see information about the variant or mutation and its associated diseases.

3. As a user of the Platform, if I have clicked on a particular variant or mutation, I want to see a clear link to the Open Targets Genetics Portal so that I can further explore the genes and traits associated with the variant or mutation that have been identified by the pipelines run in the Portal.

### Detail Views

_View when user first loads browser_ 
![variants_and_genomic_context_detail_view_1_on_load](https://user-images.githubusercontent.com/7490258/55159148-582fa480-5158-11e9-801a-3d5aea706bf9.png)
[**Full-size version**](https://drive.google.com/open?id=1KVw6CnJcbhotvR2YRNiGketjQOFUWqyz)

_View when user clicks on a point in the ``Variants in common diseases`` track_
![variants_and_genomic_context_detail_view_2_common_disease_popup](https://user-images.githubusercontent.com/7490258/55159958-24557e80-515a-11e9-9f36-0fdc4f639ae7.png)
**[Full-size version](https://drive.google.com/open?id=1ZmZgE4vl5oLAQ9SvaKzP4mcZZYEQ_I03)**

_View when user clicks on a point in the ``Mutations in rare diseases`` track_
![variants_and_genomic_context_detail_view_2_common_disease_popup](https://user-images.githubusercontent.com/7490258/55160126-82826180-515a-11e9-87d0-a2eb2dc08eaa.png)
**[Full-size version](https://drive.google.com/open?id=1ZmZgE4vl5oLAQ9SvaKzP4mcZZYEQ_I03)**

### Design and Interaction Notes

1. For the detail view description, please use the following text:

``Genomic variants associated with HGNC-SYMBOL. Only variant information associating HGNC-SYMBOL with any disease is displayed. Click on any variant, gene or transcript to get more information about it. Pan or zoom the browser to see neighbouring genes. The number above gene variants means that more than 1 overlap the same region at the current zoom level. Genomic coordinates are relative to GRCh38.``

* Note: please replace HGNC-SYMBOL with the respective gene symbol

2. For the ``Ensembl ID:`` link, please link to the Ensembl profile page for the target using the following link structure:  

``http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=GENE-ID``

Please update GENE-ID with the Ensembl ID of the target (e.g. http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000091831 as the link for ESR1).

3. For the ``Location:`` link, please link to the Ensembl region view page using the following link structure:

``http://www.ensembl.org/Homo_sapiens/Location/View?db=core;g=GENE-ID``

Please update GENE-ID with the Ensembl ID of the target (e.g. http://www.ensembl.org/Homo_sapiens/Location/View?db=core;g=ENSG00000091831 as the link for ESR1).

4. Please integrate the existing browser view library used in the current Platform.

5. For the pop-up that is displayed when a user clicks a variant or mutation, please add a line ``Additional information`` and a link to the variant page on the Open Targets Genetics Portal. In order to build the link, this may require calling the Ensembl API with the RSID in order to generate the variant notation used to link to variant pages in the Portal.

6. For the pop-up that is displayed when a user clicks a variant, please update the design to use the `X publication(s)`` design pattern where X is the number of publications. Currently, the pop-up displays [the FontAwesome newspaper icon](https://fontawesome.com/icons/newspaper?style=regular) but it is not clear to users that clicking on it will direct users to the publication. 
 
### Design Assets

1. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)
2. [Full-size versions of mockups](https://drive.google.com/drive/folders/1GEltZ8Dc8oKW9V7T8NZf-Q1t5WI7c8Gr)

**Comment by LucaFumis** [comment]
I believe @peatroot implemented this.
