### ISSUE TITLE
Target profile page rewrite: Create Protein Interactions summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#525]
### Use Cases

1. As a user of the Platform, I want to see how many protein-protein interactions, pathway interactions, and/or enzyme-substrate interactions that have been identified for my protein of interest.

### Summary Widget Views

![protein_interactions_summary_widget](https://user-images.githubusercontent.com/7490258/55171001-810f6400-516f-11e9-9091-3c8cdd5e530b.png)

**[Full-size version](https://drive.google.com/open?id=1LjGjUsqui_wrV071HOOFwGXT0pjxjLrA)**

### Design and Interaction Notes

1. For targets where there is data on all three types of interactions (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831)), please use the following text in Open Targets Grey - ``#5a5f5f``:

``X protein-protein interactions``
``X pathway interactions``
``X enzyme-substrate interactions``

Please replace X with the relevant number from the GraphQL response.

Also, please colour the icon in Open Targets Grey - ``#5a5f5f``.

2. For targets where there is data on some, but not all, types of interactions (e.g. [PI3](https://www.targetvalidation.org/target/ENSG00000124102) or [SPTLC2](https://www.targetvalidation.org/target/ENSG00000100596)), please display the interactions with data in Open Targets Grey - ``#5a5f5f`` as per point 1 above. For the type(s) of interactions without data, please display the following text in Open Targets Light Grey - ``#e2dfdf``:

``0 TYPE-OF-INTERACTION interactions`` (e.g. ``0 protein-protein interactions``)

Also, please colour the icon in Open Targets Grey - ``#5a5f5f``.

3. For targets with no data (e.g. [HOTAIR](https://www.targetvalidation.org/target/ENSG00000228630) or [NUDT1](https://www.targetvalidation.org/target/ENSG00000106268)), please use the following text in Open Targets Light Grey - ``#e2dfdf``:

``0 protein-protein interactions``
``0 pathway interactions``
``0 enzyme-substrate interactions``

Also, please colour the icon and the widget container box outline in Open Targets Light Grey - ``#e2dfdf``. 

4. When a user hovers over the summary widget and the target has either a small molecule and/or an antibody tractability assessment, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Protein interactions icon](https://drive.google.com/open?id=1hNQflewkRQggM1JPY9b6MBvYEKUUvLdd)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by andrewhercules** [comment]
For some genes (e.g. [PI3](https://platform-app.netlify.com/target/ENSG00000124102)), the widget is incorrectly greyed out, despite having data - see below:

![Screenshot 2019-05-16 at 09 42 59](https://user-images.githubusercontent.com/7490258/57839757-2d101b80-77bf-11e9-8695-e84130f3b4a3.png)

Can we please fix? Once fixed, it's good to go! 👍

**Comment by d0choa** [comment]
Thanks Andrew! Do we know why is this happening?

The inside of the widget has some strange behaviors that we will have to fix when the new network comes into place.

**Comment by andrewhercules** [comment]
I'm not sure @d0choa, but I think we may need to tweak the logic for the widget. In the current Platform [PI3 target profile page](https://www.targetvalidation.org/target/ENSG00000124102), it lists one enzyme-substrate interaction. I've looked at other targets where there is 1 or 2 types of interactions (e.g. [SPTLC2](https://platform-app.netlify.com/target/ENSG00000100596)) and the logic looks good, so may just be a small fix.

**Comment by andrewhercules** [comment]
@mirandaio, can we please also update the label to ``pathway interactions`` - an ``o`` is missing in ``interactions``?

**Comment by mirandaio** [comment]
@andrewhercules should be fixed now.

**Comment by andrewhercules** [comment]
Thanks @mirandaio - looks good - will close this ticket
