### ISSUE TITLE
Target profile page rewrite: Create Mouse Phenotypes summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#527]
### Use Cases

1. As a user of the Platform, I want to see how many phenotypes have been observed in different mouse models.

### Summary Widget Views

![mouse_phenotypes_summary_widget](https://user-images.githubusercontent.com/7490258/55224823-380bee00-5209-11e9-8ac8-80adf72dc122.png)

**[Full-size version](https://drive.google.com/open?id=1HxRdU80PGTpFtPSze8kI5-dHzhvY7wkM)**

### Design and Interaction Notes

1. For targets where there is mouse phenotype data (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831)), please use the following text in Open Targets Grey - ``#5a5f5f``:

``X phenotypes in Y different phenotype categories observed in 
mouse models``

Please replace X with the relevant number of individual phenotypes, which are available from the existing API response - ``mouse_phenotypes.phenotypes.genotype_phenotype.mp_label``. Please replace Y with the relevant number of phenotype categories, which are also available from the existing API response - ``mouse_phenotypes.phenotypes.category_mp_label``.

Also, please colour the icon and the widget container box outline in Open Targets Grey - ``#5a5f5f``.

2. For targets where there is no mouse phenotype data (e.g. [HOTAIR](https://www.targetvalidation.org/target/ENSG00000228630) or [ATF7IP](https://www.targetvalidation.org/target/ENSG00000171681)), please use the following text in Open Targets Light Grey - ``#e2dfdf``:

``0 phenotypes in 0 different phenotype categories observed in 
mouse models``

Also, please colour the icon and the widget container box outline in Open Targets Light Grey - ``#e2dfdf``. 

3. When a user hovers over the summary widget and the target has either a small molecule and/or an antibody tractability assessment, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Mouse phenotypes icon](https://drive.google.com/open?id=1BfGafxt9I7xler66rViaR0HLapEyNX8a)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
@andrewhercules, there is a different mouse icon on the gene page of the genetics portal. Can we use one consistently?

**Comment by andrewhercules** [comment]
@peatroot, I have updated the icon used in the Genetics Portal to this icon (see ticket [#303](https://github.com/opentargets/genetics/issues/303) for a full spec) as it is more consistent with the weights of the all of the other icons used across the Platform and Portal.

**Comment by peatroot** [comment]
Ok. Suggest we do the same with pathways icon, which is also inconsistent.

**Comment by andrewhercules** [comment]
Agreed. I have created a separate ticket to make the change in the next phase of the project - see #530 for more information.

**Comment by andrewhercules** [comment]
SVG icon has been updated to resolve Illustrator export issue

**Comment by andrewhercules** [comment]
Looks good @mirandaio - thank you! :) 👍 

UX QC review complete
