### ISSUE TITLE
ChEMBL evidence strings: up_or_down activity for drugs

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#533]
Following a support email "I totally understand what "antagonist" and "agonist" mean in the "activity" column. However, I am not able to uncover the meaning of "up_or_down". Could you help me on that? Where could I find this information?"

According to @gkos-bio "_It means mainly that this was a temporary solution until we could better qualify the MOA of the small molecule or biologic.
Maybe, it’s time to revisit the classification of MOAs in Open Targets. This will require more work from and coordination with ChEMBL_."

From Paula (ChEMBL):
_up_or_down seems to be one of the activity types in the JSON schema:

"activity": {
          "type": "string",
          "enum": [
            "http://identifiers.org/cttv.activity/decreased_transcript_level",
            "http://identifiers.org/cttv.activity/decreased_translational_product_level",
            "http://identifiers.org/cttv.activity/drug_negative_modulator",
            "http://identifiers.org/cttv.activity/drug_positive_modulator",
            "http://identifiers.org/cttv.activity/gain_of_function",
            "http://identifiers.org/cttv.activity/increased_transcript_level",
            "http://identifiers.org/cttv.activity/increased_translational_product_level",
            "http://identifiers.org/cttv.activity/loss_of_function",
            "http://identifiers.org/cttv.activity/partial_loss_of_function",
            "http://identifiers.org/cttv.activity/up_or_down",
            "http://identifiers.org/cttv.activity/up",
            "http://identifiers.org/cttv.activity/down",
            "http://identifiers.org/cttv.activity/tolerated",
            "http://identifiers.org/cttv.activity/predicted",
            "http://identifiers.org/cttv.activity/damaging",
            "http://identifiers.org/cttv.activity/damaging_to_target",
            "http://identifiers.org/cttv.activity/predicted_tolerated",
            "http://identifiers.org/cttv.activity/predicted_damaging",
            "http://identifiers.org/cttv.activity/tolerated_by_target",
            "http://identifiers.org/cttv.activity/unknown"
          ],
          "description": "Activity of target in disease context"
In our data we assign 3 types of activities:

drug_negative_modulator for drugs which are negative modulators, 
drug_positive_modulator for drugs which are positive modulators, 
up_or_down for any other

So I think this must have been how it was required (from many years ago I think)._

This is how ChEMBL classifies the different activity types (what they seem to provide to us is 
the parent term i.e. negative modulator, positive modulator. But do we have "other". Or do we use "up_or_down" instead of "other"):

NEGATIVE MODULATOR (parent type) | BLOCKER (action type) | Negatively effects the normal functioning of an ion channel e.g., prevents or reduces transport of ions through the channel (description)
-- | -- | --
NEGATIVE MODULATOR | RELEASING AGENT | Reverses the normal functioning of a transporter, causing release of the substrate, rather than uptake
NEGATIVE MODULATOR | ANTAGONIST | Binds to a receptor and prevents activation by an agonist through competing for the binding site
NEGATIVE MODULATOR | INVERSE AGONIST | Binds to and inactivates a receptor
NEGATIVE MODULATOR | ANTISENSE INHIBITOR | Prevents translation of a complementary mRNA sequence through binding to it
NEGATIVE MODULATOR | ALLOSTERIC ANTAGONIST | Binds to a receptor at an allosteric site and prevents activation by a positive allosteric modulator at that site
NEGATIVE MODULATOR | NEGATIVE ALLOSTERIC MODULATOR | Reduces or prevents the action of the endogenous ligand of a receptor through binding to a site distinct from that ligand (non-competitive inhibition)
NEGATIVE MODULATOR | INHIBITOR | Negatively effects (inhibits) the normal functioning of the protein e.g., prevention of enzymatic reaction or activation of downstream pathway
NEGATIVE MODULATOR | DEGRADER | Binds to or antagonizes a receptor, leading to its degradation
NEGATIVE MODULATOR | NEGATIVE MODULATOR | Negatively effects the normal functioning of a protein e.g., receptor antagonist, inverse agonist or negative allosteric modulator
OTHER | SUBSTRATE | Carried by a transporter, possibly competing with the natural substrate for transport
OTHER | MODULATOR | Effects the normal functioning of a protein in some way e.g., mixed agonist/antagonist or unclear whether action is positive or negative
OTHER | CHELATING AGENT | Binds to a metal, reducing its availability for further interactions
OTHER | HYDROLYTIC ENZYME | Hydrolyses a substrate through enzymatic reaction
OTHER | DISRUPTING AGENT | Destabilises or disrupts a protein complex, macromolecular assembly, cell membrane etc
OTHER | SEQUESTERING AGENT | Binds to a substance such as a drug, toxin or metabolite reducing its availability for further interactions
OTHER | METHYLATING AGENT | Methylates or participates in methylation (e.g., through donation of a methyl group) of a substrate molecule
OTHER | STABILISER | Increases the conformational stability of a protein or complex
OTHER | REDUCING AGENT | Modifies a substrate via a reduction reaction
OTHER | OTHER | Other action type, not clearly postively or negatively affecting the normal functioning of a protein e.g., chelation of substances, hydrolysis of substrate
OTHER | PROTEOLYTIC ENZYME | Hydrolyses a protein substrate through enzymatic reaction
OTHER | BINDING AGENT | Binds to a substance such as a cell surface antigen, targetting a drug to that location, but not necessarily affecting the functioning of the substance itself
OTHER | OXIDATIVE ENZYME | Oxidises a substrate through enzymatic reaction
OTHER | CROSS-LINKING AGENT | Induces cross-linking of proteins or nucleic acids
POSITIVE MODULATOR | OPENER | Positively effects the normal functioning of an ion channel e.g., facilitates transport of ions through the channel
POSITIVE MODULATOR | POSITIVE MODULATOR | Positively effects the normal functioning of a protein e.g., receptor agonist, positive allosteric modulator, ion channel activator
POSITIVE MODULATOR | ACTIVATOR | Positively effects the normal functioning of the protein e.g., activation of an enzyme or cleaving a clotting protein precursor
POSITIVE MODULATOR | AGONIST | Binds to and activates a receptor, often mimicking the effect of the endogenous ligand
POSITIVE MODULATOR | POSITIVE ALLOSTERIC MODULATOR | Enhances the action of the endogenous ligand of a receptor through binding to a site distinct from that ligand
POSITIVE MODULATOR | PARTIAL AGONIST | Binds to and only partially activates a receptor (relative to the response to a full agonist)

Things we may need to do:

1) revisit our classification of activity 
* Do we want to change it to be in line with ChEMBL's (table above)?
* If we continue with "agonist", "antagonist" and "up_or_down", we need a sentence in the external docs (FAQ or other) to explain what it is.

Considerations:
Where is this activity data in the ChEMBL website? Is it under "activity charts"?
If so, there does not seem to be a correspondence between what we have ("up_or_down" for example) and what they provide. Ex:

 * **CHEMBL2108576**
--> Platform: **up_or_down** in the drug table (https://www.targetvalidation.org/evidence/ENSG00000142192/EFO_0000249?view=sec:known_drug)

--> ChEMBL website: no data available: https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2108576/

* **CHEMBL1201550**
--> Platform: **up_or_down** in the drug table (https://www.targetvalidation.org/evidence/ENSG00000134460/EFO_1000785?view=sec:known_drug)

--> ChEMBL website: other, plus hepatotoxicity
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201550/
(if we click on "other" in the bioactivity summary chart we get redirected to: https://www.ebi.ac.uk/chembl/g/#browse/activities/filter/molecule_chembl_id%3A(%22CHEMBL1201550%22)%20AND%20standard_type%3A(%22Hepatotoxicity%20(cytolytic)%22%20OR%20%22Hepatotoxicity%20(granulomatous%20hepatitis)%22%20OR%20%22Hepatotoxicity%20(malignant%20tumour)%22%20OR%20%22Hepatotoxicity%20(mechanism)%22%20OR%20%22Hepatotoxicity%20(severe%20hepatitis)%22%20OR%20%22Hepatotoxicity%20(steatosis)%22%20OR%20%22Hepatotoxicity%20(successful%20reintroduction)%22%20OR%20%22Hepatotoxicity%20(time%20to%20onset)%22)

* **CHEMBL1655**
--> Platform: **up_or_down** in the drug table 
https://www.targetvalidation.org/evidence/ENSG00000091831/EFO_0000616?view=sec:known_drug (**modulator** in the drug summary page: https://www.targetvalidation.org/summary?drug=CHEMBL1655)

ChEMBL website: Inhibition...
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1655/

* **CHEMBL1201649**
--> Platform: **agonist** in the drug table (https://www.targetvalidation.org/evidence/ENSG00000091831/EFO_0000616?view=sec:known_drug)

--> ChEMBL website: no data available: 
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201649/

@AsierGonzalez says "I guess it would be interesting to know how many drugs there are for each activity category. Perhaps there are only a handful of “up_or_down” cases.

**Comment by AsierGonzalez** [comment]
I have checked the numbers of each of the different categories in the evidence data from the 19.02 release and this is what I found:

**Counts based on the _target.activity_ field in the JSON**

Target activity | Counts
-- | --
drug_negative_modulator | 391178
drug_positive_modulator | 63493
up_or_down | 22293

**Counts based on the _action_type_ field in the JSON**

Target activity | Action type | Counts
-- | -- | --
NEGATIVE MODULATOR | RELEASING AGENT | 340
NEGATIVE MODULATOR | ANTAGONIST | 27840
NEGATIVE MODULATOR | INVERSE AGONIST | 347
NEGATIVE MODULATOR | ANTISENSE INHIBITOR | 0
NEGATIVE MODULATOR | ALLOSTERIC ANTAGONIST | 192
NEGATIVE MODULATOR | NEGATIVE ALLOSTERIC MODULATOR | 3310
NEGATIVE MODULATOR | INHIBITOR | 332247
NEGATIVE MODULATOR | DEGRADER | 1
NEGATIVE MODULATOR | NEGATIVE MODULATOR | 10
NEGATIVE MODULATOR | BLOCKER | 10
OTHER | SUBSTRATE | 20
OTHER | MODULATOR | 18635
OTHER | CHELATING AGENT | 0
OTHER | HYDROLYTIC ENZYME | 1521
OTHER | DISRUPTING AGENT | 135
OTHER | SEQUESTERING AGENT | 0
OTHER | METHYLATING AGENT | 0
OTHER | STABILISER | 750
OTHER | REDUCING AGENT | 0
OTHER | OTHER | 340
OTHER | PROTEOLYTIC ENZYME | 16
OTHER | BINDING AGENT | 538
OTHER | OXIDATIVE ENZYME | 0
OTHER | CROSS-LINKING AGENT | 336
POSITIVE MODULATOR | OPENER | 1701
POSITIVE MODULATOR | POSITIVE MODULATOR | 4816
POSITIVE MODULATOR | ACTIVATOR | 2108
POSITIVE MODULATOR | AGONIST | 35341
POSITIVE MODULATOR | POSITIVE ALLOSTERIC MODULATOR | 18135
POSITIVE MODULATOR | PARTIAL AGONIST | 1392

For me the biggest question is why we seem to use "antagonist", "agonist" and "up_or_down" as activities in the platform, which is a mixture of the activity and action data we get from ChEMBL.

**Comment by MichaelaEBI** [comment]
I will investigate this with Paula from ChEMBL as part of an effort to understand all fields in the ChEMBL evidence strings.

**Comment by MichaelaEBI** [comment]
Update: It looks like ChEMBL does the mapping of different activity types to drug_positive_modulator, drug_negative_modulator and up_or_down because they provide these terms in the `target.activity` field and they also provide their activity types in the `target2drug.action_type` field. 

The `target.activity` field entries are changed to agonist, antagonist and up_or_down in the front end.

It makes sense for us to use the terms in the action_type field to be more specific. This information has been added to [this document](https://docs.google.com/document/d/1409mFEsQJ0ej7dmV0U_r-lFsZcLVMABfuQS5GQdmQpo/edit) which specifies upcoming changes to the JSON schema for ChEMBL evidence strings.

**Comment by MichaelaEBI** [comment]
For the 19.09 release, ChEMBL have changed the `activity` values to be `negative_modulator`, `positive_modulator` and `other`. The plan is to display both, these general categories and ChEMBL's more specific terms in the drug tables.

**Comment by MichaelaEBI** [comment]
This ticket can be closed since details for the front end have been summarised in ticket #730.
