### ISSUE TITLE
Roadmap: Harmonize evidence_datasource_parsers

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#535]
The modules in evidence_datasource_parsers have slightly different implementations (for example, some validate the generate evidence strings others don't). The aim is to define a template for a 'model' module that all modules should follow.

For all modules, the following will be done
1. Data QC
1. Document current implementation
1. Document data processing workflow
1. Improve implementation
    1. Configuration
    1. Management of disease mappings
    1. Logging
    1. Comments / docstring
    1. Reliability (e.g. network retries)
    1. JSON schema validation
    1. Check that all combinations of unique_association_fields are unique
    1. Reproducibility (e.g. saving API results as files)
    1. Dockerize

Progress and tickets for each module:
- [ ] Gene2Phenotype
- [ ] GenomicsEnglandPanelApp
- [ ] CRISPR
- [ ] IntOGen
- [ ] MouseModels (aka phenodigm)
- [ ] PROGENy
- [ ] SLAPEnrich

**Comment by afaulconbridge** [comment]
Note there is already a ticket opentargets/platform#195 "Refactor the PheWAS module" which I think is superseeded by this ticket.

**Comment by d0choa** [comment]
The guidelines for every module are copied into the evidence_datasource_parsers ticket
