### ISSUE TITLE
Load evidence data without running --as and subsequent steps

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#539]
For initial prototyping, development and testing of plugins to visualize custom evidence data it would be nice to be able to load evidence data on top of an existing data release snapshot and skip the `--as` and subsequent steps. 

Some preliminary pipeline tests we did seem to indicate that this already works fine. Can you please confirm if this is indeed the case and whether this will remain working in the near future?

**Comment by afaulconbridge** [comment]
It depends on how you define "working". Will the api or webapp crash? No. Will the extra evidence be reflected in associations, search, or relationships? No. Is this a supported or recommended approach? No.

So for prototypes, then yes you could do this. But for production, we would strongly recommend not to.
