### ISSUE TITLE
Data source research - Connectivity Maps

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#54]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/69)

@MichaelaEBI commented on [Tue Jan 23 2018](https://github.com/opentargets/data_pipeline/issues/236)

- [ ] Identify what people want. We could have 1. pre-canned analysis that matches disease profiles to drugs, 2. information of gene expression changes under drug treatment, 3. something else?
- [ ] Look at possible analyses to connect diseases with small molecules or targets.

More details [here](https://docs.google.com/spreadsheets/d/1kMVh2JybvJdh00xtkQWjfKCZIMiReLPdSUXShDb33HQ/edit?ts=5a672eae#gid=669895092)

**Comment by ElaineMcA** [comment]
Industry workshop in early April 2019 to firm up plans.  Looking into using this data for target safety predictions at present.

**Comment by MichaelaEBI** [comment]
The Open Targets Data Team attended the EBI Industry workshop in April and decided that at the current time, Connectivity Map data will not be integrated into the Open Targets platform (it focuses on the profiling of small molecules and disease models are not straight forward).
