### ISSUE TITLE
Target profile page rewrite: Create Bibliography summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#540]
### Use Cases

1. As a user of the Platform, I want to see how many publications are related to my target based on text mining abstracts from PubMed.

### Summary views

![bibliography_summary_widget](https://user-images.githubusercontent.com/7490258/55490609-f1186100-562b-11e9-9c4a-0d1aa7ace311.png)
**[Full-size view](https://drive.google.com/open?id=1EA67AfrFu-MFmecbuSR-lzStl33TPmcW)**

### Design and Interaction Notes

1. For targets where there is bibliography data (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831), [SERPINB2](https://www.targetvalidation.org/target/ENSG00000091831), or [AQP7](https://www.targetvalidation.org/target/ENSG00000165269)), please use the following text in Open Targets Grey - #5a5f5f:

``X scientific publications on GENE-SYMBOL available``

Please replace X with the number of publications returned by the LINK API. And please replace GENE-SYMBOL with the HGNC symbol for the target.

Also, please colour the icon and widget container box outline in Open Targets Grey - ``#5a5f5f``.

2. For targets where there is no bibliography data (e.g. [AL138921.2](https://www.targetvalidation.org/target/ENSG00000236308)), please use the following text in Open Targets Light Grey - ``#e2dfdf``:

``0 scientific publications on GENE-SYMBOL available``

Please replace GENE-SYMBOL with the HGNC symbol for the target.

Also, please colour the icon and widget container box outline in Open Targets Light Grey - ``#e2dfdf``

3. When a user hovers over the summary widget and the target has either a small molecule and/or an antibody tractability assessment, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Bibliography icon](https://drive.google.com/open?id=1ID-2XuV6-9CJliUjygQpQZ7nLV90apiT)
2. [Full-size mockup](https://drive.google.com/open?id=1EA67AfrFu-MFmecbuSR-lzStl33TPmcW)
3. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment]
@andrewhercules, I suggest `X scientific publications on GENE-SYMBOL available` is preferable to `X scientific publications on GENE-SYMBOL available from text mining PubMed abstracts using Natural Language Processing (NLP)` in the summary and that the reference to NLP goes in the message at the top of the detail section.

**Comment by andrewhercules** [comment]
@peatroot, good point. It makes the description simpler and although a few users wanted to know about the text mining source and method on the widget, we can refer them to detail view or documentation for a more thorough explanation. I've updated the design spec above and mockups.

**Comment by andrewhercules** [comment]
SVG icon has been updated to resolve Illustrator export issue

**Comment by d0choa** [comment]
Could you @andrewhercules have a look and see if you're happy with it?

**Comment by andrewhercules** [comment]
@d0choa, I have two suggestions to improve the usability and readability of the content.

1. I would remove the external links for author name and publication/journal name as it makes it difficult to communicate a visual hierarchy. The key link for users is the name of the paper, which takes users to EuropePMC, but having multiple other links makes it difficult to distinguish the key link for users to download the paper. In the current Platform implementation, the author names and publication/journal name are links, but they are styled like text. And because external links have the external-link icon, it also disrupts the readability of the citation.
 
![Screenshot 2019-06-07 at 09 49 01](https://user-images.githubusercontent.com/7490258/59092523-a657e580-8909-11e9-9b76-9a302b924f65.png)

2. To make it easier to distinguish between the list of all publications and the Similar Articles and Abstract content, I would recommend adding a light grey background - perhaps in  `#F6F5F5` or another suitable shade from the Material UI default library - and a `margin-top: 10px` and `padding: 20px`.

![Screenshot 2019-06-07 at 10 05 57](https://user-images.githubusercontent.com/7490258/59093586-34cd6680-890c-11e9-88cc-3081d9b4d127.png)

![Screenshot 2019-06-07 at 10 06 55](https://user-images.githubusercontent.com/7490258/59093588-3860ed80-890c-11e9-8402-5269410267a5.png)

**Comment by d0choa** [comment]
+1 for both changes.

I discussed both issues with @LucaFumis but we didn't come with any reasonable solution. The links to the authors and journal are not that useful for us and the grey background adds a nice visual difference for the `Similar articles`

After these 2 things we can close this ticket.
