### ISSUE TITLE
Target profile page rewrite: Create Bibliography detail views

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#542]
### Use Cases

1. As a user of the Platform, I want to see a list of publications from PubMed that have been text mined for my target of interest.

2. As a user of the Platform, I want to explore the underlying graph of the different terms and concepts that are connected and related to my target of interest so that I can access more relevant publications.

3. As a user of the Platform, I want a visual cue to know what terms and concepts I have selected as I browse the knowledge graph built from text mining PubMed abstracts.

4. As a user of the Platform, I want to see the abstract of a specific publication along with the terms and concepts that have been mined from the abstract.

5. As a user of the Platform, I want to see articles that are similar to one that I am interested in or already familiar with.

6. As a user of the Platform, I want to have a link to view the full-text of a given article.

### Detail Views

_View when user first loads detail view_
![bibliography_detail_view_1_on_load](https://user-images.githubusercontent.com/7490258/55402815-49783180-554c-11e9-8d38-7f157caee33d.png)
**[Full-size version](https://drive.google.com/open?id=1kViZeVlP753VaiLa0JjYCD0uI-E3Oa7s)**

_View when user has clicked one of the buttons to filter the list by a specific term_
![bibliography_detail_view_2_term_button_selected](https://user-images.githubusercontent.com/7490258/55402825-4d0bb880-554c-11e9-934d-0a9c27f3ba47.png)
**[Full-size version](https://drive.google.com/open?id=1VieCHpxUw6HMC_-mRv6JFv8LcBQ9JEh9)**

_View when user has clicked the ``+ Show abstract`` button_
![bibliography_detail_view_3_abstract_visible](https://user-images.githubusercontent.com/7490258/55402828-5137d600-554c-11e9-8abe-b9d2fa493d92.png)
**[Full-size version](https://drive.google.com/open?id=15RGsKMEHu8ZpT3ncUmrWserVUrEo2_al)**

_View when a user has clicked the ``+ Show similar articles`` button_
![bibliography_detail_view_4_similar_articles_visible](https://user-images.githubusercontent.com/7490258/55402843-56952080-554c-11e9-9eb9-ae97f77ce40a.png)
**[Full-size version](https://drive.google.com/open?id=1Ny5lkGkmBv2ySXe_JDI2J_qYK0cUPzqd)**

### Design and Interaction Notes

1. For the detail view description, please use the following text:

``Scientific literature on GENE-SYMBOL. The list of publications is generated by text mining PubMed abstracts with Natural Language Processing (NLP).``

2. Please copy the existing functionality offered in the Platform: showing 10 publications when the detail view first loads; including a dropdown to allow users to filter papers by various concepts/terms/entities; and providing buttons with individual terms that users can toggle as they explore the underlying knowledge graph built by LINK. 

Please colour the concept/term buttons in Open Targets Purple - ``#7b196a``. When a user has selected a term, please colour the button white and the font and close button in Open Targets Purple - ``#7b196a``.

Please also include a button at the bottom of the list of publications to allow the user to load more publications - please colour this button in Open Targets Purple - ``#7b196a`` with white font.

3. When a user clicks the ``+ Show abstract`` button, please change the text of the button to ``- Hide abstract``, please show the abstract of that paper, and please highlight the ``Gene``, ``Disease``, ``Drug``, and ``Target and disease`` terms and concepts similar to how it is currently done in the Platform.

For this implementation, please update the colours to keep in line with the Open Targets brand palette:

| Concept/Term/Entity | Outline colour | Background colour |
|---|---|---|
| Gene | ``#BC8CB5`` | ``#E3D1E2`` |
| Drug | ``#9CCCA6`` | ``#D8EDDC`` |
| Disease |  ``#E7B1A0`` | ``#F3E1D9`` |
| Target and disease | ``#82B0CA``| ``#D0DDEB`` |

*Note: these colours are not ideal from an accessibility standpoint; however, the colours and overall functionality of this detail view have been marked for review pending further clarification of long-term development and support for LINK. 

4. When a user clicks the ``+ Show similar articles`` button, please change the text of the button to ``- Hide similar articles`` and please show the list of similar publications. Within the list, please hyperlink the title of the publication to EuropePMC and please colour the link in Open Targets Blue - ``#3489ca``. Also, please bold the year of the publication.

### Design Assets

1. F[ull-size mockups](https://drive.google.com/drive/folders/1XXJnE2P-ETBpRY7pkxZgcJNRW6dJ4exz)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by LucaFumis** [comment]
This is done pending PR approval/merging
