### ISSUE TITLE
Look at excluding "function" efo terms

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#543]
Outside of child terms of disease, we also import the child terms of "function" https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ifomis.org%2Fbfo%2F1.1%2Fsnap%23Function

There are only 13 targets associated with child terms of function, and this is a very poorly populated and structured part of the ontology.

This ticket is to consider removing "function" and its child terms from OpenTargets. This would reduce the amount of noise and confusion when mapping ontlogy terms, simplify the code, and have negligible impact on users.

**Comment by ElaineMcA** [comment]
@d0choa - checking with you where this fits in workload/priorities to feed 19.11 readiness for EFO 3.

**Comment by d0choa** [comment]
Within the scope of the EFO3 work for 19.11. I agree with @afaulconbridge the `function` node or its child terms add very little value to the platform.

**Comment by andrewhercules** [comment]
Ticket moved to 20.02 release as work is still ongoing with EFO team

**Comment by d0choa** [comment]
SPOT team is looking at relocating these terms eventually. We can push back to them and close this ticket.

Since the inclusion of EFO3 (19.11), the pipeline respects the ontology as it is. An eventual modification of the ontology won't introduce any actions.
