### ISSUE TITLE
Target profile page rewrite: Create Cancer Hallmarks summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#544]
### Use Cases

1. As a user of the Platform, I want to see the role my target of interest plays in cancer.

2. As a user of the Platform, I want to see which hallmarks are promoted and which are suppressed for my target of interest.

### Summary Views

![cancer_hallmarks_summary_widget](https://user-images.githubusercontent.com/7490258/55412101-b5fc2c00-555e-11e9-8f4c-5d6b8d3f72a4.png)
**[Full-size version](https://drive.google.com/open?id=1-ePBOWZOkNteniFD_pABmYa7CoqzalIa)**

### Design and Interaction Notes

1. For targets where there is data about cancer hallmarks (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831) or [TP53](https://www.targetvalidation.org/target/ENSG00000141510)), please display their roles in cancer in Open Targets Grey - ``#5a5f5f`` as this data is already available from the existing Open Targets API.

Also, please colour the widget container box outline in Open Targets Grey - ``#5a5f5f``.

If a hallmark has been promoted, please colour the first box of the row in Open Targets Green - ``#38954c`` and display [the FontAwesome check icon](https://fontawesome.com/icons/check?style=solid) in white.

If a hallmark has been suppressed, please colour the second box of the row in Open Targets Red - ``#c94c52`` and display [the FontAwesome check icon](https://fontawesome.com/icons/check?style=solid) in white.

If a hallmark has been both promoted and suppressed (e.g. [the invasion and metastasis hallmark for ESR1](https://www.targetvalidation.org/target/ENSG00000091831?view=sec:hallmarks)), please colour the first box in the row as per point 2 and the second box in the row as per point 3.

2. Underneath the table with colours and icons showing the promoted and suppressed hallmarks, please create a legend section using the colours and icons noted in points 2 and 3 above.

3. For targets where there is no data about cancer hallmarks (e.g. [AQP7](https://www.targetvalidation.org/target/ENSG00000165269) or [HOTAIR](https://www.targetvalidation.org/target/ENSG00000228630)), please grey out all table content, icons, and text with Open Targets Light Grey - ``#e2dfdf``. Also, please display ``Role in cancer: no data available``.

4. When a user hovers over the summary widget and the target has either a small molecule and/or an antibody tractability assessment, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Full-size mockup](https://drive.google.com/open?id=1-ePBOWZOkNteniFD_pABmYa7CoqzalIa)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by LucaFumis** [comment]
Done, pending PRs merging. Will update with demo link once that is done.
