### ISSUE TITLE
Target profile page rewrite: Create Cancer Hallmarks detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#545]
### Use Cases

1. As a user of the Platform, I want to see a list of all of the hallmarks of cancer that are related to a given target, whether these hallmarks are promoted or suppressed, and a description and publication so that I can conduct further research. 

### Detail Views

![cancer_hallmarks_detail_view](https://user-images.githubusercontent.com/7490258/55416255-5a35a100-5566-11e9-8897-bb732401342e.png)
**[Full-size version](https://drive.google.com/open?id=1RSLbsYGP5w6qyHFooc9fgsF36vinqUw1)**

### Design and Interaction Notes

1. For the detail view description, please use the following text:

``Essential alterations in cell physiology that dictate malignant growth. Cancer hallmarks were originally described by Hanahan and Weinberg (2000) and are manually curated by COSMIC and integrated into the Cancer Gene Census.``

Please hyperlink ``Hanahan and Weinberg (2000)`` to ``https://www.cell.com/abstract/S0092-8674(00)81683-9``.

2. Below the detail view description, please list the role in cancer values and hyperlink to EuropePMC with the list of PubMed IDs passed through as a parameter.

3. For the data table, please use the existing data table design pattern and include the filter/search bars in the ``Hallmark`` and ``Promotes or suppresses`` columns.

### Design Assets

1. [Full-size mockup](https://drive.google.com/open?id=1RSLbsYGP5w6qyHFooc9fgsF36vinqUw1)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by LucaFumis** [comment]
Done, pending PRs merging. Will update with demo link once that is done.
