### ISSUE TITLE
Target profile page rewrite: Create Protein and Baseline Expression summary widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#546]
### Use Cases

1. As a user of the Platform, I want to see if baseline RNA expression data for my target is available.

2. As a user of the Platform, I want to see if baseline protein expression data for my target is available.

3. As a user of the Platform, I want to see if data from experiments listed in Expression Atlas are available for my target.

4. As a user of the Platform, I want to see if experiments listed in Single Cell Expression Atlas are available for my target.

5. As a user of the Platform, I want to see if data from GTEx is available for my target.

### Summary Widgets

![expression_summary_widget](https://user-images.githubusercontent.com/7490258/55467217-bcd77d00-55f8-11e9-98ea-610dbecfe702.png)

### Design and Interaction Notes

1. For targets where there is data for some or all types of RNA and protein baseline expression data (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831), [SERPINB2](https://www.targetvalidation.org/target/ENSG00000091831), or [AQP7](https://www.targetvalidation.org/target/ENSG00000165269)), please use the following text in Open Targets Grey - #5a5f5f:

``Data available for GENE-SYMBOL``

Please replace GENE-SYMBOL with the HGNC gene symbol.

Also, please colour the widget container box outline in Open Targets Grey - ``#5a5f5f``.

2. Underneath the text, please create a table that copies the design pattern used in the Protein Information summary widget (see #254) and in the Gene Tree summary widget (see #536). 

If a specific type of RNA or protein baseline expression data is available, please colour the box containing [the FontAwesome checkmark icon ](https://fontawesome.com/icons/check?style=solid) in Open Targets Purple - ``#7b196a`` and please colour the checkmark icon white. 

If a specific type of RNA or protein baseline expression data is not available (e.g. [NANOGP8](https://www.targetvalidation.org/target/ENSG00000255192) or [DUXA](https://www.targetvalidation.org/target/ENSG00000258873) or [MIR4299](https://www.targetvalidation.org/target/ENSG00000266645) or [RNA5-8SN1](https://www.targetvalidation.org/target/ENSG00000278189)), please replace the checkmark with the [the FontAwesome times icon](https://fontawesome.com/icons/times?style=solid) in Open Targets Light Grey - ``#e2dfdf``. Also, please colour the text for that type of data in Open Targets Light Grey - ``#e2dfdf``.

3. For targets where this no data on protein or baseline expression data, please display all text (including [the FontAwesome times icon](https://fontawesome.com/icons/times?style=solid)) and the widget container box outline in Open Targets Light Grey - ``#e2dfdf``.

_Note: have been unable to find a target where there isn't some type of data available, but please build the widget to accommodate this potential situation_

4. When a user hovers over the summary widget and the target has either a small molecule and/or an antibody tractability assessment, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Full-size mockup](https://drive.google.com/open?id=1DnJQeANouQ6LIunbaXq1-cszdVPzHXqe)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by mirandaio** [comment]
After discussing with @andrewhercules, since the single cell expression atlas widget is not available, the corresponding item in the summary will be taken out.

**Comment by andrewhercules** [comment]
@mirandaio, can we please make a few changes?

1. Please add the word 'data' to all options?

RNA baseline expression data
Protein baseline expression data
Expression Atlas experiment data
GTEx data

However, if it causes a layout issue due to the width of the widget, we can drop the word data.

2. I noticed that for some targets (e.g. [NANOGP8](https://platform-app.netlify.com/target/ENSG00000255192) and [DUXA](https://platform-app.netlify.com/target/ENSG00000258873)), the widget displays a checkmark, indicating that we have RNA baseline expression data, but when you look at the detail views in the Platform - [NANOGP8](https://www.targetvalidation.org/target/ENSG00000258873) and [DUXA](https://www.targetvalidation.org/target/ENSG00000258873) respectively - we list ``N/A`` in all of the tissues and anatomical systems. It is likely that we have data, but it is below the threshold to be included in the detail view visualisation. Can we please update the logic of the widget to ensure that the summary provided in the widget matches that data is available and visible in the detail view? 

![Screenshot 2019-05-16 at 11 01 26](https://user-images.githubusercontent.com/7490258/57845460-fb508200-77c9-11e9-86a4-ab159131a259.png)

**Comment by andrewhercules** [comment]
Thanks @mirandaio - looks good - will close this ticket
