### ISSUE TITLE
Target profile page rewrite: Create RNA and Protein Baseline Expression detail views

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#547]
### Use Cases

1. As a user of the Platform, I would like to see expression levels for my target of interest in normal tissues or anatomical systems.

2. As a user of the Platform, I would like to see which experiments listed in Expression Atlas have data for my target of interest.

3. As a user of the Platform, I would like to see a summary of the data about my target of interest from GTEx.
 
### Detail Views

_Summary visualisation when user first loads detail view_
![expression_detail_view_1_summary](https://user-images.githubusercontent.com/7490258/55470101-e09dc180-55fe-11e9-90d8-bdd993fe438c.png)
**[Full-size version](https://drive.google.com/open?id=1-OEdsaFbrmBWxKSAkcwSvBLa8hGZDxHA)**

_Expression Atlas widget view_
![expression_detail_view_2_expression_atlas](https://user-images.githubusercontent.com/7490258/55470112-e4c9df00-55fe-11e9-9801-967ae948b998.png)
**[Full-size version](https://drive.google.com/open?id=1ABvBXXMBz_3Qaj1gRfE2D4gnrWgPckYz)**

_GTEx widget view_
![expression_detail_view_3_gtex](https://user-images.githubusercontent.com/7490258/55470126-ec898380-55fe-11e9-9055-41149e79a57c.png)
**[Full-size version](https://drive.google.com/open?id=14zH_6-XSi7S5zipXZmS6pFThqoacInxK)**

### Design and Interaction Notes

1. Please integrate the tab navigation bar design pattern used in the [Gene Tree detail view](https://github.com/opentargets/platform/issues/538) and [Protein Information detail view](https://github.com/opentargets/platform/issues/255).

2. On the ``Summary`` tab, please display the following text in Open Targets Grey - ``#5a5f5f``:

``Summary of GENE-SYMBOL RNA and protein expression in normal human tissue, based on Human Protein Atlas normal tissue immunohistochemistry, RNA-seq expression data and Expression Atlas data.``

Please replace GENE-SYMBOL with the HGNC gene symbol.

Please integrate the existing RNA and protein visualisation library that is displayed in the current version of the Platform.

Please update the library and change the download button from the icon to ``CSV`` and put a label beside the button - ``Download as`` - so that users are given a visual cue that they can download a CSV file of the underlying data.

2. On the ``Expression Atlas`` tab, please integrate the existing Expression Atlas visualisation widget used in the current version of the Platform.

3. On the ``GTEx`` tab, please display the following text in Open Targets Grey - ``#5a5f5f``:

``Baseline expression variation based on GTEx experiments.``

Please integrate the existing GTEx visualisation widget used in the current version of the Platform. 

Please update the download button from the icon to ``PNG`` and put a label beside the button - ``Download as`` - so that users are given a visual cue that they can download a PNG of the GTEx summary visualisation. 

### Design Assets

1. [Full-size mockups](https://drive.google.com/drive/folders/13lkIiDMxhtrKlzujLZi1SXvKkeBuqjPp)
2. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by deniseOme** [comment]
One of the use cases for the summary expression information is to show mRNA and protein expression side by side so that it eases comparison. High mRNA expression not necessarily translates into high protein expression and this is relevant for target prioritisation/

**Comment by andrewhercules** [comment]
@deniseOme, is that use case already addressed with the summary visualisation?

**Comment by deniseOme** [comment]
Yes, very much so. 
Should it be included in the list at the top?

**Comment by andrewhercules** [comment]
Okay, good to know. We don't have to include it as it's already been addressed with the existing visualisation. What I've created aren't use cases _per se_. Rather, it's the expected functionality that we're replicating in the like-for-like rewrite.

**Comment by d0choa** [comment]
@andrewhercules could you check if the implementation fits the specs? It looks good to me

**Comment by andrewhercules** [comment]
Yes, looks good to me, although will want to update the colours once we have a theme in place.

I will close the ticket for now.
