### ISSUE TITLE
Target profile page rewrite: Create conditional block for Cancer Hallmark overview data 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#548]
### Use Cases

1. As a user of the Platform, I would like to see if my target of interest has been identified as a hallmark gene by the Cancer Gene Census.

2. As a user of the Platform, if my target of interest has been identified as a hallmark gene, I would like to see the overview data curated by the Cancer Gene Census and a link to further investigate the hallmarks that are related to my target of interest. 

### Detail Views

_View when user first loads the target profile page - overview information is hidden_
![cancer_hallmarks_function_data_1_overview_hidden](https://user-images.githubusercontent.com/7490258/55478183-f1f0c900-5612-11e9-90a1-9ca40d386fe4.png)
**[Full-size version](https://drive.google.com/open?id=1wudiwEwo9S91Ge2aD7ahXkQw-MJqgZn6)**

_View when user clicks the ``[+] show overview`` link - overview information is visible_
![cancer_hallmarks_function_data_2_overview_visible](https://user-images.githubusercontent.com/7490258/55478228-0df46a80-5613-11e9-8b60-8cccf6ffef43.png)
**[Full-size version](https://drive.google.com/open?id=1_JAmDQfolU0YtIkhTy7qWPYN0fG28Y0h)**

### Design and Interaction Notes

1. During [the front-end/UX meeting on 27 March 2019](https://docs.google.com/presentation/d/1JdAZc_HkenChXkE2mS9r_BCGvReVClHNNX1dKQSgMtU/edit?usp=sharing), it was suggested that the overview information about a given target that we get from Cancer Gene Census could be shown near the top of the target profile page as it relates to the overall function of the target. 

Upon reviewing the overview information available for different targets, it was noted that the amount of information can vary. Some targets have only a few lines of information (e.g. [ERBB2](https://cancer.sanger.ac.uk/cosmic/census-page/ERBB2)) whereas other targets have more information (e.g. [TP53](https://cancer.sanger.ac.uk/cosmic/census-page/TP53)). 

To accommodate the range of overview data that may be available - and to ensure that usability of the dashboard - it is recommended that the overview information initially be hidden with a clear link to show the information if the user wishes to see it. This could subsequently be built into a design pattern if there are other websites that classify or categorise genes that the Platform already links to or will link to in the future (e.g. [target development level classification codes from Pharos](https://pharos.nih.gov/idg/help)).

2. Similar to the interaction pattern for TEPs data (see #509), the entire block will be conditionally visible - if the target has cancer hallmarks data, it will be visible; however, if the target does not have cancer hallmarks data, it will be hidden. 

3. If the target does have hallmarks data (e.g. [ESR1](https://www.targetvalidation.org/target/ENSG00000091831) or [TP53](https://www.targetvalidation.org/target/ENSG00000141510)), please display the following text in Open Targets Grey - ``#5a5f5f``:

``This target has been identified as a hallmark gene (?) by the Cancer Gene Census``

With the text, please replace the ``(?)`` with [the question-circle icon from FontAwesome ](https://fontawesome.com/icons/question-circle?style=solid) indicating that it is a tooltip that defines the term. 

Alongside the text, please display [the cancer hallmarks icon](https://drive.google.com/open?id=1ae-CcMDxhyUPPpHJUy1Z0E_hpUPtgUDJ).

4. When a user hovers over the tooltip, please display the following message:

``A hallmark gene is a gene that is listed in the COSMIC Cancer Gene Census and has one or more hallmarks that is either promoted or suppressed. Hallmarks were first identified by Hanahan and Weinberg (2000) and are used to explain the role of a gene in cancer by highlighting the classic behaviours that are displayed by the gene product and whether they are promoted or suppressed.``

5. Below the text listed in point 2, please have a clickable link ``[ + ] show overview`` in Open Targets Blue - ``#3489ca``.

If a user clicks the link, please display the overview information block as shown in the mockup above. Please outline the container for the overview information block in Open Targets Purple - ``#7b196a`` - this will provide users with a visual cue as to what information on the page is related to the overview. Also, please update the link text to ``[ - ] hide overview`` when the overview is shown. 

If a user clicks the ``[ - ] hide overview`` link, please hide the overview. 

6. Within the individual information text blocks, please provide the PubMed ID and hyperlink to EuropePMC as shown in the mockup. 

7.  At the bottom of the overview information text block, please display the following text:

``For information on the individual cancer hallmarks related to GENE-SYMBOL, please see the Cancer Hallmarks detail view.``

Please replace ``GENE-SYMBOL`` with the HGNC gene symbol. Also, please hyperlink ``the Cancer Hallmarks detail view`` to the detail view URL for the given target (e.g. https://platform-app.netlify.com/target/ENSG00000091831/cancer-hallmarks). 

### Design Assets

1. [Cancer hallmarks icon](https://drive.google.com/open?id=1ae-CcMDxhyUPPpHJUy1Z0E_hpUPtgUDJ)
2. [Full-size mockups](https://drive.google.com/drive/folders/1rMjtxshepIujjenherz-7WQFJ28ABQYi)
3. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by d0choa** [comment]
I'm a bit lost in this one @andrewhercules. Is this now part of the `Cancer Hallmarks` widget or is it an alternative component?

**Comment by andrewhercules** [comment]
It is to be an alternative widget at the top of the page because this data is more about the overall function of a gene in cancer.

In my original Cancer Hallmarks detail view spec, I had included this data in the detail view at the top of the data table or in a separate tab. But after reviewing with the team, it was decided that it should appear outside of the detail view at the top of the page because of the relevance of the data to protein function. And because of the range of data available for a given target, I suggested that we identify that it is a Cancer Census hallmark gene and have an expandable section with the data.

**Comment by d0choa** [comment]
Thanks for the info. We'll revisit this a bit later once we rewrite the current functionalities. There is a parallel discussion on whether we should show all cancer information in a more dedicated view.

**Comment by deniseOme** [comment]
@d0choa @andrewhercules, I have a couple of comments re. the terminology "profile". 

Open Targets Genetics does not have a profile page _per se_.
I'd suggest we change the wording "View ESR1 **profile** in Open Targets Genetics" to "View ESR1 in Open Targets Genetics". Another advantage of doing so it's shortened 

As per the "Target profile overview", can we have "Target profile" only? 

Note that "Overview" is there twice already, so dropping "overview" from the tab will make the title shorter and avoid potential confusion by users (what is the difference between data under "hide overview" and "target profile overview"?)

**Comment by d0choa** [comment]
I created 2 separate issues to cover these 2 topics. Feel free to comment on them

**Comment by d0choa** [comment]
I'm closing this issue for the moment. This solution is specific to cancer and the target profile page. Although important, we will have to redefine our overall strategy to present data specific to a given therapeutic area: cancer, immunology, etc.  This will affect not only target profile but also disease profile, associations, etc.
