### ISSUE TITLE
DGIdb druggability information (Target profile)

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#55]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/70)

@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/data_pipeline/issues/242)

The potential druggability information (http://dgidb.org/search_categories) should be added for consideration in the tractability project.
Are all the categories being included in the tractability pipeline? 

- [ ] Look at pharos.nih.gov and drugEBIlity as they were suggested in the Quarterly Meeting of the Industry Program in December 2017.

To follow up with Chris (Andrew Leach)/Rita

**Comment by MichaelaEBI** [comment]
DruggEBIlity and the druggable genome project are both part of the Tractability project which is now life in the platform.
