### ISSUE TITLE
Target profile page rewrite: Update target information block with new external links

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#553]
Currently, the target information block includes external links to Ensembl and UniProt along with their respective identifiers - see [issue #345](https://github.com/opentargets/platform/issues/345) for more information.

Can we please update the links that appear to include a link to HGNC and Gene Cards? This will address two existing issues - see issues #173 and #541 for more information. This change will also keep the header consistent with the Genetics Portal header - see [issue #303](https://github.com/opentargets/genetics/issues/303) for more information. 

![target-info-block](https://user-images.githubusercontent.com/7490258/55641311-8864ec00-57c5-11e9-85ac-da5600dc39ab.png)

To construct the links:

``GeneCards`` ---> ``https://www.genecards.org/cgi-bin/carddisp.pl?gene=GENE-SYMBOL``
``HGNC`` ---> ``https://www.genenames.org/tools/search/#!/all?query=GENE-SYMBOL``

Please replace the ``GENE-SYMBOL`` with the HGNC symbol value.

**Comment by d0choa** [comment]
@mirandaio has done the GeneCards already. Could you please add HGNC as well right after the GeneCards link

**Comment by mirandaio** [comment]
@d0choa The HGNC link has been added as well.
