### ISSUE TITLE
Evaluate Google Cloud Deployment Manager

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#554]
Google provide a more automated and portable system for managing infrastructure deployment than the currnet scripting approach https://cloud.google.com/deployment-manager/docs

This should be evaluated for ease of use, comprehensive coverage of the features we need, and portability if we decide to move away from GCP in future or if we wanted to make it available to partners.

**Comment by afaulconbridge** [comment]
Note, Glenn has Terraform scripts that might be useful.

**Comment by cmalangone** [comment]
This ticket can be close. Manuel will rewrite the deployment with Terraform
