### ISSUE TITLE
Add text to Open Targets homepage on Wed re. CRISPR project

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#555]
This is not really Platform related; so apologies in advance.

The CRISPR paper should go live on the 10th once Nature embargo is lifted.

@andrewhercules, would you be able to add this to the homepage please?

"Open Targets is pleased to announce that one our first experimental projects has published its findings in Nature [link to paper]. In one of the largest studies of its kind, researchers used CRISPR technology to disrupt every gene in over 300 cancer models from 30 cancer types, discovered thousands of key genes essential for cancer’s survival and developed a new system to prioritise and rank 600 drug targets that show the most promise for development into treatments. Read the press release [link to press release @ Sanger]. (edited)"

As soon I get the URL from the Sanger press I will include that here. Hopefully will get the exact time this can go live (6am ET or other)...

**Comment by andrewhercules** [comment]
I have moved this to the opentargets.github.io repository so that I can attach to a pull request once the update has been made - see [issue #91](https://github.com/opentargets/opentargets.github.io/issues/91).
