### ISSUE TITLE
Target profile page rewrite: Update placeholder text in data table filters

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#557]
Currently, data tables have filters / search bars with ``None`` as placeholder text in a dark grey colour - ``#808080``. See below for an example:

![Screenshot 2019-04-09 at 10 28 23](https://user-images.githubusercontent.com/7490258/55789425-3c11f880-5ab2-11e9-8221-a314b567ec30.png)

Instead, please update the placeholder text to read ``Select ...`` and please colour the text using Open Targets Medium Grey - ``#afafaf``. See below for an example:

![Screenshot 2019-04-09 at 10 45 58](https://user-images.githubusercontent.com/7490258/55790654-b6dc1300-5ab4-11e9-8d27-8d83e6e7534d.png)

**Comment by LucaFumis** [comment]
I've updated the text ("Select..." is actually the default option). Colour change should probably go into `ot-ui` with a new component - worth a quick chat before proceeding.

**Comment by andrewhercules** [comment]
Revisit dropdown minimising custom code

**Comment by LucaFumis** [comment]
Fixed placeholder text. No custom colours applied.
