### ISSUE TITLE
kill/redirect https://api.opentargets.io/v3/platform/docs

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#558]
Can we kill https://api.opentargets.io/v3/platform/docs or redirect from it to the following instead please?

https://platform-api.opentargets.io/v3/platform/docs/swagger-ui

**Comment by afaulconbridge** [comment]
This is done with 19.04 release.

**Comment by MichaelaEBI** [comment]
`{"code":404,"message":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}`
