### ISSUE TITLE
Amend data returned by /association/filter endpoint to include summary safety data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#559]
For phase 2 of the implementation of the target safety data, we would like to display a summary of the safety data in the Prioritisation view - see #461 for more information and a full design spec.

Can we please update the response from the Open Targets ``public/association/filter`` API endpoint to include a summary of the safety data currently contained with the gene index?

This would follow what we have done for the tractability data, as a summary of that data is available from the endpoint response (e.g. ``data[0].target.tractability``). See below for an example:

![Screenshot 2019-04-09 at 14 04 05](https://user-images.githubusercontent.com/7490258/55802588-71c5da00-5ad0-11e9-9eb1-5066d6f567c4.png)

If possible, can we process the data currently found in the gene index and provide a shorter summary in the ``public/association/filter`` API endpoint response with only a list of organs and systems affected? This could help minimise the overall size of the object returned from the endpoint and improve the performance of the web app when search for a disease with a large number of associated targets. 

For example, could we return something like this?

```
{
    "data": [
        {
            "association_score": {},
            "disease": {},
            "evidence_count": {},
            "id": "",
            "is_direct": "",
            "target": {
                "gene_info": {},
                "id": "",
                "tractability": {},
                "safety": {
                    "organs_systems_affected": ["cardiovascular system", "respiratory system", "reproductive system"]
                }
            }
        }
    ]
}
```

**Comment by cmalangone** [comment]
At the first look for the BE we need to add 
*) Add safety data to association index. (It seems that gene already has the info about safety)
*) Retrieve the information through the REST API

**Comment by andrewhercules** [comment]
Thanks @cmalangone. We're going to defer this to a later release and so I've removed it from the 19.06 release. :-)

**Comment by cmalangone** [comment]
There are two branches
DATA RELEASE
https://github.com/opentargets/data_pipeline/tree/cm_559_add_safety_info_to_association
REST API
https://github.com/opentargets/rest_api/tree/cm_559_add_safety_info_to_association

The REST API are available here:
curl -X GET http://platform-dev.opentargets.io/v3/platform/public/utils/stats

Web APP
https://platform-dev.opentargets.io:8443/
https://platform-dev.opentargets.io:8443/target/ENSG00000087085/associations (dev tools)

**Comment by andrewhercules** [comment]
@cmalangone, thank you for exposing the safety data. :-)

I have spoken to @EPetsalaki and in order to show the basic information on the prioritisation view - #461 - can the API only return the ``safety.organs_systems_affected`` array along with the ``reference value``?

So for example:

```
target: {
  safety:  [
    {
      organs_systems_affected: [{}, {}, {}],
      reference: "Lynch et al. (2017)
    },
    {
      organs_systems_affected: [{}, {}],
      reference: "Bowes et al. (2012)
    }
  ]
}
```

This should reduce the overall size of the associations object.
