### ISSUE TITLE
Network project scoping (Evidence)

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#56]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/71)

@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/data_pipeline/issues/243)

The P-P Interactions on target profile page comes from Omnipath. Idea is to replace data serve it with the data from Network project,  speak to Sandra Orchard

P-P interactions 
https://string-db.org/
https://www.ebi.ac.uk/intact/

**Comment by MichaelaEBI** [comment]
Closing this since this is in progress and more specific tickets will be created as work progresses.
