### ISSUE TITLE
Drug index: Specify partner requirements

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#563]
The drug index should enable our partners to import data about their own compounds into the Open Targets platform. So far we have feedback from one partner and they will have the following compound information:

- compound_id
- name(s)
- target
- mode_of_action
- disease?

Chemical structures have not been planned to be included in the near future.

To give an idea of what information is available for ChEMBL compounds, the fields that are available from the ChEMBL API are the following:
![Screenshot 2019-04-10 at 11 54 23](https://user-images.githubusercontent.com/34450955/55873678-30910100-5b88-11e9-88a0-0ec3760a7c5b.png)

**Comment by ElaineMcA** [comment]
Planning meeting on 15Apr based on partner feedback/requirements:

Mandatory fields: ID (unique ChEMBL or private ID)
Optional fields: name (generic); synonyms (subset of brand names); CT info; cross references.

Two files provided to OT:
1. List of drugs ---> drug index populated by ChEMBL API downloads(Cinzia)
2. Evidence strings (JSON) ---> should be kept as lean as possible.

**Comment by pieterlukasse** [comment]
Thanks @MichaelaEBI . Just to clarify: loading custom drug _evidence_ data is already possible by adding a new datasource to the "known_drug" datatype, so I am assuming this is about the drug summary page (see screenshot below). Is this correct?

**Comment by MichaelaEBI** [comment]
@pieterlukasse yes, that is correct. We are planning to store information about drugs in a separate index so that we do not have to call different APIs to generate the drug summary page. This change will also allow partners to add their own drugs and generate drug summary pages for them. Eventually the drug index will allow us to add further functionality to the platform related to drugs.

**Comment by pieterlukasse** [comment]
@ElaineMcA has this been implemented? Can you point us to the PR? Thanks!

**Comment by MichaelaEBI** [comment]
@pieterlukasse, a first version of the drug index with ChEMBL drugs has been PR'd here: https://github.com/opentargets/data_pipeline/pull/498
