### ISSUE TITLE
Drug index: Redesign drug summary page 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#564]
Using the partner requirements identified in #563, we will update the drug summary page to provide a flexible base for partners to build their own drug summary pages for internal compounds. Will will also change the API call to the OpenFDA for adverse events - see #74 for more information.

A medium fidelity mockup will be uploaded within the next week.

**Comment by andrewhercules** [comment]
## Use cases

1. As a user of the public version of the Platform that is interested in a specific drug or compound, I want to see information about the drug or compound, including its mechanisms of action, indications, and adverse events.

2. As a user of a private instance of the Platform that is interested in a specific drug or compound, I want to see information about the drug or compound along with a clearly visible flag that the drug or compound is confidential/internal-use only.

## Designs

For usability and readability, no designs are included in this ticket as they are quite large. Instead, please find all the design mockups on the [the OT Core Platform Google Drive](https://drive.google.com/drive/folders/1X8jGcOd7ZEWGVRAcCMoqWXv81YN8n8-7).

## Interaction notes

#### Page header

1. At the top of the page, please display the drug name in TitleCase, rather than all caps.

2. Underneath the drug name, please display the drug ID. If the drug is not a private compound, please link the ID to the ChEMBL page for the drug. If the drug is a private compound, please only display the ID value.

3. If the drug is not a private compound, please call the UniChem API to obtain the DrugBank ID and construct a link. DrugBank IDs can be accessed from UniChem by using the following API query:

``https://www.ebi.ac.uk/unichem/rest/src_compound_id/CHEMBL112/1/2``

Please replace the CHEMBLxxxxx with the relevant ID but keep the ``/1/2`` parameters as that is what is used to tell UniChem that we are sending a ChEMBL ID and expecting the DrugBank ID to be in the response object.

If UniChem does not return a DrugBank ID (e.g. [CHEMBL3137343](https://www.ebi.ac.uk/unichem/rest/src_compound_id/CHEMBL3137343/1/2)), please catch the error and do not show either the DrugBank label or ID - see [the CHEMBL3137343 mockup](https://drive.google.com/open?id=13ZhtHjDAUdl29cfLctsoDinnto1Lsk06) for an example.

4. If the drug is a private compound, please display the [user-lock](https://fontawesome.com/icons/user-lock?style=solid) FontAwesome icon (or the [lock](https://fontawesome.com/icons/lock?style=solid) icon) in OT Corporate Red ``#c94c52`` along with the text, ``This is a confidential internal compound!`` on the right-hand side of the page - see [the GSKSANTAK123 mockup](https://drive.google.com/open?id=1ep2W90Am87pNmqn1r7frWPHi8rnWG8ia) for an example.

#### Withdrawn information block

1. If the drug has been withdrawn, please display the withdrawn notice block with the withdrawn class, withdrawn reason, withdrawn year, and withdrawn country information - see [the CHEMBL122 mockup](https://drive.google.com/open?id=1yuPJam6omo9Ff6fya376XS_m9S-ANBQi) for an example. Please use the use [the FontAwesome exclamation-triangle icon](https://fontawesome.com/icons/exclamation-triangle?style=solid) in pure yellow ``#FFCC00`` as currently found in the target profile page safety section.

#### General properties

1. The existing text content will remain as-is

2. Please display the synonyms and known trade names using in pill format using the same ``.ot-profile-synonym-list`` CSS class used on the target and disease profile pages.

3. For the molecule structure image, please wrap the HTML block and the API call (to ChEMBL) with a conditional check to see if the drug is private or not. If the drug is private, please do not call the ChEMBL API as it will not return any information and please do not display the block. If the drug is not public, the current functionality can remain as-is - a call to the ChEMBL API if it is a small molecule, showing an antibody icon if drug is an antibody, or showing nothing if it is another modality.

#### Mechanisms of action

1. This section can remain as-is.

#### Targets

1. This section can remain as-is. However, please update the colour of the pill to use the Bootstrap ``.btn-primary`` class.

#### Diseases

1. Please construct a OT data table as shown in the mockup with columns for diseases, max clinical trial phase for that disease, and reference links.

#### Adverse events 

1. Please update the API call with [the new parameters identified by Eirini](https://github.com/opentargets/platform/issues/74#issuecomment-481181132) that will limit the data to events reported by healthcare professionals. For example, for Naproxen, the API call would be the following:

``https://api.fda.gov/drug/event.json?search=(primarysource.qualification:1+OR+primarysource.qualification:2+OR+primarysource.qualification:3)+AND+patient.drug.medicinalproduct:NAPROXEN&count=patient.reaction.reactionmeddrapt.exact)``

2. If the drug is private, please do not make a call to the Open FDA and please hide this section from the UI.

#### Publications

1. This section can remain as-is.

2. If the drug is private, please do not make a call to LINK and please hide this section from the UI.

## Required API changes

New API endpoints will be opened - details TBC

## Post-implementation review:

To ensure that the drug profile page Review drug profile page to test for various scenarios:

- [ ] ChEMBL112 Acetaminophen (small molecule with chemical structure diagram, large number of synonyms and indications, MoA contains protein family entry, multiple targets should include link to batch search)
- [ ] ChEMBL122 Rofecoxib (withdrawn drug)
- [ ] ChEMBL 3137343 Pembrolizumab (antibody with no chemical structure diagram, large number of indications, no DrugBank link)

**Comment by LucaFumis** [comment]
There are at present 3 outstanding points in this issue:
 - DrugBank ID in page header: call to unichem doesn't work from app due to CORS restrictions.
 - Diseases table: currently data is retrieved via search endpoint which doesn't return phase information. Will need to look / rethink this.
 - Private compound icon (in page header): will address this with next mini release

**Comment by LucaFumis** [comment]
Added private compound icon/message in release 3.13.2

The other two remaining items (DrugBank ID, diseases table) cannot currently be implemented (see previous comment).
