### ISSUE TITLE
Current analytics integration has hard-coded paths to EBI servers

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#565]
Examples:

https://github.com/opentargets/webapp/blob/master/app/index-tmpl.html#L336
and
https://github.com/opentargets/webapp/blob/master/app/piwik.js#L2

**Comment by afaulconbridge** [comment]
Duplicating description from associated PR https://github.com/opentargets/webapp/pull/305

Fix for https://github.com/opentargets/platform/issues/565. This PR:
- removes EBI specific configuration that was referring
to the public portal.
- changes the default behavior to "no analytics" (no piwik,
no google analytics). Makes changes to ensure this
scenario works.
- adds documentation section in README.md to explain
how one can configure the frontend to connect to his
own analytics installation.
- removes the "noscript" type of tracking by piwik

**Comment by afaulconbridge** [comment]
We've had some discussions within the team about this (@LucaFumis @andrewhercules @ElaineMcA ). In principle, we agree that tracking should be better documented and customization.

However, the master branch of the webapp needs to reflect what is deployed at www.targetvalidation.org - at least for the time being. We don't have the resources currently to adapt our deploy process to customise it, or the resources to make it fully customisable inside the app. We can probably make it customizable as part of the react rewrite (see https://github.com/opentargets/platform/issues/473 and associated tickets) but when and how that might happen depends on many factors.

One key requirement we need to make sure is that there is no spurious "noise" from local installs generated. "Event" tracking might be a particular problem for this. We've also got to check that any solution is compatible with other partners.

We will investigate further and see if we can clarify some of these requirements. In the mean time, there are already some things we can specify for the current PR that will definitely need to be changed. Those will be added to the PR to avoid cluttering here with technical detail.

**Comment by Docproc** [comment]
I'm interested in usage tracking too, so I'll be following this discussion. Anything that reduces the number of changes required to implement a different analytics platform (in my case, probably a local install of Matomo/Piwik) will be welcome.
Also it's likely very undesirable for any local install to have any possibility of reporting back to the targetvalidation.org analytics server.

**Comment by pieterlukasse** [comment]
@afaulconbridge , @Docproc: thanks for your feedback. I have updated the PR with some comments and extra commits.

**Comment by pieterlukasse** [comment]
@afaulconbridge any updates on this one?

**Comment by andrewhercules** [comment]
Given the eventual deprecation of the Angular app, this ticket will be closed and instead, the analytics code will be part of the customisation repo work - see #745 for more information
