### ISSUE TITLE
eQTL databases potential

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#57]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/72)

@ckongEbi commented on [Tue Jan 23 2018](https://github.com/opentargets/data_pipeline/issues/241)

Explore for eQTL database with Daniel Zerbino for post gap and genetics portal

1) HFGP: Human Functional Genomics Project  
[hfgp.bbmri.nl](url)

2) exQTLserve/ROSMAP
[http://mostafavilab.stat.ubc.ca/xqtl/](url)

**Comment by MichaelaEBI** [comment]
There is now an eQTL Open Targets project: http://home.opentargets.org/OTAR2046
