### ISSUE TITLE
missing small molecule tractability data throughout Platform on QA 19.04

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#571]
Missing "small molecules" data whenever tractability data is displayed in the Open Targets Platform i.e.

1) results of batch search
https://qa.targetvalidation.org/summary?targets=188906,12048
versus
https://www.targetvalidation.org/summary?targets=12048,188906

2) target profile page
https://www.targetvalidation.org/target/ENSG00000188906
versus
https://qa.targetvalidation.org/target/ENSG00000188906)

3) prioritisation view in the disease association page
https://qa.targetvalidation.org/disease/EFO_0002508/associations?view=t:priority&fcts=datatype:genetic_association;somatic_mutation;known_drug;affected_pathway
versus
https://www.targetvalidation.org/disease/EFO_0002508/associations?view=t:priority&fcts=datatype:genetic_association;somatic_mutation;known_drug;affected_pathway

**Comment by MichaelaEBI** [comment]
I have 'fixed' the tractability data file - the small molecule bucket columns were formatted as floats and not integers as expected. The updated file will be used for a pipeline re-run. I will open a ticket to amend the code to convert floats to integers if necessary so that this does not happen again.

**Comment by MichaelaEBI** [comment]
I will close this ticket because the pipeline will be started again tomorrow morning with the updated file and I have opened a ticket to prevent this issue in the future: https://github.com/opentargets/platform/issues/572
