### ISSUE TITLE
curate clinical trials as drug information for TRPV6

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#573]
A request from a user via support email.

(At least) two clinical trials are available to investigate a TRPV6 Calcium Channel Inhibitor (SOR-C13):

https://clinicaltrials.gov/ct2/show/NCT01578564?term=trpv6&rank=1
https://clinicaltrials.gov/ct2/show/NCT03784677?term=trpv6&rank=2

But Open Targets Platform has no drug information for this target (either as evidence or just annotation in the target profile page).

Can this be curated by ChEMBL at all? If not, can we have the rationale so that we can go back to the user please?

One of the trails was first reported in 2012, the other trial first reported in 2018 and updated in Jan 2019.

SOR-C13 elsewhere:
* https://www.ncbi.nlm.nih.gov/pubmed/28150073
* https://www.soricimed.com/sor-c13.htm
* https://www.cancer.gov/publications/dictionaries/cancer-drug/def/trpv6-calcium-channel-inhibitor-sor-c13

**note the trials are on solid-tumor cancer, which may not be in EFO3. Potentially a new EFO term for this so that we can have for the first time drug evidence for TRPV6: https://www.targetvalidation.org/target/ENSG00000165125/associations**

**Comment by MichaelaEBI** [comment]
@deniseOme: Requests for ChEMBL curation of clinical trials can be logged [here]( 
https://docs.google.com/spreadsheets/d/1fO97H4BJ_Lxu1GHHytibYZg92MTUTrjgRxDQ_ksK1aw/edit#gid=0)

**Comment by deniseOme** [comment]
I will add this to the spreadsheet, so closing this ticket now.
