### ISSUE TITLE
Update PhenoDigm module to use EFO3

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#576]
The working version of the PhenoDigm evidence parser (https://github.com/opentargets/evidence_datasource_parsers/tree/solr_phenodigm_1904) broke after EFO released the April 2019 release because of the upgrade to EFO 3. The problem has been solved by pointing to the **last**  EFO 2 tag (https://github.com/EBISPOT/efo/tree/v2019-03-18) but this is only a patch and the module should be updated to work with EFO 3 (among a number of other things).

**Comment by d0choa** [comment]
We should be now using EFO3 in the `evidence_datasource_parsers` settings. It's still using an outdated EFO2 version

**Comment by AsierGonzalez** [comment]
PhenoDigm was [upgraded in the `solr_phenodigm_1904` branch to use the latest EFO version for 19.11](https://github.com/opentargets/evidence_datasource_parsers/commit/7a637a6f1b720f251fe0ec57a76cb35780b70d75) following the [advice given by Zoe from SPOT team](https://github.com/EBISPOT/efo/issues/602). The parser completed as expected after the change and the results looked good but a thorough review of the changes was not done.
I'm sorry I forgot to update the ticket, it can probably be closed now.
