### ISSUE TITLE
GTEx not loading in 19.04 (since 19.02 or earlier)

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#578]
GTEx's site has changed from:
https://www.gtexportal.org/rest/v1/reference/geneId?geneId=BRAF&v=clversion
to:
https://gtexportal.org/rest/v1/expression/geneExpression?gencodeId=ENSG00000157764.8

The shape of the response may also have changed. This is not a public API, so GTEx can reasonably change it at any time, which is why our widget keeps breaking. 

Since this feature has been requested by users, we would like to try to keep it and work around calling GTEx with API calls. Besides this shows variance/variability in expression for a given gene (this is not captured by Expression Atlas for example).

Suggestions:
1) GTEx data downloaded and served from our API? 
2) From Open Targets Genetics with an analysis step
3) From expression atlas e.g. https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5214/Results?specific=false&geneQuery=%255B%257B%2522value%2522%253A%2522ensg00000157764%2522%257D%255D&filterFactors=%257B%257D&cutoff=%257B%2522value%2522%253A0.5%257D&unit=%2522TPM%2522

summary from slack discussions w/ @mkarmona @deniseOme @peatroot @iandunham 

See #136 for previous issues on GTEx widget

**Comment by andrewhercules** [comment]
@LucaFumis, I think I found a solution that might work.

For [the first API call](https://github.com/opentargets/webapp/blob/5cc54d0c613be714aae94ad8caa690169256d0db/app/plugins/baseline-expression/baseline-expression-directive.js#L29) that we make to get the ``gencodeId`` value, can we update the URL to:

``https://gtexportal.org/rest/v1/reference/gene?format=json&gencodeVersion=v19&genomeBuild=GRCh37%2Fhg19&geneId=`` + **HGNC symbol** + ``&_=1556539172141&v=clversion``

So for example, the URL for BRAF would be ``https://gtexportal.org/rest/v1/reference/gene?format=json&gencodeVersion=v19&genomeBuild=GRCh37%2Fhg19&geneId=BRAF&_=1556539172141&v=clversion``.

With the ``gencodeId`` value, can we update the [URL of the second API call](https://github.com/opentargets/webapp/blob/5cc54d0c613be714aae94ad8caa690169256d0db/app/plugins/baseline-expression/baseline-expression-directive.js#L36) to:

``https://gtexportal.org/rest/v1/expression/geneExpression?gencodeId=`` + **gencodeId**

So for example, the URL for the second call for BRAF would be ``https://gtexportal.org/rest/v1/expression/geneExpression?gencodeId=ENSG00000157764.8``.

That should return for us the same array used in the [``plotGtex`` function](https://github.com/opentargets/webapp/blob/5cc54d0c613be714aae94ad8caa690169256d0db/app/plugins/baseline-expression/baseline-expression-directive.js#L54).

**Comment by LucaFumis** [comment]
Hi @andrewhercules that is correct. GTEx changed the endpoint name from `/geneId` to `/gene` for that first call (to get full gene ID).
Keeping the other parameters and second call as originally implemented by Miguel P appears to work correctly.
