### ISSUE TITLE
update Link for EFO3

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#579]
LINK has to be updated for EFO3 if we want that bibliography works for all new disease IDs (e.g. MONDO IDs, HP IDs) coming up with EFO3 e.g.

https://qa.targetvalidation.org/disease/MONDO_0000044
https://qa.targetvalidation.org/disease/MONDO_0044710
https://qa.targetvalidation.org/disease/MONDO_0037821
https://qa.targetvalidation.org/disease/HP_0012075

More example of MONDO IDs can be found on [OT Pipeline Metrics - 19.04 ](https://docs.google.com/spreadsheets/d/1mNkDjnxud9ANJiVsbP5i-fSV7mixDHOzVQ6jx__M31s/edit#gid=1492578396).

Note this is also an issue for current production (i.e. EFO2) e.g.
https://www.targetvalidation.org/disease/Orphanet_101435

If this can't or won't be fixed, we should at least provide a message for the users to know why Bibliography does not work for some diseases.

**Comment by ElaineMcA** [comment]
Additional discussions required to confirm actionable plans:

Short-term:
1. Assess extent of specific MONDO terms/ diseases affected and propose appropriate message text to present in UI.

2. Long-term: requires effort estimation
a.  Google library expiration issue to be addressed
b. New dictionary to be created for EFO 3
c. Source original list from Andreas and ePMC

**Comment by d0choa** [comment]
Resolved since 19.11
