### ISSUE TITLE
Disease Prevalence Information (Disease profile)

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#58]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/74)

Include disease prevalence on Disease Profile Page.

- [ ] Assess World Health Organisation (common diseases) and orphanet (rare diseases) as data sources
- [ ] Identify additional data sources for disease prevalence
- [ ] Extract, transform and load data
- [ ] API and frontend changes

**Comment by MichaelaEBI** [comment]
Enquire at EFO whether they will include disease prevalence data in EFO and if so, when?

**Comment by d0choa** [comment]
Not a priority at the moment. We'll reopen if necessary
