### ISSUE TITLE
Generate Gene2Phenotype evidence as genetic_assocation type

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#585]
Currently we generate the Gene2Phenotype evidence as genetic_literature data type and then the pipeline hardcoded replaces genetic_literature with genetic_association.

We should generate it correctly as genetic_association in the first place. Note this will change how it is validated by the schema, so we need to ensure it is still valid after this change.

**Comment by MichaelaEBI** [comment]
`genetic_literature` refers to evidence strings that do not provide variant information. Therefore they need to be validated against a different JSON schema than `genetic_association`.
