### ISSUE TITLE
Remove genetic_literature evidence type from schema

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#586]
Related to opentargets/platform#584 and opentargets/platform#585 to replace `genetic_literature` evidence type with `genetic_assocation`  once they have been completed, the `genetic_literature` type should be remove from the JSON schema.

**Comment by MichaelaEBI** [comment]
`genetic_literature` refers to evidence strings that do not provide variant information. Therefore they need to be validated against a different JSON schema than `genetic_association`.
