### ISSUE TITLE
Remove genetic_literature -> genetic_association change in pipeline

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#587]
Related to opentargets/platform#584 and opentargets/platform#585 to replace `genetic_literature` evidence type with `genetic_assocation`  once they have been completed, the `genetic_literature` to `genetic_assocation` hardcoded change should be removed from `data_pipeline`.

**Comment by MichaelaEBI** [comment]
`genetic_literature` refers to evidence strings that do not provide variant information. Therefore they need to be validated against a different JSON schema than `genetic_association`.
