### ISSUE TITLE
Proteomics data (Evidence)

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#59]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/75)

Proteomics data has been suggested several times for inclusion in the Open Targets platform. ProteomicsDB and MaxQB have been suggested as data sources.

- [ ] Assess PRIDE, ProteomicsDB and MaxQB as potential data sources - what is the overlap between these repositories?
- [ ] Are there other mass spec experiment repositories?
- [ ] Extract, transform and load data
- [ ] API and front end changes

**Comment by d0choa** [comment]
We're expecting PRIDE to eventually provide data through ExpressionAtlas. We'll keep an eye on it
