### ISSUE TITLE
Similar targets & diseases: review function and provide explanation to users 

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#590]
### Observed behaviour:
Feedback from users is that they do not understand fully what is presented here, and importantly, the scoring and logic or ranking approach for those associations that are presented here versus those presented in the associations view.

**Similar diseases:**

https://www.targetvalidation.org/disease/EFO_0000249

- only shows up to top 20 in array
- rarer diseases put higher over common diseases 
- uses overall score from associations page
- not visible in GSK (switched off)

**Similar targets:**
https://www.targetvalidation.org/target/ENSG00000171862

- Only shows up to top 20 associations on expansion of each bubble
- Tooltips or legend at top of visualisations would add context

- [ ] Nabeel to assist with providing suggestions to replace current bubbles view from Sanofi user group.

- [ ] Make available a more extensive explanation of scoring mechanism for this section on intranet for partners ASAP.

**Comment by ElaineMcA** [comment]
Next steps confirmed 09May2019:

1. Current visualisation
- [ ] Update with legend and tooltips @andrewhercules 
- [ ] Work with @deniseOme to extend documentation to explain principles used and also post on intranet for partners with other scoring training slides.

2. Changes to visualisation:
Changes have already been implemented as part of FE rewrite.
- [ ] Seek further feedback on possible other visualisation options from users.

3. Download of complete data for section:
Not immediate requirement/ for action now.  Will be considered if a need once further info on point 2 above.

**Comment by deniseOme** [comment]
@ElaineMcA, a tentative document to address the extended doc task is available in the [google drive](https://docs.google.com/document/d/1CdA5ydrccTfF5Z4SxeIcfKRSh5ZfCMDiaqiqWC84mf0/edit#)

**Comment by andrewhercules** [comment]
Currently, the description for the Similar Targets tab reads ``Other targets related to ESR1 based on common associated diseases`` while the Similar Diseases tab reads``Other diseases related to multiple sclerosis based on common associated targets``.

However, based on feedback from users at Sanofi, we should provide a better description of the visualisation and a link to documentation that explains how the similarity score is calculated. 

For [the description at the top of the Similar Targets tab](https://github.com/opentargets/webapp/blob/master/app/plugins/related-entities/related-targets.html), can we please update it to read the following?

``Targets related to GENE-SYMBOL based on a computation of similar target-to-disease connections and overall association scores. For more information on this visualisation and how we generate similarity scores, please read our documentation on target and disease similarity.``

For [the description at the top of the Similar Diseases tab](https://github.com/opentargets/webapp/blob/master/app/plugins/related-entities/related-diseases.html), can we please update it to read the following?

``Diseases related to DISEASE-NAME based on a computation of similar disease-to-target connections and overall association scores. For more information on this visualisation and how we generate similarity scores, please read our documentation on target and disease similarity.``

In both cases, can we please link the text ``our documentation on target and disease similarity`` to a new FAQ page on target and disease similarity? @deniseOme, can you please open a new FAQ page with [the description on how we compute target and disease similarity](https://docs.google.com/document/d/1o-asCqS4pcWB0E9AOI0cAp-e5_tg4InxWWAL_rXOVwc/) and add the link to this ticket? @LucaFumis, please use this link once ready.

Also, @LucaFumis, can we please [add basic event tracking](https://docs.google.com/spreadsheets/d/1hAPI9dV0PEAjT2iDZOYifoe94Sxe9t_4mJNYkfoc6aE/edit#gid=0) when a user clicks a related entity and views an underlying association?

**Comment by deniseOme** [comment]
@LucaFumis, FAQ link created and content added to the page:
https://docs.targetvalidation.org/faq/how-do-you-compute-target-and-disease-similarities

**Comment by LucaFumis** [comment]
Will add tracking with next mini-release

**Comment by andrewhercules** [comment]
Closing this ticket as tracking for this widget a low priority that can be addressed in the rewrite

**Comment by dhimmel** [comment]
Just starting to look at the disease similarities, but excited that this data could be very useful! I noticed that https://www.targetvalidation.org/disease/EFO_0000249 includes:

> The top 20 diseases related to Alzheimer's disease based on a computation of similar disease-to-target connections and overall association scores. Clicking on a related disease bubble will show you a list of the targets used to calculate the similarity between the two diseases. For more information on this visualisation and how we compute similarity scores, please read [our documentation on target and disease similarity](https://docs.targetvalidation.org/faq/how-do-you-compute-target-and-disease-similarity).

The link for "documentation on target and disease similarity" is incorrect and should be updated to https://docs.targetvalidation.org/faq/how-do-you-compute-target-and-disease-similarities.
