### ISSUE TITLE
Automation of various post-pipeline steps

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#591]
There are a few steps that are currently run with various scripts manually after the pipeline has run. It would be good to at least get the code for all these into one place, document each of them and then see whether they should all be run from a single script.

Steps that are run manually after a pipeline run:
 - [x] 1. Generation of file with unique targets (for reactome to link out to us, as input for the tractability pipeline) (DONE, see #657)
 - [x] 2. Disease list with multiple identifiers, including ICD10 (for MalaCard to link out to us)
 - [x] 3. New and lost diseases and targets compared to previous OT release
 - [x] 4. Pipeline metrics to populate the release metrics table
 - [x] 5. Feedback to data providers on non-validated evidence strings 
 - [x] 6. Generation of site map (#607)

**Comment by afaulconbridge** [comment]
For the site map that is ticket opentargets/platform#607 right?

**Comment by MichaelaEBI** [comment]
Update:
For 2.: A first version of a disease list will be made available for download from the 19.09 Open Targets release.
For 3.: It is very easy now to retrieve new and lost targets and diseases using the downloadable lists generated for points 1. & 2.
For 4.: The python code to generate the metrics has been handed over to Asier and can eventually be added to the pipeline in some form.
For 5.: The code for this will be handed over to Asier and this will probably remain a semi-manual step for now.

**Comment by hammer** [comment]
Will the code that maps EFO ID to ICD10 code be made available as open source?

**Comment by MichaelaEBI** [comment]
The first version of the disease list does not contain any cross-references (see specs here #657).The code that maps EFO IDs to ICD10 will probably be part of the pipeline and therefore be open source, if and when it gets implemented.

**Comment by hammer** [comment]
@MichaelaEBI thanks for the update. I thought perhaps the code that was used to generate the spreadsheet at https://github.com/opentargets/genetics/issues/353#issuecomment-497243088 might be used.

**Comment by d0choa** [comment]
Not sure if I'm missing something but the current version of EFO keeps ICD10 cross-references (e.g. [Myotonic syndrome](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_206970)). I would guess the mappings are as complete as the ones in the aforementioned spreadsheet. From the [EFO repo](https://github.com/EBISPOT/efo), it seems many of the mappings have been curated manually, so there might be no such code at the end.

**Comment by hammer** [comment]
@d0choa I do see those xrefs in the download of `efo.xml` but not in the `efo-data` index produced by Open Targets. Is the plan then to simply import those mappings?

**Comment by d0choa** [comment]
We don't have any short-term plans to include more cross-references in the index. We don't see the need as EFO does this for us. If you see any important use-case we might reconsider.

**Comment by hammer** [comment]
@d0choa I think there are 2 primary reasons to incorporate more external identifiers in the EFO index: first, to facilitate users from communities that make use of non-EFO disease and phenotype ontologies; and second, to facilitate joining against external data sources that use non-EFO disease and phenotype ontologies as identifiers.

We think it would be valuable to build a plugin architecture for `efo-data` similar to what's currently in place for `gene-data`. This would allow the data pipeline to enrich traits with metadata like prevalence and unmet needs. Many sources of prevalence and unmet needs data don't currently use EFO identifiers.

**Comment by d0choa** [comment]
This task is mainly complete although some subtasks might still be pending.

The issue to improve our cross-references is not a high priority at the moment. OxO and Zooma from the EBI SPOT team solve part of the issue at the moment. A never ending task is to keep investigating the best way to improve and standardise our phenotype/disease mappings.
