### ISSUE TITLE
Variants panel not working or too slow

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#595]
Steps to reproduce:

1. go to https://www.targetvalidation.org/target/ENSG00000139618
2. open panel "Variants, isoforms and gnomic context"

It will either take a very long time to load (with no indication of progress) or just not load at all.

**Comment by LucaFumis** [comment]
Mmhh... yes, there is a bunch of post requests to ensembl API and most appear to fail (500 code). 
For others I get error 400. For some (e.g. BRAF) it is slow but works upon reloading the page.
Not sure if there have been changes on Ensemble side...

**Comment by d0choa** [comment]
With the most recent updates in genetics portal, phewas catalog and clinvar there are a number of functionalities that are not scaling well to the genome browser.

The whole approach will need to be reimplemented in the React application. Closing as the angular viewer will soon be obsoleted
