### ISSUE TITLE
Protein information panel "Variants" track sometimes not shown

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#596]
For some genes the "Variants" track on "Protein information" panel will not show.

Steps to reproduce:
1. go to https://www.targetvalidation.org/target/ENSG00000139618
2. the last track "Variants" will sometimes not load

tested on a low end Lenovo laptop with Windows 7 (_not_ my laptop in case you are wondering)

**Comment by d0choa** [comment]
Not able to reproduce. Probably fixed by ProtVista team
