### ISSUE TITLE
Drug index: Requests to change data returned from API

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#602]
Thank you to @afaulconbridge who has created an API branch that serves the JSON from the drug index. Please see https://platform-api-drug.opentargets.io/v3/platform/private/drug/CHEMBL83 and https://platform-api-drug.opentargets.io/v3/platform/private/drug/CHEMBL122 for examples of the current JSON data and structure.

This ticket will track all requests for changes to the API response, which is based on [the JSON schema files found in the team Google Drive](https://drive.google.com/drive/folders/1jJzdsyf4WumiC9zOG-FVQShpJH8Zw3Bd).

**Comment by andrewhercules** [comment]
@afaulconbridge, can we please include some additional data so that the front-end can recreate the current drug profile page using our API endpoints?

## ``indications`` object

Format currently returned by API:

```
"indications": [
  {
    "efo_id": "EFO:0004616"
  },
  {
    "efo_id": "EFO:0000305
  },
]
```

**Additional requirements for initial front-end implementation (MVP):**

- [ ] Name of disease/phenotype

However, if possible, can we please also return the following (low-priority, but would allow us to create and future-proof an indications data table):

- [ ] Maximum phase for the specific indication
- [ ] References for each indication (e.g. Clinical Trial IDs, FDA links, etc.)
- [ ] Therapeutic area for indication based on EFO2 or EFO3

## ``targets`` object

_No data is currently returned by the API_

**Additional requirements for initial front-end implementation (MVP):**

- [ ] An array that returns Ensembl ID, UniProt ID, and HGNC symbol for each target

## ``mechanisms_of_action`` object

**Format currently returned by API:**

```
"mechanisms_of_action": [
  {
    "references": [
      {
        "source": "PubMed",
        "ids": ["18819158"]
      },
    ]
    "description": "Estrogen receptor alpha modulator",
    "action_type": "modulator"
  }
],
```

**Additional requirements for initial front-end implementation (MVP):**

- [ ] Type of target (e.g. single protein, protein family, protein complex)
- [ ] Full name of target
- [ ] HGNC symbols of target (or symbols of all targets that are members of protein family or complex)
- [ ] Ensembl IDs of target (or IDs of all targets that are members of the protein family or complex)

## Other attributes

- [ ] Are we able to include the DrugBank IDs from @MichaelaEBI's mapping and include it in the ``cross_references`` array? (low-priority as I seem to remember Michaela mentioning that there are differences in coverage between ChEMBL and DrugBank)

**Comment by afaulconbridge** [comment]
> Therapeutic area for indication based on EFO2 or EFO3
Do we still want this for 19.06 @andrewhercules ? I think we decided to omit it for implementation phase I ?

**Comment by afaulconbridge** [comment]
> Can we please add a boolean field that partners can set to true if the drug is an internal, private compound not listed in ChEMBL?

This does exist in the code and is supported in the input file, but isn't present in the files we download from chembl so currently isn't included in our API response. I could make it default explicitly to `true` if that is preferred ? What do you think @andrewhercules ?

**Comment by afaulconbridge** [comment]
> Are we able to include the DrugBank IDs from @MichaelaEBI's mapping and include it in the cross_references array? (low-priority as I seem to remember Michaela mentioning that there are differences in coverage between ChEMBL and DrugBank)

We could do this, but it would be a relatively large amount of effort. We need to decide where to get it from (UniChem?), make sure its a file we can freeze somewhere, then add it to the configuration and parse it. Perhaps best left for implementation phase II @andrewhercules ?

**Comment by andrewhercules** [comment]
> > Therapeutic area for indication based on EFO2 or EFO3
> 
> Do we still want this for 19.06 @andrewhercules ? I think we decided to omit it for implementation phase I ?

Yes, my apologies - it has been omitted for 19.06 and can be done once we have migrated to EFO3

**Comment by andrewhercules** [comment]
> > Are we able to include the DrugBank IDs from @MichaelaEBI's mapping and include it in the cross_references array? (low-priority as I seem to remember Michaela mentioning that there are differences in coverage between ChEMBL and DrugBank)
> 
> We could do this, but it would be a relatively large amount of effort. We need to decide where to get it from (UniChem?), make sure its a file we can freeze somewhere, then add it to the configuration and parse it. Perhaps best left for implementation phase II @andrewhercules ?

Agreed - let's focus on cross-references for phase 2. In the interim, I will ask the front-end team to construct a link to DrugBank if UniChem's API returns the DrugBank number (e.g. for [Acetaminophen](https://www.ebi.ac.uk/unichem/rest/src_compound_id/CHEMBL112/1/2)). If there is no value returned by the API - a 404 error - we will not show the link. Also, we will encapsulate this in a check to see if the drug is listed in ChEMBL or if it is a private partner compound.

**Comment by andrewhercules** [comment]
@afaulconbridge, in the ``mechanisms_of_action`` section of the API response, can we please include the ``targets.target.pref_name`` value from ChEMBL's ``/target`` endpoint?

For example, with [Acetaminophen](https://www.targetvalidation.org/summary?drug=CHEMBL112), one of the mechanisms of action is Cyclooxygenase ([CHEMBL2094253](https://www.ebi.ac.uk/chembl/api/data/target?target_chembl_id=CHEMBL2094253
)). Our API currently returns the names of the individual components of this protein family but not the name of the family itself.

**Comment by deniseOme** [comment]
Does this mean that by leaving cross-references to phase 2, synonyms will not be captured in the revamped drug summary page.

Keep in mind the support email we had on the 21 May, user could not find the correspondence between drug names e.g. CCI-779 = TEMSIROLIMUS. Can we at least get the ChEMBL synonyms?

**Comment by iandunham** [comment]
No, they are two different issues - synonyms should be there but cross references to otehr database pages not

**Comment by andrewhercules** [comment]
> > Can we please add a boolean field that partners can set to true if the drug is an internal, private compound not listed in ChEMBL?
> 
> This does exist in the code and is supported in the input file, but isn't present in the files we download from chembl so currently isn't included in our API response. I could make it default explicitly to `true` if that is preferred ? What do you think @andrewhercules ?

I've spoken with @LucaFumis and for the front-end, can we please always return a boolean value that will be used to show/hide page elements and run/ignore third-party API calls?

If possible, can we keep this consistent with the flag used to denote if an evidence string is private? I believe the field is ``is_private``, but @afaulconbridge can you please confirm?

**Comment by afaulconbridge** [comment]
> > > Are we able to include the DrugBank IDs from @MichaelaEBI's mapping and include it in the cross_references array? (low-priority as I seem to remember Michaela mentioning that there are differences in coverage between ChEMBL and DrugBank)
> > 
> > 
> > We could do this, but it would be a relatively large amount of effort. We need to decide where to get it from (UniChem?), make sure its a file we can freeze somewhere, then add it to the configuration and parse it. Perhaps best left for implementation phase II @andrewhercules ?
> 
> Agreed - let's focus on cross-references for phase 2. In the interim, I will ask the front-end team to construct a link to DrugBank if UniChem's API returns the DrugBank number (e.g. for [Acetaminophen](https://www.ebi.ac.uk/unichem/rest/src_compound_id/CHEMBL112/1/2)). If there is no value returned by the API - a 404 error - we will not show the link. Also, we will encapsulate this in a check to see if the drug is listed in ChEMBL or if it is a private partner compound.

Great. I've created a sepearate issue to track this in future : opentargets/platform#612

**Comment by afaulconbridge** [comment]
> > > Therapeutic area for indication based on EFO2 or EFO3
> > 
> > 
> > Do we still want this for 19.06 @andrewhercules ? I think we decided to omit it for implementation phase I ?
> 
> Yes, my apologies - it has been omitted for 19.06 and can be done once we have migrated to EFO3

To track this, I've created a new issue opentargets/platform#613

**Comment by afaulconbridge** [comment]
I think all of these are now implemented. If there's anything else that needs to be done for 19.06 please say ASAP!

**Comment by andrewhercules** [comment]
All good for the front-end - happy to close this ticket unless any other issues to raise?

**Comment by andrewhercules** [comment]
Closing this ticket as JSON response meets all of the front-end requirements - thanks @afaulconbridge! 👍
