### ISSUE TITLE
Associations page: Bubbles and trees with therapeutic areas w/o score

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#603]
**Observed behaviour:**

<img width="1039" alt="Screen Shot 2019-05-17 at 13 52 22" src="https://user-images.githubusercontent.com/40168275/57929442-3d052980-78ab-11e9-8d81-653f20637743.png">

**Investigation/ data scenarios:**
1. API only returns therapeutic areas with an association score
2. Data sources (i.e Expression Atlas) can produce scores that are not propagated to the parent terms
3. Cases where child nodes have scores but TA does not don't crash the UI

**Proposed solution:**
Static API response with list of all TAs --> UI

**Comment by afaulconbridge** [comment]
As an alternative solution, we could propagate atlas evidence. That would be the "ontology" way to solve this problem.

**Comment by d0choa** [comment]
@afaulconbridge there was probably a good reason why the ExpressionAtlas data was not propagated in the first place. It occurs to me multiple reasons why we might not want to propagate certain evidences that apply to a specific disease but not general terms. From a more philosophical perspective, one single ontology might not be the unique solution to explain all the complexity in biology. Propagating in the EFO might not solve everything.

**Comment by d0choa** [comment]
What we need @cmalangone is an API response that returns the list of all therapeutic areas. The response will always be the same for the same release, therefore it will be cached. With this response @LucaFumis will be able to rescue the bubbles/trees that are currently not working

**Comment by cmalangone** [comment]
There is a new endpoint available /public/utils/therapeuticareas
branch: cm_603_static_response_for_therapeutic_area
Test: http://platform-bubble.opentargets.io/v3/platform/public/utils/therapeuticareas

**Comment by cmalangone** [comment]
The code is merged in master.

**Comment by andrewhercules** [comment]
Reopening to track work to be done on front-end for 19.06 release

**Comment by richardbrunt-tessella** [comment]
The fix applied in https://github.com/opentargets/webapp/commit/ec13c3f66d0d6778a573d1ab781356cfd65f1c12#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 breaks yarn builds in certain situations. Our docker build now gives the following yarn error:

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/opentargets/targetAssociationsBubbles.git HEAD
Directory: /build
Output:
fatal: not a git repository: /build/../.git/modules/webapp
```

This is because the yarn.lock hasn't been updated - we had to add the following change to the yarn.lock to get the build to succeed:

```diff
@@ -1882,9 +1882,9 @@ cttv.spinner@0.0.1:
   version "0.0.1"
   resolved "https://registry.yarnpkg.com/cttv.spinner/-/cttv.spinner-0.0.1.tgz#f8aa7f7ed1d71cec8b08fae6a88fee71258aff2b"

-cttv.targetAssociationsBubbles@0.0.17:
+cttv.targetAssociationsBubbles@opentargets/targetAssociationsBubbles:
   version "0.0.17"
-  resolved "https://registry.yarnpkg.com/cttv.targetAssociationsBubbles/-/cttv.targetAssociationsBubbles-0.0.17.tgz#d2128d3d1b4c304087a
+  resolved "https://codeload.github.com/opentargets/targetAssociationsBubbles/tar.gz/081e01ff0dbc910f8b9a90d4292cb7a4c2ff59de"
   dependencies:
     cttv.api "0.0.15"
     cttv.bubblesView "0.0.5"
```

@LucaFumis any chance you can fix this in opentargets/webapp?

**Comment by LucaFumis** [comment]
Well spotted @richardbrunt-tessella. I updated and pushed the lock file - hopefully that fixes it. I'll update tags etc later on.
