### ISSUE TITLE
Create sitemap generator script and generate sitemaps for Platform using 19.06 data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#607]
To improve search engine coverage and to support our SEO efforts, we should update our sitemaps - the last sitemaps were submitted a year ago using data from the 18.04 release. 

To do:

- [x] Develop initial version of XML sitemap generator script in Python
- [x] Code review by engineering team
- [x] Run script using data from the 19.06 release
- [x] Upload new sitemaps to [webapp /sitemaps directory](https://github.com/opentargets/webapp/tree/master/app/sitemaps)
- [x] Submit URL of index.xml sitemap to all search engines
- [x] Investigate the possibility of adding this pipeline as a last (optional) step for the existing OT pipeline

**Comment by andrewhercules** [comment]
[Initial version of XML sitemap generator script](https://github.com/andrewhercules/ot-data-utils/blob/master/xml-sitemap-generator/xml-sitemap-generator.ipynb) now available. Script has been run using a small list of 5 targets and diseases.

**Comment by afaulconbridge** [comment]
>  Upload new sitemaps to webapp /sitemaps directory

Are we sure we want to do that? I'm not sure having big files included in the git repository is the best approach - particularly if they are being automatically generated. 

According to https://support.google.com/webmasters/answer/75712?hl=en&ref_topic=4581190# we should be able to host the sitemaps on opentargets.io via a Google bucket that refer to targetvalidation.org

**Comment by andrewhercules** [comment]
Yeah, it may not be the best option to host the files directly in the GitHub repository. Currently, all sitemaps total about 10mb but I expect that will increase with EFO3 and any potential changes we may make about what is indexed (e.g. drug profile pages, gold standard evidence pages, etc.).

@afaulconbridge, I was actually going to ask about hosting on Google buckets as cross-domain sitemaps is [supported by all major search engines](https://www.sitemaps.org/protocol.html#sitemaps_cross_submits).

**Comment by peatroot** [comment]
@andrewhercules, the script that was used last time is [here](https://github.com/opentargets/webapp/blob/master/sitemap-generator.js).

**Comment by andrewhercules** [comment]
Thanks @peatroot. I used that as a basis to write the script in Python as I am hoping that it might be automatically run in the pipeline as an optional last step.

**Comment by afaulconbridge** [comment]
Do we have to generate static file sitemaps? On previous projects, I've built the sitemap generation into the API itself which worked well - no need for an extra step, easier to automate and maintain since its part of the API, always up-to-date, etc.

**Comment by andrewhercules** [comment]
I don't think so - all that the search engines require is a link to an index sitemap that itself links out to all the other sitemaps. We currently have static XML files but am happy to explore other alternatives. 👍

**Comment by ElaineMcA** [comment]
Actions agreed 25-Jun-2019 (@andrewhercules @afaulconbridge meeting):

- [ ] Crawl issues: @andrewhercules to check logs and filter by user agent - to assess # times that google is falling over when calling API endpoints (targets, disease, associations).  What does the google search engine see?

- [ ] Soft 404 errors: ignore for moment, refreshing sitemap more regularly post each release should resolve this

- [ ] Robots.txt file needed at the root of each branch (e.g. EFO3) to disallow indexing on internal branches versus production environments (option to set environment variables in config file in Netlify for build).

- [ ] How to implement?

FOR NOW (18.06, 18.09):
1. Retain as separate script for the moment
2. Validate the ownership using DNS
3. Automate as part of release process - GC output generated
4.  Retain in webapp repo (current location for moment until React Rewrite further along) 

LONGTERM 
1. Dissociate google analytics and site map from Web App as part of rewrite
2. Build into API as separate endpoint, easier to automate completely

**Comment by andrewhercules** [comment]
Sitemaps have been generated for target profile, target association, disease profile, and disease association pages and have been added to a ``/sitemaps`` directory on targetvalidation.org - see https://www.targetvalidation.org/sitemaps/index.xml.

![Screenshot 2019-07-09 at 09 37 55](https://user-images.githubusercontent.com/7490258/60873002-921b4700-a22d-11e9-856d-e684b54f1236.png)

Once new sitemaps have been fully indexed, the older sitemap using 18.04 release data can be removed from Google Search Console.

**Comment by andrewhercules** [comment]
Sitemaps have been generated and submitted to Google and Bing (for Microsoft and Yahoo search engines). Sitemaps will be generated after each releasing using either the associations data dump or the gene/disease list generated as part of #657.
