### ISSUE TITLE
Add new data table for additional target safety information

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#609]
New data table will be added to Target Safety block with known risks.

A full design spec will be completed once data has been processed by @EPetsalaki.

**Comment by EPetsalaki** [comment]
[Here](https://drive.google.com/open?id=1L_uvV5BsjX5rtpe6IvDjbkxgFTmLwFHF) is a first version of the new json file for 19_06: known safety data. It needs minor editing in the text, but the json schema should remain the same. 

New fields: 
- known safety split into 2 sections: adverse effects and safety liability. Targets CDK2 and AKT1 have both safety liability and adverse effect information.
- safety liability has reference info, organs affected and a string field with the safety information (NOT EFO-mapped list of side effects)
- reference format is changed into a list (was string). 3 fields for reference info (all list format): reference (author names), pmid & ref_link. The reference links are provided if no pmid is available. If there is both a reference link and a pmid, use the pmid.  
- additional field "unspecified interaction effects" within adverse effects section (if we don't know if it's activation or inhibition effects). No data currently in this field, but we are expecting to have some there soon, so this is included as well so that we can decide on how to show these.

**Comment by andrewhercules** [comment]
@EPetsalaki, can we please update the references to return a list of objects with ``ref_label``, ``ref_link``, and ``pmid`` attributes? 

```
"references": [
    {
        "ref_label": "Bowes et al. (2012)",
        "ref_link": "",
        "pmid": "23197038",
    },
],
```

or 

```
"references": [
    {
        "ref_label": "Urban et al. (2012)",
        "ref_link": "https://doi.org/10.1002/9781118098141.ch2",
        "pmid": "",
    },
    {
        "ref_label": "HeCaToS_2.2",
        "ref_link": "https://www.hecatos.eu/home",
        "pmid": "",
    }
],
```

**Comment by EPetsalaki** [comment]
Done! Please find the new file (24th May) [here](https://drive.google.com/drive/folders/17XlZ3R8Iw838XTKiasMgeOtQytXtpETW).

**Comment by andrewhercules** [comment]
Thanks @EPetsalaki - looks great! 👍

**Comment by andrewhercules** [comment]
Building on the work done for #460, there are some changes that we will make for the upcoming 19.06 release as there is new ``safety_risk_info`` data to display.

**Updated designs:**

_Existing data table (e.g. [ACHE](https://www.targetvalidation.org/target/ENSG00000087085))_
![target_safety_ache](https://user-images.githubusercontent.com/7490258/58325356-5b29d700-7e21-11e9-8326-41f16972d44c.png)

_New data table for ``safety_risk_info`` data (e.g. [MTOR](https://www.targetvalidation.org/target/ENSG00000198793) or [PIK3CA](https://www.targetvalidation.org/target/ENSG00000121879)_
![target_safety_mtor](https://user-images.githubusercontent.com/7490258/58325358-5bc26d80-7e21-11e9-9914-967845372f13.png)

_Layout change if both ``adverse_events`` and ``safety_risk_info`` data is available (e.g. [AKT1](https://www.targetvalidation.org/target/ENSG00000142208) or [CDK2](https://www.targetvalidation.org/target/ENSG00000123374))_ 
![target_safety_akt1](https://user-images.githubusercontent.com/7490258/58325357-5bc26d80-7e21-11e9-866f-178db60ce9ee.png)

To accommodate the new data, can we please:

1. Update the tab description text box to read ``Known safety effects and safety risk information for HGNC-GENE-SYMBOL``

2. Add a heading to each table - ``Known safety effects`` and ``Safety risk information``

3. Create a new data table for the ``safety_risk_info`` with the following columns - ``Main organs and systems affected``, ``Safety liability information``, and ``Publications``

4. If both data tables are displayed, reuse the same layout used for tabs that have multiple tables (e.g. [Genetic evidence tab for ESR1 and genetic disorder](https://www.targetvalidation.org/evidence/ENSG00000091831/EFO_0000508?view=sec:genetic_association)) similar 

Also, there is a change in how the data used for the ``Publications`` column in both data tables is returned by the API. Previously, they were individual values, but to accommodate multiple values for a single row, it will now be an array of objects found in the ``references`` attribute.

For example 

```
"references": [
    {
        "pmid": "",
        "ref_link": "https://doi.org/10.1002/9781118098141.ch2",
        "ref_label": "Urban et al. (2012)"
    },
    {
        "pmid": "",
        "ref_link": "https://www.hecatos.eu/home",
        "ref_label": "HeCaToS_2.2"
    }
],
```

or 

```
"references": [
    {
        "pmid": "21283106",
        "ref_link": "",
        "ref_label": "Force et al. (2011)"
    },
    {
        "pmid": "",
        "ref_link": "https://www.hecatos.eu/home",
        "ref_label": "HeCaToS_5"
    }
],
```

Can we please display the ``ref_label`` and construct a link to EuropePMC using the ``pmid`` value. However, if the ``pmid`` is not available, please construct to the ``ref_link`` value instead.

**Comment by EPetsalaki** [comment]
Hello, can we use a tooltip on the 'HeCaToS' reference? The content that should appear in the tootip is 'HeCaToS Deliverable D01.5 (2015) funded by "EU 7th Framework Programme (HEALTH-F4-2013-602156)."'

**Comment by LucaFumis** [comment]
@EPetsalaki ideally that tooltip would come with the API response, otherwise we have to start matching strings in front end... what do you think @andrewhercules ?

**Comment by d0choa** [comment]
Correct me if I’m wrong @EPetsalaki or @andrewhercules but I think we discussed to do it in the front-end. 

It’s a very particular thing. It won’t change for HeCaTos and it’s unlikely we have others in the near future.

**Comment by andrewhercules** [comment]
@d0choa, yes we decided to do it on the front-end because it is a very specific issue and the entire safety section will go through further iterations as more safety data is added.

@LucaFumis, can you please include the tooltip? I know it's not ideal but it's short-term until more safety data (e.g. buckets) are ready. :-)

**Comment by LucaFumis** [comment]
As per discussion with @andrewhercule, added standard title attribute for HeCaTos link which shows on rollover after a second or so.
