### ISSUE TITLE
Management of OT data source suggestions

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#61]
@MichaelaEBI commented on [Tue Jul 10 2018](https://github.com/opentargets/data_release/issues/88)

Data sources are continually suggested for Open Targets data sources and we ran workshops asking for data source suggestions. The goal of this issue is to:

1. Provide an overview of current data source suggestions

- All data source suggestions are captured in this [Google Sheet](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1017254333). 
- A summary of the data source suggestions from the Industrial workshop on 05 December 2017 can be found [here](https://docs.google.com/spreadsheets/d/1o8SfK1Z6feCP3pNY77ZHCD5mbyKZx4xDj-x4l6q9aqY/edit#gid=0).
- Details for top data source suggestions from the Nov 2017 Open Targets Integration Day and the Dec 2017 Industry workshop can be found [here](https://docs.google.com/spreadsheets/d/1kMVh2JybvJdh00xtkQWjfKCZIMiReLPdSUXShDb33HQ/edit#gid=0).

2. Triage all current data source suggestions
- This is in process in this [Google sheet](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1017254333).
- [x] Get gene expression data suggestions assessed by Expression Atlas

3. Implement a process for future data source suggestions
A first version of a [form for data source suggestions](https://docs.google.com/a/ebi.ac.uk/forms/d/1hBwAt5O3yJ7nwPF2j8i-zWNCBdUhPS6ooFc3I31ezkk/edit?usp=drive_web).

4. Keep partners updated on progress
Overview of progress: [integration of new data sources](https://docs.google.com/spreadsheets/d/1DOtMYpl13IS2tMTUnRAvbDnxoo1RPDH_d0lR8gLFV7E/edit#gid=0)

**Comment by MichaelaEBI** [comment]
Closing this ticket because everything is under control and all the information in this ticket has been added to the [Data FAQ document](https://docs.google.com/document/d/1e_6a5s04T019W5_s2s8XMfMZd5hXjJ6YoUfES_5OMVw/edit).
