### ISSUE TITLE
Elasticsearch parallel_bulk swallows exceptions

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#610]
The `elasticsearch.helpers.parallel_bulk` function in the official library for silently swallows non-TransportError exceptions e.g. ones raised by our code. This means that problems are ignored and the pipeline continues regardless.

We should create a minimal example (e.g. https://gist.github.com/afaulconbridge/77b43dcdaedadbbdffd8449472272aba ) and raise this as an issue with Elasticsearch. Only if they do not fix it should we investigate alternative solutions.

As a work-around, if the number of worker threads is set to zero in the pipeline then `elasticsearch.helpers.streaming_bulk` will be used instead. Performance will be worse, but that helper does correctly propagate exceptions.

**Comment by afaulconbridge** [comment]
This does not happen with elasticsearch 7

**Comment by afaulconbridge** [comment]
This should be addressed indirectly by opentargets/platform#551 when elasticsearch is upgraded

**Comment by afaulconbridge** [comment]
https://github.com/opentargets/data_pipeline/pull/522 has been merged and  https://github.com/opentargets/platform/issues/551 closed. This ticket should therefore be resolved - I'll leave it open for the moment until this is confirmed.

**Comment by cmalangone** [comment]
@afaulconbridge : should we close this ticket due the migration to ES7.2?

**Comment by afaulconbridge** [comment]
Probably. Nothing immediately says that this is still a problem, and if something does crop up we can always re-open or create a new issue.
