### ISSUE TITLE
Drug index: DrugBank cross references

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#612]
On the Drug Summary page, we would like to provide links to external drug databases other than ChEMBL (e.g. DrugBank).

From Andrew: The DrugBank ID is not returned from ChEMBL consistently. ChEMBL provides `Cross references` and `UniChem Cross References` and these sections contain a range of IDs but somewhat inconsistently (e.g. some compounds have DrugCentral as a cross-reference, others do not). ChEMBL’s own UI relies on a call to the UniChem API to get all associated IDs. To get around this issue, we tried using the UniChem API but Luca ran into CORS issues, which prevent us from displaying the ID - see https://github.com/opentargets/platform/issues/564#issuecomment-506400407 for more information from Luca.

Michaela received a ChEMBL-DrugBank mapping file from ChEMBL, this was generated using UniChem.

Ideally, we would work with a 'frozen' file to import and handle by the pipeline that is also extensible by partners to add their own cross reference e.g. to internal services.

**Comment by MichaelaEBI** [comment]
ChEMBL provided the following: When we generate each new update of UniChem, we upload mapping tables for each source to the FTP site. We have a Chembl ID to Drugbank ID mapping file at the following link, which should always be the up to date version:
ftp://ftp.ebi.ac.uk/pub/databases/chembl/UniChem/data/wholeSourceMapping/src_id1/src1src2.txt.gz

**Comment by ElaineMcA** [comment]
BE not viable for 18.09 unless possible for Cinzia to pick up during August.

**Comment by ElaineMcA** [comment]
Priority placed on aggregation activities for 19.09.

**Comment by afaulconbridge** [comment]
I'm going to put the input file in the OTAR001-core bucket at https://storage.googleapis.com/otar001-core/DrugBank/src1src2.txt.gz We'll need to integrate it into `platform-input-support` for 19.11 release.

**Comment by andrewhercules** [comment]
DrugBank IDs now available in the API and displayed on the drug profile page
