### ISSUE TITLE
Drug index: indication therapeutic area

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#613]
Once we have completed the migration to EFO3, we should add a response to the API to summarise the therapeutic area of the drug indications so that e.g. pie chart can be constructed on the front end.

**Comment by d0choa** [comment]
See #603

**Comment by afaulconbridge** [comment]
Implemented in branch `af-613-indication-tas` will have API output like:
```
          "indication_therapeutic_areas" : [
            {
              "therapeutic_code" : "MONDO_0045024",
              "therapeutic_label" : "neoplastic, precancerous and hyperplastic disease",
              "count" : 17
            },
            {
              "therapeutic_code" : "EFO_0001379",
              "therapeutic_label" : "endocrine system disease",
              "count" : 4
            }
          ]
```

**Comment by andrewhercules** [comment]
Data not yet displayed in API response - will look at resolving in 20.02 data release

**Comment by andrewhercules** [comment]
Closing as data is available and used in rewrite version of drug profile page (e.g. [Rofecoxib](https://platform-app.netlify.com/drug/CHEMBL122))
