### ISSUE TITLE
Allow platform-input-support to output single value lists

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#614]
Currently, platform-input-support will only output a list to the pipeline config file if there are mulitple values in the list.

For the drug index, there will be lists of values representing input files. For the core platform, there will only be a single file in each list, but it needs to be a list to support extension by partners.

Therefore, platform-input-support will need to support this.

**Comment by cmalangone** [comment]
PR here
https://github.com/opentargets/platform-input-support/pull/6
Branch
https://github.com/opentargets/platform-input-support/tree/cm_614_add_optional_resource_type
