### ISSUE TITLE
pipeline plugin cancerbiomarkers externalize configuration

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#615]
The `data_pipeline` plugin `cancerbiomarkers` has a large amount of data hard-coded into it. This should be split out to separate file(s) which can be hosted on Google Buckets and coped using `platform-input-support` in line with other configuration.

**Comment by d0choa** [comment]
@cmalangone I wonder if this ticket still stands after the recent work in biomarkers or we should be closing it

**Comment by cmalangone** [comment]
This ticket is related to the current pipeline. 
However, the cancerbiomarkers info are stored inside the gene index. 
The new pipeline will manage a similar approach. (gene step rewrite)
