### ISSUE TITLE
Target profile page rewrite: Ensure cross-browser compatibility

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#617]
To ensure that all Open Targets partners will be able to implement the new app written in React, we need to ensure that it can be rendered on a variety of devices and browsers.

Can we please run cross-browser testing, especially for the Windows 7 + IE11 technical environment? 

For the testing, can we please:

- [ ] Ensure that dashboard view with widgets loads and that widgets have the right content and correctly show as active and disabled depending on the data returned from the API
- [ ] Ensure that all detail views load and that interactions and visualisations work and are consistent across all browsers
- [ ] Test the dashboard layout with different screen resolutions, in particular the top 5 screen resolutions based [on the Google Analytics screen resolution report from 1 August 2018 to 30 May 2019](https://analytics.google.com/analytics/web/#/report/visitors-browser/a101860681w176880194p180872126/_u.date00=20180801&_u.date01=20190529&explorer-segmentExplorer.segmentId=analytics.screenResolution&explorer-table.plotKeys=%5B%5D):  ``1920 x 1080``, ``1366 X 768``, ``1440 x 900``, ``1536 x 864``, and ``1280 x 720``.

**Comment by Docproc** [comment]
I'm sure you're already aware, but services like [BrowserStack](https://www.browserstack.com/) and [Sauce Labs](https://saucelabs.com/) allow testing (automated and manual) on lots of different browser/OS combinations.

**Comment by andrewhercules** [comment]
Thanks @Docproc - will take a look at Sauce Labs! 👍

**Comment by d0choa** [comment]
Since #681 we have browserstack + nightwatch to smoke test if the app crashes in different browsers. Currently, we are only checking for 1 browser setup, but we'll expand to an array of sensible browsers.

**Comment by d0choa** [comment]
I'm closing this ticket and breaking down into pieces for the next steps to follow
