### ISSUE TITLE
Target profile page rewrite: Handle errors behind 3rd party APIs in GraphQL

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#621]
There are two parts to this:
* handle third party API errors within `platform-api` resolvers and propagate a sensible message to the response
* handle error messages in a more uniform way within `platform-app`

### Within platform-api
One useful point from [this apollo article](https://blog.apollographql.com/full-stack-error-handling-with-graphql-apollo-5c12da407210) is to ensure parts of any query that should be able to fail independently are nullable (ie. don't have `!` on the schema description).

Things we should check/change:
* summaries query contains independent, nullable subfields
* resolver queries to third-party APIs time out (else we wait for slowest)
* error messages are passed by apollo-server when resolvers fail, but we can clarify them further by catching resolver errors and throwing `UserInputError`s with custom messages (see article)

### Within platform-app
Almost all GraphQL queries from the client use the `<Query>` tag. The conditional content is then rendered based on `({ loading, error, data })` state. In most cases, `platform-app` currently renders nothing unless `data` is non-`null`. The `genetics-app` shows a loading bar by rendering one conditionally on the value of `loading`.

We should consider how to handle `loading` and `error` states in a reusable way across many subcomponents. The Ant Design framework has a nice idea of having [skeleton components](https://ant.design/components/skeleton/). To do this, we'd need skeletons for common UI components, such as header text, tables, charts, etc.

**Comment by d0choa** [comment]
Example: ADORA3 has a problem in the expression atlas widget reported in the angular app (see #127 and #601). In the rewrite, all widgets are missing for [ADORA3](https://platform-app.netlify.com/target/ENSG00000282608) probably because of the same issue.

**Comment by peatroot** [comment]
Following discussion today, the ADORA3 case is not an issue with querying all summaries at once. The GraphQL API returns the data for the other summaries, we just need better handling on the client side (see response).

<img width="567" alt="Screenshot 2019-06-12 at 23 03 11" src="https://user-images.githubusercontent.com/7376272/59390329-d6b7dd80-8d68-11e9-9ae8-7d623bbe6a2d.png">

**Comment by peatroot** [comment]
Update:
* no timeouts in place yet
* graphql api resolvers fail independently per section (with messages)
* app always displays same message (needs to pipe through graphql message from api)
* also still need clearer message for network error

**Comment by andrewhercules** [comment]
Need to follow up as [ADORA3 target profile page](https://platform-app.netlify.com/target/ENSG00000282608) is now blank with error message in console

**Comment by mirandaio** [comment]
Finally done using React error boundaries.
