### ISSUE TITLE
Pathways panel in target profile page shows error instead of diagram

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#626]
When I open the target profile page for a gene that has pathways available, say [BRAF](https://www.targetvalidation.org/target/ENSG00000157764), and open the **Pathways** panel, I see the following error message where I'd expect a diagram:

![Widget showing the text "There was a problem while loading the diagram" on a brick-red background](https://user-images.githubusercontent.com/4929431/59103970-91427d00-8930-11e9-9327-1aa224df91c5.png)

This occurs both on the public platform and on local deployments.

**Comment by fedde-s** [comment]
@LucaFumis, any ideas what could be going wrong here?

**Comment by afaulconbridge** [comment]
@fedde-s we've had a chat with the people from Reactome about this (benefits of being in the same building!) and it seems to be a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue. www.reactome.org is a 301 redirect to reactome.org and reactome.org has `Access-Control-Allow-Origin`:`*` but www.reactome.org doesn't. So when javascript served from www.targetvalidation.org makes a request to www.reactome.org there is a redirect response without the CORS header, and the browser blocks following it. It's unclear why this has happened today or what has changed - Reactome will investigate more next week. Also next week @LucaFumis will check the calls the webapp makes and update them all to be directly against reactome.org

**Comment by LucaFumis** [comment]
That was based on the suggestion to remove 'www' from Reactome URLs, but actually introduced an error in the batch search results. This is now fixed in commit 8de31d987915548449c9262cae506eb57ceba057

I'll merge and tag that and push a mini release out.

**Comment by fedde-s** [comment]
@LucaFumis, will there be a release tag for 3.12.3 on GitHub when it's ready?

**Comment by LucaFumis** [comment]
Hi @fedde-s, yes I've just merged and sorted out the tags.
There is a 3.12.3 tag in GitHub
Quay: 3.12.3 (also tagged as 19.04.7)

@ElaineMcA the mini release is now live; I've updated the log.

**Comment by LucaFumis** [comment]
This implements the quick fix as suggested by Reactome (i.e. removing the "www" from calls). 
I believe they're investigating in parallel so there _might_ be the need for further changes but for the time being this should work.

**Comment by fedde-s** [comment]
Fix confirmed: I see a diagram again.
