### ISSUE TITLE
Protein interactions panel in target profile page spins forever

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#627]
When I open the target profile page for a gene, say [BRAF](https://www.targetvalidation.org/target/ENSG00000157764), and open the **Protein interactions** panel, I see a blue loading spinner that does not seem to be disappearing.

This occurs both on the public platform and on local deployments.

I believe it to be waiting for a network request that has already been rejected, a GET request to the address `/proxy/www.omnipathdb.org/interactions?partners=P15056&format=json` that received a HTTP 500 (internal server error) response with no further details. The browser console reports the following programming error:
```
Possibly unhandled rejection: {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/proxy/www.omnipathdb.org/interactions?partners=Q9BZ11&format=json","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Internal Server Error","xhrStatus":"complete"}
```

**Comment by fedde-s** [comment]
@LucaFumis, any ideas what could be going wrong here?

**Comment by afaulconbridge** [comment]
@fedde-s It seems that OmniPath DB was down for a few hours, hence the inability to display. They seem to have resolved it now and its working again so I'll close this ticket. Thanks for reporting it promptly!
