### ISSUE TITLE
Rename tab name from "Target Profile Overview" to "Target Profile"

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#628]
As per the "Target profile overview", can we have "Target profile" only? 

Note that "Overview" is there twice already, so dropping "overview" from the tab will make the title shorter and avoid potential confusion by users (what is the difference between data under "hide overview" and "target profile overview"?)

_Originally posted by @deniseOme in https://github.com/opentargets/platform/issues/548#issuecomment-500399534_

**Comment by andrewhercules** [comment]
Let's put this on hold until we decide which version is preferred - be it the dashboard-style or single-page/GeneCard style. If we go for the single-page/GeneCard style, we will likely want to revisit the Association/Target Profile tab layout.
