### ISSUE TITLE
Rename link from "View ESR1 profile in Open Targets Genetics" to "View ESR1 in Open Targets Genetics"

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#629]
@d0choa @andrewhercules, I have a couple of comments re. the terminology "profile". 

Open Targets Genetics does not have a profile page _per se_.
I'd suggest we change the wording "View ESR1 **profile** in Open Targets Genetics" to "View ESR1 in Open Targets Genetics". Another advantage of doing so it's shortened 

_Originally posted by @deniseOme in https://github.com/opentargets/platform/issues/548#issuecomment-500399534_

**Comment by andrewhercules** [comment]
Let's put this on hold until we decide which version is preferred - be it the dashboard-style or single-page/GeneCard style. If we go for the single-page/GeneCard style, we will likely want to revisit the page header layout and this would be part of that.
