### ISSUE TITLE
Data: Incomplete target mapping for Probe Miner links

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#63]
@MichaelaEBI commented on [Thu Aug 09 2018](https://github.com/opentargets/data_release/issues/91)

Probe Miner links for 2606 targets will be in the OT 18.08 release. Several targets are missing for various reasons and they should be investigated:

- [ ] 7 targets from the chemical probes_probeminer.tsv file were not injected
- [x] 7 targets have data in the probe miner data dump, but are not found on the website and can't be mapped to targets in OT: 5-HT4a, 5-HT4b, 5-HT4d, 5-HT7b, 5-HT7L, 5-HT7S, E7ESS2
- [x] 2 targets cannot be mapped to UniProt or HGNC symbols: GABA C & GPR103
- [x] 8 target UniProt IDs cannot be [mapped](https://docs.google.com/spreadsheets/d/19-lMLradjc1aZnmoO3erThNlDMUkBZGjQOYl59gOYOQ/edit#gid=493136799): P06881, Q01043, Q16198, Q58F15, Q6LAF7, Q8TDZ9, Q96QA9, Q9BRH5, Q9H4C2, Q9UM81

**Comment by MichaelaEBI** [comment]
Probe Miner has been updated. Running the pre-processing script on the new download file reveals that there are 15 proteins that cannot be mapped. For 12 of these there are no Probe Miner pages. Will liaise with Probe Miner over these.

Probe Miner UniProt ID | Nr. of probes | Note | Probe Miner pages that do not exist
-- | -- | -- | --
A1Z199 | 30 | BCR/ABL p210 fusion protein | https://probeminer.icr.ac.uk/#/A1Z199
E7ESS2 | 2 | American mink | https://probeminer.icr.ac.uk/#/E7ESS2
A8K2H7 | 4 | https://www.uniprot.org/uniprot/A8K2H7 for C3AR1 which is also https://www.uniprot.org/uniprot/Q16581 | https://probeminer.icr.ac.uk/#/A8K2H7
P06881 | 104 | CALCA - Calcitonin gene-related peptide 1, not Calcitonin which is P01258 | 
Q01043 | 4 | Cyclin homolog, gene 72 in Herpesvirus saimiri | 
Q13748 | 560 | Obsolete: https://www.uniprot.org/uniprot/Q13748 | 
Q16198 | 1 | EWS-Fli1, https://www.uniprot.org/uniprot/Q16198, cannot find HGNC ID | https://probeminer.icr.ac.uk/#/Q16198
Q504U8 | 2 | EGFR, but P00533 on HGNC https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:3236 | https://probeminer.icr.ac.uk/#/Q504U8
Q58F15 | 2 | EPHA4, but P54764 on HGNC https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:3388 | https://probeminer.icr.ac.uk/#/Q58F15
Q6LAF7 | 18 | No gene name: https://www.uniprot.org/uniprot/Q6LAF7 | https://probeminer.icr.ac.uk/#/Q6LAF7
Q8TDZ9 | 40 | CES hBr2 - not on HGNC | https://probeminer.icr.ac.uk/#/Q8TDZ9
Q96QA9 | 4 | MRP3 - not on HGNC | https://probeminer.icr.ac.uk/#/Q96QA9
Q9BRH5 | 15 | DGAT1, but on HGNC it is O75907 | https://probeminer.icr.ac.uk/#/Q9BRH5
Q9H4C2 | 4 | MDM2, but on HGNC it is Q00987 https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:6973 | https://probeminer.icr.ac.uk/#/Q9H4C2
Q9UM81 | 7 | PTPsigma - not in HGNC | https://probeminer.icr.ac.uk/#/Q9UM81
