### ISSUE TITLE
Target profile page rewrite: Create Safety widget

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#633]
### Use Cases

1. As a user of the Platform, I want to see if safety data is available for my target

### Summary Widget Views

![safety-widget](https://user-images.githubusercontent.com/7490258/59498050-889bfa80-8e8c-11e9-938d-9426bd4dac0e.png)

### Design and Interaction Notes

1. For targets where there is safety data (e.g. [ACHE](https://www.targetvalidation.org/target/ENSG00000087085) or [PTGS2](https://www.targetvalidation.org/target/ENSG00000073756)), please use the following text in Open Targets Grey - ``#5a5f5f``:

``Drug target safety data assessment data available for GENE-SYMBOL``

Please use [the FontAwesome exclamation-triangle icon](https://fontawesome.com/icons/exclamation-triangle?style=solid) or similar icon in the Open Targets Purple - ``#7b196a``.

2. For targets where there is safety data (e.g. [ESR1 ](https://www.targetvalidation.org/target/ENSG00000091831)or [LIMK1](https://www.targetvalidation.org/target/ENSG00000106683)), please use the following text in Open Targets Light Grey - ``#e2dfdf``:

``Drug target safety data assessment data not available for GENE-SYMBOL``

Also, please colour the icon and the widget container box outline in Open Targets Light Grey - ``#e2dfdf``. 

3. When a user hovers over the summary widget and the target has either a small molecule and/or an antibody tractability assessment, please show the ``pointer`` icon and change the box outline to Open Targets Purple - ``#7b196a``. This will provide users with a visual cue that the summary widget is clickable. For more information, please see issue #429.

### Design Assets

1. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by d0choa** [comment]
As discussed, please add the `title` in Hecatos based on this #609

**Comment by mirandaio** [comment]
@andrewhercules @d0choa Hecatos tooltip has been added.

**Comment by d0choa** [comment]
Thanks @mirandaio!
