### ISSUE TITLE
Error at --as step

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#634]
I found this error message in the `--as` step logs (data_pipeline version 19.04.5):
```
2019-06-17 10:16:59,748 6 mrtarget.modules.Association INFO - stages created, running scoring and writing
2019-06-17 10:17:47,962 90 mrtarget.common.ElasticsearchLoader WARNING - push to
elasticsearch failed for chunk: (u'3 document(s) failed to 
index.', [{u'index': {u'status': 400, u'_type': u'association', u'_index': u'19.04_association-data', 
u'error': {u'reason': u'mapper [harmonic-sum.datasources.chembl] cannot be changed from type
[float] to [long]', u'type': u'illegal_argument_exception'},
```

`mapper [harmonic-sum.datasources.chembl] cannot be changed from type
[float] to [long]`

**Comment by afaulconbridge** [comment]
We've not encountered this before. Please confirm exactly which version of elasticsearch you are using (we use 5.6.13) and if you get this error when running with only the public data (i.e. to see if we should be able to reproduce it from that).

**Comment by pieterlukasse** [comment]
I'm using this `image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14`

**Comment by afaulconbridge** [comment]
Can you confirm if you get this with public data? It sounds like its trying to save an integer into a float field, and I wonder if it got that integer by loading from an evidence string in a previous `--val` step.
