### ISSUE TITLE
consistently use elasticsearch-dsl in assocations step

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#635]
In data_pipeline around line 324 there is:

```
    for ev in helpers.scan(client=es, query=query_body,
        index=index, size=1000):
        yield ev['_source']
```

which uses `elasticsearch.helpers` to do the scan. This should be replaced with the `elasticsearch-dsl` version to do the same thing, for consistency with scans performed elsewhere int he same file and the rest of the pipeline. We should also check for anywhere else in data_pipeline that uses `helpers.scan()` and create further tickets if appropriate.

**Comment by cmalangone** [comment]
Merged in master
