### ISSUE TITLE
Make code to generate release available as OSS?

### ISSUE THREAD

**Issue by hammer** [opentargets/platform#636]
I noticed that #611 was closed w/ a PR to the `platform-infrastructure` repo which does not appear to be public. For those of us who would like to build upon Open Targets, it would be helpful to see the precise code that creates the release.

**Comment by afaulconbridge** [comment]
Unfortunately, that repository contains confidential information and therefore cannot be made public.

However, we are in the process of preparing various pieces of documentation based on our experiences that will hopefully be helpful to you. We expect to have them completed after the summer.
