### ISSUE TITLE
Customizable Elasticsearch scroll timeout

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#639]
Make the scroll timeout configurable and consistent through the pipeline.
The hot fix to add a parameter with the scroll timeout fixed the immediate problem.
Eg. Association.py
Search().using(es).index(self.es_index_gene).query(MatchAll()).params(scroll = '4h').scan()
and
helpers.scan(client=es, query=query_body, scroll='4h', index=index, size=1000)

Related issue:
#504

**Comment by d0choa** [comment]
no action expected
