### ISSUE TITLE
description of Gene trees has a wrong URL for one of the linkouts

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#641]
@LucaFumis @d0choa, both QA and WWW have `orthologies` in the description of the Gene tree tab pointing to Ensembl Plants, rather than Ensembl.

Can we change that please? Also change the "orthologies" to "homology types" so that is the same as the title of the Ensembl page?

This is the page to link out to:
https://www.ensembl.org/info/genome/compara/homology_types.html

In summary, we would have:

"Phylogenetic tree showing the history of the human gene APP based on protein sequences from [Ensembl](http://www.ensembl.org/). All branches in this tree have the same length (unscaled branches). You can also view the branches in different lengths based on the number of evolutionary changes in the tree (select scaled branches) All species are shown by default, but you can prune it to a subset of species by unticking the species accordingly. Check [Protein trees](https://www.ensembl.org/info/genome/compara/homology_method.html) and [homology types](https://www.ensembl.org/info/genome/compara/homology_types.html) for further details."

**Comment by d0choa** [comment]
Thanks @deniseOme. "Homology types" is more appropriate than "orthologies" and the link was also the wrong one. I'll create a different issue for the React app

**Comment by ElaineMcA** [comment]
Updated in mini-release  v3.13.2 on 04Jul2019.
