### ISSUE TITLE
19.06 QC: Pathways facet empty on association page

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#643]
No facets showing under pathway types: https://qa.targetvalidation.org/disease/EFO_0000249/associations

![Screen Shot 2019-06-21 at 11 35 26](https://user-images.githubusercontent.com/40168275/59922205-0aa99780-9428-11e9-81df-86c4e3d8ce5e.png)

Per @LucaFumis:
The API response for the facets appears to be missing content for the pathway types:

![Screen Shot 2019-06-21 at 12 58 08](https://user-images.githubusercontent.com/40168275/59922241-2f9e0a80-9428-11e9-99ec-99df327d40cb.png)

**Comment by afaulconbridge** [comment]
This is solved in master by https://github.com/opentargets/data_pipeline/pull/518 and by https://github.com/opentargets/data_pipeline/commit/b81bb003d1aeb474690ccb75a85da59172fb85c2 for 19.06.3

**Comment by cmalangone** [comment]
Hot fix merged in master. Added some comments about how to improve the code. (Adam hints)
