### ISSUE TITLE
Underspecified resource creating an Health checks (platform-infrastructure)

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#644]
The command 
 gcloud beta compute --project=open-targets-platform health-checks create http platform-id-es --request-path=/_nodes/_local --port=9200 --check-interval=10s --timeout=10s --unhealthy-threshold=3 --healthy-threshold=1
raises an error 
ERROR: (gcloud.beta.compute.health-checks.create.http) Underspecified resource [platform-190623-135354-19-06-3-es]. Specify one of the [--global, --region] flags.

**Comment by afaulconbridge** [comment]
More context please. What were you trying to do? What config were you using?
