### ISSUE TITLE
batch search results no longer allows for filtering per TA

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#645]
In the past, the results of the batch search used to allow for filtering based on TA (therapeutic area). 

It used to work at least up to 18.12 as per a [short animation] and attached below: (https://www.youtube.com/watch?v=iWPXX7gPlAc&t=7s).

![Screen Shot 2019-06-26 at 11 48 47](https://user-images.githubusercontent.com/6472381/60174217-7dd85280-9808-11e9-9440-5b177b3e3965.png)

This is the current status of 19.06 QA: 
![Screen Shot 2019-06-17 at 15 19 21](https://user-images.githubusercontent.com/6472381/60174076-2639e700-9808-11e9-8d77-4dfff6ac0410.png)

If we decide not to fix this, at least we should disable the "more" option, which is just above the "Download" button.

![Screen Shot 2019-06-26 at 11 54 21](https://user-images.githubusercontent.com/6472381/60174565-369e9180-9809-11e9-9c80-a49b628b7595.png)

**Comment by ElaineMcA** [comment]
Low priority confirmed at team meeting 01Jul.  Will assign to release once resource available.

**Comment by LucaFumis** [comment]
This is now fixed - I will push a mini release on Monday morning.

**Comment by ElaineMcA** [comment]
Pushed to production 08-Jul-2019.  Change log updated.
