### ISSUE TITLE
URL name/link mismatch from uniprot_somatic

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#65]
@peatroot commented on [Fri Nov 17 2017](https://github.com/opentargets/data_pipeline/issues/210)

 Clicking on the first row for somatic mutations in the `webapp` [here](http://www.targetvalidation.org/evidence/ENSG00000012048/EFO_0000305?view=sec:somatic_mutation) (hyperlinked as UniProt), links to dbSNP rather than UniProt. 

Having looked at the API response, the `evidence/filter` endpoint is returning data with an `evidence.urls` field containing eg.
```
{
  url: "http://identifiers.org/dbsnp/rs80357069",
  nice_name: "Further details in UniProt database"
}
```

---

@elipapa commented on [Mon Jan 08 2018](https://github.com/opentargets/data_pipeline/issues/210#issuecomment-355964444)

we may have to change the text / hyperlink, because i don't believe uniprot has URLs for rsIDs.
@ckongEbi ?

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_pipeline/issues/210#issuecomment-403770368)

we will ask Uniprot to look at update the `nice_name` field

**Comment by d0choa** [comment]
This is an important point for the evidence cleaning and data provider guidelines. I'll make a note and keep it for a future ticket in the matter. Closing for now
