### ISSUE TITLE
Copy/Sync the release files stored in the google storage to private EBI FTP (platform-infrastructure)

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#655]
1) Copy/Sync platform release files stored in the google storage to private EBI FTP
2) Copy/Sync genetic release files stored in the google storage to private EBI FTP

**Comment by cmalangone** [comment]
The github repository plafform-infrastructure has a new directory called
sync_google_storages_to_ebi_ftp
Inside this directory there is a README file that explains how to execute the commands.

**Comment by andrewhercules** [comment]
Issue closed as work completed as part of 20.04 release process
