### ISSUE TITLE
Provide Open Targets target/disease files for download

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#657]
There are now multiple use cases for Open Targets target list/mapping file:
1. reactome uses a list of all targets in Open Targets to link to our Target Profile pages for all targets in Open Targets
2. ChEMBL provides links to Open Targets in the Protein Cross References section of their Target Report Cards

![Screenshot 2019-07-05 at 14 21 33](https://user-images.githubusercontent.com/34450955/60725162-45372800-9f30-11e9-9cc3-11e42314dba4.png)

Denise, July 04, 2019: However, they generate links to all alternate sequences in the human genome and since Open Targets only uses the primary assembly, many link-outs point to Open Targets pages with no information. ChEMBL would like to use a file with UniProt --> Ensembl mappings.

3. In the 19.06 release COSMIC evidence associated with FAS has been assigned to FASN. The reason for this is the gene name mapping to Ensembl gene IDs by Ensembl. COSMIC uses gene names and maps these to Ensembl gene IDs and Ensembl search results include synonyms and obsolete synonyms as matches. Between the 19.04 and 19.06 COSMIC data submissions, the Ensembl gene IDs for 20 out of 714 genes changed. Some changes resulted in the correct Ensembl gene ID, others in an incorrect gene ID and one change switched from one incorrect gene ID to another incorrect one (all for genes where the gene name is a synonym for another gene) - details can be found [here](https://docs.google.com/spreadsheets/d/1xonlvNlh6wO2Wg4rU9y8LxfFKpIxm16kkxreyGR5XB4/edit#gid=0).

4. GeneCards and MalaCards linking to Open Targets - see ticket #541

5. These files can also be used to generate site maps.

6. Tractability pipeline

7. Others?
 
Points to consider:
- [x] When should the file be made available? COSMIC would need it for data generation for Open Targets releases whereas ChEMBL and reactome would need the file whenever they are working on a new release.
--> Generate file as part of the automated release process
- [x] File columns: Ensembl Gene ID, UniProt ID, HGNC Gene Name?
-->  ensembl_gene_id, uniprot_id, hgnc_symbol, has_associations
- [x] Depending on where within the Open Targets platform a link points to (Target Association/Target Profile page), the genes listed should/should not have associations. Should we provide two files or add a column with a flag to indicate whether a target has associations?
- [x] Would we always provide the latest version of the file at a fixed link or provide a file with each release?
--> Provide a file with each release
- [ ] File format: JSON or .TSV? Multiple UniProt IDs can correspond to the same Ensembl ID and (not as often) a UniProt ID can be related to more than one Ensembl ID

**Comment by afaulconbridge** [comment]
I was talking with @andrewhercules about this for the site map. I suggest this could be implemented as  "JSON dumps" alongside existing evidence and association dump files, and therefore easily integrated into the automated release process. As a side-effect, it would then also be available through our python client (if it isn't already, I haven't checked).

**Comment by andrewhercules** [comment]
I have created the sitemaps using a list of targets and diseases generated from the 19.06 release association dump. 

* [List of targets (Ensembl ID, HGNC symbol)](https://drive.google.com/open?id=1KYvi2G8mkznTlhKD7l6CdhjHN8nkwitP)
* [List of diseases (ID, label)](https://drive.google.com/open?id=18-tVVzrlIPiDGJrMd0-NCs0Qk82vcyxz)

The target list does not include UniProt IDs as I was unsure of the best way to map Ensembl IDs to UniProt IDs.

**Comment by MichaelaEBI** [comment]
For 58,825 **targets** in the OT19.06 release, I have used `jq` to extract `Ensembl gene ID`, `UniProt accessions`, `HGNC approved symbol` and `Number of associations` from the elasticsearch `search-data` index into
a) a csv file [OT1906_target_list.csv.zip](https://github.com/opentargets/platform/files/3427996/OT1906_target_list.csv.zip)

`cat 19.06_search-data.json | jq -r '. | select(.type=="target") | [.id, .approved_symbol, [.uniprot_accessions | join("|")][],  .association_counts.total] | @csv' > OT1906_target_list.csv`
```
"ENSG00000205002","AARD","Q4LEZ3|A5PKU8",56
"ENSG00000157426","AASDH","Q4L235|A5D8V3|A5PL22|Q63HK2|Q63HR7|Q6IPP8|Q6TFZ6|Q7Z5Y3|Q96BW4|Q9P064",17
"ENSG00000143994","ABHD1","Q96SE0|B3KSF6|E9PDR9|Q05BY3|Q53SZ1|Q8IXQ7",7
"ENSG00000100439","ABHD4","Q8TB40|B4DDH7|Q9H9E0",17
"ENSG00000264031","ABHD15-AS1","",0
"ENSG00000183260","ABHD16B","Q9H3Z7",5
"ENSG00000099204","ABLIM1","O14639|A6NI16|A6NJ06|A8MXA9|B3KVH2|Q15039|Q5JVV1|Q5JVV2|Q5T6N2|Q5T6N3|Q5T6N5|Q68CQ9|Q9BUP1",218
"ENSG00000278540","ACACA","Q13085|B2RP68|B2ZZ90|Q6KEV6|Q6XDA8|Q7Z2G8|Q7Z561|Q7Z563|Q7Z564|Q86WB2|Q86WB3",216
"ENSG00000076555","ACACB","O00763|A6NK36|Q16852|Q1HEC1|Q6KE87|Q6KE89|Q6TY48",368
"ENSG00000240303","ACAD11","Q709F0|Q08AF0|Q658N9|Q658Y2|Q6ZND2|Q8WUT6|Q9H9R3",9
```

b) a json file [OT1906_target_list.json.zip](https://github.com/opentargets/platform/files/3427997/OT1906_target_list.json.zip)

`cat 19.06_search-data.json | jq -r '. | select(.type=="target") | {"ensembl_id": .id, "hgnc_approved_symbol": .approved_symbol, "uniprot_accessions": .uniprot_accessions, "number_of_associations": .association_counts.total}' > OT1906_target_list.json`
```
{
  "ensembl_id": "ENSG00000205002",
  "hgnc_approved_symbol": "AARD",
  "uniprot_accessions": [
    "Q4LEZ3",
    "A5PKU8"
  ],
  "number_of_associations": 56
}
```
===
For 12,422 **diseases** in the OT19.06 release, I have used `jq` to extract the `efo_id`, `full_name` and `total_association_count` into
a) a csv file [OT1906_disease_list.csv.zip](https://github.com/opentargets/platform/files/3428001/OT1906_disease_list.csv.zip)

`cat 19.06_search-data.json | jq -r '. | select(.type=="disease") | [.id, .full_name, .association_counts.total] | @csv' > OT1906_disease_list.csv`
```
"Orphanet_93335","Postaxial polydactyly type B",36
"Orphanet_93336","Polydactyly of a triphalangeal thumb",12
"Orphanet_262905","Partial trisomy of the long arm of chromosome 9",0
"EFO_0000474","epilepsy",2542
"EFO_1001970","squamous papilloma",37
"Orphanet_79443","Pseudohypoparathyroidism type 1A",130
"Orphanet_79444","Pseudohypoparathyroidism type 1C",118
"EFO_1001208","tarsal tunnel syndrome",4
"EFO_0007126","Acanthamoeba keratitis",16
"EFO_0007125","lachrymal gland lesion",5
```

b) a json file [OT1906_disease_list.json.zip](https://github.com/opentargets/platform/files/3428002/OT1906_disease_list.json.zip)

`cat 19.06_search-data.json | jq -c '. | select(.type=="disease") | {"efo_id": .id, "disease_full_name": .full_name, "number_of_associations": .association_counts.total}' > OT1906_disease_list.json`
```
{
  "efo_id": "EFO_0007125",
  "disease_full_name": "lachrymal gland lesion",
  "number_of_associations": 5
}
```

**Comment by ElaineMcA** [comment]
Links distributed to data providers on 27-Jul to enable August data submissions for Sep release.

Intention is to automate this as an output per release moving forward.

**Comment by cmalangone** [comment]
For release 19.09 we created manually the dumps

cat 19.09_search-data.json | jq -r '._source | select(.type=="target") | [.id, .approved_symbol, [.uniprot_accessions | join("|")][], .association_counts.total] | @csv' > 19.09_target_list.csv
cat 19.09_search-data.json | jq -r '._source | select(.type=="target") | {"ensembl_id": .id, "hgnc_approved_symbol": .approved_symbol, "uniprot_accessions": .uniprot_accessions, "number_of_associations": .association_counts.total}' > 19.09_target_list.json

cat 19.09_search-data.json | jq -r '._source | select(.type=="disease") | [.id, .full_name, .association_counts.total] | @csv' > 19.09__disease_list.csv

cat 19.09_search-data.json | jq -c '._source | select(.type=="disease") | {"efo_id": .id, "disease_full_name": .full_name, "number_of_associations": .association_counts.total}' > 19.09_disease_list.json

**Comment by mkarmona** [comment]
@cmalangone , dumps have to be produced with `--sourceOnly` flag activated. We can start having dumps for

- genes
- efos
- expression
- evidences
- drugs

**Comment by LucaFumis** [comment]
For 19.09 the platform downloads page now includes:
```
  Association objects (2019-09, 271MB)
  Evidence objects (2019-09, 2.76GB)
  Target list: CSV (2019-09, 898KB), JSON (2019-09, 1MB)
  Disease list: CSV (2019-09, 212KB), CSV (2019-09, 252KB)
```
So done from a front end perspective.

**Comment by AsierGonzalez** [comment]
@LucaFumis, I believe that for Diseases the second CSV should be JSON instead, no?

Disease list: CSV (2019-09, 212KB), ~~CSV~~ JSON (2019-09, 252KB)

**Comment by LucaFumis** [comment]
Thank you @AsierGonzalez - how did I miss it??
I'll fix it in a mini release

**Comment by cmalangone** [comment]
This issue has to be reopen due the fact that everything is still done manually.
BE and FE have to find a long term solution.

**Comment by cmalangone** [comment]
**For 19.11 release:**
```
elasticdump --input=http://localhost:9200/19.11_search-data --output=19.11_search-data.json --type=data --sourceOnly

cat 19.11_search-data.json | jq -r 'select(.type=="target") | [.id, .approved_symbol, [.uniprot_accessions | join("|")][], .association_counts.total] | @csv' > 19.11_target_list.csv
cat 19.11_search-data.json | jq -r 'select(.type=="target") | {"ensembl_id": .id, "hgnc_approved_symbol": .approved_symbol, "uniprot_accessions": .uniprot_accessions, "number_of_associations": .association_counts.total}' > 19.11_target_list.json

cat 19.11_search-data.json | jq -r 'select(.type=="disease") | [.id, .full_name, .association_counts.total] | @csv' > 19.11_disease_list.csv

cat 19.11_search-data.json | jq -c 'select(.type=="disease") | {"efo_id": .id, "disease_full_name": .full_name, "number_of_associations": .association_counts.total}' > 19.11_disease_list.json


gzip -c 19.11_target_list.json > 19.11_target_list.json.gz
gzip -c 19.11_target_list.csv > 19.11_target_list.csv.gz
gzip -c 19.11_disease_list.csv > 19.11_disease_list.csv.gz
gzip -c 19.11_disease_list.json > 19.11_disease_list.json.gz
```

**Comment by cmalangone** [comment]
echo '"ensembl_id","hgnc_approved_symbol","uniprot_accessions","number_of_associations"' > 20.02_target_list.csv
cat 20.02.1-search-data.json | jq -r 'select(.type=="target") | [.id, .approved_symbol, [.uniprot_accessions | join("|")][], .association_counts.total] | @csv' >> 20.02_target_list.csv
cat 20.02.1-search-data.json | jq -r 'select(.type=="target") | {"ensembl_id": .id, "hgnc_approved_symbol": .approved_symbol, "uniprot_accessions": .uniprot_accessions, "number_of_associations": .association_counts.total}' > 20.02_target_list.json

echo '"efo_id","disease_full_name","number_of_associations"' > 20.02_disease_list.csv
cat 20.02.1-search-data.json | jq -r 'select(.type=="disease") | [.id, .full_name, .association_counts.total] | @csv' >> 20.02_disease_list.csv
cat 20.02.1-search-data.json | jq -c 'select(.type=="disease") | {"efo_id": .id, "disease_full_name": .full_name, "number_of_associations": .association_counts.total}' > 20.02_disease_list.json
