### ISSUE TITLE
Make threshold and buckets_number configurable in handle_pairs

### ISSUE THREAD

**Issue by hammer** [opentargets/platform#658]
In https://github.com/opentargets/data_pipeline/blob/master/mrtarget/modules/DataDrivenRelation.py#L460 there are two calls to [`handle_pairs`](https://github.com/opentargets/data_pipeline/blob/master/mrtarget/modules/DataDrivenRelation.py#L320) with `threshold` set to `0.19` and `buckets_number` set to `1024`. Given the amount of configuration variables already in use, it might be best to pull these values out as well.

It would also be nice to use more specific names for `threshold`-related variables, given the multiple meanings for that term in this file.

**Comment by cmalangone** [comment]
DDR is not implemented in the new pipeline.
Data pipeline will be replace by the new ETL.
