### ISSUE TITLE
drug_data should depend on base_gene, efo

### ISSUE THREAD

**Issue by hammer** [opentargets/platform#659]
`DrugProcess` takes `es_config.gen.name` and `es_config.efo.name` in its constructor and subsequently queries these indexes in `process_all`. However, the [`drug_data` target](https://github.com/opentargets/data_pipeline/blob/master/Makefile#L119) does not depend on the `base_gene` or `efo` targets. It probably should.

**Comment by afaulconbridge** [comment]
Thank you for this. We've already fixed it as part ofhttps://github.com/opentargets/data_pipeline/pull/522 but you are right and it would have been better to have done it as a separate PR. Therefore I'm going to close this issue as fixed.
