### ISSUE TITLE
Consider moving all direct file downloads to platform-input-support

### ISSUE THREAD

**Issue by hammer** [opentargets/platform#660]
I think it's good practice to separate assembling input data (i.e. `platform-input-support`) from the transformation of that data (i.e. `data_pipeline`). To complete the separation, it would be nice to move all direct file downloads from non-Open Targets-managed Google Storage buckets out of `mrtarget.data.yml` and into `platform-input-support/config.yml`. This way we can put download dates into the filenames of all files used by the pipeline for improved reproducibility.

In [`mrtarget.data.19.06.yml`](https://storage.googleapis.com/open-targets-data-releases/19.06/input/mrtarget.data.19.06.yml), here are the direct downloads that I see:
```
schema: https://raw.githubusercontent.com/opentargets/json_schema/1.6.0/opentargets.json
ontology-eco: https://raw.githubusercontent.com/evidenceontology/evidenceontology/v2018-11-10/eco.owl
ontology-so: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/v3.1/releases/so-xp.owl/so.owl
ontology-efo: https://raw.githubusercontent.com/EBISPOT/efo/v2019-03-18/efo_inferred.owl
ontology-hpo: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2018-10-09/hp.owl
ontology-mp: http://www.informatics.jax.org/downloads/reports/mp.owl
```

I recognize that most of these URLs have version strings in them which means the resource they point to likely will not change, so I don't think this issue is urgent. It's just good hygiene.

We could also simplify `mrtarget.data.yml` configuration by pulling the Google Storage prefix URL out of all of the URL strings into a variable...

**Comment by cmalangone** [comment]
Platform-input-support downloads the resource above and upload the in a gooogle bucket.
