### ISSUE TITLE
Dependency diagram of ES indexes

### ISSUE THREAD

**Issue by hammer** [opentargets/platform#661]
I've been coming up to speed on the Open Targets Platform data pipeline and made a [diagram](https://github.com/hammer/ot-notes/blob/master/Open%20Targets%20Platform%20Data%20Pipeline.pdf) that organizes the various search indexes by their dependencies and includes links to the code and configuration that populates each index. For the links to work you need to download the PDF, since GitHub renders the PDF as an image.

I'd be happy to improve and maintain this document if y'all wanted to include it in the documentation. Otherwise just figured I'd share in case it helps others come up to speed faster.

**Comment by deniseOme** [comment]
@hammer, this looks great. Very much appreciated. Would you be keen to contribute with a post to our [blog](http://blog.opentargets.org/)?

This is what [Glenn Proctor](http://blog.opentargets.org/author/glennproctor/) @Docproc has done for a Genomics England use case.

It would be great to have a contribution from you and use your diagram, for example.

**Comment by deniseOme** [comment]
@hammer, would it be ok to re-use your diagram in our [data pipeline](https://docs.targetvalidation.org/technical-pipeline/infrastructure#data-pipeline) help documentation?

**Comment by hammer** [comment]
Sure, want me to update it for the 19.09 release?

**Comment by deniseOme** [comment]
@hammer, that'd be great. Thanks.
