### ISSUE TITLE
Include adverse events detail view

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#670]
Check with data team on the best way of representing the upcoming data.

Related to #74 and #564

**Comment by andrewhercules** [comment]
For the drug summary page, I have created an initial mockup of what the adverse event data table could look like.

![adverse-events-final](https://user-images.githubusercontent.com/7490258/61942116-adf24d00-af90-11e9-82e2-43319b6312c1.png)

At the top of the data table, I have created a summary description:

``A list of post-marketing adverse events submitted by healthcare professionals to the FDA Adverse Event Reporting System (FAERS). The list only contains adverse events with a log likelihood ratio above a critical value (CV) threshold - see our adverse event report documentation page for more information. ``

Within the summary description, I recommend that we have a tooltip with the following description for FAERS:

``The FDA Adverse Event Reporting System (FAERS) is a database that contains information on post-marketing adverse event and medication error reports submitted to the FDA. Adverse events and medication errors are coded to terms in the Medical Dictionary for Regulatory Activities (MedDRA) terminology.``

The summary description will also have a link to our documentation page where we can provide links to the LLR paper and how we calculated the critical value.

@d0choa, @EPetsalaki, and @MichaelaEBI, what do you think?

**Comment by LucaFumis** [comment]
Fix, pending PR merge

**Comment by LucaFumis** [comment]
Closing issue as work has been completed and merged.
