### ISSUE TITLE
Include text mining to evidence page

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#672]
It will be similar to the LINK detail view but we small differences.

**Comment by LucaFumis** [comment]
All development work done, pending merging of PRs.

**Comment by LucaFumis** [comment]
Looking at the standard example "Evidence for ESR1 in breast carcinoma" the textmining relevance field (single barchart) appears incorrectly scaled - will need to remove the "adjustment" we apply.

**Comment by d0choa** [comment]
@AsierGonzalez could you check for us what's the maximum value that a give literature evidence might have?

We know it's somewhere above 100 but we don't know what's the maximum empirical value.
