### ISSUE TITLE
Drug index Part II: investigate feasibility of server-side clinical trial aggregation

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#680]
Using existing data, is it possible to craft Elasticsearch queries that return evidence aggregated by:

disease
drug
phase
status
target

So that each result is a unique combination of the above.

**Comment by afaulconbridge** [comment]
See branch  af-es-mapping-clinical-trials in data_pipeline and rest_api for proptotype

**Comment by ElaineMcA** [comment]
Prototype performance will be assessed by w/e 19-Jul-2019 so that next steps may be agreed.

**Comment by ElaineMcA** [comment]
Performance testing ongoing this week on prototype now that Travis issues experienced resolved.

**Comment by afaulconbridge** [comment]
It is possible, performance is around 21 seconds for fixing disease to cancer, 24s for neoplasm, 1.2s for fixing EGFR. This is below the 1 minute threshold discussed previously. It won't "feel fast" but can be mitigated in the front end. If we significantly update the backend data model (e.g. a graph database) we should revisit this to improve this situation. For now, closing this ticket.
