### ISSUE TITLE
EPMC: Duplicated evidence strings

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#683]
Reviewing the 19.06 epmc data using the `unique_association_fields` yielded the following insights:

- The submitted file contains 7,065,740 rows. 
- The following combinations of UniProt ID and abstract ID are all repeated 3 times and are missing a disease ID:
```
http://identifiers.org/uniprot/O43612,http://europepmc.org/abstract/MED/29445282, 
http://identifiers.org/uniprot/P01286,http://europepmc.org/abstract/MED/21850272, 
http://identifiers.org/uniprot/Q5VZF2,http://europepmc.org/abstract/MED/29445282, 
http://identifiers.org/uniprot/Q8TD46,http://europepmc.org/abstract/MED/23730297, 
```
- [ ] epmc to investigate these 3x 4 evidence strings

- 733,592 JSON evidence strings are repeated twice and the UniProt, abstract and disease IDs for these can be found [here](https://drive.google.com/open?id=1XTX7qP3NzMYRuLDFWeHI00U6576sKOyU). These replicates are most likely entries for papers that have been scored in the abstract and the full-text pipeline.

- [x] epmc to confirm that these replicates are indeed due to abstract & full text pipeline
- [x] ot to define what we want to do with these replicates

**Comment by AsierGonzalez** [comment]
EuropePMC will make changes to their pipelines to exclude evidence from abtracts if there is full-text evidence for the same publication

**Comment by MichaelaEBI** [comment]
These issues will be covered in the context of the new OTAR2056 Literature project.

**Comment by hammer** [comment]
@MichaelaEBI where can we learn more about OTAR2056?

**Comment by d0choa** [comment]
Unfortunately, the research projects funded by Open Targets (OTAR projects) can only be shared within the partnership. The final results will all be made publicly available, but the proposal and the intermediate results are only accessible to the partners. As @MichaelaEBI said, this project is still in its infancy and it's the next iteration of an already published OTAR project ([ref](https://www.ncbi.nlm.nih.gov/pubmed/28587637))

**Comment by hammer** [comment]
Ah, that's unfortunate. We have quite a bit of experience with text mining (cf. https://github.com/hammerlab/t-cell-relation-extraction) and had hoped to improve the literature evidence source, having studied the existing implementation that you link and finding many areas for potential improvement. Perhaps y'all could consider a more open model for development of large features in the near future? Alternatively, how can we become a partner so that we can have access to these planning and implementation discussions?
