### ISSUE TITLE
Drug Index : missing URLs for Wikipedia, ISBN, InterPro

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#687]
References to Wikipedia, ISBN, InterPro do not have URL links. These needs to be added to the drug phase of `data_pipeline`.

**Comment by afaulconbridge** [comment]
ISBN can't be turned into URLs sensibly

**Comment by andrewhercules** [comment]
Ticket closed as issue resolved. The `/private/drug endpoint` response returns full URLs for references found in the `mechanism_of_action` section - see below for an example:
 
![Screenshot 2019-11-29 at 14 49 17](https://user-images.githubusercontent.com/7490258/69876420-70435f00-12b7-11ea-9715-1b4bc64c86a0.png)
