### ISSUE TITLE
Drug mechanisms of action: IDs or URLs

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#690]
The `mechanisms_of_action` field for this drug has a confusing mix of `ids` and `urls` fields. Also, the source name `Other` is a bit unusual.

```
"references": [
    {
        "source": "Other",
        "ids": [
            "http://www.medicines.org.uk/emc/medicine/22763"
        ]
    },
    {
        "source": "PubMed",
        "ids": [
            "20481644"
        ],
        "urls": [
            "https://europepmc.org/search?query=EXT_ID%3A20481644"
        ]
    }
]
```

Example API response: https://api.opentargets.io/v3/platform/private/drug/CHEMBL2111100

**Comment by afaulconbridge** [comment]
The "Other" comes from chembl so there's not much we can do about it. Do you think it should be omitted entirely in such cases? Or be the domain name (e.g. "source":"www.medicines.org.uk") ?

Also, I know having both "ids" and "urls" could be confusing, but I'm not aware of any better way of doing it. Do you have a specific improvement in mind? The general constraints we've identified are:
- some sources (e.g. PubMed) support multiple IDs in a single link (up to a limit on the URL length) but most others do not
- as few links as possible for better user experience
- minimize the number of components that need changing to add a new source (more maintainable)

**Comment by d0choa** [comment]
I'll close this ticket as it doesn't have any particular task attached.

I think the discussion is quite relevant. We will aim to standardise the way references (and other fields) are reported across data providers. By being more consistent, we will more easily track data fields across the data pipeline, APIs and FE. It won't happen overnight, but it seems the right thing to do.
