### ISSUE TITLE
Streamline association step

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#692]
Currently, the association step is split into two parts, one that extracts evidence from elasticsearch and one that calculates score. However, this means it has to serialise and deserialise all the evidence in between. They could be combined into a single pipeline stage, which should improve performance and make the code more readable. At the same time, we could try to identify any improvements that can be made to the elasticsearch query e.g. sort by descending score and limit to 100 records since the scorer applies that cutoff too.

**Comment by d0choa** [comment]
Most of this task is been addressed as part of the pipeline refactoring. Closing for simplicity
