### ISSUE TITLE
Batch Search - Therapeutic Areas missing in search results

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#694]
Hi,

Just noticed that there is a IE11 bug on the batch search.
The Therapeutic areas: (sorted by relevance to your list) chips are not appearing on our version.

**Comment by andrewhercules** [comment]
@gkos-bio, which version of the Platform are you using? There was a known bug that @LucaFumis fixed in a mini-release (3.13.3) - see issue #645 and the [change log](https://docs.targetvalidation.org/technical-pipeline/change-log) for more information.

**Comment by gkos-bio** [comment]
We released on the 4th of July and this was fixed on the 8th of July. That's explain why we have this bug.
We will have to patch the code.
