### ISSUE TITLE
Replace icons for drug and disease profile pages

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#697]
We will need an icon consistent with the DNA helix shown in the target profile page that could be used for drug summary page and disease profile page.

**Comment by andrewhercules** [comment]
![all-icons](https://user-images.githubusercontent.com/7490258/62203135-803b4880-b382-11e9-9999-3b19ec39e35c.png)

New icons have been created using [the Medicine (Line) collection](https://thenounproject.com/mockturtle/collection/medicine-line/) to ensure consistency in design and icon weight.

* [Target icon](https://drive.google.com/open?id=14eTm8JUhv1xAVR1ZzHau9T-lQ5SBo8Wa)
* [Disease icon](https://drive.google.com/open?id=14lDLqxRhXjHcoUutjEc4lCEM9_FiK_7x)
* [Drug icon](https://drive.google.com/open?id=1jZMX78kRiH4VLILIbI9xULfS_9eJp9Va)
* [Associations icon](https://drive.google.com/open?id=1TVvrE0PPWhdeegfUWQVuBOti-DvxdCqU)

**Comment by mirandaio** [comment]
@d0choa @andrewhercules The icons for the target, drug, and disease page have been update. You can check them out here: https://platform-app.netlify.com

**Comment by andrewhercules** [comment]
Based on yesterday's front-end meeting, I have updated the disease icon to a stethoscope to account for the phenotypes and measurements we include in the Platform. 

* [New disease icon](https://drive.google.com/open?id=14lDLqxRhXjHcoUutjEc4lCEM9_FiK_7x)

**Comment by mirandaio** [comment]
Disease icon has been updated.
