### ISSUE TITLE
Drug Index: Redesign Drugs tables

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#7]
@elipapa commented on [Thu Mar 09 2017](https://github.com/opentargets/roadmap/issues/76)

@nikiforosk commented on [Thu Jan 19 2017](https://github.com/opentargets/ux/issues/2)

These are the Drugs tables in 

**Target Profile > Drugs**:
![profile-egfr-drugs](https://cloud.githubusercontent.com/assets/20280139/21987972/7638cdda-dbfd-11e6-90ef-4cd366aa1218.png)

**Evidence page > Drugs**:
![evidence-efgr-adenocarcinoma-drugs](https://cloud.githubusercontent.com/assets/20280139/21987994/890767c8-dbfd-11e6-917c-7b9055f2f543.png)

There seems to be a lot of repetitive information, which is presumably generic i.e. **about the drug** itself.

Then there is information about the **clinical trial**, which is presumably different for each clinical trial.

Could we redesign this table so that we present:
1. General info about each drug (maybe as a drug card)
2. Info about each clinical trial (maybe as a table)

This could look similar to the section of TAs and Diseases that Miguel made for the Summary page of batch search:
![disease-table-tas-screen shot 2017-01-17 at 09 25 55](https://cloud.githubusercontent.com/assets/20280139/22109419/946c3f86-de4f-11e6-9c4b-8a68d79496d3.png)

---

@ckongEbi commented on [Fri Mar 10 2017](https://github.com/opentargets/roadmap/issues/76#issuecomment-285628513)

@elipapa there is a user I spoke to during omics training that raise the same evidence duplication issue on the drug evidence table.  

They would like to have the same evidence in different clinical trials to be combine into a single row, then have a list of related clinical trials. 

---

@emepyc commented on [Fri Mar 10 2017](https://github.com/opentargets/roadmap/issues/76#issuecomment-285651343)

We also need to (maybe optionally) add the target in another column, because the same table is reused in the evidence page and both profile pages. In the disease profile page we don't have the target information and it may be useful.

---

@deniseOme commented on [Fri Mar 10 2017](https://github.com/opentargets/roadmap/issues/76#issuecomment-285658569)

@emepyc Yes, this was asked at the Target Validation Conference in Heidelberg and I believe we discussed that on slack. For some cases, the target class column would do the job: e.g. CD20 (http://targetvalidation.org/evidence/ENSG00000156738/EFO_0003885?view=sec:known_drugs) but for others the class is more generic (isomerase) and less informative.

---

@deniseOme commented on [Fri Mar 10 2017](https://github.com/opentargets/roadmap/issues/76#issuecomment-285659157)

In the meantime of adding new columns, whenever a user reports this (apparent) row redundancy, we assure them the although the GUI does not show a difference in the columns, the data behind it is indeed different, mainly at the clinical.gov info level (i.e. different studies NCT01212094 versus NCTXXXXXXXX).

**Comment by ElaineMcA** [comment]
Front end meeting 15Aug2018 to discuss.

**Comment by andrewhercules** [comment]
Closing this ticket as it will be resolved as part of #589
