### ISSUE TITLE
Include SMILES, DrugBank ID, and target class data on drug profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#703]
Based on yesterday's front-end meeting, we will add the following data to the drug profile page, which will require adding data to the drug index API response ([example](http://api.opentargets.io/v3/platform/private/drug/CHEMBL122)):

- [x] Canonical SMILES: This will allow the front-end application to render the molecule structure without requiring a separate call to the ChEMBL API. It is available from the ChEMBL /molecule API endpoint in ``molecule_structures.canonical_smiles`` ([example](https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL112.json)) 

- [x] DrugBank ID: This will allow the front-end application to render a link to the DrugBank profile page for a given drug. The data is available via UniChem; however, we cannot use the API response [due to CORS issues](https://github.com/opentargets/platform/issues/564#issuecomment-506400407). There is a data file available for download that can be processed and added to the API response - see #612 for more information. 

- [ ] Target class information: This data would be displayed in a target table and could be part of a broader expansion to include data about protein complexes and known binding subunits.

**Comment by d0choa** [comment]
Activities on this ticket have been completed or re-prioritised
