### ISSUE TITLE
Change GWAS unique_association_fields to reduce duplicates

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#705]
In the 19.06 GWAS file there were 2,030 duplicate evidence strings. The values currently included in the `unique_association_fields` are `confidence_interval`, `gwas_panel_resolution`, `object`, `odd_ratio`, `pubmed_refs`, `pvalue`, `sample_size`, `study_name`, `target` and `variant`.
After talking to the GWAS catalog team the following changes will me made to the `unique_association_fields`:

- [x] Remove numerical values (`confidence_interval`, `gwas_panel_resolution`, `odd_ratio` and `pvalue`) as they add little information or they are not sufficient to distinguish evidences. Note that `odd_ratio` and `confidence_interval` are used by the front-end but do not appear anywhere else in the JSON, so they will need to be relocated. Suggested new location is `.evidence.variant2disease`.

- [x] Add p-value annotation (`pvalue_annotation`) to `unique_association_fields`. Note that it will set an an empty string ("") if null. 

- [x] Assign real GWAS study id to `study_name` as it is currently _otar009_gwas_catalog_ for all the evidence strings.

- [x] Change `object` to `disease_id` for clarity and consistency with evidence from other providers.

After implementing these changes this is what a GWAS evidence string will look like (changes are **highlighted**):

{
  "target": {
    "activity": "http://identifiers.org/cttv.activity/predicted_damaging",
    "id": "http://identifiers.org/ensembl/ENSG00000157168",
    "target_type": "http://identifiers.org/cttv.target/gene_evidence"
  },
  "access_level": "public",
  "sourceID": "gwas_catalog",
  "variant": {
    "type": "snp single",
    "id": "http://identifiers.org/dbsnp/rs10503887"
  },
  "disease": {
    "id": "http://www.ebi.ac.uk/efo/EFO_0004685"
  },
  "unique_association_fields": {
    "pubmed_refs": "http://europepmc.org/abstract/MED/17903296",
    "target": "http://identifiers.org/ensembl/ENSG00000157168",
    **"disease_id":** "http://www.ebi.ac.uk/efo/EFO_0004685",
    "variant": "http://identifiers.org/dbsnp/rs10503887",
    "study_name": **"GCST000101"**,
    **"pvalue_annotation": "(ShaftZ1R)"**
  },
  "evidence": {
    "variant2disease": {
      "gwas_sample_size": 1094,
      "unique_experiment_reference": "http://europepmc.org/abstract/MED/17903296",
      "gwas_panel_resolution": 70897,
      "provenance_type": {
        "literature": {
          "references": [
            {
              "lit_id": "http://europepmc.org/abstract/MED/17903296"
            }
          ]
        },
        "expert": {
          "status": true,
          "statement": "Primary submitter of data"
        },
        "database": {
          "version": "2019-07-12T11:42:54+00:00",
          "id": "GWAS Catalog",
          "dbxref": {
            "version": "2019-07-12T11:42:54+00:00",
            "id": "http://identifiers.org/gwas_catalog"
          }
        }
      },
      "is_associated": true,
      "resource_score": {
        "type": "pvalue",
        "method": {
          "description": "pvalue for the snp to disease association."
        },
        "value": 2e-07
      },
      "evidence_codes": [
        "http://identifiers.org/eco/GWAS",
        "http://purl.obolibrary.org/obo/ECO_0000205"
      ],
      "date_asserted": "2019-07-12T11:42:54+00:00",
      **"confidence_interval": "NR",
      "odd_ratio": ""**
    },
    "gene2variant": {
      "provenance_type": {
        "expert": {
          "status": true,
          "statement": "Primary submitter of data"
        },
        "database": {
          "version": "2019-07-12T11:42:54+00:00",
          "id": "GWAS Catalog",
          "dbxref": {
            "version": "2019-07-12T11:42:54+00:00",
            "id": "http://identifiers.org/gwas_catalog"
          }
        }
      },
      "is_associated": true,
      "date_asserted": "2019-07-12T11:42:54+00:00",
      "evidence_codes": [
        "http://purl.obolibrary.org/obo/ECO_0000205",
        "http://identifiers.org/eco/cttv_mapping_pipeline"
      ],
      "functional_consequence": "http://purl.obolibrary.org/obo/SO_0001627"
    }
  },
  "validated_against_schema_version": "1.6.1",
  "type": "genetic_association",
  "literature": {
    "references": [
      {
        "lit_id": "http://europepmc.org/abstract/MED/17903296"
      }
    ]
  }
}

**Comment by AsierGonzalez** [comment]
Questions for @MichaelaEBI, @mkarmona and @cmalangone:

- Does the new location for `odd_ratio` and `confidence_interval` look good to you?  

- Is it problematic that a value in the `unique_association_fields` (`pvalue_annotation`) can be an empty string? 

- Should all the values in the `unique_association_fields` appear elsewhere in the JSON? In the GWAS file, `pvalue_annotation`, `study_name` and `variant` only appear in the unique fields.

**Comment by hammer** [comment]
Will the scripts that process GWAS Catalog (or Open Targets Genetics) to generate the evidence strings be added to https://github.com/opentargets/evidence_datasource_parsers?

Stated differently, what code is being altered as part of this issue, and is that code public?

**Comment by MichaelaEBI** [comment]
@AsierGonzalez yes, all fields in `unique_association_fields` should be found in the main part of the evidence string. `unique_association_fields` are supposed to be a subset of the fields in the evidence strings that make each evidence string unique. The location of `odds_ratio` and `confidence_interval` in `evidence.variant2disease` makes sense to me. I assume that you now need to also find a home for `pvalue_annotation` in the main part of the evidence string? It could probably go with the other two fields?

@hammer the code that generates the GWAS JSON evidence strings for Open Targets is maintained by the GWAS group since they run this data export pipeline because they know their data and technologies best. The same is true for evidence from COSMIC, UniProt, EVA, EPMC, ChEMBL, reactome and Expression Atlas.

**Comment by hammer** [comment]
@MichaelaEBI is there any chance the code maintained by separate groups will ever be available as open source? GWAS Catalog in particular is a critical evidence source and it would be wonderful if we could understand how the evidence strings are generated from it.

**Comment by iandunham** [comment]
@hammer Have you looked at genetics.opentargets.org? This is eventually where we will be getting the GWAS evidence from (we are working on the scoring at the moment) and this will replace the GWAS catalog feed once we have calibrated it.

**Comment by hammer** [comment]
Yes we are quite familiar with that code as well. We did not see any
linkage between OT P and OT G; that’s one reason why I suggested the third
issue, to build a small link between the projects.

**Comment by d0choa** [comment]
All this work on the GWAS catalog unique associations fields is completed.
