### ISSUE TITLE
Review of COSMIC evidence strings

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#707]
The current work on `unique_association_fields` and the replicated `.literature` in evidence strings led to the current changes to the COSMIC evidence strings for the 19.09 data submission:
1. Remove top level `.literature` section
2. In `unique_association_fields` keys: 
	a. change `gene` -> `target_id`
	b. change `disease_uri` -> `disease_id`
3. In `unique_association_fields` values:
	a. In target_id: instead of gene symbol use (http://identifiers.org/ensembl/+ENSG_gene_id+[identifiers.org])

**Comment by hammer** [comment]
Will the scripts that process COSMIC to generate the evidence strings be added to https://github.com/opentargets/evidence_datasource_parsers?

**Comment by MichaelaEBI** [comment]
Just for completeness: @hammer see responses to this ticket: #705

**Comment by MichaelaEBI** [comment]
`.unique_association_fields.target_id` is currently (19.09 OT release) provided as `http://identifiers.org/ensembl/ENSG00000148584[identifiers.org]`. Contacted COSMIC to remove the `[identifiers.org]`.
