### ISSUE TITLE
Review of reactome evidence strings

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#708]
The current work on unique_association_fields and the replicated .literature in evidence strings led us to suggest the current changes to the COSMIC evidence strings for the 19.09 data submission:

- [x] Removal of duplicated `.literature`
- [x] Rename `biological_subjects` to `target_id` 
- [x] Rename `disease` to `disease_id`
- [x] Remove `biological_objects`

Further work will be needed to look into the use of `reaction_id` versus `pathway_id` (see ticket xxx)

**Comment by d0choa** [comment]
The actions for this ticket are completed. Future exploration on reaction_id versus pathway_id will be address in a different ticket
