### ISSUE TITLE
Review of uniprot evidence strings

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#709]
The review of evidence strings from different providers led us to suggest the following changes to the UniProt evidence strings:

- [ ] Remove replicated `.literature` section in `somatic_mutation` and `genetic_literature` evidence strings. The literature references given under `.provenance_type.literature.references` are repeated at `.literature.references` for 284+4627=4911 evidence strings

- [ ] `uniprot_release` can be removed from `unique_association_fields` since it is also provided at `.evidence.provenance_type.database` and has the same value for all evidence strings.

- [ ] `variant_id` seems to only be provided in `unique_association_fields`.

- [ ] `disease_acronym` is only provided in `unique_association_fields` and the full disease name is provided at `disease.name`. For completeness sake it would be great if `disease_acronym` could be added as `.disease.acronym` in case Open Targets wants to use it in the front end and to be consistent in that all fields in `unique_association_fields` can also be found in the main evidence string.

- [ ] Remove links to association_score_methods (GitHub ticket #374) - only `evidence.resource_score.type` and `evidence.resource_score.value` are required by the JSON schema, `evidence.resource_score.method` does not have to be provided:
```
    "evidence": {
      "resource_score": {
        "type": "probability",
        "value": 1,
        "method": {
          "description": "Curator inference (either 1.0 or 0.5)",
          "url": "https://github.com/CTTV/association_score_methods/blob/master/CTTV011_UniProt/description.md"
        }
      },
```
The information provided at `https://github.com/opentargets/association_score_methods/blob/master/CTTV011_UniProt/description.md` is now also contained in the [Open Targets documentation](https://docs.targetvalidation.org/getting-started/scoring).

**Comment by andrewhercules** [comment]
Re-assigning to 20.11 as UniProt evidence assessment is ongoing as noted in [our release intentions document](https://docs.google.com/document/d/1DcQ1CVg0jgQpJlKSvVCQkcYznwaAKiUcY0khToA0Ubg/edit#)

**Comment by d0choa** [comment]
Work is dependent on #1141 and mostly deprecated by the new schema work.
The key question remains if we will rescue uniprot as datasource
