### ISSUE TITLE
Data team to assist front-end to not use unique_association_fields in web app

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#710]
`unique_association_fields` are used in the Open Targets `data_pipeline` to generate a unique hash for each evidence string and should be a subset of the fields provided in the main evidence string, including `target_id` and `disease_id`. The purpose of this data team ticket is to enable the front end team to stop using these fields by providing the necessary data in separate fields in the main part of the evidence strings.

`unique_association_fields` are used in three places in the web app:

- [x] **1. COSMIC data**: `.unique_association_fields.mutation_type` is used by the front end but is also provided in the main part of the evidence string as `evidence.known_mutations.preferred_name`. We are not planning to remove or change this field, but it would probably be good if the value in the main part of the evidence string is used.
- [ ] **2. SysBio data**: `.unique_association_fields.gene_set` is used in front end. This field is not available in the main part of the evidence string. We will add this field to the main evidence string and update front end when that has been done.
**3. Common disease table** - a) GWAS and b) PheWAS data: 
- [x] **a) GWAS:** Used by front end are `.unique_association_fields.odd_ratio` & `.unique_association_fields.confidence_interval` - we are currently looking into removing these two fields from `unique_association_fields` --> neither field is provided in the main part of the JSON string. We will get GWAS to change that when we ask them to remove these fields and we will update front end. 
- [x] **b) PheWAS** `.unique_association_fields.odds_ratio` is used by the front end and is not provided in the main part of the json strings. This will be changed by the data team and front end will be notified since we are planning to remove this field from unique_association_fields.

**Comment by AsierGonzalez** [comment]
GWAS evidence is not used directly since 20.02, when OT Genetics was integrated so 3.a) does no longer apply

**Comment by AsierGonzalez** [comment]
The odds ratio in no longer part of the unique association fields in PheWAS, it has been moved to `evidence.variant2disease`.

**Comment by AsierGonzalez** [comment]
Since 20.02 there is no `mutation_type` in the COSMIC unique association fields given that the now receive one evidence string for each target-disease pair, comprared to the target-disease-mutation_type leve evidence we had before.

**Comment by AsierGonzalez** [comment]
Fixing SysBio will require updating the [parser](https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/SystemsBiology.py) which currently uses the ot `models` module, which is why `gene_set` could not be added anywhere else.

Addressing this is not priority for now, closing the issue
