### ISSUE TITLE
How to use EPMC evidence for mouse genes in the Open Targets platform

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#711]
EPMC already provides >750,000 evidence strings for ~10,000 mouse genes. At the moment these mouse gene-disease associations are not used at all because OT only validates human gene and protein identifiers. This ticket is meant to start work on characterising this data and to start a discussion about how this data could be used in the Open Targets Platform.

**Comment by AsierGonzalez** [comment]
EuropePMC will add an species tag to the evidence strings so that OT can explore the associations found in mice.

**Comment by d0choa** [comment]
This item is in the agenda of the OTAR2-056. We'll keep an eye on their progress. Closing
