### ISSUE TITLE
Link to combined TEPs not working

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#712]
The [link to the TEP](https://www.thesgc.org/tep/GALK1) on the [GALK1 target profile page](https://www.targetvalidation.org/target/ENSG00000108479) does not work. Currently the links to the TEPs are built on the front-end using [teps-service.js](https://github.com/opentargets/webapp/blob/master/app/src/services/teps-service.js), which just uses the gene symbols. This link does not work because the TEP is designed for two targets (GALT and GALK1) instead of a single one and the url is a combination of both names: https://www.thesgc.org/tep/galt-galk1.
Interestingly, the [link](https://www.thesgc.org/tep/galt) from the [GALT target profile](https://www.targetvalidation.org/target/ENSG00000213930) works because the SGC have a redirect for https://www.thesgc.org/tep/galt.
The problem will be more severe for a new TEP that targets KALRN and RAC1 given that the url is https://www.thesgc.org/tep/kalrnrac1 and neither https://www.thesgc.org/tep/kalrn nor https://www.thesgc.org/tep/rac1 works.
One solution for this issue is to explicitly add the urls to teps-service.js. In the interim, @MichaelaEBI has contacted the SGC to see if they could create redirects for the urls that don't work.

**Comment by AsierGonzalez** [comment]
The links that should be used for each TEP are the following:

| Target  | URL | Same as generated by FE?
| ------------- | ------------- | ------------- |
| **KALRN** | https://www.thesgc.org/tep/kalrnrac1 | **No** |
| **RAC1** | https://www.thesgc.org/tep/kalrnrac1 | **No** |
| ALAS2 | https://www.thesgc.org/tep/alas2 | Yes |
| KEAP1 | https://www.thesgc.org/tep/keap1 | Yes |
| KLHL20 | https://www.thesgc.org/tep/klhl20 | Yes |
| ANO10 | https://www.thesgc.org/tep/ano10 | Yes |
| **GALT** | https://www.thesgc.org/tep/galt-galk1 | **No, but** https://www.thesgc.org/tep/galt **works** |
| **GALK1** | https://www.thesgc.org/tep/galt-galk1 | **No** |
| MLLT1 | https://www.thesgc.org/tep/mllt1 | Yes |
| HCN4 | https://www.thesgc.org/tep/hcn4 | Yes |
| NUDT7 | https://www.thesgc.org/tep/nudt7 | Yes |
| PARP14 | https://www.thesgc.org/tep/parp14 | Yes |
| RIPK2 | https://www.thesgc.org/tep/ripk2 | Yes |
| HAO1 | https://www.thesgc.org/tep/hao1 | Yes |
| FAM83B | https://www.thesgc.org/tep/fam83b | Yes |
| LIMK1 | https://www.thesgc.org/tep/limk1 | Yes |
| DCLRE1A | https://www.thesgc.org/tep/dclre1a | Yes |
| DPAGT1 | https://www.thesgc.org/tep/dpagt1 | Yes |
| AASS | https://www.thesgc.org/tep/aass | Yes |
| WNK3 | https://www.thesgc.org/tep/wnk3 | Yes |
| HDAC6 | https://www.thesgc.org/tep/hdac6 | Yes |
| KDM3B | https://www.thesgc.org/tep/kdm3b | Yes |
| KDM4D | https://www.thesgc.org/tep/kdm4d | Yes |
| PHIP | https://www.thesgc.org/tep/phip | Yes |
| RECQL5 | https://www.thesgc.org/tep/recql5 | Yes |
| SETDB1 | https://www.thesgc.org/tep/setdb1 | Yes |
| CDK12 | https://www.thesgc.org/tep/cdk12 | Yes |

**Comment by LucaFumis** [comment]
Thank you @AsierGonzalez. I'll add those links in - pretty straightforward.

**Comment by MichaelaEBI** [comment]
SGC has been contacted to see whether they can implement consistent redirection from links with single gene symbols for the two TEPs with 2 proteins.

**Comment by andrewhercules** [comment]
Thanks @MichaelaEBI! Beyond the possible redirection for TEPs with 2 proteins, we also need to account for the ANO10 issue - the actual link is https://www.thesgc.org/tep/tmem16k as the link to https://www.thesgc.org/tep/ano10 does not work.

Thus, to ensure the appropriate link is available to our users, I have added all links to the TEPs file and will update #458 with a link for @LucaFumis to use in the 19.09 release.

**Comment by AsierGonzalez** [comment]
Well spotted @andrewhercules, I missed the issue with ANO10!

**Comment by AsierGonzalez** [comment]
FYI, SGC have set up redirects so that the original issue here is solved:

- https://www.thesgc.org/tep/galt, https://www.thesgc.org/tep/galk1 and https://www.thesgc.org/tep/galt-galk1 redirect to https://www.thesgc.org/tep/galtgalk1

- https://www.thesgc.org/tep/kalrn and https://www.thesgc.org/tep/rac1 redirect to https://www.thesgc.org/tep/kalrnrac1

**Comment by andrewhercules** [comment]
That's great - thanks for following up @AsierGonzalez! 👍 

For the 19.09 release, I have created a new teps-service.js file for @LucaFumis to use and in the file, we also store the link for each TEP. 

```
ENSG00000094631: {
  id: 'ENSG00000094631',
  symbol: 'HDAC6',
  link: 'https://www.thesgc.org/tep/hdac6'
}
```

**Comment by AsierGonzalez** [comment]
No problem, credit to @MichaelaEBI, who had the idea an contacted SGC. I just convey the message :)
