### ISSUE TITLE
evidence_datasource_parsers: Update IntOgen Module

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#715]
**Summary of changes:**
- Update credits and contact info
- Tidy up the code
- Update `Mengioma` disease ID
- Simplify `unique_association_fields` to `target_id` and `disease_id` because these two are enough uniquely identify each IntOgen evidence string
- Add `source_name` to `.disease`

The Pull Request can be found [here](https://github.com/opentargets/evidence_datasource_parsers/pull/30)

**Comment by andrewhercules** [comment]
Closing this ticket as the [pull request](https://github.com/opentargets/evidence_datasource_parsers/pull/30) has been merged and closed
