### ISSUE TITLE
rest_api docs reference removed pipeline setting

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#718]
The [docs](https://github.com/opentargets/rest_api/blame/19.06.4/README.md#L68 ) on running the **rest_api** service with Docker say that the ‘data version’ setting must match the ‘prefix’ option passed to the data pipeline. That prefix option was removed in release 19.06.

The pipeline now takes individual index names from its Elasticsearch configuration file, which [its docs](https://github.com/opentargets/data_pipeline/blob/19.06.4/README.md#elasticsearch-1) say shouldn't generally need to change. The **rest_api** component requires these names to have a particular format, for which leaving the file untouched should indeed work--the prefix will be `master` for all indices.

Running the pipeline in combination with the public data snapshot, however, requires replacing the first word of every index name by the snapshot number. This occurs when using `--val --val-append-data` or custom `--gen` annotation plugins to integrate internal data with public data. It can only be inferred by reading the code.

What workflow should the documentation suggest to make the setup runnable?

**Comment by d0choa** [comment]
No work is expected in the previous API (REST). All future developments will come with the soon to be released API
