### ISSUE TITLE
evidence_datasource_parsers: Update CRISPR module

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#719]
**Summary of changes:**
- [x] Code formatting
- [x] `unique_assocation_fields`: `gene_name` --> `target_id` & take `disease_id` and `target_id` from evidence string
- [x] Add symbol mapping for 9 genes that do not have an Ensembl ID in the original data file
- [x] Add `unique_association_fields.gene_set` to main part of evidence string - requires JSON schema modification
- [x] Add pmid to data file
- [ ] Remove GeneParser from this module since Ensembl IDs are provided

**Comment by AsierGonzalez** [comment]
The removal of the GeneParser dependency has been completed by @DSuveges during the update of the parser to the new schema (#1281), see opentargets/evidence_datasource_parsers#65.
