### ISSUE TITLE
OTAR042 -Tractability: Co-ordinate outreach activities

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#72]
- [ ] Add documentation to gitbook

- [ ] Amend FAQ section

- [ ] Create youtube video

- [ ] Blog post

- [ ] Twitter/ facebook plans

- [ ] Co-ordination with ChEMBL?

- [ ] Update training materials

**Comment by andrewhercules** [comment]
@deniseOme, do you want me to coordinate with Chris and interview him for a Q&A blog post?

**Comment by andrewhercules** [comment]
For the upcoming 18.12 release, we'll be adding 3 new features related to tractability:

1.  Adding the [on-hover flower in the Prioritisation view](https://drive.google.com/open?id=1tsoLQA48uOgiopTKXIWD7cO_8nxrwpoY) 

2.  Adding the [tractability facet](https://drive.google.com/open?id=1AQS3TcgX0zh5NEbMouD-YbrNRPX6P9bR) to both the Prioritisation and Association views

3.  Adding summary tractability data to the [batch search page](https://drive.google.com/open?id=1gpI-W4dkm8E2naSLv9i5GvJEX6vChkeN)

For more information, please see issue #264
