### ISSUE TITLE
PMID for CRISPR paper (Project Score)

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#720]
From 19.09, the epmc link for the CRISPR paper is provided in the evidence strings at `.evidence.resources_score.method.reference` and the front end can now use this pmid instead of hard-coding it in the web app.

**Comment by LucaFumis** [comment]
For an example see: https://www.targetvalidation.org/evidence/ENSG00000109971/EFO_0000174
Code to update: https://github.com/opentargets/webapp/blob/master/app/src/components/crispr-table/crispr-table-directive.js#L107-L109
