### ISSUE TITLE
new column for drug info table?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#722]
User has contacted @iandunham suggesting "that the clinical trial data available from the drugs tab be annotated with a column with values including "Has no results", "Success" , "Failure". This would allow for retrospective determination of parameters such as Likelihood of Approval (LOA)".

This info is partially provided in the “Status” column but we can double check whether we get the right information from ChEMBL/clinicaltrials. Are you looking into something similar already @andrewhercules ?

![Screen Shot 2019-08-22 at 14 00 51](https://user-images.githubusercontent.com/6472381/63527406-f4d45380-c4f8-11e9-8b25-418b5749474d.png)

**Comment by andrewhercules** [comment]
@deniseOme: this is something that I was hoping we could add to the data table. However, I do not believe that any additional status information or results data is currently curated by ChEMBL. That being said, I do seem to recall that there are plans to do so in the future - @MichaelaEBI, can you please confirm if this is the case?

If such data does become available, I would strongly advise that we analyse the coverage of the data - I suspect that trials that were completed/terminated/withdrawn more than 3+ years ago may not have results or outcome data and so there will be many rows with blank or N/A values. We would also need to explore the coverage of data from ATC, DailyMed, and FDA as these are usually categorised as post-marketing, Phase IV with a status of "N/A" trials - perhaps ChEMBL could assign a "Success" value in the evidence strings. But if they were to do that, how would we flag something like Rofecoxib which has been withdrawn - again I also think this is something that ChEMBL is working on.

**Comment by MichaelaEBI** [comment]
I think that status covers most options already. This is how I see the suggested terms ("Has no results", "Success" , "Failure") fit with what we currently have:
- "Failure": 'suspended', 'terminated' or 'withdrawn'
- "Has no results": any status except for the three above and 'completed'
- "Success": some of the trials that are 'completed' will have been successful (or unsuccessful)
However, quite often there is no easy way to find out whether a trial has been successful or not. An approved drug is generally the best way to find out retrospectively whether a previous trial was successful and this is how Open Targets is currently using the ChEMBL data - anything in Phase IV must have been shown to work in successful clinical trials.

I don't think there is anything specific that we can do at this point. Whenever new data becomes available in ChEMBL, then Open Targets will make use of it.

**Comment by deniseOme** [comment]
Reason for closure:

1) This info is partially captured in “Status”
2) There is no data currently in ChEMBL that could be added following investigation by @andrewhercules and @MichaelaEBI
