### ISSUE TITLE
ChEMBL tractability data file for platform-input-support

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#723]
This is a placeholder ticket (more detail to be added) to work out how to deal with the tractability file in future OT releases. ChEMBL are currently uploading both the evidence and tractability file into their OT bucket. At the moment, the platform-input-support script expects the file in the otar001-core/Tractability bucket. For platform-input-support to pick up the tractability file, naming conventions have to be adhered to.

**Comment by andrewhercules** [comment]
Added to 19.11 release milestone - @cmalangone and I to resolve in that release

**Comment by AsierGonzalez** [comment]
After discussing this with @cmalangone and @andrewhercules we have decided to ask ChEMBL (Tim for now) to upload the tractability file directly to the `otar001-core/Tractability` bucket.

**Comment by andrewhercules** [comment]
I have confirmed with ChEMBL that they can upload file  to the ``otar001-core/Tractability`` bucket and have also shared the proposed file format of ``name_of_file_dd-mm-yyyy.tsv``.
