### ISSUE TITLE
Filter atlas evidence data based on target.activity

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#724]
The gene expression evidence we get can have one of three different values for target activities: `decreased_transcript_level`, `increased_transcript_level` or `unknown`. The `unknown` activity is assigned to evidence from comparisons that are not `disease` vs `normal` (more information [here](https://docs.google.com/document/d/1_40Knrsf69bHPVEzTYZVMyHhhabhSEYzO5u7wf1X84M/edit)) and, therefore, should not be used as evidence. Activity-based filtering of evidence was not performed until the 19.06 release because some old interesting comparisons were annotated with the `unknown` activity and they required re-curation.
The obejective of this ticket is to decide what is the best way to filter the evidence. For 19.06 and 19.09 the submitted file contained evidence with the three activity categories and the file were filtered by the data team. This is error prone, because someone needs to remember to do it so it would be better to automatise it. We could consider two alternatives to do so:

- Ask Atlas to exclude the evidence with `unknown` activity from the submitted file.

or 

- Include the filtering to the processing done by [`platform-input-support`](https://github.com/opentargets/platform-input-support).

Each option has its own advantages and limitations, so which solution do you think is better @cmalangone, @MichaelaEBI, @d0choa?

**Comment by AsierGonzalez** [comment]
Request to implement filtering in their side sent to Atlas team in November. Issue to be reviewed next time they submit a new file.

**Comment by AsierGonzalez** [comment]
Filtering still not implemeted by atlas for the 20.04 iteration so filtered in-house.

**Comment by AsierGonzalez** [comment]
Filtering still not implemeted by atlas for the 20.06 iteration so filtered in-house.

**Comment by AsierGonzalez** [comment]
Filtering still not implemeted by atlas for the 20.09 iteration so filtered in-house.

**Comment by andrewhercules** [comment]
Re-assigned to 20.11 to track outcome of this ticket in that release process

**Comment by AsierGonzalez** [comment]
There is no updated gene expression evidence file for 20.11, so moving this 21.02

**Comment by ireneisdoomed** [comment]
This has been already implemented in the Expression Atlas new pipeline, along with the specific filter we apply on a number of biotypes in expression data (see [#369](https://github.com/opentargets/platform/issues/369) for reference).

Closing the issue.
