### ISSUE TITLE
GTEx is down

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#725]
GTEx widget seems to be down e.g. 

https://www.targetvalidation.org/target/ENSG00000145777
https://www.targetvalidation.org/target/ENSG00000198125

Both Chrome and Firefox.
![Screen Shot 2019-08-29 at 10 04 29](https://user-images.githubusercontent.com/6472381/63926844-74f04100-ca44-11e9-9953-bdab34df404d.png)

Ed's pointed out they released a new version (GTEx v8) on 27th Aug. https://twitter.com/tuuliel/status/1166092633615339524

@peatroot has confirmed this "Calls like https://gtexportal.org/rest/v1/expression/geneExpression?gencodeId=ENSG00000091831.22 no longer have quantiles and outliers computed server side, they just pass all the data now."

Something to revisit for the rewrite @d0choa ?

**Comment by d0choa** [comment]
@mirandaio has been looking at updating our code to draw the boxplot with the new endpoint.

However, I found in the [Swagger documentation](https://gtexportal.org/home/api-docs/#!/expression/geneExpression) that in the previous version there was a `boxplotDetail` parameter that could be tuned to get the full data, median or quartiles.

It just seems they missed this feature in the new version. Before spending more time on this, I would suggest that @deniseOme drop them a line and ask whether they are planning to include this in the `gtex_v8` API

**Comment by mirandaio** [comment]
This function could be reused in the Angular app to transform the new data structure that is returned by the GTEx API to how the data was previously returned. https://github.com/opentargets/platform-app/pull/95/files#diff-be05d42e66ec54b698e1605fa9d1db38R9-R39

**Comment by LucaFumis** [comment]
Fixed version is live in production.
