### ISSUE TITLE
search in qa returns results of 10000 (target) and 10000 (disease)

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#726]
@LucaFumis @mirandaio @peatroot @d0choa, whilst searching for anything (disease, target, phenotype) the response returns by default the number 10000, always (consequence of moving from ES5 to ES7)

e.g.

https://qa.targetvalidation.org/search?src=q:ovarian%20carcinoma
https://qa.targetvalidation.org/search?src=q:dmd
https://qa.targetvalidation.org/search?src=q:Joint%20Swelling
https://qa.targetvalidation.org/search?src=q:Multiple%20sclerosis

@cmalangone has fixed this on the API, so the number we should expect returned on the front end for ovarian carcinoma is 700, not 20000:

http://platform-api-qc.opentargets.io/v3/platform/public/search?q=ovarian%20carcinoma

![Screen Shot 2019-09-02 at 11 24 27](https://user-images.githubusercontent.com/6472381/64108244-3f18c880-cd74-11e9-9f3e-3a38f5d6fab6.png)

**Comment by LucaFumis** [comment]
The search API endpoint doesn't have a 'proper' facets options. Rather the 'facets' on the search page are generated by calling the search enpoint again with size 0 and filtering by target and disease. Now both these calls return a `total` of 10000, which is what is displayed there...
https://platform-api-qc.opentargets.io/v3/platform/public/search?q=ovarian%20carcinoma&size=0&filter=target

**Comment by andrewhercules** [comment]
Ticket closed as UI displays correct number of targets and diseases
