### ISSUE TITLE
Update drug-summary-directive.js to show data returned from API

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#727]
As discussed with @cmalangone, due to the migration to ES7, the API response used for the drug summary page has changed.

Currently, the production version of the API returns the raw drug index object in JSON format. Please see below for a screenshot of the existing API response for [Rofecoxib - CHEMBL122](https://platform-api.opentargets.io/v3/platform/private/drug/CHEMBL122):

![Screenshot 2019-09-03 at 09 34 06](https://user-images.githubusercontent.com/7490258/64238774-efaed580-cef6-11e9-9aa8-0b55b9455465.png)

However, after moving to ES7, the drug index data will now be found in the `data` array and so we will need to call `data[0]` to get the data used by the Angular directive. Please see below for a screenshot of the new API response for [Rofecoxib - CHEMBL122](https://platform-api-qc.opentargets.io/v3/platform/private/drug/CHEMBL122)

![Screenshot 2019-09-03 at 09 33 51](https://user-images.githubusercontent.com/7490258/64238791-f5a4b680-cef6-11e9-9baf-4a26c843c636.png)

Can we please update the code in the [drug-summary-directive.js file](https://github.com/opentargets/webapp/blob/22122c6d9587a4f085c35e2895a7ea7048c85366/app/src/components/drug-summary/drug-summary-directive.js) to account for the new data structure?

**Comment by afaulconbridge** [comment]
After discussion with @andrewhercules @LucaFumis @cmalangone we have decided to stick to this `data` structure for better consistency with other API endpoints.

**Comment by ElaineMcA** [comment]
Pushed with 19.09 release on 24-Sep-2019.
