### ISSUE TITLE
Duplicated labels in facets

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#729]
@peatroot noticed the next problem in production (and rewrite): some labels are duplicated in the target class facet. (E.g. Hydrolase as Enzyme subcategory in [Chron's disease](https://www.targetvalidation.org/disease/EFO_0000384/associations))

From @peatroot:

When making query https://platform-api.opentargets.io/v3/platform/public/association/filter with body:

```
{"disease":["EFO_0000384"],"outputstructure":"flat","facets":"true","size":1,"target_class":["646","1027"]}
```

There's an issue with both `646` and `1027` being returned with label `Hydrolase` with key `646` and `1027`

Correct label `Primary active transporter` shown for key `1027` later in response

**Comment by d0choa** [comment]
Recent investigations point to this part of the pipeline as responsible:

https://github.com/opentargets/data_pipeline/blob/e8372eac48b81a337049dd6b132dd69ff5cc7b64/mrtarget/common/chembl_lookup.py#L116-L138

Still looking at it...

**Comment by cmalangone** [comment]
@mkarmona changed the procedure in the chembl_lookup.py. 
I run the code against 19.09 file and I uploaded the resultset here:
[response_protein_classification.zip](https://github.com/opentargets/platform/files/3595294/response_protein_classification.zip)

**Comment by d0choa** [comment]
Looks good for 2 of the problematic ids: `646` and `1027`. Let's wait to see if this resolves the issue once we have a new instance of 19.09.

**Comment by d0choa** [comment]
Problem persists in 19.09.4. @mkarmona looking at it

**Comment by mkarmona** [comment]
Coming from this disease `EFO_0000384` and this target `ENSG00000105675` chembl annotate target classes [as these two](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL3919/). The problem seems to be the aggregation is done by the API.

**Comment by andrewhercules** [comment]
Ticket moved to 20.02 release

**Comment by d0choa** [comment]
The new API will resolve this issue. No work expected
