### ISSUE TITLE
Drug index: Refine content of ES Drug index

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#73]
- [x] Filter for human diseases and targets

- [ ] Investigate indications in more detail (exclude cosmetics or carriers)

- [ ] Disease ontology mapping if necessary

- [ ] Evaluate number and usability of disease-drug and drug-target pairs

**Comment by afaulconbridge** [comment]
Filtering against disease index opentargets/platform#599 should solve this. Can this issue be closed?
