### ISSUE TITLE
Display more details for drug mode of action in drug tables

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#730]
Based on ticket #533 there are two front end changes related to drug mechanism of action:

1) ChEMBL have changed the values of the `target.activity` field to be `negative_modulator`, `positive_modulator` and `other`. In the Open Targets front end we currently do this:
```
 // 11: Activity
                        cell = item.target.activity;
                        switch (cell) {
                        case 'drug_positive_modulator' :
                            cell = 'agonist';
                            break;
                        case 'drug_negative_modulator' :
                            cell = 'antagonist';
                            break;
                        }
```
The new values can be displayed in the drugs table and do not have to be mapped to `agonist`, `antagonist` anymore.

2.) ChEMBL provides more detailed mechanism of action terms in the `target2drug.action_type` field. This field gives more details which would be useful to users. It would be great to display this field together with `.target.activity`.

**Comment by andrewhercules** [comment]
This has been pushed to the 19.11 release - please see the [19.11 Release Intentions document](https://docs.google.com/document/d/1DcQ1CVg0jgQpJlKSvVCQkcYznwaAKiUcY0khToA0Ubg/edit#heading=h.66yhh7b333u1) for more information.

**Comment by LucaFumis** [comment]
Part 1 (activity label) has been completed and included in 19.09.
Only part 2 is left for 19.11 release.

**Comment by LucaFumis** [comment]
I've updated `qa` and the drugs table now shows an "action type" column: do check if the location (column order) makes sense.

**Comment by d0choa** [comment]
Column order looks good to me. I'll leave it to @andrewhercules (or @MichaelaEBI feedback) to decide whether this can be closed.

**Comment by andrewhercules** [comment]
Ticket closed as work has been completed
