### ISSUE TITLE
Rewrite: page crashes when visiting certain expression atlas widgets

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#732]
The expression atlas widget in target profile page seems to be crashing the site [AKT1](https://platform-app.netlify.com/target/ENSG00000142208).

The console throws the next error:

- TypeError: undefined is not an object (evaluating 'i.genomeBrowsers[0].replace')
- Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'i.genomeBrowsers[0].replace')

Since this widget is often a problem, I would suggest the next actions:
- [ ] Try to handle the error nicely
- [ ] Include smoke test to make sure this widget is present in one random target?

**Comment by peatroot** [comment]
This is broken for all targets I think. We have `v5.2.6`, which fails for BRAF and AKT1, but `v5.3.1` works for both. See https://github.com/opentargets/platform-app/pull/105.
