### ISSUE TITLE
platform-infrastructure es use machine tag

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#733]
As with pipeline machine, we should wait for the elasticsearch startup script to fully complete by looking for the machine tag instead of the elasticsearch status.

This would help ensure that dump credentials and plugins have completed installation and setup before the MCP proceeds with the pipeline.

**Comment by cmalangone** [comment]
@afaulconbridge : We got a couple of issues this release (19.09) were the ES docker image failed to be download and subsequently ES did not start properly.
This behaviour was easy to detect due the check of the health endpoint. 
We might implement a strategy that check both. 
It is really useful to check that the ES is up and running.

Moreover, with this version we can easily re-run the docker command and continue the release.

**Comment by andrewhercules** [comment]
Ticket moved to 20.02 release

**Comment by cmalangone** [comment]
the script verifies that ES is up and running and the MCP is able to capture it properly.
So action is required
