### ISSUE TITLE
Changing field in the API response from `probenumber` to `number_of_probes`

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#735]
The private endpoint to retrieve target annotations returns the field `probenumber` e.g.
http://platform-api.opentargets.io/v3/platform/private/target/ENSG00000232810

As per 19.06:
<img width="474" alt="Screen Shot 2019-09-17 at 12 33 10" src="https://user-images.githubusercontent.com/6472381/65038866-ceafa100-d948-11e9-8cdc-b61b93930fbd.png">

This has caused confusion (is this a unique, stable probe ID? Or does it refer to the number of probes) and led to inclusion of this rule in checkOmatic. 

It's been agreed by @afaulconbridge @MichaelaEBI to rename this field to `number_of_probes`.

@mkarmona and I will change the checkOmatic rule so it no longer takes this field into account, rather a stable one, which is not expected to change over time.

**Comment by andrewhercules** [comment]
@afaulconbridge, for 19.11, could you please change the Chemical Probes plugin so that the API response changes from `probenumber` to `number_of_probes`?

**Comment by AsierGonzalez** [comment]
If we keep this value in the response (no matter the name) the expected value needs to be changed as there are now 801 "probes" for that target (see https://probeminer.icr.ac.uk/#/P01375) after the Probes Miner update in July

**Comment by d0choa** [comment]
Can @andrewhercules confirm we don't use this number in the FE?
If this is the case and it's simpler, we can remove this field completely. It's a source of errors as we have to manually update the data.
In the future, Chembl will provide this information and we can re-evaluate what needs to be shown.

**Comment by andrewhercules** [comment]
@d0choa: we do NOT use this number in the front-end and so we can drop this field completely

**Comment by andrewhercules** [comment]
Ticket has been moved to 20.02 release

**Comment by AsierGonzalez** [comment]
The probe number will be removed from the API response. PR https://github.com/opentargets/data_pipeline/pull/557 should fix this.
I will close the ticket after I check that this is the case after the next pipeline run.

**Comment by AsierGonzalez** [comment]
This has been resolved in QA
