### ISSUE TITLE
Protein information not working for deprecated Uniprot ids

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#738]
Protein information in Target Profile Page is not working for ARHGDIA (ENSG00000141522) in 19.09 QA. This is because the front end constructs the Uniprot links using the first item in the `uniprot_accessions` array returned by the API, which is `B4DUV9` for this gene. This Uniprot id is deprecated and the page has been moved permanently (HTTP 301) to `P52565`.

This issue would be solved if the FE used `uniprot_id` instead for the links. In addition, back end should try to check that the Uniprot ids are still valid.

**Comment by mkarmona** [comment]
Having deprecated uniprot ids aren't necessarily a bad thing as it can resolve old publications from literature. When the literature mining project does the resolving of the IDs then we can think about removing deprecated ones.

**Comment by mkarmona** [comment]
@LucaFumis I guess the sensible thing to do is just pick the `uniprot_id` field from the target object if not null and use as a default protein id. 
Having a look at the code, I found at [least 3 potential places](https://github.com/opentargets/webapp/search?q=uniprot_accessions&unscoped_q=uniprot_accessions) where the selected uniprot id to [show are wrong](https://qa.targetvalidation.org/search?src=q:ARHGDIA) as you can see on the right side on the search result page. It is also wrong on the target profile page as [you can see here](https://qa.targetvalidation.org/target/ENSG00000141522) hovering over the target function description _Uniprot_ link.
