### ISSUE TITLE
Assess component usage within ot-ui

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#743]
The repo `ot-ui` is intended for code reuse between `platform-app` and `genetics-app`. There are currently some components that are used only in one repo or that would ideally be refactored. There is therefore a need to go through each component and assess any refactoring or whether it is best to move  it to the single app in which it is used.

**Comment by peatroot** [comment]
## Root components

| Component            | Used in `platform-app` | Used in `genetics-app` | Used internally | Notes                                                         | TODOs                                                                                                 |
| -------------------- | ---------------------- | ---------------------- | --------------- | ------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------- |
| BrowserControls      | N                      | Y                      | N               |                                                               | move to `genetics-app`                                                                                |
| Button               | Y                      | Y                      | N               | use of Button from `ot-ui`, but IconButton from `material-ui` | remove?                                                                                               |
| Chip                 | N                      | Y                      | N               | use of `material-ui` Chip in `platform-app`                   | remove?                                                                                               |
| CloseButton          | N                      | Y                      | N               |                                                               | remove?                                                                                               |
| DataCircle           | N                      | Y                      | N               |                                                               | move to `genetics-app`?                                                                               |
| DataDownloader       | Y                      | Y                      | N               |                                                               |                                                                                                       |
| DownloadSVGPlot      | Y                      | Y                      | N               |                                                               |                                                                                                       |
| EmailLink            | N                      | N                      | Y               | not exported                                                  | remove?                                                                                               |
| Footer               | Y                      | Y                      | N               |                                                               |                                                                                                       |
| HomeBox              | N                      | Y                      | N               |                                                               | refactor when doing `platform-app` homepage?                                                          |
| LabelHML             | N                      | Y                      | N               |                                                               | remove?                                                                                               |
| Link                 | Y                      | Y                      | Y               | issue with `react-router-dom` context                         | consider `material-ui` Link instead?                                                                  |
| ListTooltip          | Y                      | Y                      | N               |                                                               | consider pattern with HOCs `withTooltip` in `platform-app` and `ot-charts`?                           |
| ModelSchematic       | N                      | N                      | Y               |                                                               | remove export                                                                                         |
| MultiSelect          | N                      | N                      | N               |                                                               | remove                                                                                                |
| NavBar               | Y                      | Y                      | N               |                                                               |                                                                                                       |
| OpenTargetsTitle     | N                      | N                      | Y               |                                                               | consider moving internal components to separate directory?                                            |
| OtTable              | Y                      | Y                      | N               |                                                               | remove                                                                                                |
| OtTableRF            | Y                      | Y                      | N               |                                                               | rename? consider splitting due to server vs client side pagination filtering?                         |
| OtUiThemeProvider    | Y                      | Y                      | N               |                                                               | rename to `ThemeProvider`?                                                                            |
| Page                 | Y                      | Y                      | N               |                                                               |                                                                                                       |
| PlotContainer        | N                      | Y                      | Y               |                                                               | rename/remove?                                                                                        |
| PlotContainerSection | N                      | Y                      | Y               |                                                               | rename/remove?                                                                                        |
| SearchExamples       | N                      | N                      | N               |                                                               | remove                                                                                                |
| SectionHeading       | N                      | Y                      | N               |                                                               | remove and harmonise section structure between `platform-app` and `genetics-app`? currently different |
| Splash               | N                      | Y                      | N               |                                                               | refactor when doing `platform-app` homepage?                                                          |

**Comment by peatroot** [comment]
## Typography components

| Component  | Used in `platform-app` | Used in `genetics-app` | Used internally | Notes                        | TODOs  |
| ---------- | ---------------------- | ---------------------- | --------------- | ---------------------------- | ------ |
| Heading    | N                      | N                      | Y               | used in eg. `SectionHeading` | remove |
| PageTitle  | N                      | N                      | N               |                              | remove |
| SubHeading | N                      | N                      | Y               | used in eg. `SectionHeading` | remove |
| Text       | N                      | N                      | N               |                              | remove |

**Comment by peatroot** [comment]
## Search subcomponents

We could potentially replace the `Autocomplete` and `Search` components using [react-select-material-ui](https://github.com/iulian-radu-at/react-select-material-ui), which appears to be a maintained styling of `react-select`. We currently do this ourselves. This would affect the following components in `ot-ui`, most of which are only used internally in the `Autocomplete` and `Search` components.

- `Autocomplete`
- `Control`
- `DropdownIndicator`
- `Group`
- `GroupHeading`
- `Menu`
- `MenuFilter`
- `MultiValue`
- `NoOptionsMessage`
- `OptionContainer`
- `OptionFilter`
- `Placeholder`
- `Search`
- `SearchOption`
- `SingleValue`
- `ValueContainer`

**Comment by andrewhercules** [comment]
Closing ticket - for information purposes and will be picked up at a later date
