### ISSUE TITLE
Add analytics support to `platform-app`

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#745]
The `platform-app` will need analytics support before release. Some thoughts:
* It should be easy to toggle analytics on/off and to switch the provider.
* There should be a common mechanism for page analytics (eg. HOC for page components?).
* There should be a common mechanism for event analytics (eg. HOF for event handlers?).

**Comment by peatroot** [comment]
There are currently helpers used in the `genetics-app`, which could be moved to `ot-ui` for reuse in `platform-app`:
* `useAnalytics`
* `withPageAnalytics`
* `reportAnalyticsEvent`

**Comment by andrewhercules** [comment]
Ticket closed as basic installation of Google Analytics completed and merged into `alpha` in #1092
