### ISSUE TITLE
HPA step: Unicode error (data pipeline)

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#749]
I tried to run the data release with this config file:
https://storage.googleapis.com/open-targets-data-releases/19.11/input/mrtarget.data.19.11.efo3-slim.yml

The data pipeline was running using python3 and recently we updated HPA step.
The error is:
File "/usr/src/app/mrtarget/modules/HPA.py", line 488, in elasticsearch_actions
   for entry in hpa_merged_table.data():
....
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 10: invalid start byte
Command exited with non-zero status 1
	Command being timed: "python -m mrtarget.CommandLine --hpa"
	User time (seconds): 1.46

**Comment by afaulconbridge** [comment]
This is due to the line in the config:
```
hpa-normal-tissue: https://storage.googleapis.com/open-targets-data-releases/19.11/input/annotation-files/normal_tissue-2019-08-22.tsv.zip
```
Due to python3, this file cannot be compressed. See PR https://github.com/opentargets/platform-input-support/pull/15 which needs to be resolved before this ticket can be closed.

**Comment by cmalangone** [comment]
I fixed the code in the platform-input-support.
https://github.com/opentargets/platform-input-support/commit/6c8038584dacb7530dde4f2873e62ec88139c51e

**Comment by andrewhercules** [comment]
Ticket closed as work has been completed and pipeline successfully run for the 19.11.4 release
