### ISSUE TITLE
Drug index : III : Enhance search functions associated with drug

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#75]
Search should return a separate type of result "drug" pointing to the single page for each drug. This includes brand and generic names, safety warnings, and low weighting of genes and associated diseases.

**Comment by ElaineMcA** [comment]
2019 roadmap - timeline to be confirmed.

**Comment by ElaineMcA** [comment]
Ensure that ability to search by unique identifier (private ID or ChEMBL ID)

**Comment by d0choa** [comment]
#822 and #823 supersede this ticket
