### ISSUE TITLE
Re-run LINK pipeline with EFO3 'slim' OWL file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#750]
Details TBC once finalised EFO3 'slim' OWL file is available

**Comment by afaulconbridge** [comment]
Is this superseded by #769 & #770 @andrewhercules ?

**Comment by andrewhercules** [comment]
Yes @afaulconbridge! :-)

Based on our meeting last week, I've set #770 as a dependency/blocker for this ticket as we will want to update the dictionaries to capture new EFO3 terms. If I remember correctly, we should still be able to run LINK even if #769 is still open/pending?

**Comment by arwaraies** [comment]
One benefit of updating the libraries and code is to be able to run LINK efficiently. Running LINK using the existing code and libraries is extremely slow and it may not be possible using only one machine. So I think both #769 and #770 should dependencies.

**Comment by andrewhercules** [comment]
Good point @arwaraies! 👍  I have updated the dependencies for this ticket! :-)

**Comment by andrewhercules** [comment]
Awaiting final confirmation from @cmalangone that all the data has been loaded into an ElasticSearch index

**Comment by andrewhercules** [comment]
Issue closed as LINK has been rerun with EFO3 and bug identified by back-end team limiting the amount of data loaded into ElasticSearch has [been resolved](https://github.com/opentargets/library-beam/commits/master)
