### ISSUE TITLE
Rewrite: attempt to include tractability in classic associations view

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#755]
We want to explore the possibility to include the tractability track in the classic associations view as extra columns when visiting a disease (and targets are listed).

If we are convinced by this approach we might decide to drop the prioritisation view for a more simplified view.

Similar approach might be discussed for the dynamic associations view.

**Comment by peatroot** [comment]
I've added columns for small molecule and antibody tractability on the classic disease associations page ([see example](https://platform-app.netlify.com/disease/EFO_0000384/classic-associations)).

The current scoring system (which should probably be discussed) that generates the green colours:
* takes the checked buckets per target (a boolean array, sorted by decreasing reliableness as tractability indicator)
* computes the sum of powers of two for negated indices where the boolean array is true

<img width="1487" alt="Screenshot 2019-12-06 at 14 32 59" src="https://user-images.githubusercontent.com/7376272/70330950-721c9d80-1836-11ea-89e1-58f7536b70fd.png">
