### ISSUE TITLE
EFO3 disease description in pipeline

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#756]
As @deniseOme noted, the disease description in EFO3 is actually a list of descriptions. The pipeline currently concatenates them and the API presents them as one single string.

Sometimes, the descriptions might be very similar if not the same and we show the same string duplicated (e.g. ovarian carcinoma).

We will need to change the response to provide a list of descriptions or, alternatively, present arbitrarily only one (the first) of the descriptions. The OLS does actually the latter.

**Comment by afaulconbridge** [comment]
How about keeping the existing single description field, so the API is backwards compatible, but adding a separate `description_alternative` field with a full list? That seems the best of both worlds to me.

**Comment by afaulconbridge** [comment]
Created branch `af-756-disease-description` with this added. Will need a pipeline run to test.

**Comment by afaulconbridge** [comment]
Merged into master and deployed on qa.targetvalidation.org

**Comment by andrewhercules** [comment]
Ticket closed as issue has been resolved in 19.11. The `/private/disease` endpoint now returns a `description_alternative` field with all associated descriptions while the `description` field returns only one description to prevent duplication in the disease profile page UI.
