### ISSUE TITLE
PheWAS variant cosequence SO text not displayed

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#757]
As reported by @deniseOme, the PheWAS evidence in the genetic associations tab displays `SO 0001060` in the `Variant Type` column instead of its text equivalent, i.e. “sequence variant”. The image below shows [the genetic evidence of the NOD2-Crohn's disease association](https://www.targetvalidation.org/evidence/ENSG00000167207/EFO_0000384?view=sec:genetic_association):

![Screenshot 2019-10-15 at 14 12 10](https://user-images.githubusercontent.com/11410715/66834820-48da4200-ef56-11e9-8cfc-05fdcb8022b6.png)

Based on the explanation given by @peatroot about how the text displayed in the **Variant type** field in the common variants table is calculated, this happens when `.evidence.evidence_codes_info === null`. I have checked the PheWAS evidence strings and they are all annotated with the consequence `http://purl.obolibrary.org/obo/SO_0001060` but their `evidence_codes_info` returned by the API is always `null`. See the [API response for the example above](https://platform-api.opentargets.io/v3/platform/public/evidence/filter?size=1000&datasource=phewas_catalog&fields=unique_association_fields&fields=disease&fields=evidence&fields=variant&fields=target&fields=sourceID&fields=access_level&target=ENSG00000167207&disease=EFO_0000384&view=sec:genetic_association&expandefo=true) and two additional examples:

- [CFI-colorectal cancer](https://platform-api.opentargets.io/v3/platform/public/evidence/filter?size=1000&datasource=phewas_catalog&fields=unique_association_fields&fields=disease&fields=evidence&fields=variant&fields=target&fields=sourceID&fields=access_level&target=ENSG00000205403&disease=EFO_0005842&view=sec:genetic_association&expandefo=true)

- [TCF7L2-diabetes mellitus](https://platform-api.opentargets.io/v3/platform/public/evidence/filter?size=1000&datasource=phewas_catalog&fields=unique_association_fields&fields=disease&fields=evidence&fields=variant&fields=target&fields=sourceID&fields=access_level&target=ENSG00000148737&disease=EFO_0000400&view=sec:genetic_association&expandefo=true)

This suggests that there must be an issue in the data pipeline.

**Comment by afaulconbridge** [comment]
@AsierGonzalez can you extract the equivalent input evidence string please? So we can see what is going into the pipeline.

**Comment by LucaFumis** [comment]
There was a similar issue a while back, only recently resolved at data level:
https://github.com/opentargets/platform/issues/19

**Comment by AsierGonzalez** [comment]
The ECO ES index seems to be fine since SO_0001060 is in there. I wonder if the source of the issue is that this is the root term of the SO ontology and that breaks something in the pipeline. @mkarmona or @cmalangone, could you please have a look?

<img width="1354" alt="Screenshot 2019-12-06 at 13 07 00" src="https://user-images.githubusercontent.com/11410715/70325185-5b237e80-1829-11ea-9c31-6a54ccffd439.png">

**Comment by deniseOme** [comment]
@AsierGonzalez, it seems this is no longer an issue per se (at least visible on the UI) as we have dropped the "variant info" column in the new table.

<img width="1175" alt="Screen Shot 2020-02-26 at 19 47 25" src="https://user-images.githubusercontent.com/6472381/75381549-d64c7c00-58d0-11ea-9cf0-e799fc1482c7.png">

**Comment by AsierGonzalez** [comment]
@deniseOme the problem is not solved yet as the API still returns the codes instead of the labels and it requires BE work to find out what is happening. Dropping the column from the table was a temporary FE workaround.

**Comment by AsierGonzalez** [comment]
The real issue seems to be that `PheWAS` is not in the ECO index. The action suggested in #874 should fix this issue.

**Comment by AsierGonzalez** [comment]
This is now fixed, the SO codes can be found in the REST API response:

- 20.02

```
"evidence_codes_info": null
```
- 20.04 QA
```
"evidence_condes_info": [
[{"eco_id": "ECO_0000362", "label": "evidence based on computational logical inference"}],
[{"eco_id": "GWAS", "label": "Genome-wide association study evidence"}],
[{"eco_id": "locus_to_gene_pipeline", "label": "Open Targets Genetics portal locus to gene annotation pipeline"}],
[{"eco_id": "SO_0001583", "label": "missense_variant"}]
]
```
