### ISSUE TITLE
Rewrite: Some Protista v2 links are broken

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#759]
We need to come back to Xavier to fix some of the links in the variation track. Clinvar links seem to be broken

**Comment by mirandaio** [comment]
@d0choa Xavier agrees this is a bug. I've opened an issue in their repository: https://github.com/ebi-webcomponents/protvista-uniprot/issues/7

**Comment by andrewhercules** [comment]
Blocked by https://github.com/ebi-webcomponents/protvista-uniprot/issues/7

**Comment by mirandaio** [comment]
Upgraded the version of `protvista-uniprot` which fixes this issue.
