### ISSUE TITLE
Heatmaps on association pages across rewrite

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#760]
We need to improve the aesthetics of the heatmap visualisations:

- [x] Change gradient to go from light blue to darker blue. Currently it goes from white to blue and very low values are confused with missing data. ([Example](https://platform-app.netlify.com/target/ENSG00000228412/classic-associations))

- [x] Include color scale

- [x] Try with similar aspect as the webapp in terms of cell border and spacing. It looks hard to improve at the moment

**Comment by peatroot** [comment]
Implemented for the classic associations ([see example](https://platform-app.netlify.com/disease/EFO_0000384/classic-associations)):

<img width="1487" alt="Screenshot 2019-12-06 at 14 32 59" src="https://user-images.githubusercontent.com/7376272/70331077-a6905980-1836-11ea-8050-6a0316fd45a3.png">

**Comment by d0choa** [comment]
I've gone with @andrewhercules through some of the pending things:
- [ ] Add slider for bubbles and graph view that defaults to showing associations over 0.1
- [ ] Bubbles/Graph views: when a user selects a TA only show that TA (similar to current production), rather than showing the other TAs that diseases may appear in
- [ ] Table view: when a user hovers over a disease name (with ellipsis) or gene name, show the full disease or gene name
- [ ] Table view: when a user hovers over a cell, show the score (similar to current production) except for tractability cells (instead, only allow user to click through to tractability section on target profile page)
- [ ] Table view: when a user clicks on the gene/disease name or overall score cell, redirect user to top of evidence page; when a user clicks on a specific cell (e.g. somatic mutations), redirect user to that specific section on evidence page (similar to current production)
- [ ] Trigger column sorting when clicking on the label.

Other activities:
- We need to trigger the loading state in different places in the page. The association pages requires to show the loading state to show users that facets are been applied and that application is dealing with data.
- @andrewhercules noticed a bug with the table sorting that seems very difficult to reproduce. We'll need a bit more information about it.
