### ISSUE TITLE
navigation bar going on top of footer

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#767]
Make sure navigation bar don't go on top of footer.

**Comment by d0choa** [comment]
Not an immediate priority but if you @javfg could have a look at this at some point would be great.

**Comment by javfg** [comment]
Can we get a screenshot of this? I can't reproduce it.

**Comment by d0choa** [comment]
![Screenshot 2020-04-17 at 12 06 03](https://user-images.githubusercontent.com/5097586/79563010-df252700-80a3-11ea-9b4b-583c546dc815.png)

**Comment by javfg** [comment]
The new sidebar does not overlap any text in the footer: 

![image](https://user-images.githubusercontent.com/6058151/103749713-c546be00-4ffd-11eb-94da-17c7d3307798.png)
