### ISSUE TITLE
LINK: review/refactor Python code and dependencies

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#769]
Based on today's meeting, @afaulconbridge will explore the LINK codebase to see what updates can be made to dependencies and libraries and if the code can be refactored so that it can easily be run in the future

**Comment by afaulconbridge** [comment]
Pretty much done, awaiting rerun completion for 19.11 & EFO3

**Comment by andrewhercules** [comment]
Ticket closed as LINK has been rerun with EFO3 - awaiting final confirmation that all data has been loaded into the ElasticSearch index.
