### ISSUE TITLE
Issue with orthologues in some pages (MAP3K2)

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#771]
At least one target profile page crashes - MAP3K2
https://platform-app.netlify.com/target/ENSG00000169967

The console error says:
TypeError: null is not an object (evaluating 'e.orthologuesBySpecies')

By the name of the field, it looks to be related with the "Homology" widget

**Comment by andrewhercules** [comment]
Check console log as Bibliography section is also showing an error
