### ISSUE TITLE
Update "Targets" section in Drug Profile Page

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#772]
Self-explanatory. We don't need it as all targets come from the mechanisms of action table.  It's basically a duplication of information

**Comment by andrewhercules** [comment]
Based on our front-end team meeting yesterday, can we please make the following changes to the "Target" section on the drug profile page?

- [ ] Update data table to display target class and associated Reactome pathway(s)
- [ ] Add functionality to export list of targets in CSV, JSON, or TSV format

**Comment by d0choa** [comment]
Consider @andrewhercules comment a correction of the previous action.

I have doubts about the target class and the pathways as I understand it might be a long list for some of the targets. Please double check if appropriate before implementing it.

**Comment by LucaFumis** [comment]
After discussion it was decided to add the target name instead.
Will update the table with target class and pathways if/when agreed where the info is coming from.

**Comment by LucaFumis** [comment]
This has been merged - closing.
