### ISSUE TITLE
Update "Disease" section on drug profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#773]
Based on our front-end team meeting yesterday, can we please make the following changes to the "Disease" section on the drug profile page?

1. Change the explanatory text to `DRUG NAME has been indicated for the following diseases`
2. In the data table, include the max clinical trial phase value for that indication

**Comment by LucaFumis** [comment]
Just a note, as I had a quick look at this, thinking it was a simple cosmetic change.
It seems that for the max clinical trial phase we should update the API:
the production API drug endpoint `private/drug/ID` now has a new `indications` field. This will have to be added to our Graphql API; there is a comment in LinkedDisease.js

**Comment by LucaFumis** [comment]
Fixed as PRs have been merged:
https://github.com/opentargets/platform-api/pull/51
https://github.com/opentargets/platform-app/pull/118
