### ISSUE TITLE
Redesign homepage for React version of Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#775]
TBC with mockup for new homepage

**Comment by andrewhercules** [comment]
![new_homepage_v1](https://user-images.githubusercontent.com/7490258/68468853-c5d4a080-0210-11ea-84dc-8846f510d2c5.png)

@d0choa, here is an initial draft of the new homepage for the React version of the Platform. I have made some changes, which I've noted below:

- [ ] The hero background image is a network diagram overlaid on a map, courtesy of [Pixabay](https://pixabay.com/illustrations/earth-globalisation-network-3866609/). The rationale for this image is two-fold: 1) to show the global reach of the Platform and our services; and 2) to show network connections. 

- [ ] For the quick search terms, we should always display a target, a disease, a generic drug label, and a brand-name drug. When I spoke with users about drug search, they wanted to be able to search by generic and brand-name. One thing to consider depending on the size of the search box - should we also show the various IDs that users can search for (e.g. ENSG, EFO, CHEMBL)?

- [ ] I have created 6 call-to-action buttons representing the 6 most-common tasks a user would want to do after visiting the home page. Because of this section, I have removed some of the existing links we show (e.g. outreach sessions, tutorials, FAQs, etc.).

- [ ] I have updated the description about the Open Targets Consortium to be more in line with the text found on the Open Targets corporate website.

Any comments would be much appreciated! :-)

**Comment by AsierGonzalez** [comment]
Is there a reason to move the grey box with the data version and stats down? I like to see it right under the search box :)

**Comment by LucaFumis** [comment]
A hero image at the top is quite nice - I suspect it will be tricky to find the right one though.

Also worth considering whether we want to keep all the social media feeds: FB and Twitter requires some extra JS and that scrollable box is not always ideal. 
On the other hand we pull the blog post through its API: this could be made into a larger feature, like a carousel (if I remember correctly we could pull the hero image for each blog post)

**Comment by d0choa** [comment]
@andrewhercules I'm closing this to avoid confusion as logos etc are obsolete. I believe a different ticket will be necessary for any future work on the home page, but this one might still be useful for reference
