### ISSUE TITLE
pharmacovilance data: crohn’s vs chron^s

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#778]
the new pharmacovigilance data has some minor issues with denoting diseases e.g. 
Crohn^s disease” = “Crohn’s disease”

https://qa.targetvalidation.org/summary?drug=CHEMBL1201580

This means that we report those two as two different adverse events. This will have an impact on the significance that is computed (log likelihood ratio and the reported critical value threshold). This does not seem to be widespread to other diseases, with drugs in phase IV, that have an apostrophe e.g. Hansen’s, Hodgkin’s, and “Raynaud’s” etc...

![Screen Shot 2019-11-13 at 17 19 17](https://user-images.githubusercontent.com/6472381/68787613-c5d20780-0639-11ea-9ecc-e9275b0f50d3.png)

**Comment by mkarmona** [comment]
@deniseOme this should fix this and any other possible same problem. If you catch any other typo please reopen it and highlight the character that causes the typo

```scala
@ val df = List("crohn's", "crohn^s").toDF("name") 
df: DataFrame = [name: string]

@ df.selectExpr("translate(name,'^','\\'')").show() 
+---------------------+
|translate(name, ^, ')|
+---------------------+
|              crohn's|
|              crohn's|
+---------------------+

```
