### ISSUE TITLE
OTAR015 - CRISPR: Review project data and publication to understand scope of data and importance for Platform

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#78]
The plan is to use the CRISPR data that was generated as part of the Sanger Cancer Dependency Map as evidence and potentially as target annotation in the Open Targets platform.

To do:
- [x] Summary of data as described in the publication draft
- [x] Get tour of the cancer dependency map app (Andrew to organise?)
- [x] Get the data files with different values (Bayesian factors, scaled bayesian factors and log-fold changes before/after CRISPcleanR correction)
- [x] Disease mapping for cancer cell lines

**Comment by ElaineMcA** [comment]
@MichaelaEBI has discussed with Miguel P and proposal is to include evidence under Pathways and System Biology.

**Comment by MichaelaEBI** [comment]
Disease mapping for the cancer cell lines has been done and I will look into this very soon: 

All cell lines that have been crispr'ed are included on our new website the Cell Model Passports, which can be found on cellmodelpassports.sanger.ac.uk. On the downloads page, the top file is a list of all of our models. These have been annotated with various identifiers and names, as well as (in order of granularity) tissue, cancer type and cancer type details. The latter is also mapped to NCIThesaurus terms.

Alternatively, all this information is available through the api at api.cellmodelpassports.sanger.ac.uk/models - the documentation for the API can be found on the website under the user guides.

**Comment by MichaelaEBI** [comment]
Progress of the OTAR015 data inclusion can be followed here: #163
