### ISSUE TITLE
Cancer Hallmarks request for correction of grammatical errors

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#780]
Please may you chnage the following sentence 

 Essencial alterations in cell physiology that dictate malignant growth. Cancer hallmarks were originally described by Hanahan and Weinberg (2000), are manually curated by COSMIC and integrated in the Cancer Gene Census. 

to read as below

Essential alterations in cell physiology that dictate malignant growth. Cancer hallmarks, originally described by Hanahan and Weinberg (2000) are manually curated by COSMIC and integrated in the Cancer Gene Census.

**Comment by andrewhercules** [comment]
Ticket closed as issue fixed
