### ISSUE TITLE
Cancer Biomarkers Summary- request for punctuation correction

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#781]
Please may you amend the following paragraph

 Genomic biomarkers of drug responses, and their levels of clinical significance as described by Tamborero et al. (2018). This data is manually curated by clinical and scientific communities in the field of precision oncology. 

to read as follows (please may you remove the comma after the word responses) 

Genomic biomarkers of drug responses and their levels of clinical significance as described by Tamborero et al. (2018). This data is manually curated by clinical and scientific communities in the field of precision oncology.

**Comment by andrewhercules** [comment]
Ticket closed as issue resolved
