### ISSUE TITLE
No target tractability data notification not always visible

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#783]
@PruMM has identified an issue where the sentence about no tractability data is not visible for some targets. For a target like [TRIP11](https://qa.targetvalidation.org/target/ENSG00000100815), we display the sentence `No tractability data for TRIP11 is available` in the Target Tractability section:

![Screenshot 2019-11-21 at 10 43 20](https://user-images.githubusercontent.com/7490258/69330906-c2e3a200-0c4b-11ea-8190-e007082a6179.png)

However, for a target like [BRCA2](https://qa.targetvalidation.org/target/ENSG00000139618), the sentence about no tractability data does not show:

![Screenshot 2019-11-21 at 10 41 32](https://user-images.githubusercontent.com/7490258/69330827-9def2f00-0c4b-11ea-9a4d-8615029896f0.png)

In reviewing the API response for both targets, [the BRCA2 API response](http://platform-api-qc.opentargets.io/v3/platform/private/target/ENSG00000139618) has an empty object for tractability compared to [the API response for TRIP11](http://platform-api-qc.opentargets.io/v3/platform/private/target/ENSG00000100815) which has the full tractability schema but no data in the respective buckets fields.

@LucaFumis, can we please update the logic in [the target-tractability.html file](https://github.com/opentargets/webapp/blob/0b7ea215d74bb57868b8c859a22ffe72596470e8/app/plugins/target-tractability/target-tractability.html#L54) to check if the `tractability` key is an empty object `{ }` in addition to both arrays being empty?

**Comment by AsierGonzalez** [comment]
The real cause of this issue is that TRIP11 (ENSG00000100815) appears in the tractability file whereas BRCA2 (ENSG00000139618) doesn't, is this expected? My understanding was that the tractability pipeline was supposed to generate an entry for all the genes regardless of whether they are tractable or not.
