### ISSUE TITLE
data_pipeline branch for the 19.11 release

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#788]
Hi, is there a specific branch in data_pipeline that was used to build the 19.11 release?  Based on https://github.com/opentargets/platform/issues/765, it seems like there should be one but I don't see any obvious suspects.  I wanted to run the pipeline locally and to be certain that I'm using the same code that was used for the recent update.  Thanks!

**Comment by AsierGonzalez** [comment]
Hi @eric-czech, I believe you should be using [tag 19.11.4](https://github.com/opentargets/data_pipeline/tree/19.11.4) which is also the [latest data-pipeline release](https://github.com/opentargets/data_pipeline/releases/tag/19.11.4). Can you please confirm that this is the case @cmalangone?

**Comment by cmalangone** [comment]
The releases 19.04, 19.06 and 19.09 used EFO2 ontology meanwhile the master branch was used to develop the new code for using EFO3 ontology
From 19.11, the data release uses only EFO3 so it is not necessary to create a specific branch anymore. Please let me know if you need more details or if you have further questions.

**Comment by cmalangone** [comment]
@eric-czech: please let me know if I can close this issue.

**Comment by eric-czech** [comment]
Makes sense, thanks @cmalangone
