### ISSUE TITLE
Underlying storage questions in regard to Spark pipelines

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#790]
Hey @mkarmona cc: @d0choa (moving this discussion out of email in case it helps others),

I had a quick and hopefully easy question for you -- I saw in genetics-pipe that all of the inputs to the pipeline come directly from Google Storage, which I'm assuming is fairly straightforward to do given that the GCP Connector for Spark is already installed on Dataproc clusters.  How do you test those pipelines outside of GCP though?  In other words, have you gone through the process of installing the GCP Connector yourself in an on-premise environment?

I was asking because I'm trying to determine what the best way is to parallelize computations on the public GS files, namely the evidence files, used by data_pipeline now.  I could of course download / uncompress / partition them outside of Spark, or use Spark to parallelize the download, but that's certainly wasteful if it's possible to process the streams directly -- and also silly for organizations that might want to run the pipeline using GS as their underlying file system anyhow.  On the other hand, streaming the data directly over HTTP into RDDs or Dataframes seems impossible with Spark outside of some ugly hacks (or possibly using SparkStreaming).  That seems to leave the GCP Connector as the best option, and realistically probably the only option for non-public GS files, but I'm angling for ways that might let others run the pipeline without OAuth authentication via a GCP account (which the connector would require even to access public files if I'm not mistaken).  Let me know if you have any thoughts/advice on the topic.

Thanks!

**Comment by mkarmona** [comment]
@eric-czech thanks for your questions! Regarding genetics-pipe, it makes use of all files from GCS. We offer some buckets as paywalled so you can copy to your bucket and then work from there. If you rather prefer getting the whole data then you can download freely from the [public FTP from EMBL-EBI](ftp://ftp.ebi.ac.uk/pub/databases/opentargets/) 
Trying to answer your second question, the Platform data we offer is not fully prepared for straight use. Using GZip as compressor stops you to use it directly. Maybe LZO could be a better compressor as it is splittable when compressed or just offer uncompressed as I don't think is big enough these days but something to discuss what could be the best approach. 
Internally, we consume them uncompressed but reviewing this process could help us to be more publicly usable. Offering GCS and FTP we think is something flexible enough to cover most of the use cases but, again, the GZIP compressed files as they are not splittable could be a potential problem as you well said, we need to uncompress them before going Spark. 
Regarding Spark better to use uncompressed files as it will be read in blocks and shuffled if you directly use compressed files (gzipped) you might want to repartition straight from reading to optimise parallelisation. We currently use them already uncompressed internally.
Being a bit more explicit regarding spark and compressed raw data source files (in the case you don't want to uncompress first) what I would be doing is 

1. load all files by string glob 
2. and `repartition()` them; by default I think is _200 or 300_

Also, I would like to bring here what we think is interesting too. The way you put the data out and offer not just to us but for the public in general
3 and perhaps I might want to do at the end when finished and before write something like this `.write.partitionBy("release", "datasource").json(...)` so your data lake will be in a shape for post-processing and being orthogonal with releases and datasources or datatypes instead as some datasources are relatively small except for EPMC.

I hope this helps as a starting point for further discussion. Therefore, @eric-czech do you have any initial proposal? just to clarify the data steps for evidences

`raw evidences (RE) -> process evidence action -> processed and scored evidences (PE)`

So the problem you mentioned before (RE) I agree it could be better and also (PE) which I personally consider a bit more important for us and for public use

**Comment by eric-czech** [comment]
Thanks @mkarmona ,

I get that the gzip files will all be read individually on one worker since they can't be split, so I didn't have any plans to try to work around that other than distributing the reading of the files for each source.  What I'm stuck on though is how do you do the "load all files by string glob" part?  I can't just point spark at the http links (or gs:// links unless running it on Dataproc) and downloading the files first outside of spark is ugly since they're already in a distributed FS.  Basically, how do I read them directly from GCP?  

Were you ever able to test genetics-pipe outside of Dataproc while still reading the input files from GS?

**Comment by eric-czech** [comment]
Hey @mkarmona ,

As far as an initial proposal goes, here are some of my thoughts after spending more time understanding genetics-pipe as well as data_pipeline, and beginning to work through some of the raw evidence processing:

- In general, I was adopting the large majority of the practices in genetics-pipe and not veering too far from that style, namely via:
   - pureconfig over HOCON config files
   - scopt for CLI apps
   - logback for logging
   - enumeratum for enums
   - using typed Datasets where reasonable, DataFrames otherwise
- The style aside, I was assuming it makes to keep the same relative decomposition of the different steps with the assumption that these things may all make sense to run independently:
   - A pipeline that builds a dataset like the gene data index (as well as other auxiliary datasets for EFO, ECO, reactome, etc.)
   - A pipeline that merges gene data with raw evidence, with identifier normalization and record "fixing"
   - A pipeline that does the actual scoring
- As for frameworks, I looked at a few and this was my take on them -- let me know if you disagree or have explored any of them more:
  - [frameless](https://github.com/typelevel/frameless) - I thought this could be an interesting way to introduce further type safety, though I think it's impractical in the context of big hairy structs like much of this data is
  - [metorikku](https://github.com/YotpoLtd/metorikku) - I was playing around with this after you mentioned it and I like the idea but had a hard time bringing myself to think committing to SQL rather than the Scala API makes sense.  I like being able to introduce type safety judiciously like you guys did in genetics-pipe via the Scala API, and using custom jars as a means of avoiding SQL for each metorikku step, seemed pretty onerous.  Were there any particular advantages of that you saw beyond being able to express the pipeline as a configuration rather than code?
   - [sparkplug](https://github.com/springnz/sparkplug) - This was an interesting idea for [creating composable pipelines with Spark](https://www.stephenzoio.com/creating-composable-data-pipelines-spark/).  The library itself appears abandoned but I thought defining pipelines in a way they can be operated on programmatically is a good one (so I borrowed some of the ideas).

Overall, my initial proposal is essentially to redo data_pipeline with an implementation closely matching genetics-pipe.  The only improvements I have found useful are:
1. Doing much of the development/exploration/test generation with [almond](https://almond.sh/) (for ammonite within jupyter) notebooks rather than straight ammonite scripts 
2. Building the pipelines using a Functor ([example](https://github.com/related-sciences/ot-scoring/blob/master/src/main/scala/com/relatedsciences/opentargets/etl/pipeline/ScoringCalculationPipeline.scala#L144)) that makes it possible to inject logic to do things like log messages, grab result sizes, print schemas, compute summaries, etc without having to put this into the main flow of the program since those are often unwanted actions in production.  It also makes it possible to string pipelines together (in the spirit of sparkplug) and the application.conf would dictate which, if any, of those "decorating" behaviors are enabled.  I think that borders on adding "framework-y" features that other ETL libraries undoubtably have, but I don't know what they are for Scala/Spark (and it only takes a dozen or so lines of code to do it).

I'll stop there and I think that proposal may be a bit down in the weeds, but on a higher level I don't actually have much to say about the scope of all of this since data_pipeline makes what needs to be done pretty clear, and genetics-pipe gives me a lot to go in terms of how to do it.  Let me know if you have any concerns/suggestions or if you think there are other important features that need to be worked in (e.g. scoring configurations specific to users and private data).

Thanks Miguel!
