### ISSUE TITLE
Inaccurate condition in drugs against side effects of cancer treatments

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#791]
An IDG member reported that the the evidence we have for the [association between HTR2A and cancer based on ChEMBL data](https://www.targetvalidation.org/evidence/ENSG00000102468/EFO_0000311?view=sec:known_drug) is inaccurate. The issue is caused by "cancer" being the condition reported in clinical trials for drugs used to reduce the side effects of cancer treatments. 

The table below lists the clinical trials that affect drugs targeting HTR2A:

| Clinical_Trial | Drug | Reported_Condition | Expected_condition |
| --- | --- | --- | --- |
| [NCT03137121](https://clinicaltrials.gov/ct2/show/NCT03137121) | "Olanzapine" | "Advanced Cancer" | "chronic nausea and/or vomiting unrelated to chemotherapy or radiation" |
| [NCT02400866](https://clinicaltrials.gov/ct2/show/NCT02400866) | "Olanzapine" | "Cancer" | "chemotherapy-induced nausea and vomiting" |
| [NCT02635984](https://clinicaltrials.gov/ct2/show/NCT02635984) | "Olanzapine" | "Hematologic Neoplasms" | "chemotherapy-induced nausea and vomiting" |
| [NCT02861859](https://clinicaltrials.gov/ct2/show/NCT02861859) | "Olanzapine" | "Breast Cancer" | "chemotherapy-induced nausea and vomiting" |
| [NCT03079219](https://clinicaltrials.gov/ct2/show/NCT03079219) | "Olanzapine" | "Breast Cancer" | "chemotherapy-induced nausea and vomiting" |
| [NCT03367572](https://clinicaltrials.gov/ct2/show/NCT03367572) | "Olanzapine" | "Breast Carcinoma" | "chemotherapy-induced nausea and vomiting" |
| [NCT00832520](https://clinicaltrials.gov/ct2/show/NCT00832520) | "Mirtazapine" | "Advanced Cancer" | "weight loss" |
| [NCT02336750](https://clinicaltrials.gov/ct2/show/NCT02336750) | "Mirtazapine" | "Breast Cancer" | "Delayed Emesis" |
| [NCT01598584](https://clinicaltrials.gov/ct2/show/NCT01598584) | "Mirtazapine" | "Pancreatic Cancer" | "Anxiety, depression and weight loss" |
| [NCT01949662](https://clinicaltrials.gov/ct2/show/NCT01949662) | "Haloperidol decanoate" | "Advanced Cancer" | "Delirium" |

Note that the last column (`Expected_condition`) has been manually filled based on the information in the clinicalTrials.gov website and it does not necessarily correspond to the EFO term that Open Targets would need. In addition, this only contains drugs targeting HTR2A but there may be others affected.

This issue has been discussed with ChEMBL, who will manually fix their data for the next release and it has also been reported to clinicalTrials.gov asking them to update the records with the correct condition.

**Comment by AsierGonzalez** [comment]
clinicaltrials.gov have responded that the clinical trials information is the responsibility of the sponsors/submitters, so changing the original data would be hard work if not impossible. Therefore, the solution will be for ChEMBL to fix the issues we identify.

**Comment by AsierGonzalez** [comment]
These cases should be fixed in the next release, I leave the ticket open until we receive the next ChEMBL submission to check that it's fixed

**Comment by d0choa** [comment]
The issue is still there in the 20.02 data submission

**Comment by AsierGonzalez** [comment]
This issue has been resolved in 20.02 but there might be many other unknown similar cases lurking. It is a problem we should keep an eye on in the future. For now we will solve the issues reported by users.
