### ISSUE TITLE
Web app build instructions are incomplete / out of date

### ISSUE THREAD

**Issue by Docproc** [opentargets/platform#792]
The README for the web app at https://github.com/opentargets/webapp is not sufficient to build a working version of the web app on a non-Netlify platform. Specific versions of tools such as yarn, npm etc are required but not documented.

**Comment by Docproc** [comment]
The above PR should address this issue.

**Comment by LucaFumis** [comment]
I unintentionally closed this when merging I believe. Please reopen if documentation is still work in progress.
