### ISSUE TITLE
Update logic that generates HTML <link rel="canonical" ...> meta tag

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#793]
Currently, the [controllers.js file](https://github.com/opentargets/webapp/blob/master/app/src/js/controllers.js) is responsible for setting the `<link rel="canonical href="...">` metatag.

However, there are cases where the `href` value that is set is incorrect. For example, on [the drug profile page for Mitoxantrone](https://www.targetvalidation.org/summary?drug=CHEMBL58), the `href` value is set to `https://www.targetvalidation.org/summary` instead of `https://www.targetvalidation.org/summary?drug=CHEMBL58`.

![Screenshot 2019-12-09 at 17 01 03](https://user-images.githubusercontent.com/7490258/70456175-86b29d00-1aa5-11ea-9b03-7d7a97179cbc.png)

Is it possible to update the logic so that the `href` set for drug profile pages includes the CHEMBL id? For example, the `href` tag on the Mitoxantrone profile page would be:

`<link rel="canonical" ng-href="https://www.targetvalidation.org/summary?drug=CHEMBL58" href="https://www.targetvalidation.org/summary?drug=CHEMBL58">`

@d0choa, although this is work for the existing Angular app and we want to spend as much as time as possible on the React rewrite for a Q1 beta release, I would recommend that we include this in our 20.02 release. Because the `href` that is currently set on drug profile pages - `https://www.targetvalidation.org/summary` - is technically a valid page that returns a 200 success response code and a blank page, search engines are likely to penalise us for having what they call ["soft 404s"](https://support.google.com/webmasters/answer/181708?hl=en) and they might also set the canonical version of these pages to be something entirely unrelated.

**Comment by d0choa** [comment]
As discussed in FE meeting today, this is part of a much bigger analysis on our SEO. @andrewhercules will look into this in more detail and create the appropriate actions
