### ISSUE TITLE
Missing Gene Ontology annotations for noncoding RNA (Obtain from QuickGO or RNA central) 

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#794]
We are missing GO annotations to RNA 

2 good sources of RNA GO annotations are 
1- The EBI maintained QuickGO website (https://www.ebi.ac.uk/QuickGO/)
2- RNAcentral (https://rnacentral.org/). 

An example being Malat1 where 
The Open Targets Platform has an entry for MALAT1 and no available GO annotations in the platform (https://www.targetvalidation.org/target/ENSG00000251562). 
2- UniProt does not have it as entry (rightly so since it is not a protein) 
3- Ensembl has the entry but no GO annotations (https://www.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000251562;r=11:65497688-65506516) 
4- RNAcentral has both the entry AND GO annotations (https://rnacentral.org/rna/URS0000A77400/9606)
5- EBI QuickGO website has the entry and the GO annotations (https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=URS0000A77400_9606).

Wold it be possible to use the EBI QuickGO API to get these annotations?

**Comment by d0choa** [comment]
Positive enhancement on the annotation of RNA targets. We'll eventually allocate appropriate resources. Not a short term priority unfortunately.

**Comment by d0choa** [comment]
Closing as captured as part of a bigger task to revamp the GO annotation data feed #1037
