### ISSUE TITLE
New TEPs (target enabling packages) not yet in our Platform

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#80]
While preparing some training materials, I realised a few additional genes have got a TEP (according to https://www.thesgc.org/tep) but this information does not seem to have been updated in the index files for the corresponding target profile page. These are the 3 genes that have been updated in 2018:

* RIPK2: https://www.targetvalidation.org/target/ENSG00000104312
* HAO1: https://www.targetvalidation.org/target/ENSG00000101323
* FAM83B: https://www.targetvalidation.org/target/ENSG00000168143

It'd be useful to check when a new TEP gets updated on the SGC side, so that we automatically fetch that information and display in in the Open Targets Platform.

**Comment by iandunham** [comment]
@luca Can you add to 
https://github.com/opentargets/webapp/blob/893fcb951caaf312d86447f952e66256fd9c537d/app/src/services/teps-service.js ?

**Comment by iandunham** [comment]
We don't have an automated way to do this because it would involve scraping their pages, and the number is low

**Comment by MichaelaEBI** [comment]
My plan is to start checking the SGC Chemical Probes page before each release and we can include a check for new TEPs.

**Comment by LucaFumis** [comment]
This is fixed in master and will go in the upcoming 3.8 release; close after new release QA.
