### ISSUE TITLE
Incorrect gene symbol suggestion for MLL

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#803]
Both the platform search and the batch search suggest that `MLL` is `SEPTIN9` when based [on the synonyms](https://www.targetvalidation.org/target/ENSG00000118058) and [HGNC](https://www.genenames.org/tools/search/#!/all?query=mll) it seems it should be `KMT2A`. According to @mkarmona, "it seems search is not working properly. it should weight more synonyms as MLL is one of those. the moment search match MLL it should return the canonical id and therefore the target object for that id"

**Comment by d0choa** [comment]
It's important to get it right in the new search API. This is the current result. 

![Screenshot 2020-01-09 at 14 09 12](https://user-images.githubusercontent.com/5097586/72074723-58192380-32ea-11ea-8283-2a8fa9270f2c.png)

Thanks to @mirandaio for the screenshot

**Comment by mkarmona** [comment]
@d0choa @AsierGonzalez this is something that is fixed for the rewrite

**Comment by d0choa** [comment]
It's not a priority to enhance search in the angular app, so I consider this sorted.
