### ISSUE TITLE
target.csv files are corrupted in 19.09 and 19.11 downloads page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#805]
Since 19.09 we provide two additional files in the Downloads page (in addition to evidence and association JSON files). These are disease.csv and target.csv.

Target.csv is corrupted is both 19.09 and 19.11 and it can't be opened.

<img width="403" alt="Screen Shot 2020-01-14 at 17 10 13" src="https://user-images.githubusercontent.com/6472381/72366364-07db0080-36f2-11ea-87a2-f2942fe723f9.png">

<img width="382" alt="Screen Shot 2020-01-14 at 17 20 02" src="https://user-images.githubusercontent.com/6472381/72366406-1fb28480-36f2-11ea-82e7-d9db3bd8b9c6.png">

**Comment by d0choa** [comment]
I can confirm the files are not corrupted.

Depending on your browser/OS the files might be download in different ways. For instance, Safari downloads and uncompresses the files automatically, whereas Chrome downloads the file but doesn't uncompress it.

When you use the `Archive Utility` to uncompress the `.gz` file in macOS Catalina it throws the above error. However, it works in previous macOS versions. If you use `gunzip` in the command line it uncompresses correctly independently of the OS. As a short term solutions, free tools such as `The Unarchiver` work fine. 

In the long term, we need to find out why our `.gz` are no longer compatible with this tool. @cmalangone is our gzip compression particularly old fashioned in any way?

**Comment by d0choa** [comment]
@mkarmona reports the files have no issue and points to a problem with the `Archive Utility`.

**Comment by mkarmona** [comment]
this command works `zcat 19.11_target_list.csv | csvcut -H -c a | less` and I can see the output

![Captura de pantalla de 2020-01-28 18-01-42](https://user-images.githubusercontent.com/5394232/73291761-bace5280-41f8-11ea-80fa-a2482bab8ee3.png)
