### ISSUE TITLE
README or column header for disease.csv in the downloads page?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#806]
One user has inquired what the columns mean in the diseases.csv file. 

From the JSON file (disease.json), we can deduct that the 3 columns mean:

* EFO ID
*  Disease full name
*  Number of associations

Can we add this information somewhere to the csv file or elsewhere. 

Worth considering this in the rewrite for the Data Downloads page, assuming it will be different from what it is now.

**Comment by d0choa** [comment]
Related to #774

**Comment by cmalangone** [comment]
The CSV dumps contain the header
echo '"ensembl_id","hgnc_approved_symbol","uniprot_accessions","number_of_associations"' > 20.02_target_list.csv
cat 20.02.1-search-data.json | jq -r 'select(.type=="target") | [.id, .approved_symbol, [.uniprot_accessions | join("|")][], .association_counts.total] | @csv' >> 20.02_target_list.csv
cat 20.02.1-search-data.json | jq -r 'select(.type=="target") | {"ensembl_id": .id, "hgnc_approved_symbol": .approved_symbol, "uniprot_accessions": .uniprot_accessions, "number_of_associations": .association_counts.total}' > 20.02_target_list.json

echo '"efo_id","disease_full_name","number_of_associations"' > 20.02_disease_list.csv
cat 20.02.1-search-data.json | jq -r 'select(.type=="disease") | [.id, .full_name, .association_counts.total] | @csv' >> 20.02_disease_list.csv
cat 20.02.1-search-data.json | jq -c 'select(.type=="disease") | {"efo_id": .id, "disease_full_name": .full_name, "number_of_associations": .association_counts.total}' > 20.02_disease_list.json
