### ISSUE TITLE
Infer new T<->T relationship from PPI and/or receptor-ligand relationships

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#81]
@elipapa commented on [Tue Jan 10 2017](https://github.com/opentargets/roadmap/issues/24)

intact as data source?

**Comment by ElaineMcA** [comment]
Already listed on central data backlog list for investigation/consideration for inclusion in platform.

**Comment by MichaelaEBI** [comment]
This is happening with the [Network Project OTAR044](http://home.opentargets.org/OTAR044). Closing this ticket because we have tickets with specific tasks for this.
