### ISSUE TITLE
Review COSMIC evidence

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#811]
The maximum value of the association score of COSMIC and other somatic_mutation datasources is ~ 0.55 even when the evidence score is 1:

![image](https://user-images.githubusercontent.com/11410715/72734726-3b0a0d80-3b92-11ea-846b-420a672ff414.png)

This is caused by the normalisation of a frequency value calculated from the evidence strings (f) that converts f=1 into 0.55, that is, _normalisation(1) = 0.55_. The frequency takes a value between 0 and 1 and it can only be calculated based on the evidence for COSMIC. It is always set to 1 for IntOGen, EVA and UniProt.

It is clear that the normalisation function is the cause of the issue, the question is whether it should be simply corrected so that _normalisation(1) = 0.55_, if frequency values should be calculated in a different way of if it should be scrapped altogether for somatic mutation evidence.

**Comment by AsierGonzalez** [comment]
Arguments in favour of removing the frequency normalisation (by @d0choa):

> With regard to COSMIC, we generate evidence for every target, disease and mutation type (e.g. gene fusion, missense variant, etc.). The way we score evidence is by taking the score they generate based on the tier system of the curation effort. This is pretty much a discretized number (e.g. 0.25, 0.5, 0.75) that takes into account the mutational pattern and the functional consequence (e.g. missense variant). We take that and we multiply it by a normalised frequency number. The way the frequency is currently calculated is by dividing the number of samples with the given target, disease, mutation_type by the number of samples with target, disease and any mutation type. In a sense, the frequency is capturing how relevant is this mutation type compared to other mutation types in the same target in the context of the same disease. The implementation has a few shortcomings but I’m also concerned about the principle. I would understand the frequency to be about the count of this mutation type in this target, divided by the total number of samples on this cancer. However, I also think that in principle, the COSMIC evidence should not be about mutation frequency. If there is a significant curation effort and they agree on some driver mutations, we should respect that and not use any approach based on frequency on top. We could then have other datasources such as IntoGen that use a more statistical approach on calling the cancer driver genes

**Comment by AsierGonzalez** [comment]
Arguments in favour of keeping the frequency normalisation (by @iandunham):

> That is broadly the principle, although my understanding was that it should be the number of samples with the given target, disease, mutation_type by the number of samples with disease and any mutation type.  Such a frequency approach is, I think, valid because it represents how often this target is a driver in a particular cancer type. Although Cosmic curate driver genes, these can be quite rare within a cancer type and still be called a driver. The frequency part is to correct by how relevant the target is across that cancer type. In effect we are splitting the score based on a breakdown of the cancer phenotype using molecular biomarkers.[...]

**Comment by AsierGonzalez** [comment]
COSMIC/CGC scoring explained by Zbyslaw:

> Two Poisson tests are performed: 1) if mutations in a gene occur more frequently compared to all other genes in the same disease; 2) if a gene is mutated significantly more frequently in particular disease compared to all other diseases. Positive results indicate frequency higher than expected.

A base association score 0.5 is given to all mutations detected in the Cancer Gene Census Genes

• A significant result of each of the two tests (fdr < 0.025) adds 0.25 to the score. E.g. one test positive => score = 0.75, two tests positive => score = 1

• If the gene belongs to Tier 2, score = 0.5 regardless of test results

• If the gene is known to drive cancer only through fusions, all mutation types except fusions get the score of 0.5; fusions are scored according to the rules above

• If there’s only 1 sample mutated 0.25 is subtracted from the score

**Comment by d0choa** [comment]
For reference, last update of COSMIC evidence was done in #707

**Comment by AsierGonzalez** [comment]
An updated file with the evidence at the gene-disease level was received on 17th Feb. The file looks good but the pipeline was not re-run after this, so this change will be visible in the next release. The new format may require changes to the FE, @d0choa you may want to double-cehck this.

The scoring has now been fixed and the COSMIC score is now used as is.
