### ISSUE TITLE
activity URL in evidence page leading to a deprecated page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#812]
In the [Crohn’s disease-NOS2 evidence](https://www.targetvalidation.org/evidence/ENSG00000007171/EFO_0000384) page, under RNA expression, when filtering to see evidence from "RNA-Seq data only", we get this table where the hyperlinked "increased" leads to a deprecated page.

![Screen Shot 2020-01-21 at 11 57 12](https://user-images.githubusercontent.com/6472381/72804288-0193d980-3c48-11ea-85d5-012b87516f81.png)

Initially I though the issue is because RNASeq wouldn’t be on ArrayExpress, only microarray experiments being deposited there, not sequencing data. But that does not seem to be the case judging from the ArrayExpression [About](https://www.ebi.ac.uk/arrayexpress/about.html) page.

And this is the proof of the pudding: "increased" activity in the [evidence for S100A9 in schizophrenia
](https://www.targetvalidation.org/evidence/ENSG00000163220/EFO_0000692?view=sec:rna_expression) leads to a [working page in ArrayExpress](https://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-78936/).

**Comment by deniseOme** [comment]
According to @AsierGonzalez some RNA-seq experiments may not have an ArrayExpress page. That'd explain the deprecated page.

![Screen Shot 2020-01-21 at 13 17 39](https://user-images.githubusercontent.com/6472381/72807968-7408b780-3c50-11ea-9708-fe4a0b0e11e9.png)

At least we know the reason for the observed behaviour if users come across this as well.

**Comment by deniseOme** [comment]
on the same evidence page, as I user I’d expect the “Experiment overview and data" column to take me to different pages in Expression Atlas rather than taking me to the same page regardless the experiment used as evidence i.e. it takes us to the gene page in Expression Atlas.

For the Crohn's-NOS2 example above the hyperlinked sentence "RNA-seq of 359 treatment-naive pediatric patients with Crohn's disease, patients with ulcerative colitis and control individuals" should take us to https://www.ebi.ac.uk/gxa/experiments/E-GEOD-57945/ rather than the gene page for NOS2 (https://www.ebi.ac.uk/gxa/genes/ENSG00000007171)

**Comment by AsierGonzalez** [comment]
The links in the "Activity" and "Experiment overview and data" columns are built using the urls in the evidence section of the API response. For example, for the [ENSG00000007171-EFO_0000384 association](https://platform-api.opentargets.io/v3/platform/public/evidence/filter?size=1000&datasource=expression_atlas&fields=disease&fields=evidence&fields=target&fields=access_level&target=ENSG00000007171&disease=EFO_0000384&view=rnaexpression&expandefo=true):
```
[
  {
    "nice_name": "ArrayExpress Experiment overview",
    "url": "http://identifiers.org/arrayexpress/E-GEOD-57945"
  },
  {
    "nice_name": "Gene expression in Expression Atlas",
    "url": "http://www.ebi.ac.uk/gxa/experiments/E-GEOD-57945?geneQuery=ENSG00000007171"
  },
  {
    "nice_name": "Baseline gene expression in Expression Atlas",
    "url": "http://www.ebi.ac.uk/gxa/genes/ENSG00000007171"
  }
]
```
@d0choa, @LucaFumis and I looked into this issue and we found two independent problems, one related to the data and one related to the way linkout URLs are built by the webapp:

- Linking to a deprecated page is a data issue. As @deniseOme mentioned, not all the Atlas experiment have a correcponding ArrayExpress page. According to ArrayExpress, they stopped importing GEO experiments, whereas GXA selectively import them. Therefore, the only studies that have corresponding ArrayExpress entries for sure are the `E-MTAB` ones. To avoid this issue we should either link to the GXA [Experiment Design](https://www.ebi.ac.uk/gxa/experiments/E-GEOD-57945/Experiment%20Design) or [Supplementary Information](https://www.ebi.ac.uk/gxa/experiments/E-GEOD-57945/Supplementary%20Information) pages. We only need the GXA study id for this, so we would not need any changes to the data really (although removing the links to ArrayExpress sounds reasonable).

- The other problem is that the "Activity" column links to ArrayExpress whereas the "Experiment overview and data" links to the gene baseline expression page, which does not make sense. In theory. The "Experiment overview and data" should link to one of the two pages mentioned above whereas "Activity" should link to the "Gene expression in Expression Atlas" url in the API response. The web app builds the[ "Activity" url using the first item in the urls array](https://github.com/opentargets/webapp/blob/master/app/src/components/rna-expression-table/rna-expression-table-directive.js#L101), whereas the ["Gene expression in Expression Atlas"  url is built using the third value](https://github.com/opentargets/webapp/blob/master/app/src/components/rna-expression-table/rna-expression-table-directive.js#L121). @LucaFumis will change the webapp logic to use the right fields.

**Comment by richardbrunt-tessella** [comment]
The fix for this is causing an exception on the RNA Expression table of our private deployment, as our evidence sources don't return any items from the filter. I'll submit a PR that addresses this to fix it for us as well.
