### ISSUE TITLE
Implement pagination in the Pharmacovigilance section

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#814]
For some drugs (e.g. [Rofecoxib](https://platform-app.netlify.com/drug/CHEMBL122), [Pembrolizumab](https://platform-app.netlify.com/drug/CHEMBL3137343), [Metformin](https://platform-app.netlify.com/drug/CHEMBL1431), etc.), there are more than 20 entries in the Pharmacovigilance section data table.

![Screenshot 2020-01-23 at 15 45 00](https://user-images.githubusercontent.com/7490258/72999477-56298700-3df7-11ea-9010-301f7f24ba59.png)

In the React rewrite, could we please implement a paginated table, similar to the data table used in the Drugs section in the target and disease profile pages?

**Comment by d0choa** [comment]
Closing as duplicated in #936
