### ISSUE TITLE
Genetics Portal evidence into Platform

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#815]
**Aim**: to import evidence from the OpenTargets Genetics Portal into the OpenTargets Platform

**Context**: With the recent inclusion of the locus-2-gene (L2G) score, the genetics portal provides now a link to the most likely causal targets for a particular GWAS signal. The L2G score bridges the gap necessary to build OT platform evidence for target-disease prioritisation by combining multiple features using ML. 

**Specification**: @DSuveges has undergone a deep analysis on the implications of taking different decisions on the evidence generation and scoring. A deep summary can be found in this [report](https://docs.google.com/document/d/1v364IIWYiMmXXVV4JuNozZwPb-Xgb5faiQMpmqr1sTc/edit?usp=sharing) and [results](https://docs.google.com/spreadsheets/d/1G7XyzSgprJ6onwMiH1veSWS0BjZdeKbcxAjuYNcToxE/edit?usp=sharing).

- A new datasource for the Genetics Portal will be created using the current GWAS threshold (p-value < 5 * 10-8). As all GWAS Catalog studies are now going through the feeding through the Genetics Portal they will be removed. ~40k evidence we'll not make it to the new feed because of the more stringent p-value threshold 5e-8 instead of 1e-5.

- In the Genetics Portal feed, we will expand complex traits to multiple EFOs as GWAS catalog currently.

- All potential causal genes are passed as evidence. All l2g scores are used with no threshold.

- For scoring, we use the L2G score for simplicity.
 
- Genetics Portal evidence will be generated in a format compatible with the GWAS catalog.

**Comment by hammer** [comment]
@d0choa :wave: let us know if we can help cc @eric-czech
