### ISSUE TITLE
Create Genetics Portal evidence file

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#817]
The new evidence requirements:
- definition described in the Epic ([#815](https://github.com/opentargets/platform/issues/815))
- compatible with previous GWAS catalog evidence
- provide necessary fields for FE ([#816](https://github.com/opentargets/platform/issues/816))

Code to be developed in [evidence_datasource_parsers](https://github.com/opentargets/evidence_datasource_parsers) repo

A random example of a GWAScatalog evidence can be found next

>  {
  "target": {
    "activity": "http://identifiers.org/cttv.activity/predicted_damaging",
    "id": "http://identifiers.org/ensembl/ENSG00000133048",
    "target_type": "http://identifiers.org/cttv.target/gene_evidence"
  },
  "access_level": "public",
  "sourceID": "gwas_catalog",
  "variant": {
    "type": "snp single",
    "id": "http://identifiers.org/dbsnp/rs4950928"
  },
  "disease": {
    "id": "http://www.ebi.ac.uk/efo/EFO_0004869"
  },
  "unique_association_fields": {
    "pubmed_refs": "http://europepmc.org/abstract/MED/18403759",
    "target": "http://identifiers.org/ensembl/ENSG00000133048",
    "disease_id": "http://www.ebi.ac.uk/efo/EFO_0004869",
    "variant": "http://identifiers.org/dbsnp/rs4950928",
    "study_name": "GCST000177",
    "pvalue_annotation": " "
  },
  "evidence": {
    "variant2disease": {
      "gwas_sample_size": 1772,
      "unique_experiment_reference": "http://europepmc.org/abstract/MED/18403759",
      "gwas_panel_resolution": 290325,
      "provenance_type": {
        "literature": {
          "references": [
            {
              "lit_id": "http://europepmc.org/abstract/MED/18403759"
            }
          ]
        },
        "expert": {
          "status": true,
          "statement": "Primary submitter of data"
        },
        "database": {
          "version": "2020-00-21T02:13:36+00:00",
          "id": "GWAS Catalog",
          "dbxref": {
            "version": "2020-00-21T02:13:36+00:00",
            "id": "http://identifiers.org/gwas_catalog"
          }
        }
      },
      "is_associated": true,
      "resource_score": {
        "type": "pvalue",
        "method": {
          "description": "pvalue for the snp to disease association."
        },
        "value": 1e-13,
        "mantissa": 1,
        "exponent": -13
      },
      "evidence_codes": [
        "http://identifiers.org/eco/GWAS",
        "http://purl.obolibrary.org/obo/ECO_0000205"
      ],
      "date_asserted": "2020-00-21T02:13:36+00:00",
      "confidence_interval": "NR",
      "odds_ratio": ""
    },
    "gene2variant": {
      "provenance_type": {
        "expert": {
          "status": true,
          "statement": "Primary submitter of data"
        },
        "database": {
          "version": "2020-00-21T02:13:36+00:00",
          "id": "GWAS Catalog",
          "dbxref": {
            "version": "2020-00-21T02:13:36+00:00",
            "id": "http://identifiers.org/gwas_catalog"
          }
        }
      },
      "is_associated": true,
      "date_asserted": "2020-00-21T02:13:36+00:00",
      "evidence_codes": [
        "http://purl.obolibrary.org/obo/ECO_0000205",
        "http://identifiers.org/eco/cttv_mapping_pipeline"
      ],
      "functional_consequence": "http://purl.obolibrary.org/obo/SO_0001631"
    }
  },
  "validated_against_schema_version": "1.6.3",
  "type": "genetic_association",
  "literature": {
    "references": [
      {
        "lit_id": "http://europepmc.org/abstract/MED/18403759"
      }
    ]
  }
}

**Comment by d0choa** [comment]
Keep in mind the evidence_datasources_repo is using an old EFO file (#576). Although, not relevant for this task, we will need to eventually update it.

**Comment by DSuveges** [comment]
I have a prototype for the genetics platform evidence string. You can take a look at it here: [link](https://jsoneditoronline.org/?id=80128fe932704e058721999144dfd408)

I tried to follow the convention of the gwas catalog evidences, with respect to #815 and #816.

**What is different:**

* Publication link contains publication year and author.
* For non-GWAS Catalog studies, the values for these keys are `null`
* L2G score is added to evidence.gene2variant.resource_score property
* both the EFO ID and reported trait is added.
* As a consequence the the most severe consequence for the target gene is listed. This value can be vound here: `evidence.gene2variant.functional_consequence`
*  `evidence.gene2variant.consequence_link` points to the relevant sequence ontology term.
* The `variant.type` is inferred from the alleles. Available values: `SNP`, `insertion`, `deletion`
* The `variant.type_link` points to the proper sequence ontology term.
* Unique fields: `target`, `study`, `disease`, `variant`
* `evidence.variant2disease` property contains study level information as well: sample size, trait (both EFO id and reported trait)
* `evidence.variant2disease.resource_score` contains p-value of the GWAS association split into mantissa and exponent. 

A small set 1000 such evidence strings are attached.
