### ISSUE TITLE
Use ANACONDA_INSTALL_DIR

### ISSUE THREAD

**Issue by hammer** [opentargets/platform#828]
`EnsemblResource.py` calls out to `conda` in several places using both a hard-coded path and one from `config.yaml`. Conda defines an environment variable `ANACONDA_INSTALL_DIR` for the purpose of finding conda-related files. We should consider using it.

**Comment by cmalangone** [comment]
This ticket is obsolete.
The step ensembl uses a module for the version conda3 - python3

**Comment by cmalangone** [comment]
Moved to anaconda 3
