### ISSUE TITLE
EFO problem with orphanet diseases: symptoms as parent-child 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#838]
EFO3 has currently an issue regarding the Orphanet diseases being children of other terms due to symptoms.
SPOT team has been working in resolving this issue that requires coordination with MONDO since last November.

Once this is resolved on their side, no action will be required in our side

**Comment by smnorthen** [comment]
The current plan is to start with obsolete Orphanet terms which are still in EFO and to replace them with an existing Mondo term. If a Mondo term does not exist then a new EFO term will be created. 

In addition, Orphanet disease terms which have the word 'rare' in the term label will be replaced with just the disease name (without 'rare' in the disease name) from Mondo. 

Anything else will be reviewed manually.

Will continue to update the ticket with how the work is progressing.

**Comment by d0choa** [comment]
Related task in MONDO:
https://github.com/monarch-initiative/mondo/issues/834

**Comment by paolaroncaglia** [comment]
Latest update: https://github.com/monarch-initiative/mondo/issues/834#issuecomment-595314262
cc @zoependlington

**Comment by d0choa** [comment]
@paolaroncaglia and @zoependlington continue meeting with MONDO regularly and approaching this problem branch by branch.

The improvements will propagate to us without any extra action but we'll keep this ticket open for a while in order to monitor the progress

**Comment by andrewhercules** [comment]
Work is ongoing - moved to 21.02 release to monitor progress

**Comment by d0choa** [comment]
I consider this an ongoing improvement of the ontology. Closing this on our side
