### ISSUE TITLE
MoA table of drugs without a MoA keeps loading

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#839]
It seems that if the array with the mechanism of action of a drug in the `drug` endpoint is an empty array the `Mechanisms of actio` table in the Open Targets drug page gives the impression of being loading data.

Drug page of [Ifosfamide](https://www.targetvalidation.org/summary?drug=CHEMBL1024):
<img width="1327" alt="Screenshot 2020-02-06 at 14 24 44" src="https://user-images.githubusercontent.com/11410715/73945928-fea61380-48ec-11ea-88b1-31a73e2a7a33.png">

API response for [Ifosfamide](https://platform-api.opentargets.io/v3/platform/private/drug/CHEMBL1024):
<img width="440" alt="Screenshot 2020-02-06 at 14 27 01" src="https://user-images.githubusercontent.com/11410715/73945949-08c81200-48ed-11ea-92b3-d5a1d8f5569d.png">

Drug page of [Amifostine](https://www.targetvalidation.org/summary?drug=CHEMBL1006):
<img width="1322" alt="Screenshot 2020-02-06 at 14 24 31" src="https://user-images.githubusercontent.com/11410715/73945989-17162e00-48ed-11ea-9b46-f1e00ae9bbaa.png">

API response for [Amifostine](https://platform-api.opentargets.io/v3/platform/private/drug/CHEMBL1006):
<img width="436" alt="Screenshot 2020-02-06 at 14 27 44" src="https://user-images.githubusercontent.com/11410715/73946004-1ed5d280-48ed-11ea-830d-91a9a7174c7e.png">

**Comment by d0choa** [comment]
Keeping this ticket just for reference but no action is expected in the angular app. The only way to get to this page is by knowing the url. This is sorted in the upcoming React rewrite. Thanks @AsierGonzalez for documenting it.
