### ISSUE TITLE
EFO_0000378 and Orphanet_94062 and EVA evidence

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#843]
We associate LRP6 (ENSG00000070018) with Orphanet_94062 (Coronary artery disease - hyperlipidemia - hypertension - diabetes - osteoporosis) but genetic evidence suggests this gene should be associated with EFO_0000378 (coronary artery disease) instead:

https://www.targetvalidation.org/evidence/ENSG00000070018/Orphanet_94062?view=sec:genetic_association

@AsierGonzalez has looked at this and the issue may be due the disease mapping via OMIM ID:
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_94062

These are the the ClinVar evidence linking CAD to LRP6:
http://www.ncbi.nlm.nih.gov/clinvar/RCV000006645
http://www.ncbi.nlm.nih.gov/clinvar/RCV000056293
http://www.ncbi.nlm.nih.gov/clinvar/RCV000056294
http://www.ncbi.nlm.nih.gov/clinvar/RCV000056292

On a slightly different note, note that ClinVar now seems to have other accessions for the variants above:

Old NCBI website | New NCBI website
------------ | -------------
https://www.ncbi.nlm.nih.gov/clinvar/RCV000006645/ | https://www.ncbi.nlm.nih.gov/clinvar/variation/6267/
https://www.ncbi.nlm.nih.gov/clinvar/RCV000056293/ | https://www.ncbi.nlm.nih.gov/clinvar/variation/66055/
https://www.ncbi.nlm.nih.gov/clinvar/RCV000056294/ | https://www.ncbi.nlm.nih.gov/clinvar/variation/66056/
https://www.ncbi.nlm.nih.gov/clinvar/RCV000056292/ | https://www.ncbi.nlm.nih.gov/clinvar/variation/66054/

And there is this new evidence https://www.ncbi.nlm.nih.gov/clinvar/variation/684469/
Although its clinical significance (interpretation) is not provided, it would be a 5th piece of evidence linking CAD to LRP6.

related to [#841](https://github.com/opentargets/platform/issues/841)

**Comment by AsierGonzalez** [comment]
To clarify, the association between LRP6 and Orphanet_94062 is supported by two data sources, EVA and UniProt. However, 8 of the 9 evidence strings are based on four variants (`rs397515473`, `rs397515474`, `rs121918313`, `rs141212743`) reported by both sources which seem to come from OMIM originally:
![image](https://user-images.githubusercontent.com/11410715/74674410-317fbf80-51a9-11ea-9e29-130f4ad72b67.png)

There are two different reasons why those variants are associated with that disease:

1) EVA: Zooma maps the string `Coronary artery disease, autosomal dominant 2` to Orphanet_94062 by default (analogous to #841) .

2) UniProt: The cross-references between EFO and OMIM map Orphanet_94062 to OMIM:610947 ( as explained by @deniseOme above)

There are two alternative ontology terms for this condition. One is the MONDO term [MONDO_0012586](http://purl.obolibrary.org/obo/MONDO_0012586) which is an exact match but is not in EFO. The other one is the more general EFO term [EFO_0000378]( http://www.ebi.ac.uk/efo/EFO_0000378) suggested by @deniseOme.

Whatever the mapping selected, two separated actions are required to fix this problem. I will ask EVA about `1` and EFO/SPOT about `2`.

**Comment by AsierGonzalez** [comment]
Regarding the 5th piece of evidence associating LRP6 and Orphanet_94062 (https://www.ncbi.nlm.nih.gov/clinvar/variation/684469/), as you suggest @deniseOme, it is not cosidered because it's clinical significance is not defined.

**Comment by AsierGonzalez** [comment]
EFO have corrected the xref, they have decided to import MONDO_0012586 and this term will be cross-referenced from there (see EFO issue [#712](https://github.com/EBISPOT/efo/issues/712) for more info). The next UniProt submission should pick up the correct term.

**Comment by AsierGonzalez** [comment]
EVA have added "Coronary artery disease, autosomal dominant 2" to their [list of problematic traits](https://docs.google.com/spreadsheets/d/1m4ld3y3Pfust5JSOJOX9ZmImRCKRGi-fGYj_dExoGj8/edit#gid=0) and they have manually mapped it to `EFO_0000378`.
Note that, for consistency with UniProt, the chosen EFO term should be `MONDO_0012586` in the next release.

**Comment by AsierGonzalez** [comment]
This has been fixed in the 20.06 EVA file
