### ISSUE TITLE
API changes in Reactome

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#844]
We got the next email from Reactome

> We are doing some changes in our Header (directly in Apache) and before we move to production we’d like to check with our partners if they are still accessing Reactome and its widgets.
> 
> I would to test the widget directly to our dev servers:
> Replace the server reactome.org by dev.reactome.org. 
> 
> <script type="text/javascript" language="javascript" src="https://dev.reactome.org/DiagramJs/diagram/diagram.nocache.js"></script>
> 
> My apologies if you are not in charge of the front-end, would you mind forwarding to the right person please?

We need to explore if this will cause any issues in our public or private instances

**Comment by d0choa** [comment]
@andrewhercules commented:

> In both the existing Angular app (index-tmpl.html) and new React app (index.html), could you ( @LucaFumis ) please update the src attribute of the relevant <script> tag and change to dev.reactome.org? So for example, src="https://dev.reactome.org/DiagramJs/diagram/diagram.nocache.js”. Could you then send me a deploy preview link to both versions so I can test various scenarios to ensure it still works?

**Comment by LucaFumis** [comment]
In regards to the Angular app is this something we want to include for 20.02 or 20.04? (rather than an urgent fix?)

**Comment by andrewhercules** [comment]
@LucaFumis, can you please revert the API call to their production version? Once done, we can close this ticket as Reactome has confirmed that they have what they need from our testing.
