### ISSUE TITLE
Platform GWAS from Genetics Portal (expanded data documentation)

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#846]
An expanded explanation on the steps to generate evidence and the datasource nature

- [x] gitbook documentation
- [x] evidence_datasource_parsers repo
- [x] respective section in the OT Datasources document https://docs.google.com/document/d/1jujcyOmRSlgT2kwm3DVhhCQ-tMNJDskOsqjV1HLwXTI/edit#heading=h.i9vahyscnzsz
- [x] Unique association fields [document](https://docs.google.com/spreadsheets/d/1yo2_cW__upXmQfQp1CiGwJqnO611WvzjBTTMH4-9JNI/edit#gid=0)

**Comment by DSuveges** [comment]
Once https://github.com/opentargets/evidence_datasource_parsers/pull/43 is merged, this ticket can be closed.
