### ISSUE TITLE
Intogen update documentation

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#847]
Additional information to document the changes will be required in:

- [x] OT Data Sources [document](https://docs.google.com/document/d/1jujcyOmRSlgT2kwm3DVhhCQ-tMNJDskOsqjV1HLwXTI/edit#heading=h.i9vahyscnzsz)
- [x] Unique association fields [document](https://docs.google.com/spreadsheets/d/1yo2_cW__upXmQfQp1CiGwJqnO611WvzjBTTMH4-9JNI/edit#gid=0)
- [x] Gitbook page
- [x] evidence_datasource_parsers repo

**Comment by AsierGonzalez** [comment]
All the above now contain up-to-date information
