### ISSUE TITLE
amend FAQ "How variants are assigned to genes"

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#854]
With the upcoming new data type (locus-to-gene from Open Targets Genetics, to replace GWAS Catalog evidence), we need to updated this [FAQ](https://docs.targetvalidation.org/faq/how-variants-are-assigned-to-genes).

Note the current FAQ still applies to other data sources. So we can subdivide this session into two: GWAS and non-GWAS or something alike…

**Comment by DSuveges** [comment]
I have prepared a draft for the new documentation you can find here: https://docs.google.com/document/d/10KLJdvLBK2-M6fkF20jtvX609M6z5UbxEQP1tTvezbk/edit

Please add comments and then I can update.

**Comment by DSuveges** [comment]
[Commit](https://github.com/opentargets/docs.targetvalidation.org/commit/a5372b5e9fb8f64f17a9d5b613240bf00fc316a0) merged into master.
