### ISSUE TITLE
ot_genetics_portal evidence missing evidence_codes_info

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#856]
The new evidence strings from the OT Genetics Portal  lack the `evidence.evidence_codes_info` field after being processed by the data pipeline. To be accurate, the field exists but its value is `null` instead of an array:
```
  "evidence": {
    "evidence_codes_info": null,
    "variant2disease": {
```
This is causing issues to the front-end and also to check-o-matic, which has one test that iterates through the expected array.

**Comment by DSuveges** [comment]
A commit is now pushed to this pull request: [#39](https://github.com/opentargets/evidence_datasource_parsers/pull/39)

Once this pull request is reviewed, and merged, this issue can be closed.

**Comment by d0choa** [comment]
Slightly related to #757

**Comment by DSuveges** [comment]
Full resolution in #873
