### ISSUE TITLE
OT Genetics portal sourced evidences: some studies are missing disease label

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#858]
When @AsierGonzalez performed QC checks on the evidences for the 20.02 release it made clear ~4k Genetics portal sourced evidences are missing disease label. The initial investigation showed only a handful of studies are affected but needs to find out why this is happening.

**Comment by d0choa** [comment]
Related to #860

**Comment by DSuveges** [comment]
A fix is going to be added to the evidence creator script that tests if the disease label is provided and skips rows where it is missing (while raising warnings), so these evidences won't reach the pipeline.

**Comment by DSuveges** [comment]
**Bug found:** when the evidences are generated there's no check to ensure the evidence has a disease label. This is going to be fixed and a warning is thrown for each such evidences so we'll see these rows in the log file. 

Otherwise based on the input data this is expected: ~750 studies in the genetics portal study table has no disease associated with.

**Comment by DSuveges** [comment]
Fixes to filter out studies without disease id are merged: [#42](https://github.com/opentargets/evidence_datasource_parsers/pull/42)
Fix to prevent the generation of evidences without disease is merged: [#39](https://github.com/opentargets/evidence_datasource_parsers/pull/39)
