### ISSUE TITLE
Animal model (PhenoDigm) evidence data missing allele ids

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/platform#859]
The animal models evidence table in the platform display PhenoDigm data: currently the mouse model field appears incomplete (no link and incorrect formatting).

It appears that in the API response the allele_ids field `evidence.biological_model.allele_ids` is empty:
https://platform-api.opentargets.io/v3/platform/public/evidence/filter?size=1000&datasource=phenodigm&fields=disease&fields=evidence&fields=scores&fields=access_level&target=ENSG00000282608&disease=EFO_0000516&view=sec:animal_model&expandefo=true
It should be a string like "MGI:3054788|MGI:3054788".
This appears also in production, which means since at least 19.11.

**Comment by AsierGonzalez** [comment]
The `evidence.biological_model.allele_ids` has been an empty string at least since April 2018. The PhenoDigm parser should be thoroughly reviewed to look into this and other issues.

**Comment by AsierGonzalez** [comment]
For the time being we should perhaps hide the column in the table if it is based on this value. Can you @LucaFumis please give me a list of the values used by the FE to make sure that they are correct?

**Comment by LucaFumis** [comment]
Hi @AsierGonzalez that `evidence.biological_model.allele_ids` is needed to generate the link only (mouse model column), the actual cell text is OK - I don't think we should hide it.
We can very easily refactor that bit of code to format the content regardless of whether we have a link for it or not. Perhaps something for next (mini) release.

The fields from the response are mapped as follow:

disease: `disease.efo_info.label`
human: `evidence.disease_model_association.human_phenotypes`
mouse: `evidence.disease_model_association.model_phenotypes`
mouse model: `evidence.biological_model.allelic_composition` and `evidence.biological_model.allele_ids` and `evidence.biological_model.genetic_background`

score: `scores.association_score` hidden column used for sorting the table

**Comment by LucaFumis** [comment]
No one reported (noticed) that the link was missing in all this time, so probably not that urgent...

**Comment by AsierGonzalez** [comment]
Ok. And just for me to understand, are you expecting it to be a link or do you use it to generate a link?

**Comment by LucaFumis** [comment]
It was a string of ids from which we generate the links - something like `MGI:3054788|MGI:3054788`.
