### ISSUE TITLE
Which disease in the search results is spinal muscular atrophy?

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#86]
@elipapa commented on [Fri Jan 12 2018](https://github.com/opentargets/roadmap/issues/115)

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_semantic/issues/7)

@elipapa commented on [Mon Feb 20 2017](https://github.com/opentargets/platform_issues_triage/issues/2)

@nikiforosk commented on [Mon Feb 13 2017](https://github.com/opentargets/features/issues/66)

Prompted from our discussion with Shila from Biogen on Friday I searched for "spinal muscular atrophy" and got the following results:
https://www.targetvalidation.org/search?src=q:spinal%20muscular%20atrophy,p:1,f:disease

![search-spinal-muscular-atrophy](https://cloud.githubusercontent.com/assets/20280139/22900594/cae8029e-f226-11e6-8b41-b49a29079847.png)

I'm not sure where to click next to look for the targets associated with "spinal muscular atrophy":
Is it "Proximal spinal muscular atrophy" (1st result), "Spinal muscular atrophy associated with central nervous system anomaly" (3rd result) or some of the other types of "spinal muscular atrophy".

@iandunham can you check these results and let us know if they look OK to you?

---

@elipapa commented on [Mon Feb 20 2017](https://github.com/opentargets/features/issues/66#issuecomment-281191424)

I had already sent an email to Sira @EFO earlier. Pasted here for reference:

> From: Sirarat 
Date: Wednesday, February 8, 2017 at 3:08 PM
To: Eliseo Papa 
Cc: Gautier Koscielny 
Subject: Re: EFO terms for Spinal muscular atrophy
 
Hi Eliseo,
 
I will consult with Orphanet on this and will let you know. In the meantime, if SMA is already one of the terms that Gautier is working on and is making its way to his webulous submission, it will be generated and I will work to link the different subtypes of SMA to this newly created term once it is created.
 
Thank you,
Sira

--------------------------------------------------------------
 
> On 8 Feb 2017, at 14:59, Eliseo Papa  wrote:
 
Hi Sira,
 
The use case comes from the fact that Biogen has just released a drug to treat SMA (spinal muscular atrophy) an autosomal recessive proximal muscular spinal muscular atrophy.
This is the most well known of all spinal muscular atrophies.
 
The clinical distinction between proximal and distal is indeed important, but a common parent definitely needs to be there regardless.
 
OMIM appeared to capture the structure of the classification remarkably well (the table on Wikipedia https://en.wikipedia.org/wiki/Spinal_muscular_atrophiesreports the OMIM identifiers).
As you can see SMA is the most common form and the best recognized.
 
Hope this helps.
Thanks,
eliseo
 
 
 
 
> From: Sirarat Sarntivijai 
Date: Wednesday, February 8, 2017 at 11:37 AM
To: Eliseo Papa 
Subject: Re: EFO terms for Spinal muscular atrophy
 
Hi Eliseo, 
 
Both terms (distal and proximal SMA) are sibling rare diseases under a shared parent ‘genetic motor neuron disease' defined by Orphanet (I have no control over terms imported from another ontology e.g. Orphanet Ontology). I do not know why they did not define a common parent class of SMA, possibly because genetic diseases is hard to be defined by a parent? I can inquire them for a new term for SMA, but looking at their many specific type of SMA’s that they have in their database (http://www.orpha.net/consor/cgi-bin/Disease_Search_Simple.php?lng=EN&diseaseGroup=spinal+muscular+atrophy), I think there might be a clinical reason why they do not define a common SMA (I’m only guessing here).
 
Do you have a need for this term? Let me know if you’d like me to get in touch with them and further inquire for this new term to be created.
 
Cheers,
Sira

--------------------------------------------------------------
 
> On 7 Feb 2017, at 15:42, Eliseo Papa  wrote:
 
Hi Sira,
 
I was looking at SMA (spinal muscular atrophy) in the EFO and saw that proximal SMA
 
http://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_70
 
and distal SMA are not joined by a common parent (which I would expect to be called SMA).
 
Is that right?
 
Thanks,
eliseo
 

---

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_issues_triage/issues/2#issuecomment-296816337)

cc/ @opentargets/efo_mapping 

---

@ElaineMcA commented on [Mon Aug 13 2018](https://github.com/opentargets/roadmap/issues/115#issuecomment-412486293)

Check in EFO 3. SPOT ticket opened to address.

https://github.com/EBISPOT/efo/issues/229

**Comment by afaulconbridge** [comment]
Upstream ticket in EFO3 has been closed. Will need to revisit this once we are using EFO3.

**Comment by afaulconbridge** [comment]
This is solved in the EFO3 prototype. See https://efo3.targetvalidation.org/search?src=q:spinal%20muscular%20atrophy Closing this ticket.
