### ISSUE TITLE
Curate more target safety information and integrate into Platform for 20.04

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#862]
This is epic is part of a bigger project on improving the target safety information in the Open Targets Platform. It's a continuation of the work started in #411.

The aim of this epic is to expand gold standard of known target safety issues.

Tickets on this task will cover: data curation, annotation specifications, annotation generation, ingestion and FE changes.

**Comment by PruMM** [comment]
Subtasks in this epic include
1- Data set assessment: HeCatos, PharmGKB, EUToxrisk, ChEMBL withdrawn drugs
2- Criteria for inclusion of new targets into gold standard set
3- Identification process for inclusion of new safety related parameters into the gold standard

**Comment by andrewhercules** [comment]
For the upcoming 20.04 release, we are going to focus on the experimental toxicity data that Prudence has curated from ETOX and TOX21 as noted in #891

**Comment by andrewhercules** [comment]
Epic closed as safety data changes for 20.04 have been implemented in production
