### ISSUE TITLE
genomic browser issues derived from new Genetics Portal evidence

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#864]
Users reported to @deniseOme problems with the genomic browser missing data.
After a preliminary review on the issue with @DSuveges and @LucaFumis, we think the problem is summarised in the next issues:

- There are missing rsIDs on some of the Genetics Portal evidence due to a bug. This problem will be resolved thanks to the changes in the evidence generation introduced by @DSuveges in #857.

- The Genomic Browser is still querying the GWAS Catalog datasource.

The action in this ticket is only related to changes in the Genomic Browser to pull the Genetics Portal evidence. This change can justify a mini-release.

**Comment by LucaFumis** [comment]
This is now fixed in production.
