### ISSUE TITLE
Create a first draft on data submission guidelines

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#865]
According to discussions between @AsierGonzalez and @d0choa. Further discussions will be required based on the first draft.

**Comment by andrewhercules** [comment]
Pushed to 20.09 release

**Comment by andrewhercules** [comment]
Pushed to 20.11 release

**Comment by AsierGonzalez** [comment]
Draft of the document started here: https://docs.google.com/document/d/16sUmWpMAlfLP3PC8y3NqHREHOtyX-LnFqU9OlUlOeEQ/edit

**Comment by andrewhercules** [comment]
Moving to 21.02 as the first iteration of the data submission guidelines, focussing on the process and general guidelines, will be part of the 21.02 release process

**Comment by ktsirigos** [comment]
first draft is [here](https://docs.google.com/document/d/1rtKw69VAOFdona5auzv1sLORwD9quFiwMUmZ1uSd9bA/edit).

@ireneisdoomed and @DSuveges will have a look and David to take a final look.

**Comment by ktsirigos** [comment]
Document is done and ready to be circulated.

https://docs.google.com/document/d/1rtKw69VAOFdona5auzv1sLORwD9quFiwMUmZ1uSd9bA/edit#heading=h.xyc86metdhp6
