### ISSUE TITLE
Process network data in platform-input-support

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#869]

**Comment by cmalangone** [comment]
Platform input support has a new step called "interactions".
Interactions step generates/gets the data from strings and intact and transform them in order to be used by ETL.

Moreover, this step generates/gets the mapping files. Eg. protein mapping, ensembl human mapping.

**Comment by cmalangone** [comment]
Deployed first release for this resource.

*) Platform-input-support: step interactions with two modules: Intact and String Interaction
To do:
    move string threshold to ETL 
    use the json schema that Daniel wrote

*) ETL: step interactions.

**Comment by cmalangone** [comment]
A first release of "network" that was recalled "interactions" was already deployed for the alpha and beta-release.

PIS is generating the input file for the ETL.

**Comment by cmalangone** [comment]
Improved the PIS and ETL.
Moved the files to ETL. Quicker and good practices.

**Comment by cmalangone** [comment]
Done.
