### ISSUE TITLE
Create STRING network json

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#870]

**Comment by DSuveges** [comment]
To build STRING network JSON in the same as we have proposed for Intact, we collect a list of evidences under the `interaction` key. The only problem is that the available evidences for STRING does not follow [MI](https://www.ebi.ac.uk/ols/ontologies/mi) vocabulary, so we need to map them.

This is the list of evidence types and the corresponding mapping I could came up with:

| STRING term | mapped MI term | MI code |
|-------------|----------------|---------|
| coexpression | [coexpression](http://purl.obolibrary.org/obo/MI_2231)  |  MI:2231  |
| neighborhood | [gene neighbourhood](http://purl.obolibrary.org/obo/MI_0057)  | MI:0057  |
| fusion |  [domain fusion](http://purl.obolibrary.org/obo/MI_0036) | MI:0036  |
| homology | [by homology](http://purl.obolibrary.org/obo/MI_2163)  |  MI:2163  |
| experiments |  [experiment description](http://purl.obolibrary.org/obo/MI_0591 ) | MI:0591  |
| cooccurence |   |   |
| database |   |   |
| textmining | [text mining](http://purl.obolibrary.org/obo/MI_0110)  | MI:0110  |

**Comment by DSuveges** [comment]
**Input: **

| header | Value |
| ---  |  --- |
|  protein1  |  9606.ENSP00000354878  |
|  protein2  |  9606.ENSP00000000233  |
|  neighborhood  |  0  |
|  neighborhood_transferred  |  0  |
|  fusion  |  0  |
|  cooccurence  |  0  |
|  homology  |  0  |
|  coexpression  |  0  |
|  coexpression_transferred  |  0  |
|  experiments  |  0  |
|  experiments_transferred  |  131  |
|  database  |  900  |
|  database_transferred  |  0  |
|  textmining  |  0  |
|  textmining_transferred  |  56  |
|  combined_score  |  910  |

**Output:**

```json
{
  "interactorA": {
    "uniprot_id": "P84085",
    "ensembl_gene_id": "ENSG00000004059",
    "ensembl_protein_id": "ENSP00000000233",
    "organism": {
      "scientific_name": "Homo sapiens",
      "taxon_id": 9606,
      "mnemonic": "human"
    },
    "biological_role": null
  },
  "interactorB": {
    "uniprot_id": "Q7Z4S6",
    "ensembl_gene_id": "ENSG00000139116",
    "ensembl_protein_id": "ENSP00000354878",
    "organism": {
      "scientific_name": "Homo sapiens",
      "taxon_id": 9606,
      "mnemonic": "human"
    },
    "biological_role": null
  },
  "interaction": {
    "interaction_score": 910,
    "causal_interaction": false,
    "evidence": [
      {
        "interaction_identifier": null,
        "interaction_detection_method_short_name": "experiments_transferred",
        "interaction_detection_method_mi_identifier": "",
        "pubmed_id": null,
        "evidence_score": 131
      },
      {
        "interaction_identifier": null,
        "interaction_detection_method_short_name": "database",
        "interaction_detection_method_mi_identifier": "",
        "pubmed_id": null,
        "evidence_score": 900
      },
      {
        "interaction_identifier": null,
        "interaction_detection_method_short_name": "textmining_transferred",
        "interaction_detection_method_mi_identifier": "",
        "pubmed_id": null,
        "evidence_score": 56
      }
    ]
  },
  "source_info": {
    "source_database": "string",
    "database_version": null
  }
}
```

The script soon will be wrapped up and pushed to platform input support. Also a proper JSON schema will be built.

**Comment by d0choa** [comment]
Looks great! Just minor comments:
- We don't use the `ensembl_protein_id` for anything at the moment, so feel free to remove it if you want.
- make sure you fill `source_info.database_version`. It will be handy

**Comment by DSuveges** [comment]
Currently STRING data is coming with the Ensembl protein id. I think for tracking it makes sense to keep those identifiers as well. 

Yes, the version will be filled: this value cannot be read from the file itself, but from the filename. This bit is yet to be added to the code.

**Comment by DSuveges** [comment]
How the most recent version looks like:

```json
{
  "interactorA": {
    "id": "ENSG00000004059",
    "source": "ensembl_gene",
    "organism": {
      "scientific_name": "Homo sapiens",
      "taxon_id": 9606,
      "common_name": "human"
    }
  },
  "interactorB": {
    "id": "ENSG00000197892",
    "source": "ensembl_gene",
    "organism": {
      "scientific_name": "Homo sapiens",
      "taxon_id": 9606,
      "common_name": "human"
    }
  },
  "interaction": {
    "interaction_score": 910,
    "causal_interaction": false,
    "evidence": [
      {
        "interaction_detection_method_short_name": "experiments_transferred",
        "interaction_detection_method_mi_identifier": "",
        "evidence_score": 131
      },
      {
        "interaction_detection_method_short_name": "database",
        "interaction_detection_method_mi_identifier": "",
        "evidence_score": 900
      },
      {
        "interaction_detection_method_short_name": "textmining_transferred",
        "interaction_detection_method_mi_identifier": "",
        "evidence_score": 56
      }
    ]
  },
  "source_info": {
    "source_database": "string",
    "database_version": "11"
  }
}
```

**Comment by DSuveges** [comment]
Steps remaining to complete this ticket:

- [ ] Complete script that parses string data and generates json.
- [ ] Finalise which input file should actually be used.
- [ ] Finalise the mapping of detection methods to MI terms.
- [ ] Submit pull request and ask for code review.
