### ISSUE TITLE
Adding new ECO code for Genetics platform

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#873]
**This ticket is related to** #856

The `evidence_codes_info` field was missing from the genetics portal evidences as the new source was not introduced into the ECO json file. The variant to gene mapping pipeline represents a new evidence class.

Affected repository: [ECO ontology generation](https://github.com/opentargets/ontology-utils/blob/master/opentargets_ontologyutils/eco_so.py)

A relatively straightforward resolution is to add the following line to the [open_targets_terms](https://github.com/opentargets/ontology-utils/blob/4d79b8d530f88ace55ff27334b7dd4bd99b247bb/opentargets_ontologyutils/eco_so.py#L38) dictionary:
`'http://identifiers.org/eco/locus_to_gene_pipeline':'Open Targets Genetics portal locus to gene annotation pipeline,`

This will lead to the addition of the following evidence class:

```json
{
    "code": "http://identifiers.org/eco/locus_to_gene_pipeline",
    "label": "Open Targets Genetics portal locus to gene annotation pipeline",
    "path": [
        {
            "label": "evidence",
            "uri": "http://purl.obolibrary.org/obo/ECO_0000000"
        },
        {
            "label": "Open Targets Genetics portal locus to gene annotation pipeline",
            "uri": "http://identifiers.org/eco/locus_to_gene_pipeline"
        }
    ],
    "path_codes": [
        "ECO_0000000",
        "locus_to_gene_pipeline"
    ],
    "path_labels": [
        "evidence",
        "Open Targets Genetics portal locus to gene annotation pipeline"
    ]
}
```

**Comment by AsierGonzalez** [comment]
Fixed by https://github.com/opentargets/ontology-utils/pull/11
