### ISSUE TITLE
OT Genetics Portal evidence scored based on functional consequence

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#876]
A user realised that the scores of the 20.02 OT Genetics Portal evidence strings only had one of five values (0.5, 0.6, 0.65, 0.7 or 0.95) when it should be the l2g score, which has a value between 0-1.
![Screenshot 2020-03-10 at 12 45 37](https://user-images.githubusercontent.com/11410715/76313766-7e991200-62cd-11ea-96b6-2b9e870ac16f.png)
We have realised that this is caused by a bug in the data pipeline, which causes genetic association evidence to be scored based on the functional consequence of the variant, ignoring the p-value o l2g score.

**Note:** This seems to have been around unnoticed since 2016, meaning that is not related to the recent integration of the genetics portal data.

**Comment by AsierGonzalez** [comment]
PR [#560](https://github.com/opentargets/data_pipeline/pull/560) should fix this issue.

**Comment by AsierGonzalez** [comment]
Issue has been solved, now the scores cover the whole 0-1 range:
![Screenshot 2020-04-16 at 14.43.13.png](https://images.zenhubusercontent.com/5e3bdd3b5ae31307fec27bc8/fc73f27d-e3be-47ae-b105-e929f98a18fe)

**Comment by d0choa** [comment]
@iandunham @DSuveges @AsierGonzalez 
There is an ongoing discussion on removing from the platform the bottom bar from the plot above (1.6M evidence). Not urgent as they are all low scored and have very little impact on associations. Happy to hear opinions here:

![portal_evidence](https://user-images.githubusercontent.com/5097586/79567686-932ab000-80ac-11ea-933c-ce58df5a7144.jpg)

My views:

Pros:

- removal of low-scoring evidence with low enrichment on validated evidence.
- lighter pipeline, DDR, associations, etc.

Cons:
- introduction of arbitrary threshold
- lost of weak signals that could become important when combined with other datasources.

Further actions will be issued in different tickets.

**Comment by iandunham** [comment]
My view on this is that we should be able to identify a principled threshold. for instance we could say we should be at least as good as GWAS catalog - we would achieve this on the enrichment with a threshold of at least 0.05. Have we looked at the overall distribution of the L2G score values? On the basis of this analysis it loks like there is a long tail below 0.05

Happy to explore further
