### ISSUE TITLE
PheWAS: link from evidence to ePMC shows ID_1

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#88]
Go to this page:

https://www.targetvalidation.org/evidence/ENSG00000114013/EFO_0000540?view=sec:genetic_association

Link out from PheWAS evidence

https://europepmc.org/abstract/MED/1?fromSearch=singleResult&fromQuery=EXT_ID:1

Note: GWAS evidence links work as expected.

Needs follow-up with ePMC as we build the URL with the query, but the ID (i.e. ‘1’) is like that in the data.

![screen shot 2018-08-23 at 15 40 35](https://user-images.githubusercontent.com/40168275/44573990-036e1a80-a780-11e8-902a-b45ad3f7e7a0.png)

**Comment by ElaineMcA** [comment]
Code has been fixed in PheWAS code.  Will be included in 18.10 (was not included in 18.08 as we reverted to old file for metrics reasons).

**Comment by MichaelaEBI** [comment]
Will be fixed in 18.12 - we used the old PheWAS evidence file again because we are still working on the PheWAS module. This will be sorted out shortly so that a new, corrected file is available for 18.12.

**Comment by MichaelaEBI** [comment]
Fixed in 18.12!
