### ISSUE TITLE
Update tractability plugin in data pipeline

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#880]
In order to process the latest tractability [.tsv file](https://drive.google.com/drive/folders/1J0QnDrAFswaBZhs0HsF4XK9H_IMyVilE) generated by ChEMBL, we will need to update the pipeline as the headings for the small molecule modality have changed. Also, there is now a section for other clinical modalities (e.g. protein, enzyme) with the same clinical precedence buckets 1, 2, and 3. And there is also a single string of ChEMBL IDs that support the clinical precedence buckets 1, 2, and 3 for small molecule, antibody, and other clinical modalities.

As such, @cmalangone, can you please update the pipeline with the following changes:

1. Update the pipeline to use the data about other clinical modalities and add an entry in the gene index tractability object - see below for a scaffold of what it could look like:

```
"tractability": {
  "smallmolecule": {},
  "antibody": {},
  "other_modalities": {
    "buckets": [
      1
    ],
    "categories": {
      "clinical_precedence": 1
    }
  }
}
```

For other clinical modalities, the buckets are 1, 2, and 3 and the categories are "clinical_precedence".

2. Update the pipeline to use the new small molecule column headings

| Old column name / heading | New column name / heading |
| --- | --- |
| Bucket_1 | Bucket_1_sm |
| Bucket_2 | Bucket_2_sm |
| Bucket_3 | Bucket_3_sm | 
| Bucket_4 | Bucket_4_sm |
| Bucket_5 | Bucket_5_sm |
| Bucket_6 | Bucket_6_sm |
| Bucket_7 | Bucket_7_sm |
| Bucket_8 | Bucket_8_sm |
| Bucket_sum | Bucket_sum_sm |
| Top_bucket | Top_bucket_sm |
| Category | Category_sm |
| Clinical_Precedence | Clinical_Precedence_sm |
| Discovery_Precedence | Discovery_Precedence_sm |
| Predicted_Tractable | Predicted_Tractable_sm |
| PDB_Known_Ligand | PDB_Known_Ligand |
| ensemble | DrugEBIlity_score |
| High_Quality_ChEMBL_compounds | High_Quality_ChEMBL_compounds |
| Small_Molecule_Druggable_Genome_Member | Small_Molecule_Druggable_Genome_Member |

**Comment by andrewhercules** [comment]
ChEMBL have made the data available and it has been uploaded into [otar001-core/Tractability/20.04](https://console.cloud.google.com/storage/browser/otar001-core/Tractability/20.04)

**Comment by andrewhercules** [comment]
Based on a conversation with @cmalangone, we will not update the pipeline to process the ChEMBL IDs and labels for this release. Rather, we will work with ChEMBL to update the JSON generated by the tractability pipeline for 20.06.

**Comment by cmalangone** [comment]
Point 1 and 2 done. 
Had a conversation with @LucaFumis about the format for the index. 

PR done and merge. 
Run a first test and no issue came up.

**Comment by andrewhercules** [comment]
Thank you @cmalangone - the data is now available in the API! 👍
