### ISSUE TITLE
Update Angular application to display other modality data and link to tractability data file

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#882]
To support our users that want to see more tractability data, we will show the other modality assessment and the the underlying evidence used to support a tractability assessment.

@LucaFumis, can you please update the Target Tractability section with the following:

1. An "Other Clinical Modalities" section that will be similar to the Small Molecule and Antibody sections and will only have 3 buckets - 1, 2, and 3 (Clinical Precedence)

2. Add the following text underneath the data tables - "To view the underlying evidence supporting the tractability assessment for GENE-SYMBOL, please download the Open Targets tractability data file" and please link "Open Targets tractability data file" to the Platform downloads page at https://www.targetvalidation.org/downloads/data.

**Comment by andrewhercules** [comment]
@Luca, would it be possible to build something like this?

![Screenshot 2020-04-15 at 15 57 23](https://user-images.githubusercontent.com/7490258/79352476-d280c180-7f31-11ea-9fad-f0587be97069.png)

**Comment by andrewhercules** [comment]
@LucaFumis, looks great on QA!

Could we make a few small changes?

1. Update the `Target tractability` section description to read `Summary of tractability information for _____ for small molecule, antibody, and other modalities.`

2. Change the title of "Other modalities" to "Other modalities (protein, enzyme, oligionucleotide, etc.)"

3. For the text with the link to the tractability data file, could we please remove `for GENE-SYMBOL` so that the text now reads `To view the underlying evidence for the tractability assessment, please download the Open Targets tractability data file`

4. Update the logic so that the "Other modalities" heat map table shows on all genes. For example, with [ESR1](https://qa.targetvalidation.org/target/ENSG00000091831), the title "Other modalities" is shown but there is no heat map underneath. 

5. Update the logic so that the link to the tractability data file is shown for all genes - including genes with no tractability data (e.g. [AC004997.1](https://qa.targetvalidation.org/target/ENSG00000248751)) as some of these genes may have data that did not meet the threshold for the tractability assessment pipeline but may still be relevant to our users.

**Comment by andrewhercules** [comment]
@LucaFumis, can we please make one small change to the wording of the link to the tractability data file? Can we please change "underlying evidence supporting" to "data used to make" :

`** To view the data used to make the tractability assessment, please download the [Open Targets tractability data file](https://www.targetvalidation.org/downloads/data) **`

**Comment by d0choa** [comment]
I think we should probably remove the message for the next version. Once the novelty wears off, I don't see a reason to have the link for tractability and not for safety (or others to come).

**Comment by andrewhercules** [comment]
@d0choa, we could just drop completely as you suggested earlier. I would rather get to a stage with the JSON where users can download the individual tractability assessment data for a specific target right on the target profile page.

**Comment by d0choa** [comment]
@andrewhercules is your call. I can see the novelty on this version and the point on highlighting it. Long-term, it doesn't make much sense. Happy either way

**Comment by andrewhercules** [comment]
Issue closed as work completed as part of 20.04 release process
