### ISSUE TITLE
Platform Infrastructure changes for targets deployment

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#889]
Production infrastructure needs to support serving the new technical requirements for targets.

Currently the frontend uses Netlify, also for production (Angular app) - it seems we can continue with that.

Other points to consider:
 * We need to decide on the best approach (front end) to switch over to the new API.
 * Do we want to deploy, as a possible `beta`, the target page only?

**Comment by cmalangone** [comment]
Release the rewrite in 3 Region with a load balance for the OT day.
Wrote a script with few parameters in order to create the new infrastructure. 
We are investigating to write an infrastructure using terraform.

**Comment by andrewhercules** [comment]
Ticket closed as Alpha deployed with production setup. Further changes may be made for the Beta release scheduled in September 2019
