### ISSUE TITLE
Overlap syndrome (OS) representation in EFO

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#89]
@elipapa commented on [Fri Jan 12 2018](https://github.com/opentargets/roadmap/issues/121)

@gkos-bio commented on [Wed Feb 22 2017](https://github.com/opentargets/platform_semantic/issues/1)

See EFO ticket 
https://github.com/EBISPOT/efo/issues/27

1. Context:

Overlapping connective tissue diseases (with shared autoimmunity)/rheumatic autoimmune disease and Asthma-COPD Overlap Syndrome (ACOS) classification.

1.1 Rheumatic autoimmune disease
Rheumatic autoimmune disease patients can been diagnosed with: 
- Rheumatoid Arthritis (RA),
- Systemic lupus erythematosus (SLE),
- RA first and then with RA + SLE.

The last case is commonly seen in clinical practice.
So, they have been diagnosed with an overlap autoimmune disease that differs from those with 'pure' RA or 'pure' SLE. There is a controversial term coined in the litterature as 'Rhupus' or 'Rhupus syndrome' to categorise these patients with overlapping phenotypes from both SLE and RA. 

1.2 
Another example is Asthma and COPD commonly presented in clinical practice ant the challenge to identify whether the patients are ‘purely’ asthmatic or suffer from asthma-COPD overlap syndrome (ACOS). The asthma-COPD overlap syndrome (ACOS) has reemerged in the medical literature.
ACOS is characterized by persistent airflow limitation (FEV1 ≤ 80% predicted; FEV1/FVC ratio ≤70%) with several features shared with both asthma and COPD, including current or past smoking
(see section 5. below)

1.3 Disease heterogeneity
There is controversy concerning this overlapping/mixed disease classified as a separate entity due to heterogeneous clinical manifestations (there is no consensus on an ACOS definition, likely due to the heterogeneity of the disease), and especially, because there is an increasing tendency to shift away from fixed disease labels. 

However, in terms of disease classification and of finding the relevant biomarkers and genetic information from text-mining, it make sense to acknowledge what disease labels are currently used in the literature to characterise a group of related disorders with distinct co-morbidities. 

2. Overlap Connective Tissue Disease Syndromes:

In general, overlap syndromes (OSs) - which I don't particularly like as a term from a patient point of view - is defined as entities satisfying classification criteria of at leas two connective tissue diseases occurring at the *same* time or at a *different* time in the same patient.

This include:

- systemic lupus erythematosus (SLE), 
- rheumatoid arthritis (RA), 
- systemic sclerosis (SSc), 
- polymyositis/dermatomyositis (PDM), and 
- Sjögren syndrome (SS).

For reference, please read:
http://www.sciencedirect.com/science/article/pii/S1568997212001218

Scleromyositis is another one that is both 'Systemic sclerosis' and 'polymyositis' and a synonym of 'scleroderma/polymyositis overlap syndrome'.

3. Current classification in thesaurus and ontologies:

What information is available in EFO?

3.1 Mixed connective tissue disease
Currently, there is a concept of 'mixed connective tissue disease' in EFO with a x-ref to DO and to MeSH.

In DO, the same concept is defined as 'A collagen disease that is considered an overlap of three diseases, systemic lupus erythematosus, scleroderma, and polymyositis with very high titers of circulating antinuclear antibody to a ribonucleoprotein antigen.'

In MeSH, it's a subtype of 'connective tissue diseases' and defined as 'A syndrome with overlapping clinical features of systemic lupus erythematosus, scleroderma, polymyositis, and Raynaud's phenomenon.'

In NCIt, it's labeled as Mixed Connective Tissue Disease (Code C84892).

In ORDO, it's defined as 'Mixed connective tissue disease (MCTD) is a rare connective tissue disorder combining clinical features of systemic lupus erythematosus (SLE), systemic sclerosis (SSc), polymyositis (PM) (see these terms) and/or rheumatoid arthritis (RA).'

3.2 Localised scleroderma and scleroderma:
Note that there is one child of mixed connective tissue disease in EFO: localised scleroderma.
However, it's not a mixed connective tissue disease and will have to be reclassified.
Scleroderma is indeed a connective tissue disease characterized by tissue fibrosis, vasculopathy and immune dysregulation. 
Localised scleroderma is a subclass of scleroderma (see DO)

3.3 Connective tissue disease:
The concept is missing from EFO but present in DO, MeSH and NCIt (Connective Tissue Disorder (Code C26729)). This should be added.

3.4 Overlap syndrome:
The concept is missing from EFO 

In ORDO, the concept of 'Overlapping connective tissue disease' is already defined with 
- 'Mixed connective tissue disease' (MCTD), and
- 'Unclassified overlapping connective tissue disease'
as subclasses of it.

3.5 Suggested classification changes in EFO:

Connective tissue disease (to be added)
|__ Overlapping connective tissue disease (need synonyms like Overlap connective tissue disease syndrome)
     |__ Scleromyositis
     |__ dermatomyositis/systemic lupus erythematosus overlap syndrome (Dermatomyositis Overlap with Systemic Lupus Erythematosus) 
     |__ Rhupus
     |__ Scleroderma overlap syndrome (PMID:27684895)
     |__ Mixed connective tissue disease
     |__Unclassified overlapping connective tissue disease

Reclassify Localised scleroderma has a subclass of scleroderma (to be defined)

5. Asthma-COPD overlap syndrome (ACOS). 
Approximately one in four patients with chronic obstructive pulmonary disease (COPD) have asthmatic features consisting of wheezing, airway hyper-responsiveness or atopy ((PMID:28119742)

Look also at the following article:
Postma DS , Rabe KF . The asthma-COPD overlap syndrome. N. Engl. J. Med. 2015; 373: 1241–9.
http://www.nejm.org/doi/full/10.1056/NEJMra1411863

Action: to be discussed after review.

---

@gkos-bio commented on [Fri Jun 22 2018](https://github.com/opentargets/roadmap/issues/121#issuecomment-399493786)

Still open in EFO
https://github.com/EBISPOT/efo/issues/27

**Comment by andrewhercules** [comment]
@smnorthen, could you please investigate this in relation to EFO3 and decide if it is something we need to pursue or if this issue can be closed?

**Comment by smnorthen** [comment]
@andrewhercules 
@gkos-bio
From what I can see, there have been multiple discussions between OT, EFO and Mondo regarding this issue. Based on my review of the literature, more of the research seems to point to overlap syndromes being separate clinical entities. Having said that, some experts disagree. Personally, I feel that it would be the safest option to represent these syndromes separate in EFO and not have them as a child record of each of the 2 different diseases which make up the overlap syndrome.

From what I can see, all of the individual diseases such as RA, Lupus etc are all in EFO. There are some overlap syndromes present, such as Scleromyositis (although it's a child of scleroderma and polymyositis which is probably not ideal). However, I am unable to find all of the variations of these overlap syndromes in EFO, such as Rhupus. 

Considering that this issue has been raised a long time ago, I am not sure if any work in EFO regarding these syndromes is still required. Taking a pragmatic approach, if no one has required these terms since, then we may be able to close this ticket as it would take a lot of research and agreements to implement all of the different overlap syndrome.

**Comment by d0choa** [comment]
Thanks @smnorthen.
