### ISSUE TITLE
Targets Routinely Screened in Safety Panels: TOX21 and ETOX data formatting for 20.04

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#891]
Interest has been expressed in highlighting targets that are routinely screened in Toxicity Safety Panels. TOX21 and ETOX  are 2 data sources with such screening information

**Comment by andrewhercules** [comment]
@PruMM to generate a spreadsheet based on [a proposed JSON schema](https://drive.google.com/file/d/1JSHxuKLntezl3KnOTGYx7SVWjZpeRTF9/view) and [data table UI element](https://docs.google.com/presentation/d/1_Dfr3A3ztQezwvH_vDadcl2MnViBGcitU_NNZNJ1uLA/edit#slide=id.g7ee0bec8fe_0_0) for new experimental toxicity data.

One the data table has been generated, this ticket can be closed and work can commence on updating the safety plugin (#904).

**Comment by andrewhercules** [comment]
Ticket closed as data from eTOX and Tox21 has been curated and added to the [/Target Safety/safety_buckets_work/experimental_toxicity folder](https://drive.google.com/drive/folders/1Cm-tnZSkNZLhshYY98S_Hom58vci9Huq) in .tsv and .xlsx formats.
