### ISSUE TITLE
Update existing target safety spreadsheets with new targets

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#894]
New targets that could potentially be added

**Comment by PruMM** [comment]
New targets to add to the platform under the current categories. These new targets were identfied using the following script that looks for targets NOT in the interface

**Comment by andrewhercules** [comment]
@PruMM to update the existing spreadsheets used in the platform-input-support script to generate the adverse effects and known safety risk information for targets

**Comment by andrewhercules** [comment]
Based on analysis of data available for targets below by @PruMM, decision made to push updates to this data to 20.06 to allow for more curation using new data sources.

Targets:

- ENSG00000118777
- ENSG00000143921
- ENSG00000138075
- ENSG00000085563
- ENSG00000108846
- ENSG00000023839
- ENSG00000164889
- ENSG00000175003
- ENSG00000125257
- ENSG00000081923
- ENSG00000005471
- ENSG00000125255
- ENSG00000100652
- ENSG00000073734

**Comment by andrewhercules** [comment]
Ticket closed as data curated by @PruMM has been uploaded to the [Open Targets team Google Drive](https://drive.google.com/drive/folders/1Y3blQcdnCjqpxWaE9_VtSmQYwCGjB_A4)
