### ISSUE TITLE
Regex in json_schema v1.6.6

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#896]
Edd from UniProt has contacted us about a potential issue in the regex for v1.6.6 of the json_schema. @AsierGonzalez, can you please investigate? 

> ... when I run our pipeline, I get an error about the JSON schema 1.6.6 not being valid: ^http://www.ncbi.nlm.nih.gov/clinvar/RCV[0-9]{9}|http://identifiers.org/dbsnp/rs[0-9]{1,}|http://identifiers.org/dbsnp/esv[0-9]{1,}|http://identifiers.org/dbsnp/nsv[0-9]{1,}|.{,2}_[0-9]+_[ACTG]+_[ACTG]+$ 
> 
> Specifically, the final part of the disjunction, .{,2}_[0-9]+_[ACTG]+_[ACTG]+, looks wrong, and indeed our compiler complains about it. Usually, curly braces indicate the number of times a match is repeated. e.g., {3} => match 3 times, or {2,4} matches between 2 and 4 times. But as far as I know, {,2} doesn't mean anything, hence our pipeline can't generate anything, since our the fails. I could be wrong about this, but could you please check that the regex is correct?
> 
> I could be wrong about this, but could you please check that the regex is correct?
>

**Comment by AsierGonzalez** [comment]
That last bit of the regex was introduced by @DSuveges in the schema version `1.6.4` to match the genetics portal variant notation that comes in the form of `1_154453788_C_T`. The problematic `{,2}` refers to the chromosome number, which chan be a number between 1-22, X, Y or MT. Changing that to `{1,2}` should sort the issue but if we want to be more explicit it could be changed to something like [[1-2]?[0-9]|X|Y|MT].
What do you think Daniel?

**Comment by DSuveges** [comment]
Yes, that was a mistake on my side: I was wrongfully assumed that in the range quantifier (`{}`) the minimum value is optional (the maximum certainly is optional where `{3,}` means matching 3 or more times). Yes, the proposed solution is correct: should be `{1,2}`

**Comment by AsierGonzalez** [comment]
Solved by PR [#85](https://github.com/opentargets/json_schema/pull/85) and version tagged as [`1.6.7`](https://github.com/opentargets/json_schema/blob/1.6.7/opentargets.json)

**Comment by eddturner** [comment]
:+1: thanks!
