### ISSUE TITLE
Bibliography widget

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#900]
The Bibliography widget shows literature data from the LINK platform, allowing to refine results based on keywords and concepts.
See https://platform-app.netlify.com/target/ENSG00000091831 for an example.
LINK: https://link.opentargets.io/

Original tickets:
#540 
#542 

The bibliography widget is different from other widgets in that it doesn't pull data from our API.
Instead it fetches data from the LINK API directly from the widget (React) code:
https://github.com/opentargets/platform-app/tree/master/src/public/common/sections/Bibliography
https://github.com/opentargets/platform-app/blob/master/src/public/common/sections/Bibliography/custom/Api.js

Although not going through our API, is this setup ideal? Can that be optimized?

See issue https://github.com/opentargets/platform/issues/901 for a list of actual external API calls.

**Comment by forus** [comment]
@andrewhercules @LucaFumis Hi guys! I've uncommented code to show the bibliography section. It looks working out of the box. No wonder as it does not depend on our GraphQL API.
Any idea what part of the section code deserves more work?
Shall we use react hooks instead of `componentDidMount`?

**Comment by andrewhercules** [comment]
Good question @forus!

@javfg and @mirandaio, for other third party API calls, do we use React hooks or `componentDidMount`?

**Comment by javfg** [comment]
We do not have a hook that handles the API call, but you are welcome to rewrite the widget as a functional component using standard hooks.

It would probably be good to wait for @mirandaio, he is more familiar with that widget.

**Comment by andrewhercules** [comment]
Copying note from duplicate issue #1020 

> The `Bibliography` summary widget and detail view sections on the Platform entity pages make an API call to LINK to display relevant publications. These sections have already been implemented on the disease and drug profile pages (e.g. [kidney disease](https://alpha--platform-app.netlify.app/disease/EFO_0003086), [CHEMBL122](https://alpha--platform-app.netlify.app/drug/CHEMBL122)).
> 
> Can we please integrate the Bibliography summary widget on the target profile page in the `alpha branch? Please display the total number of publications for the target (e.g. 3,548 publications).
> 
> And can we please integrate the Bibliography detail view on the target profile page in the `alpha` branch?
> 
> When integrating the Bibliography detail view, please pay attention to:
> 
> * Targets with no publications (e.g. ENSG00000265018)
> * Targets with 10,000+ publications (e.g. ENSG00000141510 or ENSG00000012048)
> * Error handling if the LINK API returns an error (note: please confirm with @mirandaio that the work he has done with React error boundaries will capture any LINK API errors)

**Comment by mirandaio** [comment]
Hi @forus, using hooks instead of `componentDidMount` will not bring that much benefit to this component. This bibliography component is working well as it is. A better thing to do will be to work on integrating a new widget.

**Comment by forus** [comment]
I don't know why the commit in the following PR has not been bind to the ticket automatically. Anyway here is related PR https://github.com/opentargets/platform-app/pull/144

**Comment by andrewhercules** [comment]
Ticket closed as PR has been merged into `alpha`
