### ISSUE TITLE
Refactor ETL into a modular Scala project

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#902]
To lunch the ETL in dataproc the project needs to be compiled as a `fat-jar` . And to achieve this the project as to be moved to a proper scala project. Setting an initial modular project structure might be beneficial. Having a common module to put all trans-module functions could be good. Also, exploring the option to generate a project per module or all combined can have a future impact.

**Comment by cmalangone** [comment]
PR branch cm_jar_project_1_release approved

**Comment by cmalangone** [comment]
Done
