### ISSUE TITLE
Update Angular application to display data table with new target safety information

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#906]
With the inclusion of new experimental toxicity data - see #904 - we should create a simple data table within the Target Safety tab on the target profile page.

Can we please implement a new data table based on the specs found below?

**Comment by andrewhercules** [comment]
[Data table design spec](https://docs.google.com/presentation/d/1_Dfr3A3ztQezwvH_vDadcl2MnViBGcitU_NNZNJ1uLA/edit#slide=id.g7ee0bec8fe_0_0) updated to account for changes to API response data noted in #905

**Comment by d0choa** [comment]
this looks great @PruMM and @andrewhercules

**Comment by andrewhercules** [comment]
Based on further conversations with @PruMM, the design specs have changed to account for key differences between the eTOX and Tox21 datasets. 

Instead of one table, we will generate two tables - one for cell-based Tox21 data and one for tissue-based eTOX data.

The design specs have been updated in the [team Google Drive](https://docs.google.com/presentation/d/1_Dfr3A3ztQezwvH_vDadcl2MnViBGcitU_NNZNJ1uLA) and more details are available below:

### Data table specifications

**Tox21 data table columns**

Column | API response data
-- | --
Assay format | `experimental_toxicity.experiment_details.assay_format`|
Assay description | `experimental_toxicity.experiment_details.assay_description`|
Cell name | `experimental_toxicity.experiment_details.cell_short_name`|
Assay type | `experimental_toxicity.experiment_details.assay_format_type`|
Source | `experimental_toxicity.data_source` with an external link using the `experimental_toxicity.data_source_reference_link` value |

**eTOX data table columns**

Column | API response data
-- | --
Tissue | `experimental_toxicity.experiment_details.tissue`|
Assay description | `experimental_toxicity.experiment_details.assay_description`|
Assay format | `experimental_toxicity.experiment_details.assay_format` |
Assay type | `experimental_toxicity.experiment_details.assay_format_type`|
Source | `experimental_toxicity.data_source` with an external link using the `experimental_toxicity.data_source_reference_link` value |

**Examples**

_Target with just Tox21 data (e.g. [SLC10A2](https://www.targetvalidation.org/target/ENSG00000125255))_

![Target Safety - Experimental Toxicity (ETOX_TOX21) Data Table Specification (4)](https://user-images.githubusercontent.com/7490258/78645559-9dc89680-78af-11ea-9715-001f5c2681fd.png)

_Target with only Tox21 data (e.g. [F3](https://www.targetvalidation.org/target/ENSG00000117525))_

![Target Safety - Experimental Toxicity (ETOX_TOX21) Data Table Specification (3)](https://user-images.githubusercontent.com/7490258/78646173-8fc74580-78b0-11ea-8d28-ef7e561b4854.png)

_Target with both eTOX and Tox21 data (e.g. [ABCG2](https://www.targetvalidation.org/target/ENSG00000118777))_

![Target Safety - Experimental Toxicity (ETOX_TOX21) Data Table Specification (2)](https://user-images.githubusercontent.com/7490258/78646281-b8e7d600-78b0-11ea-9f80-4bde80e302d9.png)

**Comment by andrewhercules** [comment]
@LucaFumis this looks all ready to go - thank you!

Can we please make one small change to the section description to note that non-clinical experimental toxicity data is also included? Can we please change it to the following?

`Known side effects, safety risk information, and/or non-clinical experimental toxicity data for _____, when available.`

**Comment by andrewhercules** [comment]
@LucaFumis, can we  please make one other small change to the link for the Tox21 data?

Instead of using the link provided in the API response, can we please use `https://tripod.nih.gov/tox21/assays/` as provided by @PruMM? The link text can continue to be `Tox21`.

**Comment by andrewhercules** [comment]
Issue closed as work completed as part of 20.04 release process
