### ISSUE TITLE
sources pubmed field from Cancer Biomarkers needs to be simplified

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#911]
The field `sources_pubmed` is overcomplicated with the current structure
```json
          "sources_pubmed" : [
            {
              "pmid" : "26287849"
            }
          ],
```
It has to be a list of pubmed ids as a string list not as the current object list.

**Comment by cmalangone** [comment]
Related with #925.

**Comment by cmalangone** [comment]
Approved with PR #925
