### ISSUE TITLE
Gene Ontology annotations for each target needs the eco field corrected

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#912]
Having this structure
```
          "go" : [
            {
              "id" : "GO:0015629",
              "value" : {
                "project" : "UniProtKB",
                "term" : "C:actin cytoskeleton",
                "evidence" : "ECO:0000304"
              }
            },
```
the field `evidence` contains an id with the wrong separator `:` and it has to be `_` to match the ECO LUT

**Comment by cmalangone** [comment]
The code to fix this issue will generate the following behaviour
*) go field is not available is there are not data 
*) go field will have the following structure  with evidence value with '_' value

"go" : [
            {
              "id" : "GO:0015629",
              "value" : {
                "project" : "UniProtKB",
                "term" : "C:actin cytoskeleton",
                "evidence" : "ECO_0000304"
              }
            }
branch cm_912_ontology_annotation_ecoId
es7 example: 20.02_target_912

**Comment by cmalangone** [comment]
PR approved by Miguel. Merged in master.

**Comment by mkarmona** [comment]
@cmalangone value has a list of elements and that is wrong as it should only have the triplet I have shown above. It has now

```json
          "go" : [
            {
              "id" : "GO:0005911",
              "value" : [
                {
                  "project" : "Ensembl",
                  "term" : "C:cell-cell junction",
                  "evidence" : "ECO_0000501"
                },
                {
                  "project" : "Ensembl",
                  "term" : "C:ciliary basal body",
                  "evidence" : "ECO_0000501"
                },
```

**Comment by d0choa** [comment]
Yes, this is important. The id `GO:0005911` is about [cell-cell junction](https://www.ebi.ac.uk/QuickGO/term/GO:0005911). It has nothing to do with `ciliary basal body`

**Comment by cmalangone** [comment]
Fixed in a new PR
https://github.com/opentargets/platform-etl-backend/pull/31
