### ISSUE TITLE
Ontology review: mental or behavioural disorder/brain disease classification

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#92]
@elipapa commented on [Fri Jan 12 2018](https://github.com/opentargets/roadmap/issues/117)

@gkos-bio commented on [Tue Mar 28 2017](https://github.com/opentargets/platform_semantic/issues/5)

mental or behavioural disorder is classified under other disease for some reason.
It should be at the same level as the other main categories
https://www.targetvalidation.org/disease/EFO_0000677

---

@ElaineMcA commented on [Mon Aug 13 2018](https://github.com/opentargets/roadmap/issues/117#issuecomment-412484454)

Check if resolved within EFO 3.

---

@afaulconbridge commented on [Mon Aug 13 2018](https://github.com/opentargets/roadmap/issues/117#issuecomment-412525679)

We do some re-arrangement of high level EFO diseases within OpenTargets, to make the high levels more presentable than the default organisation within EFO (see https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000408 ). So I think this is probably something to look at on our side, rather than within EFO 3 (though the relevant bits of code will need updating for EFO 3 anyway, but that's probably a separate, and bigger, issue).

---

@iandunham commented on [Mon Aug 13 2018](https://github.com/opentargets/roadmap/issues/117#issuecomment-412529324)

Simon Jupp is aware of our structure - the TAs, and would be willing to think about getting this cleaner for us

**Comment by afaulconbridge** [comment]
Issue #116 is the same problem (brain disease as other), therefore closing this issue.
