### ISSUE TITLE
Disease Profile Page

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#920]

**Comment by cmalangone** [comment]
Opened a specific issue 
#924

**Comment by cmalangone** [comment]
Currently mouse_phenotype index is created manually and the json file is just an input file to ETL
cat 20.06_gene-data.json | jq -r '{"id":.id,"phenotypes": [.mouse_phenotypes[]?] }|@json' > mouse_phenotypes.json

**Comment by andrewhercules** [comment]
Epic ticket closed as disease profile page ETL, GraphQL, and React UI all pushed to production
