### ISSUE TITLE
Tractability has to be either null or structured

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#922]
tractability section inside target structure has to be either

- null in the case no subtypes don't exist, both antibody and smallmolecule
- a structure containing both sub structures either null or the information belongs to it

**Comment by cmalangone** [comment]
Branch: cm_922_tractability_structure (PR to review)
Elasticsearch index: 20.02_target_922 

Example Ensembl ID
ENSG00000196115 : no info for tractability 
ENSG00000143727 : smallmolecule only
ENSG00000106541: antibody only
ENSG00000198216 : antibody and smallmolecule info.
