### ISSUE TITLE
Adverse Effects from safety in targets contains useless field and string pmid

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#923]
As an example section
```json
          "safety" : {
            "adverse_effects" : [
              {
                "unspecified_interaction_effects" : [ ],
                "references" : [
                  {
                    "pmid" : "28216264",
                    "ref_link" : "",
                    "ref_label" : "Lynch et al. (2017)"
                  }
                ],
```
the `unspecified_interaction_effects` is always null, so no

- [x] t sure it is a glich and therefore has to be remove or conversely is something we need to properly fix and re-capture the data we are losing
- [x] Also, the pubmed id needs to be converted to a number

**Comment by cmalangone** [comment]
Example GENE ID

ENSG00000142208 safety and adverse info
ENSG00000097007 safety info
ENSG00000274286 adverse info
ENSG00000225730 empty info

**Comment by cmalangone** [comment]
The code is solid in the sense that uses transform and if in order to avoid to lose data. 

branch: cm_923_adverse_events_safety
es7-mk: 20.02_target_923

PR: https://github.com/opentargets/platform-etl-backend/pull/26
