### ISSUE TITLE
Pumed IDs included in cancerbiomarkers have to numbers not stings

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#925]

**Comment by cmalangone** [comment]
This code changed two behaviours for source_pubmed and source_others
The field "sources_pubmed is renamed to "sourcesPubmed" and it is an array of long
If the values are not available -> the field "sourcesPubmed" is not present in the index.
 "sourcesPubmed" : [
            24622468,
            26859683
          ],
The field "source_others" changed name in "sourcesOther".
If the data are not available "sourcesOther" is not present in the index.

Branch: cm_925_change_type_df_field
Es7-mk example : 20.02_cancerbiomarker_925
PR: 
https://github.com/opentargets/platform-etl-backend/pull/new/cm_925_change_type_df_field

Example to check
target : ENSG00000198216
target : ENSG00000165699
