### ISSUE TITLE
Empty search result page need a consistent design style 

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#928]

**Comment by andrewhercules** [comment]
@mirandaio, based on the feedback in yesterday's front-end meeting, I have updated the design spec for the no search results/404 page - please see below.

![platform-rewrite-no-seach-results-v2](https://user-images.githubusercontent.com/7490258/77629709-d9737000-6f41-11ea-81cc-9d866f646f87.png)

I have sourced the icons from FontAwesome; however, please feel free to suggest alternatives.

- https://fontawesome.com/icons/exclamation-triangle?style=solid
- https://fontawesome.com/icons/question-circle?style=solid
- https://fontawesome.com/icons/envelope?style=solid
- https://fontawesome.com/icons/search-plus?style=solid

For the call-to-action circles below "You might also want to ...", please construct the following links:

- For the first documentation CTA, link to `https://docs.targetvalidation.org/getting-started/getting-started`
- For the second contact support CTA, construct a mailto: link to support@targetvalidation.org
- For the third suggest a target/disease/drug CTA, construct a mailto: link to support@targetvalidation.org with a subject line of "Suggest an entry for the Open Targets Platform"

**Comment by mirandaio** [comment]
Empty search results page has been implemented. It uses a component that is reused as well in 404 pages https://alpha--platform-app.netlify.app/search?q=asdf&page=1

**Comment by andrewhercules** [comment]
Looks good @mirandaio! My only suggestion - should we use the same search component on the homepage? Would that make it easier for the front-end team to maintain?

**Comment by mkarmona** [comment]
Grand!

**Comment by mirandaio** [comment]
Hi @andrewhercules, it is already using the same Search component as the homepage and the top right of the pages.
