### ISSUE TITLE
Update Gene2Phenotype evidence

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#931]
Gene2Phenotype evidence has not been updated since 19.11.

It would also be good to check if more of the information they provide could be used given that at the moment only the target and disease information is used. For example, the functional consequence in the column "mutation consequence" and the conficence level in "DDD category" could be useful.

**Comment by AsierGonzalez** [comment]
The file has been downloaded today (24/04/20) and uploaded to the Gene2Phenotype Google Bucket and the evidence has been generated for it. The only difference so far is that the functional consequence has been included in the `unique_association_fields`. This is not ideal and it should be reviewed but it was needed for a side project (ask @d0choa).

**Comment by d0choa** [comment]
Could you @AsierGonzalez revert the inclusion of the functional consequence in the `unique asociation_fields`. When reviewed, we'll include it in the relevant part of the evidence string.

**Comment by AsierGonzalez** [comment]
The evidence file was created again on 02-04-2020 without the functional consequence as requested.

**Comment by AsierGonzalez** [comment]
The parser has been updated and it will be merged via PR [#45](https://github.com/opentargets/evidence_datasource_parsers/pull/45)

**Comment by AsierGonzalez** [comment]
There are two additional tasks to complete the update:

- [ ] Review if the OMIM ids used to map the traits to EFO are reliable. It seems that some of them are not very accurate and a different approach may be needed.

- [ ] Check if any of the other three gene panels could be used to generate evidence. Currently only the DD panel is used and there are separate ones for cancer, eye  disorders and skin disorders.

**Comment by AsierGonzalez** [comment]
I'm closing this issuea as per @d0choa's suggestion as the update is done and I will create two separate tickets to work on the two tasks mentiones above.
