### ISSUE TITLE
Update Platform documentation to list new target safety data sources (eTOX, Tox21)

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#933]
Given the new experimental toxicity data from eTOX and Tox21, we will need to update the [Getting Started - Target Profile ](https://docs.targetvalidation.org/getting-started/getting-started/target-profile) section in the Platform documentation to reflect the new data sources and how it relates to the existing target safety data.

As we will now have 7 different target safety resources - with more planned for 20.06 - we should also create a separate page about target safety, similar to what we do for [target tractability](https://docs.targetvalidation.org/getting-started/target-tractability).

@PruMM, please collaborate with @deniseOme on these changes to the documentation so that we can link to these pages in the 20.04 release blog.

**Comment by deniseOme** [comment]
@andrewhercules @PruMM @d0choa, I've made a start with two google docs to be populated:

* [update short section on targets safety in the Target profile help doc](https://docs.google.com/document/d/1psYCO3sywRDngda6X_fAdXac9IOfm8B9rwdjViDtIJU/edit#heading=h.issh4678b4bi)
* [create brand new standalone help page with detailed information on target safety](https://docs.google.com/document/d/19ZhvS9EVAmibkoaGVdMS5D4_xNsJX8TcJXI85Vm1f1w/edit#)

Could you add/comment as appropriate please?

**Comment by deniseOme** [comment]
@andrewhercules @d0choa, could you please confirm the number of unique Ensembl gene IDs for safety data combining Eirini and Prudence curation efforts is 445 as per the draft https://docs.google.com/document/d/1psYCO3sywRDngda6X_fAdXac9IOfm8B9rwdjViDtIJU/edit#heading=h.pzcfnqeiofex

**Comment by AsierGonzalez** [comment]
According to the metrics there used to be 193 targets with safety data before and there are 439 now. I wonder if the discrepancy may be due to some ids being repeated or invalid?

**Comment by PruMM** [comment]
To avoid speculation and making a guess on it- I have asked Andrew to provide us with the final numbers as he has the full oversight on the new targets he created as well as having the final version of the file we worked on the last few days, he'll either upadre on here or pass the figure onto me and I can update on here

**Comment by andrewhercules** [comment]
@AsierGonzalez is correct - it's 439 targets that now have safety information.

- 305 targets have experimental toxicity data
- 122 targets have adverse effects data
- 73 targets have known safety risk data

There is some overlap as some targets will have multiple types of safety data (e.g. CDK2 has all three).

**Comment by PruMM** [comment]
thanks Andrew

**Comment by deniseOme** [comment]
@andrewhercules could you please provide the number of unique targets, with no overlap, irrespective of the source of safety data?

My counts give rise to 445 Ensembl gene IDs with (at least) one source of safety data. This list of unique Ensembl IDs is attached here (a combination of Eirini's and Prudence's work). This is not a guess work or speculation @PruMM; it's based on the spreadsheets in the Open Targets Platform google drive. But I could have had access to an outdated version, hence I'd like the confirmation. Many thanks.

[eirini_prudence_safety_ENS_unique.txt](https://github.com/opentargets/platform/files/4457080/eirini_prudence_safety_ENS_unique.txt)

**Comment by deniseOme** [comment]
@andrewhercules if you can provide the list of IDs themselves (not only the numbers), that'd be extremely useful and much appreciated. Ta.

**Comment by andrewhercules** [comment]
I have done an assessment of the file provided by @deniseOme, the file generated by @PruMM, and the original known safety risk and adverse effects files generated by Eirini. 

You can find the report on the team Google Drive in both [.csv](https://drive.google.com/open?id=1eZEdsrgN-FSofj4j48VGbvEM_SmJCDO-) and [Google Sheets](https://drive.google.com/open?id=1kVYCUBRIelJzRi6d4xdS9Dg2tomYO0N6cgqOP884rpI) formats. The report includes the Ensembl gene IDs and HGNC symbols used by the various input files. 

There are 447 entries in the report. However, 7 IDs on @deniseOme's original list do not appear in either the QC or production versions of the API:

- ENSG00000276996
- ENSG00000277273
- ENSG00000277292
- ENSG00000282076
- ENSG00000282928
- ENSG00000285479
- ENSG00000288516

I have reviewed each ID manually and the Platform does not have a target profile page for any of these IDs. I suspect that perhaps they were incomplete entries in earlier version of the safety file.

And so I can confirm that for 20.04, we will have target safety information on **439** targets.

If you would like to review the code that generated the report, you can find it on my [ot-data-utils/target-safety](https://github.com/andrewhercules/ot-data-utils/blob/master/target-safety/assess-target-safety-coverage.ipynb) repository.

**Comment by AsierGonzalez** [comment]
Having a quick look, those Ensembl ids seem to belong to genes in non-standard chromosomes which explains why they aren't in the gene index. The questions are why were those ids chosen and if their counterparts in standard chromosomes are included.

**Comment by andrewhercules** [comment]
Issue closed as initial changes made to Platform documentation on [target profile page and data sources](https://docs.targetvalidation.org/getting-started/getting-started/target-profile)
