### ISSUE TITLE
Pharmacovigilance widget pagination

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#936]
regarding adverse events widget, please, load everything but the widget has to show the rows packed by 25 rows each page otherwise it looks quite ugly and useless showing 150 rows. BONUS, if the `count < (2 * numberRowsPerPage)` then show all adverse events, otherwise paginate them as `numberRowsPerPage`. 
In the batch loading the data for the adverse events you can use 1k pagination.

**Comment by d0choa** [comment]
It was agreed that to increase consistency, the table should use whatever standard number of lines per page is used in other tables.
