### ISSUE TITLE
example POST requests in swagger UI are not valid

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#94]
@elipapa commented on [Mon Jul 16 2018](https://github.com/opentargets/rest_api/issues/164)

ht/ @deniseOme for highlighting this issue. 

The JSON body we offer as example suffers from multiple escape quotes:

For instance at https://api.opentargets.io/v3/platform/docs/swagger-ui#/filter/postEvidenceFilter
you get:

![image](https://user-images.githubusercontent.com/112610/42775287-e93ee332-892b-11e8-8778-bb425fcd6ebe.png)

and sending that request through gives a `500` internal server error as the body is not valid JSON.

Looking at the original swagger JSON we serve (at https://api.opentargets.io/v3/platform/swagger):

![image](https://user-images.githubusercontent.com/112610/42775209-bd7120da-892b-11e8-8c2e-475be9c7d3b3.png)

the `.schema.example` field is shown quoted and escaped, which shouldn't be.

The bug does not seem to be in swaggerUI. The error seems to be at the level of the flask app, which is processing and serving the body incorrectly. 

---

@ElaineMcA commented on [Tue Aug 28 2018](https://github.com/opentargets/rest_api/issues/164#issuecomment-416524593)

Discussed with @mkarmona .  Need to work on documenting contract for API and then bringing back completely into centralised documentation with appropriate examples (even if not executable examples as initially presented in swagger).

**Comment by AsierGonzalez** [comment]
All the POST examples in SwaggerUI semem to be affected by this. [The swagger/openAPI YAML file do not have the escapes](https://github.com/opentargets/rest_api/blob/master/app/static/openapi.template.yaml#L259) so there must be an issue somewhere else.

**Comment by AsierGonzalez** [comment]
This issue requires input from the back-end team, someone who knows how the rest API works and how the documentation is built. Do you know anything about this @mkarmona, @cmalangone or @afaulconbridge?

**Comment by mkarmona** [comment]
@deniseOme @AsierGonzalez , that does not work because it has the body already escaped so when you use curl it will be escaped twice again. so just pass a simple json like this and it will work

```json
{"target":["ENSG00000094755", "ENSG00000167207"], "disease":["EFO_0003767"]}
```

**Comment by AsierGonzalez** [comment]
I know that but what we are trying to do is understand why it is wrong in the first place as it affects all the POST examples in Swagger. I understand this can be controlled from the REST code so I wonder if you know where to look?

**Comment by AsierGonzalez** [comment]
After speaking with Miguel, these issue should be fixed by editing the examples directly in https://github.com/opentargets/rest_api/blob/master/app/static/openapi.template.yaml and deploying Swagger again.

**Comment by d0choa** [comment]
No work is expected in former API
