### ISSUE TITLE
Two entries for SOD2 in Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#941]
After reviewing the target tractability file for duplicates, I have noted that the Platform contains two entries for SOD2:

https://www.targetvalidation.org/target/ENSG00000285441 - 270 disease associations
https://www.targetvalidation.org/target/ENSG00000112096 - 462 disease associations

Can we please investigate the evidence strings and why there are two entries? 

As we are already working with submissions for 20.04, I have tagged this for review in the 20.06 release.

**Comment by AsierGonzalez** [comment]
These are two overlapping genes in the same strand with the same name:
<img width="954" alt="Screenshot 2020-03-26 at 09 51 49" src="https://user-images.githubusercontent.com/11410715/77633495-75ec4100-6f47-11ea-97ed-d78728ec15cd.png">

It seems that ENSG00000112096 is a more complete gene model given that it has multiple transcripts and associated UniProt accessions, whereas ENSG00000285441 has a single transcript an no UniProt accessions. We could ask Ensembl to review the gene models to make sure that they are really two independent genes.

In terms of evidence, both genes have evidence from data sources that provide evidence at the gene level but only ENSG00000112096 has evidence those using proteins, such as UniProt and text mining.

**Comment by AsierGonzalez** [comment]
Ensembl will merge the two SOD2 genes as they agree that ENSG00000285441 looks like a transcript of ENSG00000112096, with the latter being the kept id. The change will be effective in Ensembl 101 due to be released later this year, not the upcoming 100.

**Comment by andrewhercules** [comment]
Ticket closed as Ensembl has responded - see above.

Thanks @AsierGonzalez! 👍

**Comment by AsierGonzalez** [comment]
Note that, however, this will not be fixed in until Ensembl 101 is released and we use it, which could be 20.06 or, possibly, later.
