### ISSUE TITLE
Update links on /downloads page to include tractability, safety, and baseline expression files

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#942]
Details TBC

**Comment by LucaFumis** [comment]
I understand from https://github.com/opentargets/platform/issues/926 that the data files are ready for download. 
 1. Where do we add add these to the download page? Under the Apr 2020 heading after associations, evidence and target/disease lists?
 2. Do we link to the 20.04 folder in google cloud @cmalangone ? I see there are also 20.04.1 and .2

**Comment by andrewhercules** [comment]
Sorry @LucaFumis ... I meant to update this ticket but forgot about it.

Yes, could we please add these links to the download page under the April 2020 heading after the associations, evidence, and target/disease lists? For example, like the following:

- Association objects (2020-02, 765MB)
- Evidence objects (2020-02, 4.23GB)
- Target list: CSV (2020-02, 2.5MB), JSON (2020-02, 9MB)
- Disease list: CSV (2020-02, 832KB), JSON (2020-02, 1.7MB)
- Gene prioritisation data
  - Target tractability
  - Target safety
  - Baseline expression

For the baseline expression data, please link to https://github.com/opentargets/expression_analysis/blob/master/exp_summary_NormCounts_genes.txt

@cmalangone, could you please provide the appropriate link for the tractability and safety data once the release has been finalised?

**Comment by d0choa** [comment]
I would suggest to remove the `gene prioritisation data` level. Providing all files as an unnested list should be ok.

We will eventually provide more files as some of the activities in the BE progress (e.g. drug list, adverse events, ...). We can then evaluate what's the best nesting strategy.

**Comment by LucaFumis** [comment]
Fixed pending confirmation of final download folder and file sizes (I'll update these as a last thing).

**Comment by andrewhercules** [comment]
Issue closed as work completed as part of 20.04 release process
