### ISSUE TITLE
Align back-end for rewrite with new target safety data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#943]
The new experimental toxicity data will need to be added to the rewrite back-end so that the React application can display the data table - see #907

**Comment by cmalangone** [comment]
PR: https://github.com/opentargets/platform-etl-backend/pull/33

**Comment by cmalangone** [comment]
Test for safety data
Safety:
ENSG00000142208 all info
ENSG00000097007 safety info
ENSG00000274286 adverse info
ENSG00000225730 empty info

**Comment by andrewhercules** [comment]
Ticket closed as PR merged and any further updates will be tracked in #989
