### ISSUE TITLE
Align back-end for rewrite with new tractability data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#945]
The new tractability data will need to be added to the rewrite back-end so that the React application can display the data table - see #881 for the work done with the Angular application

**Comment by cmalangone** [comment]
PR: https://github.com/opentargets/platform-etl-backend/pull/33

**Comment by cmalangone** [comment]
Example TEST
Tractability
ENSG00000196115 : no info for tractability
ENSG00000143727 : smallmolecule only
ENSG00000106541: antibody only
ENSG00000198216 : antibody and smallmolecule info.
ENSG00000198400: other_modalities info

**Comment by andrewhercules** [comment]
Ticket reassigned to "Tractability widget" epic #897

**Comment by andrewhercules** [comment]
Ticket closed as PR merged and any further updates will be tracked in #989
