### ISSUE TITLE
handle more gracefully an empty query for POST besthitsearch

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#95]
@elipapa commented on [Thu May 17 2018](https://github.com/opentargets/rest_api/issues/160)

call to `bestHitSearch` (POST, http://api.opentargets.io/v3/platform/docs#operation/postBestHitSearch) fails when the query parameter `q` is an empty array…
successful POST call has `q: ["GLUR", "GRD1", "GSR"]`
error POST call has `q: []`

we should handle it more gracefully

**Comment by AsierGonzalez** [comment]
@ElaineMcA is this not more of an API design issue? It would require the function to control this situation.
I would be happy to look into it but I would need the developers (perhaps @mkarmona or @LucaFumis?) to guide me.
