### ISSUE TITLE
Update Platform (React version) and Genetics Portal footers due to partnership changes

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#955]
Due to changes in the consortium partnership that took effect on 1 April 2020, can we please make the following changes to the React version of the Platform and the Genetics Portal footers?

![Screenshot 2020-04-02 at 10 21 22](https://user-images.githubusercontent.com/7490258/78232140-ba3d8b00-74cb-11ea-94d1-b1eb9e590ed9.png)

1. Remove the Biogen text and link
2. Remove the Celgene text and link
3. Please add a text entry for Bristol Myers Squibb and please link to https://www.bms.com/

**Comment by mirandaio** [comment]
Also added Sanofi to the footer of the Genetics portal since it was missing there.
