### ISSUE TITLE
Update documentation references due to partnership changes

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#956]
Due to changes in the consortium partnership that took effect on 1 April 2020, can we please review the documentation for the Platform and Genetics Portal and make the following changes?

1. Remove all references and web links to Biogen
2. Replace all Celgene references and web links with Bristol Myers Squibb and link to their website at https://www.bms.com

**Comment by deniseOme** [comment]
We have no references to Biogen in the Open Targets Platform docs.

As per Open Targets Genetics docs, we had two instances referring to Biogen and Celgene:

* https://genetics-docs.opentargets.org/#our-partners
* https://genetics-docs.opentargets.org/#copyright

Biogen removed. Celgene changes to
