### ISSUE TITLE
Read TEPs from Google Spreadsheet

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#957]
Currently, the Target Enabling Packages (TEPs) shown in the target profile page of certain genes are [hard-coded in a javascript script in the webapp code base](https://github.com/opentargets/webapp/blob/master/app/src/services/teps-service.js). This is cumbersome because it means that the script has to be changed every time a new TEP needs to be added.

It has been decided that going forward, platform-input-support will read the TEPs from a [Google Spreadhseet](https://docs.google.com/spreadsheets/d/1pV06MTC-szlJRjlgG9rV6WW67r6Nxd9oAXfqZkrNVAU/edit#gid=0) similar to what is already done with the chemical probes and they will be added to the gene index.

**Comment by AsierGonzalez** [comment]
`Ensembl_id` added to spreadsheet following a conversation with @cmalangone. The values that are really needed are `Ensembl_id` and `Real_URL`, everything else is for tracking and debugging purposes.

**Comment by cmalangone** [comment]
Added TEP step in platform-input-support
The output file is used by the platform-etl-backend.
Added TEP info to the target step
