### ISSUE TITLE
Link to Open Targets Genetics in the evidence page not loading

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#959]
The genetic evidence for [SNCA in dementia](https://www.targetvalidation.org/evidence/ENSG00000145335/HP_0000726?view=sec:genetic_association), and its child [Lewis body dementia](https://www.targetvalidation.org/evidence/ENSG00000145335/EFO_0006792?view=sec:genetic_association) has one variant from Open Targets Genetics (OTG), i.e. rs7681440, which is on chr 4 (4_89835399_C_G).

When clicking on the Evidence source to be redirected to OTG, the new page does not load.

<img width="1161" alt="Screen Shot 2020-04-03 at 15 22 05" src="https://user-images.githubusercontent.com/6472381/78370695-e7b73100-75be-11ea-9b79-659e91996f28.png">

Looking at the trait in OTG i.e [GCST005276](https://genetics.opentargets.org/study/GCST005276), there is no variant located on chr 4 in the current release of OTG (it could have been there prior to March 2020). So based on OTG evidence, we can not associate synuclein alpha with dementia.

**Comment by d0choa** [comment]
I'm puzzled here. @mkarmona could you confirm this study was loaded as expected in the Portal BE?

**Comment by mkarmona** [comment]
@d0choa @deniseOme there is a bug of the frontend as the [API has information for it](https://tinyurl.com/v2ta6sk)

**Comment by mkarmona** [comment]
yes, there might be something [strange here](https://tinyurl.com/w2w7e43)

**Comment by d0choa** [comment]
Checking on recent releases, the offending issue is no longer there
