### ISSUE TITLE
Issues with proxy performance in production

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#963]
The production proxy is having issues (most of the times). The next query fails:
https://www.targetvalidation.org/proxy/rest.ensembl.org/lookup/id/ENSG00000142192?content-type=application/json

However, the same query works in QC:
https://platform-api-qc.opentargets.io/proxy/rest.ensembl.org/lookup/id/ENSG00000142192?content-type=application/json

@mkarmona suggests it might be related with either firewall rules or google load balance configuration

A few other problematic queries:
- [Structures](https://www.targetvalidation.org/proxy/www.ebi.ac.uk/pdbe/api/mappings/best_structures/P15056)
- [Gene tree](https://www.targetvalidation.org/proxy/rest.ensembl.org/homology/id/ENSG00000157764.json?format=full;sequence=none;type=all;target_taxon=9606;target_taxon=10090;target_taxon=10141;target_taxon=9544;target_taxon=9615;target_taxon=9986;target_taxon=10116;target_taxon=9823;target_taxon=8364;target_taxon=7955;target_taxon=9598;target_taxon=7227;target_taxon=6239)
- [Gene tree II ](https://www.targetvalidation.org/proxy/rest.ensembl.org/genetree/member/id/ENSG00000157764.json?sequence=none;aligned=0;prune_species=Homo_sapiens;prune_species=Mus_musculus;prune_species=Cavia_porcellus;prune_species=Macaca_mulatta;prune_species=Canis_lupus_familiaris;prune_species=Oryctolagus_cuniculus;prune_species=Rattus_norvegicus;prune_species=Sus_scrofa;prune_species=Xenopus_tropicalis;prune_species=Danio_rerio;prune_species=Pan_troglodytes;prune_species=Drosophila_melanogaster;prune_species=Caenorhabditis_elegans)

Other proxy calls work normally:

- [interactions](https://www.targetvalidation.org/proxy/www.omnipathdb.org/interactions?partners=P05067&format=json)

**Comment by mkarmona** [comment]
After further inspection of the firewall rules and internal VPC connections, the problem is related to a hang of the _nginx_ service. A **rolling replace** fixed the issue.
