### ISSUE TITLE
Adverse events file: changes the header field report_count to count or data_pipeline

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#966]
Adverse events file has the header 
chembl_id	critval	event	llr	report_count

the data pipeline raises an exception with report_count. It expected "count".
Change the header file or the data_pipeline.

@mkarmona : what do you prefer?

**Comment by mkarmona** [comment]
@cmalangone I guess we should stick to a more uniformly way of naming things when is possible. If we have the option to change so let's try to apply something like this (balanced between meaningful and keeping short)

```
event
report_count -> count
llr -> logLR
critval -> criticalValue
```
@cmalangone This has to be [changed here](https://github.com/opentargets/platform-etl-openfda-faers/blob/master/platformDataProcessFDAMonteCarlo.sc#L135)

Furthermore, this changes have to be propagated to [MrTarget pipeline too](https://github.com/opentargets/data_pipeline/)

**Comment by d0choa** [comment]
Please, keep in mind you will be affecting the 2 FE versions if endpoints change their name. Just a reminder to follow up on them if changes are implemented.

**Comment by mkarmona** [comment]
@d0choa I will only break the former one as for the new FE the api is already encapsualted. I am just talking about data output. See [here](https://github.com/opentargets/platform-api-beta/blob/mk-target/app/models/entities/AdverseEvent.scala#L14) and the GraphQL object will remain the same as it is, see [here](https://github.com/opentargets/platform-api-beta/blob/mk-target/app/models/entities/AdverseEvent.scala#L8).

**Comment by JarrodBaker** [comment]
I've changed it so that [report_count is now count](https://github.com/opentargets/platform-etl-openfda-faers/commit/f1414ee8a2c95edbb0fd5e3b73b11bff239527a4) and works with the existing data pipeline.  

Let me know if we want to make more significant renaming changes.

**Comment by cmalangone** [comment]
Thanks to @JarrodBaker to fixing the bug.
I keep this issue open and next release @JarrodBaker and I can try to follow @mkarmona indication.

**Comment by JarrodBaker** [comment]
Sounds like a plan!

**Comment by mkarmona** [comment]
@cmalangone careful with changes here that have to be in sync with the new API beta . Just to keep an eye on it

**Comment by JarrodBaker** [comment]
@mkarmona, @cmalangone   The commit above has not yet been merged into master as it implements Miguel's suggestion: 
event -> name
report_count -> count
llr -> logLR
critval -> criticalValue

I don't know if any of the renaming is going to break anything down-stream.

**Comment by mkarmona** [comment]
It is ok. Go for it @JarrodBaker

**Comment by andrewhercules** [comment]
Ticket closed as work merged into `master` of `etl-openfda-faers` repo

See https://github.com/opentargets/platform-etl-openfda-faers/pull/15 for more details
