### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by javfg** [opentargets/platform#979]
Bring all dependency libraries for the frontend to its latest version.

**Comment by javfg** [comment]
So far these are the main dep which have been upgraded to newest versions (including major versions):

```
dependencies:

@material-ui/core: ^3.9.3	         =>  @material-ui/core": "^4.9.10
@material-ui/icons: ^3.0.1	         =>  @material-ui/icons": "^4.9.1
@material-ui/lab: ^3.0.0-alpha.30	 =>  @material-ui/lab": ^4.0.0-alpha.49
graphql: ^14.0.2	                 =>  graphql: ^15.0.0
react-scripts: 2.1.5	                 =>  react-scripts: 3.4.1
react-helmet: ^5.2.0	                 =>  react-helmet: ^6.0.0
react-router-dom: 5.0.1	                 =>  react-router-dom": 5.1.2

dev-dependencies:

husky: ^1.1.3	                         =>  husky: ^4.2.5
lint-staged: ^8.0.4	                 =>  lint-staged": ^10.1.3
prettier": ^1.15.1	                 =>  prettier": ^2.0.4
```

All the widgets in the current __alpha__ rewrite branch are working. There are some font size problems, due to changes in the default font size in Material-UI.

**Comment by andrewhercules** [comment]
Ticket closed as dependencies have been updated and merged into `alpha`

Ticket created to update dependencies in Genetics Portal front-end - see https://github.com/opentargets/genetics/issues/430
