### ISSUE TITLE
Review mapping of Gene2Phenotype traits to EFO

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#980]
Currently the OMIM ids provided by G2P are used to map them to EFO using xrefs. There are two problems, one is that many entries do not have an OMIM id that can be used and the other is that some of them are not very accurate. I will have a look to see if a different approach may be needed.

**Comment by d0choa** [comment]
There is some interest to be able to map comprehensively the list of diseases to EFO. I'll generate a first template in the next days

**Comment by AsierGonzalez** [comment]
I reran the mapping in June because there was a bug in OnToma that was fixed in [version 0.0.14](https://github.com/opentargets/OnToma/commits/0.0.14). The input to map were `4,257` gene-disease associations that comprised `3,189` unique disease name - OMIM id pairs which yielded `4,391` mappings.

To make the review process easier, these mappings were divided into categories based on the confidence that they may be correct, summarised in the table below:

| Mapping source | Quality | Description | Action  | Complexity | Counts  |
| --- | --- | --- | --- | --- | --- |
| OMIM & EFO OBO | match | Mapped to the same EFO term using both the EFO-OMIM xrefs and checking names and synonyms in the EFO OBO file | Quick check in EFO, make sure that label makes sense and OMIM xref is in there | Low | 461 | 
| EFO OBO | match | Mapped to EFO checking the names and synonyms in the EFO OBO file | Quick check in EFO, pay attention to any OMIM xrefs | Low | 131 |
| OMIM & OT Zooma Mappings | match | Mapped to the same EFO term using both EFO-OMIM xrefs and the [OT Zooma mappings file](https://raw.githubusercontent.com/opentargets/platform_semantic/master/resources/zooma/cttv_indications_3.txt) | Quick check in EFO, watch for outdated mappings in OT file | Low-medium | 490 |
| OT Zooma Mappings  | match | Exact mapping available in [OT Zooma mapping file](https://raw.githubusercontent.com/opentargets/platform_semantic/master/resources/zooma/cttv_indications_3.txt)  | Quick check in EFO, watch for outdated mappings in OT file | Low-medium  | 87 |
| OMIM & Zooma API lookup  | match | Mapped to the same EFO term using both EFO-OMIM xrefs and the Zooma API | Quick check in EFO, if not convinced check what the source of the mapping is | Low-medium | 264 |
| Zooma API lookup  | match | Exact mapping found in the Zooma API | Quick check in EFO, if not convinced check what the source of the mapping is | Medium  | 80 |
| OMIM & OLS API EFO lookup  | match | Mapped to the same EFO term using both EFO-OMIM xrefs and the OLS API | Quick check in EFO | Low | 119 |
| OLS API EFO lookup  | match | Exact mapping found in the OLS API | Quick check in EFO, pay attention to any OMIM xrefs | Low medium  | 44 |
| OMIM  |  | Mapping to EFO based on EFO-OMIM xrefs only | Quick check in EFO and check if the term is mapped to another EFO term via any of the other methods above since xrefs can be quite promiscuous | Medium | 1,211 |
| OLS API ORDO exact lookup  | match | Mapped to ORDO/Orphanet term using OLS API | Check if in OT or if there are similar terms | Medium  | 13 |
| OMIM & OLS API EFO lookup  | fuzzy | Mapped to the same EFO term using both EFO-OMIM xrefs and the OLS API, but only partial match returned by the latter | Check if partial mapping valid | High | 363 |
| OLS API EFO lookup  | fuzzy | Partial match returned by OLS API | Check if valid | High | 1,081 |
|  |  | Seemingly unmapped terms | Check what they are | High | 47 |

I have started the review from the top of the table and I will record progress here.

**Comment by AsierGonzalez** [comment]
Mapping has been reviewed for the 461 diseases that are mapped to the same EFO term using EFO-OMIM xrefs and looking them up in the EFO OBO file. This is the breakdown of the mappings:
- X were accepted as they are
- Five need to be discussed with EFO because they are mapped to an obsolete ORDO term or because a more specific term is available in MONDO or because there are more than one equivalent terms.
- Two of them were kept despite there are better options based on the disease name. They have been considered the best mappings based on the gene reported by G2P.
- Three have been discarded because there are better mappings in EFO.

**Comment by AsierGonzalez** [comment]
According to conversations with Sarah Hunt, who leads the G2P development at EBI, in July 2020, they are having conversations about "standardising disease names and using OMIM names, where possible". However, note that "G2P curators don't consider current ontologies map all of the rare diseases they are dealing with to the right level of detail, so it probably won't be possible to find useful mappings for all names. We have discussed working with ontologies to improve this, but it would be a long term goal."

**Comment by iandunham** [comment]
Is it worth sharing our mappings with them?

**Comment by AsierGonzalez** [comment]
When we told her that we were working on the mappings she sounded a bit sceptical about it, that's when she mentioned that curators are not satisfied with current ontologies. We could probably contribute to what they are doing and provide some useful feedback but that would probably require some high-level talks with them.

**Comment by AsierGonzalez** [comment]
Given the slow progress in the manual mapping and that G2P might be doing some work in that area (see messages above) this work has been deprioritised. Instead, the G2P parser has been revamped to map the G2P disease names on the fly using OnToma (See [evidence_datasource_parsers/pull/48](https://github.com/opentargets/evidence_datasource_parsers/pull/48)). In a nutshell, the mapping algorithm works as follows:
- Exact matches to EFO are used directly.
- If the match comes from HP or ORDO the disease is searched in MONDO and if there is an exact match it is used. If not, the HP or ORDO term is used.
- If OnToma returns a fuzzy match it is ignore and MONDO is searched for exact matches.
- When no exact matches are found the disease is considered unmapped and it's recorded for follow up.

This algorithm may produce mappings to HP, ORDO or MONDO that are not part of EFO and, hence, are invalid for Open Targets. This is a deliverate design decission, which will allow to identify useful mappings not yet in EFO that could be imported, in particular MONDO terms.

**Comment by AsierGonzalez** [comment]
Although there are now more diseases to map, the new approach produces fewer mappings compared to the previous one based on EFO-OMIM xrefs. This is not surprising given that one OMIM id may be cross-referenced to many EFO ids and besides, the mapped EFO terms may have parent-child relationships, which is redundant. The new method only reports high-confidence matches and only one per input disease.

|  | 20.04/20.06 | 20.09 |
| --- | --- | --- |
| Distinct disease names to map | 2,296 | 3,224 |
| Distinct mappings | 1,482 | 1,352 |

A better metric to compare the previous and current mapping methods will be the number of diseases with evidence after ontology propagation performed by the pipeline.

**Comment by andrewhercules** [comment]
Ticket closed - released as part of 20.09

**Comment by d0choa** [comment]
There is a backlog of diseases that would require manual mapping, or a more sophisticated systematic approach.
They have not been prioritised, as some changes on the gene2phenotype-side might affect or obsolete some of these mappings.
However, gene2phenoype mapping will need to be reviewed in a few months time
