### ISSUE TITLE
Update 'dementia' related terms in EFO to help with disease-evidence consistency

### ISSUE THREAD

**Issue by smnorthen** [opentargets/platform#982]
Re-categorisation of dementia related terms in EFO (currently under phenotype) to the disease branch.

See: https://github.com/EBISPOT/efo/issues/764#issuecomment-616424893

**Comment by andrewhercules** [comment]
Ticket re-assigned to next release as https://github.com/EBISPOT/efo/issues/764#issuecomment-616424893 is still open and work is ongoing.

**Comment by andrewhercules** [comment]
Ticket re-assigned to 20.11 release, pending closure of https://github.com/EBISPOT/efo/issues/764#issuecomment-616424893.

**Comment by andrewhercules** [comment]
Ticket closed as https://github.com/EBISPOT/efo/issues/764 has been closed and integrated into EFO
