### ISSUE TITLE
Tractability contains double nested fields

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#985]
Asking for the target 
```
GET 20.04_target/_search
{
  "query": {
    "match": {
      "id.keyword": "ENSG00000091831"
    }
  }
}
```
the fields come double nested
![imagen.png](https://images.zenhubusercontent.com/58e5fe8e51aa2c30577a8b6a/79c4473d-b279-44ab-9883-daa25f1b0843)

**Comment by cmalangone** [comment]
Pushed branch 
cm_fix_985_tractability_contains_nested_fields

**Comment by mkarmona** [comment]
looks good the changes @cmalangone but why not PR with the fat-jar branch?

**Comment by cmalangone** [comment]
@mkarmona : I will add this fix in the fat-branch PR. :)

**Comment by cmalangone** [comment]
Done.
