### ISSUE TITLE
re-run open-fda pipeline

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#986]
https://github.com/opentargets/platform-etl-openfda-faers

**Comment by cmalangone** [comment]
Done.

**Comment by mkarmona** [comment]
@cmalangone I realised that the field used to show the number of reports is not the proper one. all computations are ok but wrong field selected at the end.

Problem - the total number of reports per event in total was selected but it should be the column `A` that contains the total number of reports per event for that specific drug. I am fixing it so I will create a PR so you can run just the final step of openfda the monte carlo one with a new code.

**Comment by cmalangone** [comment]
I regenerated the files for openfda index and loaded the data into the es7 20.04
