### ISSUE TITLE
include entity name for entity in the direct aggregated known drugs

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#987]
having

- target - approvedSymbol
- disease - label
- drug - prefName

**Comment by cmalangone** [comment]
Just change these lines

      val fds = df
        .where(col("private.datatype") === "known_drug")
        .withColumn("disease_id", col("disease.id"))
	.withColumn("label", col("disease.efo_info.label"))
        .withColumn("target_id", col("target.id"))
	.withColumn("approvedSymbol", col("target.gene_info.symbol"))
        .withColumn("drug_id", substring_index(col("drug.id"), "/", -1))
        .withColumn("prefName", col("drug.molecule_name"))

**Comment by cmalangone** [comment]
Added to platform-etl-backend
