### ISSUE TITLE
Drug index: searching for riluzole gives higher priority to SMA than ALS

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#99]
@gkos-bio commented on [Thu Jan 05 2017](https://github.com/opentargets/rest_api/issues/35)

https://www.targetvalidation.org/search?src=q:riluzole
unclear what the criteria is to rank between the four disease who seem to have the same evidence.. alphabetical? capitalization?

---

@elipapa commented on [Mon Nov 13 2017](https://github.com/opentargets/rest_api/issues/35#issuecomment-343914409)

it ranks by lucene scoring. 

we can consider boosting on a field, but a full test suite needs to be in effect to understand how much the _entire_ search behaviour is affected

---

@mkarmona commented on [Thu Mar 01 2018](https://github.com/opentargets/rest_api/issues/35#issuecomment-369768224)

![Pantallazo-2018-03-01 23-30-43.png](https://images.zenhubusercontent.com/58e5fe8e51aa2c30577a8b6a/641e9dc0-4b85-4d40-a845-4feb8ca1dad6)

---

@elipapa commented on [Fri Mar 02 2018](https://github.com/opentargets/rest_api/issues/35#issuecomment-369774318)

![image.png](https://images.zenhubusercontent.com/58ab643351aa2c305774f85f/e7037b63-c85e-4a25-a5d3-898fcab52084)

SMA should still come below ALS (more targets, but also more clinical relevance)

**Comment by ElaineMcA** [comment]
Will be considered as part of drug index efforts for 2019 roadmap - to be scheduled.

**Comment by d0choa** [comment]
To be evaluated, when #823 is done

**Comment by d0choa** [comment]
New search API will find riluzole as top hit. We'll explore the performance of the results
