### ISSUE TITLE
Sarch input box must query the API through timeouts not per typed key

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#991]
If I type `123456789` one character each other it asks that many times to the api

![imagen.png](https://images.zenhubusercontent.com/58e5fe8e51aa2c30577a8b6a/ab672882-ae15-4be5-95fd-d014b0d97145)

**Comment by javfg** [comment]
This will be solved by [#992](https://github.com/opentargets/platform/issues/992).

**Comment by andrewhercules** [comment]
Ticket closed as @javfg notes it will be covered in #992 which has been assigned to the next May The Fourth sprint
