### ISSUE TITLE
Publish new page on target safety in Platform documentation

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#995]
In the 20.04 release, we have added new target safety data from eTOX and Tox21. To ensure that users are aware of the new data and our approach to curating target safety information, we will develop a new, stand-alone [documentation page on target safety](https://docs.google.com/document/d/19ZhvS9EVAmibkoaGVdMS5D4_xNsJX8TcJXI85Vm1f1w/edit#). This will complement the changes to the [target profile documentation page](https://docs.targetvalidation.org/getting-started/getting-started/target-profile) made in #933.

The page is currently being drafted and reviewed and will be merged into docs once ready.

**Comment by deniseOme** [comment]
New page is now live and well: https://docs.targetvalidation.org/getting-started/target-safety
