### ISSUE TITLE
PharmGKB data formatting

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#997]
Formatting the PharmGKB data for potential ntegration into Open Targets
To pull out drug response data for target safety
- hold meetings with PharmGKB to discuss the cotrect usage and interpretation
- document rational for subcategorisation
- check with ChEMBL format  (Issue #969)

**Comment by andrewhercules** [comment]
Ticket closed as data curated by @PruMM has been uploaded to the [Open Targets team Google Drive](https://drive.google.com/drive/folders/1Y3blQcdnCjqpxWaE9_VtSmQYwCGjB_A4)
