### ISSUE TITLE
Targets Of Drugs with BlackBoxed Warning : Data Formatting

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#998]
Awaiting withdrawn information from ChEMBL publication (toxicity annotations)
Setting up a temporary format with a few examples of what is currently available

**Comment by andrewhercules** [comment]
Ticket closed as data curated by @PruMM has been uploaded to the [Open Targets team Google Drive](https://drive.google.com/drive/folders/1Y3blQcdnCjqpxWaE9_VtSmQYwCGjB_A4)
